import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_OPS: readonly StackPage[] = [
  topic(
    "nodejs",
    "Node.js",
    t("Node.js nədir?", "What is Node.js?", "Node.js nedir?", "ما هو Node.js؟", "Что такое Node.js?"),
    t(
      "Node.js JavaScript-i brauzerdən kənarda, serverdə və alətdə işlədən mühitdir. Öz-özlüyündə ayrıca proqramlaşdırma dili deyil.",
      "Node.js is a runtime that runs JavaScript outside the browser, on a server and in a tool. It is not a separate programming language by itself.",
      "Node.js, JavaScript’i tarayıcı dışında, sunucuda ve araçta çalıştıran ortamdır. Kendi başına ayrı bir programlama dili değildir.",
      "Node.js بيئة تشغّل JavaScript خارج المتصفح، على الخادم وفي أداة. ليست لغة برمجة مستقلة بذاتها.",
      "Node.js — среда, которая запускает JavaScript вне браузера, на сервере и в утилите. Сама по себе это не отдельный язык программирования.",
    ),
    t("Node.js nədir, Node server, npm, JavaScript runtime", "what is Node.js, Node server, npm, JavaScript runtime", "Node.js nedir, Node sunucu, npm", "ما هو Node.js, خادم Node, npm", "что такое Node.js, сервер Node, npm"),
    {
      what: t(
        "Node.js V8 mühərrikində JavaScript işlədir. Fayl, şəbəkə və proses buradan açılır. Paketlər npm ilə gəlir. Brauzerdəki JavaScript səhifəni dəyişir. Node isə terminalda və serverdə qalır.",
        "Node.js runs JavaScript on the V8 engine. Files, the network, and processes open from here. Packages come with npm. JavaScript in the browser changes the page. Node stays in the terminal and on the server.",
        "Node.js, JavaScript’i V8 motorunda çalıştırır. Dosya, ağ ve süreç buradan açılır. Paketler npm ile gelir. Tarayıcıdaki JavaScript sayfayı değiştirir. Node terminalde ve sunucuda kalır.",
        "يشغّل Node.js لغة JavaScript على محرك V8. من هنا تُفتح الملفات والشبكة والعمليات. الحزم تأتي مع npm. JavaScript في المتصفح تغيّر الصفحة. Node يبقى في الطرفية وعلى الخادم.",
        "Node.js запускает JavaScript на движке V8. Отсюда открываются файлы, сеть и процессы. Пакеты приходят через npm. JavaScript в браузере меняет страницу. Node остаётся в терминале и на сервере.",
      ),
      uses: t("Node.js API, yığım aləti və avtomatlaşdırma skripti üçündür.", "Node.js is for an API, a build tool, and an automation script.", "Node.js API, derleme aracı ve otomasyon betiği içindir.", "Node.js لواجهة API وأداة بناء وسكربت أتمتة.", "Node.js нужен для API, инструмента сборки и скрипта автоматизации."),
      useList: lines(
        ["JSON qaytaran HTTP server", "Frontend yığımı", "npm skripti", "Capacitor və CLI aləti"],
        ["An HTTP server that returns JSON", "A frontend build", "An npm script", "A Capacitor or CLI tool"],
        ["JSON dönen HTTP sunucu", "Frontend derlemesi", "npm betiği", "Capacitor ve CLI aracı"],
        ["خادم HTTP يعيد JSON", "بناء الواجهة", "سكربت npm", "أداة Capacitor أو سطر أوامر"],
        ["HTTP-сервер, который возвращает JSON", "Сборка фронтенда", "скрипт npm", "Инструмент Capacitor или CLI"],
      ),
      can: t(
        "Node ilə kiçik API, fayl oxuyan skript və brauzer paketini yığan əmr yazılır. Uzun CPU hesabı üçün birinci seçim deyil, çünki bir əsas axın üzərində qurulub. Gözləməli şəbəkə işində isə güclüdür.",
        "With Node you write a small API, a script that reads a file, and a command that builds a browser bundle. It is not the first choice for a long CPU calculation, because it is built on one main thread. It is strong for network work that waits.",
        "Node ile küçük API, dosya okuyan betik ve tarayıcı paketini derleyen komut yazılır. Uzun CPU hesabı için ilk seçim değildir, çünkü bir ana akış üzerine kuruludur. Beklemeli ağ işinde ise güçlüdür.",
        "بـ Node تكتب واجهة صغيرة وسكربتاً يقرأ ملفاً وأمراً يبني حزمة المتصفح. ليس الخيار الأول لحساب CPU طويل لأنه مبني على خيط رئيسي واحد. وهو قوي في عمل الشبكة الذي ينتظر.",
        "На Node пишут маленький API, скрипт, который читает файл, и команду, которая собирает браузерный пакет. Для долгого счёта на CPU это не первый выбор: среда стоит на одном главном потоке. В сетевой работе с ожиданием она сильна.",
      ),
      hard: t(
        "JavaScript bilən üçün giriş qısadır. Çətinlik asinxron kod, paket versiyası və callback yerinə promise axınıdır. node və npm ayrı əmrlərdir. Biri dil mühiti, digəri paket alətidir.",
        "If you know JavaScript, the entrance is short. The difficulty is async code, package versions, and the flow of promises instead of callbacks. node and npm are different commands. One is the runtime. The other is the package tool.",
        "JavaScript bilen için giriş kısadır. Zorluk asenkron kod, paket sürümü ve callback yerine promise akışıdır. node ve npm ayrı komutlardır. Biri dil ortamı, diğeri paket aracıdır.",
        "لمن يعرف JavaScript الدخول قصير. الصعوبة في الكود غير المتزامن وإصدارات الحزم وتدفق promise بدل callback. node وnpm أمران مختلفان. أحدهما بيئة اللغة والآخر أداة الحزم.",
        "Если знаешь JavaScript, вход короткий. Трудность в асинхронном коде, версиях пакетов и потоке promise вместо callback. node и npm — разные команды. Одна — среда, другая — инструмент пакетов.",
      ),
      balance: t(
        "Üstünlük: eyni dil brauzerdə və serverdə, paket sayı çoxdur. Məhdudiyyət: ağır hesabda zəifdir, köhnə paket təhlükəsizlik dəliyi gətirə bilər. Node versiyası layihənin engines sahəsində yazılmalıdır.",
        "Advantage: the same language in the browser and on the server, and a huge number of packages. Limit: it is weak at heavy calculation, and an old package can bring a security hole. The Node version should be written in the project’s engines field.",
        "Avantaj: aynı dil tarayıcıda ve sunucuda, paket sayısı çoktur. Sınır: ağır hesapta zayıftır, eski paket güvenlik deliği getirebilir. Node sürümü projenin engines alanına yazılmalıdır.",
        "الميزة: اللغة نفسها في المتصفح وعلى الخادم، وعدد الحزم كبير. الحد: ضعيف في الحساب الثقيل، وقد تجلب حزمة قديمة ثغرة. يجب كتابة إصدار Node في حقل engines للمشروع.",
        "Плюс: один язык в браузере и на сервере, пакетов очень много. Ограничение: слаб в тяжёлом счёте, старый пакет может принести дыру. Версию Node стоит записать в поле engines проекта.",
      ),
      ideas: t(
        "Modul require və ya import ilə açılır. process obyekti mühit dəyişənlərini göstərir. npm install paketi node_modules içinə qoyur.",
        "A module opens with require or import. The process object shows environment variables. npm install puts a package into node_modules.",
        "Modül require veya import ile açılır. process nesnesi ortam değişkenlerini gösterir. npm install paketi node_modules içine koyar.",
        "تُفتح الوحدة بـ require أو import. كائن process يُظهر متغيرات البيئة. npm install يضع الحزمة في node_modules.",
        "Модуль открывается через require или import. Объект process показывает переменные среды. npm install кладёт пакет в node_modules.",
      ),
      ideaList: lines(
        ["LTS buraxılışı server üçün seçilir", "package.json adı və skripti saxlayır", "npx paketi quraşdırmadan əmr işlədə bilər", "Node brauzer obyektini, məsələn window, vermir"],
        ["An LTS release is chosen for a server", "package.json keeps the name and the scripts", "npx can run a command without a global install", "Node does not give a browser object such as window"],
        ["LTS sürümü sunucu için seçilir", "package.json ad ve betiği tutar", "npx paketi kurmadan komut çalıştırabilir", "Node, window gibi bir tarayıcı nesnesi vermez"],
        ["إصدار LTS يُختار للخادم", "package.json يحفظ الاسم والسكربتات", "npx قد يشغّل أمراً بلا تثبيت عام", "Node لا يعطي كائن متصفح مثل window"],
        ["Для сервера берут выпуск LTS", "package.json хранит имя и скрипты", "npx может выполнить команду без глобальной установки", "Node не даёт объект браузера, например window"],
      ),
      sample: t("Bu əmr Node quraşdırılıbsa terminala bir sətir yazır.", "This command writes one line to the terminal if Node is installed.", "Bu komut Node kuruluysa terminale bir satır yazar.", "هذا الأمر يكتب سطراً في الطرفية إذا كان Node مثبّتاً.", "Эта команда пишет одну строку в терминал, если Node установлен."),
      code: `node -e "console.log('Hello')"`,
      faq: lines(
        ["Node.js dilidir? Xeyr. JavaScript-i işlədən mühitdir.", "Node və brauzer eyni kodu həmişə işlədir? Şəbəkə və fayl tərəfi fərqlidir. Ümumi dil eynidir.", "npm Node-un özüdürmü? Xeyr. Node ilə gələn paket alətidir."],
        ["Is Node.js a language? No. It is the runtime that runs JavaScript.", "Do Node and the browser always run the same code? The network and file side differ. The shared language is the same.", "Is npm Node itself? No. It is the package tool that comes with Node."],
        ["Node.js bir dil mi? Hayır. JavaScript’i çalıştıran ortamdır.", "Node ve tarayıcı aynı kodu her zaman çalıştırır mı? Ağ ve dosya tarafı farklıdır. Ortak dil aynıdır.", "npm Node’un kendisi mi? Hayır. Node ile gelen paket aracıdır."],
        ["هل Node.js لغة؟ لا. هي البيئة التي تشغّل JavaScript.", "هل يشغّل Node والمتصفح الكود نفسه دائماً؟ جانب الشبكة والملفات مختلف. اللغة المشتركة هي نفسها.", "هل npm هو Node نفسه؟ لا. هي أداة الحزم التي تأتي مع Node."],
        ["Node.js — это язык? Нет. Это среда, которая запускает JavaScript.", "Node и браузер всегда выполняют один код? Сторона сети и файлов различается. Общий язык один.", "npm — это сам Node? Нет. Это инструмент пакетов, который идёт с Node."],
      ),
    },
  ),
  topic(
    "android-sdk",
    "Android SDK",
    t("Android SDK nədir?", "What is Android SDK?", "Android SDK nedir?", "ما هي Android SDK؟", "Что такое Android SDK?"),
    t(
      "Android SDK telefon tətbiqi yığmaq üçün alət və kitabxana dəstidir. Öz-özlüyündə tətbiq deyil və proqramlaşdırma dili də deyil.",
      "The Android SDK is the set of tools and libraries used to build a phone app. It is not an app by itself, and it is not a programming language.",
      "Android SDK, telefon uygulaması derlemek için araç ve kütüphane takımıdır. Kendi başına bir uygulama değildir ve programlama dili de değildir.",
      "Android SDK مجموعة أدوات ومكتبات لبناء تطبيق هاتف. ليست تطبيقاً بذاتها وليست لغة برمجة.",
      "Android SDK — набор инструментов и библиотек, чтобы собрать приложение для телефона. Сам по себе это не приложение и не язык программирования.",
    ),
    t("Android SDK nədir, Android SDK alətləri, adb, compileSdk", "what is the Android SDK, Android SDK tools, adb, compileSdk", "Android SDK nedir, adb, compileSdk", "ما هي Android SDK, أدوات Android, adb", "что такое Android SDK, adb, compileSdk"),
    {
      what: t(
        "SDK platform API-sini, yığım alətlərini, emulatoru və adb-ni verir. Android Studio bunları SDK Manager ilə qurur. Tətbiqin kodu Kotlin və ya Java-dır. SDK həmin kodu telefonun başa düşdüyü pakete, APK və ya AAB-yə çevirən tərəfdir.",
        "The SDK gives the platform API, the build tools, the emulator, and adb. Android Studio installs them with SDK Manager. The app’s code is Kotlin or Java. The SDK is the side that turns that code into a package the phone understands, an APK or an AAB.",
        "SDK platform API’sini, derleme araçlarını, emülatörü ve adb’yi verir. Android Studio bunları SDK Manager ile kurar. Uygulamanın kodu Kotlin veya Java’dır. SDK o kodu telefonun anladığı pakete, APK veya AAB’ye çeviren taraftır.",
        "تعطي SDK واجهة المنصة وأدوات البناء والمحاكي وadb. يثبّتها Android Studio عبر SDK Manager. كود التطبيق Kotlin أو Java. SDK هي الجهة التي تحوّل ذلك الكود إلى حزمة يفهمها الهاتف، APK أو AAB.",
        "SDK даёт API платформы, инструменты сборки, эмулятор и adb. Android Studio ставит их через SDK Manager. Код приложения — Kotlin или Java. SDK — сторона, которая превращает этот код в пакет, понятный телефону: APK или AAB.",
      ),
      uses: t("SDK olmadan Android paketi yığılmır. Studio onu gizlədə bilər, amma yığım yenə ondan keçir.", "An Android package does not build without the SDK. Studio can hide it, but the build still goes through it.", "SDK olmadan Android paketi derlenmez. Studio onu gizleyebilir, ama derleme yine ondan geçer.", "بلا SDK لا تُبنى حزمة Android. قد تخفيها Studio، لكن البناء يمر بها.", "Без SDK пакет Android не собирается. Studio может его спрятать, но сборка всё равно идёт через него."),
      useList: lines(
        ["compileSdk ilə API səviyyəsini seçmək", "Emulatorda tətbiqi açmaq", "adb ilə telefona bağlanmaq", "Platform-tools və build-tools quraşdırmaq"],
        ["Choosing an API level with compileSdk", "Opening the app in an emulator", "Connecting a phone with adb", "Installing platform-tools and build-tools"],
        ["compileSdk ile API düzeyini seçmek", "Uygulamayı emülatörde açmak", "adb ile telefona bağlanmak", "platform-tools ve build-tools kurmak"],
        ["اختيار مستوى API بـ compileSdk", "فتح التطبيق في المحاكي", "وصل الهاتف بـ adb", "تثبيت platform-tools وbuild-tools"],
        ["Выбор уровня API через compileSdk", "Открытие приложения в эмуляторе", "Подключение телефона через adb", "Установка platform-tools и build-tools"],
      ),
      can: t(
        "SDK ilə tətbiqi emulatorda sınayır, telefona quraşdırır və log oxuyursan. O, dizaynı və məntiqi əvəz etmir. Dil öyrənmək ayrıca işdir. SDK yalnız hədəf platformanın alətidir.",
        "With the SDK you test the app in an emulator, install it on a phone, and read the log. It does not replace the design or the logic. Learning the language is a separate job. The SDK is only the tool of the target platform.",
        "SDK ile uygulamayı emülatörde denersin, telefona kurarsın ve günlüğü okursun. Tasarımın ve mantığın yerine geçmez. Dili öğrenmek ayrı iştir. SDK yalnız hedef platformanın aracıdır.",
        "بـ SDK تجرب التطبيق في المحاكي وتثبّته على الهاتف وتقرأ السجل. لا تغني عن التصميم أو المنطق. تعلّم اللغة عمل منفصل. SDK أداة المنصة المستهدفة فقط.",
        "С SDK приложение проверяют в эмуляторе, ставят на телефон и читают журнал. Она не заменяет дизайн и логику. Учить язык — отдельная работа. SDK только инструмент целевой платформы.",
      ),
      hard: t(
        "İlk quraşdırma uzundur, çünki platforma və emulator böyükdür. Çətinlik versiya uyğunluğudur: compileSdk, build-tools və Gradle eyni layihədə bir-birinə uyğun olmalıdır. Yol ANDROID_HOME ilə göstərilə bilər.",
        "The first install is long because the platform and the emulator are large. The difficulty is version fit: compileSdk, build-tools, and Gradle must agree in one project. The path can be pointed to with ANDROID_HOME.",
        "İlk kurulum uzundur, çünkü platforma ve emülatör büyüktür. Zorluk sürüm uyumudur: compileSdk, build-tools ve Gradle aynı projede birbirine uymalıdır. Yol ANDROID_HOME ile gösterilebilir.",
        "التثبيت الأول طويل لأن المنصة والمحاكي كبيران. الصعوبة في توافق الإصدار: يجب أن يتفق compileSdk وbuild-tools وGradle في مشروع واحد. يمكن الإشارة إلى المسار بـ ANDROID_HOME.",
        "Первая установка долгая, потому что платформа и эмулятор большие. Трудность в согласии версий: compileSdk, build-tools и Gradle должны сойтись в одном проекте. Путь можно указать через ANDROID_HOME.",
      ),
      balance: t(
        "Üstünlük: rəsmi alətdir, emulator və adb bir yerdədir. Məhdudiyyət: disk və vaxt aparır, lisenziya şərtləri qəbul edilməlidir. SDK-nı yeniləmək köhnə layihəni qəfil poza bilər.",
        "Advantage: it is the official tool, and the emulator and adb are together. Limit: it takes disk and time, and the license terms have to be accepted. Updating the SDK can suddenly break an old project.",
        "Avantaj: resmi araçtır, emülatör ve adb bir yerdedir. Sınır: disk ve zaman yer, lisans koşulları kabul edilmelidir. SDK’yı güncellemek eski projeyi birden bozabilir.",
        "الميزة: أداة رسمية، والمحاكي وadb معاً. الحد: يأخذ قرصاً ووقتاً، ويجب قبول شروط الترخيص. تحديث SDK قد يكسر مشروعاً قديماً فجأة.",
        "Плюс: это официальный инструмент, эмулятор и adb вместе. Ограничение: занимает диск и время, условия лицензии нужно принять. Обновление SDK может внезапно сломать старый проект.",
      ),
      ideas: t(
        "API səviyyəsi telefonun sistem versiyasına bağlıdır. Yüksək compileSdk yeni API açır. minSdk isə köhnə telefonu kəsib-kəsmədiyini deyir.",
        "The API level is tied to the phone’s system version. A high compileSdk opens a new API. minSdk says whether an old phone is cut off.",
        "API düzeyi telefonun sistem sürümüne bağlıdır. Yüksek compileSdk yeni API açar. minSdk eski telefonu kesip kesmediğini söyler.",
        "مستوى API مربوط بإصدار نظام الهاتف. compileSdk العالي يفتح API جديداً. minSdk يقول هل يُستبعد الهاتف القديم.",
        "Уровень API связан с версией системы телефона. Высокий compileSdk открывает новый API. minSdk говорит, отсекается ли старый телефон.",
      ),
      ideaList: lines(
        ["platform-tools içinə adb girir", "emulator virtual telefon açır", "build-tools paketi yığır", "SDK Manager çatışmayan paketi göstərir"],
        ["adb lives in platform-tools", "The emulator opens a virtual phone", "build-tools packs the app", "SDK Manager shows a missing package"],
        ["adb, platform-tools içindedir", "emulator sanal telefon açar", "build-tools paketi derler", "SDK Manager eksik paketi gösterir"],
        ["adb يعيش في platform-tools", "المحاكي يفتح هاتفاً افتراضياً", "build-tools تحزّم التطبيق", "SDK Manager يُظهر الحزمة الناقصة"],
        ["adb живёт в platform-tools", "эмулятор открывает виртуальный телефон", "build-tools упаковывает приложение", "SDK Manager показывает недостающий пакет"],
      ),
      sample: t("Bu əmrlər quraşdırılmış paketlərə və qoşulmuş telefona baxır. sdkmanager PATH-də olmalıdır.", "These commands look at installed packages and a connected phone. sdkmanager must be on PATH.", "Bu komutlar kurulu paketlere ve bağlı telefona bakar. sdkmanager PATH içinde olmalıdır.", "هذه الأوامر تنظر إلى الحزم المثبّتة والهاتف المتصل. يجب أن يكون sdkmanager في PATH.", "Эти команды смотрят установленные пакеты и подключённый телефон. sdkmanager должен быть в PATH."),
      code: `sdkmanager --list
adb devices`,
      faq: lines(
        ["Android SDK və Android Studio eynidir? Xeyr. Studio redaktordur. SDK yığım dəstidir.", "SDK bir dildir? Xeyr. Dil Kotlin və ya Java-dır.", "Hər layihə eyni SDK versiyasını istifadə edir? Xeyr. compileSdk layihənin içində yazılır."],
        ["Are the Android SDK and Android Studio the same? No. Studio is the editor. The SDK is the build set.", "Is the SDK a language? No. The language is Kotlin or Java.", "Does every project use the same SDK version? No. compileSdk is written inside the project."],
        ["Android SDK ve Android Studio aynı mı? Hayır. Studio düzenleyicidir. SDK derleme takımıdır.", "SDK bir dil mi? Hayır. Dil Kotlin veya Java’dır.", "Her proje aynı SDK sürümünü mü kullanır? Hayır. compileSdk projenin içinde yazılır."],
        ["هل Android SDK وAndroid Studio الشيء نفسه؟ لا. Studio المحرّر. SDK مجموعة البناء.", "هل SDK لغة؟ لا. اللغة Kotlin أو Java.", "هل يستخدم كل مشروع إصدار SDK نفسه؟ لا. يُكتب compileSdk داخل المشروع."],
        ["Android SDK и Android Studio — одно и то же? Нет. Studio — редактор. SDK — набор сборки.", "SDK — это язык? Нет. Язык — Kotlin или Java.", "Каждый проект использует одну версию SDK? Нет. compileSdk записан внутри проекта."],
      ),
    },
  ),
  topic(
    "gradle",
    "Gradle",
    t("Gradle nədir?", "What is Gradle?", "Gradle nedir?", "ما هو Gradle؟", "Что такое Gradle?"),
    t(
      "Gradle Java, Kotlin və Android layihəsini yığan alətdir. Asılılığı endirir, tapşırığı işlədir və paketi hazırlayır.",
      "Gradle is the tool that builds a Java, Kotlin, and Android project. It downloads a dependency, runs a task, and prepares the package.",
      "Gradle, Java, Kotlin ve Android projesini derleyen araçtır. Bağımlılığı indirir, görevi çalıştırır ve paketi hazırlar.",
      "Gradle أداة تبني مشروع Java وKotlin وAndroid. تنزّل الاعتمادية وتشغّل المهمة وتجهّز الحزمة.",
      "Gradle — инструмент, который собирает проект Java, Kotlin и Android. Он скачивает зависимость, выполняет задачу и готовит пакет.",
    ),
    t("Gradle nədir, Gradle Android, gradlew, Gradle Kotlin DSL", "what is Gradle, Gradle Android, gradlew, Gradle Kotlin DSL", "Gradle nedir, Gradle Android, gradlew", "ما هو Gradle, Gradle Android, gradlew", "что такое Gradle, Gradle Android, gradlew"),
    {
      what: t(
        "Gradle tapşırıqlar qrafıdır. Məsələn, tərtib et, test işlət, APK yığ. Təsvir build.gradle və ya build.gradle.kts faylındadır. Birincisi Groovy, ikincisi Kotlin DSL-dir. Layihə ilə gələn gradlew skripti hər kəsin eyni Gradle versiyasını işlətməsini saxlayır.",
        "Gradle is a graph of tasks. For example, compile, run tests, build an APK. The description is in build.gradle or build.gradle.kts. The first is the Groovy DSL. The second is the Kotlin DSL. The gradlew script that comes with the project keeps everyone on the same Gradle version.",
        "Gradle bir görev grafıdır. Örneğin derle, testi çalıştır, APK üret. Anlatım build.gradle veya build.gradle.kts dosyasındadır. Birincisi Groovy, ikincisi Kotlin DSL’dir. Projeyle gelen gradlew betiği herkesin aynı Gradle sürümünü kullanmasını sağlar.",
        "Gradle رسم بياني للمهام. مثلاً: صرّف، شغّل الاختبار، ابنِ APK. الوصف في build.gradle أو build.gradle.kts. الأول Groovy والثاني Kotlin DSL. سكربت gradlew الذي يأتي مع المشروع يُبقي الجميع على إصدار Gradle نفسه.",
        "Gradle — граф задач. Например: скомпилировать, запустить тесты, собрать APK. Описание в build.gradle или build.gradle.kts. Первый — Groovy DSL, второй — Kotlin DSL. Скрипт gradlew, который идёт с проектом, держит всех на одной версии Gradle.",
      ),
      uses: t("Android Studio düyməsinin arxasında çox vaxt Gradle tapşırığı durur.", "Behind an Android Studio button there is usually a Gradle task.", "Android Studio düğmesinin arkasında çoğu zaman bir Gradle görevi durur.", "خلف زر Android Studio تقف غالباً مهمة Gradle.", "За кнопкой Android Studio обычно стоит задача Gradle."),
      useList: lines(
        ["Asılı kitabxananı endirmək", "Debug və release paket yığmaq", "Testi işlətmək", "Versiya nömrəsini bir yerdə saxlamaq"],
        ["Downloading a library dependency", "Building a debug and a release package", "Running tests", "Keeping the version number in one place"],
        ["Bağımlı kütüphaneyi indirmek", "Debug ve release paketi üretmek", "Testi çalıştırmak", "Sürüm numarasını bir yerde tutmak"],
        ["تنزيل مكتبة معتمدة", "بناء حزمة debug وrelease", "تشغيل الاختبار", "حفظ رقم الإصدار في مكان واحد"],
        ["Скачивание зависимой библиотеки", "Сборка пакета debug и release", "Запуск тестов", "Номер версии в одном месте"],
      ),
      can: t(
        "Gradle ilə təkrarlanan yığım əmrini bir tapşırığa bağlayırsan. Android-də variant, imza və ProGuard da buradan keçir. O, tətbiqin ekranını yazmır. Yalnız yığır və yoxlayır.",
        "With Gradle you bind a repeated build command to one task. On Android the variant, the signature, and ProGuard also pass through here. It does not write the app’s screen. It only builds and checks.",
        "Gradle ile yinelenen derleme komutunu bir göreve bağlarsın. Android’de varyant, imza ve ProGuard da buradan geçer. Uygulamanın ekranını yazmaz. Yalnız derler ve denetler.",
        "بـ Gradle تربط أمر بناء متكرر بمهمة واحدة. في Android يمر من هنا المتغير والتوقيع وProGuard أيضاً. لا تكتب شاشة التطبيق. تبني وتفحص فقط.",
        "Gradle связывает повторяемую команду сборки с одной задачей. В Android вариант, подпись и ProGuard тоже проходят здесь. Экран приложения он не пишет. Только собирает и проверяет.",
      ),
      hard: t(
        "Kiçik fayl oxunur. Çətinlik plugin versiyası, keş və xəta mətninin uzunluğudur. Əmri həmişə gradlew ilə vermək, qlobal gradle ilə versiya dalaşını azaldır.",
        "A small file is readable. The difficulty is the plugin version, the cache, and the length of the error text. Always giving the command through gradlew reduces a version fight with a global gradle.",
        "Küçük dosya okunur. Zorluk eklenti sürümü, önbellek ve hata metninin uzunluğudur. Komutu her zaman gradlew ile vermek, genel gradle ile sürüm kavgasını azaltır.",
        "الملف الصغير يُقرأ. الصعوبة في إصدار الإضافة والذاكرة المؤقتة وطول نص الخطأ. إعطاء الأمر دائماً عبر gradlew يقلل نزاع الإصدار مع gradle العام.",
        "Маленький файл читается. Трудность в версии плагина, кэше и длине текста ошибки. Команда через gradlew уменьшает спор версий с глобальным gradle.",
      ),
      balance: t(
        "Üstünlük: Android-in rəsmi yığım yoludur, artımlı yığım vaxt qazandırır. Məhdudiyyət: ilk endirmə ağırdır, köhnə plugin yeni JDK ilə sınmaya bilər. Maven daha sadə XML istəyən Java layihəsində hələ durur.",
        "Advantage: it is Android’s official build path, and an incremental build saves time. Limit: the first download is heavy, and an old plugin may not agree with a new JDK. Maven still stands in a Java project that wants simpler XML.",
        "Avantaj: Android’in resmi derleme yoludur, artımlı derleme zaman kazandırır. Sınır: ilk indirme ağırdır, eski eklenti yeni JDK ile anlaşmayabilir. Daha sade XML isteyen Java projesinde Maven hâlâ durur.",
        "الميزة: طريق البناء الرسمي لـ Android، والبناء التدريجي يوفّر وقتاً. الحد: أول تنزيل ثقيل، وقد لا تتفق إضافة قديمة مع JDK جديد. Maven ما زال قائماً في مشروع Java يريد XML أبسط.",
        "Плюс: это официальный путь сборки Android, а добавочная сборка экономит время. Ограничение: первая загрузка тяжёлая, старый плагин может не сойтись с новым JDK. Maven ещё стоит в Java-проекте, которому нужен более простой XML.",
      ),
      ideas: t(
        "Plugin imkan əlavə edir. Məsələn, Android plugin. Asılılıq implementation ilə elan olunur. Keş eyni işi təkrar etməmək üçündür.",
        "A plugin adds a capability. For example, the Android plugin. A dependency is declared with implementation. The cache is there so the same work is not repeated.",
        "Eklenti olanak ekler. Örneğin Android eklentisi. Bağımlılık implementation ile bildirilir. Önbellek aynı işi yinelememek içindir.",
        "الإضافة تزيد قدرة. مثلاً إضافة Android. تُعلَن الاعتمادية بـ implementation. الذاكرة المؤقتة كي لا يُكرَّر العمل نفسه.",
        "Плагин добавляет возможность. Например, плагин Android. Зависимость объявляют через implementation. Кэш нужен, чтобы не повторять одну работу.",
      ),
      ideaList: lines(
        ["./gradlew layihənin öz Gradle-ını işlədir", "settings.gradle modulları sayır", "build artıq çıxışı saxlayır", "task öz əmrini əlavə edir"],
        ["./gradlew runs the project’s own Gradle", "settings.gradle lists the modules", "build stores the finished output", "A task adds your own command"],
        ["./gradlew projenin kendi Gradle’ını çalıştırır", "settings.gradle modülleri sayar", "build bitmiş çıktıyı saklar", "task kendi komutunu ekler"],
        ["./gradlew يشغّل Gradle الخاص بالمشروع", "settings.gradle يعدّ الوحدات", "build يحفظ الخرج الجاهز", "task تضيف أمرك"],
        ["./gradlew запускает собственный Gradle проекта", "settings.gradle перечисляет модули", "build хранит готовый вывод", "task добавляет свою команду"],
      ),
      sample: t("Bu əmr layihədə hansı tapşırıqların olduğunu göstərir. Windows-da əmr gradlew.bat tasks ola bilər.", "This command shows which tasks exist in the project. On Windows the command may be gradlew.bat tasks.", "Bu komut projede hangi görevlerin olduğunu gösterir. Windows’ta komut gradlew.bat tasks olabilir.", "هذا الأمر يُظهر أي المهام موجودة في المشروع. على Windows قد يكون الأمر gradlew.bat tasks.", "Эта команда показывает, какие задачи есть в проекте. В Windows команда может быть gradlew.bat tasks."),
      code: `./gradlew tasks`,
      faq: lines(
        ["Gradle bir dildir? Xeyr. Yığım alətidir. Təsvir Groovy və ya Kotlin ola bilər.", "gradlew nə üçündür? Hər geliştiricinin eyni versiyanı işlətməsi üçündür.", "Android-də Gradle-sız yığılır? Adi yol yox. Studio da Gradle çağırır."],
        ["Is Gradle a language? No. It is a build tool. The description can be Groovy or Kotlin.", "What is gradlew for? So every developer runs the same version.", "Does Android build without Gradle? Not on the ordinary path. Studio calls Gradle too."],
        ["Gradle bir dil mi? Hayır. Derleme aracıdır. Anlatım Groovy veya Kotlin olabilir.", "gradlew ne işe yarar? Her geliştiricinin aynı sürümü çalıştırması için.", "Android Gradle’sız derlenir mi? Olağan yol değil. Studio da Gradle çağırır."],
        ["هل Gradle لغة؟ لا. هي أداة بناء. الوصف قد يكون Groovy أو Kotlin.", "لمَ gradlew؟ كي يشغّل كل مطوّر الإصدار نفسه.", "هل يُبنى Android بلا Gradle؟ ليس في الطريق العادي. Studio تستدعي Gradle أيضاً."],
        ["Gradle — это язык? Нет. Это инструмент сборки. Описание может быть на Groovy или Kotlin.", "Зачем gradlew? Чтобы каждый разработчик запускал одну версию.", "Android собирается без Gradle? Не обычным путём. Studio тоже вызывает Gradle."],
      ),
    },
  ),
];
