import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_AGAIN: readonly StackPage[] = [
  topic(
    "composer",
    "Composer",
    t("Composer nədir?", "What is Composer?", "Composer nedir?", "ما هو Composer؟", "Что такое Composer?"),
    t(
      "Composer PHP paketini endirən alətdir. PHP-nin özü deyil. pip Python üçündür, npm Node üçündür, Composer isə PHP üçündür.",
      "Composer is the tool that downloads a PHP package. It is not PHP itself. pip is for Python, npm is for Node, and Composer is for PHP.",
      "Composer, PHP paketini indiren araçtır. PHP’nin kendisi değildir. pip Python içindir, npm Node içindir, Composer ise PHP içindir.",
      "Composer الأداة التي تنزّل حزمة PHP. ليس PHP نفسه. pip لـ Python وnpm لـ Node وComposer لـ PHP.",
      "Composer — инструмент, который скачивает пакет PHP. Это не сам PHP. pip для Python, npm для Node, а Composer для PHP.",
    ),
    t("Composer nədir, composer.json, PHP paket, Packagist", "what is Composer, composer.json, PHP package, Packagist", "Composer nedir, composer.json, PHP paket", "ما هو Composer, composer.json, Packagist", "что такое Composer, composer.json, Packagist"),
    {
      what: t(
        "Composer-i Nils Adermann və Jordi Boggiano yazılıb. İlk açıq buraxılış 2012-ci ildir. Paketlər əsasən Packagist reyestrində durur. composer.json layihənin paket siyahısıdır. composer.lock dəqiq versiyanı bağlayır. composer install həmin siyahını oxuyur və paketləri vendor qovluğuna yığır. PHP proqramı işlədir. Composer yalnız kitabxananı gətirir və özü səhifəni işlətmir.",
        "Nils Adermann and Jordi Boggiano wrote Composer. The first open release was in 2012. Packages mostly sit in the Packagist registry. composer.json is the project's package list. composer.lock pins the exact version. composer install reads that list and puts the packages in the vendor folder. PHP runs the program. Composer only brings the library and does not run the page itself.",
        "Composer’i Nils Adermann ve Jordi Boggiano yazdı. İlk açık yayın 2012’dir. Paketler çoğunlukla Packagist kaydında durur. composer.json projenin paket listesidir. composer.lock kesin sürümü bağlar. composer install o listeyi okur ve paketleri vendor klasörüne koyar. PHP programı çalıştırır. Composer yalnız kütüphaneyi getirir ve sayfayı kendi çalıştırmaz.",
        "كتب Composer كل من Nils Adermann وJordi Boggiano. أول إصدار مفتوح سنة 2012. الحزم تقف في الأغلب في سجل Packagist. composer.json قائمة حزم المشروع. composer.lock يثبت النسخة الدقيقة. composer install يقرأ تلك القائمة ويضع الحزم في مجلد vendor. PHP يشغّل البرنامج. Composer يجلب المكتبة فقط ولا يشغّل الصفحة بنفسه.",
        "Composer написали Nils Adermann и Jordi Boggiano. Первый открытый выпуск был в 2012 году. Пакеты в основном лежат в реестре Packagist. composer.json — список пакетов проекта. composer.lock закрепляет точную версию. composer install читает этот список и кладёт пакеты в папку vendor. PHP запускает программу. Composer только приносит библиотеку и сам страницу не запускает.",
      ),
      uses: t(
        "Composer PHP layihəsinə hazır kitabxana qurmaq və eyni siyahını başqa kompüterdə təkrarlamaq üçündür.",
        "Composer is for installing a ready library into a PHP project and repeating the same list on another computer.",
        "Composer PHP projesine hazır kütüphane kurmak ve aynı listeyi başka bilgisayarda tekrarlamak içindir.",
        "Composer لتثبيت مكتبة جاهزة في مشروع PHP وتكرار القائمة نفسها على حاسوب آخر.",
        "Composer нужен, чтобы поставить готовую библиотеку в проект PHP и повторить тот же список на другом компьютере.",
      ),
      useList: lines(
        ["Çərçivənin özünü bir əmrlə qurmaq", "Versiyanı composer.lock ilə saxlamaq", "vendor qovluğunda paketi ayırmaq", "Köhnə paketi yenisi ilə əvəz etmək"],
        ["Installing a framework itself with one command", "Keeping the version with composer.lock", "Separating the package in the vendor folder", "Replacing an old package with a newer one"],
        ["Çatının kendisini tek komutla kurmak", "Sürümü composer.lock ile tutmak", "Paketi vendor klasöründe ayırmak", "Eski paketi yenisiyle değiştirmek"],
        ["تثبيت الإطار نفسه بأمر واحد", "حفظ النسخة بـ composer.lock", "فصل الحزمة في مجلد vendor", "استبدال حزمة قديمة بأخرى أحدث"],
        ["Поставить сам фреймворк одной командой", "Хранить версию через composer.lock", "Отделить пакет в папке vendor", "Заменить старый пакет более новым"],
      ),
      can: t(
        "Composer ilə paket əlavə edir və siyahıdan qurursan. O, PHP-ni əvəz etmir. Tanımadığın paket öz kodunu sənin layihənin içinə qoyur. vendor qovluğunu repoya qoymaq adətən lazım deyil. Siyahı və lock faylı kifayətdir.",
        "With Composer you add a package and install from the list. It does not replace PHP. A package you do not know puts its own code inside your project. Putting the vendor folder in the repo is usually not needed. The list and the lock file are enough.",
        "Composer ile paket eklersin ve listeden kurarsın. PHP’nin yerine geçmez. Tanımadığın paket kendi kodunu senin projenin içine koyar. vendor klasörünü depoya koymak genellikle gerekmez. Liste ve kilit dosyası yeter.",
        "بـ Composer تضيف حزمة وتثبّت من القائمة. لا يحل محل PHP. حزمة لا تعرفها تضع كودها داخل مشروعك. وضع مجلد vendor في المستودع عادة غير لازم. القائمة وملف القفل يكفيان.",
        "Через Composer добавляют пакет и ставят из списка. Он не заменяет PHP. Незнакомый пакет кладёт свой код внутрь твоего проекта. Папку vendor в репозиторий обычно класть не нужно. Хватает списка и файла lock.",
      ),
      hard: t(
        "Bir paket qurmaq asandır. Çətinlik PHP versiyası və lock faylındadır. Paket sənin PHP-ndən yeni versiya istəyə bilər və quraşdırma dayanır. composer.lock-u atmaq sabah başqa versiya gətirə bilər. İki layihə eyni ümumi qovluğa yazırsa versiyalar qarışır.",
        "Installing one package is easy. The difficulty is the PHP version and the lock file. A package may ask for a newer PHP than yours, and the install stops. Throwing away composer.lock can bring another version tomorrow. If two projects write to the same shared folder, the versions mix.",
        "Bir paket kurmak kolaydır. Zorluk PHP sürümü ve kilit dosyasındadır. Paket senin PHP’nden yeni sürüm isteyebilir ve kurulum durur. composer.lock dosyasını atmak yarın başka sürüm getirebilir. İki proje aynı ortak klasöre yazarsa sürümler karışır.",
        "تثبيت حزمة واحدة سهل. الصعوبة في نسخة PHP وملف القفل. قد تطلب الحزمة PHP أحدث من الذي عندك فيتوقف التثبيت. رمي composer.lock قد يجلب نسخة أخرى غداً. إذا كتب مشروعان في المجلد المشترك نفسه اختلطت النسخ.",
        "Поставить один пакет легко. Трудность в версии PHP и в файле lock. Пакет может просить PHP новее твоего, и установка останавливается. Если выбросить composer.lock, завтра может прийти другая версия. Если два проекта пишут в одну общую папку, версии смешиваются.",
      ),
      balance: t(
        "Üstünlük: kitabxana təkrar yazılmır, siyahı bir faylda durur, eyni quraşdırma başqa maşında təkrarlanır. Məhdudiyyət: vendor böyüyür. Hər kiçik iş üçün paket lazım deyil. Composer pip və npm deyil.",
        "Advantage: a library is not rewritten, the list stays in one file, and the same install repeats on another machine. Limit: vendor grows. Not every small job needs a package. Composer is not pip and it is not npm.",
        "Avantaj: kütüphane yeniden yazılmaz, liste bir dosyada durur, aynı kurulum başka makinede tekrarlanır. Sınır: vendor büyür. Her küçük iş için paket gerekmez. Composer, pip ve npm değildir.",
        "الميزة: لا تُعاد كتابة المكتبة والقائمة تبقى في ملف واحد والتثبيت نفسه يتكرر على جهاز آخر. الحد: vendor يكبر. ليس كل عمل صغير يحتاج حزمة. Composer ليس pip وليس npm.",
        "Плюс: библиотеку не переписывают, список лежит в одном файле, та же установка повторяется на другой машине. Ограничение: vendor растёт. Не каждой мелкой работе нужен пакет. Composer — это не pip и не npm.",
      ),
      ideas: t(
        "Paketin adı və versiyası var. composer.json siyahıdır. vendor endirilən faylların yeridir.",
        "A package has a name and a version. composer.json is the list. vendor is the place of the downloaded files.",
        "Paketin adı ve sürümü vardır. composer.json listedir. vendor indirilen dosyaların yeridir.",
        "للحزمة اسم ونسخة. composer.json القائمة. vendor مكان الملفات المنزّلة.",
        "У пакета есть имя и версия. composer.json — список. vendor — место скачанных файлов.",
      ),
      ideaList: lines(
        ["composer.json siyahını saxlayır", "composer.lock versiyanı bağlayır", "vendor paketlərin qovluğudur", "Packagist ümumi reyestrdir"],
        ["composer.json keeps the list", "composer.lock pins the version", "vendor is the packages' folder", "Packagist is the shared registry"],
        ["composer.json listeyi tutar", "composer.lock sürümü bağlar", "vendor paketlerin klasörüdür", "Packagist ortak kayıttır"],
        ["composer.json يحفظ القائمة", "composer.lock يثبت النسخة", "vendor مجلد الحزم", "Packagist السجل المشترك"],
        ["composer.json хранит список", "composer.lock закрепляет версию", "vendor — папка пакетов", "Packagist — общий реестр"],
      ),
      sample: t(
        "Bu əmr siyahıdakı paketləri vendor qovluğuna qurur. PHP proqramını özü yazmır.",
        "This command installs the packages from the list into the vendor folder. It does not write the PHP program itself.",
        "Bu komut listedeki paketleri vendor klasörüne kurar. PHP programını kendi yazmaz.",
        "هذا الأمر يثبّت حزم القائمة في مجلد vendor. لا يكتب برنامج PHP نفسه.",
        "Эта команда ставит пакеты из списка в папку vendor. Саму программу на PHP она не пишет.",
      ),
      code: `composer install`,
      faq: lines(
        ["Composer və PHP eynidir? Xeyr. PHP proqramı işlədir. Composer kitabxananı gətirir.", "Composer, pip və npm eynidir? İş oxşardır, alət ayrıdır. Composer PHP üçündür.", "vendor qovluğu reyestrdə durmalıdır? Adətən yox. Siyahı və lock faylı durur, paketlər quraşdırma zamanı gəlir."],
        ["Are Composer and PHP the same? No. PHP runs the program. Composer brings the library.", "Are Composer, pip, and npm the same? The job is similar, the tool is separate. Composer is for PHP.", "Should the vendor folder stay in the repo? Usually no. The list and the lock file stay, and the packages arrive at install time."],
        ["Composer ve PHP aynı mı? Hayır. PHP programı çalıştırır. Composer kütüphaneyi getirir.", "Composer, pip ve npm aynı mı? İş benzerdir, araç ayrıdır. Composer PHP içindir.", "vendor klasörü depoda durmalı mı? Genellikle hayır. Liste ve kilit dosyası durur, paketler kurulumda gelir."],
        ["هل Composer وPHP الشيء نفسه؟ لا. PHP يشغّل البرنامج. Composer يجلب المكتبة.", "هل Composer وpip وnpm الشيء نفسه؟ العمل قريب والأداة منفصلة. Composer لـ PHP.", "هل يبقى مجلد vendor في المستودع؟ عادة لا. القائمة وملف القفل يبقيان والحزم تصل عند التثبيت."],
        ["Composer и PHP — одно и то же? Нет. PHP запускает программу. Composer приносит библиотеку.", "Composer, pip и npm — одно и то же? Работа похожа, инструмент отдельный. Composer для PHP.", "Папка vendor должна лежать в репозитории? Обычно нет. Остаются список и файл lock, а пакеты приходят при установке."],
      ),
    },
  ),
  topic(
    "cargo",
    "Cargo",
    t("Cargo nədir?", "What is Cargo?", "Cargo nedir?", "ما هو Cargo؟", "Что такое Cargo?"),
    t(
      "Cargo Rust paketini gətirən və proqramı quran alətdir. Rust dilinin özü deyil. Kompilyator rustc-dir. Cargo onu çağırır.",
      "Cargo is the tool that brings a Rust package and builds the program. It is not the Rust language itself. The compiler is rustc. Cargo calls it.",
      "Cargo, Rust paketini getiren ve programı kuran araçtır. Rust dilinin kendisi değildir. Derleyici rustc’dir. Cargo onu çağırır.",
      "Cargo الأداة التي تجلب حزمة Rust وتبني البرنامج. ليست لغة Rust نفسها. المترجم هو rustc. Cargo يستدعيه.",
      "Cargo — инструмент, который приносит пакет Rust и собирает программу. Это не сам язык Rust. Компилятор — rustc. Cargo его вызывает.",
    ),
    t("Cargo nədir, Cargo.toml, Rust paket, crates.io", "what is Cargo, Cargo.toml, Rust package, crates.io", "Cargo nedir, Cargo.toml, Rust paket", "ما هو Cargo, Cargo.toml, crates.io", "что такое Cargo, Cargo.toml, crates.io"),
    {
      what: t(
        "Cargo Rust-un rəsmi qurma və paket alətidir. 2014-cü ildə açıq işlənməyə başlayıb. Rəsmi Rust quraşdırması onu rustc ilə birlikdə gətirir. Paketlər crates.io reyestrində durur. Cargo.toml layihənin adını və paket siyahısını saxlayır. Cargo.lock dəqiq versiyanı bağlayır. cargo build proqramı qurur. cargo run qurulmuş proqramı işə salır. Rust kodunu rustc maşın koduna çevirir. Cargo həmin addımları sənin yerinə sıraya qoyur.",
        "Cargo is Rust's official build and package tool. Open work on it began in 2014. The official Rust install brings it together with rustc. Packages sit in the crates.io registry. Cargo.toml keeps the project's name and the package list. Cargo.lock pins the exact version. cargo build builds the program. cargo run starts the built program. rustc turns Rust code into machine code. Cargo lines those steps up for you.",
        "Cargo, Rust’un resmi kurma ve paket aracıdır. Açık çalışma 2014’te başladı. Resmi Rust kurulumu onu rustc ile birlikte getirir. Paketler crates.io kaydında durur. Cargo.toml projenin adını ve paket listesini tutar. Cargo.lock kesin sürümü bağlar. cargo build programı kurar. cargo run kurulan programı başlatır. Rust kodunu rustc makine koduna çevirir. Cargo o adımları senin yerine sıraya koyar.",
        "Cargo أداة البناء والحزم الرسمية لـ Rust. بدأ العمل المفتوح عليه سنة 2014. تثبيت Rust الرسمي يأتي به مع rustc. الحزم تقف في سجل crates.io. Cargo.toml يحفظ اسم المشروع وقائمة الحزم. Cargo.lock يثبت النسخة الدقيقة. cargo build يبني البرنامج. cargo run يشغّل البرنامج المبني. rustc يحوّل كود Rust إلى كود الآلة. Cargo يرتب تلك الخطوات عنك.",
        "Cargo — официальный инструмент сборки и пакетов Rust. Открытая работа над ним началась в 2014 году. Официальная установка Rust приносит его вместе с rustc. Пакеты лежат в реестре crates.io. Cargo.toml хранит имя проекта и список пакетов. Cargo.lock закрепляет точную версию. cargo build собирает программу. cargo run запускает собранную программу. rustc переводит код Rust в машинный код. Cargo выстраивает эти шаги за тебя.",
      ),
      uses: t(
        "Cargo yeni Rust layihəsi açmaq, kitabxana əlavə etmək və proqramı bir əmrlə qurmaq üçündür.",
        "Cargo is for opening a new Rust project, adding a library, and building the program with one command.",
        "Cargo yeni bir Rust projesi açmak, kütüphane eklemek ve programı tek komutla kurmak içindir.",
        "Cargo لفتح مشروع Rust جديد وإضافة مكتبة وبناء البرنامج بأمر واحد.",
        "Cargo нужен, чтобы открыть новый проект Rust, добавить библиотеку и собрать программу одной командой.",
      ),
      useList: lines(
        ["Boş layihəni cargo new ilə açmaq", "Kitabxananı Cargo.toml-a yazmaq", "Proqramı cargo build ilə qurmaq", "Testi cargo test ilə işlətmək"],
        ["Opening an empty project with cargo new", "Writing a library into Cargo.toml", "Building the program with cargo build", "Running the test with cargo test"],
        ["Boş projeyi cargo new ile açmak", "Kütüphaneyi Cargo.toml içine yazmak", "Programı cargo build ile kurmak", "Testi cargo test ile çalıştırmak"],
        ["فتح مشروع فارغ بـ cargo new", "كتابة مكتبة في Cargo.toml", "بناء البرنامج بـ cargo build", "تشغيل الاختبار بـ cargo test"],
        ["Открыть пустой проект через cargo new", "Записать библиотеку в Cargo.toml", "Собрать программу через cargo build", "Запустить тест через cargo test"],
      ),
      can: t(
        "Cargo ilə asılılığı endirir, kodu yoxlayır və hazır proqramı target qovluğuna qoyursan. O, Rust dilinin qaydasını dəyişmir. Xətanı kompilyator deyir. Cargo həmin xətanı sənə göstərir. Tanımadığın paket crates.io-dan gələ bilər və onun kodu sənin proqramına qarışır.",
        "With Cargo you download a dependency, check the code, and put the finished program in the target folder. It does not change the rules of the Rust language. The compiler says the error. Cargo shows that error to you. A package you do not know can come from crates.io, and its code mixes into your program.",
        "Cargo ile bağımlılığı indirir, kodu denetler ve biten programı target klasörüne koyarsın. Rust dilinin kuralını değiştirmez. Hatayı derleyici söyler. Cargo o hatayı sana gösterir. Tanımadığın paket crates.io’dan gelebilir ve onun kodu senin programına karışır.",
        "بـ Cargo تنزّل اعتماداً وتفحص الكود وتضع البرنامج الجاهز في مجلد target. هو لا يغيّر قواعد لغة Rust. المترجم يقول الخطأ. Cargo يريك ذلك الخطأ. حزمة لا تعرفها قد تأتي من crates.io وكودها يختلط ببرنامجك.",
        "Через Cargo скачивают зависимость, проверяют код и кладут готовую программу в папку target. Правил языка Rust он не меняет. Ошибку говорит компилятор. Cargo показывает тебе эту ошибку. Незнакомый пакет может прийти с crates.io, и его код вмешивается в твою программу.",
      ),
      hard: t(
        "İlk layihəni açmaq asandır. Çətinlik versiya və qurma vaxtındadır. Paket başqa paket də gətirir. Onlardan biri sənin Rust versiyandan yenidirsə qurma dayanır. Cargo.lock-u proqramda saxlamaq eyni nəticə üçündür. Kitabxanada isə onu hər dəfə bağlamaq eyni məcburiyyət deyil. target qovluğu böyüyür.",
        "Opening the first project is easy. The difficulty is the version and the build time. A package also brings another package. If one of them is newer than your Rust, the build stops. Keeping Cargo.lock in a program is for the same result. In a library, pinning it every time is not the same requirement. The target folder grows.",
        "İlk projeyi açmak kolaydır. Zorluk sürüm ve kurma süresindedir. Paket başka paket de getirir. Biri senin Rust sürümünden yeniyse kurma durur. Cargo.lock dosyasını programda tutmak aynı sonuç içindir. Kütüphanede onu her sefer bağlamak aynı zorunluluk değildir. target klasörü büyür.",
        "فتح المشروع الأول سهل. الصعوبة في النسخة ومدة البناء. الحزمة تجلب حزمة أخرى أيضاً. إذا كانت إحداها أحدث من نسخة Rust عندك يتوقف البناء. إبقاء Cargo.lock في البرنامج للنتيجة نفسها. في المكتبة تثبيته كل مرة ليس الشرط نفسه. مجلد target يكبر.",
        "Открыть первый проект легко. Трудность в версии и во времени сборки. Пакет приносит и другой пакет. Если один новее твоего Rust, сборка останавливается. Cargo.lock в программе держат ради того же результата. В библиотеке закреплять его каждый раз — не то же требование. Папка target растёт.",
      ),
      balance: t(
        "Üstünlük: qurma, test və paket bir əmrdədir, versiya bir faylda durur. Məhdudiyyət: ilk qurma uzun çəkə bilər. Cargo rustc deyil və pip deyil. O, Rust layihəsinin alətidir.",
        "Advantage: build, test, and package sit in one command, and the version stays in one file. Limit: the first build can take a long time. Cargo is not rustc and it is not pip. It is the tool of a Rust project.",
        "Avantaj: kurma, test ve paket bir komuttadır, sürüm bir dosyada durur. Sınır: ilk kurma uzun sürebilir. Cargo, rustc değildir ve pip değildir. Rust projesinin aracıdır.",
        "الميزة: البناء والاختبار والحزمة في أمر واحد والنسخة تبقى في ملف واحد. الحد: البناء الأول قد يطول. Cargo ليس rustc وليس pip. هو أداة مشروع Rust.",
        "Плюс: сборка, тест и пакет в одной команде, версия лежит в одном файле. Ограничение: первая сборка может идти долго. Cargo — не rustc и не pip. Это инструмент проекта Rust.",
      ),
      ideas: t(
        "Crate paketin adıdır. Cargo.toml siyahıdır. rustc isə kodu çevirən kompilyatordur.",
        "A crate is the name of a package. Cargo.toml is the list. rustc is the compiler that translates the code.",
        "Crate paketin adıdır. Cargo.toml listedir. rustc ise kodu çeviren derleyicidir.",
        "Crate اسم الحزمة. Cargo.toml القائمة. rustc المترجم الذي يحوّل الكود.",
        "Crate — имя пакета. Cargo.toml — список. rustc — компилятор, который переводит код.",
      ),
      ideaList: lines(
        ["cargo new layihə açır", "cargo build proqramı qurur", "Cargo.lock versiyanı saxlayır", "crates.io paketlərin reyestridir"],
        ["cargo new opens a project", "cargo build builds the program", "Cargo.lock keeps the version", "crates.io is the registry of packages"],
        ["cargo new proje açar", "cargo build programı kurar", "Cargo.lock sürümü tutar", "crates.io paketlerin kaydıdır"],
        ["cargo new يفتح مشروعاً", "cargo build يبني البرنامج", "Cargo.lock يحفظ النسخة", "crates.io سجل الحزم"],
        ["cargo new открывает проект", "cargo build собирает программу", "Cargo.lock хранит версию", "crates.io — реестр пакетов"],
      ),
      sample: t(
        "Bu əmr hazırkı qovluqdakı Rust layihəsini qurur. Kodu özü yazmır.",
        "This command builds the Rust project in the current folder. It does not write the code itself.",
        "Bu komut bulunduğun klasördeki Rust projesini kurar. Kodu kendi yazmaz.",
        "هذا الأمر يبني مشروع Rust في المجلد الحالي. لا يكتب الكود نفسه.",
        "Эта команда собирает проект Rust в текущей папке. Сам код она не пишет.",
      ),
      code: `cargo build`,
      faq: lines(
        ["Cargo və Rust eynidir? Xeyr. Rust dildir. rustc kompilyatordur. Cargo paketi gətirir və qurmağı sıraya qoyur.", "Cargo və pip eynidir? İşin bir hissəsi oxşardır. Cargo Rust üçündür və proqramı da qurur. pip yalnız Python paketini qurar.", "Cargo.toml paketin özüdür? Xeyr. O, ad və siyahıdır. Paketin kodu ayrıca fayldadır."],
        ["Are Cargo and Rust the same? No. Rust is the language. rustc is the compiler. Cargo brings the package and lines up the build.", "Are Cargo and pip the same? Part of the job is similar. Cargo is for Rust and it also builds the program. pip only installs a Python package.", "Is Cargo.toml the package itself? No. It is the name and the list. The package's code is in a separate file."],
        ["Cargo ve Rust aynı mı? Hayır. Rust dildir. rustc derleyicidir. Cargo paketi getirir ve kurmayı sıraya koyar.", "Cargo ve pip aynı mı? İşin bir parçası benzerdir. Cargo Rust içindir ve programı da kurar. pip yalnız Python paketini kurar.", "Cargo.toml paketin kendisi mi? Hayır. O, ad ve listedir. Paketin kodu ayrı dosyadadır."],
        ["هل Cargo وRust الشيء نفسه؟ لا. Rust اللغة. rustc المترجم. Cargo يجلب الحزمة ويرتب البناء.", "هل Cargo وpip الشيء نفسه؟ جزء من العمل قريب. Cargo لـ Rust وهو يبني البرنامج أيضاً. pip يثبّت حزمة Python فقط.", "هل Cargo.toml هو الحزمة نفسها؟ لا. هو الاسم والقائمة. كود الحزمة في ملف منفصل."],
        ["Cargo и Rust — одно и то же? Нет. Rust — язык. rustc — компилятор. Cargo приносит пакет и выстраивает сборку.", "Cargo и pip — одно и то же? Часть работы похожа. Cargo для Rust и он ещё собирает программу. pip только ставит пакет Python.", "Cargo.toml — это сам пакет? Нет. Это имя и список. Код пакета в отдельном файле."],
      ),
    },
  ),
  topic(
    "make",
    "Make",
    t("Make nədir?", "What is Make?", "Make nedir?", "ما هو Make؟", "Что такое Make?"),
    t(
      "Make fayl dəyişəndə yalnız lazım olan əmri işə salan alətdir. Dil deyil. Qaydalar Makefile içində yazılır.",
      "Make is the tool that starts only the command that is needed when a file changes. It is not a language. The rules are written in a Makefile.",
      "Make, dosya değişince yalnız gereken komutu çalıştıran araçtır. Dil değildir. Kurallar Makefile içinde yazılır.",
      "Make الأداة التي تشغّل الأمر اللازم فقط حين يتغير ملف. ليست لغة. القواعد تُكتب في Makefile.",
      "Make — инструмент, который запускает только нужную команду, когда файл меняется. Это не язык. Правила пишутся в Makefile.",
    ),
    t("Make nədir, Makefile, hədəf, qurma", "what is Make, Makefile, target, build", "Make nedir, Makefile, hedef", "ما هو Make, Makefile, هدف", "что такое Make, Makefile, цель"),
    {
      what: t(
        "Make-i Stuart Feldman Bell Labs-da 1976-cı ildə yazıb. Məqsəd hər şeyi yenidən qurmamaq idi. Makefile hədəf, asılılıq və əmr saxlayır. Hədəf alınan faylın adıdır. Asılılıq həmin fayldan əvvəl hazır olması lazım olan fayldır. Əmr sətirinin əvvəli boşluq deyil, tab olmalıdır. Boşluq yazılsa Make dayanır. Linux-da geniş işlənən variant GNU Make-dir. O, köhnə Make-in üstünə öz əlavələrini qoyur. Əmrin özü başqa proqramdır: kompilyator, skript və ya surət.",
        "Stuart Feldman wrote Make at Bell Labs in 1976. The aim was not to rebuild everything. A Makefile keeps a target, a dependency, and a command. The target is the name of the file you get. The dependency is the file that must be ready before that one. The start of a command line must be a tab, not a space. If a space is written, Make stops. The widely used kind on Linux is GNU Make. It puts its own additions on top of old Make. The command itself is another program: a compiler, a script, or a copy.",
        "Make’i Stuart Feldman Bell Labs’ta 1976’da yazdı. Amaç her şeyi yeniden kurmamaktı. Makefile hedef, bağımlılık ve komut tutar. Hedef alınan dosyanın adıdır. Bağımlılık o dosyadan önce hazır olması gereken dosyadır. Komut satırının başı boşluk değil, sekme olmalıdır. Boşluk yazılırsa Make durur. Linux’ta yaygın kullanılan tür GNU Make’tir. Eski Make’in üstüne kendi eklerini koyar. Komutun kendisi başka programdır: derleyici, betik veya kopya.",
        "كتب Stuart Feldman أداة Make في Bell Labs سنة 1976. القصد كان ألا يُعاد بناء كل شيء. Makefile يحفظ هدفاً واعتماداً وأمراً. الهدف اسم الملف الذي تحصل عليه. الاعتماد الملف الذي يجب أن يكون جاهزاً قبل ذلك. أول سطر الأمر يجب أن يكون جدولة لا مسافة. إذا كُتبت مسافة يتوقف Make. النوع الواسع على Linux هو GNU Make. يضع إضافاته فوق Make القديم. الأمر نفسه برنامج آخر: مترجم أو سكربت أو نسخ.",
        "Make написал Stuart Feldman в Bell Labs в 1976 году. Цель была не собирать всё заново. Makefile хранит цель, зависимость и команду. Цель — имя файла, который получается. Зависимость — файл, который должен быть готов раньше. Начало строки команды должно быть табом, не пробелом. Если написан пробел, Make останавливается. Широко используемый вид в Linux — GNU Make. Он кладёт свои добавления поверх старого Make. Сама команда — другая программа: компилятор, скрипт или копирование.",
      ),
      uses: t(
        "Make böyük layihədə yalnız dəyişən hissəni yenidən qurmaq üçündür. Kiçik təkrar əmri də bir hədəfə bağlaya bilər.",
        "Make is for rebuilding only the part that changed in a large project. It can also tie a small repeated command to one target.",
        "Make büyük projede yalnız değişen parçayı yeniden kurmak içindir. Küçük yinelenen komutu da bir hedefe bağlayabilir.",
        "Make لإعادة بناء الجزء المتغير فقط في مشروع كبير. يقدر أيضاً أن يربط أمراً صغيراً متكرراً بهدف واحد.",
        "Make нужен, чтобы в большом проекте заново собрать только изменившуюся часть. Он может и маленькую повторяющуюся команду привязать к одной цели.",
      ),
      useList: lines(
        ["C proqramında yalnız dəyişən faylı yenidən qurmaq", "Testi bir hədəf adı ilə açmaq", "Təmizlik əmrini ayrıca hədəf etmək", "Bir neçə addımı bir ad altında saxlamaq"],
        ["Rebuilding only the changed file in a C program", "Opening the test by one target name", "Making the cleanup command its own target", "Keeping several steps under one name"],
        ["C programında yalnız değişen dosyayı yeniden kurmak", "Testi bir hedef adıyla açmak", "Temizlik komutunu ayrı hedef yapmak", "Birkaç adımı bir ad altında tutmak"],
        ["إعادة بناء الملف المتغير فقط في برنامج C", "فتح الاختبار باسم هدف واحد", "جعل أمر التنظيف هدفاً وحده", "حفظ عدة خطوات تحت اسم واحد"],
        ["Заново собрать только изменившийся файл в программе на C", "Открыть тест одним именем цели", "Сделать команду уборки отдельной целью", "Держать несколько шагов под одним именем"],
      ),
      can: t(
        "Make ilə hədəfin köhnə olub-olmadığını yoxlayırsan. Fayl dəyişməyibsə əmri təkrar işlətmir. O, kompilyator deyil. Kompilyatoru sətirin içində çağırırsan. Səhv tab və ya səhv yol olanda qurma sakit və ya yarım qalır. Nəticəni Makefile-dan oxumaq lazımdır.",
        "With Make you check whether a target is old. If the file has not changed, it does not run the command again. It is not a compiler. You call the compiler inside the line. When the tab or the path is wrong, the build stays quiet or half done. The result has to be read from the Makefile.",
        "Make ile hedefin eski olup olmadığına bakarsın. Dosya değişmediyse komutu yeniden çalıştırmaz. Derleyici değildir. Derleyiciyi satırın içinde çağırırsın. Sekme veya yol yanlışsa kurma sessiz veya yarım kalır. Sonucu Makefile’dan okumak gerekir.",
        "بـ Make تفحص هل الهدف قديم. إذا لم يتغير الملف لا يشغّل الأمر مرة أخرى. ليس مترجماً. تستدعي المترجم داخل السطر. إذا أخطأت الجدولة أو المسار يبقى البناء صامتاً أو نصف كامل. يجب قراءة النتيجة من Makefile.",
        "Через Make проверяют, устарела ли цель. Если файл не менялся, команду снова не запускают. Это не компилятор. Компилятор вызывают внутри строки. Если таб или путь неверны, сборка остаётся тихой или наполовину сделанной. Результат нужно читать из Makefile.",
      ),
      hard: t(
        "Bir hədəf yazmaq asandır. Çətinlik tab və asılılıqdadır. Boşluq tab kimi görünür, amma Make onu qəbul etmir. Asılılığı yazmamaq köhnə faylı yeni sayır və əmri buraxır. Eyni hədəf iki yerdədirsə sonuncu qayda işləyir. Saat səhvdirsə Make faylı təzə və ya köhnə sanır.",
        "Writing one target is easy. The difficulty is the tab and the dependency. A space looks like a tab, but Make does not accept it. Not writing the dependency counts an old file as new and skips the command. If the same target is in two places, the last rule runs. If the clock is wrong, Make treats the file as fresh or old.",
        "Bir hedef yazmak kolaydır. Zorluk sekme ve bağımlılıktadır. Boşluk sekme gibi görünür, ama Make onu kabul etmez. Bağımlılığı yazmamak eski dosyayı yeni sayar ve komutu atlar. Aynı hedef iki yerdeyse son kural çalışır. Saat yanlışsa Make dosyayı taze veya eski sanır.",
        "كتابة هدف واحد سهلة. الصعوبة في الجدولة والاعتماد. المسافة تشبه الجدولة لكن Make لا يقبلها. عدم كتابة الاعتماد يعد الملف القديم جديداً ويتخطى الأمر. إذا كان الهدف نفسه في مكانين تعمل القاعدة الأخيرة. إذا أخطأت الساعة يحسب Make الملف جديداً أو قديماً.",
        "Написать одну цель легко. Трудность в табе и в зависимости. Пробел похож на таб, но Make его не принимает. Если не записать зависимость, старый файл считается новым и команда пропускается. Если одна цель в двух местах, работает последнее правило. Если часы неверны, Make считает файл свежим или старым.",
      ),
      balance: t(
        "Üstünlük: dəyişməyən hissə təkrar qurulmur, qayda bir faylda durur, alət köhnə və genişdir. Məhdudiyyət: tab səhvi tez-tez olur və böyük Makefile çətin oxunur. Make Cargo və npm deyil. O, sənin yazdığın əmri vaxtı çatanda çağırır.",
        "Advantage: the part that did not change is not rebuilt, the rule stays in one file, and the tool is old and widespread. Limit: a tab mistake happens often, and a large Makefile is hard to read. Make is not Cargo and it is not npm. It calls the command you wrote when the time comes.",
        "Avantaj: değişmeyen parça yeniden kurulmaz, kural bir dosyada durur, araç eski ve yaygındır. Sınır: sekme hatası sık olur ve büyük Makefile zor okunur. Make, Cargo ve npm değildir. Vakti gelince senin yazdığın komutu çağırır.",
        "الميزة: الجزء الذي لم يتغير لا يُعاد بناؤه والقاعدة تبقى في ملف واحد والأداة قديمة وواسعة. الحد: خطأ الجدولة يقع كثيراً وMakefile الكبير صعب القراءة. Make ليس Cargo وليس npm. يستدعي الأمر الذي كتبته حين يأتي الوقت.",
        "Плюс: неизменившаяся часть не собирается заново, правило лежит в одном файле, инструмент старый и распространённый. Ограничение: ошибка таба случается часто, и большой Makefile трудно читать. Make — не Cargo и не npm. Он вызывает написанную тобой команду, когда приходит время.",
      ),
      ideas: t(
        "Hədəf alınacaq addır. Asılılıq ondan əvvəl hazır olan fayldır. Əmr isə həmin addımın özüdür.",
        "A target is the name you want to get. A dependency is the file ready before it. The command is the step itself.",
        "Hedef alınacak addır. Bağımlılık ondan önce hazır olan dosyadır. Komut ise o adımın kendisidir.",
        "الهدف الاسم الذي تريد الحصول عليه. الاعتماد الملف الجاهز قبله. الأمر هو الخطوة نفسها.",
        "Цель — имя, которое нужно получить. Зависимость — файл, готовый раньше неё. Команда — сам этот шаг.",
      ),
      ideaList: lines(
        ["Hədəf sətrin solunda durur", "Əmr tab ilə başlayır", "Dəyişməyən fayl yenidən qurulmur", "make adı verilən hədəfi işlədir"],
        ["The target stays on the left of the line", "The command starts with a tab", "A file that did not change is not rebuilt", "make runs the target you name"],
        ["Hedef satırın solunda durur", "Komut sekme ile başlar", "Değişmeyen dosya yeniden kurulmaz", "make adı verilen hedefi çalıştırır"],
        ["الهدف يقف يسار السطر", "الأمر يبدأ بجدولة", "الملف الذي لم يتغير لا يُعاد بناؤه", "make يشغّل الهدف الذي تسميه"],
        ["Цель стоит слева в строке", "Команда начинается с таба", "Неизменившийся файл заново не собирается", "make запускает названную цель"],
      ),
      sample: t(
        "Bu, bir proqramı iki obyekt faylından quran qısadır. Əmr sətirindəki boşluq tab olmalıdır.",
        "This is a short rule that builds one program from two object files. The space in the command line must be a tab.",
        "Bu, bir programı iki nesne dosyasından kuran kısa kuraldır. Komut satırındaki boşluk sekme olmalıdır.",
        "هذه قاعدة قصيرة تبني برنامجاً من ملفي كائن. الفراغ في سطر الأمر يجب أن يكون جدولة.",
        "Это короткое правило, которое собирает одну программу из двух объектных файлов. Пробел в строке команды должен быть табом.",
      ),
      code: `app: main.o util.o
\tgcc -o app main.o util.o`,
      faq: lines(
        ["Make proqramlaşdırma dilidir? Xeyr. O, fayl köhnədirsə sənin əmrini çağırır.", "Make və Cargo eynidir? Xeyr. Cargo Rust üçündür. Make sənin yazdığın əmri hədəfə bağlayır.", "Əmr boşluqla başlaya bilər? Xeyr. Ənənəvi Make tab istəyir. Boşluq sətiri əmr saymır."],
        ["Is Make a programming language? No. It calls your command if a file is old.", "Are Make and Cargo the same? No. Cargo is for Rust. Make ties the command you wrote to a target.", "Can a command start with a space? No. Traditional Make wants a tab. It does not count a space line as a command."],
        ["Make programlama dili mi? Hayır. Dosya eskiyse senin komutunu çağırır.", "Make ve Cargo aynı mı? Hayır. Cargo Rust içindir. Make senin yazdığın komutu hedefe bağlar.", "Komut boşlukla başlayabilir mi? Hayır. Geleneksel Make sekme ister. Boşluk satırını komut saymaz."],
        ["هل Make لغة برمجة؟ لا. يستدعي أمرك إذا كان الملف قديماً.", "هل Make وCargo الشيء نفسه؟ لا. Cargo لـ Rust. Make يربط الأمر الذي كتبته بهدف.", "هل يبدأ الأمر بمسافة؟ لا. Make التقليدي يريد جدولة. لا يعد سطر المسافة أمراً."],
        ["Make — язык программирования? Нет. Он вызывает твою команду, если файл старый.", "Make и Cargo — одно и то же? Нет. Cargo для Rust. Make привязывает написанную тобой команду к цели.", "Команда может начинаться с пробела? Нет. Традиционный Make хочет таб. Строку с пробелом он командой не считает."],
      ),
    },
  ),
];
