import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_BIT: readonly StackPage[] = [
  topic(
    "linux",
    "Linux",
    t("Linux nədir?", "What is Linux?", "Linux nedir?", "ما هو Linux؟", "Что такое Linux?"),
    t(
      "Linux kompüterin nüvəsidir. Proqramlaşdırma dili deyil. Nüvə yaddaşı, diski və prosesi idarə edir. Ubuntu isə onun üzərinə qurulmuş bir paylamadır.",
      "Linux is the kernel of a computer. It is not a programming language. The kernel manages memory, the disk, and a process. Ubuntu is one distribution built on top of it.",
      "Linux bir bilgisayarın çekirdeğidir. Programlama dili değildir. Çekirdek belleği, diski ve süreci yönetir. Ubuntu ise onun üzerine kurulmuş bir dağıtımdır.",
      "Linux نواة الحاسوب. ليست لغة برمجة. النواة تدير الذاكرة والقرص والعملية. Ubuntu توزيعة واحدة مبنية فوقها.",
      "Linux — это ядро компьютера. Это не язык программирования. Ядро управляет памятью, диском и процессом. Ubuntu — один дистрибутив, собранный поверх него.",
    ),
    t("Linux nədir, Linux nüvəsi, Ubuntu, paylama", "what is Linux, Linux kernel, Ubuntu, distribution", "Linux nedir, Linux çekirdeği, dağıtım", "ما هو Linux, نواة Linux, توزيعة", "что такое Linux, ядро Linux, дистрибутив"),
    {
      what: t(
        "Linux nüvəsini Linus Torvalds 1991-ci ildə yazmağa başlayıb. Nüvə tək başına masaüstü deyil. Paylama nüvəyə əmrlər, paket idarəsi və çox vaxt GNU alətlərini əlavə edir. Ubuntu, Debian və Fedora ayrı paylamalardır. Hamısı Linux nüvəsini işlədir, amma paketləri və quraşdırma yolu eyni deyil. Android də Linux nüvəsindən istifadə edir. Android Ubuntu deyil.",
        "Linus Torvalds began writing the Linux kernel in 1991. The kernel alone is not a desktop. A distribution adds commands, package management, and often the GNU tools to the kernel. Ubuntu, Debian, and Fedora are separate distributions. All of them run the Linux kernel, but their packages and install path are not the same. Android also uses the Linux kernel. Android is not Ubuntu.",
        "Linux çekirdeğini Linus Torvalds 1991’de yazmaya başladı. Çekirdek tek başına masaüstü değildir. Dağıtım çekirdeğe komutlar, paket yönetimi ve çoğu zaman GNU araçlarını ekler. Ubuntu, Debian ve Fedora ayrı dağıtımlardır. Hepsi Linux çekirdeğini çalıştırır, ama paketleri ve kurulum yolu aynı değildir. Android de Linux çekirdeğini kullanır. Android Ubuntu değildir.",
        "بدأ Linus Torvalds كتابة نواة Linux سنة 1991. النواة وحدها ليست سطح مكتب. التوزيعة تضيف أوامر وإدارة حزم وغالباً أدوات GNU إلى النواة. Ubuntu وDebian وFedora توزيعات منفصلة. كلها تشغّل نواة Linux، لكن حزمها وطريق التثبيت ليست واحدة. Android أيضاً يستخدم نواة Linux. Android ليست Ubuntu.",
        "Ядро Linux Linus Torvalds начал писать в 1991 году. Ядро само по себе — не рабочий стол. Дистрибутив добавляет к ядру команды, управление пакетами и часто инструменты GNU. Ubuntu, Debian и Fedora — разные дистрибутивы. Все они запускают ядро Linux, но пакеты и путь установки не одинаковы. Android тоже использует ядро Linux. Android — это не Ubuntu.",
      ),
      uses: t(
        "Linux serverdə, buludda və kiçik cihazda seçilir. Uzun müddət açıq qalması və paketlə qurulması onun adi yeridir.",
        "Linux is chosen on a server, in the cloud, and on a small device. Staying up for a long time and being set up with packages is its ordinary place.",
        "Linux sunucuda, bulutta ve küçük aygıtta seçilir. Uzun süre açık kalması ve paketle kurulması onun olağan yeridir.",
        "يُختار Linux على الخادم وفي السحابة وعلى الجهاز الصغير. بقاؤه مفتوحاً مدة طويلة وبناؤه بالحزم مكانه العادي.",
        "Linux выбирают на сервере, в облаке и на маленьком устройстве. Долго оставаться включённым и ставиться пакетами — его обычное место.",
      ),
      useList: lines(
        ["Sayt serveri", "Konteynerin içindəki sistem", "Şəbəkə avadanlığı", "Android telefonun nüvəsi"],
        ["A site server", "The system inside a container", "Network equipment", "The kernel of an Android phone"],
        ["Site sunucusu", "Konteynerin içindeki sistem", "Ağ donanımı", "Android telefonun çekirdeği"],
        ["خادم موقع", "النظام داخل الحاوية", "عتاد الشبكة", "نواة هاتف Android"],
        ["Сервер сайта", "Система внутри контейнера", "Сетевое оборудование", "Ядро телефона Android"],
      ),
      can: t(
        "Linux ilə prosesi görür, paketi qurur, diski bölür və şəbəkəni açıb bağlayırsan. O, səhifəni özü çəkmir. Səhifəni Nginx, verilənlər bazası və sənin proqramın çəkir. İcazəsiz əmr sistemin faylını poza bilər. Kök istifadəçi hər şeyi dəyişə bilir.",
        "With Linux you see a process, install a package, split a disk, and open or close the network. It does not draw the page itself. Nginx, a database, and your program draw the page. A command without care can break a system file. The root user can change everything.",
        "Linux ile süreci görür, paketi kurar, diski bölersin ve ağı açıp kapatırsın. Sayfayı kendi çizmez. Sayfayı Nginx, veritabanı ve senin programın çizer. Dikkatsiz komut sistem dosyasını bozabilir. Kök kullanıcı her şeyi değiştirebilir.",
        "بـ Linux ترى العملية وتثبّت الحزمة وتقسم القرص وتفتح الشبكة أو تغلقها. هو لا يرسم الصفحة بنفسه. Nginx وقاعدة البيانات وبرنامجك يرسمون الصفحة. أمر بلا حذر قد يفسد ملف النظام. مستخدم الجذر يقدر أن يغيّر كل شيء.",
        "В Linux смотрят процесс, ставят пакет, делят диск и открывают или закрывают сеть. Сам он страницу не рисует. Её рисуют Nginx, база данных и твоя программа. Неосторожная команда может сломать системный файл. Пользователь root может изменить всё.",
      ),
      hard: t(
        "Paket qurmaq asandır. Çətinlik icazə və servisdədir. Fayl sənin istifadəçinə aid deyilsə əmr dayanır. Servis düşəndə səhifə də düşür, halbuki nüvə hələ işləyir. Paylamanı qarışdırmaq da buradadır: Ubuntu əmri Fedora-da eyni paket adıyla işləməyə bilər.",
        "Installing a package is easy. The difficulty is permission and the service. If a file does not belong to your user, the command stops. When a service falls, the page falls too, even though the kernel is still running. Mixing up distributions sits here as well: an Ubuntu command may not work on Fedora under the same package name.",
        "Paket kurmak kolaydır. Zorluk izin ve servistedir. Dosya senin kullanıcına ait değilse komut durur. Servis düşünce sayfa da düşer, çekirdek hâlâ çalışsa bile. Dağıtımı karıştırmak da buradadır: Ubuntu komutu Fedora’da aynı paket adıyla çalışmayabilir.",
        "تثبيت حزمة سهل. الصعوبة في الإذن والخدمة. إذا لم يكن الملف لمستخدمك يتوقف الأمر. حين تسقط الخدمة تسقط الصفحة أيضاً ولو بقيت النواة تعمل. خلط التوزيعات هنا أيضاً: أمر Ubuntu قد لا يعمل على Fedora باسم الحزمة نفسه.",
        "Поставить пакет легко. Трудность в праве и в службе. Если файл не принадлежит твоему пользователю, команда останавливается. Когда служба падает, падает и страница, хотя ядро ещё работает. Путаница дистрибутивов тоже здесь: команда Ubuntu может не сработать на Fedora с тем же именем пакета.",
      ),
      balance: t(
        "Üstünlük: serverdə geniş işlənir, paketlər aydındır, nüvənin kodu oxuna bilir. Məhdudiyyət: hər masaüstü proqramı burada hazır deyil. Əmr səhv olanda geri almaq pəncərədən çətindir. Linux Ubuntu ilə eyni söz deyil.",
        "Advantage: it is widely used on servers, packages are clear, and the kernel's code can be read. Limit: not every desktop program is ready here. When a command is wrong, undoing it is harder than in a window. Linux is not the same word as Ubuntu.",
        "Avantaj: sunucuda geniş kullanılır, paketler açıktır, çekirdeğin kodu okunabilir. Sınır: her masaüstü programı burada hazır değildir. Komut yanlışsa geri almak pencereden zordur. Linux, Ubuntu ile aynı söz değildir.",
        "الميزة: يُستخدم على الخوادم على نطاق واسع والحزم واضحة وكود النواة يُقرأ. الحد: ليس كل برنامج سطح مكتب جاهزاً هنا. إذا أخطأ الأمر فالرجوع أصعب من النافذة. Linux ليست الكلمة نفسها مثل Ubuntu.",
        "Плюс: на серверах его широко используют, пакеты понятны, код ядра можно читать. Ограничение: не каждая настольная программа здесь готова. Если команда неверна, откатить её труднее, чем в окне. Linux — не то же слово, что Ubuntu.",
      ),
      ideas: t(
        "Nüvə avadanlıqla danışır. Paylama həmin nüvənin ətrafındakı hazır sistemdir. Paket qurulan proqramın bağlanmış haldır.",
        "The kernel talks to the hardware. A distribution is the ready system around that kernel. A package is a program tied up for install.",
        "Çekirdek donanımla konuşur. Dağıtım o çekirdeğin çevresindeki hazır sistemdir. Paket kurulacak programın bağlanmış halidir.",
        "النواة تكلم العتاد. التوزيعة النظام الجاهز حول تلك النواة. الحزمة برنامج مربوط للتثبيت.",
        "Ядро говорит с оборудованием. Дистрибутив — готовая система вокруг этого ядра. Пакет — программа, собранная для установки.",
      ),
      ideaList: lines(
        ["Nüvə prosesi və yaddaşı bölür", "Paylama paketləri bir yerdə saxlayır", "Servis arxa planda işləyir", "İcazə faylı kimin dəyişdiyini deyir"],
        ["The kernel divides a process and memory", "A distribution keeps packages in one place", "A service runs in the background", "A permission says who may change a file"],
        ["Çekirdek süreci ve belleği böler", "Dağıtım paketleri bir yerde tutar", "Servis arkada çalışır", "İzin dosyayı kimin değiştireceğini söyler"],
        ["النواة تقسم العملية والذاكرة", "التوزيعة تحفظ الحزم في مكان واحد", "الخدمة تعمل في الخلف", "الإذن يقول من يقدر أن يغيّر الملف"],
        ["Ядро делит процесс и память", "Дистрибутив держит пакеты в одном месте", "Служба работает в фоне", "Право говорит, кто может изменить файл"],
      ),
      sample: t(
        "Bu əmr işləyən nüvənin qısa adını göstərir. O, sistemi qurmur və fayl silmir.",
        "This command shows the short name of the kernel that is running. It does not install the system and it does not delete a file.",
        "Bu komut çalışan çekirdeğin kısa adını gösterir. Sistemi kurmaz ve dosya silmez.",
        "هذا الأمر يُظهر الاسم القصير للنواة التي تعمل. لا يثبّت النظام ولا يحذف ملفاً.",
        "Эта команда показывает короткое имя ядра, которое работает. Она не ставит систему и не удаляет файл.",
      ),
      code: `uname -r`,
      faq: lines(
        ["Linux və Ubuntu eynidir? Xeyr. Linux nüvədir. Ubuntu həmin nüvəni işlədən bir paylamadır.", "Linux proqramlaşdırma dilidir? Xeyr. O, proqramların üstündə işlədiyi sistemdir.", "Android Linux-dur? Android Linux nüvəsini işlədir. Ubuntu və ya masaüstü Linux deyil."],
        ["Are Linux and Ubuntu the same? No. Linux is the kernel. Ubuntu is one distribution that runs that kernel.", "Is Linux a programming language? No. It is the system programs run on.", "Is Android Linux? Android runs the Linux kernel. It is not Ubuntu or a desktop Linux."],
        ["Linux ve Ubuntu aynı mı? Hayır. Linux çekirdektir. Ubuntu o çekirdeği çalıştıran bir dağıtımdır.", "Linux programlama dili mi? Hayır. Programların üzerinde çalıştığı sistemdir.", "Android Linux mu? Android Linux çekirdeğini çalıştırır. Ubuntu veya masaüstü Linux değildir."],
        ["هل Linux وUbuntu الشيء نفسه؟ لا. Linux النواة. Ubuntu توزيعة واحدة تشغّل تلك النواة.", "هل Linux لغة برمجة؟ لا. هو النظام الذي تعمل البرامج فوقه.", "هل Android هو Linux؟ Android يشغّل نواة Linux. ليس Ubuntu ولا Linux المكتبي."],
        ["Linux и Ubuntu — одно и то же? Нет. Linux — ядро. Ubuntu — один дистрибутив, который это ядро запускает.", "Linux — язык программирования? Нет. Это система, на которой работают программы.", "Android — это Linux? Android запускает ядро Linux. Это не Ubuntu и не настольный Linux."],
      ),
    },
  ),
  topic(
    "ssh",
    "SSH",
    t("SSH nədir?", "What is SSH?", "SSH nedir?", "ما هو SSH؟", "Что такое SSH?"),
    t(
      "SSH uzaq kompüterə şifrəli giriş qaydasıdır. Əmr orada işləyir, mətn yolda oxunmur. Bash deyil. Bash içəri girdikdən sonra açıla bilən örtükdür.",
      "SSH is the rule for an encrypted login to a remote computer. The command runs there, and the text is not read on the path. It is not Bash. Bash is the shell that can open after you are inside.",
      "SSH, uzak bilgisayara şifreli giriş kuralıdır. Komut orada çalışır, metin yolda okunmaz. Bash değildir. Bash içeri girdikten sonra açılabilecek kabuktur.",
      "SSH قاعدة دخول مشفّر إلى حاسوب بعيد. الأمر يعمل هناك والنص لا يُقرأ في الطريق. ليس Bash. Bash الصدفة التي قد تُفتح بعد الدخول.",
      "SSH — правило шифрованного входа на удалённый компьютер. Команда выполняется там, а текст по пути не читается. Это не Bash. Bash — оболочка, которая может открыться уже после входа.",
    ),
    t("SSH nədir, SSH açar, uzaq giriş, 22 port", "what is SSH, SSH key, remote login, port 22", "SSH nedir, SSH anahtar, uzak giriş", "ما هو SSH, مفتاح SSH, منفذ 22", "что такое SSH, ключ SSH, порт 22"),
    {
      what: t(
        "SSH Secure Shell deməkdir. İlk variantını Tatu Ylönen 1995-ci ildə yazılıb. Köhnə Telnet mətni açıq aparırdı. SSH həmin yolu şifrələyir. Adətən 22-ci port işlənir. Açılış parol və ya açarla olur. Açar iki hissəlidir: gizli hissə sənin maşınında qalır, açıq hissə serverə qoyulur. OpenSSH bu qaydanın geniş işlənən proqramıdır.",
        "SSH means Secure Shell. Tatu Ylönen wrote the first version in 1995. Old Telnet carried the text in the open. SSH encrypts that path. Port 22 is usually used. You open it with a password or a key. A key has two parts: the secret part stays on your machine, and the public part is placed on the server. OpenSSH is the widely used program of this rule.",
        "SSH, Secure Shell demektir. İlk sürümünü Tatu Ylönen 1995’te yazdı. Eski Telnet metni açık taşırdı. SSH o yolu şifreler. Genellikle 22. port kullanılır. Açılış parola veya anahtarla olur. Anahtarın iki parçası vardır: gizli parça senin makinede kalır, açık parça sunucuya konur. OpenSSH bu kuralın geniş kullanılan programıdır.",
        "SSH تعني Secure Shell. كتب Tatu Ylönen النسخة الأولى سنة 1995. Telnet القديم كان يحمل النص مكشوفاً. SSH يشفّر ذلك الطريق. يُستخدم المنفذ 22 عادة. يُفتح بكلمة مرور أو بمفتاح. للمفتاح جزءان: الجزء السري يبقى على جهازك والجزء العلني يوضع على الخادم. OpenSSH البرنامج الواسع الاستخدام لهذه القاعدة.",
        "SSH значит Secure Shell. Первую версию написал Tatu Ylönen в 1995 году. Старый Telnet вёз текст открыто. SSH шифрует этот путь. Обычно используется порт 22. Вход идёт паролем или ключом. У ключа две части: секретная остаётся на твоей машине, открытая кладётся на сервер. OpenSSH — широко используемая программа этого правила.",
      ),
      uses: t(
        "SSH serverə əmr vermək, fayl köçürmək və qapalı bir portu öz maşınına gətirmək üçündür.",
        "SSH is for giving a command to a server, copying a file, and bringing a closed port to your own machine.",
        "SSH sunucuya komut vermek, dosya kopyalamak ve kapalı bir portu kendi makineye getirmek içindir.",
        "SSH لإعطاء أمر للخادم ونسخ ملف وجلب منفذ مغلق إلى جهازك.",
        "SSH нужен, чтобы дать команду серверу, скопировать файл и привести закрытый порт на свою машину.",
      ),
      useList: lines(
        ["Serverdə paketi yeniləmək", "Jurnalı oxumaq", "Açar ilə parolsuz giriş", "Uzaq faylı yerli maşına köçürmək"],
        ["Updating a package on the server", "Reading a log", "A login without a password, by key", "Copying a remote file to the local machine"],
        ["Sunucuda paketi yenilemek", "Günlüğü okumak", "Anahtarla parolasız giriş", "Uzak dosyayı yerel makineye kopyalamak"],
        ["تحديث حزمة على الخادم", "قراءة السجل", "دخول بلا كلمة مرور بالمفتاح", "نسخ ملف بعيد إلى الجهاز المحلي"],
        ["Обновить пакет на сервере", "Прочитать журнал", "Вход без пароля, по ключу", "Скопировать удалённый файл на свою машину"],
      ),
      can: t(
        "SSH ilə içəri girəndə artıq o kompüterin əmrini yazırsan. Sənin ekranındakı mətn orada işləyir. Fayl köçürmək ayrı əmrdir. SSH səhifəni internetə açmır. O, sənin girişindir. Kök girişini hər kəsə açmaq olmaz.",
        "Once you are inside with SSH, you are typing that computer's command. The text on your screen runs there. Copying a file is a separate command. SSH does not open a page to the internet. It is your login. Do not open root login to everyone.",
        "SSH ile içeri girince artık o bilgisayarın komutunu yazarsın. Ekranındaki metin orada çalışır. Dosya kopyalamak ayrı komuttur. SSH sayfayı internete açmaz. O, senin girişindir. Kök girişini herkese açmamak gerekir.",
        "حين تدخل بـ SSH تكتب أمر ذلك الحاسوب. النص على شاشتك يعمل هناك. نسخ الملف أمر منفصل. SSH لا يفتح الصفحة للإنترنت. هو دخولك. لا تفتح دخول الجذر لكل أحد.",
        "Когда ты внутри по SSH, ты уже пишешь команду того компьютера. Текст на твоём экране выполняется там. Копирование файла — отдельная команда. SSH не открывает страницу в интернет. Это твой вход. Не открывай вход root для всех.",
      ),
      hard: t(
        "Bir dəfə bağlanmaq asandır. Çətinlik açar və ünvandadır. Açarın gizli hissəsini serverə qoymaq olmaz. O, sənin tərəfində qalır. Səhv port və ya səhv istifadəçi eyni xəta kimi görünə bilər. Köhnə açar server dəyişəndə xəbərdarlıq verir. Həmin xəbərdarlığı keçmək olmaz.",
        "Connecting once is easy. The difficulty is the key and the address. Do not put the secret part of the key on the server. It stays on your side. A wrong port or a wrong user can look like the same error. An old key warns you when the server changes. Do not skip that warning.",
        "Bir kez bağlanmak kolaydır. Zorluk anahtar ve adrestedir. Anahtarın gizli parçasını sunucuya koymamak gerekir. O, senin tarafında kalır. Yanlış port veya yanlış kullanıcı aynı hata gibi görünebilir. Eski anahtar sunucu değişince uyarı verir. O uyarıyı geçmemek gerekir.",
        "الاتصال مرة سهل. الصعوبة في المفتاح والعنوان. لا تضع الجزء السري من المفتاح على الخادم. يبقى في طرفك. المنفذ الخطأ أو المستخدم الخطأ قد يظهر كالخطأ نفسه. المفتاح القديم ينذرك حين يتغير الخادم. لا تتجاوز ذلك الإنذار.",
        "Подключиться один раз легко. Трудность в ключе и в адресе. Секретную часть ключа не кладут на сервер. Она остаётся у тебя. Неверный порт или неверный пользователь могут выглядеть как одна и та же ошибка. Старый ключ предупреждает, когда сервер сменился. Это предупреждение не пропускают.",
      ),
      balance: t(
        "Üstünlük: əmr və parol yolda oxunmur, açar paroldan idarə olunasıdır. Məhdudiyyət: açarın gizli hissəsini itirmək girişi kəsə bilər. SSH özü təhlükəsiz divar deyil. Divar hansı portun açıq olduğunu deyir.",
        "Advantage: the command and the password are not read on the path, and a key is easier to manage than a password. Limit: losing the secret part of the key can cut the login. SSH itself is not the firewall. The firewall says which port is open.",
        "Avantaj: komut ve parola yolda okunmaz, anahtar paroladan yönetilebilir. Sınır: anahtarın gizli parçasını kaybetmek girişi kesebilir. SSH kendi güvenlik duvarı değildir. Duvar hangi portun açık olduğunu söyler.",
        "الميزة: الأمر وكلمة المرور لا يُقرآن في الطريق والمفتاح أسهل إدارة من كلمة المرور. الحد: فقد الجزء السري قد يقطع الدخول. SSH نفسه ليس جدار الحماية. الجدار يقول أي منفذ مفتوح.",
        "Плюс: команда и пароль по пути не читаются, ключом управлять легче, чем паролем. Ограничение: потеря секретной части ключа может отрезать вход. Сам SSH — не межсетевой экран. Экран говорит, какой порт открыт.",
      ),
      ideas: t(
        "İstifadəçi kimin girdiyini deyir. Ünvan hansı maşın olduğunu deyir. Açar parolun yerinə duran cütdür.",
        "The user says who is entering. The address says which machine it is. A key is the pair that stands in place of a password.",
        "Kullanıcı kimin girdiğini söyler. Adres hangi makine olduğunu söyler. Anahtar parolanın yerine duran çifttir.",
        "المستخدم يقول من يدخل. العنوان يقول أي جهاز هو. المفتاح الزوج الذي يقوم مقام كلمة المرور.",
        "Пользователь говорит, кто входит. Адрес говорит, какая это машина. Ключ — пара, которая стоит вместо пароля.",
      ),
      ideaList: lines(
        ["Port adətən 22-dir", "Açıq açar serverdə durur", "Gizli açar səndə qalır", "Telnet şifrələmir, SSH şifrələyir"],
        ["The port is usually 22", "The public key stays on the server", "The secret key stays with you", "Telnet does not encrypt, SSH does"],
        ["Port genellikle 22’dir", "Açık anahtar sunucuda durur", "Gizli anahtar sende kalır", "Telnet şifrelemez, SSH şifreler"],
        ["المنفذ عادة 22", "المفتاح العلني يبقى على الخادم", "المفتاح السري يبقى عندك", "Telnet لا يشفّر وSSH يشفّر"],
        ["Порт обычно 22", "Открытый ключ лежит на сервере", "Секретный ключ остаётся у тебя", "Telnet не шифрует, SSH шифрует"],
      ),
      sample: t(
        "Bu əmr adı verilmiş istifadəçi ilə serverə bağlanır. Bağlantı açılmadan əmr orada işləmir.",
        "This command connects to the server as the named user. The command does not run there until the connection opens.",
        "Bu komut adı verilen kullanıcı ile sunucuya bağlanır. Bağlantı açılmadan komut orada çalışmaz.",
        "هذا الأمر يتصل بالخادم بالمستخدم المذكور. الأمر لا يعمل هناك قبل أن يُفتح الاتصال.",
        "Эта команда соединяется с сервером названным пользователем. Команда там не выполняется, пока соединение не открыто.",
      ),
      code: `ssh user@server.example`,
      faq: lines(
        ["SSH və Bash eynidir? Xeyr. SSH girişi aparır. Bash içəridə açıla bilən əmr örtüyüdür.", "Parol açıq gedir? SSH-də yox. Telnetdə gedərdi. Buna görə Telnet giriş üçün işlədilmir.", "Açarın hər iki hissəsi serverdə durur? Xeyr. Gizli hissə sənin maşınında qalır."],
        ["Are SSH and Bash the same? No. SSH carries the login. Bash is the command shell that can open inside.", "Does the password travel in the open? Not in SSH. It would in Telnet. That is why Telnet is not used for login.", "Do both parts of the key stay on the server? No. The secret part stays on your machine."],
        ["SSH ve Bash aynı mı? Hayır. SSH girişi taşır. Bash içeride açılabilecek komut kabuğudur.", "Parola açık gider mi? SSH’de hayır. Telnet’te giderdi. Bu yüzden Telnet giriş için kullanılmaz.", "Anahtarın iki parçası da sunucuda mı durur? Hayır. Gizli parça senin makinede kalır."],
        ["هل SSH وBash الشيء نفسه؟ لا. SSH يحمل الدخول. Bash صدفة الأوامر التي قد تُفتح في الداخل.", "هل تسير كلمة المرور مكشوفة؟ ليس في SSH. كانت تسير في Telnet. لذلك لا يُستخدم Telnet للدخول.", "هل جزءا المفتاح يبقيان على الخادم؟ لا. الجزء السري يبقى على جهازك."],
        ["SSH и Bash — одно и то же? Нет. SSH везёт вход. Bash — оболочка команд, которая может открыться внутри.", "Пароль идёт открыто? В SSH нет. В Telnet шёл бы. Поэтому Telnet для входа не используют.", "Обе части ключа лежат на сервере? Нет. Секретная часть остаётся на твоей машине."],
      ),
    },
  ),
  topic(
    "dns",
    "DNS",
    t("DNS nədir?", "What is DNS?", "DNS nedir?", "ما هو DNS؟", "Что такое DNS?"),
    t(
      "DNS adın nömrəyə çevrilmə qaydasıdır. Brauzer nibrascode.com yazır, DNS onun ünvanını tapır. Saytın özü deyil və HTTP deyil.",
      "DNS is the rule that turns a name into a number. The browser writes nibrascode.com, and DNS finds its address. It is not the site itself, and it is not HTTP.",
      "DNS, adın numaraya çevrilme kuralıdır. Tarayıcı nibrascode.com yazar, DNS onun adresini bulur. Sitenin kendisi değildir ve HTTP değildir.",
      "DNS قاعدة تحويل الاسم إلى رقم. المتصفح يكتب nibrascode.com وDNS يجد عنوانه. ليس الموقع نفسه وليس HTTP.",
      "DNS — правило, которое переводит имя в номер. Браузер пишет nibrascode.com, а DNS находит его адрес. Это не сам сайт и не HTTP.",
    ),
    t("DNS nədir, domen adı, A qeydi, ad serveri", "what is DNS, domain name, A record, name server", "DNS nedir, alan adı, A kaydı", "ما هو DNS, اسم النطاق, سجل A", "что такое DNS, домен, запись A"),
    {
      what: t(
        "DNS Domain Name System deməkdir. Paul Mockapetris onu 1983-cü ildə təsvir edib. İnsan adı yadda saxlayır, kompüter nömrə ilə gedir. Həmin nömrə IP ünvanıdır. Sorğu əvvəl yaxın həllediciyə gedir. Həlledici cavabı bilmirsə, adın məsul serverinə soruşur. Məsul server o adın qeydlərini saxlayır. Qeyd dəyişəndə köhnə cavab bir müddət yaddaşda qala bilər. Buna görə dəyişiklik hər yerdə eyni saniyədə görünmür.",
        "DNS means Domain Name System. Paul Mockapetris described it in 1983. A person remembers a name, and a computer goes by a number. That number is the IP address. The query first goes to a nearby resolver. If the resolver does not know the answer, it asks the server responsible for the name. The responsible server keeps that name's records. When a record changes, the old answer can stay in memory for a while. That is why the change does not appear everywhere in the same second.",
        "DNS, Domain Name System demektir. Paul Mockapetris onu 1983’te tarif etti. İnsan adı hatırlar, bilgisayar numara ile gider. O numara IP adresidir. Sorgu önce yakın çözücüye gider. Çözücü cevabı bilmiyorsa adın sorumlu sunucusuna sorar. Sorumlu sunucu o adın kayıtlarını tutar. Kayıt değişince eski cevap bir süre bellekte kalabilir. Bu yüzden değişiklik her yerde aynı saniyede görünmez.",
        "DNS تعني Domain Name System. وصفها Paul Mockapetris سنة 1983. الإنسان يحفظ اسماً والحاسوب يسير برقم. ذلك الرقم عنوان IP. الطلب يذهب أولاً إلى محلّل قريب. إذا لم يعرف المحلّل الجواب يسأل الخادم المسؤول عن الاسم. الخادم المسؤول يحفظ سجلات ذلك الاسم. حين يتغير السجل قد يبقى الجواب القديم في الذاكرة مدة. لذلك لا يظهر التغيير في كل مكان في الثانية نفسها.",
        "DNS значит Domain Name System. Paul Mockapetris описал её в 1983 году. Человек помнит имя, а компьютер идёт по номеру. Этот номер — IP-адрес. Запрос сначала идёт к близкому распознавателю. Если распознаватель не знает ответ, он спрашивает сервер, ответственный за имя. Ответственный сервер хранит записи этого имени. Когда запись меняется, старый ответ может ещё побыть в памяти. Поэтому изменение не появляется везде в ту же секунду.",
      ),
      uses: t(
        "DNS sayt adını, poçt serverini və bir adı başqa ada bağlamaq üçündür. Brauzer səhifəni DNS-dən almır. Əvvəl ünvanı alır, sonra HTTP ilə gedir.",
        "DNS is for a site name, a mail server, and tying one name to another name. The browser does not take the page from DNS. It first takes the address, then goes by HTTP.",
        "DNS site adı, posta sunucusu ve bir adı başka ada bağlamak içindir. Tarayıcı sayfayı DNS’ten almaz. Önce adresi alır, sonra HTTP ile gider.",
        "DNS لاسم الموقع وخادم البريد وربط اسم باسم آخر. المتصفح لا يأخذ الصفحة من DNS. يأخذ العنوان أولاً ثم يذهب بـ HTTP.",
        "DNS нужен для имени сайта, почтового сервера и связи одного имени с другим. Браузер не берёт страницу из DNS. Сначала он берёт адрес, потом идёт по HTTP.",
      ),
      useList: lines(
        ["Adı bir IP ünvanına bağlamaq", "Poçtun hansı serverə gedəcəyini demək", "Bir adı başqa adın üstünə yönəltmək", "Köhnə ünvanı bir müddət yaddaşda saxlamaq"],
        ["Tying a name to one IP address", "Saying which server mail goes to", "Pointing one name onto another name", "Keeping an old address in memory for a while"],
        ["Adı bir IP adresine bağlamak", "Postanın hangi sunucuya gideceğini söylemek", "Bir adı başka adın üstüne yöneltmek", "Eski adresi bir süre bellekte tutmak"],
        ["ربط اسم بعنوان IP واحد", "قول أي خادم يذهب إليه البريد", "توجيه اسم إلى اسم آخر", "إبقاء العنوان القديم في الذاكرة مدة"],
        ["Связать имя с одним IP-адресом", "Сказать, на какой сервер идёт почта", "Направить одно имя на другое", "Держать старый адрес в памяти какое-то время"],
      ),
      can: t(
        "DNS ilə adın hara baxdığını dəyişirsən. Faylı köçürmürsən. A qeydi nömrəni, CNAME başqa adı, MX poçt serverini deyir. Səhv qeyd saytı başqa maşına apara bilər. HTTPS sertifikatı isə ad üçündür. Ünvan dəyişəndə sertifikat özü köhnəlmir, amma ad həmin maşına işarə etməlidir.",
        "With DNS you change where a name looks. You do not move the file. An A record says the number, a CNAME says another name, and an MX says the mail server. A wrong record can send the site to another machine. An HTTPS certificate is for the name. When the address changes, the certificate itself does not go stale, but the name must point at that machine.",
        "DNS ile adın nereye baktığını değiştirirsin. Dosyayı taşımazsın. A kaydı numarayı, CNAME başka adı, MX posta sunucusunu söyler. Yanlış kayıt siteyi başka makineye götürebilir. HTTPS sertifikası ad içindir. Adres değişince sertifikanın kendisi eskimez, ama ad o makineyi göstermelidir.",
        "بـ DNS تغيّر أين ينظر الاسم. لا تنقل الملف. سجل A يقول الرقم وCNAME يقول اسماً آخر وMX يقول خادم البريد. السجل الخطأ قد يأخذ الموقع إلى جهاز آخر. شهادة HTTPS للاسم. حين يتغير العنوان لا تهرم الشهادة نفسها، لكن الاسم يجب أن يشير إلى ذلك الجهاز.",
        "Через DNS меняют, куда смотрит имя. Файл им не переносят. Запись A говорит номер, CNAME — другое имя, MX — почтовый сервер. Неверная запись может увести сайт на другую машину. Сертификат HTTPS — для имени. Когда адрес меняется, сам сертификат не устаревает, но имя должно указывать на ту машину.",
      ),
      hard: t(
        "Bir qeyd yazmaq asandır. Çətinlik gözləmə müddətindədir. Köhnə cavab saatlarla qala bilər. İki yerə bir-birinə baxan CNAME dövriyyə yaradır və ad açılmır. Adı dəyişib faylı köhnə serverdə qoymaq da səhifəni itirir.",
        "Writing one record is easy. The difficulty is the waiting time. An old answer can stay for hours. Two CNAME records that look at each other make a loop, and the name does not open. Changing the name and leaving the file on the old server also loses the page.",
        "Bir kayıt yazmak kolaydır. Zorluk bekleme süresindedir. Eski cevap saatlerce kalabilir. Birbirine bakan iki CNAME döngü kurar ve ad açılmaz. Adı değiştirip dosyayı eski sunucuda bırakmak da sayfayı kaybettirir.",
        "كتابة سجل واحد سهلة. الصعوبة في مدة الانتظار. الجواب القديم قد يبقى ساعات. سجلان CNAME ينظران إلى بعضهما يصنعان حلقة والاسم لا يُفتح. تغيير الاسم وترك الملف على الخادم القديم يضيع الصفحة أيضاً.",
        "Записать одну запись легко. Трудность во времени ожидания. Старый ответ может оставаться часами. Две записи CNAME, которые смотрят друг на друга, делают петлю, и имя не открывается. Сменить имя и оставить файл на старом сервере тоже теряет страницу.",
      ),
      balance: t(
        "Üstünlük: adam nömrə yadda saxlamır, ünvan dəyişəndə ad qala bilər. Məhdudiyyət: dəyişiklik ani hər yerdə görünmür. DNS səhifənin məzmunu deyil. Məzmun ünvanın göstərdiyi serverdədir.",
        "Advantage: a person does not memorize the number, and the name can stay when the address changes. Limit: the change does not appear everywhere at once. DNS is not the content of the page. The content is on the server the address points to.",
        "Avantaj: kişi numarayı ezberlemez, adres değişince ad kalabilir. Sınır: değişiklik her yerde anında görünmez. DNS sayfanın içeriği değildir. İçerik adresin gösterdiği sunucudadır.",
        "الميزة: الإنسان لا يحفظ الرقم والاسم قد يبقى حين يتغير العنوان. الحد: التغيير لا يظهر في كل مكان فوراً. DNS ليس محتوى الصفحة. المحتوى على الخادم الذي يشير إليه العنوان.",
        "Плюс: человек не запоминает номер, и имя может остаться, когда адрес меняется. Ограничение: изменение не видно везде сразу. DNS — не содержание страницы. Содержание на сервере, на который указывает адрес.",
      ),
      ideas: t(
        "Ad insanın oxuduğu hissədir. Qeyd həmin adın bir cavabıdır. Həlledici cavabı soran yaxın serverdir.",
        "The name is the part a person reads. A record is one answer for that name. The resolver is the nearby server that asks.",
        "Ad insanın okuduğu parçadır. Kayıt o adın bir cevabıdır. Çözücü soran yakın sunucudur.",
        "الاسم الجزء الذي يقرأه الإنسان. السجل جواب واحد لذلك الاسم. المحلّل الخادم القريب الذي يسأل.",
        "Имя — часть, которую читает человек. Запись — один ответ для этого имени. Распознаватель — близкий сервер, который спрашивает.",
      ),
      ideaList: lines(
        ["A qeydi nömrəni deyir", "AAAA qeydi yeni nömrə növünü deyir", "MX poçtu yönəldir", "Gözləmə müddəti köhnə cavabın ömrüdür"],
        ["An A record says the number", "An AAAA record says the newer kind of number", "MX directs mail", "The waiting time is the life of an old answer"],
        ["A kaydı numarayı söyler", "AAAA kaydı yeni numara türünü söyler", "MX postayı yöneltir", "Bekleme süresi eski cevabın ömrüdür"],
        ["سجل A يقول الرقم", "سجل AAAA يقول نوع الرقم الأحدث", "MX يوجّه البريد", "مدة الانتظار عمر الجواب القديم"],
        ["Запись A говорит номер", "Запись AAAA говорит более новый вид номера", "MX направляет почту", "Время ожидания — жизнь старого ответа"],
      ),
      sample: t(
        "Bu, bir adın nömrəsini soran sadə sətirdir. O, saytı köçürmür və qeydi dəyişmir.",
        "This is a simple line that asks for a name's number. It does not move the site and it does not change the record.",
        "Bu, bir adın numarasını soran sade bir satırdır. Siteyi taşımaz ve kaydı değiştirmez.",
        "هذا سطر بسيط يسأل عن رقم اسم. لا ينقل الموقع ولا يغيّر السجل.",
        "Это простая строка, которая спрашивает номер имени. Она не переносит сайт и не меняет запись.",
      ),
      code: `nibrascode.com.  A  203.0.113.10`,
      faq: lines(
        ["DNS və HTTP eynidir? Xeyr. DNS adı nömrəyə çevirir. HTTP həmin nömrədəki serverdən səhifəni istəyir.", "Qeydi dəyişəndə sayt dərhal hər yerdə açılır? Həmişə yox. Köhnə cavab bir müddət qala bilər.", "DNS faylı köçürür? Xeyr. Yalnız adın hara baxdığını deyir."],
        ["Are DNS and HTTP the same? No. DNS turns a name into a number. HTTP asks the server at that number for the page.", "When you change a record, does the site open everywhere at once? Not always. An old answer can stay for a while.", "Does DNS move the file? No. It only says where the name looks."],
        ["DNS ve HTTP aynı mı? Hayır. DNS adı numaraya çevirir. HTTP o numaradaki sunucudan sayfayı ister.", "Kayıt değişince site hemen her yerde açılır mı? Her zaman değil. Eski cevap bir süre kalabilir.", "DNS dosyayı taşır mı? Hayır. Yalnız adın nereye baktığını söyler."],
        ["هل DNS وHTTP الشيء نفسه؟ لا. DNS يحوّل الاسم إلى رقم. HTTP يطلب الصفحة من الخادم على ذلك الرقم.", "حين تغيّر السجل هل يُفتح الموقع في كل مكان فوراً؟ ليس دائماً. الجواب القديم قد يبقى مدة.", "هل ينقل DNS الملف؟ لا. يقول فقط أين ينظر الاسم."],
        ["DNS и HTTP — одно и то же? Нет. DNS переводит имя в номер. HTTP просит страницу у сервера по этому номеру.", "Когда запись меняют, сайт сразу открывается везде? Не всегда. Старый ответ может ещё побыть.", "DNS переносит файл? Нет. Он только говорит, куда смотрит имя."],
      ),
    },
  ),
];
