import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_PLAIN: readonly StackPage[] = [
  topic(
    "postgresql",
    "PostgreSQL",
    t("PostgreSQL nədir?", "What is PostgreSQL?", "PostgreSQL nedir?", "ما هو PostgreSQL؟", "Что такое PostgreSQL?"),
    t(
      "PostgreSQL məlumatı cədvəldə saxlayan serverdir. Bir fayl deyil. MySQL da serverdir, amma başqa proqramdır. SQLite isə ayrı server açmır.",
      "PostgreSQL is a server that keeps data in tables. It is not one file. MySQL is also a server, but it is another program. SQLite does not open a separate server.",
      "PostgreSQL, veriyi tabloda tutan sunucudur. Bir dosya değildir. MySQL de sunucudur, ama başka programdır. SQLite ise ayrı sunucu açmaz.",
      "PostgreSQL خادم يحفظ البيانات في جداول. ليس ملفاً واحداً. MySQL خادم أيضاً لكنه برنامج آخر. SQLite لا يفتح خادماً منفصلاً.",
      "PostgreSQL — сервер, который хранит данные в таблицах. Это не один файл. MySQL тоже сервер, но другая программа. SQLite отдельный сервер не открывает.",
    ),
    t("PostgreSQL nədir, Postgres, cədvəl, MySQL, SQLite", "what is PostgreSQL, Postgres, table, MySQL, SQLite", "PostgreSQL nedir, Postgres, tablo, MySQL", "ما هو PostgreSQL, Postgres, MySQL", "что такое PostgreSQL, Postgres, MySQL"),
    {
      what: t(
        "PostgreSQL-in əsli Berkeley-də Michael Stonebraker-in POSTGRES işidir. SQL ilə danışan açıq variant 1996-cı ildə PostgreSQL adını alıb. Qısa adı Postgres-dir. Proqram ayrıca işləyir və portu adətən 5432-dir. Sən ona qoşulursan, cədvəl açırsan, sətir yazırsan və şərtə görə oxuyursan. Məlumat diskin üstündə qalır. Maşın sönüb yananda, yazılmış sətir itmir. Bunu özü bir .db faylı kimi əlinə vermir. Ehtiyat nüsxə ayrıca əmrlə çıxarılır.",
        "PostgreSQL comes from Michael Stonebraker's POSTGRES work at Berkeley. The open form that speaks SQL took the name PostgreSQL in 1996. The short name is Postgres. The program runs on its own, and its port is usually 5432. You connect to it, open a table, write a row, and read by a condition. The data stays on disk. When the machine turns off and on, a written row does not vanish. It does not hand you that as one .db file. A backup is taken with a separate command.",
        "PostgreSQL’in kökü Berkeley’de Michael Stonebraker’in POSTGRES işidir. SQL ile konuşan açık biçim 1996’da PostgreSQL adını aldı. Kısa adı Postgres’tir. Program kendi çalışır ve portu genellikle 5432’dir. Ona bağlanır, tablo açar, satır yazarsın ve koşula göre okursun. Veri diskin üstünde kalır. Makine kapanıp açılınca yazılmış satır gitmez. Bunu sana bir .db dosyası gibi vermez. Yedek ayrı komutla alınır.",
        "أصل PostgreSQL عمل POSTGRES لـ Michael Stonebraker في Berkeley. الشكل المفتوح الذي يتكلم SQL أخذ اسم PostgreSQL سنة 1996. الاسم القصير Postgres. البرنامج يعمل وحده ومنفذه عادة 5432. تتصل به وتفتح جدولاً وتكتب صفاً وتقرأ بشرط. البيانات تبقى على القرص. حين ينطفئ الجهاز ويعود لا يذهب الصف المكتوب. هو لا يعطيك ذلك كملف .db واحد. النسخة الاحتياطية تُؤخذ بأمر منفصل.",
        "Основа PostgreSQL — работа POSTGRES Майкла Стоунбрейкера в Беркли. Открытый вид, который говорит на SQL, получил имя PostgreSQL в 1996 году. Короткое имя — Postgres. Программа работает сама, порт обычно 5432. Ты подключаешься, открываешь таблицу, пишешь строку и читаешь по условию. Данные остаются на диске. Когда машина выключается и включается, записанная строка не пропадает. Он не отдаёт это тебе одним файлом .db. Резервную копию снимают отдельной командой.",
      ),
      uses: t(
        "PostgreSQL çox adamın eyni anda yazdığı məlumat üçündür. Sifariş, istifadəçi və hesab onun yeridir.",
        "PostgreSQL is for data that many people write at the same time. An order, a user, and an account are its place.",
        "PostgreSQL çok kişinin aynı anda yazdığı veri içindir. Sipariş, kullanıcı ve hesap onun yeridir.",
        "PostgreSQL للبيانات التي يكتبها كثيرون في الوقت نفسه. الطلب والمستخدم والحساب مكانه.",
        "PostgreSQL нужен для данных, которые много людей пишут одновременно. Заказ, пользователь и счёт — его место.",
      ),
      useList: lines(
        ["Saytın istifadəçi siyahısını saxlamaq", "Sifarişi sətir-sətir yazmaq", "Eyni cədvəli bir neçə proqramın oxuması", "Hesabat üçün şərtli sorğu yazmaq"],
        ["Keeping a site's user list", "Writing an order row by row", "Letting several programs read the same table", "Writing a conditional query for a report"],
        ["Sitenin kullanıcı listesini tutmak", "Siparişi satır satır yazmak", "Aynı tabloyu birkaç programın okuması", "Rapor için koşullu sorgu yazmak"],
        ["حفظ قائمة مستخدمي الموقع", "كتابة الطلب صفاً صفاً", "قراءة الجدول نفسه من عدة برامج", "كتابة طلب بشرط لتقرير"],
        ["Хранить список пользователей сайта", "Писать заказ строка за строкой", "Дать нескольким программам читать одну таблицу", "Писать условный запрос для отчёта"],
      ),
      can: t(
        "PostgreSQL ilə cədvəl yaradırsan, sətir əlavə edir və seçirsən. O, səhifəni çəkmir və Python-u işlətmir. Proqram ona sorğu göndərir, o cavabı qaytarır. Çox yazan olanda növbə saxlayır ki, iki nəfər eyni sətiri korlamasın. Şifrəsiz açıq qoymaq olmaz. Şəbəkədən hər kəsə açmaq da olmaz.",
        "With PostgreSQL you create a table, add a row, and choose. It does not draw a page and it does not run Python. A program sends it a query, and it returns the answer. When many people write, it keeps a turn so two people do not spoil the same row. Do not leave it open without a password. Do not open it to everyone from the network either.",
        "PostgreSQL ile tablo yaratır, satır ekler ve seçersin. Sayfayı çizmez ve Python çalıştırmaz. Program ona sorgu gönderir, o cevabı döndürür. Çok yazan olunca sıra tutar ki iki kişi aynı satırı bozmasın. Parolasız açık bırakmamak gerekir. Ağdan herkese açmamak da gerekir.",
        "بـ PostgreSQL تنشئ جدولاً وتضيف صفاً وتختار. لا يرسم صفحة ولا يشغّل Python. البرنامج يرسل له طلباً وهو يرجع الجواب. حين يكتب كثيرون يحفظ دوراً كي لا يفسد اثنان الصف نفسه. لا تتركه مفتوحاً بلا كلمة مرور. ولا تفتحه لكل أحد من الشبكة.",
        "В PostgreSQL создают таблицу, добавляют строку и выбирают. Страницу он не рисует и Python не запускает. Программа шлёт ему запрос, он возвращает ответ. Когда пишут многие, он держит очередь, чтобы двое не испортили одну строку. Без пароля его не оставляют. Из сети всем подряд тоже не открывают.",
      ),
      hard: t(
        "Bir cədvəl açmaq asandır. Çətinlik əlaqə və sorğudadır. Səhv istifadəçi və ya səhv port olanda proqram heç qoşula bilmir. Sorğuya istifadəçinin yazısını yapışdırmaq inyeksiya açır. Böyük cədvəldə şərtsiz oxumaq yavaş olur. Ehtiyat nüsxə alınmazsa disk xətası sətirləri aparır. MySQL üçün yazılmış sorğu burada hər sözü ilə işləməyə bilər.",
        "Opening one table is easy. The difficulty is the connection and the query. When the user or the port is wrong, the program cannot connect at all. Pasting a user's text into the query opens injection. Reading a large table without a condition becomes slow. If a backup is not taken, a disk error takes the rows away. A query written for MySQL may not work here with every word.",
        "Bir tablo açmak kolaydır. Zorluk bağlantı ve sorgudadır. Kullanıcı veya port yanlışsa program hiç bağlanamaz. Sorguya kullanıcının yazısını yapıştırmak enjeksiyon açar. Büyük tabloda koşulsuz okumak yavaş olur. Yedek alınmazsa disk hatası satırları götürür. MySQL için yazılmış sorgu burada her sözüyle çalışmayabilir.",
        "فتح جدول واحد سهل. الصعوبة في الاتصال والطلب. إذا أخطأ المستخدم أو المنفذ لا يتصل البرنامج أصلاً. لصق نص المستخدم في الطلب يفتح الحقن. قراءة جدول كبير بلا شرط تصير بطيئة. إذا لم تُؤخذ نسخة فخطأ القرص يأخذ الصفوف. طلب كُتب لـ MySQL قد لا يعمل هنا بكل كلمة.",
        "Открыть одну таблицу легко. Трудность в соединении и в запросе. Если пользователь или порт неверны, программа вообще не подключается. Вставка текста пользователя в запрос открывает инъекцию. Чтение большой таблицы без условия становится медленным. Если копию не снять, ошибка диска уносит строки. Запрос, написанный для MySQL, здесь может не сработать каждым словом.",
      ),
      balance: t(
        "Üstünlük: çox adam yaza bilir, məlumat diskdə qalır, sorğu güclüdür. Məhdudiyyət: serveri qurmaq və qorumaq lazımdır. PostgreSQL MySQL deyil və SQLite deyil.",
        "Advantage: many people can write, the data stays on disk, and the query is strong. Limit: the server has to be set up and guarded. PostgreSQL is not MySQL and it is not SQLite.",
        "Avantaj: çok kişi yazabilir, veri diskte kalır, sorgu güçlüdür. Sınır: sunucuyu kurmak ve korumak gerekir. PostgreSQL, MySQL değildir ve SQLite değildir.",
        "الميزة: كثيرون يقدرون أن يكتبوا والبيانات تبقى على القرص والطلب قوي. الحد: يجب إعداد الخادم وحمايته. PostgreSQL ليس MySQL وليس SQLite.",
        "Плюс: много людей могут писать, данные остаются на диске, запрос сильный. Ограничение: сервер нужно поставить и беречь. PostgreSQL — не MySQL и не SQLite.",
      ),
      ideas: t(
        "Cədvəl sütunların adıdır. Sətir bir qeyddir. Server isə həmin cədvəli açıq saxlayan proqramdır.",
        "A table is the names of the columns. A row is one record. The server is the program that keeps that table open.",
        "Tablo sütunların adıdır. Satır bir kayıttır. Sunucu ise o tabloyu açık tutan programdır.",
        "الجدول أسماء الأعمدة. الصف سجل واحد. الخادم البرنامج الذي يبقي ذلك الجدول مفتوحاً.",
        "Таблица — имена столбцов. Строка — одна запись. Сервер — программа, которая держит эту таблицу открытой.",
      ),
      ideaList: lines(
        ["Ayrı proses kimi işləyir", "Port adətən 5432-dir", "SQL sorğusu sətir seçir", "Ehtiyat nüsxə özü alınmır"],
        ["It runs as its own process", "The port is usually 5432", "An SQL query chooses rows", "A backup is not taken by itself"],
        ["Kendi süreci gibi çalışır", "Port genellikle 5432’dir", "SQL sorgusu satır seçer", "Yedek kendi alınmaz"],
        ["يعمل كعملية وحده", "المنفذ عادة 5432", "طلب SQL يختار الصفوف", "النسخة الاحتياطية لا تُؤخذ وحدها"],
        ["Работает своим процессом", "Порт обычно 5432", "Запрос SQL выбирает строки", "Копия сама не снимается"],
      ),
      sample: t(
        "Bu sorğu bir cədvəl açır. Server artıq işləməlidir. Faylı əlinlə yaratmırsan.",
        "This query opens one table. The server must already be running. You do not create the file by hand.",
        "Bu sorgu bir tablo açar. Sunucu zaten çalışmalıdır. Dosyayı elinle yaratmazsın.",
        "هذا الطلب يفتح جدولاً. يجب أن يكون الخادم يعمل من قبل. لا تنشئ الملف بيدك.",
        "Этот запрос открывает одну таблицу. Сервер уже должен работать. Файл руками не создают.",
      ),
      code: `CREATE TABLE reader (
  id integer PRIMARY KEY,
  name text
);`,
      faq: lines(
        ["PostgreSQL və MySQL eynidir? Xeyr. İkisi də SQL serveridir. Proqram ayrıdır və hər sorğu sözü eyni işləməyə bilər.", "PostgreSQL və SQLite eynidir? Xeyr. SQLite bir fayldır və ayrı server açmır. PostgreSQL öz prosesində işləyir.", "Postgres başqa bir bazadır? Xeyr. Postgres, PostgreSQL-in qısa adıdır."],
        ["Are PostgreSQL and MySQL the same? No. Both are SQL servers. The program is separate, and every query word may not work the same.", "Are PostgreSQL and SQLite the same? No. SQLite is one file and does not open a separate server. PostgreSQL runs in its own process.", "Is Postgres another database? No. Postgres is the short name of PostgreSQL."],
        ["PostgreSQL ve MySQL aynı mı? Hayır. İkisi de SQL sunucusudur. Program ayrıdır ve her sorgu sözü aynı çalışmayabilir.", "PostgreSQL ve SQLite aynı mı? Hayır. SQLite bir dosyadır ve ayrı sunucu açmaz. PostgreSQL kendi sürecinde çalışır.", "Postgres başka bir taban mı? Hayır. Postgres, PostgreSQL’in kısa adıdır."],
        ["هل PostgreSQL وMySQL الشيء نفسه؟ لا. كلاهما خادم SQL. البرنامج منفصل وقد لا تعمل كل كلمة في الطلب الشيء نفسه.", "هل PostgreSQL وSQLite الشيء نفسه؟ لا. SQLite ملف واحد ولا يفتح خادماً منفصلاً. PostgreSQL يعمل في عمليته.", "هل Postgres قاعدة أخرى؟ لا. Postgres الاسم القصير لـ PostgreSQL."],
        ["PostgreSQL и MySQL — одно и то же? Нет. Оба — серверы SQL. Программа другая, и каждое слово запроса может работать не так.", "PostgreSQL и SQLite — одно и то же? Нет. SQLite — один файл и отдельный сервер не открывает. PostgreSQL работает в своём процессе.", "Postgres — другая база? Нет. Postgres — короткое имя PostgreSQL."],
      ),
    },
  ),
  topic(
    "markdown",
    "Markdown",
    t("Markdown nədir?", "What is Markdown?", "Markdown nedir?", "ما هو Markdown؟", "Что такое Markdown?"),
    t(
      "Markdown mətni sadə işarələrlə yazmağın yoludur. Proqramlaşdırma dili deyil. HTML teq işlədir. Markdown isə # və * kimi qısa işarə işlədir.",
      "Markdown is a way to write text with simple marks. It is not a programming language. HTML uses tags. Markdown uses a short mark such as # and *.",
      "Markdown, metni basit işaretlerle yazmanın yoludur. Programlama dili değildir. HTML etiket kullanır. Markdown ise # ve * gibi kısa işaret kullanır.",
      "Markdown طريقة لكتابة النص بعلامات بسيطة. ليست لغة برمجة. HTML يستخدم وسوماً. Markdown يستخدم علامة قصيرة مثل # و*.",
      "Markdown — способ писать текст простыми знаками. Это не язык программирования. HTML использует теги. Markdown использует короткий знак, например # и *.",
    ),
    t("Markdown nədir, Markdown yazı, README, HTML", "what is Markdown, Markdown writing, README, HTML", "Markdown nedir, Markdown yazı, README", "ما هو Markdown, كتابة, README", "что такое Markdown, текст, README"),
    {
      what: t(
        "Markdown-u John Gruber 2004-cü ildə yazılıb. Aaron Swartz də ilk işdə kömək edib. Məqsəd adi mətni oxunaqlı saxlamaq və lazım olanda ondan HTML çıxarmaq idi. Başlıq sətirin əvvəlində # ilə yazılır. Qalın mətn iki ulduzun arasında durur. Siyahı tire və ya ulduzla başlayır. Keçid mətn və ünvanı mötərizədə göstərir. Faylın özü heç nə işlətmir. Onu oxuyan sayt və ya proqram HTML-ə çevirir. Hər sayt eyni xırdalığı eyni oxumur. Buna görə bir yerdə işləyən cədvəl başqa yerdə düz çıxmaya bilər.",
        "John Gruber wrote Markdown in 2004. Aaron Swartz also helped in the first work. The aim was to keep plain text readable and, when needed, to make HTML from it. A heading is written with # at the start of the line. Bold text sits between two stars. A list starts with a dash or a star. A link shows the text and the address in brackets. The file itself runs nothing. The site or program that reads it turns it into HTML. Not every site reads the same small detail the same way. That is why a table that works in one place may not come out right in another.",
        "Markdown’u John Gruber 2004’te yazdı. Aaron Swartz de ilk işte yardım etti. Amaç düz metni okunur tutmak ve gerektiğinde ondan HTML çıkarmaktı. Başlık satırın başında # ile yazılır. Kalın metin iki yıldızın arasında durur. Liste tire veya yıldızla başlar. Bağlantı metni ve adresi parantezde gösterir. Dosyanın kendisi hiçbir şey çalıştırmaz. Onu okuyan site veya program HTML’e çevirir. Her site aynı ayrıntıyı aynı okumaz. Bu yüzden bir yerde çalışan tablo başka yerde düz çıkmayabilir.",
        "كتب John Gruber صيغة Markdown سنة 2004. ساعد Aaron Swartz أيضاً في العمل الأول. القصد كان إبقاء النص العادي مقروءاً وإخراج HTML منه حين يلزم. العنوان يُكتب بـ # في أول السطر. النص الغليظ يقف بين نجمتين. القائمة تبدأ بشرطة أو نجمة. الرابط يُظهر النص والعنوان بين قوسين. الملف نفسه لا يشغّل شيئاً. الموقع أو البرنامج الذي يقرأه يحوّله إلى HTML. ليس كل موقع يقرأ التفصيل الصغير نفسه بالطريقة نفسها. لذلك جدول يعمل في مكان قد لا يخرج سليماً في مكان آخر.",
        "Markdown написал Джон Грубер в 2004 году. Аарон Шварц тоже помогал в первой работе. Цель была сохранить обычный текст читаемым и, когда нужно, получить из него HTML. Заголовок пишут с # в начале строки. Жирный текст стоит между двумя звёздами. Список начинается с тире или звёздочки. Ссылка показывает текст и адрес в скобках. Сам файл ничего не запускает. Сайт или программа, которые его читают, превращают его в HTML. Не каждый сайт читает одну и ту же мелочь одинаково. Поэтому таблица, которая работает в одном месте, в другом может выйти криво.",
      ),
      uses: t(
        "Markdown qeyd, README və sadə sənəd üçündür. Oxuyan adam işarəni də görür, təmiz mətni də.",
        "Markdown is for a note, a README, and a simple document. The person who reads it sees the mark and the clean text.",
        "Markdown not, README ve sade belge içindir. Okuyan kişi işareti de görür, temiz metni de.",
        "Markdown للملاحظة وREADME والمستند البسيط. من يقرأ يرى العلامة والنص النظيف.",
        "Markdown нужен для заметки, README и простого документа. Читающий видит и знак, и чистый текст.",
      ),
      useList: lines(
        ["Layihənin README faylını yazmaq", "Qısa dərs qeydini saxlamaq", "Başlığı və siyahını tez yazmaq", "Mətni sonra HTML-ə çevirmək"],
        ["Writing a project's README file", "Keeping a short lesson note", "Writing a heading and a list quickly", "Turning the text into HTML later"],
        ["Projenin README dosyasını yazmak", "Kısa ders notunu tutmak", "Başlığı ve listeyi tez yazmak", "Metni sonra HTML’e çevirmek"],
        ["كتابة ملف README للمشروع", "حفظ ملاحظة درس قصيرة", "كتابة عنوان وقائمة بسرعة", "تحويل النص إلى HTML لاحقاً"],
        ["Писать файл README проекта", "Хранить короткую заметку урока", "Быстро писать заголовок и список", "Потом превратить текст в HTML"],
      ),
      can: t(
        "Markdown ilə başlıq, siyahı, qalın mətn və keçid yazırsan. O, düyməni işlətmir və rəngi özü seçmir. Sayt onu HTML-ə çevirəndə görünüş saytın qaydasından gəlir. Şəkil üçün ünvan yazılır. Həmin ünvan səhvdirsə şəkil açılmır. Proqram kodu bu faylda işləmir. Kod nümunəsi yalnız göstərmək üçündür.",
        "With Markdown you write a heading, a list, bold text, and a link. It does not run a button and it does not pick the color itself. When a site turns it into HTML, the look comes from the site's rule. An address is written for an image. If that address is wrong, the image does not open. Program code does not run in this file. A code sample is only for showing.",
        "Markdown ile başlık, liste, kalın metin ve bağlantı yazarsın. Düğmeyi çalıştırmaz ve rengi kendi seçmez. Site onu HTML’e çevirince görünüş sitenin kuralından gelir. Resim için adres yazılır. O adres yanlışsa resim açılmaz. Program kodu bu dosyada çalışmaz. Kod örneği yalnız göstermek içindir.",
        "بـ Markdown تكتب عنواناً وقائمة ونصاً غليظاً ورابطاً. لا يشغّل زراً ولا يختار اللون بنفسه. حين يحوّله الموقع إلى HTML يأتي الشكل من قاعدة الموقع. للصورة يُكتب عنوان. إذا أخطأ العنوان لا تفتح الصورة. كود البرنامج لا يعمل في هذا الملف. مثال الكود للعرض فقط.",
        "В Markdown пишут заголовок, список, жирный текст и ссылку. Кнопку он не запускает и цвет сам не выбирает. Когда сайт превращает его в HTML, вид берётся из правила сайта. Для картинки пишут адрес. Если адрес неверный, картинка не открывается. Код программы в этом файле не выполняется. Пример кода только для показа.",
      ),
      hard: t(
        "Bir başlıq yazmaq asandır. Çətinlik boş sətirdə və sayt fərqindədir. Siyahıdan əvvəl boş sətir qoyulmasa bəzi oxuyanlar onu adi mətn sayır. Ulduzun sayı qalın və əyri mətni qarışdırır. Cədvəl hər yerdə eyni deyil. HTML-i içinə yapışdırmaq bəzi saytda işləyir, bəzində silinir. Buna görə eyni faylı hədəf saytda bir də açmaq lazımdır.",
        "Writing one heading is easy. The difficulty is the blank line and the difference between sites. If a blank line is not put before a list, some readers count it as plain text. The number of stars mixes bold and slanted text. A table is not the same everywhere. Pasting HTML inside works on some sites and is removed on others. That is why the same file has to be opened once on the target site.",
        "Bir başlık yazmak kolaydır. Zorluk boş satırda ve site farkındadır. Listeden önce boş satır konmazsa bazı okuyanlar onu düz metin sayar. Yıldızın sayısı kalın ve eğik metni karıştırır. Tablo her yerde aynı değildir. HTML’i içine yapıştırmak bazen sitede çalışır, bazen silinir. Bu yüzden aynı dosyayı hedef sitede bir kez daha açmak gerekir.",
        "كتابة عنوان واحد سهلة. الصعوبة في السطر الفارغ وفرق المواقع. إذا لم يوضع سطر فارغ قبل القائمة يحسبها بعض القراء نصاً عادياً. عدد النجوم يخلط النص الغليظ والمائل. الجدول ليس نفسه في كل مكان. لصق HTML داخله يعمل في بعض المواقع ويُحذف في غيرها. لذلك يجب فتح الملف نفسه مرة على الموقع المقصود.",
        "Написать один заголовок легко. Трудность в пустой строке и в разнице сайтов. Если перед списком не поставить пустую строку, некоторые читатели считают его обычным текстом. Число звёзд путает жирный и наклонный текст. Таблица не везде одна и та же. Вставка HTML внутрь на одном сайте работает, на другом удаляется. Поэтому тот же файл нужно один раз открыть на нужном сайте.",
      ),
      balance: t(
        "Üstünlük: mətn təmiz qalır, işarə azdır, bir çox sayt onu oxuyur. Məhdudiyyət: hər saytın xırda qaydası eyni deyil. Markdown HTML deyil və proqram deyil.",
        "Advantage: the text stays clean, the marks are few, and many sites read it. Limit: every site's small rule is not the same. Markdown is not HTML and it is not a program.",
        "Avantaj: metin temiz kalır, işaret azdır, birçok site onu okur. Sınır: her sitenin küçük kuralı aynı değildir. Markdown, HTML değildir ve program değildir.",
        "الميزة: النص يبقى نظيفاً والعلامات قليلة وكثير من المواقع تقرأه. الحد: القاعدة الصغيرة ليست نفسها في كل موقع. Markdown ليس HTML وليس برنامجاً.",
        "Плюс: текст остаётся чистым, знаков мало, многие сайты его читают. Ограничение: мелкое правило не одно на каждом сайте. Markdown — не HTML и не программа.",
      ),
      ideas: t(
        "İşarə mətnin rolunu deyir. Boş sətir yeni bloku ayırır. Çevirən proqram isə bundan HTML çıxarır.",
        "A mark says the role of the text. A blank line splits a new block. The program that converts it makes HTML from this.",
        "İşaret metnin rolünü söyler. Boş satır yeni bloğu ayırır. Çeviren program ise bundan HTML çıkarır.",
        "العلامة تقول دور النص. السطر الفارغ يفصل كتلة جديدة. البرنامج الذي يحوّل يخرج من هذا HTML.",
        "Знак говорит роль текста. Пустая строка отделяет новый блок. Программа, которая переводит, делает из этого HTML.",
      ),
      ideaList: lines(
        ["# başlıqdır", "Tire siyahı maddəsidir", "İki ulduz mətni qalın edir", "Fayl özü səhifə açmır"],
        ["# is a heading", "A dash is a list item", "Two stars make text bold", "The file itself does not open a page"],
        ["# başlıktır", "Tire liste maddesidir", "İki yıldız metni kalın eder", "Dosya kendi sayfa açmaz"],
        ["# عنوان", "الشرطة بند قائمة", "نجمتان تجعلان النص غليظاً", "الملف نفسه لا يفتح صفحة"],
        ["# — это заголовок", "Тире — пункт списка", "Две звезды делают текст жирным", "Сам файл страницу не открывает"],
      ),
      sample: t(
        "Bu, bir başlıq və bir siyahı yazır. Səhifəni özü çəkmir.",
        "This writes one heading and one list. It does not draw the page itself.",
        "Bu, bir başlık ve bir liste yazar. Sayfayı kendi çizmez.",
        "هذا يكتب عنواناً وقائمة. لا يرسم الصفحة بنفسه.",
        "Это пишет один заголовок и один список. Страницу само не рисует.",
      ),
      code: `# Qeyd

- birinci
- ikinci`,
      faq: lines(
        ["Markdown və HTML eynidir? Xeyr. HTML teq işlədir. Markdown qısa işarə işlədir. Proqram onu HTML-ə çevirə bilər.", "Markdown proqramlaşdırma dilidir? Xeyr. Yazını oxunaqlı saxlayır. Düyməni və hesabı işlətmir.", "Hər saytda eyni görünür? Yox. Əsas işarələr yaxındır. Cədvəl və bəzi xırdalıq saytdan sayta dəyişir."],
        ["Are Markdown and HTML the same? No. HTML uses tags. Markdown uses a short mark. A program can turn it into HTML.", "Is Markdown a programming language? No. It keeps writing readable. It does not run a button or a calculation.", "Does it look the same on every site? No. The main marks are close. A table and some small details change from site to site."],
        ["Markdown ve HTML aynı mı? Hayır. HTML etiket kullanır. Markdown kısa işaret kullanır. Program onu HTML’e çevirebilir.", "Markdown programlama dili mi? Hayır. Yazıyı okunur tutar. Düğmeyi ve hesabı çalıştırmaz.", "Her sitede aynı görünür mü? Hayır. Ana işaretler yakındır. Tablo ve bazı ayrıntı siteden siteye değişir."],
        ["هل Markdown وHTML الشيء نفسه؟ لا. HTML يستخدم وسوماً. Markdown يستخدم علامة قصيرة. برنامج يقدر أن يحوّله إلى HTML.", "هل Markdown لغة برمجة؟ لا. يبقي الكتابة مقروءة. لا يشغّل زراً ولا حساباً.", "هل يظهر نفسه في كل موقع؟ لا. العلامات الأساسية قريبة. الجدول وبعض التفاصيل تتغير من موقع إلى موقع."],
        ["Markdown и HTML — одно и то же? Нет. HTML использует теги. Markdown использует короткий знак. Программа может превратить его в HTML.", "Markdown — язык программирования? Нет. Он держит текст читаемым. Кнопку и счёт не запускает.", "На каждом сайте выглядит одинаково? Нет. Основные знаки близки. Таблица и некоторые мелочи меняются от сайта к сайту."],
      ),
    },
  ),
  topic(
    "rsync",
    "rsync",
    t("rsync nədir?", "What is rsync?", "rsync nedir?", "ما هو rsync؟", "Что такое rsync?"),
    t(
      "rsync faylı bir yerdən başqa yerə köçürən əmrdir. Artıq eyni olanı yenidən göndərməməyə çalışır. cp bütün faylı hər dəfə kopyalayır.",
      "rsync is a command that copies a file from one place to another. It tries not to send again what is already the same. cp copies the whole file every time.",
      "rsync, dosyayı bir yerden başka yere kopyalayan komuttur. Zaten aynı olanı yeniden göndermemeye çalışır. cp bütün dosyayı her sefer kopyalar.",
      "rsync أمر ينسخ ملفاً من مكان إلى آخر. يحاول ألا يرسل مرة أخرى ما هو نفسه من قبل. cp ينسخ الملف كله كل مرة.",
      "rsync — команда, которая копирует файл из одного места в другое. Она старается не отправлять заново то, что уже совпадает. cp копирует весь файл каждый раз.",
    ),
    t("rsync nədir, fayl köçürmə, ehtiyat nüsxə, cp", "what is rsync, file copy, backup, cp", "rsync nedir, dosya kopya, yedek, cp", "ما هو rsync, نسخ ملف, نسخة", "что такое rsync, копия файла, cp"),
    {
      what: t(
        "rsync-i Andrew Tridgell və Paul Mackerras yazılıb. İlk açıq danışıq 1996-cı ildir. Əmr iki qovluğu tutuşdurur. Dəyişməyən faylı buraxır. Dəyişən faylın yalnız fərqli hissəsini göndərə bilər. Buna görə böyük ağacın ikinci köçürməsi birincidən qısa olur. Uzaq maşına gedəndə yolu çox vaxt SSH aparır. rsync SSH-nin özü deyil. Yalnız onun üstündən fayl daşıyır. Sətrin sonundakı çəp xətt mənanı dəyişir. Qovluğun adından sonra çəp xətt qoymaq içinəkiləri köçürür. Qoymamaq qovluğun özünü də aparır.",
        "Andrew Tridgell and Paul Mackerras wrote rsync. The first open talk was in 1996. The command compares two folders. It skips a file that did not change. For a file that did change, it can send only the different part. That is why the second copy of a large tree is shorter than the first. When it goes to a far machine, SSH often carries the path. rsync is not SSH itself. It only carries the file over it. The slash at the end of the line changes the meaning. A slash after the folder name copies what is inside. Leaving it off also takes the folder itself.",
        "rsync’i Andrew Tridgell ve Paul Mackerras yazdı. İlk açık konuşma 1996’dır. Komut iki klasörü karşılaştırır. Değişmeyen dosyayı atlar. Değişen dosyanın yalnız farklı parçasını gönderebilir. Bu yüzden büyük ağacın ikinci kopyası birinciden kısa olur. Uzak makineye giderken yolu çoğu zaman SSH taşır. rsync, SSH’nin kendisi değildir. Yalnız onun üstünden dosya taşır. Satırın sonundaki eğik çizgi anlamı değiştirir. Klasör adından sonra eğik çizgi koymak içindekileri kopyalar. Koymamak klasörün kendisini de götürür.",
        "كتب rsync كل من Andrew Tridgell وPaul Mackerras. أول حديث مفتوح سنة 1996. الأمر يقارن مجلدين. يتخطى الملف الذي لم يتغير. للملف الذي تغيّر يقدر أن يرسل الجزء المختلف فقط. لذلك النسخة الثانية لشجرة كبيرة أقصر من الأولى. حين يذهب إلى جهاز بعيد كثيراً ما يحمل SSH الطريق. rsync ليس SSH نفسه. يحمل الملف فوقه فقط. الشرطة المائلة في آخر السطر تغيّر المعنى. وضع شرطة بعد اسم المجلد ينسخ ما في داخله. عدم وضعها يأخذ المجلد نفسه أيضاً.",
        "rsync написали Andrew Tridgell и Paul Mackerras. Первый открытый разговор был в 1996 году. Команда сравнивает две папки. Файл, который не менялся, она пропускает. У изменившегося файла может отправить только отличающуюся часть. Поэтому вторая копия большого дерева короче первой. Когда путь идёт на дальнюю машину, его часто несёт SSH. rsync — не сам SSH. Он только везёт файл поверх него. Косая черта в конце строки меняет смысл. Косая после имени папки копирует то, что внутри. Если её не поставить, уходит и сама папка.",
      ),
      uses: t(
        "rsync ehtiyat nüsxə və iki qovluğu eyni saxlamaq üçündür. Hər dəfə bütün diski köçürməmək üçündür.",
        "rsync is for a backup and for keeping two folders the same. It is so you do not copy the whole disk every time.",
        "rsync yedek ve iki klasörü aynı tutmak içindir. Her sefer bütün diski kopyalamamak içindir.",
        "rsync للنسخة الاحتياطية ولإبقاء مجلدين متماثلين. كي لا تنسخ القرص كله كل مرة.",
        "rsync нужен для резервной копии и чтобы две папки оставались одинаковыми. Чтобы не копировать весь диск каждый раз.",
      ),
      useList: lines(
        ["Sayt faylını başqa serverə aparmaq", "Hər gecə yalnız dəyişəni ehtiyata yazmaq", "İki qovluğu tutuşdurmaq", "Böyük faylın yarım köçürməsini davam etmək"],
        ["Taking a site's files to another server", "Writing only what changed into the backup each night", "Comparing two folders", "Continuing a large file's half-finished copy"],
        ["Site dosyasını başka sunucuya götürmek", "Her gece yalnız değişeni yedeğe yazmak", "İki klasörü karşılaştırmak", "Büyük dosyanın yarım kopyasını sürdürmek"],
        ["أخذ ملفات الموقع إلى خادم آخر", "كتابة المتغير فقط في النسخة كل ليلة", "مقارنة مجلدين", "متابعة نسخ ملف كبير بقي نصفه"],
        ["Унести файлы сайта на другой сервер", "Каждую ночь писать в копию только изменившееся", "Сравнить две папки", "Продолжить копирование большого файла, которое осталось на половине"],
      ),
      can: t(
        "rsync ilə qovluğu başqa yerə yaxın saxlayırsan. O, faylın içindəki proqramı işlətmir. Yalnız baytları aparır. --delete uzaqdakı artıq faylı silir. Bunu səhv qovluqda işlətmək oradakı faylları aparır. Əvvəl sınaq bayrağı ilə baxmaq lazımdır. Şifrə əmrin içinə yazılırsa tarixçədə qala bilər.",
        "With rsync you keep a folder close to another place. It does not run the program inside the file. It only carries the bytes. --delete removes the extra file on the far side. Running that on the wrong folder takes the files there away. Look first with the dry-run flag. If a password is written inside the command, it can stay in the history.",
        "rsync ile klasörü başka yere yakın tutarsın. Dosyanın içindeki programı çalıştırmaz. Yalnız baytları götürür. --delete uzaktaki fazla dosyayı siler. Bunu yanlış klasörde çalıştırmak oradaki dosyaları götürür. Önce deneme bayrağı ile bakmak gerekir. Parola komutun içine yazılırsa geçmişte kalabilir.",
        "بـ rsync تبقي المجلد قريباً من مكان آخر. لا يشغّل البرنامج داخل الملف. يحمل البايتات فقط. --delete يحذف الملف الزائد في الجهة البعيدة. تشغيل ذلك في المجلد الخطأ يأخذ الملفات هناك. انظر أولاً بعلم التجربة الجافة. إذا كُتبت كلمة المرور داخل الأمر فقد تبقى في السجل.",
        "Через rsync папку держат близкой к другому месту. Программу внутри файла он не запускает. Он только везёт байты. --delete удаляет лишний файл на дальней стороне. Запуск этого в неверной папке уносит файлы там. Сначала смотрят с флагом пробного прогона. Если пароль написан внутри команды, он может остаться в истории.",
      ),
      hard: t(
        "Bir qovluğu köçürmək asandır. Çətinlik çəp xətt və silmədədir. Sonda çəp xətt olub-olmaması başqa yerə yazır. --delete səhv hədəfdə işləyəndə geri qaytarmaq çətin olur. Uzaq maşının yolu və istifadəçisi səhvdirsə heç nə getmir. Saat fərqi bəzən təzə faylı köhnə sayır. Buna görə ilk dəfə silmədən və sınaqla baxılır.",
        "Copying one folder is easy. The difficulty is the slash and the delete. Whether the slash is at the end or not writes to another place. When --delete runs on the wrong target, bringing it back is hard. If the far machine's path or user is wrong, nothing goes. A clock difference sometimes counts a fresh file as old. That is why the first look is without delete and with a dry run.",
        "Bir klasörü kopyalamak kolaydır. Zorluk eğik çizgi ve silmededir. Sonda eğik çizgi olup olmaması başka yere yazar. --delete yanlış hedefte çalışınca geri getirmek zor olur. Uzak makinenin yolu veya kullanıcısı yanlışsa hiçbir şey gitmez. Saat farkı bazen taze dosyayı eski sayar. Bu yüzden ilk bakış silmeden ve denemeyle yapılır.",
        "نسخ مجلد واحد سهل. الصعوبة في الشرطة المائلة والحذف. وجود الشرطة في الآخر أو غيابها يكتب إلى مكان آخر. حين يعمل --delete على هدف خطأ يصعب الإرجاع. إذا أخطأ مسار الجهاز البعيد أو المستخدم لا يذهب شيء. فرق الساعة أحياناً يحسب الملف الجديد قديماً. لذلك النظرة الأولى بلا حذف وبتجربة.",
        "Скопировать одну папку легко. Трудность в косой черте и в удалении. Есть косая в конце или нет — пишет в другое место. Когда --delete работает на неверной цели, вернуть трудно. Если путь или пользователь дальней машины неверны, ничего не уходит. Разница часов иногда считает свежий файл старым. Поэтому первый взгляд — без удаления и с пробным прогоном.",
      ),
      balance: t(
        "Üstünlük: ikinci köçürmə qısa olur, dəyişməyən fayl təkrar getmir, uzaq serverə gedə bilir. Məhdudiyyət: səhv silmə geri çətin qayıdır. rsync cp deyil və SSH deyil.",
        "Advantage: the second copy is short, a file that did not change does not come again, and it can go to a far server. Limit: a wrong delete is hard to undo. rsync is not cp and it is not SSH.",
        "Avantaj: ikinci kopya kısa olur, değişmeyen dosya yeniden gelmez, uzak sunucuya gidebilir. Sınır: yanlış silme geri zor döner. rsync, cp değildir ve SSH değildir.",
        "الميزة: النسخة الثانية قصيرة والملف الذي لم يتغير لا يأتي مرة أخرى ويقدر أن يذهب إلى خادم بعيد. الحد: الحذف الخطأ يصعب إرجاعه. rsync ليس cp وليس SSH.",
        "Плюс: вторая копия короткая, неизменившийся файл не приходит снова, и можно уйти на дальний сервер. Ограничение: неверное удаление трудно вернуть. rsync — не cp и не SSH.",
      ),
      ideas: t(
        "Mənbə faylın çıxdığı yerdir. Hədəf getdiyi yerdir. Fərq isə artıq eyni olmayan hissədir.",
        "The source is where the file comes from. The target is where it goes. The difference is the part that is not already the same.",
        "Kaynak dosyanın çıktığı yerdir. Hedef gittiği yerdir. Fark ise zaten aynı olmayan parçadır.",
        "المصدر مكان خروج الملف. الهدف مكان ذهابه. الفرق الجزء الذي ليس نفسه من قبل.",
        "Источник — откуда файл выходит. Цель — куда он идёт. Разница — часть, которая уже не совпадает.",
      ),
      ideaList: lines(
        ["Dəyişməyən fayl buraxılır", "Çəp xətt qovluğun mənasını dəyişir", "--dry-run yalnız göstərir", "--delete hədəfdə artıq faylı silir"],
        ["A file that did not change is skipped", "A slash changes the folder's meaning", "--dry-run only shows", "--delete removes the extra file on the target"],
        ["Değişmeyen dosya atlanır", "Eğik çizgi klasörün anlamını değiştirir", "--dry-run yalnız gösterir", "--delete hedefte fazla dosyayı siler"],
        ["الملف الذي لم يتغير يُتخطى", "الشرطة المائلة تغيّر معنى المجلد", "--dry-run يُظهر فقط", "--delete يحذف الملف الزائد في الهدف"],
        ["Неизменившийся файл пропускается", "Косая черта меняет смысл папки", "--dry-run только показывает", "--delete удаляет лишний файл на цели"],
      ),
      sample: t(
        "Bu əmr bir qovluğun içinəkiləri başqa qovluğa yaxın saxlayır. Silmir. Yalnız göstərilən yola yazır.",
        "This command keeps the inside of one folder close to another folder. It does not delete. It only writes to the path you show.",
        "Bu komut bir klasörün içindekileri başka klasöre yakın tutar. Silmez. Yalnız gösterilen yola yazar.",
        "هذا الأمر يبقي داخل مجلد قريباً من مجلد آخر. لا يحذف. يكتب فقط إلى المسار الذي تُظهره.",
        "Эта команда держит содержимое одной папки близким к другой папке. Не удаляет. Пишет только в путь, который ты показываешь.",
      ),
      code: `rsync -a source/ backup/`,
      faq: lines(
        ["rsync və cp eynidir? Xeyr. cp faylı olduğu kimi kopyalayır. rsync dəyişməyəni buraxmağa və fərqli hissəni göndərməyə çalışır.", "rsync və SSH eynidir? Xeyr. SSH uzaq maşına girir. rsync fayl daşıyır və yolu SSH apara bilər.", "Çəp xətt vacibdir? Bəli. source/ içinəkiləri aparır. source qovluğun özünü də aparır."],
        ["Are rsync and cp the same? No. cp copies the file as it is. rsync tries to skip what did not change and to send the different part.", "Are rsync and SSH the same? No. SSH enters a far machine. rsync carries the file, and SSH can carry the path.", "Does the slash matter? Yes. source/ takes what is inside. source also takes the folder itself."],
        ["rsync ve cp aynı mı? Hayır. cp dosyayı olduğu gibi kopyalar. rsync değişmeyeni atlamaya ve farklı parçayı göndermeye çalışır.", "rsync ve SSH aynı mı? Hayır. SSH uzak makineye girer. rsync dosya taşır ve yolu SSH taşıyabilir.", "Eğik çizgi önemli mi? Evet. source/ içindekileri götürür. source klasörün kendisini de götürür."],
        ["هل rsync وcp الشيء نفسه؟ لا. cp ينسخ الملف كما هو. rsync يحاول أن يتخطى ما لم يتغير ويرسل الجزء المختلف.", "هل rsync وSSH الشيء نفسه؟ لا. SSH يدخل جهازاً بعيداً. rsync يحمل الملف وSSH يقدر أن يحمل الطريق.", "هل الشرطة المائلة مهمة؟ نعم. source/ يأخذ ما في الداخل. source يأخذ المجلد نفسه أيضاً."],
        ["rsync и cp — одно и то же? Нет. cp копирует файл как есть. rsync старается пропустить неизменившееся и отправить отличающуюся часть.", "rsync и SSH — одно и то же? Нет. SSH входит на дальнюю машину. rsync везёт файл, а путь может нести SSH.", "Косая черта важна? Да. source/ забирает то, что внутри. source забирает и саму папку."],
      ),
    },
  ),
];
