import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_NET: readonly StackPage[] = [
  topic(
    "capacitor",
    "Capacitor",
    t("Capacitor nədir?", "What is Capacitor?", "Capacitor nedir?", "ما هو Capacitor؟", "Что такое Capacitor?"),
    t(
      "Capacitor veb tətbiqi iOS və Android qabığına qoyan alətdir. HTML, CSS və JavaScript qalır, native imkan plugin ilə açılır.",
      "Capacitor puts a web app into an iOS and Android shell. HTML, CSS, and JavaScript stay. A native capability opens through a plugin.",
      "Capacitor, web uygulamasını iOS ve Android kabuğuna koyan araçtır. HTML, CSS ve JavaScript kalır, yerel olanak eklenti ile açılır.",
      "Capacitor يضع تطبيق الويب في غلاف iOS وAndroid. يبقى HTML وCSS وJavaScript، وتُفتح قدرة الجهاز عبر إضافة.",
      "Capacitor кладёт веб-приложение в оболочку iOS и Android. HTML, CSS и JavaScript остаются, возможность устройства открывается через плагин.",
    ),
    t("Capacitor nədir, Capacitor Android, Ionic Capacitor, veb tətbiq qabığı", "what is Capacitor, Capacitor Android, Ionic Capacitor, web app shell", "Capacitor nedir, Capacitor Android, Ionic", "ما هو Capacitor, Capacitor Android, Ionic", "что такое Capacitor, Capacitor Android, Ionic"),
    {
      what: t(
        "Capacitor Ionic komandasının alətidir. Veb layihəni native layihənin içinə qoyur və WebView-də açır. Cordova-nın davamı sayılır, amma müasir native layihə ilə işləyir. Bu, React Native deyil: ekran native komponentə çevrilmir, veb olaraq qalır.",
        "Capacitor is a tool from the Ionic team. It puts a web project inside a native project and opens it in a WebView. It is treated as a successor to Cordova, but it works with a modern native project. It is not React Native: the screen is not turned into native components. It stays web.",
        "Capacitor, Ionic ekibinin aracıdır. Web projesini yerel projenin içine koyar ve WebView’de açar. Cordova’nın devamı sayılır, ama modern yerel projeyle çalışır. Bu React Native değildir: ekran yerel bileşene çevrilmez, web olarak kalır.",
        "Capacitor أداة من فريق Ionic. تضع مشروع الويب داخل مشروع أصلي وتفتحه في WebView. تُعد امتداداً لـ Cordova، لكنها تعمل مع مشروع أصلي حديث. ليست React Native: الشاشة لا تتحول إلى مكوّنات أصلية، تبقى ويب.",
        "Capacitor — инструмент команды Ionic. Он кладёт веб-проект внутрь нативного проекта и открывает его в WebView. Его считают продолжением Cordova, но он работает с современным нативным проектом. Это не React Native: экран не превращается в нативные компоненты, он остаётся вебом.",
      ),
      uses: t("Hazır veb tətbiqi mağazaya çıxarmaq və kameraya plugin ilə çatmaq üçündür.", "It is for shipping a finished web app to a store and reaching the camera through a plugin.", "Hazır web uygulamasını mağazaya çıkarmak ve kameraya eklenti ile ulaşmak içindir.", "هو لإخراج تطبيق ويب جاهز إلى المتجر والوصول إلى الكاميرا عبر إضافة.", "Он нужен, чтобы выпустить готовое веб-приложение в магазин и дойти до камеры через плагин."),
      useList: lines(
        ["Mövcud saytı tətbiq qabığına salmaq", "Android və iOS layihəsi yaratmaq", "Plugin ilə kamera və fayl", "Veb kodu ayrıca saxlamaq"],
        ["Putting an existing site into an app shell", "Creating an Android and iOS project", "Camera and files through a plugin", "Keeping the web code separate"],
        ["Mevcut siteyi uygulama kabuğuna almak", "Android ve iOS projesi oluşturmak", "Eklenti ile kamera ve dosya", "Web kodunu ayrı tutmak"],
        ["وضع موقع موجود في غلاف تطبيق", "إنشاء مشروع Android وiOS", "الكاميرا والملفات عبر إضافة", "إبقاء كود الويب منفصلاً"],
        ["Поместить готовый сайт в оболочку приложения", "Создать проект Android и iOS", "Камера и файлы через плагин", "Держать веб-код отдельно"],
      ),
      can: t(
        "Capacitor ilə bir veb kod bazasından iki mağaza layihəsi çıxır. Native düymə və ya mürəkkəb jest lazımdırsa, bu yol daralır. O zaman native və ya başqa çərçivə düzgün ola bilər.",
        "With Capacitor one web codebase produces two store projects. If you need a native button or a complex gesture, this path gets narrow. Then native code or another framework may be the right one.",
        "Capacitor ile bir web kod tabanından iki mağaza projesi çıkar. Yerel düğme veya karmaşık jest gerekirse bu yol daralır. O zaman yerel kod veya başka çatı doğru olabilir.",
        "مع Capacitor تخرج من قاعدة ويب واحدة مشروعان للمتجر. إذا لزم زر أصلي أو إيماءة معقدة يضيق هذا الطريق. عندها قد يكون الكود الأصلي أو إطار آخر هو الصحيح.",
        "С Capacitor из одной веб-базы выходят два проекта для магазина. Если нужна нативная кнопка или сложный жест, путь сужается. Тогда верным может быть нативный код или другой фреймворк.",
      ),
      hard: t(
        "Veb tərəfi bilən üçün başlanğıc asandır. Çətinlik native layihə, imza, plugin versiyası və mağaza qaydasıdır. npx cap copy veb build-i native tərəfə köçürməyi unutdurmur.",
        "For someone who knows the web, the start is easy. The difficulty is the native project, the signature, the plugin version, and the store rules. npx cap copy is what you must not forget when moving a web build to the native side.",
        "Web tarafını bilen için başlangıç kolaydır. Zorluk yerel proje, imza, eklenti sürümü ve mağaza kuralıdır. npx cap copy, web derlemesini yerel tarafa taşırken unutulmamalıdır.",
        "لمن يعرف الويب البداية سهلة. الصعوبة في المشروع الأصلي والتوقيع وإصدار الإضافة وقواعد المتجر. npx cap copy هو ما لا يُنسى عند نقل بناء الويب إلى الجانب الأصلي.",
        "Кто знает веб, тому старт лёгкий. Трудность в нативном проекте, подписи, версии плагина и правилах магазина. npx cap copy нельзя забывать, когда веб-сборку переносят на нативную сторону.",
      ),
      balance: t(
        "Üstünlük: bir veb komanda iki platforma çıxarır, plugin sərhədi aydındır. Məhdudiyyət: ağır animasiya və tam native hiss WebView-də zəif qala bilər. Offline və icazə ayrıca yoxlanmalıdır.",
        "Advantage: one web team ships two platforms, and the plugin boundary is clear. Limit: a heavy animation and a fully native feel can stay weak in a WebView. Offline mode and permissions must be checked separately.",
        "Avantaj: bir web ekip iki platforma çıkarır, eklenti sınırı açıktır. Sınır: ağır animasyon ve tam yerel his WebView’de zayıf kalabilir. Çevrimdışı ve izin ayrıca denetlenmelidir.",
        "الميزة: فريق ويب واحد يخرج منصتين، وحد الإضافة واضح. الحد: الرسوم الثقيلة والإحساس الأصلي الكامل قد يبقيان ضعيفين في WebView. وضع عدم الاتصال والأذونات يُفحصان وحدهما.",
        "Плюс: одна веб-команда выпускает две платформы, граница плагина ясная. Ограничение: тяжёлая анимация и полностью нативное ощущение могут остаться слабыми в WebView. Офлайн и разрешения надо проверять отдельно.",
      ),
      ideas: t(
        "Web dir veb build-in yeridir. Native layihə android və ios qovluğudur. Plugin JavaScript-dən native koda körpü salır.",
        "The web dir is where the web build lives. The native project is the android and ios folders. A plugin is a bridge from JavaScript to native code.",
        "Web dir, web derlemesinin yeridir. Yerel proje android ve ios klasörüdür. Eklenti JavaScript’ten yerel koda köprü kurar.",
        "مجلد web مكان بناء الويب. المشروع الأصلي مجلدا android وios. الإضافة جسر من JavaScript إلى الكود الأصلي.",
        "Каталог web — место веб-сборки. Нативный проект — папки android и ios. Плагин — мост из JavaScript в нативный код.",
      ),
      ideaList: lines(
        ["npx cap init konfiqurasiya yaradır", "npx cap add android native layihə əlavə edir", "npx cap sync veb və pluginləri köçürür", "WebView səhifəni tətbiqin içində açır"],
        ["npx cap init creates the config", "npx cap add android adds the native project", "npx cap sync copies the web build and plugins", "A WebView opens the page inside the app"],
        ["npx cap init yapılandırmayı yaratır", "npx cap add android yerel projeyi ekler", "npx cap sync web ve eklentileri taşır", "WebView sayfayı uygulamanın içinde açar"],
        ["npx cap init ينشئ الضبط", "npx cap add android يضيف المشروع الأصلي", "npx cap sync ينقل الويب والإضافات", "WebView يفتح الصفحة داخل التطبيق"],
        ["npx cap init создаёт настройку", "npx cap add android добавляет нативный проект", "npx cap sync переносит веб и плагины", "WebView открывает страницу внутри приложения"],
      ),
      sample: t("Bu əmrlər paketi qurur, layihəni adlandırır və Android tərəfini əlavə edir. Veb build əvvəlcə hazır olmalıdır.", "These commands install the package, name the project, and add the Android side. The web build should be ready first.", "Bu komutlar paketi kurar, projeyi adlandırır ve Android tarafını ekler. Web derlemesi önce hazır olmalıdır.", "هذه الأوامر تثبّت الحزمة وتسمّي المشروع وتضيف جانب Android. يجب أن يكون بناء الويب جاهزاً أولاً.", "Эти команды ставят пакет, называют проект и добавляют сторону Android. Веб-сборка должна быть готова раньше."),
      code: `npm install @capacitor/core @capacitor/cli
npx cap init
npx cap add android`,
      faq: lines(
        ["Capacitor dildir? Xeyr. Veb tətbiqi native qabığa qoyan alətdir.", "React Native ilə eynidir? Xeyr. Capacitor ekranı veb saxlayır.", "Plugin olmadan kamera açılır? Xeyr. Cihaz imkanı plugin və icazə istəyir."],
        ["Is Capacitor a language? No. It is the tool that puts a web app in a native shell.", "Is it the same as React Native? No. Capacitor keeps the screen as web.", "Does the camera open without a plugin? No. A device capability needs a plugin and a permission."],
        ["Capacitor bir dil mi? Hayır. Web uygulamasını yerel kabuğa koyan araçtır.", "React Native ile aynı mı? Hayır. Capacitor ekranı web tutar.", "Eklenti olmadan kamera açılır mı? Hayır. Cihaz olanağı eklenti ve izin ister."],
        ["هل Capacitor لغة؟ لا. هي الأداة التي تضع تطبيق الويب في غلاف أصلي.", "هل هي مثل React Native؟ لا. Capacitor تبقي الشاشة ويب.", "هل تفتح الكاميرا بلا إضافة؟ لا. قدرة الجهاز تحتاج إضافة وإذناً."],
        ["Capacitor — это язык? Нет. Это инструмент, который кладёт веб-приложение в нативную оболочку.", "Это то же, что React Native? Нет. Capacitor оставляет экран вебом.", "Камера открывается без плагина? Нет. Возможность устройства требует плагин и разрешение."],
      ),
    },
  ),
  topic(
    "docker",
    "Docker",
    t("Docker nədir?", "What is Docker?", "Docker nedir?", "ما هو Docker؟", "Что такое Docker?"),
    t(
      "Docker proqramı konteynerdə işlədir. İmage hazır şablondur, konteyner isə həmin şablonun işlək nüsxəsidir.",
      "Docker runs a program in a container. An image is the ready template. A container is a running copy of that template.",
      "Docker, programı konteynerde çalıştırır. Image hazır şablondur, konteyner o şablonun çalışan kopyasıdır.",
      "يشغّل Docker البرنامج في حاوية. الصورة قالب جاهز، والحاوية نسخة تعمل من ذلك القالب.",
      "Docker запускает программу в контейнере. Образ — готовый шаблон. Контейнер — работающая копия этого шаблона.",
    ),
    t("Docker nədir, Docker konteyner, Docker image, Dockerfile", "what is Docker, Docker container, Docker image, Dockerfile", "Docker nedir, Docker konteyner, Dockerfile", "ما هو Docker, حاوية Docker, Dockerfile", "что такое Docker, контейнер Docker, Dockerfile"),
    {
      what: t(
        "Docker proqramı öz kitabxanaları ilə birlikdə paketləyir. Maşında «mənim kompüterimdə işləyirdi» fərqi azalır. Bu, tam virtual maşın deyil. Nüvəni host ilə bölüşür, ona görə daha yüngüldür. Ubuntu serverin üstündə Docker qurmaq adi yoldur.",
        "Docker packs a program together with its libraries. The gap of “it worked on my computer” gets smaller. It is not a full virtual machine. It shares the kernel with the host, so it is lighter. Installing Docker on an Ubuntu server is an ordinary path.",
        "Docker, programı kütüphaneleriyle birlikte paketler. “Benim bilgisayarımda çalışıyordu” farkı azalır. Bu tam sanal makine değildir. Çekirdeği host ile paylaşır, bu yüzden daha hafiftir. Ubuntu sunucusuna Docker kurmak olağan yoldur.",
        "يحزّم Docker البرنامج مع مكتباته. فجوة «كان يعمل على جهازي» تصغر. ليست آلة افتراضية كاملة. تشارك النواة مع المضيف، لذلك هي أخف. تثبيت Docker على خادم Ubuntu طريق عادي.",
        "Docker пакует программу вместе с библиотеками. Разрыв «у меня на компьютере работало» становится меньше. Это не полная виртуальная машина. Ядро общее с хостом, поэтому легче. Поставить Docker на сервер Ubuntu — обычный путь.",
      ),
      uses: t("Eyni mühiti geliştirici maşınında və serverdə saxlamaq üçündür.", "It is for keeping the same environment on a developer machine and on a server.", "Aynı ortamı geliştirici makinesinde ve sunucuda tutmak içindir.", "هو لإبقاء البيئة نفسها على جهاز المطوّر وعلى الخادم.", "Он нужен, чтобы держать одну среду на машине разработчика и на сервере."),
      useList: lines(
        ["Tətbiqi image kimi yığmaq", "Verilənlər bazasını lokal qaldırmaq", "CI-də eyni testi işlətmək", "Bir serverdə bir neçə servisi ayırmaq"],
        ["Building the app as an image", "Starting a database locally", "Running the same test in CI", "Separating several services on one server"],
        ["Uygulamayı image olarak derlemek", "Veritabanını yerelde kaldırmak", "CI’de aynı testi çalıştırmak", "Bir sunucuda birkaç servisi ayırmak"],
        ["بناء التطبيق كصورة", "تشغيل قاعدة بيانات محلياً", "تشغيل الاختبار نفسه في CI", "فصل عدة خدمات على خادم واحد"],
        ["Собрать приложение как образ", "Поднять базу локально", "Запустить тот же тест в CI", "Разделить несколько служб на одном сервере"],
      ),
      can: t(
        "Dockerfile addımları yazır: baza image, paket, əmr. docker run həmin image-dən konteyner açır. Şəbəkə portu və disk həcmi ayrıca bağlanır. Docker təhlükəsizlik divarını və HTTPS sertifikatını əvəz etmir.",
        "A Dockerfile writes the steps: a base image, packages, and the command. docker run opens a container from that image. A network port and a disk volume are attached separately. Docker does not replace a firewall or an HTTPS certificate.",
        "Dockerfile adımları yazar: taban image, paket, komut. docker run o image’den konteyner açar. Ağ portu ve disk hacmi ayrıca bağlanır. Docker güvenlik duvarının ve HTTPS sertifikasının yerine geçmez.",
        "يكتب Dockerfile الخطوات: صورة أساس وحزم والأمر. docker run يفتح حاوية من تلك الصورة. منفذ الشبكة وحجم القرص يُربطان وحدهما. Docker لا تغني عن جدار الحماية أو شهادة HTTPS.",
        "Dockerfile записывает шаги: базовый образ, пакеты и команду. docker run открывает контейнер из этого образа. Сетевой порт и том диска подключаются отдельно. Docker не заменяет межсетевой экран и сертификат HTTPS.",
      ),
      hard: t(
        "hello-world tez açılır. Çətinlik image ölçüsü, gizli məlumatı image-ə yazmaq və şəbəkədir. Şifrə və açar image içinə qoyulmamalıdır. Onlar işə düşəndə mühitdən verilməlidir.",
        "hello-world starts quickly. The difficulty is image size, writing a secret into the image, and the network. A password and a key must not be put inside the image. They should be given from the environment when it starts.",
        "hello-world çabuk açılır. Zorluk image boyutu, gizli bilgiyi image içine yazmak ve ağdır. Parola ve anahtar image içine konmamalıdır. Çalışırken ortamdan verilmelidir.",
        "يبدأ hello-world سريعاً. الصعوبة في حجم الصورة وكتابة سر داخل الصورة والشبكة. لا توضع كلمة المرور والمفتاح داخل الصورة. يُعطيان من البيئة عند التشغيل.",
        "hello-world стартует быстро. Трудность в размере образа, записи секрета внутрь образа и сети. Пароль и ключ нельзя класть в образ. Их надо передать из окружения при запуске.",
      ),
      balance: t(
        "Üstünlük: mühit təkrarlanır, serverdə «əlavə paket» dağınıqlığı azalır. Məhdudiyyət: öyrənmə var, disk dolur, səhv yazılmış image köhnə boşluğu daşıyır. Konteyner daxilində root geniş hüquq verə bilər.",
        "Advantage: the environment repeats, and the mess of extra packages on a server gets smaller. Limit: there is learning, the disk fills, and a badly written image carries an old hole. Root inside a container can give a wide right.",
        "Avantaj: ortam yinelenir, sunucudaki ek paket dağınıklığı azalır. Sınır: öğrenme vardır, disk dolar, kötü yazılmış image eski açığı taşır. Konteyner içinde root geniş hak verebilir.",
        "الميزة: البيئة تتكرر، وفوضى الحزم الزائدة على الخادم تقل. الحد: هناك تعلّم، ويمتلئ القرص، والصورة السيئة تحمل ثغرة قديمة. root داخل الحاوية قد يعطي حقاً واسعاً.",
        "Плюс: среда повторяется, беспорядок лишних пакетов на сервере меньше. Ограничение: есть учёба, диск заполняется, плохо написанный образ несёт старую дыру. root внутри контейнера может дать широкое право.",
      ),
      ideas: t(
        "Image oxunur şablondur. Konteyner ondan yaranan prosesdir. Registry, məsələn Docker Hub, image saxlayır.",
        "An image is a readable template. A container is the process created from it. A registry, for example Docker Hub, stores images.",
        "Image okunur şablondur. Konteyner ondan doğan süreçtir. Registry, örneğin Docker Hub, image saklar.",
        "الصورة قالب يُقرأ. الحاوية عملية تُخلق منها. السجل، مثل Docker Hub، يحفظ الصور.",
        "Образ — читаемый шаблон. Контейнер — процесс, созданный из него. Реестр, например Docker Hub, хранит образы.",
      ),
      ideaList: lines(
        ["Dockerfile təlimat siyahısıdır", "docker build image yaradır", "port -p 8080:80 ilə xəritələnir", "volume məlumatı konteyner silinəndə saxlaya bilər"],
        ["A Dockerfile is the list of instructions", "docker build creates an image", "A port is mapped with -p 8080:80", "A volume can keep data when the container is deleted"],
        ["Dockerfile yönerge listesidir", "docker build image yaratır", "port -p 8080:80 ile eşlenir", "volume, konteyner silinince veriyi saklayabilir"],
        ["Dockerfile قائمة تعليمات", "docker build ينشئ صورة", "يُقابل المنفذ بـ -p 8080:80", "volume قد يحفظ البيانات عند حذف الحاوية"],
        ["Dockerfile — список инструкций", "docker build создаёт образ", "порт сопоставляется через -p 8080:80", "volume может сохранить данные, когда контейнер удалят"],
      ),
      sample: t("Bu əmr sınaq image-ni endirir, işlədir və bitəndə silir.", "This command downloads a test image, runs it, and deletes it when it finishes.", "Bu komut deneme image’ini indirir, çalıştırır ve bitince siler.", "هذا الأمر ينزّل صورة اختبار ويشغّلها ويحذفها عند الانتهاء.", "Эта команда скачивает пробный образ, запускает его и удаляет, когда он закончит."),
      code: `docker run --rm hello-world`,
      faq: lines(
        ["Docker virtual maşındır? Xeyr. Nüvəni bölüşən konteynerdir.", "Image və konteyner eynidir? Xeyr. Image şablondur, konteyner işlək nüsxədir.", "Docker HTTPS verir? Xeyr. Şifrələmə sertifikat və adətən Nginx tərəfindədir."],
        ["Is Docker a virtual machine? No. It is a container that shares the kernel.", "Are an image and a container the same? No. The image is the template. The container is the running copy.", "Does Docker give HTTPS? No. Encryption is the certificate, usually on the Nginx side."],
        ["Docker sanal makine mi? Hayır. Çekirdeği paylaşan konteynerdir.", "Image ve konteyner aynı mı? Hayır. Image şablondur, konteyner çalışan kopyadır.", "Docker HTTPS verir mi? Hayır. Şifreleme sertifikadadır, genellikle Nginx tarafında."],
        ["هل Docker آلة افتراضية؟ لا. هي حاوية تشارك النواة.", "هل الصورة والحاوية الشيء نفسه؟ لا. الصورة قالب، والحاوية نسخة تعمل.", "هل تعطي Docker بروتوكول HTTPS؟ لا. التشفير في الشهادة، عادة من جهة Nginx."],
        ["Docker — это виртуальная машина? Нет. Это контейнер, который делит ядро.", "Образ и контейнер — одно и то же? Нет. Образ — шаблон, контейнер — работающая копия.", "Docker даёт HTTPS? Нет. Шифрование в сертификате, обычно на стороне Nginx."],
      ),
    },
  ),
  topic(
    "firewall",
    "Firewall",
    t("Firewall nədir?", "What is a firewall?", "Firewall nedir?", "ما هو Firewall؟", "Что такое firewall?"),
    t(
      "Firewall şəbəkə trafikini qayda ilə buraxan və ya kəsən süzgəcdür. Ubuntu-da çox vaxt ufw ilə idarə olunur.",
      "A firewall is a filter that allows or blocks network traffic by a rule. On Ubuntu it is often managed with ufw.",
      "Firewall, ağ trafiğini kurala göre geçiren veya kesen süzgeçtir. Ubuntu’da çoğu zaman ufw ile yönetilir.",
      "Firewall مرشّح يسمح بحركة الشبكة أو يمنعها حسب قاعدة. على Ubuntu يُدار غالباً بـ ufw.",
      "Firewall — фильтр, который по правилу пропускает или режет сетевой трафик. В Ubuntu им часто управляют через ufw.",
    ),
    t("Firewall nədir, ufw, şəbəkə təhlükəsizliyi, port bağlamaq", "what is a firewall, ufw, network security, close a port", "Firewall nedir, ufw, port kapatmak", "ما هو جدار الحماية, ufw, إغلاق منفذ", "что такое firewall, ufw, закрыть порт"),
    {
      what: t(
        "Firewall paketə baxır: haradan gəldi, hara gedir, hansı portdur. Qayda uyğun gəlirsə buraxır, yoxsa atır. Bu, proqramın içindəki yoxlama deyil. Şəbəkə qapısıdır. Şifrələmə etmir. HTTPS ayrı mövzudur.",
        "A firewall looks at a packet: where it came from, where it goes, and which port it is. If a rule matches, it passes. If not, it is dropped. This is not a check inside the program. It is the network door. It does not encrypt. HTTPS is a separate topic.",
        "Firewall pakete bakar: nereden geldi, nereye gider, hangi porttur. Kural uyarsa geçirir, yoksa atar. Bu, programın içindeki denetim değildir. Ağ kapısıdır. Şifreleme yapmaz. HTTPS ayrı konudur.",
        "ينظر Firewall إلى الرزمة: من أين جاءت وإلى أين تذهب وأي منفذ هي. إذا طابقت قاعدة تمر، وإلا تُسقط. هذا ليس فحصاً داخل البرنامج. هو باب الشبكة. لا يشفّر. HTTPS موضوع منفصل.",
        "Firewall смотрит на пакет: откуда пришёл, куда идёт и какой это порт. Если правило совпало, пропускает. Если нет, отбрасывает. Это не проверка внутри программы. Это дверь сети. Он не шифрует. HTTPS — отдельная тема.",
      ),
      uses: t("Serverdə yalnız lazım olan portu açıq saxlamaq üçündür.", "It is for keeping only the needed port open on a server.", "Sunucuda yalnız gereken portu açık tutmak içindir.", "هو لإبقاء المنفذ اللازم فقط مفتوحاً على الخادم.", "Он нужен, чтобы на сервере был открыт только нужный порт."),
      useList: lines(
        ["SSH portunu məhdud saxlamaq", "80 və 443-ü veb üçün açmaq", "Verilənlər bazası portunu çölə bağlamamaq", "Bulud təhlükəsizlik qrupunu təkrarlamaq"],
        ["Keeping the SSH port limited", "Opening 80 and 443 for the web", "Not exposing the database port", "Repeating a cloud security group"],
        ["SSH portunu sınırlı tutmak", "Web için 80 ve 443’ü açmak", "Veritabanı portunu dışarı vermemek", "Bulut güvenlik grubunu yinelemek"],
        ["إبقاء منفذ SSH محدوداً", "فتح 80 و443 للويب", "عدم كشف منفذ قاعدة البيانات", "تكرار مجموعة أمان السحابة"],
        ["Держать порт SSH ограниченным", "Открыть 80 и 443 для веба", "Не открывать порт базы наружу", "Повторить группу безопасности облака"],
      ),
      can: t(
        "ufw ilə qısa qayda yazılır. Əvvəl SSH-ı buraxmadan enable etmək özünü serverdən kəsə bilər. Bulud panelindəki security group ikinci qapıdır. İkisi də bağlıdırsa trafik çatmaz.",
        "With ufw you write a short rule. Running enable before you allow SSH can cut you off from the server. A security group in the cloud panel is a second door. If both are closed, traffic does not arrive.",
        "ufw ile kısa kural yazılır. SSH’yi açmadan enable çalıştırmak seni sunucudan kesebilir. Bulut panelindeki security group ikinci kapıdır. İkisi de kapalıysa trafik ulaşmaz.",
        "بـ ufw تكتب قاعدة قصيرة. تشغيل enable قبل السماح لـ SSH قد يقطعك عن الخادم. مجموعة الأمان في لوحة السحابة باب ثان. إذا أُغلق الاثنان لا تصل الحركة.",
        "Через ufw пишут короткое правило. enable до разрешения SSH может отрезать тебя от сервера. Security group в панели облака — вторая дверь. Если закрыты обе, трафик не дойдёт.",
      ),
      hard: t(
        "Bir port açmaq asandır. Çətinlik sıradır: əvvəl icazə, sonra aktivləşdirmə. Gələn və gedən trafiki qarışdırmaq servisi susdurur. Firewall proqram səhvini və zəif şifrəni düzəltmir.",
        "Opening one port is easy. The difficulty is the order: allow first, then enable. Mixing inbound and outbound traffic silences a service. A firewall does not fix a program mistake or a weak password.",
        "Bir port açmak kolaydır. Zorluk sıradır: önce izin, sonra etkinleştirme. Gelen ve giden trafiği karıştırmak servisi susturur. Firewall program hatasını ve zayıf parolayı düzeltmez.",
        "فتح منفذ واحد سهل. الصعوبة في الترتيب: الإذن أولاً ثم التفعيل. خلط الحركة الداخلة والخارجة يُسكت الخدمة. Firewall لا يصلح خطأ البرنامج أو كلمة مرور ضعيفة.",
        "Открыть один порт легко. Трудность в порядке: сначала разрешение, потом включение. Путаница входящего и исходящего трафика заставляет службу молчать. Firewall не чинит ошибку программы и слабый пароль.",
      ),
      balance: t(
        "Üstünlük: açıq portun sayı azalır, qayda oxunur. Məhdudiyyət: şifrələnmiş trafikin içinə baxmır, səhv qayda səni kilidləyə bilər. Tətbiq öz yoxlamasını yenə etməlidir.",
        "Advantage: the number of open ports drops, and the rule is readable. Limit: it does not look inside encrypted traffic, and a wrong rule can lock you out. The app still has to do its own check.",
        "Avantaj: açık port sayısı düşer, kural okunur. Sınır: şifreli trafiğin içine bakmaz, yanlış kural seni kilitleyebilir. Uygulama kendi denetimini yine yapmalıdır.",
        "الميزة: ينقص عدد المنافذ المفتوحة والقاعدة تُقرأ. الحد: لا ينظر داخل الحركة المشفّرة، وقد تحبسك قاعدة خاطئة. التطبيق ما زال عليه أن يفحص بنفسه.",
        "Плюс: открытых портов меньше, правило читается. Ограничение: внутрь зашифрованного трафика он не смотрит, неверное правило может запереть тебя. Приложение всё равно должно проверять само.",
      ),
      ideas: t(
        "Port nömrədir. 22 SSH, 80 HTTP, 443 HTTPS üçündür. Default deny qalan hər şeyi bağlayır.",
        "A port is a number. 22 is for SSH, 80 for HTTP, and 443 for HTTPS. Default deny closes everything else.",
        "Port bir sayıdır. 22 SSH, 80 HTTP, 443 HTTPS içindir. Default deny kalan her şeyi kapatır.",
        "المنفذ رقم. 22 لـ SSH و80 لـ HTTP و443 لـ HTTPS. الرفض الافتراضي يغلق الباقي.",
        "Порт — это номер. 22 для SSH, 80 для HTTP, 443 для HTTPS. Default deny закрывает всё остальное.",
      ),
      ideaList: lines(
        ["ufw Ubuntu-da sadə üz qabığıdır", "nftables daha alt səviyyədir", "security group buludun firewall-ıdır", "allow from IP yalnız bir ünvana icazə verə bilər"],
        ["ufw is a simple front on Ubuntu", "nftables is the lower level", "A security group is the cloud firewall", "allow from an IP can permit only one address"],
        ["ufw Ubuntu’da sade bir ön yüzdür", "nftables daha alt düzeydir", "security group bulutun firewall’ıdır", "allow from IP yalnız bir adrese izin verebilir"],
        ["ufw واجهة بسيطة على Ubuntu", "nftables مستوى أدنى", "مجموعة الأمان هي firewall السحابة", "allow from IP قد يسمح لعنوان واحد فقط"],
        ["ufw — простой фасад в Ubuntu", "nftables — уровень ниже", "security group — firewall облака", "allow from IP может разрешить только один адрес"],
      ),
      sample: t(
        "Bu sıra əvvəl SSH və HTTPS-i açır, sonra firewall-ı işə salır. SSH qaydasını öz portuna görə dəyiş.",
        "This order opens SSH and HTTPS first, then turns the firewall on. Change the SSH rule to match your port.",
        "Bu sıra önce SSH ve HTTPS’i açar, sonra firewall’ı çalıştırır. SSH kuralını kendi portuna göre değiştir.",
        "هذا الترتيب يفتح SSH وHTTPS أولاً ثم يشغّل الجدار. غيّر قاعدة SSH حسب منفذك.",
        "Этот порядок сначала открывает SSH и HTTPS, потом включает firewall. Поменяй правило SSH под свой порт.",
      ),
      code: `sudo ufw allow OpenSSH
sudo ufw allow 443/tcp
sudo ufw enable`,
      faq: lines(
        ["Firewall virus proqramıdır? Xeyr. Şəbəkə qaydasıdır.", "Firewall HTTPS-i əvəz edir? Xeyr. Biri portu seçir, digəri trafiki şifrələyir.", "Hər şeyi bağlamaq təhlükəsizdir? Serverə girişi də bağlaya bilər. Əvvəl idarəetmə portunu aç."],
        ["Is a firewall an antivirus? No. It is a network rule.", "Does a firewall replace HTTPS? No. One chooses the port. The other encrypts the traffic.", "Is closing everything safe? It can also close your way in. Open the admin port first."],
        ["Firewall virüs programı mı? Hayır. Ağ kuralıdır.", "Firewall HTTPS’in yerine mi geçer? Hayır. Biri portu seçer, diğeri trafiği şifreler.", "Her şeyi kapatmak güvenli mi? Sunucuya girişi de kapatabilir. Önce yönetim portunu aç."],
        ["هل Firewall مضاد فيروسات؟ لا. هو قاعدة شبكة.", "هل يغني Firewall عن HTTPS؟ لا. أحدهما يختار المنفذ والآخر يشفّر الحركة.", "هل إغلاق كل شيء آمن؟ قد يغلق طريق دخولك أيضاً. افتح منفذ الإدارة أولاً."],
        ["Firewall — это антивирус? Нет. Это сетевое правило.", "Firewall заменяет HTTPS? Нет. Один выбирает порт, другой шифрует трафик.", "Закрыть всё — безопасно? Можно закрыть и свой вход. Сначала открой порт управления."],
      ),
    },
  ),
  topic(
    "nginx",
    "Nginx",
    t("Nginx nədir?", "What is Nginx?", "Nginx nedir?", "ما هو Nginx؟", "Что такое Nginx?"),
    t(
      "Nginx veb server və əks proxy-dir. Statik faylı özü verir, dinamik tətbiqə isə sorğunu ötürür.",
      "Nginx is a web server and a reverse proxy. It serves a static file itself and forwards a request to a dynamic app.",
      "Nginx bir web sunucusu ve ters proxy’dir. Statik dosyayı kendisi verir, dinamik uygulamaya ise isteği iletir.",
      "Nginx خادم ويب ووكيل عكسي. يقدّم الملف الثابت بنفسه ويمرّر الطلب إلى تطبيق ديناميكي.",
      "Nginx — веб-сервер и обратный прокси. Статический файл он отдаёт сам, а запрос к динамическому приложению передаёт дальше.",
    ),
    t("Nginx nədir, Nginx proxy, Nginx server, Nginx SSL", "what is Nginx, Nginx proxy, Nginx server, Nginx SSL", "Nginx nedir, Nginx proxy, Nginx SSL", "ما هو Nginx, وكيل Nginx, Nginx SSL", "что такое Nginx, прокси Nginx, Nginx SSL"),
    {
      what: t(
        "Nginx çox bağlantını az yaddaşla saxlamaq üçün yazılıb. Saytın qapısında durur. Brauzer ona bağlanır. O, faylı diskdən verə bilər və ya sorğunu Node, PHP və ya başqa porta ötürə bilər. HTTPS sertifikatı da çox vaxt burada bağlanır.",
        "Nginx was written to hold many connections with little memory. It stands at the door of a site. The browser connects to it. It can serve a file from disk or forward the request to Node, PHP, or another port. An HTTPS certificate is often attached here too.",
        "Nginx çok bağlantıyı az bellekle tutmak için yazılmıştır. Sitenin kapısında durur. Tarayıcı ona bağlanır. Dosyayı diskten verebilir veya isteği Node, PHP ya da başka porta iletebilir. HTTPS sertifikası da çoğu zaman burada bağlanır.",
        "كُتب Nginx ليمسك كثيراً من الاتصالات بذاكرة قليلة. يقف عند باب الموقع. المتصفح يتصل به. يمكنه تقديم ملف من القرص أو تمرير الطلب إلى Node أو PHP أو منفذ آخر. شهادة HTTPS تُربط هنا غالباً أيضاً.",
        "Nginx написан, чтобы держать много соединений малой памятью. Он стоит у двери сайта. Браузер подключается к нему. Он может отдать файл с диска или передать запрос Node, PHP или другому порту. Сертификат HTTPS тоже часто крепят здесь.",
      ),
      uses: t("Bir domenin arxasında bir neçə servisi səliqəli açmaq üçündür.", "It is for opening several services neatly behind one domain.", "Bir alan adının arkasında birkaç servisi düzgün açmak içindir.", "هو لفتح عدة خدمات بترتيب خلف اسم نطاق واحد.", "Он нужен, чтобы аккуратно открыть несколько служб за одним доменом."),
      useList: lines(
        ["Statik sayt vermək", "Node və ya PHP-yə proxy", "TLS-i bir yerdə bitirmək", "Bir neçə domeni ayırmaq"],
        ["Serving a static site", "A proxy to Node or PHP", "Ending TLS in one place", "Separating several domains"],
        ["Statik site vermek", "Node veya PHP’ye proxy", "TLS’i bir yerde bitirmek", "Birkaç alan adını ayırmak"],
        ["تقديم موقع ثابت", "وكيل إلى Node أو PHP", "إنهاء TLS في مكان واحد", "فصل عدة أسماء نطاق"],
        ["Отдавать статический сайт", "Прокси к Node или PHP", "Завершать TLS в одном месте", "Разделять несколько доменов"],
      ),
      can: t(
        "server bloku bir domeni təsvir edir. location yolun hansı qovluğa və ya proxy-yə gedəcəyini deyir. nginx -t konfiqi sınayır. Xəta varsa reload etmə. İşləyən konfiq pozular.",
        "A server block describes one domain. location says which folder or proxy a path goes to. nginx -t tests the config. If there is an error, do not reload. A working config would break.",
        "server bloğu bir alan adını anlatır. location yolun hangi klasöre veya proxy’ye gideceğini söyler. nginx -t yapılandırmayı dener. Hata varsa reload etme. Çalışan yapılandırma bozulur.",
        "كتلة server تصف اسماً واحداً. location يقول إلى أي مجلد أو وكيل يذهب المسار. nginx -t يختبر الضبط. إذا كان هناك خطأ فلا تعمل reload. الضبط العامل ينكسر.",
        "Блок server описывает один домен. location говорит, в какую папку или прокси идёт путь. nginx -t проверяет конфиг. Если есть ошибка, не делай reload. Рабочий конфиг сломается.",
      ),
      hard: t(
        "Sadə statik sayt qısadır. Çətinlik proxy başlığı, böyük fayl və sertifikat yoludur. Apache ilə eyni işi görə bilər, amma konfiq faylı başqadır. Birini digərinin nümunəsi ilə kopyalama.",
        "A simple static site is short. The difficulty is the proxy header, a large file, and the certificate path. It can do the same job as Apache, but the config file is different. Do not copy one from the other’s example.",
        "Basit statik site kısadır. Zorluk proxy başlığı, büyük dosya ve sertifika yoludur. Apache ile aynı işi görebilir, ama yapılandırma dosyası başkadır. Birini diğerinin örneğiyle kopyalama.",
        "الموقع الثابت البسيط قصير. الصعوبة في ترويسة الوكيل والملف الكبير ومسار الشهادة. يمكنه عمل Apache نفسه، لكن ملف الضبط مختلف. لا تنسخ أحدهما من مثال الآخر.",
        "Простой статический сайт короткий. Трудность в заголовке прокси, большом файле и пути сертификата. Ту же работу, что Apache, он может сделать, но файл конфига другой. Не копируй один из примера другого.",
      ),
      balance: t(
        "Üstünlük: yüngüldür, proxy və statik faylda güclüdür, sənəd boldur. Məhdudiyyət: mürəkkəb şərt konfiqi oxunmaz edir, səhv proxy tətbiqi gizlədə bilər. Tətbiqin öz logu yenə lazımdır.",
        "Advantage: it is light, strong at proxy and static files, and the docs are plentiful. Limit: a complex condition makes the config hard to read, and a wrong proxy can hide the app. The app’s own log is still needed.",
        "Avantaj: hafiftir, proxy ve statik dosyada güçlüdür, belge boldur. Sınır: karmaşık koşul yapılandırmayı okunmaz yapar, yanlış proxy uygulamayı gizleyebilir. Uygulamanın kendi günlüğü yine gerekir.",
        "الميزة: خفيف وقوي في الوكيل والملفات الثابتة والوثائق وفيرة. الحد: الشرط المعقد يجعل الضبط صعب القراءة، وقد يخفي وكيل خاطئ التطبيق. سجل التطبيق نفسه ما زال لازماً.",
        "Плюс: лёгкий, силён в прокси и статике, документации много. Ограничение: сложное условие делает конфиг нечитаемым, неверный прокси может спрятать приложение. Собственный журнал приложения всё ещё нужен.",
      ),
      ideas: t(
        "worker proses bağlantını saxlayır. root statik qovluqdur. proxy_pass arxadakı tətbiqin ünvanıdır.",
        "A worker process holds the connection. root is the static folder. proxy_pass is the address of the app behind it.",
        "worker süreç bağlantıyı tutar. root statik klasördür. proxy_pass arkadaki uygulamanın adresidir.",
        "عملية worker تمسك الاتصال. root المجلد الثابت. proxy_pass عنوان التطبيق خلفه.",
        "Процесс worker держит соединение. root — статическая папка. proxy_pass — адрес приложения позади.",
      ),
      ideaList: lines(
        ["sites-available konfiq saxlayır", "sites-enabled aktiv linkdir", "nginx -t yoxlayır", "systemctl reload nginx prosesi kəsmədən yeniləyir"],
        ["sites-available stores the config", "sites-enabled is the active link", "nginx -t checks", "systemctl reload nginx refreshes without killing the process"],
        ["sites-available yapılandırmayı saklar", "sites-enabled etkin bağlantıdır", "nginx -t denetler", "systemctl reload nginx süreci kesmeden yeniler"],
        ["sites-available يحفظ الضبط", "sites-enabled الرابط النشط", "nginx -t يفحص", "systemctl reload nginx يحدّث بلا قتل العملية"],
        ["sites-available хранит конфиг", "sites-enabled — активная ссылка", "nginx -t проверяет", "systemctl reload nginx обновляет, не убивая процесс"],
      ),
      sample: t(
        "Bu blok 80-ci portda domeni qəbul edir və sorğunu lokal 3000 portuna ötürür. Domeni öz adına dəyiş.",
        "This block accepts a domain on port 80 and forwards the request to local port 3000. Change the domain to your own name.",
        "Bu blok 80. portta alan adını kabul eder ve isteği yerel 3000 portuna iletir. Alan adını kendi adına değiştir.",
        "هذه الكتلة تقبل الاسم على المنفذ 80 وتمرّر الطلب إلى المنفذ المحلي 3000. غيّر الاسم إلى اسمك.",
        "Этот блок принимает домен на порту 80 и передаёт запрос на локальный порт 3000. Поменяй домен на своё имя.",
      ),
      code: `server {
    listen 80;
    server_name example.com;
    location / {
        proxy_pass http://127.0.0.1:3000;
    }
}`,
      faq: lines(
        ["Nginx və Apache eynidir? İkisi də veb serverdir, konfiq və modeli fərqlidir.", "Nginx proqramlaşdırma dilidir? Xeyr. Sorğunu qarşılayan serverdir.", "Node varsa Nginx lazımdır? Məcburi deyil. Domen, TLS və bir neçə servis olanda çox vaxt lazım olur."],
        ["Are Nginx and Apache the same? Both are web servers. The config and the model differ.", "Is Nginx a programming language? No. It is the server that receives the request.", "If you have Node, do you need Nginx? Not always. When there is a domain, TLS, and several services, you usually do."],
        ["Nginx ve Apache aynı mı? İkisi de web sunucusudur, yapılandırma ve model farklıdır.", "Nginx programlama dili mi? Hayır. İsteği karşılayan sunucudur.", "Node varsa Nginx gerekir mi? Zorunlu değil. Alan adı, TLS ve birkaç servis varken çoğu zaman gerekir."],
        ["هل Nginx وApache الشيء نفسه؟ كلاهما خادم ويب، والضبط والنموذج مختلفان.", "هل Nginx لغة برمجة؟ لا. هو الخادم الذي يستقبل الطلب.", "إذا وُجد Node هل يلزم Nginx؟ ليس دائماً. حين يوجد اسم ونطاق TLS وعدة خدمات فغالباً نعم."],
        ["Nginx и Apache — одно и то же? Оба веб-серверы, конфиг и модель различаются.", "Nginx — язык программирования? Нет. Это сервер, который принимает запрос.", "Если есть Node, нужен ли Nginx? Не всегда. Когда есть домен, TLS и несколько служб, обычно да."],
      ),
    },
  ),
  topic(
    "ssl",
    "SSL / HTTPS",
    t("SSL və HTTPS nədir?", "What are SSL and HTTPS?", "SSL ve HTTPS nedir?", "ما هما SSL وHTTPS؟", "Что такое SSL и HTTPS?"),
    t(
      "HTTPS HTTP-nin şifrələnmiş halıdır. Bu gün şifrələməni TLS edir. SSL köhnə addır, amma hələ belə deyirlər.",
      "HTTPS is HTTP in encrypted form. Today TLS does the encryption. SSL is the old name, but people still say it.",
      "HTTPS, HTTP’nin şifrelenmiş halıdır. Bugün şifrelemeyi TLS yapar. SSL eski addır, ama hâlâ böyle denir.",
      "HTTPS هو HTTP بشكل مُشفَّر. اليوم ينفّذ التشفير TLS. SSL اسم قديم، لكن الناس ما زالوا يقولونه.",
      "HTTPS — это HTTP в зашифрованном виде. Сегодня шифрование делает TLS. SSL — старое имя, но так всё ещё говорят.",
    ),
    t("SSL nədir, HTTPS nədir, TLS sertifikatı, Let's Encrypt", "what is SSL, what is HTTPS, TLS certificate, Let's Encrypt", "SSL nedir, HTTPS nedir, TLS sertifikası", "ما هو SSL, ما هو HTTPS, شهادة TLS", "что такое SSL, что такое HTTPS, сертификат TLS"),
    {
      what: t(
        "Brauzer və server arasındakı yazı sertifikatla şifrələnir. Sertifikat domenin adını təsdiqləyir. Əlaqə 443 portundan gedir. Köhnə SSL protokolları söndürülüb. Danışıqda SSL deyilsə də, işləyən mexanizm TLS-dir.",
        "The text between the browser and the server is encrypted with a certificate. The certificate confirms the domain name. The connection comes through port 443. The old SSL protocols are turned off. Even when people say SSL, the working mechanism is TLS.",
        "Tarayıcı ile sunucu arasındaki yazı sertifikayla şifrelenir. Sertifika alan adını doğrular. Bağlantı 443 portundan gelir. Eski SSL protokolleri kapatılmıştır. Konuşmada SSL dense de çalışan düzenek TLS’tir.",
        "يُشفَّر النص بين المتصفح والخادم بشهادة. الشهادة تؤكد اسم النطاق. يأتي الاتصال من المنفذ 443. بروتوكولات SSL القديمة أُطفئت. حتى حين يقول الناس SSL فالآلية العاملة هي TLS.",
        "Текст между браузером и сервером шифруется сертификатом. Сертификат подтверждает имя домена. Соединение идёт через порт 443. Старые протоколы SSL выключены. Даже когда говорят SSL, рабочий механизм — TLS.",
      ),
      uses: t("Saytın ünvanini və formanı yolda oxunmaz etmək üçündür.", "It is for making the site address and the form unreadable on the path.", "Site adresini ve formu yolda okunmaz yapmak içindir.", "هو لجعل عنوان الموقع والنموذج غير قابلين للقراءة في الطريق.", "Он нужен, чтобы адрес сайта и форма не читались по пути."),
      useList: lines(
        ["Giriş səhifəsini qorumaq", "API sorğusunu şifrələmək", "Brauzerin xəbərdarlığını bağlamaq", "HTTP-ni HTTPS-ə yönəltmək"],
        ["Protecting a login page", "Encrypting an API call", "Closing the browser warning", "Redirecting HTTP to HTTPS"],
        ["Giriş sayfasını korumak", "API çağrısını şifrelemek", "Tarayıcı uyarısını kapatmak", "HTTP’yi HTTPS’e yönlendirmek"],
        ["حماية صفحة الدخول", "تشفير طلب API", "إغلاق تحذير المتصفح", "تحويل HTTP إلى HTTPS"],
        ["Защитить страницу входа", "Зашифровать вызов API", "Убрать предупреждение браузера", "Перенаправить HTTP на HTTPS"],
      ),
      can: t(
        "Let's Encrypt pulsuz sertifikat verir, müddəti təxminən 90 gündür. certbot Nginx konfiqinə 443 və yönləndirmə əlavə edə bilər. Sertifikat bitəndə sayt xəbərdarlıq verir. Avtomatik yeniləmə yoxlanmalıdır. Firewall portu açır, sertifikat isə məzmunu şifrələyir. İkisi ayrıdır.",
        "Let's Encrypt gives a free certificate. It lasts about 90 days. certbot can add port 443 and a redirect to the Nginx config. When the certificate ends, the site shows a warning. Automatic renewal has to be checked. A firewall opens the port. The certificate encrypts the content. They are separate.",
        "Let's Encrypt ücretsiz sertifika verir, süresi yaklaşık 90 gündür. certbot Nginx yapılandırmasına 443 ve yönlendirme ekleyebilir. Sertifika bitince site uyarı verir. Otomatik yenileme denetlenmelidir. Firewall portu açar, sertifika içeriği şifreler. İkisi ayrıdır.",
        "يعطي Let's Encrypt شهادة مجانية تدوم نحو 90 يوماً. يمكن لـ certbot أن يضيف المنفذ 443 والتحويل إلى ضبط Nginx. حين تنتهي الشهادة يُظهر الموقع تحذيراً. يجب فحص التجديد التلقائي. Firewall يفتح المنفذ، والشهادة تشفّر المحتوى. هما منفصلان.",
        "Let's Encrypt даёт бесплатный сертификат примерно на 90 дней. certbot может добавить порт 443 и перенаправление в конфиг Nginx. Когда сертификат кончается, сайт показывает предупреждение. Автообновление надо проверить. Firewall открывает порт, сертификат шифрует содержимое. Это разное.",
      ),
      hard: t(
        "Bir domen üçün ilk sertifikat artıq alət ilə asandır. Çətinlik ad uyğunluğu, bitmə müddəti və qarışıq proxy-dir. Sertifikat example.com üçündürsə, www ayrıca ad kimi yazılmalıdır. Öz-özünə imzalanmış sertifikat brauzerdə etibarlı sayılmır.",
        "The first certificate for one domain is easy with a tool now. The difficulty is the name match, the expiry, and a mixed proxy. If the certificate is for example.com, www must be written as a separate name. A self-signed certificate is not trusted in the browser.",
        "Bir alan adı için ilk sertifika artık araçla kolaydır. Zorluk ad uyumu, bitiş süresi ve karışık proxy’dir. Sertifika example.com içinse www ayrı ad olarak yazılmalıdır. Kendi imzaladığı sertifika tarayıcıda güvenilir sayılmaz.",
        "الشهادة الأولى لاسم واحد صارت سهلة بالأداة. الصعوبة في مطابقة الاسم ومدة الانتهاء والوكيل المختلط. إذا كانت الشهادة لـ example.com فيجب كتابة www اسماً مستقلاً. الشهادة الموقّعة ذاتياً لا تُوثَّق في المتصفح.",
        "Первый сертификат для одного домена сейчас легко получить инструментом. Трудность в совпадении имени, сроке и смешанном прокси. Если сертификат для example.com, www надо записать отдельным именем. Самоподписанный сертификат браузер не доверяет.",
      ),
      balance: t(
        "Üstünlük: pulsuz sertifikat var, brauzer açıq saytı xəbərdar edir, məzmun yolda gizlənir. Məhdudiyyət: sertifikat serverin özünün təmiz olduğunu sübut etmir. Oğurlanmış açar və səhv proqram şifrənin arxasında da qala bilər.",
        "Advantage: a free certificate exists, the browser warns on a plain site, and the content hides on the path. Limit: a certificate does not prove the server itself is clean. A stolen key and a bad program can still sit behind the encryption.",
        "Avantaj: ücretsiz sertifika vardır, tarayıcı açık siteyi uyarır, içerik yolda gizlenir. Sınır: sertifika sunucunun kendisinin temiz olduğunu kanıtlamaz. Çalınmış anahtar ve kötü program şifrenin arkasında da durabilir.",
        "الميزة: توجد شهادة مجانية، والمتصفح يحذّر من موقع بلا تشفير، والمحتوى يختفي في الطريق. الحد: الشهادة لا تثبت أن الخادم نفسه نظيف. مفتاح مسروق وبرنامج سيئ قد يبقيان خلف التشفير.",
        "Плюс: бесплатный сертификат есть, браузер предупреждает об открытом сайте, содержимое прячется в пути. Ограничение: сертификат не доказывает, что сам сервер чистый. Украденный ключ и плохая программа могут остаться за шифрованием.",
      ),
      ideas: t(
        "Açar gizli qalır. Sertifikat açıqdır. Zəncir sertifikatı kiminsə imzaladığını göstərir.",
        "The key stays secret. The certificate is public. The chain shows who signed the certificate.",
        "Anahtar gizli kalır. Sertifika açıktır. Zincir sertifikayı kimin imzaladığını gösterir.",
        "يبقى المفتاح سراً. الشهادة علنية. السلسلة تُظهر من وقّع الشهادة.",
        "Ключ остаётся тайным. Сертификат открыт. Цепочка показывает, кто подписал сертификат.",
      ),
      ideaList: lines(
        ["443 HTTPS portudur", "80 köhnə HTTP portudur", "Let's Encrypt 90 günə yaxın müddət verir", "HSTS brauzerdən yalnız HTTPS istəyir"],
        ["443 is the HTTPS port", "80 is the old HTTP port", "Let's Encrypt gives about 90 days", "HSTS asks the browser for HTTPS only"],
        ["443 HTTPS portudur", "80 eski HTTP portudur", "Let's Encrypt yaklaşık 90 gün verir", "HSTS tarayıcıdan yalnız HTTPS ister"],
        ["443 منفذ HTTPS", "80 منفذ HTTP القديم", "Let's Encrypt يعطي نحو 90 يوماً", "HSTS يطلب من المتصفح HTTPS فقط"],
        ["443 — порт HTTPS", "80 — старый порт HTTP", "Let's Encrypt даёт около 90 дней", "HSTS просит у браузера только HTTPS"],
      ),
      sample: t(
        "Bu əmr Nginx olan serverdə bir domen üçün sertifikat istəyir. Domen və Nginx konfiqi əvvəlcə hazır olmalıdır.",
        "This command asks for a certificate for one domain on a server that has Nginx. The domain and the Nginx config should be ready first.",
        "Bu komut Nginx olan sunucuda bir alan adı için sertifika ister. Alan adı ve Nginx yapılandırması önce hazır olmalıdır.",
        "هذا الأمر يطلب شهادة لاسم واحد على خادم فيه Nginx. يجب أن يكون الاسم وضبط Nginx جاهزين أولاً.",
        "Эта команда просит сертификат для одного домена на сервере с Nginx. Домен и конфиг Nginx должны быть готовы раньше.",
      ),
      code: `sudo certbot --nginx -d example.com`,
      faq: lines(
        ["SSL və TLS eynidir? Danışıqda qarışır. Bu gün işləyən protokol TLS-dir. SSL köhnə addır.", "HTTPS saytı təhlükəsiz edirmi? Yolu şifrələyir. Saytın öz kodunu təmiz etmir.", "Sertifikat bir dəfəlikdir? Xeyr. Müddəti bitir və yenilənməlidir."],
        ["Are SSL and TLS the same? People mix them. The protocol that works today is TLS. SSL is the old name.", "Does HTTPS make a site safe? It encrypts the path. It does not clean the site’s own code.", "Is a certificate forever? No. It expires and has to be renewed."],
        ["SSL ve TLS aynı mı? Konuşmada karışır. Bugün çalışan protokol TLS’tir. SSL eski addır.", "HTTPS siteyi güvenli yapar mı? Yolu şifreler. Sitenin kendi kodunu temizlemez.", "Sertifika bir kerelik mi? Hayır. Süresi biter ve yenilenmelidir."],
        ["هل SSL وTLS الشيء نفسه؟ يختلطان في الكلام. البروتوكول الذي يعمل اليوم هو TLS. SSL اسم قديم.", "هل يجعل HTTPS الموقع آمناً؟ يشفّر الطريق. لا ينظّف كود الموقع نفسه.", "هل الشهادة إلى الأبد؟ لا. تنتهي ويجب تجديدها."],
        ["SSL и TLS — одно и то же? В речи их путают. Сегодня работает TLS. SSL — старое имя.", "HTTPS делает сайт безопасным? Он шифрует путь. Код самого сайта он не чистит.", "Сертификат навсегда? Нет. Срок кончается, его надо обновлять."],
      ),
    },
  ),
];
