import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_NEXT: readonly StackPage[] = [
  topic(
    "react",
    "React",
    t("React nədir?", "What is React?", "React nedir?", "ما هو React؟", "Что такое React?"),
    t(
      "React ekrandakı interfeysi hissələrə bölən JavaScript kitabxanasıdır. Dil deyil. Düymə, siyahı və səhifə ayrı komponent kimi yazılır.",
      "React is a JavaScript library that splits an interface into parts. It is not a language. A button, a list, and a page are written as separate components.",
      "React, ekrandaki arayüzü parçalara bölen bir JavaScript kütüphanesidir. Dil değildir. Düğme, liste ve sayfa ayrı bileşen olarak yazılır.",
      "React مكتبة JavaScript تقسم الواجهة إلى أجزاء. ليست لغة. الزر والقائمة والصفحة تُكتب كمكونات منفصلة.",
      "React — библиотека JavaScript, которая делит интерфейс на части. Это не язык. Кнопка, список и страница пишутся отдельными компонентами.",
    ),
    t("React nədir, React komponent, JSX, React kitabxana", "what is React, React component, JSX, React library", "React nedir, React bileşen, JSX", "ما هو React, مكون React, JSX", "что такое React, компонент React, JSX"),
    {
      what: t(
        "React-i Meta-da (əvvəl Facebook) işləyənlər 2013-cü ildə açıblar. Səhifə bir böyük fayl olmur. Hər komponent öz məlumatını və görünüşünü saxlayır. JSX HTML-ə bənzəyir, amma JavaScript-in içindədir. Brauzer JSX-i özü oxumur. Quruluş aləti onu adi JavaScript-ə çevirir.",
        "People working at Meta (then Facebook) opened React in 2013. A page is not one huge file. Each component keeps its own data and its own look. JSX looks like HTML, but it sits inside JavaScript. The browser does not read JSX by itself. A build tool turns it into plain JavaScript.",
        "React’i Meta’da (o zaman Facebook) çalışanlar 2013’te açtı. Sayfa tek kocaman dosya olmaz. Her bileşen kendi verisini ve görünüşünü tutar. JSX HTML’e benzer, ama JavaScript’in içindedir. Tarayıcı JSX’i kendi okumaz. Derleme aracı onu düz JavaScript’e çevirir.",
        "فتح العاملون في Meta (فيسبوك آنذاك) React سنة 2013. الصفحة ليست ملفاً واحداً ضخماً. كل مكون يحفظ بياناته ومظهره. JSX يشبه HTML لكنه داخل JavaScript. المتصفح لا يقرأ JSX وحده. أداة البناء تحوّله إلى JavaScript عادي.",
        "React открыли в 2013 году люди из Meta (тогда Facebook). Страница — не один огромный файл. Каждый компонент хранит свои данные и свой вид. JSX похож на HTML, но он внутри JavaScript. Браузер сам JSX не читает. Сборщик превращает его в обычный JavaScript.",
      ),
      uses: t(
        "React dəyişən ekran üçündür: siyahı artır, düymə vəziyyəti dəyişir, eyni kart çox yerdə işlənir.",
        "React is for a screen that changes: a list grows, a button changes state, and the same card is used in many places.",
        "React değişen ekran içindir: liste uzar, düğmenin durumu değişir, aynı kart çok yerde kullanılır.",
        "React للشاشة التي تتغير: تطول القائمة وتتبدل حالة الزر وتُستخدم البطاقة نفسها في أماكن كثيرة.",
        "React нужен для экрана, который меняется: список растёт, состояние кнопки меняется, одна карточка используется во многих местах.",
      ),
      useList: lines(
        ["Eyni düyməni bir neçə yerdə işlətmək", "Siyahını məlumatdan çıxarmaq", "Formanın xətasını ekranda göstərmək", "Next.js kimi çərçivənin içində səhifə"],
        ["Using the same button in several places", "Building a list from data", "Showing a form error on the screen", "A page inside a framework such as Next.js"],
        ["Aynı düğmeyi birkaç yerde kullanmak", "Listeyi veriden çıkarmak", "Formanın hatasını ekranda göstermek", "Next.js gibi bir çatının içinde sayfa"],
        ["استخدام الزر نفسه في عدة أماكن", "بناء قائمة من البيانات", "إظهار خطأ النموذج على الشاشة", "صفحة داخل إطار مثل Next.js"],
        ["Использовать одну кнопку в нескольких местах", "Собрать список из данных", "Показать ошибку формы на экране", "Страница внутри фреймворка вроде Next.js"],
      ),
      can: t(
        "React ilə kart, menyu və axtarış qutusu yazırsan. Vəziyyət dəyişəndə React yalnız dəyişən hissəni yeniləməyə çalışır. O, verilənlər bazası deyil və serveri özü qurmur. React Native ayrı kitabxanadır: telefon tətbiqi üçündür, eyni şey deyil.",
        "With React you write a card, a menu, and a search box. When state changes, React tries to update only the part that changed. It is not a database and it does not build the server by itself. React Native is a separate library for a phone app. It is not the same thing.",
        "React ile kart, menü ve arama kutusu yazarsın. Durum değişince React yalnız değişen kısmı yenilemeye çalışır. Veritabanı değildir ve sunucuyu kendi kurmaz. React Native ayrı kütüphanedir: telefon uygulaması içindir, aynı şey değildir.",
        "بـ React تكتب بطاقة وقائمة وبحثاً. حين تتغير الحالة يحاول React تحديث الجزء المتغير فقط. ليس قاعدة بيانات ولا يبني الخادم وحده. React Native مكتبة منفصلة لتطبيق الهاتف. ليست الشيء نفسه.",
        "На React пишут карточку, меню и поле поиска. Когда состояние меняется, React старается обновить только изменившуюся часть. Это не база данных и сервер он сам не строит. React Native — отдельная библиотека для приложения телефона. Это не то же самое.",
      ),
      hard: t(
        "İlk komponent asandır. Çətinlik vəziətin harada saxlanmasındadır. Hər düymə öz içində sayırsa, səhifə sonra dağınıq olur. Effekt və siyahı açarı səhv olanda ekran artıq yenilənir və ya köhnə qiymət qalır.",
        "The first component is easy. The difficulty is where the state is kept. If every button counts inside itself, the page becomes scattered later. When an effect or a list key is wrong, the screen updates too often, or an old value stays.",
        "İlk bileşen kolaydır. Zorluk durumun nerede tutulduğudur. Her düğme kendi içinde sayarsa sayfa sonra dağınık olur. Etki veya liste anahtarı yanlışsa ekran fazla yenilenir ya da eski değer kalır.",
        "المكون الأول سهل. الصعوبة أين تُحفظ الحالة. إذا عدّ كل زر داخل نفسه تتشتت الصفحة لاحقاً. إذا أخطأ الأثر أو مفتاح القائمة تتجدد الشاشة أكثر من اللازم أو تبقى قيمة قديمة.",
        "Первый компонент прост. Трудность в том, где хранить состояние. Если каждая кнопка считает внутри себя, страница потом разъезжается. Если эффект или ключ списка неверный, экран обновляется лишний раз или остаётся старое значение.",
      ),
      balance: t(
        "Üstünlük: eyni hissə təkrar yazılmır, böyük interfeys hissələrə bölünür. Məhdudiyyət: JSX və quruluş aləti əlavə addımdır. Kiçik sabit səhifə üçün tək HTML daha düz yoldur. React hər layihənin şərti deyil.",
        "Advantage: the same part is not rewritten, and a large interface splits into pieces. Limit: JSX and a build tool are an extra step. For a small fixed page, plain HTML is the straighter path. React is not a requirement of every project.",
        "Avantaj: aynı parça yeniden yazılmaz, büyük arayüz parçalara bölünür. Sınır: JSX ve derleme aracı ek adımdır. Küçük sabit sayfa için düz HTML daha düz yoldur. React her projenin şartı değildir.",
        "الميزة: لا يُعاد كتابة الجزء نفسه وتنقسم الواجهة الكبيرة إلى قطع. الحد: JSX وأداة البناء خطوة إضافية. للصفحة الصغيرة الثابتة HTML العادي أوضح. React ليس شرطاً لكل مشروع.",
        "Плюс: одну часть не переписывают, большой интерфейс делится на куски. Ограничение: JSX и сборщик — лишний шаг. Для маленькой неподвижной страницы прямой путь — обычный HTML. React не обязателен в каждом проекте.",
      ),
      ideas: t(
        "Komponent funksiyadır. Props ona xaricdən gələn qiymətdir. State onun öz içində dəyişən qiymətdir.",
        "A component is a function. Props are the value that comes in from outside. State is the value that changes inside it.",
        "Bileşen bir fonksiyondur. Props dışarıdan gelen değerdir. State onun kendi içinde değişen değerdir.",
        "المكون دالة. Props قيمة تأتي من الخارج. State قيمة تتغير داخله.",
        "Компонент — это функция. Props — значение, которое приходит снаружи. State — значение, которое меняется внутри.",
      ),
      ideaList: lines(
        ["JSX görünüşü JavaScript-in içinə yazır", "Props komponenti dəyişmir, gələn məlumatdır", "State dəyişəndə həmin hissə yenilənir", "Açar siyahıda hansı sətrin hansı olduğunu saxlayır"],
        ["JSX writes the look inside JavaScript", "Props do not change the component; they are incoming data", "When state changes, that part updates", "A key keeps which row is which in a list"],
        ["JSX görünüşü JavaScript’in içine yazar", "Props bileşeni değiştirmez, gelen veridir", "State değişince o parça yenilenir", "Anahtar listede hangi satırın hangisi olduğunu tutar"],
        ["JSX يكتب المظهر داخل JavaScript", "Props لا تغيّر المكون، هي بيانات واردة", "حين تتغير State يتجدد ذلك الجزء", "المفتاح يحفظ أي صف هو أي صف في القائمة"],
        ["JSX пишет вид внутри JavaScript", "Props не меняют компонент, это входящие данные", "Когда state меняется, обновляется эта часть", "Ключ хранит, какая строка какая, в списке"],
      ),
      sample: t(
        "Bu funksiya bir başlıq qaytarır. Brauzerdə görmək üçün onu səhifəyə bağlamaq və JSX-i çevirmək lazımdır.",
        "This function returns a heading. To see it in the browser you still connect it to the page and translate the JSX.",
        "Bu fonksiyon bir başlık döndürür. Tarayıcıda görmek için onu sayfaya bağlamak ve JSX’i çevirmek gerekir.",
        "هذه الدالة تُرجع عنواناً. لرؤيته في المتصفح ما زلت تربطه بالصفحة وتترجم JSX.",
        "Эта функция возвращает заголовок. Чтобы увидеть его в браузере, её ещё соединяют со страницей и переводят JSX.",
      ),
      code: `function Hello() {
  return <h1>Salam</h1>;
}`,
      faq: lines(
        ["React və JavaScript eynidir? Xeyr. React kitabxanadır. Onu JavaScript yazır.", "React çərçivədir? Özünü kitabxana sayır. Səhifə yolu və server üçün adətən başqa alət əlavə olunur.", "React HTML-i əvəz edir? Xeyr. Nəticədə brauzer yenə element görür."],
        ["Are React and JavaScript the same? No. React is a library. JavaScript is what writes it.", "Is React a framework? It calls itself a library. A page route and a server usually add another tool.", "Does React replace HTML? No. In the end the browser still sees elements."],
        ["React ve JavaScript aynı mı? Hayır. React kütüphanedir. Onu JavaScript yazar.", "React bir çatı mı? Kendini kütüphane sayar. Sayfa yolu ve sunucu için genellikle başka araç eklenir.", "React HTML’in yerine mi geçer? Hayır. Sonuçta tarayıcı yine öğe görür."],
        ["هل React وJavaScript الشيء نفسه؟ لا. React مكتبة. JavaScript هو الذي يكتبها.", "هل React إطار؟ يسمي نفسه مكتبة. مسار الصفحة والخادم عادة يضيفان أداة أخرى.", "هل يحل React محل HTML؟ لا. في النهاية المتصفح يرى عناصر."],
        ["React и JavaScript — одно и то же? Нет. React — библиотека. Её пишет JavaScript.", "React — это фреймворк? Он называет себя библиотекой. Маршрут страницы и сервер обычно добавляют другой инструмент.", "React заменяет HTML? Нет. В конце браузер всё равно видит элементы."],
      ),
    },
  ),
  topic(
    "c",
    "C",
    t("C nədir?", "What is C?", "C nedir?", "ما هي لغة C؟", "Что такое C?"),
    t(
      "C kompüterə yaxın duran proqramlaşdırma dilidir. 1972-ci ildə yazılıb. Əməliyyat sistemi və kiçik cihazların çoxu onunla bağlıdır.",
      "C is a programming language that sits close to the computer. It was written in 1972. Many operating systems and small devices are tied to it.",
      "C, bilgisayara yakın duran bir programlama dilidir. 1972’de yazıldı. Birçok işletim sistemi ve küçük aygıt onunla bağlantılıdır.",
      "C لغة برمجة تقف قريبة من الحاسوب. كُتبت سنة 1972. كثير من أنظمة التشغيل والأجهزة الصغيرة مرتبط بها.",
      "C — язык программирования, который стоит близко к компьютеру. Его написали в 1972 году. Многие операционные системы и маленькие устройства связаны с ним.",
    ),
    t("C nədir, C dili, C və C++, pointer", "what is C, C language, C vs C++, pointer", "C nedir, C dili, C ve C++", "ما هي C, لغة C, المؤشر", "что такое C, язык C, указатель"),
    {
      what: t(
        "C-ni Dennis Ritchie Bell Labs-da yazıb. Dil az əmrdən ibarətdir: dəyişən, funksiya, şərt, döngü və yaddaş ünvanı. C++ onun üstünə sinif və başqa qaydalar əlavə edir. C# isə ayrı dildir, ada bənzəsə də C deyil. C proqramı işləməzdən əvvəl maşın koduna kompilyasiya olunur.",
        "Dennis Ritchie wrote C at Bell Labs. The language is a few commands: a variable, a function, a condition, a loop, and a memory address. C++ adds classes and other rules on top of it. C# is a different language. The name is similar, but it is not C. A C program is compiled into machine code before it runs.",
        "C’yi Dennis Ritchie Bell Labs’ta yazdı. Dil az komuttan oluşur: değişken, fonksiyon, koşul, döngü ve bellek adresi. C++ onun üstüne sınıf ve başka kurallar ekler. C# ayrı dildir. Ad benzemesine rağmen C değildir. C programı çalışmadan önce makine koduna derlenir.",
        "كتب Dennis Ritchie لغة C في Bell Labs. اللغة أوامر قليلة: متغير ودالة وشرط وحلقة وعنوان ذاكرة. C++ تضيف أصنافاً وقواعد أخرى فوقها. C# لغة مختلفة. الاسم يشبهها لكنها ليست C. يُترجم برنامج C إلى كود الآلة قبل أن يعمل.",
        "C написал Dennis Ritchie в Bell Labs. В языке мало команд: переменная, функция, условие, цикл и адрес памяти. C++ добавляет сверху классы и другие правила. C# — другой язык. Имя похоже, но это не C. Программа на C компилируется в машинный код до запуска.",
      ),
      uses: t(
        "C sürət və kiçik ölçü lazım olanda seçilir. Əməliyyat sisteminin nüvəsi, drayver və mikrokontrolör onun yeridir.",
        "C is chosen when speed and a small size are needed. The kernel of an operating system, a driver, and a microcontroller are its place.",
        "C, hız ve küçük boyut gerektiğinde seçilir. İşletim sisteminin çekirdeği, sürücü ve mikrodenetleyici onun yeridir.",
        "تُختار C حين تُطلب السرعة والحجم الصغير. نواة نظام التشغيل وبرنامج التعريف والمتحكم الدقيق مكانها.",
        "C выбирают, когда нужны скорость и маленький размер. Ядро операционной системы, драйвер и микроконтроллер — его место.",
      ),
      useList: lines(
        ["Linux nüvəsinin hissələri", "Mikrokontrolör proqramı", "Başqa dilin kompilyatoru", "Şəbəkə alətinin aşağı təbəqəsi"],
        ["Parts of the Linux kernel", "A microcontroller program", "Another language's compiler", "The lower layer of a network tool"],
        ["Linux çekirdeğinin parçaları", "Mikrodenetleyici programı", "Başka bir dilin derleyicisi", "Bir ağ aracının alt katmanı"],
        ["أجزاء من نواة Linux", "برنامج متحكم دقيق", "مترجم لغة أخرى", "الطبقة السفلى لأداة شبكة"],
        ["Части ядра Linux", "Программа микроконтроллера", "Компилятор другого языка", "Нижний слой сетевого инструмента"],
      ),
      can: t(
        "C ilə fayl oxuyur, baytları sayır və yaddaşdan yer ayırırsan. Dil sənin yerinə yoxlamır: massivin sonundan kənara çıxmaq proqramı səssizcə poza bilər. Pəncərəli sayt yazmaq onun adi işi deyil.",
        "With C you read a file, count bytes, and reserve a place in memory. The language does not check for you. Stepping past the end of an array can break the program quietly. Writing a windowed site is not its ordinary job.",
        "C ile dosya okur, bayt sayar ve bellekten yer ayırırsın. Dil senin yerine denetlemez. Dizinin sonundan dışarı çıkmak programı sessizce bozabilir. Pencereli site yazmak onun olağan işi değildir.",
        "بـ C تقرأ ملفاً وتعد البايتات وتحجز مكاناً في الذاكرة. اللغة لا تفحص عنك. تجاوز نهاية المصفوفة قد يفسد البرنامج بصمت. كتابة موقع بنوافذ ليست عمله العادي.",
        "На C читают файл, считают байты и занимают место в памяти. Язык не проверяет за тебя. Шаг за конец массива может тихо сломать программу. Писать оконный сайт — не его обычная работа.",
      ),
      hard: t(
        "Sözlər azdır, amma ünvan çətindir. Göstərici yaddaşın nömrəsidir. Səhv nömrə başqa proqramın yaddaşına toxuna bilər. Ayrılan yeri qaytarmamaq proqramı yavaş-yavaş doldurur.",
        "The words are few, but the address is hard. A pointer is a number of a place in memory. A wrong number can touch another program's memory. Not returning a reserved place fills the program slowly.",
        "Sözler azdır, ama adres zordur. Gösterici bellekteki yerin numarasıdır. Yanlış numara başka programın belleğine dokunabilir. Ayrılan yeri geri vermemek programı yavaş yavaş doldurur.",
        "الكلمات قليلة لكن العنوان صعب. المؤشر رقم مكان في الذاكرة. الرقم الخطأ قد يلمس ذاكرة برنامج آخر. عدم إعادة المكان المحجوز يملأ البرنامج ببطء.",
        "Слов мало, но адрес труден. Указатель — номер места в памяти. Неверный номер может задеть память другой программы. Если не вернуть занятое место, программа медленно заполняется.",
      ),
      balance: t(
        "Üstünlük: nəticə kiçik və sürətli ola bilər, dilin özü az dəyişir. Məhdudiyyət: mətn, siyahı və xəta üçün hazır rahatlıq azdır. Onları özün yazırsan. Təhlükəsizlik səhvi burada bahadır.",
        "Advantage: the result can be small and fast, and the language itself changes little. Limit: ready comfort for text, a list, and an error is small. You write those yourself. A security mistake is expensive here.",
        "Avantaj: sonuç küçük ve hızlı olabilir, dilin kendisi az değişir. Sınır: metin, liste ve hata için hazır rahatlık azdır. Onları kendin yazarsın. Güvenlik hatası burada pahalıdır.",
        "الميزة: الناتج قد يكون صغيراً وسريعاً واللغة نفسها تتغير قليلاً. الحد: الراحة الجاهزة للنص والقائمة والخطأ قليلة. تكتبها أنت. خطأ الأمان هنا غالٍ.",
        "Плюс: результат может быть маленьким и быстрым, сам язык мало меняется. Ограничение: готового удобства для текста, списка и ошибки мало. Их пишешь сам. Ошибка безопасности здесь дорогая.",
      ),
      ideas: t(
        "Dəyişənin tipi ölçüsünü deyir. Funksiya işi ada bağlayır. Göstərici ünvan saxlayır, qiymətin özünü yox.",
        "A variable's type says its size. A function ties a job to a name. A pointer stores an address, not the value itself.",
        "Değişkenin tipi boyutunu söyler. Fonksiyon işi ada bağlar. Gösterici adres tutar, değerin kendisini değil.",
        "نوع المتغير يقول حجمه. الدالة تربط العمل باسم. المؤشر يحفظ عنواناً لا القيمة نفسها.",
        "Тип переменной говорит её размер. Функция связывает работу с именем. Указатель хранит адрес, не само значение.",
      ),
      ideaList: lines(
        ["int tam ədəd saxlayır", "char bir bayt saxlayır", "if şərt yoxlayır", "return funksiyadan qiymət çıxarır"],
        ["int stores a whole number", "char stores one byte", "if checks a condition", "return sends a value out of a function"],
        ["int tam sayı tutar", "char bir bayt tutar", "if koşul denetler", "return fonksiyondan değer çıkarır"],
        ["int يحفظ عدداً صحيحاً", "char يحفظ بايتاً", "if يفحص شرطاً", "return يُخرج قيمة من الدالة"],
        ["int хранит целое число", "char хранит один байт", "if проверяет условие", "return выводит значение из функции"],
      ),
      sample: t(
        "Bu proqram ekrana bir sətir yazır və 0 ilə bitir. 0 adətən «xəta yoxdur» deməkdir.",
        "This program writes one line on the screen and ends with 0. 0 usually means there was no error.",
        "Bu program ekrana bir satır yazar ve 0 ile biter. 0 genellikle «hata yok» demektir.",
        "هذا البرنامج يكتب سطراً على الشاشة وينتهي بـ 0. 0 عادة يعني «لا خطأ».",
        "Эта программа пишет одну строку на экран и заканчивается 0. 0 обычно значит «ошибки не было».",
      ),
      code: `#include <stdio.h>
int main(void) {
    printf("Hello\\n");
    return 0;
}`,
      faq: lines(
        ["C və C++ eynidir? Xeyr. C++ C-nin üstünə qurulub, amma ayrı dildir.", "C köhnəlib? Xeyr. Nüvə, drayver və kiçik cihazlarda işlənir.", "C təhlükəsizdir? Dil səni dayandırmır. Səhv ünvan proqramı poza bilər."],
        ["Are C and C++ the same? No. C++ is built on C, but it is a separate language.", "Is C obsolete? No. It is used in a kernel, a driver, and a small device.", "Is C safe? The language does not stop you. A wrong address can break the program."],
        ["C ve C++ aynı mı? Hayır. C++ C’nin üstüne kuruludur, ama ayrı dildir.", "C eskidi mi? Hayır. Çekirdek, sürücü ve küçük aygıtta kullanılır.", "C güvenli mi? Dil seni durdurmaz. Yanlış adres programı bozabilir."],
        ["هل C وC++ الشيء نفسه؟ لا. C++ مبنية على C لكنها لغة منفصلة.", "هل انتهت C؟ لا. تُستخدم في النواة وبرنامج التعريف والجهاز الصغير.", "هل C آمنة؟ اللغة لا توقفك. العنوان الخطأ قد يفسد البرنامج."],
        ["C и C++ — одно и то же? Нет. C++ построен на C, но это отдельный язык.", "C устарел? Нет. Его используют в ядре, драйвере и маленьком устройстве.", "C безопасен? Язык тебя не останавливает. Неверный адрес может сломать программу."],
      ),
    },
  ),
  topic(
    "mysql",
    "MySQL",
    t("MySQL nədir?", "What is MySQL?", "MySQL nedir?", "ما هو MySQL؟", "Что такое MySQL?"),
    t(
      "MySQL məlumatı cədvəldə saxlayan serverdir. SQL dil deyil, bu serverin adıdır. Sorğu SQL ilə yazılır, cavabı MySQL qaytarır.",
      "MySQL is a server that keeps data in tables. SQL is not this name. SQL is the language. The query is written in SQL, and MySQL returns the answer.",
      "MySQL, veriyi tabloda tutan sunucudur. SQL bu ad değildir. SQL dildir. Sorgu SQL ile yazılır, cevabı MySQL verir.",
      "MySQL خادم يحفظ البيانات في جداول. SQL ليس هذا الاسم. SQL هي اللغة. يُكتب الطلب بـ SQL ويرد MySQL الجواب.",
      "MySQL — сервер, который хранит данные в таблицах. SQL — не это имя. SQL — язык. Запрос пишут на SQL, а ответ возвращает MySQL.",
    ),
    t("MySQL nədir, MySQL verilənlər bazası, SQL, cədvəl", "what is MySQL, MySQL database, SQL, table", "MySQL nedir, MySQL veritabanı, SQL", "ما هو MySQL, قاعدة MySQL, SQL", "что такое MySQL, база MySQL, SQL"),
    {
      what: t(
        "MySQL əlaqəli verilənlər bazasıdır. Məlumat sətir və sütundadır. Bir cədvəl istifadəçi, o biri sifariş ola bilər. Onların ortaq nömrəsi sətirləri bağlayır. Server 1995-ci ildə açıq başlayıb. İndi Oracle şirkətinin məhsuludur. MariaDB onun yaxın qoludur, eyni şey deyil.",
        "MySQL is a relational database. Data sits in rows and columns. One table can be a user, another an order. A shared number ties the rows. The server started in the open in 1995. It is now a product of the Oracle company. MariaDB is a close branch of it, not the same thing.",
        "MySQL ilişkisel bir veritabanıdır. Veri satır ve sütundadır. Bir tablo kullanıcı, öteki sipariş olabilir. Ortak numara satırları bağlar. Sunucu 1995’te açık başladı. Şimdi Oracle şirketinin ürünüdür. MariaDB onun yakın koludur, aynı şey değildir.",
        "MySQL قاعدة بيانات علائقية. البيانات في صفوف وأعمدة. جدول قد يكون مستخدماً وآخر طلباً. رقم مشترك يربط الصفوف. بدأ الخادم مفتوحاً سنة 1995. هو الآن منتج شركة Oracle. MariaDB فرع قريب منه وليس الشيء نفسه.",
        "MySQL — реляционная база данных. Данные лежат в строках и столбцах. Одна таблица может быть пользователем, другая заказом. Общий номер связывает строки. Сервер начался открытым в 1995 году. Сейчас это продукт компании Oracle. MariaDB — близкая ветвь, не то же самое.",
      ),
      uses: t(
        "MySQL saytın istifadəçisini, yazını və sifarişini saxlamaq üçündür. Proqram sorğu göndərir, server sətir qaytarır.",
        "MySQL is for keeping a site's user, post, and order. A program sends a query, and the server returns rows.",
        "MySQL sitenin kullanıcısını, yazısını ve siparişini tutmak içindir. Program sorgu gönderir, sunucu satır döndürür.",
        "MySQL لحفظ مستخدم الموقع والمقالة والطلب. البرنامج يرسل طلباً والخادم يرد صفوفاً.",
        "MySQL нужен, чтобы хранить пользователя сайта, запись и заказ. Программа шлёт запрос, сервер возвращает строки.",
      ),
      useList: lines(
        ["İstifadəçi adı və şifrənin saxlanması", "Məqalə siyahısı", "Sifarişin məhsulla bağlanması", "Eyni sorğunun çox adam üçün cavabı"],
        ["Storing a user name and a password hash", "A list of articles", "Tying an order to a product", "The same query answered for many people"],
        ["Kullanıcı adı ve parola özetinin tutulması", "Yazı listesi", "Siparişin ürünle bağlanması", "Aynı sorgunun çok kişi için cevabı"],
        ["حفظ اسم المستخدم وملخص كلمة المرور", "قائمة مقالات", "ربط الطلب بالمنتج", "الطلب نفسه يُجاب لكثير من الناس"],
        ["Хранение имени и отпечатка пароля", "Список статей", "Связь заказа с товаром", "Один запрос отвечает многим людям"],
      ),
      can: t(
        "MySQL ilə sətir əlavə edir, şərtə görə seçir, yeniləyir və silirsən. İndeks axtarışı sürətləndirə bilər, amma hər sütuna indeks düzgün deyil. Server özü səhifə çəkmir. Səhifəni başqa proqram çəkir.",
        "With MySQL you add a row, choose by a condition, update, and delete. An index can speed a search, but an index on every column is not right. The server does not draw the page itself. Another program draws the page.",
        "MySQL ile satır eklersin, koşula göre seçer, günceller ve silersin. Dizin aramayı hızlandırabilir, ama her sütuna dizin doğru değildir. Sunucu sayfayı kendi çizmez. Sayfayı başka program çizer.",
        "بـ MySQL تضيف صفاً وتختار بشرط وتحدّث وتحذف. الفهرس قد يسرّع البحث، لكن فهرساً على كل عمود ليس صحيحاً. الخادم لا يرسم الصفحة نفسه. برنامج آخر يرسمها.",
        "В MySQL добавляют строку, выбирают по условию, обновляют и удаляют. Индекс может ускорить поиск, но индекс на каждом столбце неверен. Сервер сам страницу не рисует. Её рисует другая программа.",
      ),
      hard: t(
        "Cədvəl açmaq asandır. Çətinlik əlaqə və silmə şərtindədir. Şərt olmadan UPDATE və ya DELETE çox sətri dəyişir. İstifadəçi mətnini sorğunun içinə yapışdırmaq inyeksiya açır. Şifrənin özü deyil, onun izi saxlanılır.",
        "Opening a table is easy. The difficulty is the relation and the delete condition. UPDATE or DELETE without a condition changes many rows. Pasting user text into the query opens injection. What is stored is not the password itself, but a trace of it.",
        "Tablo açmak kolaydır. Zorluk ilişki ve silme koşuludur. Koşulsuz UPDATE veya DELETE çok satırı değiştirir. Kullanıcı metnini sorgunun içine yapıştırmak enjeksiyon açar. Tutulan parola değil, onun izidir.",
        "فتح جدول سهل. الصعوبة في العلاقة وشرط الحذف. UPDATE أو DELETE بلا شرط يغيّر صفوفاً كثيرة. لصق نص المستخدم داخل الطلب يفتح الحقن. ما يُحفظ ليس كلمة المرور نفسها بل أثرها.",
        "Открыть таблицу легко. Трудность в связи и в условии удаления. UPDATE или DELETE без условия меняет много строк. Вставка текста пользователя в запрос открывает инъекцию. Хранится не сам пароль, а его след.",
      ),
      balance: t(
        "Üstünlük: cədvəl aydındır, SQL çox adamın bildiyi dildir, ehtiyat nüsxə bir serverdə saxlanır. Məhdudiyyət: hər mətn faylına uyğun deyil. Çox əlaqəli sorğu səhv qurulanda yavaşlayır. MySQL yeganə bazadır demək olmaz.",
        "Advantage: a table is clear, SQL is a language many people know, and a backup stays on one server. Limit: it does not fit every text file. A query with many joins slows down when it is built wrong. MySQL is not the only database.",
        "Avantaj: tablo açıktır, SQL çok kişinin bildiği dildir, yedek bir sunucuda durur. Sınır: her metin dosyasına uymaz. Çok bağlantılı sorgu yanlış kurulunca yavaşlar. MySQL tek veritabanı değildir.",
        "الميزة: الجدول واضح وSQL لغة يعرفها كثيرون والنسخة الاحتياطية تبقى على خادم واحد. الحد: لا يناسب كل ملف نص. الطلب ذو الصلات الكثيرة يبطؤ إذا بُني خطأ. MySQL ليست قاعدة البيانات الوحيدة.",
        "Плюс: таблица понятна, SQL знают многие, резервная копия лежит на одном сервере. Ограничение: не каждый текстовый файл ему подходит. Запрос со многими связями замедляется, если собран неверно. MySQL — не единственная база.",
      ),
      ideas: t(
        "Cədvəl sütunların adıdır. Sətir bir qeyddir. Açar sətri tək tapmaq üçündür.",
        "A table is the names of the columns. A row is one record. A key is for finding that row alone.",
        "Tablo sütunların adıdır. Satır bir kayıttır. Anahtar satırı tek bulmak içindir.",
        "الجدول أسماء الأعمدة. الصف سجل واحد. المفتاح للعثور على ذلك الصف وحده.",
        "Таблица — это имена столбцов. Строка — одна запись. Ключ нужен, чтобы найти эту строку одну.",
      ),
      ideaList: lines(
        ["SELECT sətir seçir", "INSERT sətir əlavə edir", "WHERE şərti saxlayır", "JOIN iki cədvəli nömrə ilə bağlayır"],
        ["SELECT chooses rows", "INSERT adds a row", "WHERE keeps the condition", "JOIN ties two tables by a number"],
        ["SELECT satır seçer", "INSERT satır ekler", "WHERE koşulu tutar", "JOIN iki tabloyu numara ile bağlar"],
        ["SELECT يختار الصفوف", "INSERT يضيف صفاً", "WHERE يحفظ الشرط", "JOIN يربط جدولين برقم"],
        ["SELECT выбирает строки", "INSERT добавляет строку", "WHERE держит условие", "JOIN связывает две таблицы номером"],
      ),
      sample: t(
        "Bu sorğu adı verilmiş bir istifadəçini seçir. Ad birbaşa mətnin içinə yapışdırılmır. Proqram onu ayrıca parametr edir.",
        "This query chooses one user by name. The name is not pasted into the text. The program sends it as a separate parameter.",
        "Bu sorgu adı verilmiş bir kullanıcıyı seçer. Ad doğrudan metnin içine yapıştırılmaz. Program onu ayrı parametre yapar.",
        "هذا الطلب يختار مستخدماً بالاسم. الاسم لا يُلصق داخل النص. البرنامج يرسله معاملاً منفصلاً.",
        "Этот запрос выбирает одного пользователя по имени. Имя не вставляют в текст. Программа передаёт его отдельным параметром.",
      ),
      code: `SELECT id, name
FROM users
WHERE name = ?;`,
      faq: lines(
        ["MySQL və SQL eynidir? Xeyr. SQL sorğu dilidir. MySQL həmin sorğunu işlədən serverdir.", "Şifrə cədvəldə açıq yazılır? Xeyr. Saxlanan onun izidir, mətnin özü deyil.", "MySQL saytdır? Xeyr. Məlumat saxlayır. Səhifəni başqa proqram göstərir."],
        ["Are MySQL and SQL the same? No. SQL is the query language. MySQL is the server that runs that query.", "Is the password written in the open in the table? No. What is stored is a trace of it, not the text itself.", "Is MySQL a site? No. It stores data. Another program shows the page."],
        ["MySQL ve SQL aynı mı? Hayır. SQL sorgu dilidir. MySQL o sorguyu çalıştıran sunucudur.", "Parola tabloda açık yazılır mı? Hayır. Tutulan onun izidir, metnin kendisi değildir.", "MySQL site mi? Hayır. Veri tutar. Sayfayı başka program gösterir."],
        ["هل MySQL وSQL الشيء نفسه؟ لا. SQL لغة الطلب. MySQL الخادم الذي يشغّل ذلك الطلب.", "هل تُكتب كلمة المرور ظاهرة في الجدول؟ لا. ما يُحفظ أثرها لا النص نفسه.", "هل MySQL موقع؟ لا. يحفظ البيانات. برنامج آخر يُظهر الصفحة."],
        ["MySQL и SQL — одно и то же? Нет. SQL — язык запроса. MySQL — сервер, который этот запрос выполняет.", "Пароль пишут в таблице открыто? Нет. Хранится его след, не сам текст.", "MySQL — это сайт? Нет. Он хранит данные. Страницу показывает другая программа."],
      ),
    },
  ),
  topic(
    "http",
    "HTTP",
    t("HTTP nədir?", "What is HTTP?", "HTTP nedir?", "ما هو HTTP؟", "Что такое HTTP?"),
    t(
      "HTTP brauzerin serverlə danışma qaydasıdır. Dil deyil. Bir tərəf istək göndərir, o biri cavab qaytarır.",
      "HTTP is the rule by which a browser talks to a server. It is not a language. One side sends a request, and the other returns a response.",
      "HTTP, tarayıcının sunucuyla konuşma kuralıdır. Dil değildir. Bir taraf istek gönderir, öteki cevap döndürür.",
      "HTTP قاعدة كلام المتصفح مع الخادم. ليست لغة. طرف يرسل طلباً والآخر يرد جواباً.",
      "HTTP — правило, по которому браузер говорит с сервером. Это не язык. Одна сторона шлёт запрос, другая возвращает ответ.",
    ),
    t("HTTP nədir, HTTP sorğu, status kodu, GET POST", "what is HTTP, HTTP request, status code, GET POST", "HTTP nedir, HTTP isteği, durum kodu", "ما هو HTTP, طلب HTTP, رمز الحالة", "что такое HTTP, запрос HTTP, код состояния"),
    {
      what: t(
        "HTTP mətnlə yazılan sadə müqavilədir. İstəkdə üsul, ünvan və başlıqlar var. Cavabda status kodu, başlıqlar və bəzən gövdə var. 1991-ci ildə ilk sadə forması çıxıb. İndi işlənən əsas xətt HTTP/1.1 və HTTP/2-dir. HTTP/3 isə əlaqəni başqa nəqliyyatla aparır. HTTPS eyni qaydanın şifrəli yoludur. Onu SSL səhifəsi ayrıca deyir.",
        "HTTP is a plain agreement written as text. A request has a method, an address, and headers. A response has a status code, headers, and sometimes a body. The first simple form came out in 1991. The main lines in use now are HTTP/1.1 and HTTP/2. HTTP/3 carries the same conversation on another transport. HTTPS is the encrypted path of the same rule. The SSL page says that separately.",
        "HTTP metinle yazılan sade bir sözleşmedir. İstekte yöntem, adres ve başlıklar vardır. Cevapta durum kodu, başlıklar ve bazen gövde vardır. İlk sade biçimi 1991’de çıktı. Şimdi kullanılan ana hat HTTP/1.1 ve HTTP/2’dir. HTTP/3 aynı konuşmayı başka taşımayla götürür. HTTPS aynı kuralın şifreli yoludur. Bunu SSL sayfası ayrı söyler.",
        "HTTP اتفاق بسيط مكتوب نصاً. في الطلب طريقة وعنوان وترويسات. في الجواب رمز حالة وترويسات وأحياناً جسم. خرج الشكل البسيط الأول سنة 1991. الخط الأساسي المستخدم الآن HTTP/1.1 وHTTP/2. HTTP/3 يحمل الحوار نفسه على نقل آخر. HTTPS الطريق المشفّر للقاعدة نفسها. صفحة SSL تقول ذلك على حدة.",
        "HTTP — простое соглашение, записанное текстом. В запросе есть метод, адрес и заголовки. В ответе — код состояния, заголовки и иногда тело. Первая простая форма вышла в 1991 году. Основные линии сейчас — HTTP/1.1 и HTTP/2. HTTP/3 везёт тот же разговор другим транспортом. HTTPS — шифрованный путь того же правила. Страница SSL говорит об этом отдельно.",
      ),
      uses: t(
        "HTTP səhifə, şəkil, JSON və fayl daşımaq üçündür. Brauzer, telefon tətbiqi və server eyni qaydanı oxuyur.",
        "HTTP is for carrying a page, an image, JSON, and a file. A browser, a phone app, and a server read the same rule.",
        "HTTP sayfa, resim, JSON ve dosya taşımak içindir. Tarayıcı, telefon uygulaması ve sunucu aynı kuralı okur.",
        "HTTP لحمل صفحة وصورة وJSON وملف. المتصفح وتطبيق الهاتف والخادم يقرأون القاعدة نفسها.",
        "HTTP нужен, чтобы везти страницу, картинку, JSON и файл. Браузер, приложение телефона и сервер читают одно правило.",
      ),
      useList: lines(
        ["Səhifəni açmaq", "Formanı göndərmək", "API-dən JSON almaq", "Faylı endirmək"],
        ["Opening a page", "Sending a form", "Getting JSON from an API", "Downloading a file"],
        ["Sayfayı açmak", "Formayı göndermek", "API’den JSON almak", "Dosya indirmek"],
        ["فتح صفحة", "إرسال نموذج", "أخذ JSON من واجهة", "تنزيل ملف"],
        ["Открыть страницу", "Отправить форму", "Получить JSON от API", "Скачать файл"],
      ),
      can: t(
        "HTTP ilə ünvan istəyirsən və status alırsan. 200 tapıldığını, 404 ünvanın olmadığını, 500 serverin öz xətasını deyir. GET oxumaq üçündür. POST yeni məlumat göndərmək üçündür. HTTP özü məlumatı cədvəldə saxlamır.",
        "With HTTP you ask for an address and receive a status. 200 says it was found, 404 says the address is not there, and 500 says the server's own error. GET is for reading. POST is for sending new data. HTTP itself does not store data in a table.",
        "HTTP ile adres istersin ve durum alırsın. 200 bulunduğunu, 404 adresin olmadığını, 500 sunucunun kendi hatasını söyler. GET okumak içindir. POST yeni veri göndermek içindir. HTTP kendi veriyi tabloda tutmaz.",
        "بـ HTTP تطلب عنواناً وتأخذ حالة. 200 يقول إنه وُجد، و404 يقول إن العنوان غير موجود، و500 يقول خطأ الخادم نفسه. GET للقراءة. POST لإرسال بيانات جديدة. HTTP نفسه لا يحفظ البيانات في جدول.",
        "Через HTTP просят адрес и получают статус. 200 говорит, что найдено, 404 — что адреса нет, 500 — собственная ошибка сервера. GET для чтения. POST для отправки новых данных. Сам HTTP не хранит данные в таблице.",
      ),
      hard: t(
        "Bir ünvanı açmaq asandır. Çətinlik üsulun seçimindədir. GET ilə silmə və ya ödəniş etmək olmaz, çünki həmin istək təkrar və ya əvvəlcədən çağırıla bilər. Başlıqda sirr daşımaq və ünvanı qarışdırmaq da buradadır.",
        "Opening one address is easy. The difficulty is choosing the method. Do not delete or pay with GET, because that request can be repeated or called ahead of time. Carrying a secret in a header and mixing up the address also sit here.",
        "Bir adresi açmak kolaydır. Zorluk yöntemin seçimindedir. GET ile silme veya ödeme yapılmaz, çünkü o istek yinelenebilir veya önceden çağrılabilir. Başlıkta sır taşımak ve adresi karıştırmak da buradadır.",
        "فتح عنوان واحد سهل. الصعوبة في اختيار الطريقة. لا تحذف ولا تدفع بـ GET، لأن ذلك الطلب قد يُكرر أو يُستدعى مسبقاً. حمل السر في الترويسة وخلط العنوان هنا أيضاً.",
        "Открыть один адрес легко. Трудность в выборе метода. Не удаляют и не платят через GET, потому что такой запрос могут повторить или вызвать заранее. Секрет в заголовке и путаница адреса тоже здесь.",
      ),
      balance: t(
        "Üstünlük: hər tərəf eyni qaydanı bilir, mətn oxunur, status səbəbi qısa deyir. Məhdudiyyət: köhnə HTTP şifrələmir. Şifrə HTTPS-in işidir. HTTP səhifənin gözəl görünüşü deyil. Görünüş HTML və CSS-dədir.",
        "Advantage: every side knows the same rule, the text can be read, and the status says the reason shortly. Limit: old HTTP does not encrypt. Encryption is the job of HTTPS. HTTP is not the good look of a page. The look is in HTML and CSS.",
        "Avantaj: her taraf aynı kuralı bilir, metin okunur, durum nedeni kısa söyler. Sınır: eski HTTP şifrelemez. Şifre HTTPS’in işidir. HTTP sayfanın güzel görünüşü değildir. Görünüş HTML ve CSS’tedir.",
        "الميزة: كل طرف يعرف القاعدة نفسها والنص يُقرأ والحالة تقول السبب باختصار. الحد: HTTP القديم لا يشفّر. التشفير عمل HTTPS. HTTP ليس مظهر الصفحة الجميل. المظهر في HTML وCSS.",
        "Плюс: каждая сторона знает одно правило, текст читается, статус коротко говорит причину. Ограничение: старый HTTP не шифрует. Шифрование — работа HTTPS. HTTP — не красивый вид страницы. Вид в HTML и CSS.",
      ),
      ideas: t(
        "İstək və cavab bir cütdür. Üsul nə etmək istədiyini deyir. Status nəticənin qısa nömrəsidir.",
        "A request and a response are a pair. The method says what you want done. The status is the short number of the result.",
        "İstek ve cevap bir çifttir. Yöntem ne yapmak istediğini söyler. Durum sonucun kısa numarasıdır.",
        "الطلب والجواب زوج. الطريقة تقول ماذا تريد أن يُفعل. الحالة رقم النتيجة القصير.",
        "Запрос и ответ — пара. Метод говорит, что нужно сделать. Статус — короткий номер результата.",
      ),
      ideaList: lines(
        ["GET oxuyur", "POST göndərir", "200 alındı", "404 ünvan yoxdur"],
        ["GET reads", "POST sends", "200 was received", "404 means the address is missing"],
        ["GET okur", "POST gönderir", "200 alındı", "404 adres yok"],
        ["GET يقرأ", "POST يرسل", "200 تم الاستلام", "404 العنوان غير موجود"],
        ["GET читает", "POST отправляет", "200 получено", "404 адреса нет"],
      ),
      sample: t(
        "Bu, baş səhifəni oxumaq üçün sadə istəyin ilk sətirləridir. Host başlığı hansı saytın nəzərdə tutulduğunu deyir.",
        "These are the first lines of a simple request that reads the front page. The Host header says which site is meant.",
        "Bunlar ön sayfayı okuyan sade bir isteğin ilk satırlarıdır. Host başlığı hangi sitenin kastedildiğini söyler.",
        "هذه الأسطر الأولى لطلب بسيط يقرأ الصفحة الأولى. ترويسة Host تقول أي موقع هو المقصود.",
        "Это первые строки простого запроса, который читает главную страницу. Заголовок Host говорит, какой сайт имеется в виду.",
      ),
      code: `GET / HTTP/1.1
Host: nibrascode.com`,
      faq: lines(
        ["HTTP və HTTPS eynidir? Qayda eynidir. HTTPS həmin yolu şifrələyir.", "GET ilə məlumat silinir? Olmaz. GET oxumaq üçündür. Silmə və ödəniş başqa üsuldur.", "HTTP proqramlaşdırma dilidir? Xeyr. İstək və cavabın yazılış qaydasıdır."],
        ["Are HTTP and HTTPS the same? The rule is the same. HTTPS encrypts that path.", "Does GET delete data? No. GET is for reading. Deleting and paying use another method.", "Is HTTP a programming language? No. It is the writing rule of a request and a response."],
        ["HTTP ve HTTPS aynı mı? Kural aynıdır. HTTPS o yolu şifreler.", "GET ile veri silinir mi? Hayır. GET okumak içindir. Silme ve ödeme başka yöntemdir.", "HTTP programlama dili mi? Hayır. İstek ve cevabın yazılış kuralıdır."],
        ["هل HTTP وHTTPS الشيء نفسه؟ القاعدة نفسها. HTTPS يشفّر ذلك الطريق.", "هل يحذف GET البيانات؟ لا. GET للقراءة. الحذف والدفع طريقة أخرى.", "هل HTTP لغة برمجة؟ لا. هو قاعدة كتابة الطلب والجواب."],
        ["HTTP и HTTPS — одно и то же? Правило одно. HTTPS шифрует этот путь.", "GET удаляет данные? Нет. GET для чтения. Удаление и оплата — другой метод.", "HTTP — язык программирования? Нет. Это правило записи запроса и ответа."],
      ),
    },
  ),
];
