import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_MORE: readonly StackPage[] = [
  topic(
    "git",
    "Git",
    t("Git nədir?", "What is Git?", "Git nedir?", "ما هو Git؟", "Что такое Git?"),
    t(
      "Git layihənin dəyişiklik tarixini saxlayan alətdir. Proqramlaşdırma dili deyil. Kodun kim, nə vaxt və nəyi dəyişdiyini göstərir.",
      "Git is a tool that keeps the history of a project. It is not a programming language. It shows who changed what, and when.",
      "Git, bir projenin değişiklik geçmişini tutan araçtır. Programlama dili değildir. Kodu kimin, ne zaman ve neyi değiştirdiğini gösterir.",
      "Git أداة تحفظ تاريخ تغييرات المشروع. ليست لغة برمجة. تُظهر من غيّر ماذا ومتى.",
      "Git — инструмент, который хранит историю проекта. Это не язык программирования. Он показывает, кто, когда и что изменил.",
    ),
    t("Git nədir, Git commit, GitHub, versiya", "what is Git, Git commit, GitHub, version control", "Git nedir, Git commit, GitHub", "ما هو Git, Git commit, GitHub", "что такое Git, коммит Git, GitHub"),
    {
      what: t(
        "Git hər yaddaşı commit adlı bir nöqtəyə yazır. Commit bütün layihənin surəti deyil, əvvəlki vəziyyətdən fərqdir. Tarix kompüterində qalır. GitHub və GitLab həmin tarixi başqası ilə bölüşmək üçün saytdır. Onlar Git-in özü deyil.",
        "Git writes each save as a point called a commit. A commit is not a full copy of the project. It is the difference from the previous state. The history stays on your computer. GitHub and GitLab are sites for sharing that history. They are not Git itself.",
        "Git her kaydı commit denen bir noktaya yazar. Commit bütün projenin kopyası değildir, önceki durumdan farktır. Geçmiş bilgisayarında kalır. GitHub ve GitLab bu geçmişi başkasıyla paylaşmak için sitedir. Onlar Git’in kendisi değildir.",
        "يكتب Git كل حفظ في نقطة اسمها commit. الـ commit ليس نسخة كاملة من المشروع، بل الفرق عن الحالة السابقة. يبقى التاريخ على جهازك. GitHub وGitLab موقعان لمشاركة ذلك التاريخ. ليسا Git نفسه.",
        "Git записывает каждое сохранение в точку под названием commit. Commit — не полная копия проекта, а отличие от прошлого состояния. История остаётся на компьютере. GitHub и GitLab — сайты, чтобы делиться этой историей. Это не сам Git.",
      ),
      uses: t(
        "Git bir nəfər işləyəndə də lazımdır. Səhv dəyişiklikdən geri qayıtmaq və başqasının kodunu qarışdırmadan almaq üçündür.",
        "Git is useful even when one person works. It is for going back from a bad change and for taking someone else's code without mixing it by hand.",
        "Git tek kişi çalışırken de gerekir. Yanlış değişiklikten geri dönmek ve başkasının kodunu elle karıştırmadan almak içindir.",
        "Git مفيد حتى حين يعمل شخص واحد. هو للرجوع عن تغيير سيئ وأخذ كود غيرك دون خلطه باليد.",
        "Git нужен даже когда работает один человек. Он нужен, чтобы вернуться от плохой правки и взять чужой код, не смешивая его руками.",
      ),
      useList: lines(
        ["Səhv commit-dən əvvələ qayıtmaq", "İki fikri ayrı budaqda saxlamaq", "Serverə yalnız hazır kodu göndərmək", "Komandanın eyni faylına toxunmaq"],
        ["Going back before a bad commit", "Keeping two ideas on separate branches", "Sending only finished code to a server", "Touching the same file as a team"],
        ["Kötü commit’ten önceye dönmek", "İki fikri ayrı dalda tutmak", "Sunucuya yalnız hazır kodu göndermek", "Takımın aynı dosyasına dokunmak"],
        ["الرجوع إلى ما قبل commit سيئ", "إبقاء فكرتين في فرعين", "إرسال الكود الجاهز فقط إلى الخادم", "لمس الملف نفسه مع الفريق"],
        ["Вернуться до плохого commit", "Держать две идеи на разных ветках", "Отправить на сервер только готовый код", "Трогать тот же файл, что и команда"],
      ),
      can: t(
        "Git ilə qovluğu izləyirsən, dəyişikliyi seçib commit edirsən, budaq açırsan və uzaq ünvana göndərirsən. Köhnə commit-ə baxıb faylı o günkü halına qaytarmaq olar. Git özü saytı işə salmır və kodu yoxlamır.",
        "With Git you track a folder, choose a change and commit it, open a branch, and send it to a remote address. You can look at an old commit and return a file to that day's state. Git itself does not start a site and does not check the code.",
        "Git ile klasörü izlersin, değişikliği seçip commit edersin, dal açarsın ve uzak adrese gönderirsin. Eski commit’e bakıp dosyayı o günkü haline döndürmek olur. Git kendi başına siteyi başlatmaz ve kodu denetlemez.",
        "بـ Git تتابع مجلداً وتختار تغييراً وتعمل له commit وتفتح فرعاً وترسله إلى عنوان بعيد. يمكن النظر إلى commit قديم وإعادة الملف إلى حال ذلك اليوم. Git نفسه لا يشغّل موقعاً ولا يفحص الكود.",
        "Через Git следят за папкой, выбирают изменение и делают commit, открывают ветку и отправляют на дальний адрес. Можно посмотреть старый commit и вернуть файл к состоянию того дня. Сам Git не запускает сайт и не проверяет код.",
      ),
      hard: t(
        "İlk üç əmr asandır: status, add, commit. Çətinlik budaq, birləşmə və münaqişədə başlayır. Eyni sətri iki nəfər dəyişəndə Git özü düzgün variantı seçmir. Sirr, şifrə və böyük fayl commit-ə düşməməlidir.",
        "The first three commands are easy: status, add, commit. The difficulty starts with a branch, a merge, and a conflict. When two people change the same line, Git does not pick the right version by itself. A secret, a password, and a huge file should not go into a commit.",
        "İlk üç komut kolaydır: status, add, commit. Zorluk dal, birleştirme ve çakışmada başlar. Aynı satırı iki kişi değiştirince Git doğru sürümü kendi seçmez. Sır, parola ve büyük dosya commit’e girmemelidir.",
        "الأوامر الثلاثة الأولى سهلة: status وadd وcommit. تبدأ الصعوبة مع الفرع والدمج والتعارض. حين يغيّر شخصان السطر نفسه لا يختار Git النسخة الصحيحة وحده. السر وكلمة المرور والملف الكبير لا يدخلون commit.",
        "Первые три команды простые: status, add, commit. Трудность начинается с ветки, слияния и конфликта. Когда двое меняют одну строку, Git сам не выбирает верную. Секрет, пароль и огромный файл не должны попасть в commit.",
      ),
      balance: t(
        "Üstünlük: tarix qalır, səhv geri alınır, bir neçə nəfər eyni layihədə işləyir. Məhdudiyyət: Git yedəkləmə xidməti deyil, serverdəki saytın özü deyil. Commit mesajı qısa və düz olmalıdır, yoxsa tarix oxunmur.",
        "Advantage: the history stays, a mistake can be undone, and several people work on one project. Limit: Git is not a backup service and it is not the site on the server. A commit message should be short and plain, or the history cannot be read.",
        "Avantaj: geçmiş kalır, hata geri alınır, birkaç kişi aynı projede çalışır. Sınır: Git yedekleme hizmeti değildir, sunucudaki sitenin kendisi değildir. Commit mesajı kısa ve düz olmalıdır, yoksa geçmiş okunmaz.",
        "الميزة: يبقى التاريخ ويمكن التراجع عن الخطأ ويعمل عدة أشخاص في مشروع واحد. الحد: Git ليست خدمة نسخ احتياطي وليست الموقع على الخادم. رسالة commit يجب أن تكون قصيرة وواضحة وإلا لا يُقرأ التاريخ.",
        "Плюс: история остаётся, ошибку можно отменить, несколько человек работают в одном проекте. Ограничение: Git — не служба резервных копий и не сам сайт на сервере. Сообщение commit должно быть коротким и ясным, иначе историю не прочитать.",
      ),
      ideas: t(
        "İş qovluğu, commit və uzaq ünvan üç ayrı yerdir. Budaq eyni tarixdən ayrılan xəttdir.",
        "The working folder, the commit, and the remote address are three separate places. A branch is a line that splits from the same history.",
        "Çalışma klasörü, commit ve uzak adres üç ayrı yerdir. Dal, aynı geçmişten ayrılan çizgidir.",
        "مجلد العمل والـ commit والعنوان البعيد ثلاثة أماكن. الفرع خط ينفصل عن التاريخ نفسه.",
        "Рабочая папка, commit и дальний адрес — три разных места. Ветка — линия, которая отходит от той же истории.",
      ),
      ideaList: lines(
        ["status nəyin dəyişdiyini göstərir", "add seçilmiş faylı növbəti commit-ə qoyur", "commit mesajla nöqtə yaradır", "push həmin nöqtəni uzaq ünvana göndərir"],
        ["status shows what changed", "add puts a chosen file into the next commit", "commit creates a point with a message", "push sends that point to the remote address"],
        ["status neyin değiştiğini gösterir", "add seçilen dosyayı sonraki commit’e koyar", "commit mesajla nokta oluşturur", "push o noktayı uzak adrese gönderir"],
        ["status يُظهر ما تغيّر", "add يضع الملف المختار في الـ commit التالي", "commit ينشئ نقطة مع رسالة", "push يرسل تلك النقطة إلى العنوان البعيد"],
        ["status показывает, что изменилось", "add кладёт выбранный файл в следующий commit", "commit создаёт точку с сообщением", "push отправляет эту точку на дальний адрес"],
      ),
      sample: t(
        "Bu üç əmr vəziyyətə baxır, faylları seçir və qısa mesajla yadda saxlayır. Mesajı öz dəyişikliyinə görə yaz.",
        "These three commands look at the state, choose the files, and save them with a short message. Write the message for your own change.",
        "Bu üç komut duruma bakar, dosyaları seçer ve kısa mesajla kaydeder. Mesajı kendi değişikliğine göre yaz.",
        "هذه الأوامر الثلاثة تنظر إلى الحالة وتختار الملفات وتحفظها برسالة قصيرة. اكتب الرسالة حسب تغييرك.",
        "Эти три команды смотрят состояние, выбирают файлы и сохраняют их с коротким сообщением. Напиши сообщение под своё изменение.",
      ),
      code: `git status
git add .
git commit -m "First note"`,
      faq: lines(
        ["Git və GitHub eynidir? Xeyr. Git alətdir. GitHub həmin tarixi saxlayan saytdır.", "Git yalnız kod üçündür? Əsasən mətn faylı üçündür. Şəkil və video üçün pis yoldur.", "Hər saxlama commit-dir? Xeyr. Əvvəl faylı seçirsən, sonra commit yazırsan."],
        ["Are Git and GitHub the same? No. Git is the tool. GitHub is a site that stores that history.", "Is Git only for code? It is mainly for text files. It is a poor path for images and video.", "Is every save a commit? No. First you choose the file, then you write the commit."],
        ["Git ve GitHub aynı mı? Hayır. Git araçtır. GitHub o geçmişi saklayan sitedir.", "Git yalnız kod için mi? Daha çok metin dosyası içindir. Resim ve video için kötü yoldur.", "Her kayıt commit midir? Hayır. Önce dosyayı seçersin, sonra commit yazarsın."],
        ["هل Git وGitHub الشيء نفسه؟ لا. Git الأداة. GitHub موقع يحفظ ذلك التاريخ.", "هل Git للكود فقط؟ هو أساساً لملفات النص. الصور والفيديو طريق ضعيف.", "هل كل حفظ commit؟ لا. تختار الملف أولاً ثم تكتب الـ commit."],
        ["Git и GitHub — одно и то же? Нет. Git — инструмент. GitHub — сайт, который хранит эту историю.", "Git только для кода? В основном для текстовых файлов. Для картинок и видео это плохой путь.", "Каждое сохранение — это commit? Нет. Сначала выбираешь файл, потом пишешь commit."],
      ),
    },
  ),
  topic(
    "bash",
    "Bash",
    t("Bash nədir?", "What is Bash?", "Bash nedir?", "ما هو Bash؟", "Что такое Bash?"),
    t(
      "Bash əmrləri yazdığın proqramdır. Ubuntu terminalında çox vaxt o işləyir. Proqramlaşdırma dili kimi deyil, əmr dilidir.",
      "Bash is the program where you type commands. It is what usually runs in the Ubuntu terminal. It is a command language, not a language like Python.",
      "Bash, komutları yazdığın programdır. Ubuntu terminalinde çoğu zaman o çalışır. Python gibi bir dil değil, komut dilidir.",
      "Bash البرنامج الذي تكتب فيه الأوامر. هو الذي يعمل غالباً في طرفية Ubuntu. لغة أوامر، لا لغة مثل Python.",
      "Bash — программа, в которой пишут команды. В терминале Ubuntu обычно работает она. Это командный язык, не язык вроде Python.",
    ),
    t("Bash nədir, terminal, Ubuntu Bash, shell skript", "what is Bash, terminal, Ubuntu Bash, shell script", "Bash nedir, terminal, Ubuntu Bash", "ما هو Bash, طرفية, Ubuntu", "что такое Bash, терминал, Ubuntu Bash"),
    {
      what: t(
        "Bash shell-dir: əmri oxuyur, proqramı işə salır, nəticəni ekrana yazır. Terminal pəncərədir. Bash onun içindəki dildir. Ubuntu-da standart shell çox vaxt Bash-dır. macOS-da uzun müddət Bash idi, indi çox vaxt zsh-dir. Əmrlərin çoxu hər ikisində oxşardır.",
        "Bash is a shell: it reads a command, starts a program, and writes the result on the screen. The terminal is the window. Bash is the language inside it. On Ubuntu the default shell is usually Bash. On macOS it was Bash for a long time, and now it is often zsh. Most commands look alike in both.",
        "Bash bir kabuktur: komutu okur, programı başlatır, sonucu ekrana yazar. Terminal penceredir. Bash onun içindeki dildir. Ubuntu’da varsayılan kabuk çoğu zaman Bash’tır. macOS’ta uzun süre Bash idi, şimdi çoğu zaman zsh’dir. Komutların çoğu ikisinde benzerdir.",
        "Bash صدفة: تقرأ الأمر وتشغّل البرنامج وتكتب النتيجة على الشاشة. الطرفية هي النافذة. Bash اللغة داخلها. على Ubuntu الصدفة الافتراضية غالباً Bash. على macOS كانت Bash زمناً طويلاً والآن غالباً zsh. أكثر الأوامر متشابهة في الاثنين.",
        "Bash — это оболочка: читает команду, запускает программу и пишет результат на экран. Терминал — окно. Bash — язык внутри него. В Ubuntu оболочка по умолчанию обычно Bash. В macOS долго был Bash, теперь часто zsh. Большинство команд в обеих похожи.",
      ),
      uses: t(
        "Bash fayl tapmaq, proqram qurmaq və eyni əmri təkrarlamaq üçündür. Serverə SSH ilə girəndə də qarşına o çıxır.",
        "Bash is for finding a file, installing a program, and repeating the same command. It is also what you meet when you enter a server with SSH.",
        "Bash dosya bulmak, program kurmak ve aynı komutu tekrarlamak içindir. Sunucuya SSH ile girince de onu görürsün.",
        "Bash للعثور على ملف وتثبيت برنامج وتكرار الأمر نفسه. تراه أيضاً حين تدخل خادماً بـ SSH.",
        "Bash нужен, чтобы найти файл, поставить программу и повторить одну команду. Его же видишь, когда входишь на сервер по SSH.",
      ),
      useList: lines(
        ["Qovluqdakı faylları görmək", "apt ilə paket qurmaq", "Bir neçə əmri bir skriptdə saxlamaq", "Nginx və ya Docker-i yoxlamaq"],
        ["Seeing the files in a folder", "Installing a package with apt", "Keeping several commands in one script", "Checking Nginx or Docker"],
        ["Klasördeki dosyaları görmek", "apt ile paket kurmak", "Birkaç komutu bir betikte tutmak", "Nginx veya Docker’ı denetlemek"],
        ["رؤية الملفات في مجلد", "تثبيت حزمة بـ apt", "حفظ عدة أوامر في سكربت", "فحص Nginx أو Docker"],
        ["Видеть файлы в папке", "Ставить пакет через apt", "Держать несколько команд в одном скрипте", "Проверять Nginx или Docker"],
      ),
      can: t(
        "Bash ilə adını dəyişir, faylı köçürür, mətn axtarır və proqramın çıxışını başqa proqrama ötürürsən. Skript eyni işi hər dəfə eyni sıra ilə görür. Pəncərəli proqram yazmaq onun işi deyil.",
        "With Bash you rename, copy a file, search text, and send one program's output into another. A script does the same job in the same order every time. Writing a windowed program is not its job.",
        "Bash ile ad değiştirir, dosya kopyalar, metin arar ve bir programın çıktısını başka programa iletirsin. Betik aynı işi her seferinde aynı sırayla görür. Pencereli program yazmak onun işi değildir.",
        "بـ Bash تعيد التسمية وتنسخ ملفاً وتبحث في النص وتمرّر خرج برنامج إلى آخر. السكربت يؤدي العمل نفسه بالترتيب نفسه كل مرة. كتابة برنامج نوافذ ليست عمله.",
        "В Bash переименовывают, копируют файл, ищут текст и передают вывод одной программы в другую. Скрипт делает ту же работу в том же порядке каждый раз. Писать оконную программу — не его дело.",
      ),
      hard: t(
        "Bir əmr yazmaq asandır. Çətinlik boşluq, dırnaq və icazədədir. Fayl adında boşluq varsa dırnaqsız əmr onu iki fayl sanır. sudo hər sətirdə lazım deyil. Sistemi dəyişən əmrdə işlədilir.",
        "Typing one command is easy. The difficulty is the space, the quote, and the permission. If a file name has a space, a command without quotes treats it as two files. sudo is not needed on every line. It is used on a command that changes the system.",
        "Bir komut yazmak kolaydır. Zorluk boşluk, tırnak ve izindedir. Dosya adında boşluk varsa tırnaksız komut onu iki dosya sanır. sudo her satırda gerekmez. Sistemi değiştiren komutta kullanılır.",
        "كتابة أمر واحد سهلة. الصعوبة في المسافة وعلامة الاقتباس والإذن. إذا كان في اسم الملف مسافة فالأمر بلا اقتباس يحسبه ملفين. sudo ليس لكل سطر. يُستخدم في الأمر الذي يغيّر النظام.",
        "Написать одну команду легко. Трудность в пробеле, кавычке и праве. Если в имени файла есть пробел, команда без кавычек считает его двумя файлами. sudo не нужен в каждой строке. Его ставят на команду, которая меняет систему.",
      ),
      balance: t(
        "Üstünlük: eyni işi əl ilə təkrarlamırsan, serverdə pəncərə olmadan işləyirsən. Məhdudiyyət: skript başqa kompüterdə fərqli əmr tapa bilər. Silmə əmri geri alınmır. Əvvəl adı yoxla, sonra sil.",
        "Advantage: you do not repeat the same job by hand, and you work on a server without a window. Limit: a script may find a different command on another computer. A delete command is not undone. Check the name first, then delete.",
        "Avantaj: aynı işi elle tekrarlamazsın, sunucuda penceresiz çalışırsın. Sınır: betik başka bilgisayarda farklı komut bulabilir. Silme komutu geri alınmaz. Önce adı denetle, sonra sil.",
        "الميزة: لا تكرر العمل نفسه باليد وتعمل على الخادم بلا نافذة. الحد: قد يجد السكربت أمراً مختلفاً على جهاز آخر. أمر الحذف لا يُتراجع عنه. افحص الاسم أولاً ثم احذف.",
        "Плюс: одну работу не повторяешь руками и работаешь на сервере без окна. Ограничение: скрипт может найти другую команду на другом компьютере. Команда удаления не отменяется. Сначала проверь имя, потом удаляй.",
      ),
      ideas: t(
        "Əmr, arqument və bayraq üç hissədir. | işarəsi bir əmrin nəticəsini sonrakına verir.",
        "A command, an argument, and a flag are three parts. The | sign gives one command's result to the next.",
        "Komut, argüman ve bayrak üç parçadır. | işareti bir komutun sonucunu sonrakine verir.",
        "الأمر والوسيط والعلم ثلاثة أجزاء. علامة | تعطي نتيجة أمر للأمر التالي.",
        "Команда, аргумент и флаг — три части. Знак | отдаёт результат одной команды следующей.",
      ),
      ideaList: lines(
        ["pwd hazırkı qovluğu göstərir", "ls faylları sayır", "cd qovluğa keçir", "echo mətni yazır"],
        ["pwd shows the current folder", "ls lists the files", "cd moves into a folder", "echo writes text"],
        ["pwd bulunduğu klasörü gösterir", "ls dosyaları dizer", "cd klasöre geçer", "echo metni yazar"],
        ["pwd يُظهر المجلد الحالي", "ls يسرد الملفات", "cd يدخل مجلداً", "echo يكتب النص"],
        ["pwd показывает текущую папку", "ls перечисляет файлы", "cd переходит в папку", "echo пишет текст"],
      ),
      sample: t(
        "Bu iki sətir bir ad saxlayır və onu ekrana yazır. Fayl skript olacaqsa birinci sətir çox vaxt #!/usr/bin/env bash olur.",
        "These two lines store a name and write it on the screen. If the file will be a script, the first line is often #!/usr/bin/env bash.",
        "Bu iki satır bir ad saklar ve onu ekrana yazar. Dosya betik olacaksa ilk satır çoğu zaman #!/usr/bin/env bash olur.",
        "هذان السطران يحفظان اسماً ويكتبانه على الشاشة. إذا كان الملف سكربتاً فالسطر الأول غالباً #!/usr/bin/env bash.",
        "Эти две строки хранят имя и пишут его на экран. Если файл будет скриптом, первая строка часто #!/usr/bin/env bash.",
      ),
      code: `name="Nibras"
echo "Hello, $name"`,
      faq: lines(
        ["Terminal və Bash eynidir? Xeyr. Terminal pəncərədir. Bash içindəki əmr dilidir.", "Hər Linux əmri Bash-dır? Xeyr. ls və apt ayrı proqramdır. Bash onları işə salır.", "Bash sayt yazır? Xeyr. Saytın qurulması və yoxlanması üçündür, səhifənin özü deyil."],
        ["Are the terminal and Bash the same? No. The terminal is the window. Bash is the command language inside it.", "Is every Linux command Bash? No. ls and apt are separate programs. Bash starts them.", "Does Bash write a site? No. It is for installing and checking, not for the page itself."],
        ["Terminal ve Bash aynı mı? Hayır. Terminal penceredir. Bash içindeki komut dilidir.", "Her Linux komutu Bash mı? Hayır. ls ve apt ayrı programdır. Bash onları başlatır.", "Bash site yazar mı? Hayır. Kurmak ve denetlemek içindir, sayfanın kendisi değildir."],
        ["هل الطرفية وBash الشيء نفسه؟ لا. الطرفية نافذة. Bash لغة الأوامر داخلها.", "هل كل أمر Linux هو Bash؟ لا. ls وapt برنامجان منفصلان. Bash يشغّلهما.", "هل يكتب Bash موقعاً؟ لا. هو للتثبيت والفحص، لا للصفحة نفسها."],
        ["Терминал и Bash — одно и то же? Нет. Терминал — окно. Bash — командный язык внутри.", "Каждая команда Linux — это Bash? Нет. ls и apt — отдельные программы. Bash их запускает.", "Bash пишет сайт? Нет. Он для установки и проверки, не для самой страницы."],
      ),
    },
  ),
  topic(
    "json",
    "JSON",
    t("JSON nədir?", "What is JSON?", "JSON nedir?", "ما هو JSON؟", "Что такое JSON?"),
    t(
      "JSON məlumatı mətnlə yazmağın qaydasıdır. Proqramlaşdırma dili deyil. API, tənzim və paket siyahısı onu oxuyur.",
      "JSON is a rule for writing data as text. It is not a programming language. An API, a setting, and a package list are read from it.",
      "JSON, veriyi metinle yazma kuralıdır. Programlama dili değildir. API, ayar ve paket listesi onu okur.",
      "JSON قاعدة لكتابة البيانات نصاً. ليست لغة برمجة. تقرأه واجهة وتهيئة وقائمة حزم.",
      "JSON — правило записывать данные текстом. Это не язык программирования. Его читают API, настройка и список пакетов.",
    ),
    t("JSON nədir, JSON format, API JSON, package.json", "what is JSON, JSON format, API JSON, package.json", "JSON nedir, JSON biçimi, API JSON", "ما هو JSON, تنسيق JSON, package.json", "что такое JSON, формат JSON, package.json"),
    {
      what: t(
        "JSON açarlar və qiymətlərdən ibarətdir. Açar həmişə dırnaqlı mətndir. Qiymət mətn, ədəd, true, false, null, siyahı və ya başqa obyekt ola bilər. Şərh yoxdur. Sonda vergül standart JSON-da xətadır. JavaScript obyektinə bənzəyir, amma eyni deyil.",
        "JSON is made of keys and values. A key is always quoted text. A value can be text, a number, true, false, null, a list, or another object. There is no comment. A trailing comma is an error in standard JSON. It looks like a JavaScript object, but it is not the same.",
        "JSON anahtar ve değerlerden oluşur. Anahtar her zaman tırnaklı metindir. Değer metin, sayı, true, false, null, liste veya başka nesne olabilir. Yorum yoktur. Sondaki virgül standart JSON’da hatadır. JavaScript nesnesine benzer, ama aynı değildir.",
        "يتكوّن JSON من مفاتيح وقيم. المفتاح دائماً نص بين علامتي اقتباس. القيمة قد تكون نصاً أو رقماً أو true أو false أو null أو قائمة أو كائناً آخر. لا تعليق. الفاصلة في الآخر خطأ في JSON القياسي. يشبه كائن JavaScript لكنه ليس نفسه.",
        "JSON состоит из ключей и значений. Ключ всегда текст в кавычках. Значение может быть текстом, числом, true, false, null, списком или другим объектом. Комментария нет. Запятая в конце — ошибка в стандартном JSON. Он похож на объект JavaScript, но это не одно и то же.",
      ),
      uses: t(
        "JSON iki proqramın bir-birinə məlumat göndərməsi üçündür. Brauzer, server və telefon eyni mətni oxuya bilir.",
        "JSON is for two programs sending data to each other. A browser, a server, and a phone can read the same text.",
        "JSON iki programın birbirine veri göndermesi içindir. Tarayıcı, sunucu ve telefon aynı metni okuyabilir.",
        "JSON ليرسل برنامجان البيانات بينهما. المتصفح والخادم والهاتف يقرأون النص نفسه.",
        "JSON нужен, чтобы две программы послали данные друг другу. Браузер, сервер и телефон могут прочитать один и тот же текст.",
      ),
      useList: lines(
        ["API cavabı", "package.json asılılıq siyahısı", "Tətbiq tənzimi", "Tərcümə faylı"],
        ["An API answer", "The dependency list in package.json", "An app setting", "A translation file"],
        ["API cevabı", "package.json bağımlılık listesi", "Uygulama ayarı", "Çeviri dosyası"],
        ["جواب واجهة", "قائمة الاعتمادات في package.json", "تهيئة تطبيق", "ملف ترجمة"],
        ["Ответ API", "Список зависимостей в package.json", "Настройка приложения", "Файл перевода"],
      ),
      can: t(
        "JSON ilə bir istifadəçinin adını, yaşını və siyahısını bir faylda saxlayırsan. Proqram onu oxuyur, dəyişir və yenidən mətn edir. JSON özü hesab aparmır və səhifə çəkmir. Hesab başqa dildədir.",
        "With JSON you keep a person's name, age, and list in one file. A program reads it, changes it, and turns it back into text. JSON itself does not calculate and does not draw a page. The calculation is in another language.",
        "JSON ile bir kişinin adını, yaşını ve listesini bir dosyada tutarsın. Program onu okur, değiştirir ve yeniden metin yapar. JSON kendi hesap yapmaz ve sayfa çizmez. Hesap başka dildedir.",
        "بـ JSON تحفظ اسم شخص وعمره وقائمته في ملف واحد. البرنامج يقرأه ويغيّره ويعيده نصاً. JSON نفسه لا يحسب ولا يرسم صفحة. الحساب في لغة أخرى.",
        "В JSON хранят имя человека, возраст и список в одном файле. Программа читает его, меняет и снова делает текстом. Сам JSON не считает и не рисует страницу. Счёт в другом языке.",
      ),
      hard: t(
        "Kiçik fayl asandır. Çətinlik dırnaq və vergül səhvidir. Bir vergül bütün faylı yararsız edir. İç-içə obyekt uzananda gözlə izləmək çətinləşir. İstifadəçi mətnini yoxlamadan obyektə çevirmək təhlükəlidir.",
        "A small file is easy. The difficulty is a quote and a comma mistake. One comma makes the whole file useless. When objects sit inside objects, the eye loses the path. Turning user text into an object without a check is unsafe.",
        "Küçük dosya kolaydır. Zorluk tırnak ve virgül hatasıdır. Bir virgül bütün dosyayı işe yaramaz eder. İçe içe nesne uzayınca göz yolu kaybeder. Kullanıcı metnini denetlemeden nesneye çevirmek güvensizdir.",
        "الملف الصغير سهل. الصعوبة خطأ الاقتباس والفاصلة. فاصلة واحدة تجعل الملف كله بلا فائدة. حين تتداخل الكائنات يضيع النظر. تحويل نص المستخدم إلى كائن بلا فحص غير آمن.",
        "Маленький файл прост. Трудность — ошибка кавычки и запятой. Одна запятая делает весь файл бесполезным. Когда объекты внутри объектов, глаз теряет путь. Превращать текст пользователя в объект без проверки небезопасно.",
      ),
      balance: t(
        "Üstünlük: adam oxuyur, demək olar hər dilin kitabxanası var, fayl kiçik qalır. Məhdudiyyət: şərh yoxdur, tarix və pul öz tipi deyil, hamısı mətn və ya ədəddir. Böyük cədvəl üçün verilənlər bazası daha düz yoldur.",
        "Advantage: a person can read it, almost every language has a library, and the file stays small. Limit: there is no comment, and a date and money are not their own type. They are text or a number. For a large table, a database is the straighter path.",
        "Avantaj: insan okur, neredeyse her dilin kütüphanesi vardır, dosya küçük kalır. Sınır: yorum yoktur, tarih ve para kendi tipi değildir, ikisi de metin veya sayıdır. Büyük tablo için veritabanı daha düz yoldur.",
        "الميزة: يقرؤه الإنسان ولكل لغة تقريباً مكتبة ويبقى الملف صغيراً. الحد: لا تعليق، والتاريخ والمال ليسا نوعاً خاصاً، كلاهما نص أو رقم. للجدول الكبير قاعدة البيانات طريق أوضح.",
        "Плюс: человек его читает, почти у каждого языка есть библиотека, файл остаётся маленьким. Ограничение: комментария нет, дата и деньги не свой тип, это текст или число. Для большой таблицы база данных — более прямой путь.",
      ),
      ideas: t(
        "Obyekt fiqurlu mötərizədədir. Siyahı kvadrat mötərizədədir. İkisi qarışa bilər.",
        "An object is in curly brackets. A list is in square brackets. The two can sit inside each other.",
        "Nesne süslü parantezdedir. Liste köşeli parantezdedir. İkisi birbirinin içine girebilir.",
        "الكائن بين قوسين معقوفين. القائمة بين قوسين مربعين. يمكن أن يدخل أحدهما في الآخر.",
        "Объект в фигурных скобках. Список в квадратных. Они могут лежать друг в друге.",
      ),
      ideaList: lines(
        ["Açar həmişə dırnaqdadır", "Mətn də dırnaqdadır", "true və false kiçik hərflədir", "Boş qiymət null-dur, boş mətn deyil"],
        ["A key is always in quotes", "Text is in quotes too", "true and false are lowercase", "An empty value is null, not empty text"],
        ["Anahtar her zaman tırnaklıdır", "Metin de tırnaklıdır", "true ve false küçük harftir", "Boş değer null’dur, boş metin değildir"],
        ["المفتاح دائماً بين اقتباس", "النص أيضاً بين اقتباس", "true وfalse بحروف صغيرة", "القيمة الفارغة null لا نص فارغ"],
        ["Ключ всегда в кавычках", "Текст тоже в кавычках", "true и false строчными буквами", "Пустое значение — null, не пустой текст"],
      ),
      sample: t(
        "Bu mətn bir adı və hazır olub-olmadığını saxlayır. Son açardan sonra vergül qoyma.",
        "This text stores a name and whether it is ready. Do not put a comma after the last key.",
        "Bu metin bir adı ve hazır olup olmadığını saklar. Son anahtardan sonra virgül koyma.",
        "هذا النص يحفظ اسماً وهل هو جاهز. لا تضع فاصلة بعد المفتاح الأخير.",
        "Этот текст хранит имя и готов ли он. Не ставь запятую после последнего ключа.",
      ),
      code: `{
  "name": "Nibras",
  "ready": true
}`,
      faq: lines(
        ["JSON və JavaScript eynidir? Xeyr. JSON yalnız məlumat mətnidir. JavaScript dildir.", "JSON-da şərh yazılır? Standart JSON-da yox. Şərh lazımdırsa bu, artıq başqa formadır.", "JSON verilənlər bazasıdır? Xeyr. Fayl və ya cavab mətnidir. Bazanın özü deyil."],
        ["Are JSON and JavaScript the same? No. JSON is only data text. JavaScript is a language.", "Can you write a comment in JSON? Not in standard JSON. If you need a comment, that is already another format.", "Is JSON a database? No. It is a file or an answer text. It is not the database itself."],
        ["JSON ve JavaScript aynı mı? Hayır. JSON yalnız veri metnidir. JavaScript dildir.", "JSON’da yorum yazılır mı? Standart JSON’da hayır. Yorum gerekiyorsa bu artık başka biçimdir.", "JSON veritabanı mı? Hayır. Dosya veya cevap metnidir. Veritabanının kendisi değildir."],
        ["هل JSON وJavaScript الشيء نفسه؟ لا. JSON نص بيانات فقط. JavaScript لغة.", "هل يُكتب تعليق في JSON؟ لا في JSON القياسي. إذا لزم تعليق فهذا شكل آخر.", "هل JSON قاعدة بيانات؟ لا. هو ملف أو نص جواب. ليس قاعدة البيانات نفسها."],
        ["JSON и JavaScript — одно и то же? Нет. JSON — только текст данных. JavaScript — язык.", "В JSON пишут комментарий? В стандартном JSON нет. Если нужен комментарий, это уже другой формат.", "JSON — это база данных? Нет. Это файл или текст ответа. Не сама база."],
      ),
    },
  ),
];
