import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_FEW: readonly StackPage[] = [
  topic(
    "pip",
    "pip",
    t("pip nədir?", "What is pip?", "pip nedir?", "ما هو pip؟", "Что такое pip?"),
    t(
      "pip Python paketini endirən alətdir. Python proqramı işlədir, pip isə kitabxananı gətirir. Node.js pip işlətmir. Onun paketi npm ilə gəlir.",
      "pip is the tool that downloads a Python package. Python runs the program, and pip brings the library. Node.js does not use pip. Its package comes with npm.",
      "pip, Python paketini indiren araçtır. Python programı çalıştırır, pip ise kütüphaneyi getirir. Node.js pip kullanmaz. Onun paketi npm ile gelir.",
      "pip أداة تنزّل حزمة Python. Python يشغّل البرنامج وpip يجلب المكتبة. Node.js لا يستخدم pip. حزمته تأتي بـ npm.",
      "pip — инструмент, который скачивает пакет Python. Python запускает программу, а pip приносит библиотеку. Node.js не использует pip. Его пакет приходит через npm.",
    ),
    t("pip nədir, pip install, requirements.txt, Python", "what is pip, pip install, requirements.txt, Python", "pip nedir, pip install, requirements.txt", "ما هو pip, pip install, requirements.txt", "что такое pip, pip install, requirements.txt"),
    {
      what: t(
        "pip Python-un paket alətidir. Adı «pip installs packages» sözlərindən yığılır. Paketlər PyPI reyestrində durur. requirements.txt layihənin paket siyahısıdır. pip install -r həmin siyahını oxuyur. Python 3.4-dən bəri pip adətən Python ilə birlikdə gəlir. Virtual mühit paketləri layihənin içinə yığır ki, başqa layihənin versiyası buna qarışmasın. Python ilə fərqi budur: Python faylı işlədir, pip heç bir proqramı özü işlətmir. Node.js ilə fərqi də budur: Node JavaScript işlədir və pip işlətmir. Node-un paketi npm ilə gəlir. pip yalnız Python üçündür.",
        "pip is Python's package tool. The name is built from the words pip installs packages. Packages sit in the PyPI registry. requirements.txt is the project's package list. pip install -r reads that list. Since Python 3.4, pip usually comes with Python. A virtual environment gathers packages inside the project, so another project's version does not mix in. The difference from Python is this: Python runs the file, and pip does not run any program by itself. The difference from Node.js is this too: Node runs JavaScript and does not use pip. Node's package comes with npm. pip is only for Python.",
        "pip, Python’un paket aracıdır. Adı «pip installs packages» sözlerinden kurulur. Paketler PyPI kaydında durur. requirements.txt projenin paket listesidir. pip install -r o listeyi okur. Python 3.4’ten beri pip genellikle Python ile birlikte gelir. Sanal ortam paketleri projenin içine toplar ki başka projenin sürümü buna karışmasın. Python ile farkı şudur: Python dosyayı çalıştırır, pip hiçbir programı kendi çalıştırmaz. Node.js ile farkı da şudur: Node JavaScript çalıştırır ve pip kullanmaz. Node’un paketi npm ile gelir. pip yalnız Python içindir.",
        "pip أداة حزم Python. الاسم مركب من كلمات pip installs packages. الحزم تقف في سجل PyPI. requirements.txt قائمة حزم المشروع. pip install -r يقرأ تلك القائمة. منذ Python 3.4 يأتي pip عادة مع Python. البيئة الافتراضية تجمع الحزم داخل المشروع كي لا تختلط نسخة مشروع آخر. الفرق عن Python هو هذا: Python يشغّل الملف وpip لا يشغّل أي برنامج بنفسه. الفرق عن Node.js هو هذا أيضاً: Node يشغّل JavaScript ولا يستخدم pip. حزمة Node تأتي بـ npm. pip لـ Python فقط.",
        "pip — инструмент пакетов Python. Имя собрано из слов pip installs packages. Пакеты лежат в реестре PyPI. requirements.txt — список пакетов проекта. pip install -r читает этот список. С Python 3.4 pip обычно идёт вместе с Python. Виртуальная среда собирает пакеты внутри проекта, чтобы версия другого проекта не вмешалась. Разница с Python такая: Python запускает файл, а pip сам никакую программу не запускает. Разница с Node.js такая же: Node запускает JavaScript и не использует pip. Пакет Node приходит через npm. pip только для Python.",
      ),
      uses: t(
        "pip kitabxananı bir dəfə qurmaq və eyni siyahını başqa kompüterdə təkrarlamaq üçündür.",
        "pip is for installing a library once and repeating the same list on another computer.",
        "pip kütüphaneyi bir kez kurmak ve aynı listeyi başka bilgisayarda tekrarlamak içindir.",
        "pip لتثبيت مكتبة مرة وتكرار القائمة نفسها على حاسوب آخر.",
        "pip нужен, чтобы один раз поставить библиотеку и повторить тот же список на другом компьютере.",
      ),
      useList: lines(
        ["Hazır kitabxananı layihəyə qurmaq", "Siyahını requirements.txt-də saxlamaq", "Virtual mühitdə versiyanı ayırmaq", "Köhnə paketi yenisi ilə əvəz etmək"],
        ["Installing a ready library into the project", "Keeping the list in requirements.txt", "Separating the version in a virtual environment", "Replacing an old package with a newer one"],
        ["Hazır kütüphaneyi projeye kurmak", "Listeyi requirements.txt içinde tutmak", "Sürümü sanal ortamda ayırmak", "Eski paketi yenisiyle değiştirmek"],
        ["تثبيت مكتبة جاهزة في المشروع", "حفظ القائمة في requirements.txt", "فصل النسخة في بيئة افتراضية", "استبدال حزمة قديمة بأخرى أحدث"],
        ["Поставить готовую библиотеку в проект", "Хранить список в requirements.txt", "Отделить версию в виртуальной среде", "Заменить старый пакет более новым"],
      ),
      can: t(
        "pip ilə paket endirir, siyahıdan qurur və qurulmuş adı göstərirsən. O, Python proqramını özü yazmır. Paketin kodu sənin əmrinlə işə düşə bilər. Tanımadığın paketi qurmaq həmin kodu da gətirir.",
        "With pip you download a package, install from the list, and show the installed name. It does not write the Python program itself. A package's code can start with your command. Installing a package you do not know brings that code too.",
        "pip ile paket indirir, listeden kurar ve kurulu adı gösterirsin. Python programını kendi yazmaz. Paketin kodu senin komutunla işe düşebilir. Tanımadığın paketi kurmak o kodu da getirir.",
        "بـ pip تنزّل حزمة وتثبّت من القائمة وتُظهر الاسم المثبّت. هو لا يكتب برنامج Python نفسه. كود الحزمة قد يبدأ بأمرك. تثبيت حزمة لا تعرفها يجلب ذلك الكود أيضاً.",
        "Через pip скачивают пакет, ставят из списка и показывают установленное имя. Сам он программу на Python не пишет. Код пакета может запуститься твоей командой. Установка незнакомого пакета приносит и этот код.",
      ),
      hard: t(
        "Bir paket qurmaq asandır. Çətinlik versiyanın qarışmasındadır. Kompüterdəki pip başqa Python-a baxa bilər. Siyahını yazmayıb yalnız əllə qurmaq sabah başqa maşında eyni nəticəni vermir. Virtual mühit açılmadan paket ümumi yerə düşür.",
        "Installing one package is easy. The difficulty is the versions mixing. The pip on the computer may look at another Python. Installing only by hand, without writing the list, does not give the same result on another machine tomorrow. Without a virtual environment, the package falls into the shared place.",
        "Bir paket kurmak kolaydır. Zorluk sürümün karışmasıdır. Bilgisayardaki pip başka Python’a bakabilir. Listeyi yazmadan yalnız elle kurmak yarın başka makinede aynı sonucu vermez. Sanal ortam açılmadan paket ortak yere düşer.",
        "تثبيت حزمة واحدة سهل. الصعوبة اختلاط النسخ. pip على الحاسوب قد ينظر إلى Python آخر. التثبيت باليد وحدها بلا كتابة القائمة لا يعطي النتيجة نفسها على جهاز آخر غداً. بلا بيئة افتراضية تقع الحزمة في المكان المشترك.",
        "Поставить один пакет легко. Трудность в том, что версии смешиваются. pip на компьютере может смотреть на другой Python. Ставить только руками, не записав список, завтра на другой машине не даст того же результата. Без виртуальной среды пакет падает в общее место.",
      ),
      balance: t(
        "Üstünlük: kitabxana təkrar yazılmır, siyahı bir faylda durur, Python ilə hazır gəlir. Məhdudiyyət: səhv Python-a qurmaq sakit xəta yaradır. Hər kiçik iş üçün paket lazım deyil. pip Python-un özü deyil.",
        "Advantage: a library is not rewritten, the list stays in one file, and it comes ready with Python. Limit: installing into the wrong Python makes a quiet mistake. Not every small job needs a package. pip is not Python itself.",
        "Avantaj: kütüphane yeniden yazılmaz, liste bir dosyada durur, Python ile hazır gelir. Sınır: yanlış Python’a kurmak sessiz hata doğurur. Her küçük iş için paket gerekmez. pip, Python’un kendisi değildir.",
        "الميزة: لا تُعاد كتابة المكتبة والقائمة تبقى في ملف واحد ويأتي جاهزاً مع Python. الحد: التثبيت في Python الخطأ يصنع خطأً صامتاً. ليس كل عمل صغير يحتاج حزمة. pip ليس Python نفسه.",
        "Плюс: библиотеку не переписывают, список лежит в одном файле, и он уже идёт с Python. Ограничение: установка в неверный Python даёт тихую ошибку. Не каждой мелкой работе нужен пакет. pip — это не сам Python.",
      ),
      ideas: t(
        "Paket hazır koddur. Siyahı layihənin nəyə ehtiyacı olduğunu deyir. Mühit həmin paketlərin ayrı qovluğudur.",
        "A package is ready code. The list says what the project needs. The environment is the separate folder of those packages.",
        "Paket hazır koddur. Liste projenin neye ihtiyacı olduğunu söyler. Ortam o paketlerin ayrı klasörüdür.",
        "الحزمة كود جاهز. القائمة تقول ماذا يحتاج المشروع. البيئة المجلد المنفصل لتلك الحزم.",
        "Пакет — готовый код. Список говорит, что нужно проекту. Среда — отдельная папка этих пакетов.",
      ),
      ideaList: lines(
        ["pip install bir paket qurur", "requirements.txt siyahını saxlayır", "venv mühiti ayırır", "PyPI paketlərin ümumi yeridir"],
        ["pip install installs one package", "requirements.txt keeps the list", "venv separates the environment", "PyPI is the shared place of packages"],
        ["pip install bir paket kurar", "requirements.txt listeyi tutar", "venv ortamı ayırır", "PyPI paketlerin ortak yeridir"],
        ["pip install يثبّت حزمة واحدة", "requirements.txt يحفظ القائمة", "venv يفصل البيئة", "PyPI المكان المشترك للحزم"],
        ["pip install ставит один пакет", "requirements.txt хранит список", "venv отделяет среду", "PyPI — общее место пакетов"],
      ),
      sample: t(
        "Bu əmr siyahıdakı paketləri qurur. Siyahı boşdursa heç nə endirmir.",
        "This command installs the packages in the list. If the list is empty, it downloads nothing.",
        "Bu komut listedeki paketleri kurar. Liste boşsa hiçbir şey indirmez.",
        "هذا الأمر يثبّت الحزم في القائمة. إذا كانت القائمة فارغة لا ينزّل شيئاً.",
        "Эта команда ставит пакеты из списка. Если список пуст, она ничего не скачивает.",
      ),
      code: `pip install -r requirements.txt`,
      faq: lines(
        ["pip və Python eynidir? Xeyr. Python .py faylını işlədir. pip həmin faylın kitabxanasını gətirir və özü proqram işlətmir.", "pip və Node.js eynidir? Xeyr. Node JavaScript işlədir və pip işlətmir. Node-un paketi npm ilə gəlir. pip yalnız Python üçündür.", "requirements.txt paketin özüdür? Xeyr. O, adların siyahısıdır."],
        ["Are pip and Python the same? No. Python runs the .py file. pip brings that file's library and does not run a program itself.", "Are pip and Node.js the same? No. Node runs JavaScript and does not use pip. Node's package comes with npm. pip is only for Python.", "Is requirements.txt the package itself? No. It is the list of names."],
        ["pip ve Python aynı mı? Hayır. Python .py dosyasını çalıştırır. pip o dosyanın kütüphanesini getirir ve kendi program çalıştırmaz.", "pip ve Node.js aynı mı? Hayır. Node JavaScript çalıştırır ve pip kullanmaz. Node’un paketi npm ile gelir. pip yalnız Python içindir.", "requirements.txt paketin kendisi mi? Hayır. O, adların listesidir."],
        ["هل pip وPython الشيء نفسه؟ لا. Python يشغّل ملف .py. pip يجلب مكتبة ذلك الملف ولا يشغّل برنامجاً بنفسه.", "هل pip وNode.js الشيء نفسه؟ لا. Node يشغّل JavaScript ولا يستخدم pip. حزمة Node تأتي بـ npm. pip لـ Python فقط.", "هل requirements.txt هو الحزمة نفسها؟ لا. هو قائمة الأسماء."],
        ["pip и Python — одно и то же? Нет. Python запускает файл .py. pip приносит библиотеку этого файла и сам программу не запускает.", "pip и Node.js — одно и то же? Нет. Node запускает JavaScript и не использует pip. Пакет Node приходит через npm. pip только для Python.", "requirements.txt — это сам пакет? Нет. Это список имён."],
      ),
    },
  ),
  topic(
    "sqlite",
    "SQLite",
    t("SQLite nədir?", "What is SQLite?", "SQLite nedir?", "ما هو SQLite؟", "Что такое SQLite?"),
    t(
      "SQLite məlumatı bir faylda saxlayır. Python da deyil, Node.js də deyil. Onlar bu faylı açıb sətir oxuya bilər, amma özləri baza deyil.",
      "SQLite keeps data in one file. It is not Python, and it is not Node.js. They can open this file and read rows, but they are not the database.",
      "SQLite veriyi bir dosyada tutar. Python da değildir, Node.js de değildir. Onlar bu dosyayı açıp satır okuyabilir, ama kendileri taban değildir.",
      "SQLite يحفظ البيانات في ملف واحد. ليس Python وليس Node.js. هما يقدران أن يفتحا هذا الملف ويقرآ الصفوف، لكنهما ليسا القاعدة.",
      "SQLite хранит данные в одном файле. Это не Python и не Node.js. Они могут открыть этот файл и прочитать строки, но сами они не база.",
    ),
    t("SQLite nədir, SQLite fayl, SQL, MySQL", "what is SQLite, SQLite file, SQL, MySQL", "SQLite nedir, SQLite dosya, SQL", "ما هو SQLite, ملف SQLite, SQL", "что такое SQLite, файл SQLite, SQL"),
    {
      what: t(
        "SQLite-ı D. Richard Hipp 2000-ci ildə yazıb. Mühərrik proqramın içinə qoyulur. Başqa bir proses gözləmir. Bütün cədvəllər adətən bir .sqlite və ya .db faylındadır. SQL dili burada da işlənir, amma mühərrik MySQL deyil. MySQL ayrı serverdir və çox adam eyni anda yaza bilər. SQLite bir yazanı rahat saxlayır, çox oxuyanı da buraxır. Python ilə fərqi budur: Python proqramı işlədir, SQLite sətir saxlayır. Python-un standart kitabxanasında sqlite3 var, faylı onunla açır. Node.js ilə fərqi də budur: Node JavaScript işlədir. SQLite faylını paketlə və ya yeni Node-un öz modulu ilə aça bilər. Köhnə Node-da həmin modul yoxdur.",
        "D. Richard Hipp wrote SQLite in 2000. The engine is placed inside the program. It does not wait for another process. All the tables usually sit in one .sqlite or .db file. The SQL language is used here too, but the engine is not MySQL. MySQL is a separate server, and many people can write at the same time. SQLite is comfortable with one writer, and it also allows many readers. The difference from Python is this: Python runs the program, and SQLite keeps the rows. Python's standard library has sqlite3, and it opens the file with that. The difference from Node.js is this too: Node runs JavaScript. It can open a SQLite file with a package, or with newer Node's own module. Old Node does not have that module.",
        "SQLite’ı D. Richard Hipp 2000’de yazdı. Motor programın içine konur. Başka bir süreç beklemez. Bütün tablolar genellikle bir .sqlite veya .db dosyasındadır. SQL dili burada da kullanılır, ama motor MySQL değildir. MySQL ayrı sunucudur ve çok kişi aynı anda yazabilir. SQLite bir yazanı rahat tutar, çok okuyanı da bırakır. Python ile farkı şudur: Python programı çalıştırır, SQLite satır tutar. Python’un standart kütüphanesinde sqlite3 vardır, dosyayı onunla açar. Node.js ile farkı da şudur: Node JavaScript çalıştırır. SQLite dosyasını bir paketle veya yeni Node’un kendi modülüyle açabilir. Eski Node’da o modül yoktur.",
        "كتب D. Richard Hipp SQLite سنة 2000. المحرك يوضع داخل البرنامج. لا ينتظر عملية أخرى. كل الجداول عادة في ملف .sqlite أو .db واحد. لغة SQL تُستخدم هنا أيضاً لكن المحرك ليس MySQL. MySQL خادم منفصل ويقدر كثيرون أن يكتبوا في الوقت نفسه. SQLite مرتاح مع كاتب واحد ويسمح بكثير من القراء أيضاً. الفرق عن Python هو هذا: Python يشغّل البرنامج وSQLite يحفظ الصفوف. في مكتبة Python القياسية sqlite3، وبها يُفتح الملف. الفرق عن Node.js هو هذا أيضاً: Node يشغّل JavaScript. يقدر أن يفتح ملف SQLite بحزمة أو بوحدة Node الجديد نفسه. Node القديم ليست فيه تلك الوحدة.",
        "SQLite написал D. Richard Hipp в 2000 году. Движок кладут внутрь программы. Он не ждёт другой процесс. Все таблицы обычно лежат в одном файле .sqlite или .db. Язык SQL используется и здесь, но движок — не MySQL. MySQL — отдельный сервер, и много людей могут писать одновременно. SQLite удобен с одним пишущим и пускает много читающих. Разница с Python такая: Python запускает программу, а SQLite хранит строки. В стандартной библиотеке Python есть sqlite3, файл открывают им. Разница с Node.js такая же: Node запускает JavaScript. Файл SQLite он может открыть пакетом или собственным модулем нового Node. В старом Node этого модуля нет.",
      ),
      uses: t(
        "SQLite bir istifadəçinin və ya bir cihazın məlumatı üçündür. Ayar, qeyd və kiçik kataloq onun yeridir.",
        "SQLite is for one user's data, or one device's data. A setting, a note, and a small catalog are its place.",
        "SQLite bir kullanıcının veya bir cihazın verisi içindir. Ayar, not ve küçük katalog onun yeridir.",
        "SQLite لبيانات مستخدم واحد أو جهاز واحد. الإعداد والملاحظة والفهرس الصغير مكانه.",
        "SQLite нужен для данных одного пользователя или одного устройства. Настройка, заметка и маленький каталог — его место.",
      ),
      useList: lines(
        ["Telefon tətbiqinin yerli bazası", "Brauzerin saxladığı qeyd", "Masaüstü proqramın ayarı", "Kiçik saytın bir fayllıq bazası"],
        ["A phone app's local database", "A note the browser keeps", "A desktop program's setting", "A small site's one-file database"],
        ["Telefon uygulamasının yerel tabanı", "Tarayıcının tuttuğu not", "Masaüstü programın ayarı", "Küçük sitenin tek dosyalık tabanı"],
        ["قاعدة تطبيق الهاتف المحلية", "ملاحظة يحفظها المتصفح", "إعداد برنامج سطح المكتب", "قاعدة موقع صغير في ملف واحد"],
        ["Местная база приложения телефона", "Заметка, которую хранит браузер", "Настройка настольной программы", "База маленького сайта в одном файле"],
      ),
      can: t(
        "SQLite ilə cədvəl yaradırsan, sətir əlavə edir və şərtə görə seçirsən. Ehtiyat nüsxə həmin faylın surətidir. Çox serverdən eyni fayla eyni anda yazmaq onun işi deyil. Böyük saytın sifarişi üçün ayrı server olan baza seçilir.",
        "With SQLite you create a table, add a row, and choose by a condition. A backup is a copy of that file. Writing to the same file from many servers at the same time is not its job. For a large site's order, a database with its own server is chosen.",
        "SQLite ile tablo yaratır, satır ekler ve koşula göre seçersin. Yedek o dosyanın kopyasıdır. Çok sunucudan aynı dosyaya aynı anda yazmak onun işi değildir. Büyük sitenin siparişi için kendi sunucusu olan taban seçilir.",
        "بـ SQLite تنشئ جدولاً وتضيف صفاً وتختار بشرط. النسخة الاحتياطية نسخة ذلك الملف. الكتابة إلى الملف نفسه من خوادم كثيرة في الوقت نفسه ليست عمله. لطلب موقع كبير تُختار قاعدة لها خادمها.",
        "В SQLite создают таблицу, добавляют строку и выбирают по условию. Резервная копия — копия этого файла. Писать в один файл с многих серверов одновременно — не его работа. Для заказа большого сайта выбирают базу со своим сервером.",
      ),
      hard: t(
        "Faylı açmaq asandır. Çətinlik eyni anda yazmaqdadır. İki proses eyni sətiri dəyişəndə biri gözləyir. Gözləmə uzanırsa əmr dayanır. Faylı başqa qovluğa köçürmək proqramın yolunu da dəyişir. SQL mətninə istifadəçi yazısını yapışdırmaq burada da inyeksiya açır.",
        "Opening the file is easy. The difficulty is writing at the same time. When two processes change the same row, one waits. If the wait grows long, the command stops. Moving the file to another folder also changes the program's path. Pasting a user's text into the SQL opens injection here too.",
        "Dosyayı açmak kolaydır. Zorluk aynı anda yazmaktadır. İki süreç aynı satırı değiştirince biri bekler. Bekleme uzarsa komut durur. Dosyayı başka klasöre taşımak programın yolunu da değiştirir. SQL metnine kullanıcı yazısını yapıştırmak burada da enjeksiyon açar.",
        "فتح الملف سهل. الصعوبة الكتابة في الوقت نفسه. حين تغيّر عمليتان الصف نفسه تنتظر إحداهما. إذا طال الانتظار يتوقف الأمر. نقل الملف إلى مجلد آخر يغيّر مسار البرنامج أيضاً. لصق نص المستخدم في نص SQL يفتح الحقن هنا أيضاً.",
        "Открыть файл легко. Трудность в одновременной записи. Когда два процесса меняют одну строку, один ждёт. Если ожидание затягивается, команда останавливается. Перенос файла в другую папку меняет и путь программы. Вставка текста пользователя в текст SQL и здесь открывает инъекцию.",
      ),
      balance: t(
        "Üstünlük: quraşdırılacaq server yoxdur, surət bir fayldır, SQL tanışdır. Məhdudiyyət: çox yazan və böyük yük üçün daralır. SQLite MySQL-in kiçik adı deyil. O, faylın içində işləyən mühərrikdir.",
        "Advantage: there is no server to install, a copy is one file, and SQL is familiar. Limit: it gets tight for many writers and a large load. SQLite is not the small name of MySQL. It is an engine that works inside a file.",
        "Avantaj: kurulacak sunucu yoktur, kopya bir dosyadır, SQL tanıdıktır. Sınır: çok yazan ve büyük yük için daralır. SQLite, MySQL’in küçük adı değildir. Dosyanın içinde çalışan motordur.",
        "الميزة: لا خادم يُثبّت والنسخة ملف واحد وSQL مألوفة. الحد: يضيق مع كثير من الكتّاب والحمل الكبير. SQLite ليس الاسم الصغير لـ MySQL. هو محرك يعمل داخل ملف.",
        "Плюс: сервер ставить не нужно, копия — один файл, SQL знакомый. Ограничение: при многих пишущих и большой нагрузке ему тесно. SQLite — не маленькое имя MySQL. Это движок, который работает внутри файла.",
      ),
      ideas: t(
        "Fayl bazanın özüdür. Cədvəl sütunların adıdır. Sətir bir qeyddir.",
        "The file is the database itself. A table is the names of the columns. A row is one record.",
        "Dosya tabanın kendisidir. Tablo sütunların adıdır. Satır bir kayıttır.",
        "الملف هو القاعدة نفسها. الجدول أسماء الأعمدة. الصف سجل واحد.",
        "Файл — это сама база. Таблица — имена столбцов. Строка — одна запись.",
      ),
      ideaList: lines(
        ["Ayrı server prosesi yoxdur", "SQL sorğusu burada da işlənir", "Bir yazan rahatdır", "Ehtiyat nüsxə faylın surətidir"],
        ["There is no separate server process", "An SQL query is used here too", "One writer is comfortable", "A backup is a copy of the file"],
        ["Ayrı sunucu süreci yoktur", "SQL sorgusu burada da kullanılır", "Bir yazan rahattır", "Yedek dosyanın kopyasıdır"],
        ["لا عملية خادم منفصلة", "طلب SQL يُستخدم هنا أيضاً", "كاتب واحد مرتاح", "النسخة الاحتياطية نسخة الملف"],
        ["Отдельного процесса сервера нет", "Запрос SQL используется и здесь", "Одному пишущему удобно", "Резервная копия — копия файла"],
      ),
      sample: t(
        "Bu sorğu bir cədvəl açır. Fayl yoxdursa mühərrik onu yarada bilər. Serverə bağlanmaq lazım deyil.",
        "This query opens one table. If the file is missing, the engine can create it. There is no need to connect to a server.",
        "Bu sorgu bir tablo açar. Dosya yoksa motor onu yaratabilir. Sunucuya bağlanmak gerekmez.",
        "هذا الطلب يفتح جدولاً. إذا غاب الملف يقدر المحرك أن ينشئه. لا حاجة للاتصال بخادم.",
        "Этот запрос открывает одну таблицу. Если файла нет, движок может его создать. Подключаться к серверу не нужно.",
      ),
      code: `CREATE TABLE note (
  id INTEGER PRIMARY KEY,
  text TEXT
);`,
      faq: lines(
        ["SQLite və Python eynidir? Xeyr. Python proqramı işlədir. SQLite sətir saxlayır. Python faylı standart sqlite3 ilə açır.", "SQLite və Node.js eynidir? Xeyr. Node JavaScript işlədir. SQLite faylını paketlə və ya yeni Node-un öz modulu ilə aça bilər. Köhnə Node-da həmin modul yoxdur.", "SQLite və MySQL eynidir? Xeyr. İkisi də SQL işlədir. SQLite bir fayldır, MySQL ayrı serverdir."],
        ["Are SQLite and Python the same? No. Python runs the program. SQLite keeps the rows. Python opens the file with the standard sqlite3.", "Are SQLite and Node.js the same? No. Node runs JavaScript. It can open a SQLite file with a package, or with newer Node's own module. Old Node does not have that module.", "Are SQLite and MySQL the same? No. Both use SQL. SQLite is one file, MySQL is a separate server."],
        ["SQLite ve Python aynı mı? Hayır. Python programı çalıştırır. SQLite satır tutar. Python dosyayı standart sqlite3 ile açar.", "SQLite ve Node.js aynı mı? Hayır. Node JavaScript çalıştırır. SQLite dosyasını bir paketle veya yeni Node’un kendi modülüyle açabilir. Eski Node’da o modül yoktur.", "SQLite ve MySQL aynı mı? Hayır. İkisi de SQL kullanır. SQLite bir dosyadır, MySQL ayrı sunucudur."],
        ["هل SQLite وPython الشيء نفسه؟ لا. Python يشغّل البرنامج. SQLite يحفظ الصفوف. Python يفتح الملف بـ sqlite3 القياسي.", "هل SQLite وNode.js الشيء نفسه؟ لا. Node يشغّل JavaScript. يقدر أن يفتح ملف SQLite بحزمة أو بوحدة Node الجديد نفسه. Node القديم ليست فيه تلك الوحدة.", "هل SQLite وMySQL الشيء نفسه؟ لا. كلاهما يستخدم SQL. SQLite ملف واحد وMySQL خادم منفصل."],
        ["SQLite и Python — одно и то же? Нет. Python запускает программу. SQLite хранит строки. Python открывает файл стандартным sqlite3.", "SQLite и Node.js — одно и то же? Нет. Node запускает JavaScript. Файл SQLite он может открыть пакетом или собственным модулем нового Node. В старом Node этого модуля нет.", "SQLite и MySQL — одно и то же? Нет. Оба используют SQL. SQLite — один файл, MySQL — отдельный сервер."],
      ),
    },
  ),
  topic(
    "curl",
    "curl",
    t("curl nədir?", "What is curl?", "curl nedir?", "ما هو curl؟", "Что такое curl?"),
    t(
      "curl ünvana sorğu göndərən əmrdir. Brauzer deyil. Səhifəni pəncərədə çəkmir, cavabın mətnini göstərir.",
      "curl is a command that sends a request to an address. It is not a browser. It does not draw the page in a window. It shows the text of the response.",
      "curl, adrese sorgu gönderen komuttur. Tarayıcı değildir. Sayfayı pencerede çizmez, cevabın metnini gösterir.",
      "curl أمر يرسل طلباً إلى عنوان. ليس متصفحاً. لا يرسم الصفحة في نافذة، يُظهر نص الجواب.",
      "curl — команда, которая отправляет запрос на адрес. Это не браузер. Страницу в окне она не рисует, а показывает текст ответа.",
    ),
    t("curl nədir, curl əmri, HTTP sorğu, API", "what is curl, curl command, HTTP request, API", "curl nedir, curl komutu, HTTP isteği", "ما هو curl, أمر curl, طلب HTTP", "что такое curl, команда curl, запрос HTTP"),
    {
      what: t(
        "curl Daniel Stenberg-in cURL layihəsinin əmridir. İlk açıq buraxılış 1997-ci ilə yaxındır. Adın içinə URL girir. Əmr o ünvana bağlanır və gələn baytları çıxarır. Ən çox HTTP və HTTPS üçündür, amma özü HTTP deyil. HTTP qaydanın adıdır. curl həmin qayda ilə danışan alətdir. Brauzer HTML-i səhifəyə çevirir. curl mətni olduğu kimi göstərir.",
        "curl is the command of Daniel Stenberg's cURL project. The first open release is near 1997. A URL goes inside the name. The command connects to that address and prints the bytes that come back. It is mostly for HTTP and HTTPS, but it is not HTTP itself. HTTP is the name of the rule. curl is the tool that talks by that rule. A browser turns HTML into a page. curl shows the text as it is.",
        "curl, Daniel Stenberg’in cURL projesinin komutudur. İlk açık yayın 1997’ye yakındır. Adın içine URL girer. Komut o adrese bağlanır ve gelen baytları çıkarır. En çok HTTP ve HTTPS içindir, ama kendisi HTTP değildir. HTTP kuralın adıdır. curl o kuralla konuşan araçtır. Tarayıcı HTML’i sayfaya çevirir. curl metni olduğu gibi gösterir.",
        "curl أمر مشروع cURL لـ Daniel Stenberg. أول إصدار مفتوح قريب من 1997. يدخل URL في الاسم. الأمر يتصل بذلك العنوان ويُخرج البايتات التي تعود. هو في الأغلب لـ HTTP وHTTPS لكنه ليس HTTP نفسه. HTTP اسم القاعدة. curl الأداة التي تتكلم بتلك القاعدة. المتصفح يحوّل HTML إلى صفحة. curl يُظهر النص كما هو.",
        "curl — команда проекта cURL Дэниела Стенберга. Первый открытый выпуск около 1997 года. В имя входит URL. Команда соединяется с этим адресом и печатает байты, которые приходят. Чаще всего это HTTP и HTTPS, но сам curl — не HTTP. HTTP — имя правила. curl — инструмент, который говорит по этому правилу. Браузер превращает HTML в страницу. curl показывает текст как есть.",
      ),
      uses: t(
        "curl API-ni yoxlamaq, başlığı görmək və faylı əmrlə endirmək üçündür.",
        "curl is for checking an API, seeing a header, and downloading a file with a command.",
        "curl API’yi denemek, başlığı görmek ve dosyayı komutla indirmek içindir.",
        "curl لفحص واجهة ورؤية الترويسة وتنزيل ملف بأمر.",
        "curl нужен, чтобы проверить API, увидеть заголовок и скачать файл командой.",
      ),
      useList: lines(
        ["Bir ünvanın cavabını oxumaq", "Yalnız başlıqları görmək", "JSON göndərib cavabı almaq", "Faylı qovluğa endirmək"],
        ["Reading one address's response", "Seeing only the headers", "Sending JSON and receiving the answer", "Downloading a file into a folder"],
        ["Bir adresin cevabını okumak", "Yalnız başlıkları görmek", "JSON gönderip cevabı almak", "Dosyayı klasöre indirmek"],
        ["قراءة جواب عنوان واحد", "رؤية الترويسات فقط", "إرسال JSON وأخذ الجواب", "تنزيل ملف إلى مجلد"],
        ["Прочитать ответ одного адреса", "Увидеть только заголовки", "Отправить JSON и получить ответ", "Скачать файл в папку"],
      ),
      can: t(
        "curl ilə GET və POST göndərirsən. Statusu və gövdəni görürsən. O, düymə çəkmir və JavaScript işlətmir. Səhifə yalnız skriptlə dolursa curl boş və ya yarım mətn göstərə bilər. Açar və parol əmrin içində qalırsa tarixçədə qala bilər.",
        "With curl you send GET and POST. You see the status and the body. It does not draw a button and it does not run JavaScript. If a page fills only with a script, curl can show empty or half text. If a token or a password stays inside the command, it can remain in the history.",
        "curl ile GET ve POST gönderirsin. Durumu ve gövdeyi görürsün. Düğme çizmez ve JavaScript çalıştırmaz. Sayfa yalnız betikle doluyorsa curl boş veya yarım metin gösterebilir. Anahtar veya parola komutun içinde kalırsa geçmişte kalabilir.",
        "بـ curl ترسل GET وPOST. ترى الحالة والجسم. لا يرسم زراً ولا يشغّل JavaScript. إذا امتلأت الصفحة بسكربت فقط فقد يُظهر curl نصاً فارغاً أو نصف نص. إذا بقي مفتاح أو كلمة مرور داخل الأمر فقد يبقى في السجل.",
        "Через curl отправляют GET и POST. Видно статус и тело. Кнопку он не рисует и JavaScript не выполняет. Если страница наполняется только скриптом, curl может показать пустой или половинный текст. Если ключ или пароль остаётся внутри команды, он может остаться в истории.",
      ),
      hard: t(
        "Bir ünvanı açmaq asandır. Çətinlik başlıq və üsuldadır. POST-u GET kimi göndərmək serverdə başqa iş görür. Sertifikat xətası bağlantını dayandırır. Həmin yoxlamanı söndürmək olmaz, çünki adı başqa sayt ola bilər. Cavab böyükdürsə terminal dolur.",
        "Opening one address is easy. The difficulty is the header and the method. Sending a POST as a GET does another job on the server. A certificate error stops the connection. Do not turn that check off, because the name may be another site. If the response is large, the terminal fills up.",
        "Bir adresi açmak kolaydır. Zorluk başlık ve yöntemdedir. POST’u GET gibi göndermek sunucuda başka iş görür. Sertifika hatası bağlantıyı durdurur. O denetimi kapatmamak gerekir, çünkü ad başka site olabilir. Cevap büyükse terminal dolar.",
        "فتح عنوان واحد سهل. الصعوبة في الترويسة والطريقة. إرسال POST كأنه GET يعمل عملاً آخر على الخادم. خطأ الشهادة يوقف الاتصال. لا توقف ذلك الفحص، فقد يكون الاسم موقعاً آخر. إذا كان الجواب كبيراً يمتلئ الطرفية.",
        "Открыть один адрес легко. Трудность в заголовке и методе. Отправить POST как GET делает на сервере другую работу. Ошибка сертификата останавливает соединение. Эту проверку не выключают, потому что имя может быть другим сайтом. Если ответ большой, терминал заполняется.",
      ),
      balance: t(
        "Üstünlük: brauzersiz cavab görünür, əmr skriptə qoyulur, başlıq ayrıca oxunur. Məhdudiyyət: səhifəni insan kimi gəzdirmir. curl HTTP-nin özü deyil və brauzer deyil.",
        "Advantage: the response is visible without a browser, the command goes into a script, and a header is read separately. Limit: it does not walk the page like a person. curl is not HTTP itself, and it is not a browser.",
        "Avantaj: cevap tarayıcısız görünür, komut betiğe konur, başlık ayrıca okunur. Sınır: sayfayı insan gibi gezdirmez. curl, HTTP’nin kendisi değildir ve tarayıcı değildir.",
        "الميزة: الجواب يظهر بلا متصفح والأمر يوضع في سكربت والترويسة تُقرأ على حدة. الحد: لا يتجول في الصفحة كإنسان. curl ليس HTTP نفسه وليس متصفحاً.",
        "Плюс: ответ виден без браузера, команда кладётся в скрипт, заголовок читается отдельно. Ограничение: по странице как человек он не ходит. curl — не сам HTTP и не браузер.",
      ),
      ideas: t(
        "Ünvan hara getdiyini deyir. Üsul nə istədiyini deyir. Cavab status və gövdədən ibarətdir.",
        "The address says where it goes. The method says what you want. The response is a status and a body.",
        "Adres nereye gittiğini söyler. Yöntem ne istediğini söyler. Cevap durum ve gövdeden oluşur.",
        "العنوان يقول أين يذهب. الطريقة تقول ماذا تريد. الجواب حالة وجسم.",
        "Адрес говорит, куда идёт. Метод говорит, чего ты хочешь. Ответ состоит из статуса и тела.",
      ),
      ideaList: lines(
        ["Ünvansız curl heç yerə getmir", "-I yalnız başlığı istəyir", "-d gövdə göndərir", "Status 200 alındı deməkdir"],
        ["curl without an address goes nowhere", "-I asks for the header only", "-d sends a body", "Status 200 means it was received"],
        ["Adressiz curl hiçbir yere gitmez", "-I yalnız başlığı ister", "-d gövde gönderir", "Durum 200 alındı demektir"],
        ["curl بلا عنوان لا يذهب إلى مكان", "-I يطلب الترويسة فقط", "-d يرسل جسماً", "الحالة 200 تعني أنه تم الاستلام"],
        ["curl без адреса никуда не идёт", "-I просит только заголовок", "-d отправляет тело", "Статус 200 значит, что получено"],
      ),
      sample: t(
        "Bu əmr bir ünvanın cavab mətnini çıxarır. Səhifəni pəncərədə açmır.",
        "This command prints the response text of one address. It does not open the page in a window.",
        "Bu komut bir adresin cevap metnini çıkarır. Sayfayı pencerede açmaz.",
        "هذا الأمر يُخرج نص جواب عنوان واحد. لا يفتح الصفحة في نافذة.",
        "Эта команда печатает текст ответа одного адреса. Страницу в окне она не открывает.",
      ),
      code: `curl https://nibrascode.com`,
      faq: lines(
        ["curl və brauzer eynidir? Xeyr. Brauzer səhifəni çəkir. curl cavabın mətnini göstərir.", "curl və HTTP eynidir? Xeyr. HTTP qaydanın adıdır. curl həmin qayda ilə sorğu göndərən əmrdir.", "JavaScript işləyir? Xeyr. curl skripti işlətmir. Yalnız gələn mətni göstərir."],
        ["Are curl and a browser the same? No. A browser draws the page. curl shows the text of the response.", "Are curl and HTTP the same? No. HTTP is the name of the rule. curl is the command that sends a request by that rule.", "Does JavaScript run? No. curl does not run a script. It only shows the text that arrives."],
        ["curl ve tarayıcı aynı mı? Hayır. Tarayıcı sayfayı çizer. curl cevabın metnini gösterir.", "curl ve HTTP aynı mı? Hayır. HTTP kuralın adıdır. curl o kuralla sorgu gönderen komuttur.", "JavaScript çalışır mı? Hayır. curl betik çalıştırmaz. Yalnız gelen metni gösterir."],
        ["هل curl والمتصفح الشيء نفسه؟ لا. المتصفح يرسم الصفحة. curl يُظهر نص الجواب.", "هل curl وHTTP الشيء نفسه؟ لا. HTTP اسم القاعدة. curl الأمر الذي يرسل طلباً بتلك القاعدة.", "هل يعمل JavaScript؟ لا. curl لا يشغّل سكربتاً. يُظهر فقط النص الذي يصل."],
        ["curl и браузер — одно и то же? Нет. Браузер рисует страницу. curl показывает текст ответа.", "curl и HTTP — одно и то же? Нет. HTTP — имя правила. curl — команда, которая шлёт запрос по этому правилу.", "JavaScript выполняется? Нет. curl скрипт не запускает. Он только показывает текст, который пришёл."],
      ),
    },
  ),
];
