import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_ADD: readonly StackPage[] = [
  topic(
    "npm",
    "npm",
    t("npm nədir?", "What is npm?", "npm nedir?", "ما هو npm؟", "Что такое npm?"),
    t(
      "npm JavaScript paketini endirən və quran alətdir. Dil deyil. Node.js proqramı işlədir, npm isə həmin proqramın ehtiyac duyduğu paketləri gətirir.",
      "npm is the tool that downloads and installs a JavaScript package. It is not a language. Node.js runs the program, and npm brings the packages that program needs.",
      "npm, JavaScript paketini indiren ve kuran araçtır. Dil değildir. Node.js programı çalıştırır, npm ise o programın ihtiyaç duyduğu paketleri getirir.",
      "npm الأداة التي تنزّل حزمة JavaScript وتثبّتها. ليست لغة. Node.js يشغّل البرنامج وnpm يجلب الحزم التي يحتاجها.",
      "npm — инструмент, который скачивает и ставит пакет JavaScript. Это не язык. Node.js запускает программу, а npm приносит пакеты, которые ей нужны.",
    ),
    t("npm nədir, npm paket, package.json, Node.js", "what is npm, npm package, package.json, Node.js", "npm nedir, npm paket, package.json", "ما هو npm, حزمة npm, package.json", "что такое npm, пакет npm, package.json"),
    {
      what: t(
        "npm Node Package Manager deməkdir. Isaac Schlueter onu 2010-cu ildə Node.js ilə birlikdə açıb. Paket başqasının yazdığı hazır koddur. package.json həmin layihənin adını və paket siyahısını saxlayır. npm install o siyahını oxuyur və paketləri node_modules qovluğuna yığır. package-lock.json isə dəqiq versiyanı bağlayır ki, sabah başqa maşında eyni kod gəlsin. Yarn və pnpm oxşar iş görür, amma npm-in özü deyil.",
        "npm means Node Package Manager. Isaac Schlueter opened it in 2010 alongside Node.js. A package is ready code that someone else wrote. package.json keeps the project's name and the package list. npm install reads that list and puts the packages in the node_modules folder. package-lock.json pins the exact version, so the same code arrives on another machine tomorrow. Yarn and pnpm do a similar job, but they are not npm itself.",
        "npm, Node Package Manager demektir. Isaac Schlueter onu 2010’da Node.js ile birlikte açtı. Paket başkasının yazdığı hazır koddur. package.json projenin adını ve paket listesini tutar. npm install o listeyi okur ve paketleri node_modules klasörüne koyar. package-lock.json kesin sürümü bağlar ki yarın başka makinede aynı kod gelsin. Yarn ve pnpm benzer iş görür, ama npm’in kendisi değildir.",
        "npm تعني Node Package Manager. فتحها Isaac Schlueter سنة 2010 مع Node.js. الحزمة كود جاهز كتبه غيرك. package.json يحفظ اسم المشروع وقائمة الحزم. npm install يقرأ تلك القائمة ويضع الحزم في مجلد node_modules. package-lock.json يثبت النسخة الدقيقة كي يصل الكود نفسه إلى جهاز آخر غداً. Yarn وpnpm يقومان بعمل قريب لكنهما ليسا npm نفسه.",
        "npm значит Node Package Manager. Isaac Schlueter открыл его в 2010 году вместе с Node.js. Пакет — готовый код, который написал кто-то другой. package.json хранит имя проекта и список пакетов. npm install читает этот список и кладёт пакеты в папку node_modules. package-lock.json закрепляет точную версию, чтобы завтра на другой машине пришёл тот же код. Yarn и pnpm делают похожую работу, но это не сам npm.",
      ),
      uses: t(
        "npm kitabxananı layihəyə əlavə etmək, skripti bir əmrlə işə salmaq və paketi başqasına vermək üçündür.",
        "npm is for adding a library to a project, starting a script with one command, and giving a package to someone else.",
        "npm kütüphaneyi projeye eklemek, betiği tek komutla çalıştırmak ve paketi başkasına vermek içindir.",
        "npm لإضافة مكتبة إلى المشروع وتشغيل سكربت بأمر واحد وإعطاء حزمة لغيرك.",
        "npm нужен, чтобы добавить библиотеку в проект, запустить скрипт одной командой и отдать пакет другому.",
      ),
      useList: lines(
        ["React və başqa kitabxananı qurmaq", "Testi npm test ilə açmaq", "Layihəni başqa kompüterdə eyni paketlərlə qurmaq", "Öz paketini reyestrə göndərmək"],
        ["Installing React and another library", "Opening the test with npm test", "Setting up the project on another computer with the same packages", "Sending your own package to the registry"],
        ["React ve başka kütüphaneyi kurmak", "Testi npm test ile açmak", "Projeyi başka bilgisayarda aynı paketlerle kurmak", "Kendi paketini kayda göndermek"],
        ["تثبيت React ومكتبة أخرى", "فتح الاختبار بـ npm test", "إعداد المشروع على حاسوب آخر بالحزم نفسها", "إرسال حزمتك إلى السجل"],
        ["Поставить React и другую библиотеку", "Открыть тест через npm test", "Собрать проект на другом компьютере теми же пакетами", "Отправить свой пакет в реестр"],
      ),
      can: t(
        "npm ilə paket əlavə edir, köhnəsini silir və package.json-dakı skripti işlədirsən. O, səhifəni özü çəkmir və serveri qurmur. Paketin içindəki kod sənin layihəndə işləyir. Tanımadığın paketi qurmaq onun əmrini də işə sala bilər.",
        "With npm you add a package, remove an old one, and run the script in package.json. It does not draw the page itself and it does not build the server. The code inside the package runs in your project. Installing a package you do not know can also run its command.",
        "npm ile paket eklersin, eskisini silersin ve package.json içindeki betiği çalıştırırsın. Sayfayı kendi çizmez ve sunucuyu kurmaz. Paketin içindeki kod senin projende çalışır. Tanımadığın paketi kurmak onun komutunu da çalıştırabilir.",
        "بـ npm تضيف حزمة وتحذف القديمة وتشغّل السكربت في package.json. هو لا يرسم الصفحة بنفسه ولا يبني الخادم. الكود داخل الحزمة يعمل في مشروعك. تثبيت حزمة لا تعرفها قد يشغّل أمرها أيضاً.",
        "Через npm добавляют пакет, удаляют старый и запускают скрипт из package.json. Сам он страницу не рисует и сервер не собирает. Код внутри пакета выполняется в твоём проекте. Установка незнакомого пакета может запустить и его команду.",
      ),
      hard: t(
        "Bir paket qurmaq asandır. Çətinlik versiya və icazədədir. Paket başqa paketi də gətirir. Onlardan biri köhnəlibsə xəbərdarlıq çıxır, amma layihə hələ işləyə bilər. package-lock faylını atmaq sabah başqa versiya gətirə bilər. Reyestrə açar yazmaq və həmin açarı repoya qoymaq olmaz.",
        "Installing one package is easy. The difficulty is the version and the permission. A package also brings another package. If one of them is old, a warning appears, but the project may still run. Throwing away the package-lock file can bring another version tomorrow. Do not write a registry token into the repo.",
        "Bir paket kurmak kolaydır. Zorluk sürüm ve izindedir. Paket başka paketi de getirir. Biri eskidiyse uyarı çıkar, ama proje hâlâ çalışabilir. package-lock dosyasını atmak yarın başka sürüm getirebilir. Kayıt anahtarını depoya koymamak gerekir.",
        "تثبيت حزمة واحدة سهل. الصعوبة في النسخة والإذن. الحزمة تجلب حزمة أخرى أيضاً. إذا قدم بعضها يظهر تنبيه لكن المشروع قد يبقى يعمل. رمي ملف package-lock قد يجلب نسخة أخرى غداً. لا تضع مفتاح السجل في المستودع.",
        "Поставить один пакет легко. Трудность в версии и в праве. Пакет приносит и другой пакет. Если один устарел, выходит предупреждение, но проект ещё может работать. Если выбросить файл package-lock, завтра может прийти другая версия. Ключ реестра в репозиторий не кладут.",
      ),
      balance: t(
        "Üstünlük: kitabxana təkrar yazılmır, siyahı bir faylda durur, eyni quraşdırma başqa maşında təkrarlanır. Məhdudiyyət: node_modules böyüyür. Hər kiçik iş üçün paket lazım deyil. npm Node.js-in özü deyil.",
        "Advantage: a library is not rewritten, the list stays in one file, and the same install repeats on another machine. Limit: node_modules grows. Not every small job needs a package. npm is not Node.js itself.",
        "Avantaj: kütüphane yeniden yazılmaz, liste bir dosyada durur, aynı kurulum başka makinede tekrarlanır. Sınır: node_modules büyür. Her küçük iş için paket gerekmez. npm, Node.js’in kendisi değildir.",
        "الميزة: لا تُعاد كتابة المكتبة والقائمة تبقى في ملف واحد والتثبيت نفسه يتكرر على جهاز آخر. الحد: node_modules يكبر. ليس كل عمل صغير يحتاج حزمة. npm ليس Node.js نفسه.",
        "Плюс: библиотеку не переписывают, список лежит в одном файле, та же установка повторяется на другой машине. Ограничение: node_modules растёт. Не каждой мелкой работе нужен пакет. npm — это не сам Node.js.",
      ),
      ideas: t(
        "Paketin adı və versiyası var. package.json siyahıdır. node_modules endirilən faylların yeridir.",
        "A package has a name and a version. package.json is the list. node_modules is the place of the downloaded files.",
        "Paketin adı ve sürümü vardır. package.json listedir. node_modules indirilen dosyaların yeridir.",
        "للحزمة اسم ونسخة. package.json القائمة. node_modules مكان الملفات المنزّلة.",
        "У пакета есть имя и версия. package.json — список. node_modules — место скачанных файлов.",
      ),
      ideaList: lines(
        ["dependencies layihənin işləməsi üçündür", "devDependencies yalnız hazırlama üçündür", "scripts əmri qısa ada bağlayır", "lock faylı versiyanı saxlayır"],
        ["dependencies are for the project to run", "devDependencies are only for preparing it", "scripts tie a command to a short name", "The lock file keeps the version"],
        ["dependencies projenin çalışması içindir", "devDependencies yalnız hazırlamak içindir", "scripts komutu kısa ada bağlar", "Kilit dosyası sürümü tutar"],
        ["dependencies كي يعمل المشروع", "devDependencies للتجهيز فقط", "scripts تربط الأمر باسم قصير", "ملف القفل يحفظ النسخة"],
        ["dependencies нужны, чтобы проект работал", "devDependencies только для подготовки", "scripts связывают команду с коротким именем", "Файл lock хранит версию"],
      ),
      sample: t(
        "Bu sətir React paketini layihənin siyahısına əlavə edir və faylları endirir. React-i özü yazmır.",
        "This line adds the React package to the project's list and downloads the files. It does not write React itself.",
        "Bu satır React paketini projenin listesine ekler ve dosyaları indirir. React’i kendi yazmaz.",
        "هذا السطر يضيف حزمة React إلى قائمة المشروع وينزّل الملفات. لا يكتب React نفسه.",
        "Эта строка добавляет пакет React в список проекта и скачивает файлы. Сам React она не пишет.",
      ),
      code: `npm install react`,
      faq: lines(
        ["npm və Node.js eynidir? Xeyr. Node.js proqramı işlədir. npm paket gətirir.", "package.json paketin özüdür? Xeyr. O, siyahıdır. Paketin faylı node_modules içindədir.", "Hər paket təhlükəsizdir? Xeyr. Tanımadığın paket öz əmrini işə sala bilər."],
        ["Are npm and Node.js the same? No. Node.js runs the program. npm brings the package.", "Is package.json the package itself? No. It is the list. The package file is inside node_modules.", "Is every package safe? No. A package you do not know can run its own command."],
        ["npm ve Node.js aynı mı? Hayır. Node.js programı çalıştırır. npm paketi getirir.", "package.json paketin kendisi mi? Hayır. O, listedir. Paketin dosyası node_modules içindedir.", "Her paket güvenli mi? Hayır. Tanımadığın paket kendi komutunu çalıştırabilir."],
        ["هل npm وNode.js الشيء نفسه؟ لا. Node.js يشغّل البرنامج. npm يجلب الحزمة.", "هل package.json هو الحزمة نفسها؟ لا. هو القائمة. ملف الحزمة داخل node_modules.", "هل كل حزمة آمنة؟ لا. حزمة لا تعرفها قد تشغّل أمرها."],
        ["npm и Node.js — одно и то же? Нет. Node.js запускает программу. npm приносит пакет.", "package.json — это сам пакет? Нет. Это список. Файл пакета лежит в node_modules.", "Каждый пакет безопасен? Нет. Незнакомый пакет может запустить свою команду."],
      ),
    },
  ),
  topic(
    "redis",
    "Redis",
    t("Redis nədir?", "What is Redis?", "Redis nedir?", "ما هو Redis؟", "Что такое Redis?"),
    t(
      "Redis açarı və qiyməti yaddaşda saxlayan serverdir. Cədvəlli verilənlər bazası deyil. Cavabı tez qaytarmaq üçündür.",
      "Redis is a server that keeps a key and a value in memory. It is not a table database. It is for returning an answer quickly.",
      "Redis, anahtar ve değeri bellekte tutan sunucudur. Tablolu veritabanı değildir. Cevabı çabuk döndürmek içindir.",
      "Redis خادم يحفظ المفتاح والقيمة في الذاكرة. ليس قاعدة جداول. هو لإرجاع الجواب بسرعة.",
      "Redis — сервер, который хранит ключ и значение в памяти. Это не база с таблицами. Он нужен, чтобы быстро вернуть ответ.",
    ),
    t("Redis nədir, Redis keş, açar qiymət, yaddaş", "what is Redis, Redis cache, key value, memory", "Redis nedir, Redis önbellek, anahtar değer", "ما هو Redis, ذاكرة Redis, مفتاح", "что такое Redis, кэш Redis, ключ"),
    {
      what: t(
        "Redis adını Remote Dictionary Server sözlərindən götürür. Salvatore Sanfilippo onu 2009-cu ildə açıb. Əsas yer operativ yaddaşdır, disk deyil. Buna görə oxumaq tezdir. Maşın sönəndə yalnız yaddaşda qalan məlumat gedə bilər. Diskə yazma ayrıca açılır: ani şəkil və ya əməliyyat jurnalı. MySQL sətir və sütun saxlayır. Redis açar saxlayır. Biri digərinin adı deyil.",
        "Redis takes its name from Remote Dictionary Server. Salvatore Sanfilippo opened it in 2009. The main place is working memory, not the disk. That is why a read is fast. When the machine turns off, data that stayed only in memory can go. Writing to disk is turned on separately: a snapshot, or a journal of operations. MySQL keeps rows and columns. Redis keeps keys. One is not the other's name.",
        "Redis adını Remote Dictionary Server sözlerinden alır. Salvatore Sanfilippo onu 2009’da açtı. Ana yer disk değil, çalışan bellektir. Bu yüzden okuma tezdir. Makine kapanınca yalnız bellekte kalan veri gidebilir. Diske yazma ayrıca açılır: anlık görüntü veya işlem günlüğü. MySQL satır ve sütun tutar. Redis anahtar tutar. Biri ötekinin adı değildir.",
        "يأخذ Redis اسمه من Remote Dictionary Server. فتحه Salvatore Sanfilippo سنة 2009. المكان الأساسي الذاكرة العاملة لا القرص. لذلك القراءة سريعة. حين ينطفئ الجهاز قد تذهب البيانات التي بقيت في الذاكرة فقط. الكتابة إلى القرص تُفتح على حدة: لقطة أو سجل عمليات. MySQL يحفظ صفوفاً وأعمدة. Redis يحفظ مفاتيح. أحدهما ليس اسم الآخر.",
        "Имя Redis взято из Remote Dictionary Server. Salvatore Sanfilippo открыл его в 2009 году. Основное место — оперативная память, не диск. Поэтому чтение быстрое. Когда машина выключается, данные, оставшиеся только в памяти, могут уйти. Запись на диск включается отдельно: снимок или журнал операций. MySQL хранит строки и столбцы. Redis хранит ключи. Одно — не имя другого.",
      ),
      uses: t(
        "Redis tez-tez sorulan cavabı, sessiya nömrəsini və qısa müddətlik sayğacı saxlamaq üçündür.",
        "Redis is for an answer that is asked often, a session number, and a counter that lasts a short time.",
        "Redis sık sorulan cevabı, oturum numarasını ve kısa süreli sayacı tutmak içindir.",
        "Redis للجواب الذي يُسأل كثيراً ورقم الجلسة والعداد القصير المدة.",
        "Redis нужен для ответа, который спрашивают часто, номера сессии и счётчика на короткое время.",
      ),
      useList: lines(
        ["Eyni səhifənin hazır cavabını saxlamaq", "Giriş sessiyasını nömrə ilə bağlamaq", "Bir dəqiqəlik limiti saymaq", "Növbəyə qısa iş əlavə etmək"],
        ["Keeping a ready answer for the same page", "Tying a login session to a number", "Counting a one-minute limit", "Adding a short job to a queue"],
        ["Aynı sayfanın hazır cevabını tutmak", "Giriş oturumunu numaraya bağlamak", "Bir dakikalık sınırı saymak", "Kuyruğa kısa iş eklemek"],
        ["حفظ جواب جاهز للصفحة نفسها", "ربط جلسة الدخول برقم", "عدّ حد الدقيقة الواحدة", "إضافة عمل قصير إلى الطابور"],
        ["Хранить готовый ответ одной страницы", "Связать сессию входа с номером", "Считать лимит на одну минуту", "Добавить короткую работу в очередь"],
      ),
      can: t(
        "Redis ilə açara qiymət yazır, onu oxuyur və müddət qoyursan. Müddət bitəndə açar silinir. O, sifarişin əsas yerinə uyğun deyil. Sifariş diskdə qalan cədvəldə durmalıdır. Redis o cədvəlin tez baxılan surəti ola bilər.",
        "With Redis you write a value to a key, read it, and set a time. When the time ends, the key is deleted. It does not fit as the main place of an order. An order should stay in a table that remains on disk. Redis can be the quick copy of that table.",
        "Redis ile anahtara değer yazar, onu okur ve süre koyarsın. Süre bitince anahtar silinir. Siparişin ana yerine uymaz. Sipariş diskte kalan tabloda durmalıdır. Redis o tablonun tez bakılan kopyası olabilir.",
        "بـ Redis تكتب قيمة لمفتاح وتقرأها وتضع مدة. حين تنتهي المدة يُحذف المفتاح. لا يصلح مكاناً أساسياً للطلب. الطلب يجب أن يبقى في جدول يبقى على القرص. Redis قد يكون النسخة السريعة لذلك الجدول.",
        "В Redis пишут значение по ключу, читают его и ставят срок. Когда срок кончается, ключ удаляется. Он не годится как основное место заказа. Заказ должен лежать в таблице, которая остаётся на диске. Redis может быть быстрой копией этой таблицы.",
      ),
      hard: t(
        "Bir açar yazmaq asandır. Çətinlik yaddaşın dolmasındadır. Hər şeyi Redis-ə yığmaq maşını doldurur. Müddətsiz açar qala bilər. Server sönəndə diskə yazma açıq deyilsə son dəyişiklik gedə bilər. Parolu və ödənişin əsas sətirini burada saxlamaq olmaz.",
        "Writing one key is easy. The difficulty is the memory filling up. Putting everything into Redis fills the machine. A key without a time can stay. If writing to disk is not on when the server turns off, the last change can go. Do not keep a password or the main row of a payment here.",
        "Bir anahtar yazmak kolaydır. Zorluk belleğin dolmasıdır. Her şeyi Redis’e yığmak makineyi doldurur. Süresiz anahtar kalabilir. Sunucu kapanırken diske yazma açık değilse son değişiklik gidebilir. Parolayı ve ödemenin ana satırını burada tutmamak gerekir.",
        "كتابة مفتاح واحد سهلة. الصعوبة امتلاء الذاكرة. وضع كل شيء في Redis يملأ الجهاز. مفتاح بلا مدة قد يبقى. إذا لم تكن الكتابة إلى القرص مفتوحة حين ينطفئ الخادم قد يذهب آخر تغيير. لا تحفظ كلمة المرور ولا الصف الأساسي للدفع هنا.",
        "Записать один ключ легко. Трудность в том, что память заполняется. Складывать всё в Redis заполняет машину. Ключ без срока может остаться. Если запись на диск не включена, когда сервер гаснет, последнее изменение может уйти. Пароль и основную строку платежа здесь не хранят.",
      ),
      balance: t(
        "Üstünlük: oxumaq tezdir, müddət özü silir, eyni cavab təkrar hesab olunmur. Məhdudiyyət: yaddaş bahadır və sönəndə risk var. Redis MySQL-i əvəz etmir. O, tez baxılan qatı saxlayır.",
        "Advantage: a read is fast, the time deletes by itself, and the same answer is not calculated again. Limit: memory is expensive and there is a risk when it turns off. Redis does not replace MySQL. It keeps the layer that is looked at quickly.",
        "Avantaj: okuma tezdir, süre kendi siler, aynı cevap yeniden hesaplanmaz. Sınır: bellek pahalıdır ve kapanınca risk vardır. Redis MySQL’in yerine geçmez. Tez bakılan katmanı tutar.",
        "الميزة: القراءة سريعة والمدة تحذف وحدها والجواب نفسه لا يُحسب مرة أخرى. الحد: الذاكرة غالية وهناك خطر حين ينطفئ. Redis لا يحل محل MySQL. يحفظ الطبقة التي تُنظر بسرعة.",
        "Плюс: чтение быстрое, срок удаляет сам, один и тот же ответ не считают заново. Ограничение: память дорогая и есть риск при выключении. Redis не заменяет MySQL. Он хранит слой, на который смотрят быстро.",
      ),
      ideas: t(
        "Açar addır. Qiymət həmin ada bağlanan məlumatdır. Müddət açarın nə vaxt silinəcəyini deyir.",
        "A key is a name. A value is the data tied to that name. The time says when the key will be deleted.",
        "Anahtar addır. Değer o ada bağlanan veridir. Süre anahtarın ne zaman silineceğini söyler.",
        "المفتاح اسم. القيمة البيانات المربوطة بذلك الاسم. المدة تقول متى يُحذف المفتاح.",
        "Ключ — это имя. Значение — данные, связанные с этим именем. Срок говорит, когда ключ удалится.",
      ),
      ideaList: lines(
        ["SET qiymət yazır", "GET qiyməti oxuyur", "EX müddəti saniyə ilə qoyur", "Yaddaş diskdən tezdir, amma dolur"],
        ["SET writes a value", "GET reads the value", "EX sets the time in seconds", "Memory is faster than disk, but it fills"],
        ["SET değer yazar", "GET değeri okur", "EX süreyi saniye ile koyar", "Bellek diskten tezdir, ama dolar"],
        ["SET يكتب قيمة", "GET يقرأ القيمة", "EX يضع المدة بالثواني", "الذاكرة أسرع من القرص لكنها تمتلئ"],
        ["SET пишет значение", "GET читает значение", "EX ставит срок в секундах", "Память быстрее диска, но она заполняется"],
      ),
      sample: t(
        "Bu, bir açara mətn yazır və 60 saniyə sonra silinməsini deyir. Cədvəl yaratmır.",
        "This writes text to one key and says to delete it after 60 seconds. It does not create a table.",
        "Bu, bir anahtara metin yazar ve 60 saniye sonra silinmesini söyler. Tablo yaratmaz.",
        "هذا يكتب نصاً لمفتاح ويقول أن يُحذف بعد 60 ثانية. لا ينشئ جدولاً.",
        "Это пишет текст в один ключ и говорит удалить его через 60 секунд. Таблицу не создаёт.",
      ),
      code: `SET page:home "ready" EX 60`,
      faq: lines(
        ["Redis və MySQL eynidir? Xeyr. MySQL cədvəl saxlayır. Redis açar saxlayır və əsas yeri yaddaşdır.", "Maşın sönəndə hər şey qalır? Yalnız diskə yazma açıqdırsa. Yoxdursa yaddaşdakı son dəyişiklik gedə bilər.", "Parol burada saxlanır? Xeyr. Burada tez silinən və tez oxunan şey durur."],
        ["Are Redis and MySQL the same? No. MySQL keeps tables. Redis keeps keys, and its main place is memory.", "Does everything stay when the machine turns off? Only if writing to disk is on. If not, the last change in memory can go.", "Is a password stored here? No. What stays here is something that is deleted quickly and read quickly."],
        ["Redis ve MySQL aynı mı? Hayır. MySQL tablo tutar. Redis anahtar tutar ve ana yeri bellektir.", "Makine kapanınca her şey kalır mı? Yalnız diske yazma açıksa. Değilse bellekteki son değişiklik gidebilir.", "Parola burada tutulur mu? Hayır. Burada tez silinen ve tez okunan şey durur."],
        ["هل Redis وMySQL الشيء نفسه؟ لا. MySQL يحفظ جداول. Redis يحفظ مفاتيح ومكانه الأساسي الذاكرة.", "هل يبقى كل شيء حين ينطفئ الجهاز؟ فقط إذا كانت الكتابة إلى القرص مفتوحة. وإلا قد يذهب آخر تغيير في الذاكرة.", "هل تُحفظ كلمة المرور هنا؟ لا. هنا يقف ما يُحذف بسرعة ويُقرأ بسرعة."],
        ["Redis и MySQL — одно и то же? Нет. MySQL хранит таблицы. Redis хранит ключи, и основное место — память.", "Когда машина выключается, всё остаётся? Только если запись на диск включена. Иначе последнее изменение в памяти может уйти.", "Пароль хранят здесь? Нет. Здесь лежит то, что быстро удаляется и быстро читается."],
      ),
    },
  ),
  topic(
    "cron",
    "cron",
    t("cron nədir?", "What is cron?", "cron nedir?", "ما هو cron؟", "Что такое cron?"),
    t(
      "cron əmri vaxtı çatanda işə salan alətdir. Dil deyil. Sən yatarkən də təyin etdiyin dəqiqədə işi çağırır.",
      "cron is the tool that starts a command when its time comes. It is not a language. It calls the job at the minute you set, even while you sleep.",
      "cron, vakti gelince komutu çalıştıran araçtır. Dil değildir. Sen uyurken de belirlediğin dakikada işi çağırır.",
      "cron الأداة التي تشغّل الأمر حين يأتي وقته. ليست لغة. تستدعي العمل في الدقيقة التي حددتها حتى وأنت نائم.",
      "cron — инструмент, который запускает команду, когда приходит её время. Это не язык. Он вызывает работу в назначенную минуту, даже пока ты спишь.",
    ),
    t("cron nədir, crontab, vaxtlı əmr, Linux", "what is cron, crontab, scheduled command, Linux", "cron nedir, crontab, zamanlı komut", "ما هو cron, crontab, أمر مجدول", "что такое cron, crontab, команда по времени"),
    {
      what: t(
        "cron Unix sistemlərində köhnə vaxt qurulmasıdır. Siyahı crontab adlanır. Hər sətir beş vaxt xanasından və bir əmrdən ibarətdir: dəqiqə, saat, ayın günü, ay, həftənin günü. Ulduz həmin xananın hər qiyməti deməkdir. İş sənin istifadəçinin adı ilə açılır. Pəncərə açmır. Nəticə poçta və ya fayla gedə bilər. systemd timer oxşar işi görə bilər, amma cron-un özü deyil.",
        "cron is the old time setup on Unix systems. The list is called crontab. Each line is five time fields and one command: minute, hour, day of the month, month, and day of the week. A star means every value of that field. The job opens under your user's name. It does not open a window. The result can go to mail or to a file. A systemd timer can do a similar job, but it is not cron itself.",
        "cron, Unix sistemlerinde eski zaman kurulumudur. Listenin adı crontab’dır. Her satır beş zaman gözü ve bir komuttur: dakika, saat, ayın günü, ay, haftanın günü. Yıldız o gözün her değeri demektir. İş senin kullanıcının adıyla açılır. Pencere açmaz. Sonuç postaya veya dosyaya gidebilir. systemd timer benzer iş görebilir, ama cron’un kendisi değildir.",
        "cron إعداد الوقت القديم في أنظمة Unix. القائمة تسمى crontab. كل سطر خمسة حقول وقت وأمر واحد: الدقيقة والساعة ويوم الشهر والشهر ويوم الأسبوع. النجمة تعني كل قيمة لذلك الحقل. يُفتح العمل باسم مستخدمك. لا يفتح نافذة. النتيجة قد تذهب إلى البريد أو إلى ملف. مؤقت systemd قد يقوم بعمل قريب لكنه ليس cron نفسه.",
        "cron — старая установка времени в системах Unix. Список называется crontab. Каждая строка — пять полей времени и одна команда: минута, час, день месяца, месяц и день недели. Звезда значит каждое значение этого поля. Работа открывается от имени твоего пользователя. Окно она не открывает. Результат может уйти в почту или в файл. Таймер systemd может сделать похожую работу, но это не сам cron.",
      ),
      uses: t(
        "cron ehtiyat nüsxə, təmizlik və gecə hesabatı üçündür. Əl ilə hər gün eyni əmri yazmamaq üçündür.",
        "cron is for a backup, a cleanup, and a night report. It is so you do not type the same command by hand every day.",
        "cron yedek, temizlik ve gece raporu içindir. Her gün aynı komutu elle yazmamak içindir.",
        "cron للنسخة الاحتياطية والتنظيف وتقرير الليل. كي لا تكتب الأمر نفسه بيدك كل يوم.",
        "cron нужен для резервной копии, уборки и ночного отчёта. Чтобы не писать одну и ту же команду руками каждый день.",
      ),
      useList: lines(
        ["Hər gecə bazanın surətini almaq", "Köhnə müvəqqəti faylı silmək", "Səhər hesabatı göndərmək", "Bir saatdan bir yoxlama işlətmək"],
        ["Taking a copy of the database every night", "Deleting an old temporary file", "Sending a morning report", "Running a check once an hour"],
        ["Her gece veritabanının kopyasını almak", "Eski geçici dosyayı silmek", "Sabah raporu göndermek", "Saatte bir denetim çalıştırmak"],
        ["أخذ نسخة من القاعدة كل ليلة", "حذف ملف مؤقت قديم", "إرسال تقرير الصباح", "تشغيل فحص كل ساعة"],
        ["Каждую ночь снимать копию базы", "Удалять старый временный файл", "Отправлять утренний отчёт", "Запускать проверку раз в час"],
      ),
      can: t(
        "cron ilə əmri təqvimə bağlayırsan. O, əmrin düz olub-olmadığını yoxlamır. Səhv yol və ya səhv icazə olanda iş səssizcə düşə bilər. Ekran olmadığı üçün nəticəni fayla yazmaq lazımdır. Eyni iş hələ bitməmiş yenidən başlaya bilər.",
        "With cron you tie a command to a calendar. It does not check whether the command is right. When the path or the permission is wrong, the job can fall quietly. Because there is no screen, the result needs to be written to a file. The same job can start again before the last one has finished.",
        "cron ile komutu takvime bağlarsın. Komutun doğru olup olmadığını denetlemez. Yol veya izin yanlışsa iş sessizce düşebilir. Ekran olmadığı için sonucu dosyaya yazmak gerekir. Aynı iş bitmeden yeniden başlayabilir.",
        "بـ cron تربط الأمر بتقويم. هو لا يفحص هل الأمر صحيح. إذا أخطأ المسار أو الإذن قد يسقط العمل بصمت. لأن لا شاشة، يجب كتابة النتيجة في ملف. العمل نفسه قد يبدأ مرة أخرى قبل أن ينتهي السابق.",
        "Через cron команду привязывают к календарю. Он не проверяет, верна ли команда. Если путь или право неверны, работа может тихо упасть. Экрана нет, поэтому результат нужно писать в файл. Та же работа может начаться снова, пока прошлая не кончилась.",
      ),
      hard: t(
        "Bir sətir yazmaq asandır. Çətinlik saat qurşağında və yoldadır. Serverin saatı sənin saatın olmaya bilər. Əmrin içindəki qısa ad cron-un mühitində tapılmaya bilər. Tam yol yazılır. Ulduzu səhv qoymaq əmri hər dəqiqə işlədə bilər.",
        "Writing one line is easy. The difficulty is the time zone and the path. The server's clock may not be your clock. A short name inside the command may not be found in cron's environment. The full path is written. Putting the star wrong can run the command every minute.",
        "Bir satır yazmak kolaydır. Zorluk saat dilimi ve yoldadır. Sunucunun saati senin saatin olmayabilir. Komutun içindeki kısa ad cron’un ortamında bulunmayabilir. Tam yol yazılır. Yıldızı yanlış koymak komutu her dakika çalıştırabilir.",
        "كتابة سطر واحد سهلة. الصعوبة في منطقة الوقت والمسار. ساعة الخادم قد لا تكون ساعتك. الاسم القصير داخل الأمر قد لا يُوجد في بيئة cron. يُكتب المسار الكامل. وضع النجمة خطأ قد يشغّل الأمر كل دقيقة.",
        "Написать одну строку легко. Трудность в часовом поясе и в пути. Часы сервера могут быть не твоими часами. Короткое имя внутри команды может не найтись в окружении cron. Пишут полный путь. Неверная звезда может запускать команду каждую минуту.",
      ),
      balance: t(
        "Üstünlük: iş sənsiz də açılır, sətir qısadır, Linux serverində hazırdır. Məhdudiyyət: səhv səssiz qalır və üst-üstə düşə bilər. cron proqramın özü deyil. O, yalnız vaxtı çatanda əmri çağırır.",
        "Advantage: the job opens without you, the line is short, and it is ready on a Linux server. Limit: a mistake stays quiet and jobs can pile up. cron is not the program itself. It only calls the command when the time comes.",
        "Avantaj: iş sensiz de açılır, satır kısadır, Linux sunucusunda hazırdır. Sınır: hata sessiz kalır ve işler üst üste binebilir. cron programın kendisi değildir. Yalnız vakti gelince komutu çağırır.",
        "الميزة: العمل يُفتح بغيرك والسطر قصير وهو جاهز على خادم Linux. الحد: الخطأ يبقى صامتاً وقد تتراكم الأعمال. cron ليس البرنامج نفسه. يستدعي الأمر فقط حين يأتي الوقت.",
        "Плюс: работа открывается без тебя, строка короткая и на Linux-сервере он уже есть. Ограничение: ошибка остаётся тихой, и работы могут наслаиваться. cron — не сама программа. Он только вызывает команду, когда приходит время.",
      ),
      ideas: t(
        "Beş xana vaxtı deyir. Altıncı hissə əmrdir. İstifadəçi işin kimin adıyla açıldığını deyir.",
        "Five fields say the time. The sixth part is the command. The user says under whose name the job opens.",
        "Beş göz zamanı söyler. Altıncı parça komuttur. Kullanıcı işin kimin adıyla açıldığını söyler.",
        "خمسة حقول تقول الوقت. الجزء السادس الأمر. المستخدم يقول باسم من يُفتح العمل.",
        "Пять полей говорят время. Шестая часть — команда. Пользователь говорит, от чьего имени открывается работа.",
      ),
      ideaList: lines(
        ["Ulduz hər qiymət deməkdir", "0 3 * * * hər gecə saat 03:00", "crontab -l siyahını göstərir", "Nəticə özü ekrana çıxmır"],
        ["A star means every value", "0 3 * * * is every night at 03:00", "crontab -l shows the list", "The result does not come to the screen by itself"],
        ["Yıldız her değer demektir", "0 3 * * * her gece saat 03:00", "crontab -l listeyi gösterir", "Sonuç kendi ekrana çıkmaz"],
        ["النجمة تعني كل قيمة", "0 3 * * * كل ليلة الساعة 03:00", "crontab -l يُظهر القائمة", "النتيجة لا تخرج إلى الشاشة وحدها"],
        ["Звезда значит каждое значение", "0 3 * * * — каждую ночь в 03:00", "crontab -l показывает список", "Результат сам на экран не выходит"],
      ),
      sample: t(
        "Bu sətir hər gecə saat 03:00-da bir surət əmri çağırır. Əmrin özü burada yazılmayıb, yalnız yolu var.",
        "This line calls a copy command every night at 03:00. The command itself is not written here, only its path.",
        "Bu satır her gece saat 03:00’te bir kopya komutu çağırır. Komutun kendisi burada yazılmamıştır, yalnız yolu vardır.",
        "هذا السطر يستدعي أمر نسخ كل ليلة الساعة 03:00. الأمر نفسه غير مكتوب هنا، مساره فقط.",
        "Эта строка вызывает команду копии каждую ночь в 03:00. Сама команда здесь не написана, только её путь.",
      ),
      code: `0 3 * * * /usr/local/bin/backup`,
      faq: lines(
        ["cron proqramlaşdırma dilidir? Xeyr. Vaxtı çatanda hazır əmri çağırır.", "İş düşəndə ekranda görünür? Xeyr. Pəncərə yoxdur. Nəticəni fayla və ya jurnala yazmaq lazımdır.", "Ulduz yalnız bazar ertəsi deməkdir? Xeyr. Ulduz həmin xananın hər qiyməti deməkdir."],
        ["Is cron a programming language? No. It calls a ready command when the time comes.", "When the job falls, does it show on the screen? No. There is no window. The result has to be written to a file or a log.", "Does a star mean only Monday? No. A star means every value of that field."],
        ["cron programlama dili mi? Hayır. Vakti gelince hazır komutu çağırır.", "İş düşünce ekranda görünür mü? Hayır. Pencere yoktur. Sonucu dosyaya veya günlüğe yazmak gerekir.", "Yıldız yalnız pazartesi mi demektir? Hayır. Yıldız o gözün her değeri demektir."],
        ["هل cron لغة برمجة؟ لا. يستدعي أمراً جاهزاً حين يأتي الوقت.", "حين يسقط العمل هل يظهر على الشاشة؟ لا. لا نافذة. يجب كتابة النتيجة في ملف أو سجل.", "هل النجمة تعني الاثنين فقط؟ لا. النجمة تعني كل قيمة لذلك الحقل."],
        ["cron — язык программирования? Нет. Он вызывает готовую команду, когда приходит время.", "Когда работа падает, это видно на экране? Нет. Окна нет. Результат нужно писать в файл или журнал.", "Звезда значит только понедельник? Нет. Звезда значит каждое значение этого поля."],
      ),
    },
  ),
];
