import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_SEARCH: readonly StackPage[] = [
  topic(
    "git-github",
    "Git və GitHub",
    t("Git və GitHub-un fərqi", "Git vs GitHub", "Git ve GitHub farkı", "الفرق بين Git وGitHub", "Разница между Git и GitHub"),
    t(
      "Git kompüterindəki faylın köhnə addımlarını saxlayan proqramdır. GitHub isə həmin addımların durduğu saytdır. Git-siz GitHub versiya saxlamır. GitHub-suz da Git işləyir.",
      "Git is the program that keeps old steps of a file on your computer. GitHub is the site where those steps can sit. Without Git, GitHub does not keep versions. Git also works without GitHub.",
      "Git, bilgisayarındaki dosyanın eski adımlarını tutan programdır. GitHub ise o adımların durduğu sitedir. Git olmadan GitHub sürüm tutmaz. GitHub olmadan da Git çalışır.",
      "Git برنامج يحفظ خطوات الملف القديمة على حاسوبك. GitHub هو الموقع الذي تقف فيه تلك الخطوات. من غير Git لا يحفظ GitHub النسخ. وGit يعمل أيضاً من غير GitHub.",
      "Git — программа, которая хранит старые шаги файла на твоём компьютере. GitHub — сайт, где эти шаги могут лежать. Без Git сайт GitHub версии не хранит. Git работает и без GitHub.",
    ),
    t(
      "git və github fərqi, github nədir, git nədir, git push, commit",
      "git vs github, what is github, what is git, git push, commit",
      "git ve github farkı, github nedir, git nedir, git push",
      "الفرق بين git وgithub, ما هو github, ما هو git",
      "разница git и github, что такое github, что такое git, git push",
    ),
    {
      what: t(
        "Git 2005-ci ildə Linus Torvalds tərəfindən yazılıb. O, qovluqdakı faylların şəklini addım-addım yadda saxlayır. Hər addımın adı commit-dir. Köhnə addıma qayıtmaq olur. Bu proqram sənin maşınındadır. İnternet olmasa da commit yazılır. GitHub isə başqa şeydir. O, Microsoft-un saytıdır. Sən commit-i ora göndərəndə tarix internetdəki bir qovluqda dayanır. Kompüter sönsə, həmin nüsxə qalır. Başqası da onu görə bilir. GitHub-un issue, pull request və səhifə göstərmək hissəsi saytın öz xidmətidir. Onlar Git-in əmri deyil.",
        "Git was written by Linus Torvalds in 2005. It remembers the files in a folder step by step. Each step is called a commit. You can return to an old step. This program lives on your machine. A commit can be written with no internet. GitHub is something else. It is Microsoft's site. When you send a commit there, the history sits in a folder on the internet. If the computer dies, that copy remains. Someone else can see it too. Issues, pull requests, and showing a page are the site's own services. They are not a Git command.",
        "Git’i 2005’te Linus Torvalds yazdı. Klasördeki dosyaların şeklini adım adım hatırlar. Her adımın adı commit’tir. Eski adıma dönmek olur. Bu program senin makinededir. İnternet olmasa da commit yazılır. GitHub başka şeydir. Microsoft’un sitesidir. Commit’i oraya gönderince tarih internetteki bir klasörde durur. Bilgisayar ölse o kopya kalır. Başkası da onu görebilir. Issue, pull request ve sayfa göstermek sitenin kendi hizmetidir. Bunlar Git’in komutu değildir.",
        "كتب Linus Torvalds برنامج Git سنة 2005. هو يتذكر شكل الملفات في المجلد خطوة خطوة. اسم كل خطوة commit. يمكن الرجوع إلى خطوة قديمة. هذا البرنامج على جهازك. يُكتب الـ commit حتى بلا إنترنت. GitHub شيء آخر. هو موقع Microsoft. حين ترسل الـ commit إليه يقف التاريخ في مجلد على الإنترنت. إذا مات الحاسوب تبقى تلك النسخة. غيرك يقدر أن يراها. Issues وpull request وإظهار صفحة خدمات الموقع نفسه. ليست أمراً في Git.",
        "Git написал Линус Торвальдс в 2005 году. Он помнит вид файлов в папке шаг за шагом. Каждый шаг называется commit. К старому шагу можно вернуться. Эта программа живёт на твоей машине. Commit пишется и без интернета. GitHub — другое. Это сайт Microsoft. Когда ты отправляешь туда commit, история стоит в папке в интернете. Если компьютер умрёт, та копия останется. Другой человек тоже может её видеть. Issues, pull request и показ страницы — услуги самого сайта. Это не команда Git.",
      ),
      uses: t(
        "Git öz addımını saxlayır. GitHub həmin addımı başqasına və sabahkı sənə göstərir.",
        "Git keeps your own step. GitHub shows that step to someone else and to tomorrow's you.",
        "Git kendi adımını tutar. GitHub o adımı başkasına ve yarınki sana gösterir.",
        "Git يحفظ خطوتك أنت. GitHub يُظهر تلك الخطوة لغيرك ولغدك.",
        "Git хранит твой шаг. GitHub показывает этот шаг другому человеку и тебе завтрашнему.",
      ),
      useList: lines(
        ["Faylın dünənki halına qayıtmaq", "İki adamın eyni qovluqda işləməsi", "Hazır kodu başqasının görməsi", "Kompüter sınırsa nüsxənin qalması"],
        ["Returning a file to yesterday's state", "Two people working in the same folder", "Letting someone else see the finished code", "Keeping a copy if the computer breaks"],
        ["Dosyayı dünkü haline döndürmek", "İki kişinin aynı klasörde çalışması", "Hazır kodu başkasının görmesi", "Bilgisayar bozulursa kopyanın kalması"],
        ["إرجاع الملف إلى حال أمس", "عمل شخصين في المجلد نفسه", "أن يرى غيرك الكود الجاهز", "بقاء نسخة إذا انكسر الحاسوب"],
        ["Вернуть файл ко вчерашнему виду", "Двум людям работать в одной папке", "Дать другому увидеть готовый код", "Оставить копию, если компьютер сломается"],
      ),
      can: t(
        "Git ilə addım yazırsan, fərqi görürsən və köhnəyə dönürsən. GitHub ilə həmin addımı göndərirsən, başqasının addımını götürürsən və kodu bir ünvanda saxlayırsan. GitHub özü faylı yadda saxlayan sehr deyil. Əvvəl Git addımı yazmalıdır. Sonra push həmin addımı sayta qoyur. Pull isə saytdakı yeni addımı sənin qovluğuna gətirir. Sayt sönəndə Git kompüterində qalır. Git olmasa, sayta yalnız adi fayl yükləmək olar, addım tarixi yaranmır.",
        "With Git you write a step, see the difference, and go back. With GitHub you send that step, take someone else's step, and keep the code at an address. GitHub itself is not the magic that remembers the file. Git has to write the step first. Then push puts that step on the site. Pull brings a new step from the site into your folder. If the site is down, Git stays on your computer. Without Git you can only upload a plain file to the site, and no step history appears.",
        "Git ile adım yazarsın, farkı görürsün ve eskiye dönersin. GitHub ile o adımı gönderir, başkasının adımını alırsın ve kodu bir adreste tutarsın. GitHub kendi dosyayı hatırlayan sihir değildir. Önce Git adımı yazmalıdır. Sonra push o adımı siteye koyar. Pull ise sitedeki yeni adımı senin klasörüne getirir. Site kapanınca Git bilgisayarında kalır. Git olmasa siteye yalnız düz dosya yüklenir, adım tarihi oluşmaz.",
        "بـ Git تكتب خطوة وترى الفرق وترجع للقديم. بـ GitHub ترسل تلك الخطوة وتأخذ خطوة غيرك وتحفظ الكود في عنوان. GitHub نفسه ليس السحر الذي يتذكر الملف. Git يجب أن يكتب الخطوة أولاً. ثم push يضع تلك الخطوة على الموقع. وpull يجلب الخطوة الجديدة من الموقع إلى مجلدك. إذا انطفأ الموقع يبقى Git على حاسوبك. من غير Git لا يُرفع إلى الموقع إلا ملف عادي، ولا يظهر تاريخ الخطوات.",
        "В Git пишут шаг, видят разницу и возвращаются назад. Через GitHub этот шаг отправляют, берут чужой шаг и держат код по адресу. Сам GitHub — не волшебство, которое помнит файл. Сначала Git должен записать шаг. Потом push кладёт этот шаг на сайт. Pull приносит новый шаг с сайта в твою папку. Если сайт погас, Git остаётся на компьютере. Без Git на сайт можно загрузить только обычный файл, история шагов не появится.",
      ),
      hard: t(
        "Bir commit yazmaq asandır. Çətinlik iki tarix qarışanda başlayır. Eyni sətri iki adam dəyişibsə, Git özü doğru olanı seçmir, sən seçirsən. push rədd olunursa, adətən saytda səndə olmayan yeni addım var. Əvvəl pull lazımdır. Şifrəni və açarı koda yazmaq olmaz. GitHub-a göndərilən açıq qovluğu hər kəs oxuyur. Gizli açar ora düşəndə onu silmək azdır, açarı da dəyişmək lazımdır.",
        "Writing one commit is easy. The difficulty starts when two histories mix. If two people changed the same line, Git does not choose the right one. You choose. If push is refused, the site usually has a new step that you do not have. A pull is needed first. Do not write a password or a key into the code. An open folder sent to GitHub is read by anyone. When a secret key falls in there, deleting it is not enough. The key has to be changed too.",
        "Bir commit yazmak kolaydır. Zorluk iki tarih karışınca başlar. Aynı satırı iki kişi değiştirdiyse Git doğrusunu seçmez, sen seçersin. push reddedilirse sitede sende olmayan yeni adım vardır. Önce pull gerekir. Parolayı ve anahtarı koda yazmamak gerekir. GitHub’a giden açık klasörü herkes okur. Gizli anahtar oraya düşünce silmek yetmez, anahtarı da değiştirmek gerekir.",
        "كتابة commit واحد سهلة. الصعوبة تبدأ حين يختلط تاريخان. إذا غيّر شخصان السطر نفسه فـ Git لا يختار الصحيح. أنت تختار. إذا رُفض push ففي الموقع غالباً خطوة جديدة ليست عندك. يلزم pull أولاً. لا تكتب كلمة المرور ولا المفتاح في الكود. المجلد المفتوح المرسل إلى GitHub يقرؤه أي أحد. إذا سقط مفتاح سري هناك فحذفه لا يكفي. يجب تغيير المفتاح أيضاً.",
        "Один commit написать легко. Трудность начинается, когда смешиваются две истории. Если двое изменили одну строку, Git сам правильную не выбирает. Выбираешь ты. Если push отказали, на сайте обычно есть новый шаг, которого у тебя нет. Сначала нужен pull. Пароль и ключ в код не пишут. Открытую папку, отправленную на GitHub, читает кто угодно. Если туда попал секретный ключ, удалить его мало. Ключ надо ещё сменить.",
      ),
      balance: t(
        "Git addımı kompüterində tez saxlayır və köhnəyə dönüş verir. GitHub nüsxəni internetdə saxlayır və başqasına yol açır. İkisi bir-birinin yerini tutmur. Git öyrənmədən yalnız sayta fayl atmaq tarix yaratmır. GitHub-suz işləmək olar, amma maşın sınırsa addımlar da gedə bilər.",
        "Git stores a step on your computer quickly and lets you go back. GitHub keeps the copy on the internet and opens a way for someone else. One does not take the other's place. Throwing a file onto the site without learning Git does not create history. You can work without GitHub, but if the machine breaks the steps can go too.",
        "Git adımı bilgisayarında çabuk tutar ve eskiye dönüş verir. GitHub kopyayı internette tutar ve başkasına yol açar. Biri diğerinin yerini tutmaz. Git öğrenmeden siteye yalnız dosya atmak tarih yaratmaz. GitHub’suz çalışmak olur, ama makine bozulursa adımlar da gidebilir.",
        "Git يحفظ الخطوة على حاسوبك بسرعة ويتيح الرجوع. GitHub يبقي النسخة على الإنترنت ويفتح طريقاً لغيرك. واحد لا يأخذ مكان الآخر. رمي ملف على الموقع من غير تعلم Git لا يصنع تاريخاً. يمكن العمل بلا GitHub، لكن إذا انكسر الجهاز قد تذهب الخطوات أيضاً.",
        "Git быстро хранит шаг на компьютере и даёт вернуться. GitHub держит копию в интернете и открывает путь другому. Один не занимает место другого. Просто бросить файл на сайт, не выучив Git, историю не создаёт. Без GitHub работать можно, но если машина сломается, шаги тоже могут уйти.",
      ),
      ideas: t(
        "Dörd söz kifayətdir: commit addımdır, push göndərməkdir, pull gətirməkdir, GitHub isə ünvanın durduğu saytdır.",
        "Four words are enough: a commit is a step, push is sending, pull is bringing, and GitHub is the site where the address sits.",
        "Dört söz yeter: commit adımdır, push göndermektir, pull getirmektir, GitHub ise adresin durduğu sitedir.",
        "أربع كلمات تكفي: commit خطوة، وpush إرسال، وpull جلب، وGitHub الموقع الذي يقف فيه العنوان.",
        "Четырёх слов хватает: commit — это шаг, push — отправка, pull — получение, а GitHub — сайт, где стоит адрес.",
      ),
      ideaList: lines(
        ["Git proqramdır, GitHub saytdır", "Commit bir addımın adıdır", "Push addımı sayta qoyur", "Pull saytdakı addımı gətirir"],
        ["Git is a program, GitHub is a site", "A commit is the name of one step", "Push puts the step on the site", "Pull brings the step from the site"],
        ["Git programdır, GitHub sitedir", "Commit bir adımın adıdır", "Push adımı siteye koyar", "Pull sitedeki adımı getirir"],
        ["Git برنامج وGitHub موقع", "Commit اسم خطوة واحدة", "Push يضع الخطوة على الموقع", "Pull يجلب الخطوة من الموقع"],
        ["Git — программа, GitHub — сайт", "Commit — имя одного шага", "Push кладёт шаг на сайт", "Pull приносит шаг с сайта"],
      ),
      sample: t(
        "Bu üç əmr addımı yazır və onu GitHub-a göndərir. Sayt ünvanı sənin qovluğunun ünvanı olmalıdır.",
        "These three commands write a step and send it to GitHub. The site address has to be the address of your folder.",
        "Bu üç komut adımı yazar ve onu GitHub’a gönderir. Site adresi senin klasörünün adresi olmalıdır.",
        "هذه الأوامر الثلاثة تكتب خطوة وترسلها إلى GitHub. عنوان الموقع يجب أن يكون عنوان مجلدك.",
        "Эти три команды пишут шаг и отправляют его на GitHub. Адрес сайта должен быть адресом твоей папки.",
      ),
      code: `git add .
git commit -m "ilk addım"
git push`,
      faq: lines(
        ["Git və GitHub eynidir? Xeyr. Git proqramdır. GitHub həmin proqramın addımlarını saxlaya bilən saytdır.", "GitHub olmadan Git işləyir? Bəli. Addım kompüterində qalır. Başqası onu görmür və maşın sınırsa nüsxə saytda olmur.", "Push nə edir? Sənin yazdığın commit-i saytdakı qovluğa göndərir. Özü yeni addım yaratmır."],
        ["Are Git and GitHub the same? No. Git is a program. GitHub is a site that can keep that program's steps.", "Does Git work without GitHub? Yes. The step stays on your computer. Someone else does not see it, and if the machine breaks there is no copy on the site.", "What does push do? It sends the commit you wrote into the folder on the site. It does not create a new step by itself."],
        ["Git ve GitHub aynı mı? Hayır. Git programdır. GitHub o programın adımlarını tutabilen sitedir.", "GitHub olmadan Git çalışır mı? Evet. Adım bilgisayarında kalır. Başkası onu görmez ve makine bozulursa sitede kopya olmaz.", "Push ne yapar? Yazdığın commit’i sitedeki klasöre gönderir. Kendi yeni adım yaratmaz."],
        ["هل Git وGitHub الشيء نفسه؟ لا. Git برنامج. GitHub موقع يقدر أن يحفظ خطوات ذلك البرنامج.", "هل يعمل Git بلا GitHub؟ نعم. الخطوة تبقى على حاسوبك. غيرك لا يراها، وإذا انكسر الجهاز لا توجد نسخة على الموقع.", "ماذا يفعل push؟ يرسل الـ commit الذي كتبته إلى المجلد على الموقع. لا يصنع خطوة جديدة بنفسه."],
        ["Git и GitHub — одно и то же? Нет. Git — программа. GitHub — сайт, который может хранить шаги этой программы.", "Git работает без GitHub? Да. Шаг остаётся на компьютере. Другой его не видит, и если машина сломается, копии на сайте нет.", "Что делает push? Отправляет написанный тобой commit в папку на сайте. Сам новый шаг не создаёт."],
      ),
    },
  ),
  topic(
    "api",
    "API",
    t("API nədir?", "What is an API?", "API nedir?", "ما هو API؟", "Что такое API?"),
    t(
      "API bir proqramın başqa proqrama açdığı qapıdır. Adam düyməyə basır. Proqram isə bu qapıdan ünvan göndərir və cavab alır. İçəridəki kodu görmək lazım deyil.",
      "An API is a door one program opens for another program. A person presses a button. A program sends an address through this door and gets an answer. You do not have to see the code inside.",
      "API, bir programın başka programa açtığı kapıdır. İnsan düğmeye basar. Program ise bu kapıdan adres gönderir ve cevap alır. İçerideki kodu görmek gerekmez.",
      "API باب يفتحه برنامج لبرنامج آخر. الإنسان يضغط زراً. أما البرنامج فيرسل عنواناً من هذا الباب ويأخذ جواباً. لا يلزم أن ترى الكود في الداخل.",
      "API — дверь, которую одна программа открывает другой. Человек жмёт кнопку. Программа же шлёт адрес через эту дверь и получает ответ. Код внутри видеть не нужно.",
    ),
    t(
      "api nədir, api nədir sadə, rest api, api açarı, json",
      "what is an api, api explained simply, rest api, api key, json",
      "api nedir, api nedir basit, rest api, api anahtarı",
      "ما هو api, ما هو api ببساطة, rest api, مفتاح api",
      "что такое api, api простыми словами, rest api, ключ api",
    ),
    {
      what: t(
        "API sözü Application Programming Interface-dir. Sadə desək, hazır danışıq qaydasıdır. Bir tərəf sorur, o biri tərəf qayda üzrə cavab verir. Sən hava saytının içindəki bazanı görmürsən. Ona bir ünvan göndərirsən, o da bugünkü istiliyi yazı və ya JSON şəklində qaytarır. Eyni qayda ilə xəritə, ödəniş və tərcümə də soruşulur. API özü dil deyil. Python da deyil, JavaScript də deyil. O, iki proqramın sözləşdiyi yoldur. Yol dəyişsə, köhnə sualın cavabı da dəyişə bilər. Ona görə sənədləşməyə baxmaq lazımdır.",
        "API means Application Programming Interface. In plain words, it is a ready way of talking. One side asks, the other side answers by the rule. You do not see the weather site's database. You send it an address, and it returns today's temperature as text or JSON. A map, a payment, and a translation are asked the same way. An API is not a language. It is not Python and it is not JavaScript. It is the path two programs agreed on. If the path changes, the answer to an old question can change too. That is why you look at the documentation.",
        "API sözü Application Programming Interface demektir. Basitçe, hazır konuşma kuralıdır. Bir taraf sorar, öteki taraf kurala göre cevap verir. Hava sitesinin içindeki tabanı görmezsin. Ona bir adres gönderirsin, o da bugünkü ısıyı yazı ya da JSON olarak döndürür. Harita, ödeme ve çeviri de aynı yolla sorulur. API kendi dil değildir. Python da değildir, JavaScript de değildir. İki programın sözleştiği yoldur. Yol değişirse eski sorunun cevabı da değişebilir. Bu yüzden belgeye bakmak gerekir.",
        "كلمة API تعني Application Programming Interface. ببساطة هي قاعدة كلام جاهزة. طرف يسأل والطرف الآخر يجيب حسب القاعدة. أنت لا ترى قاعدة موقع الطقس. ترسل له عنواناً وهو يرجع حرارة اليوم نصاً أو JSON. الخريطة والدفع والترجمة تُسأل بالطريق نفسه. API ليست لغة. ليست Python وليست JavaScript. هي الطريق الذي اتفق عليه برنامجان. إذا تغير الطريق قد يتغير جواب السؤال القديم. لذلك يلزم النظر في التوثيق.",
        "Слово API значит Application Programming Interface. Проще: это готовое правило разговора. Одна сторона спрашивает, другая отвечает по правилу. Базу внутри сайта погоды ты не видишь. Ты шлёшь ей адрес, а она возвращает сегодняшнюю температуру текстом или JSON. Карту, оплату и перевод спрашивают тем же путём. API — не язык. Это не Python и не JavaScript. Это путь, о котором договорились две программы. Если путь изменится, ответ на старый вопрос тоже может измениться. Поэтому смотрят документацию.",
      ),
      uses: t(
        "API başqa yerdə duran hazır işi sənin proqramına gətirir. Hər şeyi sıfırdan yazmırsan.",
        "An API brings a ready job that lives somewhere else into your program. You do not write everything from zero.",
        "API başka yerde duran hazır işi senin programına getirir. Her şeyi sıfırdan yazmazsın.",
        "API يجلب إلى برنامجك عملاً جاهزاً يقف في مكان آخر. لا تكتب كل شيء من الصفر.",
        "API приносит в твою программу готовую работу, которая стоит в другом месте. Не всё пишут с нуля.",
      ),
      useList: lines(
        ["Havanı və ya məzənnəni soruşmaq", "Ödənişi başqa xidmətə həvalə etmək", "Saytın öz məlumatını telefona vermək", "İki proqramın eyni bazaya toxunmadan danışması"],
        ["Asking for the weather or a rate", "Leaving a payment to another service", "Giving the site's own data to a phone", "Letting two programs talk without touching the same database"],
        ["Havayı veya kuru sormak", "Ödemeyi başka hizmete bırakmak", "Sitenin kendi verisini telefona vermek", "İki programın aynı tabana dokunmadan konuşması"],
        ["سؤال الطقس أو سعر الصرف", "ترك الدفع لخدمة أخرى", "إعطاء بيانات الموقع نفسه للهاتف", "كلام برنامجين من غير لمس القاعدة نفسها"],
        ["Спросить погоду или курс", "Оставить оплату другому сервису", "Отдать свои данные сайта телефону", "Двум программам говорить, не трогая одну базу"],
      ),
      can: t(
        "API ilə sual göndərirsən və cavabı oxuyursan. Çox vaxt ünvan bir yoldur, üsul isə GET və ya POST-dur. GET oxumaq üçündür. POST yeni bir şey göndərmək üçündür. Cavab çox vaxt JSON-dur: açar və qiymət. Sən həmin yazını öz səhifəndə göstərirsən. API səhifəni çəkmir və düyməni basmır. Açarı olan qapı hər kəsə açıq olmur. Açarı səhifənin içinə yazsan, baxan adam onu götürür. Açar serverdə qalmalıdır.",
        "With an API you send a question and read the answer. Often the address is one path, and the method is GET or POST. GET is for reading. POST is for sending something new. The answer is often JSON: a key and a value. You show that text on your own page. An API does not draw the page and does not press the button. A door with a key is not open to everyone. If you write the key inside the page, a person who looks takes it. The key has to stay on the server.",
        "API ile soru gönderir ve cevabı okursun. Çoğu zaman adres bir yoldur, yöntem ise GET ya da POST’tur. GET okumak içindir. POST yeni bir şey göndermek içindir. Cevap çoğu zaman JSON’dur: anahtar ve değer. O yazıyı kendi sayfanda gösterirsin. API sayfayı çizmez ve düğmeye basmaz. Anahtarı olan kapı herkese açık değildir. Anahtarı sayfanın içine yazarsan bakan kişi onu alır. Anahtar sunucuda kalmalıdır.",
        "بـ API ترسل سؤالاً وتقرأ الجواب. غالباً العنوان مسار واحد والطريقة GET أو POST. GET للقراءة. POST لإرسال شيء جديد. الجواب غالباً JSON: مفتاح وقيمة. تُظهر ذلك النص في صفحتك. API لا يرسم الصفحة ولا يضغط الزر. الباب الذي له مفتاح ليس مفتوحاً لكل أحد. إذا كتبت المفتاح داخل الصفحة فمن ينظر يأخذه. المفتاح يجب أن يبقى في الخادم.",
        "Через API посылают вопрос и читают ответ. Часто адрес — один путь, а способ — GET или POST. GET для чтения. POST чтобы послать новое. Ответ часто JSON: ключ и значение. Этот текст показывают на своей странице. API страницу не рисует и кнопку не жмёт. Дверь с ключом открыта не всем. Если ключ написать внутри страницы, смотрящий его заберёт. Ключ должен оставаться на сервере.",
      ),
      hard: t(
        "Bir açıq ünvandan hava oxumaq asandır. Çətinlik qayda və açardadır. Ünvan bir hərf dəyişsə, köhnə sorğu qırılır. Limit ola bilər: gündə müəyyən saydan sonra cavab gəlmir. Cavab boş, səhv və ya gecikən ola bilər. Bunu yoxlamadan səhifəyə basmaq olmaz. Başqasının açarı ilə sorğu pul və ya məlumat apara bilər. Sənəddə nə soruşmaq olar, nə qadağandır, onu oxumadan işə başlamaq olmaz.",
        "Reading the weather from one open address is easy. The difficulty is the rule and the key. If the address changes by one letter, the old question breaks. There can be a limit: after a set number in a day the answer stops. The answer can be empty, wrong, or late. Do not put it on the page without checking. A question with someone else's key can take money or data. Do not start before reading what the document allows and what it forbids.",
        "Bir açık adresten hava okumak kolaydır. Zorluk kural ve anahtardadır. Adres bir harf değişirse eski sorgu kırılır. Limit olabilir: günde belli sayıdan sonra cevap gelmez. Cevap boş, yanlış veya geç olabilir. Bunu yoklamadan sayfaya basmamak gerekir. Başkasının anahtarıyla sorgu para ya da veri götürebilir. Belgede ne sorulur, ne yasaktır, onu okumadan işe başlamamak gerekir.",
        "قراءة الطقس من عنوان مفتوح واحد سهلة. الصعوبة في القاعدة والمفتاح. إذا تغير العنوان بحرف ينكسر السؤال القديم. قد يوجد حد: بعد عدد معين في اليوم لا يأتي الجواب. الجواب قد يكون فارغاً أو خطأ أو متأخراً. لا تضعه في الصفحة بلا فحص. سؤال بمفتاح غيرك قد يأخذ مالاً أو بيانات. لا تبدأ قبل قراءة ما يسمح به التوثيق وما يمنعه.",
        "Прочитать погоду с одного открытого адреса легко. Трудность в правиле и ключе. Если адрес изменится на одну букву, старый вопрос сломается. Может быть предел: после числа за день ответ не приходит. Ответ бывает пустым, неверным или поздним. Нельзя ставить его на страницу без проверки. Вопрос с чужим ключом может унести деньги или данные. Не начинают, не прочитав, что документ разрешает и что запрещает.",
      ),
      balance: t(
        "API hazır işi sənə gətirir və içərini gizlədir. Bu, sürətdir. Qiyməti isə asılılıqdır. Qarşı tərəf ünvanı dəyişsə və ya limiti bağlasa, sənin proqramın da dayanır. Hər şeyi özündə yazsan, az asılısan, amma çox iş yazırsan. Kiçik sayt üçün hazır API düz yoldur. Açarı isə heç vaxt hamının gördüyü yerə qoyma.",
        "An API brings you a ready job and hides the inside. That is speed. The price is dependence. If the other side changes the address or closes the limit, your program stops too. If you write everything yourself, you depend less, but you write a lot. For a small site a ready API is a straight path. Never put the key where everyone can see it.",
        "API hazır işi sana getirir ve içeriyi gizler. Bu, hızdır. Bedeli bağımlılıktır. Karşı taraf adresi değiştirirse veya limiti kapatırsa senin programın da durur. Her şeyi kendin yazarsan az bağlısın, ama çok iş yazarsın. Küçük site için hazır API düz yoldur. Anahtarı ise herkesin gördüğü yere hiç koyma.",
        "API يجلب لك عملاً جاهزاً ويخفي الداخل. هذه سرعة. ثمنها الاعتماد. إذا غيّر الطرف الآخر العنوان أو أغلق الحد يتوقف برنامجك أيضاً. إذا كتبت كل شيء بنفسك فاعتمادك أقل لكنك تكتب عملاً كثيراً. لموقع صغير الـ API الجاهز طريق مستقيم. أما المفتاح فلا تضعه أبداً حيث يراه الجميع.",
        "API приносит тебе готовую работу и прячет нутро. Это скорость. Цена — зависимость. Если другая сторона сменит адрес или закроет предел, твоя программа тоже встанет. Если писать всё самому, зависишь меньше, но пишешь много. Для маленького сайта готовый API — прямой путь. Ключ никогда не кладут туда, где его видят все.",
      ),
      ideas: t(
        "API qapıdır. Ünvan sualın yeridir. JSON isə cavabın yazı formasıdır.",
        "An API is a door. The address is where the question goes. JSON is the written form of the answer.",
        "API kapıdır. Adres sorunun yeridir. JSON ise cevabın yazı biçimidir.",
        "API باب. العنوان مكان السؤال. وJSON شكل الجواب المكتوب.",
        "API — дверь. Адрес — место вопроса. JSON — письменный вид ответа.",
      ),
      ideaList: lines(
        ["Proqram proqrama soruşur, adam düyməyə basır", "GET oxuyur, POST göndərir", "Cavab çox vaxt JSON olur", "Açar hamının gördüyü səhifəyə yazılmır"],
        ["A program asks a program, a person presses a button", "GET reads, POST sends", "The answer is often JSON", "A key is not written on a page everyone sees"],
        ["Program programa sorar, insan düğmeye basar", "GET okur, POST gönderir", "Cevap çoğu zaman JSON olur", "Anahtar herkesin gördüğü sayfaya yazılmaz"],
        ["البرنامج يسأل البرنامج والإنسان يضغط الزر", "GET يقرأ وPOST يرسل", "الجواب غالباً JSON", "المفتاح لا يُكتب في صفحة يراها الجميع"],
        ["Программа спрашивает программу, человек жмёт кнопку", "GET читает, POST отправляет", "Ответ часто бывает JSON", "Ключ не пишут на странице, которую видят все"],
      ),
      sample: t(
        "Bu, bir istifadəçini oxumaq üçün ünvanın sadə halıdır. Cavab adətən JSON gəlir.",
        "This is the simple form of an address for reading one user. The answer usually comes as JSON.",
        "Bu, bir kullanıcıyı okumak için adresin basit halidir. Cevap genellikle JSON gelir.",
        "هذا الشكل البسيط لعنوان يقرأ مستخدماً واحداً. الجواب يأتي عادة JSON.",
        "Это простой вид адреса, чтобы прочитать одного пользователя. Ответ обычно приходит как JSON.",
      ),
      code: `GET /users/12

{
  "id": 12,
  "name": "Nibras"
}`,
      faq: lines(
        ["API proqramlaşdırma dilidir? Xeyr. İki proqramın danışma qaydasıdır. Python və JavaScript onu çağıran dillər ola bilər.", "API və sayt eynidir? Xeyr. Saytı adam oxuyur. API-ni proqram oxuyur. İkisi eyni məlumatdan gələ bilər.", "Açarı səhifəyə yazmaq olar? Xeyr. Baxan adam onu götürür. Açar serverdə qalmalıdır."],
        ["Is an API a programming language? No. It is the talking rule of two programs. Python and JavaScript can be the languages that call it.", "Are an API and a site the same? No. A person reads a site. A program reads an API. Both can come from the same data.", "Can you write the key on the page? No. A person who looks takes it. The key has to stay on the server."],
        ["API programlama dili mi? Hayır. İki programın konuşma kuralıdır. Python ve JavaScript onu çağıran dil olabilir.", "API ve site aynı mı? Hayır. Siteyi insan okur. API’yi program okur. İkisi aynı veriden gelebilir.", "Anahtarı sayfaya yazmak olur mu? Hayır. Bakan kişi onu alır. Anahtar sunucuda kalmalıdır."],
        ["هل API لغة برمجة؟ لا. هي قاعدة كلام برنامجين. Python وJavaScript قد تكونان اللغة التي تستدعيه.", "هل API والموقع الشيء نفسه؟ لا. الإنسان يقرأ الموقع. البرنامج يقرأ API. الاثنان قد يأتيان من البيانات نفسها.", "هل تكتب المفتاح في الصفحة؟ لا. من ينظر يأخذه. المفتاح يجب أن يبقى في الخادم."],
        ["API — язык программирования? Нет. Это правило разговора двух программ. Python и JavaScript могут быть языками, которые его вызывают.", "API и сайт — одно и то же? Нет. Сайт читает человек. API читает программа. Оба могут идти из одних данных.", "Можно писать ключ на странице? Нет. Кто смотрит, тот его заберёт. Ключ должен оставаться на сервере."],
      ),
    },
  ),
  topic(
    "python-javascript",
    "Python və JavaScript",
    t("Python, yoxsa JavaScript?", "Python or JavaScript?", "Python mu, JavaScript mi?", "بايثون أم جافاسكريبت؟", "Python или JavaScript?"),
    t(
      "Python kompüterdə kiçik proqram, hesab və məlumat üçün sakit başlanğıcdır. JavaScript isə səhifədə düyməni işlədən dildir. Brauzer onu artıq tanıyır. Biri o birinin yerini tutmur.",
      "Python is a calm start for a small program, a calculation, and data on a computer. JavaScript is the language that runs a button on a page. The browser already knows it. One does not take the other's place.",
      "Python bilgisayarda küçük program, hesap ve veri için sakin bir başlangıçtır. JavaScript ise sayfada düğmeyi çalıştıran dildir. Tarayıcı onu zaten tanır. Biri diğerinin yerini tutmaz.",
      "بايثون بداية هادئة لبرنامج صغير وحساب وبيانات على الحاسوب. جافاسكريبت هي اللغة التي تشغّل زراً في الصفحة. المتصفح يعرفها أصلاً. واحد لا يأخذ مكان الآخر.",
      "Python — спокойное начало для маленькой программы, счёта и данных на компьютере. JavaScript — язык, который запускает кнопку на странице. Браузер его уже знает. Один не занимает место другого.",
    ),
    t(
      "python yoxsa javascript, python və javascript fərqi, hansı dildən başlamaq, javascript nədir",
      "python or javascript, python vs javascript, which language to start, what is javascript",
      "python mu javascript mi, python ve javascript farkı, hangi dilden başlamalı",
      "بايثون أم جافاسكريبت, الفرق بين بايثون وجافاسكريبت, من أي لغة أبدأ",
      "python или javascript, разница python и javascript, с какого языка начать",
    ),
    {
      what: t(
        "Python 1991-ci ildə Guido van Rossum-un işidir. Yazısı adi cümləyə yaxındır. Faylı işə salırsan, nəticəni terminalda görürsən. Hesab, cədvəl, sadə avtomat və server tərəfi üçün çox kitabxanası var. JavaScript isə səhifənin içində doğulub. Brauzer HTML-i göstərir, JavaScript isə düyməyə, yazıya və rəngə toxunur. Əvvəl yalnız səhifədə işləyirdi. İndi Node.js ilə kompüterdə də işləyir, amma bu onu Python etmir. Səhifə istəyirsənsə, əvvəl HTML, sonra JavaScript. Kiçik proqram, məlumat və təkrar iş istəyirsənsə, Python sakit yoldur. İkisi də öyrənilir. Birincini seçmək o birini atmaq deyil.",
        "Python is Guido van Rossum's work from 1991. Its writing is close to an ordinary sentence. You run a file and see the result in the terminal. It has many libraries for a calculation, a table, a simple automation, and the server side. JavaScript was born inside the page. The browser shows HTML, and JavaScript touches a button, a text, and a color. At first it only ran on the page. Now it also runs on a computer with Node.js, but that does not make it Python. If you want a page, HTML first, then JavaScript. If you want a small program, data, and a repeated job, Python is the calm path. Both can be learned. Choosing the first one is not throwing the other away.",
        "Python, Guido van Rossum’un 1991’deki işidir. Yazısı olağan cümleye yakındır. Dosyayı çalıştırır, sonucu terminalde görürsün. Hesap, tablo, basit otomat ve sunucu tarafı için çok kitaplığı vardır. JavaScript sayfanın içinde doğdu. Tarayıcı HTML’i gösterir, JavaScript düğmeye, yazıya ve renge dokunur. Önce yalnız sayfada çalışırdı. Şimdi Node.js ile bilgisayarda da çalışır, ama bu onu Python yapmaz. Sayfa istiyorsan önce HTML, sonra JavaScript. Küçük program, veri ve tekrar iş istiyorsan Python sakin yoldur. İkisi de öğrenilir. Birincisini seçmek ötekini atmak değildir.",
        "بايثون عمل Guido van Rossum سنة 1991. كتابتها قريبة من جملة عادية. تشغّل ملفاً وترى النتيجة في الطرفية. لها مكتبات كثيرة للحساب والجدول والأتمتة البسيطة وجهة الخادم. جافاسكريبت وُلدت داخل الصفحة. المتصفح يُظهر HTML وجافاسكريبت تلمس الزر والنص واللون. أولاً كانت تعمل في الصفحة فقط. الآن تعمل على الحاسوب مع Node.js أيضاً، لكن هذا لا يجعلها بايثون. إذا أردت صفحة فـ HTML أولاً ثم جافاسكريبت. إذا أردت برنامجاً صغيراً وبيانات وعملاً مكرراً فبايثون طريق هادئ. الاثنتان تُتعلمان. اختيار الأولى ليس رمي الأخرى.",
        "Python — работа Гвидо ван Россума 1991 года. Запись близка к обычной фразе. Запускаешь файл и видишь результат в терминале. Много библиотек для счёта, таблицы, простой автоматизации и серверной стороны. JavaScript родился внутри страницы. Браузер показывает HTML, а JavaScript трогает кнопку, текст и цвет. Сначала он работал только на странице. Теперь с Node.js работает и на компьютере, но это не делает его Python. Если нужна страница — сначала HTML, потом JavaScript. Если нужна маленькая программа, данные и повторная работа — Python спокойный путь. Учат оба. Выбрать первый — не выбросить второй.",
      ),
      uses: t(
        "Python maşında iş görür. JavaScript səhifədə iş görür. Saytın arxası ikisindən birini götürə bilər.",
        "Python does a job on the machine. JavaScript does a job on the page. The back of a site can take either one.",
        "Python makinede iş görür. JavaScript sayfada iş görür. Sitenin arkası ikisinden birini alabilir.",
        "بايثون يعمل على الجهاز. جافاسكريبت تعمل في الصفحة. خلف الموقع قد يأخذ أي واحد منهما.",
        "Python делает работу на машине. JavaScript делает работу на странице. Зад сайта может взять любой из них.",
      ),
      useList: lines(
        ["Python ilə faylın adını dəyişmək və hesab etmək", "JavaScript ilə düyməni və siyahını səhifədə dəyişmək", "Python ilə məlumatı oxumaq", "JavaScript ilə brauzerdə hazır səhifəni canlandırmaq"],
        ["Renaming a file and calculating with Python", "Changing a button and a list on the page with JavaScript", "Reading data with Python", "Bringing a ready page to life in the browser with JavaScript"],
        ["Python ile dosyanın adını değiştirmek ve hesaplamak", "JavaScript ile düğmeyi ve listeyi sayfada değiştirmek", "Python ile veriyi okumak", "JavaScript ile tarayıcıda hazır sayfayı canlandırmak"],
        ["تغيير اسم ملف والحساب ببايثون", "تغيير زر وقائمة في الصفحة بجافاسكريبت", "قراءة البيانات ببايثون", "إحياء صفحة جاهزة في المتصفح بجافاسكريبت"],
        ["Переименовать файл и посчитать на Python", "Менять кнопку и список на странице на JavaScript", "Читать данные на Python", "Оживлять готовую страницу в браузере на JavaScript"],
      ),
      can: t(
        "Python ilə skript yazırsan, rəqəm tutursan və serverdə cavab hazırlayırsan. JavaScript ilə səhifədəki elementi tutursan və istifadəçi basanda bir şey dəyişirsən. Brauzer Python-u özü işlətmir. Səhifəyə .py qoymaq düyməni işlətmir. Node.js JavaScript-i brauzerdən çıxarır, amma səhifənin üzünü yenə HTML və JavaScript tutur. Bir layihədə ikisi yanaşı dura bilər: üzdə JavaScript, arxada Python. Birini öyrənmək o birinin sintaksisini vermir. Fikir oxşar ola bilər, yazı isə ayrıdır.",
        "With Python you write a script, hold a number, and prepare an answer on the server. With JavaScript you hold an element on the page and change something when the user presses. The browser does not run Python by itself. Putting a .py file on the page does not run a button. Node.js takes JavaScript out of the browser, but the face of the page is still held by HTML and JavaScript. In one project both can stand side by side: JavaScript on the face, Python at the back. Learning one does not give you the other's syntax. The idea can be similar, the writing is separate.",
        "Python ile betik yazarsın, sayı tutarsın ve sunucuda cevap hazırlarsın. JavaScript ile sayfadaki öğeyi tutarsın ve kullanıcı basınca bir şey değiştirirsin. Tarayıcı Python’u kendi çalıştırmaz. Sayfaya .py koymak düğmeyi çalıştırmaz. Node.js JavaScript’i tarayıcıdan çıkarır, ama sayfanın yüzünü yine HTML ve JavaScript tutar. Bir projede ikisi yan yana durabilir: yüzde JavaScript, arkada Python. Birini öğrenmek ötekinin sözdizimini vermez. Fikir benzer olabilir, yazı ayrıdır.",
        "ببايثون تكتب نصاً وتمسك رقماً وتجهّز جواباً في الخادم. بجافاسكريبت تمسك عنصراً في الصفحة وتغيّر شيئاً حين يضغط المستخدم. المتصفح لا يشغّل بايثون بنفسه. وضع ملف .py في الصفحة لا يشغّل الزر. Node.js يُخرج جافاسكريبت من المتصفح، لكن وجه الصفحة يبقى عند HTML وجافاسكريبت. في مشروع واحد قد يقفان جنباً إلى جنب: جافاسكريبت في الوجه وبايثون في الخلف. تعلم واحدة لا يعطيك قواعد الأخرى. الفكرة قد تتشابه والكتابة منفصلة.",
        "На Python пишут скрипт, держат число и готовят ответ на сервере. На JavaScript держат элемент на странице и меняют что-то, когда пользователь нажимает. Браузер сам Python не запускает. Положить .py на страницу кнопку не запустит. Node.js выводит JavaScript из браузера, но лицо страницы всё равно держат HTML и JavaScript. В одном проекте оба могут стоять рядом: JavaScript на лице, Python сзади. Выучить один не даёт синтаксис другого. Мысль может быть похожей, запись разная.",
      ),
      hard: t(
        "Python-un ilk sətri asandır. JavaScript-in ilk düyməsi də asandır. Çətinlik seçimi qarışdırmaqdan gəlir. Səhifə üçün Python axtarmaq, hesab üçün isə yalnız brauzerə baxmaq adamı dolandırır. JavaScript-də eyni işin köhnə və yeni yazısı var. Python-da boşluq sətirin mənasını dəyişir. İkisində də kitabxana ayrıca quraşdırılır: pip və npm eyni şey deyil. Əvvəl birini bitir, sonra o birinə keç. İkisini eyni gündə qarışdırmaq ikisini də yavaşladır.",
        "Python's first line is easy. JavaScript's first button is easy too. The difficulty comes from mixing the choice. Looking for Python for a page, and looking only at the browser for a calculation, walks a person in circles. In JavaScript the same job has an old and a new way of writing. In Python a space changes the meaning of a line. In both, a library is installed separately: pip and npm are not the same thing. Finish one first, then move to the other. Mixing both on the same day slows both.",
        "Python’un ilk satırı kolaydır. JavaScript’in ilk düğmesi de kolaydır. Zorluk seçimi karıştırmaktan gelir. Sayfa için Python aramak, hesap için yalnız tarayıcıya bakmak insanı dolaştırır. JavaScript’te aynı işin eski ve yeni yazısı vardır. Python’da boşluk satırın anlamını değiştirir. İkisinde de kitaplık ayrı kurulur: pip ve npm aynı şey değildir. Önce birini bitir, sonra ötekine geç. İkisini aynı günde karıştırmak ikisini de yavaşlatır.",
        "السطر الأول في بايثون سهل. الزر الأول في جافاسكريبت سهل أيضاً. الصعوبة تأتي من خلط الاختيار. البحث عن بايثون لصفحة، والنظر إلى المتصفح فقط لحساب، يدوّخ الإنسان. في جافاسكريبت للعمل نفسه كتابة قديمة وجديدة. في بايثون المسافة تغيّر معنى السطر. في الاثنين تُثبَّت المكتبة وحدها: pip وnpm ليسا الشيء نفسه. أنهِ واحدة أولاً ثم انتقل إلى الأخرى. خلط الاثنين في اليوم نفسه يبطئ الاثنين.",
        "Первая строка Python легка. Первая кнопка JavaScript тоже легка. Трудность идёт от смешанного выбора. Искать Python для страницы и смотреть только в браузер для счёта — ходить кругами. В JavaScript у одной работы есть старая и новая запись. В Python пробел меняет смысл строки. В обоих библиотека ставится отдельно: pip и npm — не одно и то же. Сначала закончи один, потом переходи к другому. Мешать оба в один день замедляет оба.",
      ),
      balance: t(
        "Python oxunaqlıdır və məlumatda güclüdür. Səhifənin üzünü özü çəkmir. JavaScript səhifədə güclüdür. Brauzerdən kənarda Node lazımdır və yazı qaydaları daha qarışıq görünə bilər. Səhv seçim yoxdur. Səhv olan, səhifə istəyib Python faylı axtarmaqdır, ya da kiçik hesab üçün əvvəlcə böyük səhifə qurmağa çalışmaqdır.",
        "Python is readable and strong with data. It does not draw the face of a page by itself. JavaScript is strong on the page. Outside the browser it needs Node, and the writing rules can look more mixed. There is no wrong choice. The wrong thing is to want a page and look for a Python file, or to want a small calculation and try to build a large page first.",
        "Python okunaklıdır ve veride güçlüdür. Sayfanın yüzünü kendi çizmez. JavaScript sayfada güçlüdür. Tarayıcı dışında Node gerekir ve yazı kuralları daha karışık görünebilir. Yanlış seçim yoktur. Yanlış olan, sayfa isteyip Python dosyası aramaktır ya da küçük hesap için önce büyük sayfa kurmaya çalışmaktır.",
        "بايثون مقروءة وقوية في البيانات. لا ترسم وجه الصفحة بنفسها. جافاسكريبت قوية في الصفحة. خارج المتصفح تحتاج Node وقد تبدو قواعد الكتابة أخلط. لا يوجد اختيار خاطئ. الخطأ أن تريد صفحة فتبحث عن ملف بايثون، أو تريد حساباً صغيراً فتحاول بناء صفحة كبيرة أولاً.",
        "Python читаем и силён в данных. Лицо страницы сам не рисует. JavaScript силён на странице. Вне браузера нужен Node, и правила записи могут выглядеть запутаннее. Неверного выбора нет. Неверно хотеть страницу и искать файл Python, или хотеть маленький счёт и сначала строить большую страницу.",
      ),
      ideas: t(
        "Səhifədirsə JavaScript. Maşında kiçik işdirsə Python. İkisi də bir-birinin kitabxanasını işlətmir.",
        "If it is a page, JavaScript. If it is a small job on the machine, Python. Neither runs the other's library.",
        "Sayfaysa JavaScript. Makinede küçük işse Python. İkisi de diğerinin kitaplığını çalıştırmaz.",
        "إذا كانت صفحة فجافاسكريبت. إذا كان عملاً صغيراً على الجهاز فبايثون. لا واحد يشغّل مكتبة الآخر.",
        "Если это страница — JavaScript. Если маленькая работа на машине — Python. Ни один не запускает библиотеку другого.",
      ),
      ideaList: lines(
        ["Python-u brauzer özü işlətmir", "JavaScript düymə və səhifə üçündür", "Node JavaScript-i Python etmir", "pip Python üçündür, npm JavaScript üçündür"],
        ["The browser does not run Python by itself", "JavaScript is for a button and a page", "Node does not turn JavaScript into Python", "pip is for Python, npm is for JavaScript"],
        ["Tarayıcı Python’u kendi çalıştırmaz", "JavaScript düğme ve sayfa içindir", "Node, JavaScript’i Python yapmaz", "pip Python içindir, npm JavaScript içindir"],
        ["المتصفح لا يشغّل بايثون بنفسه", "جافاسكريبت للزر والصفحة", "Node لا يجعل جافاسكريبت بايثون", "pip لبايثون وnpm لجافاسكريبت"],
        ["Браузер сам Python не запускает", "JavaScript для кнопки и страницы", "Node не делает JavaScript языком Python", "pip для Python, npm для JavaScript"],
      ),
      sample: t(
        "İkisi də salam yazır. Yazı qaydası ayrıdır. Biri o biri ilə işləmir.",
        "Both write hello. The writing rule is separate. One does not run with the other.",
        "İkisi de merhaba yazar. Yazı kuralı ayrıdır. Biri diğeriyle çalışmaz.",
        "الاثنان يكتبان مرحبا. قاعدة الكتابة منفصلة. واحد لا يعمل مع الآخر.",
        "Оба пишут привет. Правило записи разное. Один с другим не запускается.",
      ),
      code: `# Python
print("salam")

// JavaScript
console.log("salam")`,
      faq: lines(
        ["Hansından başlayım? Səhifə və düymə istəyirsənsə, HTML-dən sonra JavaScript. Kiçik proqram və məlumat istəyirsənsə, Python.", "Node.js Python-u əvəz edir? Xeyr. Node JavaScript-i kompüterdə işlədir. Python-un kitabxanasını və yazısını vermir.", "İkisini bir saytda işlətmək olar? Bəli. Üzdə JavaScript, arxada Python dura bilər. Biri o birinin kodunu özü işlətmir."],
        ["Which one should I start with? If you want a page and a button, JavaScript after HTML. If you want a small program and data, Python.", "Does Node.js replace Python? No. Node runs JavaScript on a computer. It does not give Python's libraries or writing.", "Can both be used on one site? Yes. JavaScript can stand on the face and Python at the back. One does not run the other's code by itself."],
        ["Hangisinden başlayayım? Sayfa ve düğme istiyorsan HTML’den sonra JavaScript. Küçük program ve veri istiyorsan Python.", "Node.js Python’un yerini tutar mı? Hayır. Node, JavaScript’i bilgisayarda çalıştırır. Python’un kitaplığını ve yazısını vermez.", "İkisini bir sitede kullanmak olur mu? Evet. Yüzde JavaScript, arkada Python durabilir. Biri diğerinin kodunu kendi çalıştırmaz."],
        ["بأي واحدة أبدأ؟ إذا أردت صفحة وزرًا فجافاسكريبت بعد HTML. إذا أردت برنامجاً صغيراً وبيانات فبايثون.", "هل Node.js يحل محل بايثون؟ لا. Node يشغّل جافاسكريبت على الحاسوب. لا يعطي مكتبات بايثون ولا كتابتها.", "هل يُستعملان في موقع واحد؟ نعم. جافاسكريبت في الوجه وبايثون في الخلف. واحد لا يشغّل كود الآخر بنفسه."],
        ["С какого начать? Если нужны страница и кнопка — JavaScript после HTML. Если нужны маленькая программа и данные — Python.", "Node.js заменяет Python? Нет. Node запускает JavaScript на компьютере. Библиотеки и запись Python он не даёт.", "Можно использовать оба на одном сайте? Да. На лице может стоять JavaScript, сзади Python. Один сам код другого не запускает."],
      ),
    },
  ),
  topic(
    "localhost",
    "Localhost",
    t("Localhost nədir?", "What is localhost?", "Localhost nedir?", "ما هو localhost؟", "Что такое localhost?"),
    t(
      "Localhost sənin öz kompüterindir. Sayt orada açılır, amma internetdəki adam onu görmür. Hosting isə başqa maşındır. Sayt orada duranda başqası da açır. Domen isə həmin maşının adıdır.",
      "Localhost is your own computer. The site opens there, but a person on the internet does not see it. Hosting is another machine. When the site sits there, someone else opens it too. A domain is that machine's name.",
      "Localhost senin kendi bilgisayarındır. Site orada açılır, ama internetteki kişi onu görmez. Hosting başka makinedir. Site orada durunca başkası da açar. Alan adı ise o makinenin adıdır.",
      "Localhost هو حاسوبك أنت. الموقع يُفتح هناك لكن الشخص على الإنترنت لا يراه. الاستضافة جهاز آخر. حين يقف الموقع هناك يفتحه غيرك أيضاً. النطاق هو اسم ذلك الجهاز.",
      "Localhost — это твой собственный компьютер. Сайт открывается там, но человек в интернете его не видит. Хостинг — другая машина. Когда сайт стоит там, его открывает и другой. Домен — имя этой машины.",
    ),
    t(
      "localhost nədir, localhost:8080, hosting nədir, saytı internetə necə qoyum, domen nədir",
      "what is localhost, localhost:8080, what is hosting, how to put a site online, what is a domain",
      "localhost nedir, hosting nedir, siteyi internete nasıl koyarım, alan adı",
      "ما هو localhost, ما هي الاستضافة, كيف أضع الموقع على الإنترنت, ما هو النطاق",
      "что такое localhost, что такое хостинг, как выложить сайт в интернет, что такое домен",
    ),
    {
      what: t(
        "Localhost bir adır. O ad sənin maşınına qayıdır. Ünvan adətən http://localhost olur, yanında isə port durur: 8080, 3000 və ya 5173. Port qapı nömrəsidir. Eyni kompüterdə iki proqram eyni nömrəni götürə bilməz. Sən saytı bu ünvanda yoxlayırsan. Telefonundan başqa şəhərdəki dostun bu ünvanı açsa, sənin səhifən gəlmir, onun öz kompüteri gəlir. Çünki localhost heç vaxt sənin evindən çıxmır. Hosting bunun əksidir. O, gecə-gündüz işlək qalan və internet ünvanı olan maşındır. Fayllar ora köçür. Domen, məsələn nibrascode.com, həmin maşının yadda qalan adıdır. DNS adı ünvana bağlayır. Ad, maşın və sənin yoxlama ünvanın üç ayrı şeydir.",
        "Localhost is a name. That name comes back to your machine. The address is usually http://localhost, and a port stands beside it: 8080, 3000, or 5173. A port is a door number. Two programs on the same computer cannot take the same number. You check the site at this address. If a friend in another city opens this address from their phone, your page does not come. Their own computer comes. Because localhost never leaves your house. Hosting is the opposite. It is a machine that stays on day and night and has an internet address. The files move there. A domain, for example nibrascode.com, is the memorable name of that machine. DNS ties the name to the address. The name, the machine, and your test address are three separate things.",
        "Localhost bir addır. O ad senin makineye döner. Adres genellikle http://localhost olur, yanında ise port durur: 8080, 3000 veya 5173. Port kapı numarasıdır. Aynı bilgisayarda iki program aynı numarayı alamaz. Siteyi bu adreste yoklarsın. Başka şehirdeki arkadaşın telefondan bu adresi açarsa senin sayfan gelmez, onun kendi bilgisayarı gelir. Çünkü localhost hiç evinden çıkmaz. Hosting bunun tersidir. Gece gündüz açık kalan ve internet adresi olan makinedir. Dosyalar oraya taşınır. Alan adı, örneğin nibrascode.com, o makinenin akılda kalan adıdır. DNS adı adrese bağlar. Ad, makine ve senin deneme adresin üç ayrı şeydir.",
        "Localhost اسم. ذلك الاسم يرجع إلى جهازك. العنوان عادة http://localhost وبجانبه منفذ: 8080 أو 3000 أو 5173. المنفذ رقم باب. برنامجان على الحاسوب نفسه لا يأخذان الرقم نفسه. تفحص الموقع في هذا العنوان. إذا فتح صديق في مدينة أخرى هذا العنوان من هاتفه لا تأتي صفحتك. يأتي حاسوبه هو. لأن localhost لا يخرج من بيتك أبداً. الاستضافة عكس ذلك. هي جهاز يبقى شغالاً ليلاً ونهاراً وله عنوان على الإنترنت. الملفات تنتقل إليه. النطاق، مثل nibrascode.com، هو الاسم الذي يُحفظ لذلك الجهاز. DNS يربط الاسم بالعنوان. الاسم والجهاز وعنوان تجربتك ثلاثة أشياء منفصلة.",
        "Localhost — это имя. Это имя возвращается на твою машину. Адрес обычно http://localhost, а рядом стоит порт: 8080, 3000 или 5173. Порт — номер двери. Две программы на одном компьютере не могут взять один номер. Сайт проверяют по этому адресу. Если друг в другом городе откроет этот адрес с телефона, твоя страница не придёт. Придёт его собственный компьютер. Потому что localhost никогда не выходит из твоего дома. Хостинг — наоборот. Это машина, которая работает день и ночь и имеет адрес в интернете. Файлы переезжают туда. Домен, например nibrascode.com, — запоминающееся имя этой машины. DNS связывает имя с адресом. Имя, машина и твой проверочный адрес — три разные вещи.",
      ),
      uses: t(
        "Localhost yoxlamaq üçündür. Hosting başqasına göstərmək üçündür. Domen isə ünvanı adla dəyişir.",
        "Localhost is for checking. Hosting is for showing someone else. A domain replaces the address with a name.",
        "Localhost yoklamak içindir. Hosting başkasına göstermek içindir. Alan adı ise adresi adla değiştirir.",
        "Localhost للفحص. الاستضافة لتُظهر لغيرك. والنطاق يبدّل العنوان باسم.",
        "Localhost для проверки. Хостинг чтобы показать другому. Домен меняет адрес на имя.",
      ),
      useList: lines(
        ["Səhifəni yalnız özünde açmaq", "Düyməni internetə qoymadan yoxlamaq", "Hazır saytı gecə-gündüz işlək maşına qoymaq", "Uzun ünvanın yerinə ad almaq"],
        ["Opening a page only on your own machine", "Checking a button before putting it on the internet", "Putting a finished site on a machine that stays on", "Taking a name instead of a long address"],
        ["Sayfayı yalnız kendinde açmak", "Düğmeyi internete koymadan yoklamak", "Hazır siteyi gece gündüz açık makineye koymak", "Uzun adresin yerine ad almak"],
        ["فتح الصفحة على جهازك فقط", "فحص الزر قبل وضعه على الإنترنت", "وضع الموقع الجاهز على جهاز يبقى شغالاً", "أخذ اسم بدل العنوان الطويل"],
        ["Открыть страницу только у себя", "Проверить кнопку, не выкладывая в интернет", "Поставить готовый сайт на машину, которая не выключается", "Взять имя вместо длинного адреса"],
      ),
      can: t(
        "Localhost ilə səhifəni, düyməni və səhvi öz maşınında görürsən. Heç kim başqa evdən onu açmır. Hosting ilə faylı o maşına qoyursan və qapını internetə açarsan. Domen alıb DNS-də hosting ünvanına bağlayırsan. Ondan sonra adam adı yazır, sənin səhifən gəlir. Localhost-u dostuna göndərmək işləmir. 127.0.0.1 də eyni qapıdır, yenə sənin maşınındır. Saytı internetə qoymaq localhost-u kopyalamaq deyil. Fayl başqa maşına keçməli, ad da ora baxmalıdır.",
        "With localhost you see the page, the button, and the mistake on your own machine. Nobody opens it from another house. With hosting you put the file on that machine and open the door to the internet. You buy a domain and tie it to the hosting address in DNS. After that a person types the name and your page comes. Sending localhost to a friend does not work. 127.0.0.1 is the same door, still your machine. Putting a site on the internet is not copying localhost. The file has to move to another machine, and the name has to look there.",
        "Localhost ile sayfayı, düğmeyi ve hatayı kendi makinede görürsün. Başka evden kimse onu açmaz. Hosting ile dosyayı o makineye koyar ve kapıyı internete açarsın. Alan adı alıp DNS’te hosting adresine bağlarsın. Ondan sonra kişi adı yazar, senin sayfan gelir. Localhost’u arkadaşına göndermek çalışmaz. 127.0.0.1 de aynı kapıdır, yine senin makinedir. Siteyi internete koymak localhost’u kopyalamak değildir. Dosya başka makineye geçmeli, ad da oraya bakmalıdır.",
        "بـ localhost ترى الصفحة والزر والخطأ على جهازك. لا أحد يفتحه من بيت آخر. بالاستضافة تضع الملف على ذلك الجهاز وتفتح الباب للإنترنت. تشتري نطاقاً وتربطه بعنوان الاستضافة في DNS. بعد ذلك يكتب الشخص الاسم فتأتي صفحتك. إرسال localhost إلى صديق لا يعمل. 127.0.0.1 هو الباب نفسه، ما زال جهازك. وضع الموقع على الإنترنت ليس نسخ localhost. الملف يجب أن ينتقل إلى جهاز آخر والاسم يجب أن ينظر إلى هناك.",
        "На localhost ты видишь страницу, кнопку и ошибку на своей машине. Из другого дома её никто не откроет. На хостинге файл кладут на ту машину и открывают дверь в интернет. Покупают домен и в DNS привязывают его к адресу хостинга. После этого человек пишет имя, и приходит твоя страница. Послать localhost другу не работает. 127.0.0.1 — та же дверь, всё ещё твоя машина. Выложить сайт в интернет — не скопировать localhost. Файл должен перейти на другую машину, и имя должно смотреть туда.",
      ),
      hard: t(
        "Ünvanı açmaq asandır. Çətinlik üç şeyi qarışdırmaqdır. Localhost işləyirsə, sayt internetdədir demək deyil. Domen alınsa, fayl özü ora uçmur. Hosting ünvanı dəyişsə, DNS köhnə yerə baxa bilər və səhifə açılmır. Port məşğuldursa, proqram ikinci dəfə qalxmır. Başqa bir səhv: gizli açarı və ya yarımçıq səhvi localhost-da qoyub eyni qovluğu hostingə atmaq. Yoxlama yeri ilə insanların gördüyü yer eyni qayda ilə qorunmalıdır.",
        "Opening the address is easy. The difficulty is mixing three things. If localhost works, that does not mean the site is on the internet. If a domain is bought, the file does not fly there by itself. If the hosting address changes, DNS can still look at the old place and the page does not open. If the port is busy, the program does not rise a second time. Another mistake is to leave a secret key or a half-finished error on localhost and throw the same folder onto hosting. The test place and the place people see have to be kept with the same care.",
        "Adresi açmak kolaydır. Zorluk üç şeyi karıştırmaktır. Localhost çalışıyorsa site internettedir demek değildir. Alan adı alınsa dosya kendi oraya uçmaz. Hosting adresi değişirse DNS eski yere bakabilir ve sayfa açılmaz. Port doluysa program ikinci kez kalkmaz. Başka bir hata, gizli anahtarı veya yarım hatayı localhost’ta bırakıp aynı klasörü hostinge atmak. Deneme yeri ile insanların gördüğü yer aynı özenle korunmalıdır.",
        "فتح العنوان سهل. الصعوبة خلط ثلاثة أشياء. إذا عمل localhost فهذا لا يعني أن الموقع على الإنترنت. إذا اشترى النطاق فالملف لا يطير إلى هناك بنفسه. إذا تغير عنوان الاستضافة فقد ينظر DNS إلى المكان القديم ولا تُفتح الصفحة. إذا كان المنفذ مشغولاً لا يقوم البرنامج مرة ثانية. خطأ آخر: ترك مفتاح سري أو خطأ ناقص على localhost ورمي المجلد نفسه إلى الاستضافة. مكان الفحص والمكان الذي يراه الناس يجب أن يُحفظا بالعناية نفسها.",
        "Открыть адрес легко. Трудность — смешать три вещи. Если localhost работает, это не значит, что сайт в интернете. Если домен куплен, файл сам туда не улетает. Если адрес хостинга сменился, DNS может смотреть на старое место, и страница не открывается. Если порт занят, программа второй раз не поднимается. Другая ошибка — оставить секретный ключ или недоделанную ошибку на localhost и бросить ту же папку на хостинг. Место проверки и место, которое видят люди, надо беречь одинаково.",
      ),
      balance: t(
        "Localhost pulsuzdur və səhvi gizlədir. Onu başqası görmür, bu həm yaxşıdır, həm də paylaşmaq üçün kifayət etmir. Hosting başqasına yol açır, amma maşın, ad və qoruma sənə qalır. Domen gözəl ünvandır, faylın özü deyil. Əvvəl localhost-da düzəlt. Sonra faylı hostingə qoy. Ən sonda adı ora bağla.",
        "Localhost is free and hides a mistake. Someone else does not see it. That is good, and it is also not enough for sharing. Hosting opens a way for someone else, but the machine, the name, and the protection stay with you. A domain is a nice address, not the file itself. Fix it on localhost first. Then put the file on hosting. Tie the name there last.",
        "Localhost parasızdır ve hatayı gizler. Başkası onu görmez. Bu hem iyidir hem de paylaşmak için yetmez. Hosting başkasına yol açar, ama makine, ad ve koruma sende kalır. Alan adı güzel adrestir, dosyanın kendisi değildir. Önce localhost’ta düzelt. Sonra dosyayı hostinge koy. En sonda adı oraya bağla.",
        "Localhost بلا مال ويخفي الخطأ. غيرك لا يراه. هذا حسن وهو أيضاً لا يكفي للمشاركة. الاستضافة تفتح طريقاً لغيرك، لكن الجهاز والاسم والحماية تبقى عندك. النطاق عنوان جميل وليس الملف نفسه. أصلح أولاً على localhost. ثم ضع الملف على الاستضافة. وفي الأخير اربط الاسم هناك.",
        "Localhost бесплатный и прячет ошибку. Другой её не видит. Это и хорошо, и недостаточно, чтобы поделиться. Хостинг открывает путь другому, но машина, имя и защита остаются на тебе. Домен — красивый адрес, не сам файл. Сначала поправь на localhost. Потом положи файл на хостинг. Имя привяжи туда в конце.",
      ),
      ideas: t(
        "Üç söz: localhost sənin maşınındır, hosting başqa maşındır, domen isə addır.",
        "Three words: localhost is your machine, hosting is another machine, and a domain is a name.",
        "Üç söz: localhost senin makinedir, hosting başka makinedir, alan adı ise addır.",
        "ثلاث كلمات: localhost جهازك، والاستضافة جهاز آخر، والنطاق اسم.",
        "Три слова: localhost — твоя машина, хостинг — другая машина, а домен — имя.",
      ),
      ideaList: lines(
        ["localhost internetə çıxmır", "127.0.0.1 eyni qapıdır", "Port nömrədir, iki proqram bir nömrəni bölüşmür", "Domen fayl deyil, addır"],
        ["localhost does not go out to the internet", "127.0.0.1 is the same door", "A port is a number, two programs do not share one number", "A domain is not a file, it is a name"],
        ["localhost internete çıkmaz", "127.0.0.1 aynı kapıdır", "Port numaradır, iki program bir numarayı paylaşmaz", "Alan adı dosya değil, addır"],
        ["localhost لا يخرج إلى الإنترنت", "127.0.0.1 هو الباب نفسه", "المنفذ رقم، وبرنامجان لا يتقاسمان رقماً واحداً", "النطاق ليس ملفاً بل اسماً"],
        ["localhost в интернет не выходит", "127.0.0.1 — та же дверь", "Порт — это номер, две программы один номер не делят", "Домен — не файл, а имя"],
      ),
      sample: t(
        "Bu ünvan yalnız sənin kompüterindəki qapıdır. Dostuna göndərsən, onun kompüteri açılır.",
        "This address is only the door on your computer. If you send it to a friend, their computer opens.",
        "Bu adres yalnız senin bilgisayarındaki kapıdır. Arkadaşına gönderirsen onun bilgisayarı açılır.",
        "هذا العنوان باب على حاسوبك فقط. إذا أرسلته لصديق يُفتح حاسوبه.",
        "Этот адрес — дверь только на твоём компьютере. Если послать его другу, откроется его компьютер.",
      ),
      code: `http://localhost:8080
http://127.0.0.1:8080`,
      faq: lines(
        ["Localhost internetdə görünür? Xeyr. Yalnız sənin kompüterində açılır. Başqası eyni sözü yazsa, öz maşınını açır.", "Hosting ilə domen eynidir? Xeyr. Hosting maşındır. Domen addır. Ad DNS ilə maşına bağlanır.", "Saytı internetə necə qoyum? Əvvəl localhost-da düzəlt. Sonra faylı hosting maşınına qoy. Ən sonda domeni ora bağla."],
        ["Is localhost visible on the internet? No. It opens only on your computer. If someone else types the same word, they open their own machine.", "Are hosting and a domain the same? No. Hosting is a machine. A domain is a name. The name is tied to the machine with DNS.", "How do I put a site on the internet? Fix it on localhost first. Then put the file on the hosting machine. Tie the domain there last."],
        ["Localhost internette görünür mü? Hayır. Yalnız senin bilgisayarında açılır. Başkası aynı sözü yazarsa kendi makinesini açar.", "Hosting ile alan adı aynı mı? Hayır. Hosting makinedir. Alan adı addır. Ad, DNS ile makineye bağlanır.", "Siteyi internete nasıl koyarım? Önce localhost’ta düzelt. Sonra dosyayı hosting makinesine koy. En sonda alan adını oraya bağla."],
        ["هل يظهر localhost على الإنترنت؟ لا. يُفتح فقط على حاسوبك. إذا كتب غيرك الكلمة نفسها يفتح جهازه هو.", "هل الاستضافة والنطاق الشيء نفسه؟ لا. الاستضافة جهاز. النطاق اسم. الاسم يُربط بالجهاز عبر DNS.", "كيف أضع الموقع على الإنترنت؟ أصلح أولاً على localhost. ثم ضع الملف على جهاز الاستضافة. وفي الأخير اربط النطاق هناك."],
        ["Localhost виден в интернете? Нет. Он открывается только на твоём компьютере. Если другой напишет то же слово, откроется его машина.", "Хостинг и домен — одно и то же? Нет. Хостинг — машина. Домен — имя. Имя связывают с машиной через DNS.", "Как выложить сайт в интернет? Сначала поправь на localhost. Потом положить файл на машину хостинга. Домен привяжи туда в конце."],
      ),
    },
  ),
];
