import type { StackPage } from "@/lib/stack-pages";
import { lines, t, topic } from "@/lib/stack-pages";

export const STACK_TRIO: readonly StackPage[] = [
  topic(
    "maven",
    "Maven",
    t("Maven nədir?", "What is Maven?", "Maven nedir?", "ما هو Maven؟", "Что такое Maven?"),
    t(
      "Maven Java layihəsini quran və kitabxanasını gətirən alətdir. Java-nın özü deyil. Gradle da qurur, amma Maven-in özü deyil.",
      "Maven is the tool that builds a Java project and brings its library. It is not Java itself. Gradle also builds, but it is not Maven.",
      "Maven, Java projesini kuran ve kütüphanesini getiren araçtır. Java’nın kendisi değildir. Gradle da kurar, ama Maven’in kendisi değildir.",
      "Maven الأداة التي تبني مشروع Java وتجلب مكتبته. ليس Java نفسه. Gradle يبني أيضاً لكنه ليس Maven.",
      "Maven — инструмент, который собирает проект Java и приносит его библиотеку. Это не сам Java. Gradle тоже собирает, но это не Maven.",
    ),
    t("Maven nədir, pom.xml, Java qurma, Gradle", "what is Maven, pom.xml, Java build, Gradle", "Maven nedir, pom.xml, Java kurma", "ما هو Maven, pom.xml, Gradle", "что такое Maven, pom.xml, Gradle"),
    {
      what: t(
        "Maven-i Jason van Zyl yazılıb. Apache Maven 1.0 2004-cü ildə çıxıb. Layihənin siyahısı pom.xml faylındadır. Bu ad Project Object Model deməkdir. Maven Central kitabxanaların ümumi yeridir. mvn compile kodu yoxlayıb sinif faylına çevirir. mvn package hazır arxivi çıxarır. Java dili qaydanı deyir. Maven həmin qaydanı işlətməyi sıraya qoyur. Gradle də Java qurur, amma siyahını skriptlə yazır. Maven siyahını pom.xml-də sabit quruluşla saxlayır.",
        "Jason van Zyl wrote Maven. Apache Maven 1.0 came out in 2004. The project's list is in the pom.xml file. This name means Project Object Model. Maven Central is the shared place of libraries. mvn compile checks the code and turns it into a class file. mvn package produces the finished archive. The Java language says the rule. Maven lines up the work of using that rule. Gradle also builds Java, but it writes the list as a script. Maven keeps the list in pom.xml with a fixed shape.",
        "Maven’i Jason van Zyl yazdı. Apache Maven 1.0 2004’te çıktı. Projenin listesi pom.xml dosyasındadır. Bu ad Project Object Model demektir. Maven Central kütüphanelerin ortak yeridir. mvn compile kodu denetleyip sınıf dosyasına çevirir. mvn package hazır arşivi çıkarır. Java dili kuralı söyler. Maven o kuralı kullanmayı sıraya koyar. Gradle da Java kurar, ama listeyi betikle yazar. Maven listeyi pom.xml içinde sabit kuruluşla tutar.",
        "كتب Maven Jason van Zyl. خرج Apache Maven 1.0 سنة 2004. قائمة المشروع في ملف pom.xml. هذا الاسم يعني Project Object Model. Maven Central المكان المشترك للمكتبات. mvn compile يفحص الكود ويحوّله إلى ملف صنف. mvn package يخرج الأرشيف الجاهز. لغة Java تقول القاعدة. Maven يرتب عمل استخدام تلك القاعدة. Gradle يبني Java أيضاً لكنه يكتب القائمة كسكربت. Maven يحفظ القائمة في pom.xml بشكل ثابت.",
        "Maven написал Jason van Zyl. Apache Maven 1.0 вышел в 2004 году. Список проекта лежит в файле pom.xml. Это имя значит Project Object Model. Maven Central — общее место библиотек. mvn compile проверяет код и переводит его в файл класса. mvn package выдаёт готовый архив. Язык Java говорит правило. Maven выстраивает работу по этому правилу. Gradle тоже собирает Java, но список пишет скриптом. Maven хранит список в pom.xml в фиксированном виде.",
      ),
      uses: t(
        "Maven Java layihəsini eyni addımlarla qurmaq və kitabxananı bir siyahıdan gətirmək üçündür.",
        "Maven is for building a Java project with the same steps and bringing a library from one list.",
        "Maven Java projesini aynı adımlarla kurmak ve kütüphaneyi bir listeden getirmek içindir.",
        "Maven لبناء مشروع Java بالخطوات نفسها وجلب مكتبة من قائمة واحدة.",
        "Maven нужен, чтобы собирать проект Java одними и теми же шагами и приносить библиотеку из одного списка.",
      ),
      useList: lines(
        ["Kodu sinif faylına çevirmək", "Testi mvn test ilə açmaq", "Kitabxananı pom.xml-ə yazmaq", "Hazır jar arxivini çıxarmaq"],
        ["Turning code into a class file", "Opening the test with mvn test", "Writing a library into pom.xml", "Producing a finished jar archive"],
        ["Kodu sınıf dosyasına çevirmek", "Testi mvn test ile açmak", "Kütüphaneyi pom.xml içine yazmak", "Hazır jar arşivini çıkarmak"],
        ["تحويل الكود إلى ملف صنف", "فتح الاختبار بـ mvn test", "كتابة مكتبة في pom.xml", "إخراج أرشيف jar جاهز"],
        ["Перевести код в файл класса", "Открыть тест через mvn test", "Записать библиотеку в pom.xml", "Выдать готовый архив jar"],
      ),
      can: t(
        "Maven ilə asılılığı endirir, testi işlədir və arxivi qurursan. O, Java proqramını özü yazmır. Səhv Java versiyası olanda qurma dayanır. Tanımadığın kitabxana sənin layihənin içinə girir. Gradle faylını Maven oxumur.",
        "With Maven you download a dependency, run the test, and build the archive. It does not write the Java program itself. When the Java version is wrong, the build stops. A library you do not know enters your project. Maven does not read a Gradle file.",
        "Maven ile bağımlılığı indirir, testi çalıştırır ve arşivi kurarsın. Java programını kendi yazmaz. Java sürümü yanlışsa kurma durur. Tanımadığın kütüphane senin projenin içine girer. Maven, Gradle dosyasını okumaz.",
        "بـ Maven تنزّل اعتماداً وتشغّل الاختبار وتبني الأرشيف. هو لا يكتب برنامج Java نفسه. إذا أخطأت نسخة Java يتوقف البناء. مكتبة لا تعرفها تدخل مشروعك. Maven لا يقرأ ملف Gradle.",
        "Через Maven скачивают зависимость, запускают тест и собирают архив. Сам он программу на Java не пишет. Если версия Java неверна, сборка останавливается. Незнакомая библиотека входит в твой проект. Файл Gradle Maven не читает.",
      ),
      hard: t(
        "Boş layihədə bir əmr asandır. Çətinlik versiya və anbardadır. İki kitabxana eyni adı fərqli versiya ilə istəyə bilər. pom.xml böyüyəndə hansı sətrin nə gətirdiyi itir. Lokal anbar köhnə faylı saxlayır və yeni yükləməni gizlədə bilər. Şəbəkə bağlı deyilsə Central-dan paket gəlmir.",
        "One command in an empty project is easy. The difficulty is the version and the repository. Two libraries may want the same name at a different version. When pom.xml grows, it gets lost which line brings what. The local repository keeps an old file and can hide a new download. If the network is down, a package does not come from Central.",
        "Boş projede bir komut kolaydır. Zorluk sürüm ve depodadır. İki kütüphane aynı adı farklı sürümle isteyebilir. pom.xml büyüyünce hangi satırın ne getirdiği kaybolur. Yerel depo eski dosyayı tutar ve yeni indirmeyi gizleyebilir. Ağ kapalıysa Central’dan paket gelmez.",
        "أمر واحد في مشروع فارغ سهل. الصعوبة في النسخة والمستودع. قد تطلب مكتبتان الاسم نفسه بنسخة مختلفة. حين يكبر pom.xml يضيع أي سطر يجلب ماذا. المستودع المحلي يحفظ ملفاً قديماً وقد يخفي تنزيلاً جديداً. إذا انقطعت الشبكة لا تأتي حزمة من Central.",
        "Одна команда в пустом проекте легка. Трудность в версии и в хранилище. Две библиотеки могут хотеть одно имя в разной версии. Когда pom.xml растёт, теряется, какая строка что приносит. Локальное хранилище держит старый файл и может спрятать новую загрузку. Если сети нет, пакет из Central не приходит.",
      ),
      balance: t(
        "Üstünlük: addımlar tanışdır, siyahı bir fayldadır, eyni qurma başqa maşında təkrarlanır. Məhdudiyyət: pom.xml uzun olur. Maven Java deyil və Gradle deyil.",
        "Advantage: the steps are familiar, the list is in one file, and the same build repeats on another machine. Limit: pom.xml becomes long. Maven is not Java and it is not Gradle.",
        "Avantaj: adımlar tanıdıktır, liste bir dosyadadır, aynı kurma başka makinede tekrarlanır. Sınır: pom.xml uzun olur. Maven, Java değildir ve Gradle değildir.",
        "الميزة: الخطوات مألوفة والقائمة في ملف واحد والبناء نفسه يتكرر على جهاز آخر. الحد: pom.xml يطول. Maven ليس Java وليس Gradle.",
        "Плюс: шаги знакомые, список в одном файле, та же сборка повторяется на другой машине. Ограничение: pom.xml становится длинным. Maven — не Java и не Gradle.",
      ),
      ideas: t(
        "pom.xml siyahıdır. Asılılıq gətirilən kitabxanadır. Hədəf isə bir qurma addımının adıdır.",
        "pom.xml is the list. A dependency is a library that is brought in. A goal is the name of one build step.",
        "pom.xml listedir. Bağımlılık getirilen kütüphanedir. Hedef ise bir kurma adımının adıdır.",
        "pom.xml القائمة. الاعتماد مكتبة تُجلب. الهدف اسم خطوة بناء واحدة.",
        "pom.xml — список. Зависимость — библиотека, которую приносят. Цель — имя одного шага сборки.",
      ),
      ideaList: lines(
        ["compile kodu çevirir", "test yoxlamanı işlədir", "package arxivi çıxarır", "Maven Central ümumi yerdir"],
        ["compile translates the code", "test runs the check", "package produces the archive", "Maven Central is the shared place"],
        ["compile kodu çevirir", "test denetimi çalıştırır", "package arşivi çıkarır", "Maven Central ortak yerdir"],
        ["compile يترجم الكود", "test يشغّل الفحص", "package يخرج الأرشيف", "Maven Central المكان المشترك"],
        ["compile переводит код", "test запускает проверку", "package выдаёт архив", "Maven Central — общее место"],
      ),
      sample: t(
        "Bu əmr hazırkı qovluqdakı Java layihəsini paketləyir. Kodu özü yazmır.",
        "This command packages the Java project in the current folder. It does not write the code itself.",
        "Bu komut bulunduğun klasördeki Java projesini paketler. Kodu kendi yazmaz.",
        "هذا الأمر يحزّم مشروع Java في المجلد الحالي. لا يكتب الكود نفسه.",
        "Эта команда упаковывает проект Java в текущей папке. Сам код она не пишет.",
      ),
      code: `mvn package`,
      faq: lines(
        ["Maven və Java eynidir? Xeyr. Java dili işlədir. Maven layihəni qurur və kitabxananı gətirir.", "Maven və Gradle eynidir? Xeyr. İkisi də Java qura bilər. Maven siyahını pom.xml-də saxlayır. Gradle siyahını skriptlə yazır.", "pom.xml proqramın özüdür? Xeyr. O, ad və kitabxana siyahısıdır."],
        ["Are Maven and Java the same? No. Java runs the language. Maven builds the project and brings the library.", "Are Maven and Gradle the same? No. Both can build Java. Maven keeps the list in pom.xml. Gradle writes the list as a script.", "Is pom.xml the program itself? No. It is the name and the library list."],
        ["Maven ve Java aynı mı? Hayır. Java dili çalıştırır. Maven projeyi kurar ve kütüphaneyi getirir.", "Maven ve Gradle aynı mı? Hayır. İkisi de Java kurabilir. Maven listeyi pom.xml içinde tutar. Gradle listeyi betikle yazar.", "pom.xml programın kendisi mi? Hayır. O, ad ve kütüphane listesidir."],
        ["هل Maven وJava الشيء نفسه؟ لا. Java تشغّل اللغة. Maven يبني المشروع ويجلب المكتبة.", "هل Maven وGradle الشيء نفسه؟ لا. كلاهما يقدر أن يبني Java. Maven يحفظ القائمة في pom.xml. Gradle يكتب القائمة كسكربت.", "هل pom.xml هو البرنامج نفسه؟ لا. هو الاسم وقائمة المكتبات."],
        ["Maven и Java — одно и то же? Нет. Java выполняет язык. Maven собирает проект и приносит библиотеку.", "Maven и Gradle — одно и то же? Нет. Оба могут собирать Java. Maven хранит список в pom.xml. Gradle пишет список скриптом.", "pom.xml — это сама программа? Нет. Это имя и список библиотек."],
      ),
    },
  ),
  topic(
    "yaml",
    "YAML",
    t("YAML nədir?", "What is YAML?", "YAML nedir?", "ما هو YAML؟", "Что такое YAML?"),
    t(
      "YAML ayarı sətir və boşluqla yazan formatdır. Proqramlaşdırma dili deyil. JSON mötərizə işlədir, YAML isə girintiyə baxır.",
      "YAML is a format that writes a setting with lines and spaces. It is not a programming language. JSON uses braces, and YAML looks at the indent.",
      "YAML, ayarı satır ve boşlukla yazan formattır. Programlama dili değildir. JSON parantez kullanır, YAML ise girintiye bakar.",
      "YAML صيغة تكتب الإعداد بأسطر ومسافات. ليست لغة برمجة. JSON يستخدم الأقواس وYAML ينظر إلى الإزاحة.",
      "YAML — формат, который пишет настройку строками и пробелами. Это не язык программирования. JSON использует скобки, а YAML смотрит на отступ.",
    ),
    t("YAML nədir, YAML girinti, JSON, ayar faylı", "what is YAML, YAML indent, JSON, config file", "YAML nedir, YAML girinti, JSON", "ما هو YAML, إزاحة YAML, JSON", "что такое YAML, отступ YAML, JSON"),
    {
      what: t(
        "YAML-ı Clark Evans 2001-ci ildə təklif edib. Ingy döt Net və Oren Ben-Kiki də ilk müəlliflərdəndir. Adı «YAML Ain't Markup Language» deməkdir. Əvvəl «Yet Another Markup Language» sayılıb, sonra işarələmə dili olmadığını demək üçün dəyişib. Açar və qiymət iki nöqtə ilə ayrılır. Siyahı tire ilə başlayır. Eyni blokun sətirləri eyni sayda boşluqla girir. Tab boşluq yerinə işlənmir. Docker Compose, GitHub Actions və bir çox server ayarı bu faylı oxuyur. Fayl özü heç nə işlətmir. Onu oxuyan proqram işlədir.",
        "Clark Evans proposed YAML in 2001. Ingy döt Net and Oren Ben-Kiki are also among the first authors. The name means YAML Ain't Markup Language. It was first counted as Yet Another Markup Language, then changed to say it is not a markup language. A key and a value are split by a colon. A list starts with a dash. The lines of the same block indent with the same number of spaces. A tab is not used in place of a space. Docker Compose, GitHub Actions, and many server settings read this file. The file itself runs nothing. The program that reads it does the work.",
        "YAML’ı Clark Evans 2001’de önerdi. Ingy döt Net ve Oren Ben-Kiki de ilk yazarlardandır. Adı «YAML Ain't Markup Language» demektir. Önce «Yet Another Markup Language» sayıldı, sonra işaretleme dili olmadığını söylemek için değişti. Anahtar ve değer iki nokta ile ayrılır. Liste tire ile başlar. Aynı bloğun satırları aynı sayıda boşlukla girer. Sekme boşluk yerine kullanılmaz. Docker Compose, GitHub Actions ve birçok sunucu ayarı bu dosyayı okur. Dosyanın kendisi hiçbir şey çalıştırmaz. Onu okuyan program çalıştırır.",
        "اقترح Clark Evans صيغة YAML سنة 2001. Ingy döt Net وOren Ben-Kiki أيضاً من أوائل الكتّاب. الاسم يعني YAML Ain't Markup Language. حُسبت أولاً Yet Another Markup Language ثم تغيّرت لتقول إنها ليست لغة ترميز. المفتاح والقيمة يفصل بينهما نقطتان. القائمة تبدأ بشرطة. أسطر الكتلة نفسها تُزاح بعدد المسافات نفسه. الجدولة لا تُستخدم مكان المسافة. Docker Compose وGitHub Actions وكثير من إعدادات الخادم تقرأ هذا الملف. الملف نفسه لا يشغّل شيئاً. البرنامج الذي يقرأه يعمل.",
        "YAML предложил Clark Evans в 2001 году. Ingy döt Net и Oren Ben-Kiki тоже среди первых авторов. Имя значит YAML Ain't Markup Language. Сначала это считалось Yet Another Markup Language, потом название изменили, чтобы сказать, что это не язык разметки. Ключ и значение разделяет двоеточие. Список начинается с тире. Строки одного блока отступают одним числом пробелов. Таб вместо пробела не используют. Docker Compose, GitHub Actions и многие настройки сервера читают этот файл. Сам файл ничего не запускает. Работает программа, которая его читает.",
      ),
      uses: t(
        "YAML adamın oxuya biləcəyi ayar üçündür. Siyahı, ad və qiymət bir faylda durur.",
        "YAML is for a setting a person can read. A list, a name, and a value stay in one file.",
        "YAML insanın okuyabildiği ayar içindir. Liste, ad ve değer bir dosyada durur.",
        "YAML لإعداد يستطيع الإنسان قراءته. القائمة والاسم والقيمة تقف في ملف واحد.",
        "YAML нужен для настройки, которую человек может прочитать. Список, имя и значение лежат в одном файле.",
      ),
      useList: lines(
        ["Serverin portunu və adını yazmaq", "Bir neçə addımlı işin siyahısını saxlamaq", "Docker xidmətlərinin ayarını yazmaq", "Eyni açarı bir neçə mühitdə dəyişmək"],
        ["Writing a server's port and name", "Keeping the list of a job with several steps", "Writing the setting of Docker services", "Changing the same key in several environments"],
        ["Sunucunun portunu ve adını yazmak", "Birkaç adımlı işin listesini tutmak", "Docker hizmetlerinin ayarını yazmak", "Aynı anahtarı birkaç ortamda değiştirmek"],
        ["كتابة منفذ الخادم واسمه", "حفظ قائمة عمل ذي عدة خطوات", "كتابة إعداد خدمات Docker", "تغيير المفتاح نفسه في عدة بيئات"],
        ["Записать порт и имя сервера", "Хранить список работы из нескольких шагов", "Записать настройку служб Docker", "Менять один ключ в нескольких средах"],
      ),
      can: t(
        "YAML ilə açar, siyahı və iç-içə blok yazırsan. O, hesab işlətmir və səhifə çəkmir. Proqram faylı öz qaydası ilə oxumalıdır. Səhv girinti başqa bloku içinə salır və proqram başqa ayar görür. Parolu bu fayla repoya qoymaq olmaz.",
        "With YAML you write a key, a list, and a nested block. It does not run a calculation and it does not draw a page. The program must read the file by its own rule. A wrong indent pulls another block inside, and the program sees another setting. Do not put a password in this file into the repo.",
        "YAML ile anahtar, liste ve iç içe blok yazarsın. Hesap çalıştırmaz ve sayfa çizmez. Program dosyayı kendi kuralıyla okumalıdır. Yanlış girinti başka bloğu içine alır ve program başka ayar görür. Parolayı bu dosyayla depoya koymamak gerekir.",
        "بـ YAML تكتب مفتاحاً وقائمة وكتلة داخل كتلة. لا يشغّل حساباً ولا يرسم صفحة. يجب أن يقرأ البرنامج الملف بقاعدته. الإزاحة الخطأ تسحب كتلة أخرى إلى الداخل فيرى البرنامج إعداداً آخر. لا تضع كلمة مرور في هذا الملف داخل المستودع.",
        "В YAML пишут ключ, список и вложенный блок. Он не считает и страницу не рисует. Программа должна читать файл по своему правилу. Неверный отступ втягивает другой блок внутрь, и программа видит другую настройку. Пароль этим файлом в репозиторий не кладут.",
      ),
      hard: t(
        "İki sətir yazmaq asandır. Çətinlik boşluq sayındadır. Bir sətir az və ya çox girəndə blok sınırır. Tab və boşluq qarışanda oxuyan proqram dayanır. Eyni söz bəzən mətn, bəzən doğru-yanlış və bəzən rəqəm sayılır. Bunu istəmədən buraxmaq ayarı dəyişir. JSON-da mötərizə bağlanmayan yeri göstərir. YAML-da səhv daha sakitdir.",
        "Writing two lines is easy. The difficulty is the number of spaces. When one line indents too little or too much, the block breaks. When a tab and a space mix, the program that reads it stops. The same word is sometimes counted as text, sometimes as true or false, and sometimes as a number. Leaving that by accident changes the setting. In JSON a brace shows the place that did not close. In YAML the mistake is quieter.",
        "İki satır yazmak kolaydır. Zorluk boşluk sayısındadır. Bir satır az veya çok girince blok bozulur. Sekme ve boşluk karışınca okuyan program durur. Aynı söz bazen metin, bazen doğru-yanlış, bazen sayı sayılır. Bunu istemeden bırakmak ayarı değiştirir. JSON’da kapanmayan yeri parantez gösterir. YAML’da hata daha sessizdir.",
        "كتابة سطرين سهلة. الصعوبة في عدد المسافات. حين يُزاح سطر أقل أو أكثر تنكسر الكتلة. إذا اختلطت الجدولة والمسافة يتوقف البرنامج الذي يقرأ. الكلمة نفسها تُحسب أحياناً نصاً وأحياناً صح أو خطأ وأحياناً رقماً. ترك ذلك بلا قصد يغيّر الإعداد. في JSON يُظهر القوس المكان الذي لم يُغلق. في YAML الخطأ أهدأ.",
        "Написать две строки легко. Трудность в числе пробелов. Когда одна строка отступает меньше или больше, блок ломается. Если смешать таб и пробел, читающая программа останавливается. Одно и то же слово иногда считается текстом, иногда правдой или ложью, иногда числом. Если оставить это случайно, настройка меняется. В JSON скобка показывает место, которое не закрылось. В YAML ошибка тише.",
      ),
      balance: t(
        "Üstünlük: fayl qısa oxunur, şərh yazılır, siyahı tiresiz JSON-dan sakit görünür. Məhdudiyyət: girinti səhvi başqa məna verir. YAML JSON deyil və proqram deyil.",
        "Advantage: the file reads short, a comment can be written, and a list looks quieter than JSON. Limit: an indent mistake gives another meaning. YAML is not JSON and it is not a program.",
        "Avantaj: dosya kısa okunur, yorum yazılır, liste JSON’dan sakin görünür. Sınır: girinti hatası başka anlam verir. YAML, JSON değildir ve program değildir.",
        "الميزة: الملف يُقرأ قصيراً ويُكتب تعليق والقائمة تبدو أهدأ من JSON. الحد: خطأ الإزاحة يعطي معنى آخر. YAML ليس JSON وليس برنامجاً.",
        "Плюс: файл читается коротко, можно писать комментарий, список выглядит тише JSON. Ограничение: ошибка отступа даёт другой смысл. YAML — не JSON и не программа.",
      ),
      ideas: t(
        "Açar addır. Qiymət həmin ada yazılandır. Girinti hansı blokun içində olduğunu deyir.",
        "A key is a name. A value is what is written to that name. The indent says which block it is inside.",
        "Anahtar addır. Değer o ada yazılandır. Girinti hangi bloğun içinde olduğunu söyler.",
        "المفتاح اسم. القيمة ما يُكتب لذلك الاسم. الإزاحة تقول داخل أي كتلة هو.",
        "Ключ — имя. Значение — то, что написано этому имени. Отступ говорит, внутри какого блока это лежит.",
      ),
      ideaList: lines(
        ["İki nöqtə açarı qiymətdən ayırır", "Tire siyahı maddəsidir", "Boşluq sayılır, tab yox", "Faylın özü proqram işlətmir"],
        ["A colon splits a key from a value", "A dash is a list item", "A space counts, a tab does not", "The file itself does not run a program"],
        ["İki nokta anahtarı değerden ayırır", "Tire liste maddesidir", "Boşluk sayılır, sekme değil", "Dosyanın kendisi program çalıştırmaz"],
        ["النقطتان تفصلان المفتاح عن القيمة", "الشرطة بند قائمة", "المسافة تُحسب والجدولة لا", "الملف نفسه لا يشغّل برنامجاً"],
        ["Двоеточие отделяет ключ от значения", "Тире — пункт списка", "Пробел считается, таб нет", "Сам файл программу не запускает"],
      ),
      sample: t(
        "Bu, bir serverin adını və portunu yazır. Proqramı işə salmır.",
        "This writes a server's name and port. It does not start the program.",
        "Bu, bir sunucunun adını ve portunu yazar. Programı başlatmaz.",
        "هذا يكتب اسم خادم ومنفذه. لا يشغّل البرنامج.",
        "Это пишет имя сервера и его порт. Программу не запускает.",
      ),
      code: `name: nibras
port: 8080`,
      faq: lines(
        ["YAML və JSON eynidir? Xeyr. İkisi də ayar saxlaya bilər. JSON mötərizə işlədir. YAML girinti işlədir və şərh yazılır.", "YAML proqramlaşdırma dilidir? Xeyr. Faylı oxuyan proqram işi görür. YAML özü heç nə işlətmir.", "Tab ilə girinti olar? Xeyr. Girinti boşluqla yazılır. Tab oxuyanı dayandıra bilər."],
        ["Are YAML and JSON the same? No. Both can keep a setting. JSON uses braces. YAML uses indent, and a comment can be written.", "Is YAML a programming language? No. The program that reads the file does the work. YAML itself runs nothing.", "Can indent be a tab? No. Indent is written with spaces. A tab can stop the reader."],
        ["YAML ve JSON aynı mı? Hayır. İkisi de ayar tutabilir. JSON parantez kullanır. YAML girinti kullanır ve yorum yazılır.", "YAML programlama dili mi? Hayır. Dosyayı okuyan program işi görür. YAML kendi hiçbir şey çalıştırmaz.", "Girinti sekme ile olur mu? Hayır. Girinti boşlukla yazılır. Sekme okuyanı durdurabilir."],
        ["هل YAML وJSON الشيء نفسه؟ لا. كلاهما يقدر أن يحفظ إعداداً. JSON يستخدم الأقواس. YAML يستخدم الإزاحة ويُكتب تعليق.", "هل YAML لغة برمجة؟ لا. البرنامج الذي يقرأ الملف يقوم بالعمل. YAML نفسه لا يشغّل شيئاً.", "هل تكون الإزاحة جدولة؟ لا. الإزاحة تُكتب بمسافات. الجدولة قد توقف القارئ."],
        ["YAML и JSON — одно и то же? Нет. Оба могут хранить настройку. JSON использует скобки. YAML использует отступ, и можно писать комментарий.", "YAML — язык программирования? Нет. Работу делает программа, которая читает файл. Сам YAML ничего не запускает.", "Отступ может быть табом? Нет. Отступ пишут пробелами. Таб может остановить читателя."],
      ),
    },
  ),
  topic(
    "systemd",
    "systemd",
    t("systemd nədir?", "What is systemd?", "systemd nedir?", "ما هو systemd؟", "Что такое systemd?"),
    t(
      "systemd Linux-da xidməti açan və bağlayan alətdir. Nüvə deyil. cron vaxtı çatanda əmr çağırır, systemd isə xidmətin özünü idarə edir.",
      "systemd is the tool that starts and stops a service on Linux. It is not the kernel. cron calls a command when the time comes, and systemd manages the service itself.",
      "systemd, Linux’ta hizmeti açan ve kapatan araçtır. Çekirdek değildir. cron vakti gelince komut çağırır, systemd ise hizmetin kendisini yönetir.",
      "systemd الأداة التي تفتح خدمة وتغلقها على Linux. ليس النواة. cron يستدعي أمراً حين يأتي الوقت وsystemd يدير الخدمة نفسها.",
      "systemd — инструмент, который открывает и закрывает службу в Linux. Это не ядро. cron вызывает команду, когда приходит время, а systemd управляет самой службой.",
    ),
    t("systemd nədir, systemctl, Linux xidmət, unit", "what is systemd, systemctl, Linux service, unit", "systemd nedir, systemctl, Linux hizmet", "ما هو systemd, systemctl, خدمة", "что такое systemd, systemctl, служба"),
    {
      what: t(
        "systemd-i Lennart Poettering və Kay Sievers yazılıb. İlk buraxılış 2010-cu ildir. Bir çox Linux paylanğıcı açılışda onu işə salır. Ubuntu da onlardandır. Hər xidmətin unit faylı var. Ən çox görülən sonluq .service-dir. systemctl start xidməti indi açır. systemctl enable onu növbəti açılışa bağlayır. Bu ikisi eyni deyil. Jurnalı journalctl göstərir. Nüvə dəmirlə danışır. systemd isə nüvə açıldıqdan sonra xidmətlərin sırasını saxlayır. Alpine kimi bəzi sistemlər onu işlətmir.",
        "Lennart Poettering and Kay Sievers wrote systemd. The first release was in 2010. Many Linux distributions start it at boot. Ubuntu is one of them. Each service has a unit file. The ending seen most is .service. systemctl start opens the service now. systemctl enable ties it to the next boot. These two are not the same. journalctl shows the log. The kernel talks to the hardware. systemd keeps the order of services after the kernel has started. Some systems, such as Alpine, do not use it.",
        "systemd’i Lennart Poettering ve Kay Sievers yazdı. İlk yayın 2010’dur. Birçok Linux dağıtımı açılışta onu başlatır. Ubuntu da onlardandır. Her hizmetin unit dosyası vardır. En çok görülen son .service’tir. systemctl start hizmeti şimdi açar. systemctl enable onu sonraki açılışa bağlar. Bu ikisi aynı değildir. Günlüğü journalctl gösterir. Çekirdek donanımla konuşur. systemd ise çekirdek açıldıktan sonra hizmetlerin sırasını tutar. Alpine gibi bazı sistemler onu kullanmaz.",
        "كتب systemd كل من Lennart Poettering وKay Sievers. أول إصدار سنة 2010. كثير من توزيعات Linux تشغّله عند الإقلاع. Ubuntu واحدة منها. لكل خدمة ملف unit. اللاحقة الأكثر هي .service. systemctl start يفتح الخدمة الآن. systemctl enable يربطها بالإقلاع التالي. هذان ليسا الشيء نفسه. journalctl يُظهر السجل. النواة تتكلم مع العتاد. systemd يحفظ ترتيب الخدمات بعد أن تبدأ النواة. بعض الأنظمة مثل Alpine لا تستخدمه.",
        "systemd написали Lennart Poettering и Kay Sievers. Первый выпуск был в 2010 году. Многие дистрибутивы Linux запускают его при загрузке. Ubuntu среди них. У каждой службы есть файл unit. Чаще всего окончание .service. systemctl start открывает службу сейчас. systemctl enable привязывает её к следующей загрузке. Это не одно и то же. Журнал показывает journalctl. Ядро говорит с железом. systemd держит порядок служб после того, как ядро запустилось. Некоторые системы, например Alpine, его не используют.",
      ),
      uses: t(
        "systemd saytın, bazanın və arxa plan proqramının həmişə açıq qalması üçündür.",
        "systemd is for a site, a database, and a background program to stay open.",
        "systemd sitenin, tabanın ve arka plan programının hep açık kalması içindir.",
        "systemd كي يبقى الموقع والقاعدة وبرنامج الخلفية مفتوحة.",
        "systemd нужен, чтобы сайт, база и фоновая программа оставались открытыми.",
      ),
      useList: lines(
        ["Veb serverini açılışda başlatmaq", "Düşən xidməti yenidən qaldırmaq", "Jurnalda son səhvi oxumaq", "Bir xidməti digərindən sonra açmaq"],
        ["Starting the web server at boot", "Raising a fallen service again", "Reading the last error in the log", "Opening one service after another"],
        ["Web sunucusunu açılışta başlatmak", "Düşen hizmeti yeniden kaldırmak", "Günlükte son hatayı okumak", "Bir hizmeti diğerinden sonra açmak"],
        ["بدء خادم الويب عند الإقلاع", "رفع خدمة سقطت مرة أخرى", "قراءة آخر خطأ في السجل", "فتح خدمة بعد أخرى"],
        ["Запускать веб-сервер при загрузке", "Снова поднять упавшую службу", "Прочитать последнюю ошибку в журнале", "Открыть одну службу после другой"],
      ),
      can: t(
        "systemd ilə xidməti açıb bağlayır, açılışa bağlayır və jurnalı oxuyursan. O, proqramın kodunu yazmır. Səhv yol və ya səhv istifadəçi olanda xidmət düşür. enable etmədən start etmək yalnız indi açır. Maşın sönəndə həmin xidmət özü qayıtmır.",
        "With systemd you open and close a service, tie it to boot, and read the log. It does not write the program's code. When the path or the user is wrong, the service falls. Starting without enable opens it only now. When the machine turns off, that service does not come back by itself.",
        "systemd ile hizmeti açıp kapatır, açılışa bağlar ve günlüğü okursun. Programın kodunu yazmaz. Yol veya kullanıcı yanlışsa hizmet düşer. enable etmeden start etmek yalnız şimdi açar. Makine kapanınca o hizmet kendi dönmez.",
        "بـ systemd تفتح الخدمة وتغلقها وتربطها بالإقلاع وتقرأ السجل. هو لا يكتب كود البرنامج. إذا أخطأ المسار أو المستخدم تسقط الخدمة. start بلا enable يفتحها الآن فقط. حين ينطفئ الجهاز لا تعود تلك الخدمة وحدها.",
        "Через systemd службу открывают и закрывают, привязывают к загрузке и читают журнал. Код программы он не пишет. Если путь или пользователь неверны, служба падает. start без enable открывает её только сейчас. Когда машина выключается, эта служба сама не возвращается.",
      ),
      hard: t(
        "Bir start əmri asandır. Çətinlik unit faylının yolundadır. Proqramın tam yolu yazılmazsa systemd onu tapa bilmir. İşçi qovluq sənin terminal qovluğun olmaya bilər. Restart səhv qurulanda düşən proqram fasiləsiz yenidən açılır və jurnalı doldurur. Alpine-də systemctl yoxdursa əmr başqa alətə aiddir.",
        "One start command is easy. The difficulty is the path in the unit file. If the program's full path is not written, systemd cannot find it. The working folder may not be your terminal folder. When restart is set wrong, a fallen program opens again without a pause and fills the log. If Alpine has no systemctl, the command belongs to another tool.",
        "Bir start komutu kolaydır. Zorluk unit dosyasının yolundadır. Programın tam yolu yazılmazsa systemd onu bulamaz. Çalışma klasörü senin terminal klasörün olmayabilir. Restart yanlış kurulunca düşen program ara vermeden yeniden açılır ve günlüğü doldurur. Alpine’de systemctl yoksa komut başka araca aittir.",
        "أمر start واحد سهل. الصعوبة في مسار ملف unit. إذا لم يُكتب مسار البرنامج الكامل لا يجده systemd. مجلد العمل قد لا يكون مجلد الطرفية. إذا ضُبط restart خطأ يُفتح البرنامج الساقط بلا توقف ويملأ السجل. إذا لم يكن في Alpine systemctl فالأمر لأداة أخرى.",
        "Одна команда start легка. Трудность в пути внутри файла unit. Если полный путь программы не написан, systemd её не находит. Рабочая папка может быть не папкой твоего терминала. Если restart настроен неверно, упавшая программа открывается снова без паузы и заполняет журнал. Если в Alpine нет systemctl, команда принадлежит другому инструменту.",
      ),
      balance: t(
        "Üstünlük: açılış sırası bir yerdədir, düşən xidmət qaldırıla bilər, jurnal ayrıca oxunur. Məhdudiyyət: hər Linux-da yoxdur və unit səhvi xidməti səssiz saxlayır. systemd nüvə deyil və cron deyil.",
        "Advantage: the boot order is in one place, a fallen service can be raised, and the log is read separately. Limit: it is not on every Linux, and a unit mistake keeps the service quiet. systemd is not the kernel and it is not cron.",
        "Avantaj: açılış sırası bir yerdedir, düşen hizmet kaldırılabilir, günlük ayrıca okunur. Sınır: her Linux’ta yoktur ve unit hatası hizmeti sessiz tutar. systemd çekirdek değildir ve cron değildir.",
        "الميزة: ترتيب الإقلاع في مكان واحد والخدمة الساقطة تُرفع والسجل يُقرأ على حدة. الحد: ليس على كل Linux وخطأ unit يبقي الخدمة صامتة. systemd ليس النواة وليس cron.",
        "Плюс: порядок загрузки в одном месте, упавшую службу можно поднять, журнал читается отдельно. Ограничение: его нет в каждом Linux, и ошибка unit держит службу тихой. systemd — не ядро и не cron.",
      ),
      ideas: t(
        "Unit xidmətin faylıdır. start indi açır. enable növbəti açılışa yazır.",
        "A unit is the service's file. start opens it now. enable writes it to the next boot.",
        "Unit hizmetin dosyasıdır. start şimdi açar. enable sonraki açılışa yazar.",
        "unit ملف الخدمة. start يفتحها الآن. enable يكتبها للإقلاع التالي.",
        "unit — файл службы. start открывает её сейчас. enable записывает её на следующую загрузку.",
      ),
      ideaList: lines(
        ["systemctl status vəziyyəti göstərir", "journalctl jurnalı oxuyur", ".service ən çox görülən unit-dir", "Nüvə systemd-dən əvvəl açılır"],
        ["systemctl status shows the state", "journalctl reads the log", ".service is the unit seen most", "The kernel starts before systemd"],
        ["systemctl status durumu gösterir", "journalctl günlüğü okur", ".service en çok görülen unit’tir", "Çekirdek systemd’den önce açılır"],
        ["systemctl status يُظهر الحالة", "journalctl يقرأ السجل", ".service أكثر unit ظهوراً", "النواة تبدأ قبل systemd"],
        ["systemctl status показывает состояние", "journalctl читает журнал", ".service — самый частый unit", "Ядро стартует раньше systemd"],
      ),
      sample: t(
        "Bu əmr bir xidmətin indi açıq olub-olmadığını göstərir. Onu yaratmır.",
        "This command shows whether a service is open now. It does not create it.",
        "Bu komut bir hizmetin şimdi açık olup olmadığını gösterir. Onu yaratmaz.",
        "هذا الأمر يُظهر هل الخدمة مفتوحة الآن. لا ينشئها.",
        "Эта команда показывает, открыта ли служба сейчас. Она её не создаёт.",
      ),
      code: `systemctl status nginx`,
      faq: lines(
        ["systemd və Linux nüvəsi eynidir? Xeyr. Nüvə dəmirlə danışır. systemd xidmətlərin sırasını saxlayır.", "systemd və cron eynidir? Xeyr. cron vaxtı çatanda əmr çağırır. systemd xidməti açıq saxlayır.", "start və enable eynidir? Xeyr. start indi açır. enable növbəti açılışa bağlayır."],
        ["Are systemd and the Linux kernel the same? No. The kernel talks to the hardware. systemd keeps the order of services.", "Are systemd and cron the same? No. cron calls a command when the time comes. systemd keeps a service open.", "Are start and enable the same? No. start opens it now. enable ties it to the next boot."],
        ["systemd ve Linux çekirdeği aynı mı? Hayır. Çekirdek donanımla konuşur. systemd hizmetlerin sırasını tutar.", "systemd ve cron aynı mı? Hayır. cron vakti gelince komut çağırır. systemd hizmeti açık tutar.", "start ve enable aynı mı? Hayır. start şimdi açar. enable sonraki açılışa bağlar."],
        ["هل systemd ونواة Linux الشيء نفسه؟ لا. النواة تتكلم مع العتاد. systemd يحفظ ترتيب الخدمات.", "هل systemd وcron الشيء نفسه؟ لا. cron يستدعي أمراً حين يأتي الوقت. systemd يبقي الخدمة مفتوحة.", "هل start وenable الشيء نفسه؟ لا. start يفتحها الآن. enable يربطها بالإقلاع التالي."],
        ["systemd и ядро Linux — одно и то же? Нет. Ядро говорит с железом. systemd хранит порядок служб.", "systemd и cron — одно и то же? Нет. cron вызывает команду, когда приходит время. systemd держит службу открытой.", "start и enable — одно и то же? Нет. start открывает её сейчас. enable привязывает к следующей загрузке."],
      ),
    },
  ),
];
