import type { Lang } from "@/lib/i18n";
import type { ToolId } from "@/lib/tools";

const L = (az: string, en: string, tr: string, ar: string, ru: string): Record<Lang, string> => ({ az, en, tr, ar, ru });

export const TOOL_SLUG: Record<ToolId, string> = {
  json: "json",
  "json-min": "json-minifier",
  base64: "base64",
  uuid: "uuid",
  password: "password",
  url: "url",
  md5: "md5",
  sha256: "sha-256",
  lorem: "lorem-ipsum",
  html: "html",
  hash: "hash",
  css: "css",
  js: "javascript",
  "html-min": "html-minifier",
  "css-min": "css-minifier",
  number: "random-number",
  xml: "xml",
  sql: "sql",
  text: "random-text",
  name: "random-name",
  case: "letter-case",
  count: "word-count",
  diff: "text-diff",
  regex: "regex",
  unix: "unix-time",
  color: "color",
  csv: "json-csv",
};

export const TOOL_LEAD: Record<ToolId, Record<Lang, string>> = {
  json: L(
    "JSON mətnini sətirlərə ayırır. Səhv mötərizə və ya vergül burada görünür.",
    "Breaks JSON onto separate lines. A bad bracket or comma shows up here.",
    "JSON metnini satırlara ayırır. Hatalı parantez veya virgül burada görünür.",
    "يفصل JSON على أسطر. القوس أو الفاصلة الخطأ تظهر هنا.",
    "Разбивает JSON на строки. Плохая скобка или запятая видны здесь.",
  ),
  "json-min": L(
    "JSON mətnindən boşluqları çıxarır. Bir sətirdə qalır.",
    "Removes the spaces from JSON. It stays on one line.",
    "JSON metnindeki boşlukları çıkarır. Tek satırda kalır.",
    "يحذف الفراغات من JSON. يبقى في سطر واحد.",
    "Убирает пробелы из JSON. Остаётся одна строка.",
  ),
  base64: L(
    "Mətni Base64 koduna çevirir və kodu geri oxuyur.",
    "Turns text into Base64 and reads a Base64 code back.",
    "Metni Base64 koduna çevirir ve kodu geri okur.",
    "يحوّل النص إلى Base64 ويقرأ الرمز مرة أخرى.",
    "Переводит текст в Base64 и читает код обратно.",
  ),
  uuid: L(
    "Təsadüfi UUID yaradır. Hər basışda yeni identifikator çıxır.",
    "Makes a random UUID. Each press gives a new identifier.",
    "Rastgele UUID üretir. Her basışta yeni bir kimlik çıkar.",
    "ينشئ UUID عشوائيًا. كل ضغطة تعطي معرفًا جديدًا.",
    "Создаёт случайный UUID. Каждое нажатие даёт новый идентификатор.",
  ),
  password: L(
    "Hərflərdən, rəqəmlərdən və işarələrdən şifrə düzəldir. Uzunluğu özün seçirsən.",
    "Builds a password from letters, digits, and signs. You choose the length.",
    "Harflerden, rakamlardan ve işaretlerden parola kurar. Uzunluğu sen seçersin.",
    "يبني كلمة سر من حروف وأرقام وعلامات. أنت تختار الطول.",
    "Собирает пароль из букв, цифр и знаков. Длину выбираешь сам.",
  ),
  url: L(
    "Ünvandakı boşluğu və işarəni kodlayır, kodu geri açır.",
    "Encodes a space or sign in an address, and opens the code again.",
    "Adresteki boşluğu ve işareti kodlar, kodu geri açar.",
    "يرمّز الفراغ والعلامة في العنوان، ثم يفتح الرمز.",
    "Кодирует пробел и знак в адресе и открывает код обратно.",
  ),
  md5: L(
    "Mətndən MD5 hash çıxarır. Eyni mətn həmişə eyni kodu verir.",
    "Makes an MD5 hash from text. The same text always gives the same code.",
    "Metinden MD5 hash çıkarır. Aynı metin her zaman aynı kodu verir.",
    "يخرج MD5 من النص. النص نفسه يعطي الرمز نفسه دائمًا.",
    "Делает MD5 из текста. Один и тот же текст всегда даёт тот же код.",
  ),
  sha256: L(
    "Mətndən SHA-256 hash çıxarır. Nəticə 64 simvolluq onaltılıq koddur.",
    "Makes a SHA-256 hash from text. The result is a 64-character hex code.",
    "Metinden SHA-256 hash çıkarır. Sonuç 64 karakterlik onaltılık koddur.",
    "يخرج SHA-256 من النص. النتيجة رمز من 64 حرفًا.",
    "Делает SHA-256 из текста. Результат — код из 64 знаков.",
  ),
  lorem: L(
    "Səhifə nümunəsi üçün Lorem Ipsum abzasları yazır.",
    "Writes Lorem Ipsum paragraphs for a page sample.",
    "Sayfa örneği için Lorem Ipsum paragrafları yazar.",
    "يكتب فقرات Lorem Ipsum لنموذج صفحة.",
    "Пишет абзацы Lorem Ipsum для образца страницы.",
  ),
  html: L(
    "HTML işarələrini kodlayır ki, səhifə onları mətn kimi göstərsin. Kodu geri də açır.",
    "Encodes HTML signs so a page shows them as text. It also opens the code.",
    "HTML işaretlerini kodlar ki sayfa onları metin gibi göstersin. Kodu da geri açar.",
    "يرمّز علامات HTML كي تعرضها الصفحة كنص. ويعيد فتح الرمز.",
    "Кодирует знаки HTML, чтобы страница показала их как текст. Код также открывается назад.",
  ),
  hash: L(
    "Mətndən SHA-1 hash çıxarır. MD5 və SHA-256 ayrı səhifələrdədir.",
    "Makes a SHA-1 hash from text. MD5 and SHA-256 are on their own pages.",
    "Metinden SHA-1 hash çıkarır. MD5 ve SHA-256 ayrı sayfalardadır.",
    "يخرج SHA-1 من النص. MD5 وSHA-256 في صفحتين منفصلتين.",
    "Делает SHA-1 из текста. MD5 и SHA-256 на отдельных страницах.",
  ),
  css: L(
    "CSS qaydalarını sətirlərə ayırır. Mötərizənin içi içəri çəkilir.",
    "Breaks CSS rules onto lines. The inside of a brace is indented.",
    "CSS kurallarını satırlara ayırır. Parantezin içi içeri çekilir.",
    "يفصل قواعد CSS على أسطر. داخل القوس يتراجع.",
    "Разбивает правила CSS на строки. Внутри скобки делается отступ.",
  ),
  js: L(
    "JavaScript mətnini sətirlərə ayırır. Mötərizə və nöqtəli vergül yeni sətir açır.",
    "Breaks JavaScript onto lines. A brace and a semicolon start a new line.",
    "JavaScript metnini satırlara ayırır. Parantez ve noktalı virgül yeni satır açar.",
    "يفصل JavaScript على أسطر. القوس والفاصلة المنقوطة يفتحان سطرًا.",
    "Разбивает JavaScript на строки. Скобка и точка с запятой открывают новую строку.",
  ),
  "html-min": L(
    "HTML içindəki artıq boşluğu və şərhi çıxarır.",
    "Removes extra space and comments inside HTML.",
    "HTML içindeki fazla boşluğu ve yorumu çıkarır.",
    "يحذف الفراغ الزائد والتعليق من HTML.",
    "Убирает лишний пробел и комментарий из HTML.",
  ),
  "css-min": L(
    "CSS içindəki boşluğu və şərhi çıxarır. Qayda bir sətirdə qalır.",
    "Removes space and comments from CSS. A rule stays on one line.",
    "CSS içindeki boşluğu ve yorumu çıkarır. Kural tek satırda kalır.",
    "يحذف الفراغ والتعليق من CSS. القاعدة تبقى في سطر.",
    "Убирает пробел и комментарий из CSS. Правило остаётся в одной строке.",
  ),
  number: L(
    "Verdiyin iki ədədin arasından təsadüfi rəqəm seçir.",
    "Picks a random number between the two values you give.",
    "Verdiğin iki sayının arasından rastgele sayı seçer.",
    "يختار رقمًا عشوائيًا بين القيمتين اللتين تكتبهما.",
    "Выбирает случайное число между двумя заданными значениями.",
  ),
  xml: L(
    "XML teqlərini sətirlərə ayırır. İç-içə teq içəri çəkilir.",
    "Breaks XML tags onto lines. A nested tag is indented.",
    "XML etiketlerini satırlara ayırır. İç içe etiket içeri çekilir.",
    "يفصل وسوم XML على أسطر. الوسم الداخلي يتراجع.",
    "Разбивает теги XML на строки. Вложенный тег получает отступ.",
  ),
  sql: L(
    "SQL cümləsində SELECT, FROM və WHERE sözlərini ayrı sətirə qoyur.",
    "Puts SELECT, FROM, and WHERE on their own lines in an SQL sentence.",
    "SQL cümlesinde SELECT, FROM ve WHERE sözlerini ayrı satıra koyar.",
    "يضع SELECT وFROM وWHERE في أسطر منفصلة داخل جملة SQL.",
    "Ставит SELECT, FROM и WHERE на отдельные строки в фразе SQL.",
  ),
  text: L(
    "Qısa təsadüfi sözlərdən mətn düzəldir. Sınaq üçün kifayətdir.",
    "Builds text from short random words. Enough for a test.",
    "Kısa rastgele sözlerden metin kurar. Deneme için yeter.",
    "يبني نصًا من كلمات عشوائية قصيرة. يكفي للتجربة.",
    "Собирает текст из коротких случайных слов. Хватает для пробы.",
  ),
  name: L(
    "Təsadüfi ad və soyad yazır. Nümunə siyahı üçündür, real şəxs deyil.",
    "Writes a random first and last name. It is a sample, not a real person.",
    "Rastgele ad ve soyad yazar. Örnek listedir, gerçek kişi değildir.",
    "يكتب اسمًا ولقبًا عشوائيين. هذا نموذج، وليس شخصًا حقيقيًا.",
    "Пишет случайные имя и фамилию. Это образец, не настоящий человек.",
  ),
  case: L(
    "Mətni böyük, kiçik, camelCase, snake_case və slug formasında göstərir.",
    "Shows text as upper case, lower case, camelCase, snake_case, and a slug.",
    "Metni büyük, küçük, camelCase, snake_case ve slug biçiminde gösterir.",
    "يعرض النص بحروف كبيرة وصغيرة وcamelCase وsnake_case وslug.",
    "Показывает текст в верхнем и нижнем регистре, camelCase, snake_case и slug.",
  ),
  count: L(
    "Mətndə sözün, simvolun, boşluqsuz simvolun və sətrin sayını göstərir.",
    "Shows how many words, characters, characters without spaces, and lines are in the text.",
    "Metindeki söz, karakter, boşluksuz karakter ve satır sayısını gösterir.",
    "يعرض عدد الكلمات والحروف والحروف بلا فراغ والأسطر.",
    "Показывает число слов, символов, символов без пробелов и строк.",
  ),
  diff: L(
    "İki mətni sətir-sətir tutuşdurur. Çıxan sətir minus, gələn sətir plus ilə görünür.",
    "Compares two texts line by line. A removed line has a minus, a new line has a plus.",
    "İki metni satır satır karşılaştırır. Çıkan satır eksi, gelen satır artı ile görünür.",
    "يقارن نصين سطرًا بسطر. السطر المحذوف بناقص، والسطر الجديد بزائد.",
    "Сравнивает два текста построчно. Ушедшая строка с минусом, новая с плюсом.",
  ),
  regex: L(
    "Nümunəni mətnin içində axtarır. Uyğun gələn parçaları alt-alta yazır.",
    "Looks for a pattern inside text. Matching pieces are listed one under another.",
    "Kalıbı metnin içinde arar. Eşleşen parçaları alt alta yazar.",
    "يبحث عن نمط داخل النص. الأجزاء المطابقة تُكتب واحدًا تحت الآخر.",
    "Ищет шаблон в тексте. Совпавшие куски пишет один под другим.",
  ),
  unix: L(
    "Saniyəni tarixə, tarixi Unix saniyəsinə çevirir. Qısa ədəd saniyə sayılır.",
    "Turns seconds into a date, and a date into Unix seconds. A short number is treated as seconds.",
    "Saniyeyi tarihe, tarihi Unix saniyesine çevirir. Kısa sayı saniye sayılır.",
    "يحوّل الثواني إلى تاريخ، والتاريخ إلى ثوان يونكس. العدد القصير يُحسب ثواني.",
    "Переводит секунды в дату, а дату в секунды Unix. Короткое число считается секундами.",
  ),
  color: L(
    "HEX, RGB və HSL rəng kodunu bir-birinə çevirir.",
    "Converts a HEX, RGB, and HSL color code into the others.",
    "HEX, RGB ve HSL renk kodunu birbirine çevirir.",
    "يحوّل رمز اللون بين HEX وRGB وHSL.",
    "Переводит код цвета между HEX, RGB и HSL.",
  ),
  csv: L(
    "JSON siyahısını CSV cədvəlinə, CSV cədvəlini JSON siyahısına çevirir.",
    "Turns a JSON list into a CSV table, and a CSV table into a JSON list.",
    "JSON listesini CSV tablosuna, CSV tablosunu JSON listesine çevirir.",
    "يحوّل قائمة JSON إلى جدول CSV، وجدول CSV إلى قائمة JSON.",
    "Переводит список JSON в таблицу CSV, а таблицу CSV в список JSON.",
  ),
};

export function toolIdFromSlug(slug: string) {
  const pair = (Object.entries(TOOL_SLUG) as [ToolId, string][]).find((item) => item[1] === slug);
  return pair ? pair[0] : null;
}
