import type { Lang } from "@/lib/i18n";
import type { ToolId } from "@/lib/tools";

const L = (az: string, en: string, tr: string, ar: string, ru: string): Record<Lang, string> => ({ az, en, tr, ar, ru });

export const TOOL_SLUG: Record<ToolId, string> = {
  json: "json",
  "json-min": "json-minifier",
  base64: "base64",
  uuid: "uuid",
  password: "password",
  url: "url",
  md5: "md5",
  sha256: "sha-256",
  lorem: "lorem-ipsum",
  html: "html",
  hash: "hash",
  css: "css",
  js: "javascript",
  "html-min": "html-minifier",
  "css-min": "css-minifier",
  number: "random-number",
  xml: "xml",
  sql: "sql",
  text: "random-text",
  name: "random-name",
  case: "letter-case",
  count: "word-count",
  diff: "text-diff",
  regex: "regex",
  unix: "unix-time",
  color: "color",
  csv: "json-csv",
  base: "binary-hex",
  pxrem: "px-rem",
  jwt: "jwt",
  cron: "cron",
  chmod: "chmod",
  robots: "robots-txt",
  contrast: "color-contrast",
  slug: "slug",
  percent: "percent",
  mime: "mime",
  meta: "meta",
  sitemap: "sitemap",
  utm: "utm",
  days: "date-diff",
  shadow: "css-shadow",
  htaccess: "htaccess",
  gradient: "css-gradient",
  strength: "password-strength",
  table: "html-table",
  radius: "css-radius",
  trim: "trim-spaces",
  lines: "line-numbers",
  jsoncsv: "json-to-csv",
  palette: "color-palette",
  htmlfmt: "html-formatter",
  "js-min": "javascript-minifier",
  python: "python",
  php: "php",
  "sql-min": "sql-minifier",
  "xml-min": "xml-minifier",
  cssvar: "css-variable",
  link: "link-check",
  chars: "character-count",
  yaml: "yaml",
  markdown: "markdown-html",
  email: "email-check",
  words: "number-words",
  ip: "ip-check",
};

export const TOOL_LEAD: Record<ToolId, Record<Lang, string>> = {
  json: L(
    "JSON mətnini sətirlərə ayırır. Səhv mötərizə və ya vergül burada görünür.\n\nNümunə: {\"ad\":\"Aysel\",\"yaş\":20}. Yaradan sonra hər sahə öz sətirində olur. Vergül unudulsa və ya dırnaq çatışmasa, alət mətni qəbul etmir.\n\nBu səhifə yalnız düzəldir. Boşluqları çıxarmaq üçün JSON sıx aləti var. Nəticəni kopyalamaq və ya .txt kimi yükləmək olur.",
    "Breaks JSON onto separate lines. A bad bracket or comma shows up here.\n\nExample: {\"name\":\"Aysel\",\"age\":20}. After you press Make, each field sits on its own line. A missing comma or quote is rejected.\n\nThis page only formats. The JSON minifier removes the spaces. You can copy the result or download it as .txt.",
    "JSON metnini satırlara ayırır. Hatalı parantez veya virgül burada görünür.\n\nÖrnek: {\"ad\":\"Aysel\",\"yaş\":20}. Üret dedikten sonra her alan kendi satırında durur. Virgül ya da tırnak eksikse metin kabul edilmez.\n\nBu sayfa yalnız düzenler. Boşlukları çıkarmak için JSON sıkıştır aracı vardır. Sonucu kopyalayabilir ya da .txt olarak indirebilirsin.",
    "يفصل JSON على أسطر. القوس أو الفاصلة الخطأ تظهر هنا.\n\nمثال: {\"ad\":\"Aysel\",\"yaş\":20}. بعد الإنشاء يقف كل حقل في سطره. إذا نقصت فاصلة أو علامة اقتباس يُرفض النص.\n\nهذه الصفحة تنسّق فقط. ضغط JSON يحذف الفراغات. يمكن نسخ النتيجة أو تنزيلها كملف txt.",
    "Разбивает JSON на строки. Плохая скобка или запятая видны здесь.\n\nПример: {\"ad\":\"Aysel\",\"yaş\":20}. После кнопки каждое поле стоит на своей строке. Пропущенная запятая или кавычка отклоняется.\n\nЭта страница только оформляет. Сжатие JSON убирает пробелы. Результат можно скопировать или скачать как .txt.",
  ),
  "json-min": L(
    "JSON mətnindən boşluqları çıxarır. Bir sətirdə qalır.",
    "Removes the spaces from JSON. It stays on one line.",
    "JSON metnindeki boşlukları çıkarır. Tek satırda kalır.",
    "يحذف الفراغات من JSON. يبقى في سطر واحد.",
    "Убирает пробелы из JSON. Остаётся одна строка.",
  ),
  base64: L(
    "Mətni Base64 koduna çevirir və kodu geri oxuyur.\n\nNümunə: Salam yazılanda kod U2FsYW0= olur. Aç düyməsi kodu yenidən mətnə qaytarır.\n\nBase64 şifrə deyil. Mətni gizlətmir, yalnız başqa formada saxlayır. Şəkil və fayl burada oxunmur, yalnız mətn.",
    "Turns text into Base64 and reads a Base64 code back.\n\nExample: Salam becomes U2FsYW0=. Read turns the code back into text.\n\nBase64 is not a cipher. It does not hide the text, it only stores it in another form. Pictures and files are not read here, only text.",
    "Metni Base64 koduna çevirir ve kodu geri okur.\n\nÖrnek: Salam yazılınca kod U2FsYW0= olur. Aç düğmesi kodu yeniden metne çevirir.\n\nBase64 şifre değildir. Metni gizlemez, yalnız başka biçimde saklar. Resim ve dosya burada okunmaz, yalnız metin.",
    "يحوّل النص إلى Base64 ويقرأ الرمز مرة أخرى.\n\nمثال: Salam تصبح U2FsYW0=. زر القراءة يعيد الرمز إلى نص.\n\nBase64 ليس تشفيرًا. لا يخفي النص، بل يحفظه بشكل آخر. الصور والملفات لا تُقرأ هنا، النص فقط.",
    "Переводит текст в Base64 и читает код обратно.\n\nПример: Salam становится U2FsYW0=. Кнопка чтения возвращает текст.\n\nBase64 — не шифр. Он не прячет текст, только хранит его в другом виде. Картинки и файлы здесь не читаются, только текст.",
  ),
  uuid: L(
    "Təsadüfi UUID yaradır. Hər basışda yeni identifikator çıxır.\n\nNümunə: 3f1c0a2e-7b44-4d1a-9c6e-1a0b8e5d2f77 kimi 36 simvolluq kod olur. Eyni kodun təkrar çıxma ehtimalı praktiki olaraq yoxdur.\n\nBu səhifə bazaya yazmır. Kodu kopyalayıb öz layihəndə işlədə bilərsən. Uzunluq seçimi yoxdur, UUID həmişə eyni formadadır.",
    "Makes a random UUID. Each press gives a new identifier.\n\nExample: a code like 3f1c0a2e-7b44-4d1a-9c6e-1a0b8e5d2f77, 36 characters. The chance of the same code twice is practically none.\n\nThis page does not write to a database. Copy the code into your own project. There is no length choice: a UUID always has the same shape.",
    "Rastgele UUID üretir. Her basışta yeni bir kimlik çıkar.\n\nÖrnek: 3f1c0a2e-7b44-4d1a-9c6e-1a0b8e5d2f77 gibi 36 karakterlik kod olur. Aynı kodun yeniden çıkma ihtimali pratikte yoktur.\n\nBu sayfa veritabanına yazmaz. Kodu kopyalayıp kendi projende kullanabilirsin. Uzunluk seçimi yoktur, UUID hep aynı biçimdedir.",
    "ينشئ UUID عشوائيًا. كل ضغطة تعطي معرفًا جديدًا.\n\nمثال: رمز مثل 3f1c0a2e-7b44-4d1a-9c6e-1a0b8e5d2f77 من 36 حرفًا. احتمال تكرار الرمز نفسه شبه معدوم.\n\nهذه الصفحة لا تكتب في قاعدة بيانات. انسخ الرمز إلى مشروعك. لا يوجد اختيار للطول، شكل UUID ثابت.",
    "Создаёт случайный UUID. Каждое нажатие даёт новый идентификатор.\n\nПример: код вроде 3f1c0a2e-7b44-4d1a-9c6e-1a0b8e5d2f77, 36 знаков. Шанс повтора практически нулевой.\n\nСтраница ничего не пишет в базу. Код можно скопировать в свой проект. Длину не выбирают: вид UUID всегда один.",
  ),
  password: L(
    "Hərflərdən, rəqəmlərdən və işarələrdən şifrə düzəldir. Uzunluğu özün seçirsən.\n\nNümunə: uzunluq 12 olanda 12 simvolluq şifrə çıxır. Hər basışda başqa şifrə olur.\n\nBu səhifə şifrəni yadda saxlamır. Özün kopyala. Qısa şifrə zəifdir, 12 və ya daha uzun daha uyğundur.",
    "Builds a password from letters, digits, and signs. You choose the length.\n\nExample: length 12 gives a 12-character password. Each press gives another password.\n\nThis page does not store the password. Copy it yourself. A short password is weak. 12 or more is a better fit.",
    "Harflerden, rakamlardan ve işaretlerden parola kurar. Uzunluğu sen seçersin.\n\nÖrnek: uzunluk 12 olunca 12 karakterlik parola çıkar. Her basışta başka parola olur.\n\nBu sayfa parolayı saklamaz. Kendin kopyala. Kısa parola zayıftır, 12 ya da daha uzun daha uygundur.",
    "يبني كلمة سر من حروف وأرقام وعلامات. أنت تختار الطول.\n\nمثال: الطول 12 يعطي كلمة من 12 حرفًا. كل ضغطة تعطي كلمة أخرى.\n\nهذه الصفحة لا تحفظ كلمة السر. انسخها بنفسك. الكلمة القصيرة ضعيفة، و12 أو أكثر أنسب.",
    "Собирает пароль из букв, цифр и знаков. Длину выбираешь сам.\n\nПример: длина 12 даёт пароль из 12 знаков. Каждое нажатие даёт другой пароль.\n\nСтраница пароль не хранит. Скопируй сам. Короткий пароль слаб, 12 и больше лучше.",
  ),
  url: L(
    "Ünvandakı boşluğu və işarəni kodlayır, kodu geri açır.",
    "Encodes a space or sign in an address, and opens the code again.",
    "Adresteki boşluğu ve işareti kodlar, kodu geri açar.",
    "يرمّز الفراغ والعلامة في العنوان، ثم يفتح الرمز.",
    "Кодирует пробел и знак в адресе и открывает код обратно.",
  ),
  md5: L(
    "Mətndən MD5 hash çıxarır. Eyni mətn həmişə eyni kodu verir.\n\nNümunə: Salam yazılanda nəticə e0c0587b2f05f1a546894eae0424339f olur. Bir hərf dəyişsə, kod tamam başqa olur.\n\nMD5 köhnə üsuldur. Yeni şifrə saxlamaq üçün SHA-256 daha uyğundur. Bu səhifə kodu yoxlamır, yalnız hesablayır.",
    "Makes an MD5 hash from text. The same text always gives the same code.\n\nExample: Salam becomes e0c0587b2f05f1a546894eae0424339f. Change one letter and the code is different.\n\nMD5 is an old method. SHA-256 is a better fit for a new password store. This page does not check a code, it only calculates one.",
    "Metinden MD5 hash çıkarır. Aynı metin her zaman aynı kodu verir.\n\nÖrnek: Salam yazılınca sonuç e0c0587b2f05f1a546894eae0424339f olur. Bir harf değişirse kod bütünüyle değişir.\n\nMD5 eski bir yoldur. Yeni parola saklamak için SHA-256 daha uygundur. Bu sayfa kodu kontrol etmez, yalnız hesaplar.",
    "يخرج MD5 من النص. النص نفسه يعطي الرمز نفسه دائمًا.\n\nمثال: Salam تعطي e0c0587b2f05f1a546894eae0424339f. إذا تغيّر حرف يتغيّر الرمز كله.\n\nMD5 طريقة قديمة. SHA-256 أنسب لحفظ كلمة سر جديدة. هذه الصفحة لا تفحص رمزًا، بل تحسبه فقط.",
    "Делает MD5 из текста. Один и тот же текст всегда даёт тот же код.\n\nПример: Salam даёт e0c0587b2f05f1a546894eae0424339f. Одна другая буква — и код другой.\n\nMD5 — старый способ. Для нового хранения пароля лучше SHA-256. Страница код не проверяет, только считает.",
  ),
  sha256: L(
    "Mətndən SHA-256 hash çıxarır. Nəticə 64 simvolluq onaltılıq koddur.",
    "Makes a SHA-256 hash from text. The result is a 64-character hex code.",
    "Metinden SHA-256 hash çıkarır. Sonuç 64 karakterlik onaltılık koddur.",
    "يخرج SHA-256 من النص. النتيجة رمز من 64 حرفًا.",
    "Делает SHA-256 из текста. Результат — код из 64 знаков.",
  ),
  lorem: L(
    "Səhifə nümunəsi üçün Lorem Ipsum abzasları yazır.",
    "Writes Lorem Ipsum paragraphs for a page sample.",
    "Sayfa örneği için Lorem Ipsum paragrafları yazar.",
    "يكتب فقرات Lorem Ipsum لنموذج صفحة.",
    "Пишет абзацы Lorem Ipsum для образца страницы.",
  ),
  html: L(
    "HTML işarələrini kodlayır ki, səhifə onları mətn kimi göstərsin. Kodu geri də açır.",
    "Encodes HTML signs so a page shows them as text. It also opens the code.",
    "HTML işaretlerini kodlar ki sayfa onları metin gibi göstersin. Kodu da geri açar.",
    "يرمّز علامات HTML كي تعرضها الصفحة كنص. ويعيد فتح الرمز.",
    "Кодирует знаки HTML, чтобы страница показала их как текст. Код также открывается назад.",
  ),
  hash: L(
    "Mətndən SHA-1 hash çıxarır. MD5 və SHA-256 ayrı səhifələrdədir.",
    "Makes a SHA-1 hash from text. MD5 and SHA-256 are on their own pages.",
    "Metinden SHA-1 hash çıkarır. MD5 ve SHA-256 ayrı sayfalardadır.",
    "يخرج SHA-1 من النص. MD5 وSHA-256 في صفحتين منفصلتين.",
    "Делает SHA-1 из текста. MD5 и SHA-256 на отдельных страницах.",
  ),
  css: L(
    "CSS qaydalarını sətirlərə ayırır. Mötərizənin içi içəri çəkilir.\n\nNümunə: body{color:red;margin:0} yazılanda hər qayda öz sətirində olur.\n\nBu səhifə rəngi dəyişmir, yalnız oxumağı asanlaşdırır. Boşluqları çıxarmaq üçün CSS sıx aləti var.",
    "Breaks CSS rules onto lines. The inside of a brace is indented.\n\nExample: body{color:red;margin:0} puts each rule on its own line.\n\nThis page does not change the color. It only makes the text easier to read. The CSS minifier removes the spaces.",
    "CSS kurallarını satırlara ayırır. Parantezin içi içeri çekilir.\n\nÖrnek: body{color:red;margin:0} yazılınca her kural kendi satırında olur.\n\nBu sayfa rengi değiştirmez, yalnız okumayı kolaylaştırır. Boşlukları çıkarmak için CSS sıkıştır aracı vardır.",
    "يفصل قواعد CSS على أسطر. داخل القوس يتراجع.\n\nمثال: body{color:red;margin:0} يضع كل قاعدة في سطرها.\n\nهذه الصفحة لا تغيّر اللون. تسهّل القراءة فقط. ضغط CSS يحذف الفراغات.",
    "Разбивает правила CSS на строки. Внутри скобки делается отступ.\n\nПример: body{color:red;margin:0} ставит каждое правило на свою строку.\n\nСтраница цвет не меняет, только облегчает чтение. Сжатие CSS убирает пробелы.",
  ),
  js: L(
    "JavaScript mətnini sətirlərə ayırır. Mötərizə və nöqtəli vergül yeni sətir açır.",
    "Breaks JavaScript onto lines. A brace and a semicolon start a new line.",
    "JavaScript metnini satırlara ayırır. Parantez ve noktalı virgül yeni satır açar.",
    "يفصل JavaScript على أسطر. القوس والفاصلة المنقوطة يفتحان سطرًا.",
    "Разбивает JavaScript на строки. Скобка и точка с запятой открывают новую строку.",
  ),
  "html-min": L(
    "HTML içindəki artıq boşluğu və şərhi çıxarır.",
    "Removes extra space and comments inside HTML.",
    "HTML içindeki fazla boşluğu ve yorumu çıkarır.",
    "يحذف الفراغ الزائد والتعليق من HTML.",
    "Убирает лишний пробел и комментарий из HTML.",
  ),
  "css-min": L(
    "CSS içindəki boşluğu və şərhi çıxarır. Qayda bir sətirdə qalır.",
    "Removes space and comments from CSS. A rule stays on one line.",
    "CSS içindeki boşluğu ve yorumu çıkarır. Kural tek satırda kalır.",
    "يحذف الفراغ والتعليق من CSS. القاعدة تبقى في سطر.",
    "Убирает пробел и комментарий из CSS. Правило остаётся в одной строке.",
  ),
  number: L(
    "Verdiyin iki ədədin arasından təsadüfi rəqəm seçir.",
    "Picks a random number between the two values you give.",
    "Verdiğin iki sayının arasından rastgele sayı seçer.",
    "يختار رقمًا عشوائيًا بين القيمتين اللتين تكتبهما.",
    "Выбирает случайное число между двумя заданными значениями.",
  ),
  xml: L(
    "XML teqlərini sətirlərə ayırır. İç-içə teq içəri çəkilir.",
    "Breaks XML tags onto lines. A nested tag is indented.",
    "XML etiketlerini satırlara ayırır. İç içe etiket içeri çekilir.",
    "يفصل وسوم XML على أسطر. الوسم الداخلي يتراجع.",
    "Разбивает теги XML на строки. Вложенный тег получает отступ.",
  ),
  sql: L(
    "SQL cümləsində SELECT, FROM və WHERE sözlərini ayrı sətirə qoyur.",
    "Puts SELECT, FROM, and WHERE on their own lines in an SQL sentence.",
    "SQL cümlesinde SELECT, FROM ve WHERE sözlerini ayrı satıra koyar.",
    "يضع SELECT وFROM وWHERE في أسطر منفصلة داخل جملة SQL.",
    "Ставит SELECT, FROM и WHERE на отдельные строки в фразе SQL.",
  ),
  text: L(
    "Qısa təsadüfi sözlərdən mətn düzəldir. Sınaq üçün kifayətdir.",
    "Builds text from short random words. Enough for a test.",
    "Kısa rastgele sözlerden metin kurar. Deneme için yeter.",
    "يبني نصًا من كلمات عشوائية قصيرة. يكفي للتجربة.",
    "Собирает текст из коротких случайных слов. Хватает для пробы.",
  ),
  name: L(
    "Təsadüfi ad və soyad yazır. Nümunə siyahı üçündür, real şəxs deyil.",
    "Writes a random first and last name. It is a sample, not a real person.",
    "Rastgele ad ve soyad yazar. Örnek listedir, gerçek kişi değildir.",
    "يكتب اسمًا ولقبًا عشوائيين. هذا نموذج، وليس شخصًا حقيقيًا.",
    "Пишет случайные имя и фамилию. Это образец, не настоящий человек.",
  ),
  case: L(
    "Mətni böyük, kiçik, camelCase, snake_case və slug formasında göstərir.",
    "Shows text as upper case, lower case, camelCase, snake_case, and a slug.",
    "Metni büyük, küçük, camelCase, snake_case ve slug biçiminde gösterir.",
    "يعرض النص بحروف كبيرة وصغيرة وcamelCase وsnake_case وslug.",
    "Показывает текст в верхнем и нижнем регистре, camelCase, snake_case и slug.",
  ),
  count: L(
    "Mətndə sözün, simvolun, boşluqsuz simvolun və sətrin sayını göstərir.\n\nNümunə: bir iki üç yazılanda söz 3, simvol 11 olur. Boşluq simvola daxildir, boşluqsuz sayda çıxır.\n\nSətir sayı Enter ilə ayrılan sətirlərdir. Boş mətn sıfır verir. Say özü hazır cavabdır, kopyalamaq olur.",
    "Shows how many words, characters, characters without spaces, and lines are in the text.\n\nExample: one two three gives 3 words and 13 characters. A space counts as a character, and the no-space count leaves it out.\n\nA line is what Enter separates. Empty text gives zero. The count can be copied.",
    "Metindeki söz, karakter, boşluksuz karakter ve satır sayısını gösterir.\n\nÖrnek: bir iki üç yazılınca söz 3, karakter 11 olur. Boşluk karaktere girer, boşluksuz sayıda çıkmaz.\n\nSatır sayısı Enter ile ayrılan satırlardır. Boş metin sıfır verir. Sayı kopyalanabilir.",
    "يعرض عدد الكلمات والحروف والحروف بلا فراغ والأسطر.\n\nمثال: bir iki üç تعطي 3 كلمات و11 حرفًا. الفراغ يُحسب حرفًا، ويخرج من العدد بلا فراغ.\n\nالسطر ما يفصله Enter. النص الفارغ يعطي صفرًا. يمكن نسخ العدد.",
    "Показывает число слов, символов, символов без пробелов и строк.\n\nПример: bir iki üç даёт 3 слова и 11 символов. Пробел входит в символы и выходит из счёта без пробелов.\n\nСтрока — то, что отделяет Enter. Пустой текст даёт ноль. Число можно скопировать.",
  ),
  diff: L(
    "İki mətni sətir-sətir tutuşdurur. Çıxan sətir minus, gələn sətir plus ilə görünür.",
    "Compares two texts line by line. A removed line has a minus, a new line has a plus.",
    "İki metni satır satır karşılaştırır. Çıkan satır eksi, gelen satır artı ile görünür.",
    "يقارن نصين سطرًا بسطر. السطر المحذوف بناقص، والسطر الجديد بزائد.",
    "Сравнивает два текста построчно. Ушедшая строка с минусом, новая с плюсом.",
  ),
  regex: L(
    "Nümunəni mətnin içində axtarır. Uyğun gələn parçaları alt-alta yazır.\n\nNümunə: nümunə a+, mətn baac. Nəticə aa olur. Nöqtə istənilən simvol, ulduz təkrar deməkdir.\n\nSəhv nümunə qəbul olunmur. Heç nə uyğun gəlməsə, səhifə bunu ayrıca yazır.",
    "Looks for a pattern inside text. Matching pieces are listed one under another.\n\nExample: pattern a+, text baac. The result is aa. A dot means any character, a star means a repeat.\n\nA bad pattern is rejected. If nothing matches, the page says so.",
    "Kalıbı metnin içinde arar. Eşleşen parçaları alt alta yazar.\n\nÖrnek: kalıp a+, metin baac. Sonuç aa olur. Nokta herhangi bir karakter, yıldız tekrar demektir.\n\nHatalı kalıp kabul edilmez. Hiçbir şey eşleşmezse sayfa bunu ayrıca yazar.",
    "يبحث عن نمط داخل النص. الأجزاء المطابقة تُكتب واحدًا تحت الآخر.\n\nمثال: النمط a+ والنص baac. النتيجة aa. النقطة أي حرف، والنجمة تكرار.\n\nالنمط الخطأ يُرفض. إذا لم يطابق شيء تكتب الصفحة ذلك.",
    "Ищет шаблон в тексте. Совпавшие куски пишет один под другим.\n\nПример: шаблон a+, текст baac. Результат aa. Точка — любой знак, звёздочка — повтор.\n\nПлохой шаблон отклоняется. Если ничего не совпало, страница пишет об этом.",
  ),
  unix: L(
    "Saniyəni tarixə, tarixi Unix saniyəsinə çevirir. Qısa ədəd saniyə sayılır.\n\nNümunə: 0 yazılanda nəticə 1970-01-01 00:00:00 UTC olur. 2026-10-07 yazılanda saniyə çıxır.\n\n10 rəqəmli ədəd saniyə sayılır. 13 rəqəmli ədəd millisaniyə sayılır. Tarix UTC-dir, yerli saat deyil.",
    "Turns seconds into a date, and a date into Unix seconds. A short number is treated as seconds.\n\nExample: 0 becomes 1970-01-01 00:00:00 UTC. 2026-10-07 becomes a second count.\n\nA 10-digit number is seconds. A 13-digit number is milliseconds. The date is UTC, not local time.",
    "Saniyeyi tarihe, tarihi Unix saniyesine çevirir. Kısa sayı saniye sayılır.\n\nÖrnek: 0 yazılınca sonuç 1970-01-01 00:00:00 UTC olur. 2026-10-07 yazılınca saniye çıkar.\n\n10 basamaklı sayı saniyedir. 13 basamaklı sayı milisaniyedir. Tarih UTC'dir, yerel saat değildir.",
    "يحوّل الثواني إلى تاريخ، والتاريخ إلى ثوان يونكس. العدد القصير يُحسب ثواني.\n\nمثال: 0 تعطي 1970-01-01 00:00:00 UTC. 2026-10-07 تعطي عدد الثواني.\n\nالعدد من 10 أرقام هو ثوان. العدد من 13 رقمًا هو أجزاء من الثانية. التاريخ بتوقيت UTC، وليس التوقيت المحلي.",
    "Переводит секунды в дату, а дату в секунды Unix. Короткое число считается секундами.\n\nПример: 0 даёт 1970-01-01 00:00:00 UTC. 2026-10-07 даёт число секунд.\n\nЧисло из 10 цифр — секунды. Число из 13 цифр — миллисекунды. Дата в UTC, не местное время.",
  ),
  color: L(
    "HEX, RGB və HSL rəng kodunu bir-birinə çevirir.\n\nNümunə: #1d4ed8 yazılanda rgb və hsl də çıxır. rgb(29, 78, 216) yazsan, HEX geri gəlir.\n\nQısa HEX də olur: #abc uzun formaya açılır. Ad rəng, məsələn red, burada oxunmur.",
    "Converts a HEX, RGB, and HSL color code into the others.\n\nExample: #1d4ed8 also gives rgb and hsl. rgb(29, 78, 216) comes back as HEX.\n\nA short HEX works too: #abc opens into the long form. A name such as red is not read here.",
    "HEX, RGB ve HSL renk kodunu birbirine çevirir.\n\nÖrnek: #1d4ed8 yazılınca rgb ve hsl de çıkar. rgb(29, 78, 216) yazarsan HEX geri gelir.\n\nKısa HEX de olur: #abc uzun biçime açılır. red gibi ad burada okunmaz.",
    "يحوّل رمز اللون بين HEX وRGB وHSL.\n\nمثال: #1d4ed8 يعطي RGB وHSL أيضًا. rgb(29, 78, 216) يعود HEX.\n\nHEX القصير يعمل: #abc يُفتح إلى الشكل الطويل. اسم مثل red لا يُقرأ هنا.",
    "Переводит код цвета между HEX, RGB и HSL.\n\nПример: #1d4ed8 даёт ещё rgb и hsl. rgb(29, 78, 216) возвращается как HEX.\n\nКороткий HEX тоже работает: #abc раскрывается в длинный вид. Имя вроде red здесь не читается.",
  ),
  csv: L(
    "JSON siyahısını CSV cədvəlinə, CSV cədvəlini JSON siyahısına çevirir.",
    "Turns a JSON list into a CSV table, and a CSV table into a JSON list.",
    "JSON listesini CSV tablosuna, CSV tablosunu JSON listesine çevirir.",
    "يحوّل قائمة JSON إلى جدول CSV، وجدول CSV إلى قائمة JSON.",
    "Переводит список JSON в таблицу CSV, а таблицу CSV в список JSON.",
  ),
  base: L(
    "Ədədi 10-luq, 2-lik və 16-lıq formada göstərir.\n\nNümunə: 42 yazılanda 2-lik 101010, 16-lıq 2a olur. 0b101010 və 0x2a da eyni ədəddir.\n\nHərf olan kod onaltılıq sayılır. Mənfi ədəd və vergül qəbul olunmur.",
    "Shows a number in decimal, binary, and hex.\n\nExample: 42 becomes binary 101010 and hex 2a. 0b101010 and 0x2a are the same number.\n\nA code with a letter is read as hex. A minus and a comma are not accepted.",
    "Sayıyı 10'luk, 2'lik ve 16'lık biçimde gösterir.\n\nÖrnek: 42 yazılınca 2'lik 101010, 16'lık 2a olur. 0b101010 ve 0x2a aynı sayıdır.\n\nHarf olan kod onaltılık sayılır. Eksi sayı ve virgül kabul edilmez.",
    "يعرض العدد بالنظام العشري والثنائي والست عشري.\n\nمثال: 42 تعطي الثنائي 101010 والست عشري 2a. 0b101010 و0x2a هما العدد نفسه.\n\nالرمز الذي فيه حرف يُقرأ ست عشريًا. العدد السالب والفاصلة لا يُقبلان.",
    "Показывает число в десятичном, двоичном и шестнадцатеричном виде.\n\nПример: 42 даёт двоичное 101010 и шестнадцатеричное 2a. 0b101010 и 0x2a — то же число.\n\nКод с буквой читается как шестнадцатеричный. Минус и запятая не принимаются.",
  ),
  pxrem: L(
    "Piksel və rem ölçüsünü bir-birinə çevirir. Kök ölçü adətən 16-dır.\n\nNümunə: 16px yazılanda 1rem olur. 1.5rem yazılanda 24px olur.\n\nKök ölçünü dəyişsən, nəticə də dəyişir. 32px kökü 32 olanda 1rem edir.",
    "Converts pixels and rem. The root size is usually 16.\n\nExample: 16px becomes 1rem. 1.5rem becomes 24px.\n\nChange the root size and the result changes. 32px is 1rem when the root is 32.",
    "Piksel ve rem ölçüsünü birbirine çevirir. Kök ölçü genelde 16'dır.\n\nÖrnek: 16px yazılınca 1rem olur. 1.5rem yazılınca 24px olur.\n\nKök ölçüyü değiştirirsen sonuç da değişir. Kök 32 iken 32px 1rem eder.",
    "يحوّل البكسل وrem. حجم الجذر عادة 16.\n\nمثال: 16px تصبح 1rem. 1.5rem تصبح 24px.\n\nإذا غيّرت حجم الجذر تغيّرت النتيجة. 32px تساوي 1rem حين يكون الجذر 32.",
    "Переводит пиксели и rem. Корневой размер обычно 16.\n\nПример: 16px становится 1rem. 1.5rem становится 24px.\n\nСменишь корневой размер — сменится результат. 32px равны 1rem, когда корень 32.",
  ),
  jwt: L(
    "JWT tokenin başlığını və içini oxuyur. İmzanı yoxlamır və tokeni heç yerə göndərmir.\n\nToken üç hissədən ibarətdir: başlıq, iç və imza. Burada yalnız ilk iki hissə mətn olur.\n\nİmza yoxlanmadığı üçün bu səhifə tokenin doğru olduğunu demir. Şifrə və gizli açar bura yapışdırılmamalıdır.",
    "Reads the header and the inside of a JWT. It does not check the signature and does not send the token anywhere.\n\nA token has three parts: header, payload, and signature. Only the first two become text here.\n\nBecause the signature is not checked, this page does not say the token is valid. Do not paste a password or a secret key.",
    "JWT tokenin başlığını ve içini okur. İmzayı kontrol etmez ve tokeni hiçbir yere göndermez.\n\nToken üç parçadır: başlık, iç ve imza. Burada yalnız ilk iki parça metin olur.\n\nİmza kontrol edilmediği için bu sayfa tokenin doğru olduğunu söylemez. Parola ve gizli anahtar buraya yapıştırılmamalıdır.",
    "يقرأ رأس JWT وداخله. لا يفحص التوقيع ولا يرسل الرمز إلى أي مكان.\n\nالرمز ثلاثة أجزاء: الرأس والداخل والتوقيع. هنا يصبح الجزءان الأولان نصًا فقط.\n\nلأن التوقيع لا يُفحص، هذه الصفحة لا تقول إن الرمز صحيح. لا تلصق كلمة سر أو مفتاحًا سريًا.",
    "Читает заголовок и содержимое JWT. Подпись не проверяет и токен никуда не отправляет.\n\nУ токена три части: заголовок, содержимое и подпись. Здесь текстом становятся только первые две.\n\nПодпись не проверяется, поэтому страница не говорит, что токен верный. Пароль и секретный ключ сюда вставлять не нужно.",
  ),
  cron: L(
    "Cron sətrini insan dilinə çevirir. Beş yer olur: dəqiqə, saat, gün, ay, həftənin günü.\n\nNümunə: 0 9 * * 1 hər bazar ertəsi saat 09:00 deməkdir. Ulduz hər deməkdir.\n\nBu səhifə işi işlətmir, yalnız oxuyur. Serverə göndərmir.",
    "Turns a cron line into plain words. Five places: minute, hour, day, month, weekday.\n\nExample: 0 9 * * 1 means every Monday at 09:00. A star means every.\n\nThis page does not run the job. It only reads the line and does not send it anywhere.",
    "Cron satırını insan diline çevirir. Beş yer vardır: dakika, saat, gün, ay, haftanın günü.\n\nÖrnek: 0 9 * * 1 her pazartesi saat 09:00 demektir. Yıldız her demektir.\n\nBu sayfa işi çalıştırmaz, yalnız okur. Sunucuya göndermez.",
    "يحوّل سطر Cron إلى كلام واضح. خمسة مواضع: الدقيقة والساعة واليوم والشهر ويوم الأسبوع.\n\nمثال: 0 9 * * 1 يعني كل اثنين الساعة 09:00. النجمة تعني كل.\n\nهذه الصفحة لا تشغّل العمل. تقرأ السطر فقط ولا ترسله.",
    "Переводит строку cron на обычный язык. Пять мест: минута, час, день, месяц, день недели.\n\nПример: 0 9 * * 1 значит каждый понедельник в 09:00. Звезда значит каждый.\n\nСтраница работу не запускает. Только читает строку и никуда её не отправляет.",
  ),
  chmod: L(
    "755 və rwxr-xr-x bir-birinə çevirir. Üç rəqəm üç qrupdur: sahibi, qrup, qalanlar.\n\nNümunə: 755 yazılanda rwxr-xr-x olur. 7 oxu, yaz və işlət deməkdir. 5 oxu və işlət deməkdir.\n\nBu səhifə faylın icazəsini dəyişmir. Yalnız kodu göstərir.",
    "Converts 755 and rwxr-xr-x. Three digits are three groups: owner, group, others.\n\nExample: 755 becomes rwxr-xr-x. 7 means read, write, and run. 5 means read and run.\n\nThis page does not change a file. It only shows the code.",
    "755 ve rwxr-xr-x birbirine çevirir. Üç rakam üç gruptur: sahip, grup, diğerleri.\n\nÖrnek: 755 yazılınca rwxr-xr-x olur. 7 oku, yaz ve çalıştır demektir. 5 oku ve çalıştır demektir.\n\nBu sayfa dosyanın iznini değiştirmez. Yalnız kodu gösterir.",
    "يحوّل 755 وrwxr-xr-x. ثلاثة أرقام ثلاث مجموعات: المالك والمجموعة والباقون.\n\nمثال: 755 تصبح rwxr-xr-x. 7 تعني اقرأ واكتب وشغّل. 5 تعني اقرأ وشغّل.\n\nهذه الصفحة لا تغيّر إذن الملف. تعرض الرمز فقط.",
    "Переводит 755 и rwxr-xr-x. Три цифры — три группы: владелец, группа, остальные.\n\nПример: 755 становится rwxr-xr-x. 7 значит читать, писать и запускать. 5 значит читать и запускать.\n\nСтраница права файла не меняет. Только показывает код.",
  ),
  robots: L(
    "Saytın robots.txt faylını yazır. Boş buraxsan, bütün səhifələr açıq qalır.\n\nNümunə: /admin yazılanda bu yol bağlı olur. Hər yol ayrı sətirdədir.\n\nBu səhifə faylı serverə qoymur. Nəticəni kopyalayıb saytın kök qovluğuna robots.txt adı ilə qoyursan.",
    "Writes a site's robots.txt file. Leave it empty and every page stays open.\n\nExample: /admin closes that path. Each path is on its own line.\n\nThis page does not put the file on a server. Copy the result and save it as robots.txt in the site root.",
    "Sitenin robots.txt dosyasını yazar. Boş bırakırsan bütün sayfalar açık kalır.\n\nÖrnek: /admin yazılınca bu yol kapanır. Her yol ayrı satırdadır.\n\nBu sayfa dosyayı sunucuya koymaz. Sonucu kopyalayıp site köküne robots.txt adıyla koyarsın.",
    "يكتب ملف robots.txt للموقع. إذا تركته فارغًا تبقى كل الصفحات مفتوحة.\n\nمثال: /admin يغلق هذا المسار. كل مسار في سطر.\n\nهذه الصفحة لا تضع الملف على الخادم. انسخ النتيجة واحفظها باسم robots.txt في جذر الموقع.",
    "Пишет файл robots.txt сайта. Если оставить пустым, все страницы открыты.\n\nПример: /admin закрывает этот путь. Каждый путь на своей строке.\n\nСтраница не кладёт файл на сервер. Скопируй результат и сохрани как robots.txt в корне сайта.",
  ),
  contrast: L(
    "İki rəngin yazı üçün oxunub-oxunmadığını göstərir.\n\nNümunə: #111111 və #ffffff. Nəticə 4.5-dən böyükdürsə, adi yazı üçün AA keçir.\n\nBu səhifə rəngi dəyişmir. Yalnız fərqi hesablayır.",
    "Shows whether two colors are readable as text.\n\nExample: #111111 and #ffffff. If the result is over 4.5, normal text passes AA.\n\nThis page does not change the color. It only calculates the difference.",
    "İki rengin yazı için okunup okunmadığını gösterir.\n\nÖrnek: #111111 ve #ffffff. Sonuç 4.5'ten büyükse normal yazı AA geçer.\n\nBu sayfa rengi değiştirmez. Yalnız farkı hesaplar.",
    "يبيّن هل اللونان يُقرآن كنص.\n\nمثال: #111111 و#ffffff. إذا كانت النتيجة أكبر من 4.5 يجتاز النص العادي AA.\n\nهذه الصفحة لا تغيّر اللون. تحسب الفرق فقط.",
    "Показывает, читаются ли два цвета как текст.\n\nПример: #111111 и #ffffff. Если результат больше 4.5, обычный текст проходит AA.\n\nСтраница цвет не меняет. Только считает разницу.",
  ),
  slug: L(
    "Başlıqdan ünvan düzəldir. Boşluq xətt olur, böyük hərf kiçilir.\n\nNümunə: Mənim ilk səhifəm yazılanda menim-ilk-sehifem olur.\n\nə, ö, ü, ş, ç, ğ latın hərfə keçir. Bu səhifə ünvanı sayta yazmır.",
    "Makes an address from a title. A space becomes a hyphen and capitals become small.\n\nExample: Mənim ilk səhifəm becomes menim-ilk-sehifem.\n\nə, ö, ü, ş, ç and ğ become Latin letters. This page does not write the address onto a site.",
    "Başlıktan adres kurar. Boşluk çizgi olur, büyük harf küçülür.\n\nÖrnek: Mənim ilk səhifəm yazılınca menim-ilk-sehifem olur.\n\nə, ö, ü, ş, ç, ğ Latin harfe döner. Bu sayfa adresi siteye yazmaz.",
    "يصنع عنوانًا من العنوان. الفراغ يصبح شرطة والحرف الكبير يصغر.\n\nمثال: Mənim ilk səhifəm تصبح menim-ilk-sehifem.\n\nə وö وü وş وç وğ تصبح حروفًا لاتينية. هذه الصفحة لا تكتب العنوان في الموقع.",
    "Делает адрес из заголовка. Пробел становится чёрточкой, большие буквы маленькими.\n\nПример: Mənim ilk səhifəm становится menim-ilk-sehifem.\n\nə, ö, ü, ş, ç, ğ переходят в латиницу. Страница адрес на сайт не пишет.",
  ),
  percent: L(
    "Faiz hesablayır. 15 200 yazsan, 200-ün 15 faizi çıxır. 80/100 yazsan, 80-in 100-ə nisbəti çıxır.\n\nNümunə: 15 200 nəticəsi 30 olur. 80/100 nəticəsi 80% olur.\n\nBu səhifə pul saxlamır. Yalnız rəqəmi hesablayır.",
    "Calculates a percent. 15 200 is 15 percent of 200. 80/100 is how much 80 is of 100.\n\nExample: 15 200 gives 30. 80/100 gives 80%.\n\nThis page does not store money. It only calculates the number.",
    "Yüzde hesaplar. 15 200 yazarsan 200'ün yüzde 15'i çıkar. 80/100 yazarsan 80'in 100'e oranı çıkar.\n\nÖrnek: 15 200 sonucu 30 olur. 80/100 sonucu %80 olur.\n\nBu sayfa para saklamaz. Yalnız sayıyı hesaplar.",
    "يحسب النسبة. 15 200 تعني 15 بالمئة من 200. 80/100 تعني كم 80 من 100.\n\nمثال: 15 200 تعطي 30. 80/100 تعطي 80%.\n\nهذه الصفحة لا تحفظ مالًا. تحسب الرقم فقط.",
    "Считает процент. 15 200 — это 15 процентов от 200. 80/100 — сколько 80 от 100.\n\nПример: 15 200 даёт 30. 80/100 даёт 80%.\n\nСтраница деньги не хранит. Только считает число.",
  ),
  mime: L(
    "Fayl sonundan MIME kodunu göstərir.\n\nNümunə: png yazılanda image/png olur. pdf yazılanda application/pdf olur.\n\nBurada tanınan sonlar: png, jpg, gif, webp, svg, pdf, json, xml, html, css, js, txt, csv, zip, mp3, mp4, woff2.",
    "Shows the MIME code from a file ending.\n\nExample: png becomes image/png. pdf becomes application/pdf.\n\nKnown endings here: png, jpg, gif, webp, svg, pdf, json, xml, html, css, js, txt, csv, zip, mp3, mp4, woff2.",
    "Dosya sonundan MIME kodunu gösterir.\n\nÖrnek: png yazılınca image/png olur. pdf yazılınca application/pdf olur.\n\nBurada bilinen sonlar: png, jpg, gif, webp, svg, pdf, json, xml, html, css, js, txt, csv, zip, mp3, mp4, woff2.",
    "يُظهر رمز MIME من نهاية الملف.\n\nمثال: png تصبح image/png. pdf تصبح application/pdf.\n\nالنهايات المعروفة هنا: png وjpg وgif وwebp وsvg وpdf وjson وxml وhtml وcss وjs وtxt وcsv وzip وmp3 وmp4 وwoff2.",
    "Показывает код MIME по окончанию файла.\n\nПример: png становится image/png. pdf становится application/pdf.\n\nЗдесь известны: png, jpg, gif, webp, svg, pdf, json, xml, html, css, js, txt, csv, zip, mp3, mp4, woff2.",
  ),
  meta: L(
    "Başlıq və təsvirdən title və Open Graph sətirlərini yazır.\n\nNümunə: başlıq Nibras Code, təsvir Pulsuz kod alətləri. Şəkil ünvanı boş qala bilər.\n\nBu səhifə səhifəni dərc etmir. Sətirləri kopyalayıb head içinə qoyursan.",
    "Writes title and Open Graph lines from a title and a description.\n\nExample: title Nibras Code, description Free code tools. The image address can stay empty.\n\nThis page does not publish the page. Copy the lines into head.",
    "Başlık ve açıklamadan title ve Open Graph satırlarını yazar.\n\nÖrnek: başlık Nibras Code, açıklama Ücretsiz kod araçları. Resim adresi boş kalabilir.\n\nBu sayfa sayfayı yayınlamaz. Satırları kopyalayıp head içine koyarsın.",
    "يكتب أسطر title وOpen Graph من عنوان ووصف.\n\nمثال: العنوان Nibras Code والوصف أدوات كود مجانية. عنوان الصورة يمكن أن يبقى فارغًا.\n\nهذه الصفحة لا تنشر الصفحة. انسخ الأسطر إلى head.",
    "Пишет строки title и Open Graph из заголовка и описания.\n\nПример: заголовок Nibras Code, описание Бесплатные инструменты. Адрес картинки можно оставить пустым.\n\nСтраница не публикует сайт. Скопируй строки в head.",
  ),
  sitemap: L(
    "Səhifə ünvanlarından sitemap.xml yazır. Hər ünvan ayrı sətirdədir.\n\nNümunə: https://www.nibrascode.com/tools. Yalnız http və https qəbul olunur.\n\nBu səhifə faylı serverə qoymur. Nəticəni sitemap.xml adı ilə yükləyə bilərsən.",
    "Writes sitemap.xml from page addresses. Each address is on its own line.\n\nExample: https://www.nibrascode.com/tools. Only http and https are accepted.\n\nThis page does not put the file on a server. You can download the result as sitemap.xml.",
    "Sayfa adreslerinden sitemap.xml yazar. Her adres ayrı satırdadır.\n\nÖrnek: https://www.nibrascode.com/tools. Yalnız http ve https kabul edilir.\n\nBu sayfa dosyayı sunucuya koymaz. Sonucu sitemap.xml adıyla indirebilirsin.",
    "يكتب sitemap.xml من عناوين الصفحات. كل عنوان في سطر.\n\nمثال: https://www.nibrascode.com/tools. لا يُقبل إلا http وhttps.\n\nهذه الصفحة لا تضع الملف على الخادم. يمكن تنزيل النتيجة باسم sitemap.xml.",
    "Пишет sitemap.xml из адресов страниц. Каждый адрес на своей строке.\n\nПример: https://www.nibrascode.com/tools. Принимаются только http и https.\n\nСтраница не кладёт файл на сервер. Результат можно скачать как sitemap.xml.",
  ),
  utm: L(
    "Linkə utm_source və utm_campaign əlavə edir.\n\nNümunə: https://www.nibrascode.com, mənbə google, kampaniya ders. Nəticə linkin sonuna bu iki sözü qoyur.\n\nBu səhifə linki açmır və heç yerə göndərmir.",
    "Adds utm_source and utm_campaign to a link.\n\nExample: https://www.nibrascode.com, source google, campaign ders. The result puts those two words on the end of the link.\n\nThis page does not open the link and does not send it anywhere.",
    "Linke utm_source ve utm_campaign ekler.\n\nÖrnek: https://www.nibrascode.com, kaynak google, kampanya ders. Sonuç bu iki sözü linkin sonuna koyar.\n\nBu sayfa linki açmaz ve hiçbir yere göndermez.",
    "يضيف utm_source وutm_campaign إلى الرابط.\n\nمثال: https://www.nibrascode.com والمصدر google والحملة ders. النتيجة تضع الكلمتين في آخر الرابط.\n\nهذه الصفحة لا تفتح الرابط ولا ترسله إلى أي مكان.",
    "Добавляет utm_source и utm_campaign к ссылке.\n\nПример: https://www.nibrascode.com, источник google, кампания ders. Результат ставит эти два слова в конец ссылки.\n\nСтраница ссылку не открывает и никуда не отправляет.",
  ),
  days: L(
    "İki tarixin arasındakı günü göstərir.\n\nNümunə: 2026-01-01 və 2026-01-31. Nəticə 30 gündür.\n\nTarix il-ay-gün şəklində yazılır. Bu səhifə təqvim saxlamır.",
    "Shows the days between two dates.\n\nExample: 2026-01-01 and 2026-01-31. The result is 30 days.\n\nWrite the date as year-month-day. This page does not keep a calendar.",
    "İki tarihin arasındaki günü gösterir.\n\nÖrnek: 2026-01-01 ve 2026-01-31. Sonuç 30 gündür.\n\nTarih yıl-ay-gün biçiminde yazılır. Bu sayfa takvim saklamaz.",
    "يُظهر الأيام بين تاريخين.\n\nمثال: 2026-01-01 و2026-01-31. النتيجة 30 يومًا.\n\nيُكتب التاريخ سنة-شهر-يوم. هذه الصفحة لا تحفظ تقويمًا.",
    "Показывает дни между двумя датами.\n\nПример: 2026-01-01 и 2026-01-31. Результат — 30 дней.\n\nДата пишется год-месяц-день. Страница календарь не хранит.",
  ),
  shadow: L(
    "Rəqəmlərdən box-shadow sətri çıxarır.\n\nNümunə: 8 16 24 #111111. Birinci yana, ikinci aşağı, üçüncü yayılma, sonuncu rəngdir.\n\nBu səhifə CSS faylını dəyişmir. Sətri kopyalayıb qaydaya qoyursan.",
    "Makes a box-shadow line from numbers.\n\nExample: 8 16 24 #111111. The first is sideways, the second is down, the third is blur, the last is the color.\n\nThis page does not change a CSS file. Copy the line into a rule.",
    "Rakamlardan box-shadow satırı çıkarır.\n\nÖrnek: 8 16 24 #111111. Birinci yana, ikinci aşağı, üçüncü yayılma, sonuncu renktir.\n\nBu sayfa CSS dosyasını değiştirmez. Satırı kopyalayıp kurala koyarsın.",
    "يصنع سطر box-shadow من أرقام.\n\nمثال: 8 16 24 #111111. الأول للجانب والثاني للأسفل والثالث للانتشار والأخير للون.\n\nهذه الصفحة لا تغيّر ملف CSS. انسخ السطر إلى قاعدة.",
    "Делает строку box-shadow из чисел.\n\nПример: 8 16 24 #111111. Первое вбок, второе вниз, третье размытие, последнее цвет.\n\nСтраница CSS-файл не меняет. Скопируй строку в правило.",
  ),
  htaccess: L(
    "Köhnə ünvandan yeni ünvana Redirect 301 sətri yazır.\n\nNümunə: /eski və /yeni. Nəticəni .htaccess faylına qoyursan.\n\nBu səhifə serveri dəyişmir. Sətri özün əlavə edirsən.",
    "Writes a Redirect 301 line from an old address to a new one.\n\nExample: /eski and /yeni. You put the result in the .htaccess file.\n\nThis page does not change a server. You add the line yourself.",
    "Eski adresten yeni adrese Redirect 301 satırı yazar.\n\nÖrnek: /eski ve /yeni. Sonucu .htaccess dosyasına koyarsın.\n\nBu sayfa sunucuyu değiştirmez. Satırı sen eklersin.",
    "يكتب سطر Redirect 301 من عنوان قديم إلى جديد.\n\nمثال: /eski و/yeni. تضع النتيجة في ملف htaccess.\n\nهذه الصفحة لا تغيّر الخادم. أنت تضيف السطر.",
    "Пишет строку Redirect 301 со старого адреса на новый.\n\nПример: /eski и /yeni. Результат кладут в файл .htaccess.\n\nСтраница сервер не меняет. Строку добавляешь сам.",
  ),
  gradient: L(
    "İki rəngdən linear-gradient sətri çıxarır.\n\nNümunə: #111111 və #ffffff. Nəticə soldan sağa keçid olur.\n\nBu səhifə CSS faylını dəyişmir. Sətri kopyalayıb qaydaya qoyursan.",
    "Makes a linear-gradient line from two colors.\n\nExample: #111111 and #ffffff. The result goes from left to right.\n\nThis page does not change a CSS file. Copy the line into a rule.",
    "İki renkten linear-gradient satırı çıkarır.\n\nÖrnek: #111111 ve #ffffff. Sonuç soldan sağa geçer.\n\nBu sayfa CSS dosyasını değiştirmez. Satırı kopyalayıp kurala koyarsın.",
    "يصنع سطر linear-gradient من لونين.\n\nمثال: #111111 و#ffffff. النتيجة تنتقل من اليسار إلى اليمين.\n\nهذه الصفحة لا تغيّر ملف CSS. انسخ السطر إلى قاعدة.",
    "Делает строку linear-gradient из двух цветов.\n\nПример: #111111 и #ffffff. Результат идёт слева направо.\n\nСтраница CSS-файл не меняет. Скопируй строку в правило.",
  ),
  strength: L(
    "Şifrənin qısa, təkrar və ya zəif olduğunu göstərir. Şifrəni saxlamır.\n\nNümunə: 123456 zəif sayılır. Uzun, böyük hərf, rəqəm və simvol olan şifrə yoxlamadan keçir.\n\nBu səhifə şifrəni heç yerə göndərmir.",
    "Shows if a password is short, repeated, or weak. It does not save the password.\n\nExample: 123456 counts as weak. A long password with a capital, a digit, and a symbol passes the check.\n\nThis page does not send the password anywhere.",
    "Parolanın kısa, tekrarlı veya zayıf olduğunu gösterir. Parolayı saklamaz.\n\nÖrnek: 123456 zayıf sayılır. Uzun, büyük harf, rakam ve simvol olan parola kontrolden geçer.\n\nBu sayfa parolayı hiçbir yere göndermez.",
    "يُظهر إن كانت كلمة السر قصيرة أو مكررة أو ضعيفة. لا يحفظها.\n\nمثال: 123456 تُعد ضعيفة. كلمة طويلة فيها حرف كبير ورقم ورمز تجتاز الفحص.\n\nهذه الصفحة لا ترسل كلمة السر إلى أي مكان.",
    "Показывает, короткий, повторный или слабый пароль. Пароль не сохраняет.\n\nПример: 123456 считается слабым. Длинный пароль с большой буквой, цифрой и символом проходит проверку.\n\nСтраница пароль никуда не отправляет.",
  ),
  table: L(
    "Vergüllə ayrılmış mətndən HTML cədvəli çıxarır.\n\nNümunə: ad,yaş sonra Aysel,20. Birinci sətir başlıq olur.\n\nBu səhifə cədvəli sayta qoymur. Kodu kopyalayıb HTML içinə qoyursan.",
    "Makes an HTML table from comma-separated text.\n\nExample: name,age then Aysel,20. The first line becomes the heading.\n\nThis page does not put the table on a site. Copy the code into HTML.",
    "Virgülle ayrılmış metinden HTML tablosu çıkarır.\n\nÖrnek: ad,yaş sonra Aysel,20. İlk satır başlık olur.\n\nBu sayfa tabloyu siteye koymaz. Kodu kopyalayıp HTML içine koyarsın.",
    "يصنع جدول HTML من نص مفصول بفواصل.\n\nمثال: ad,yaş ثم Aysel,20. السطر الأول يصبح عنوانًا.\n\nهذه الصفحة لا تضع الجدول في الموقع. انسخ الكود إلى HTML.",
    "Делает таблицу HTML из текста через запятую.\n\nПример: ad,yaş затем Aysel,20. Первая строка становится заголовком.\n\nСтраница таблицу на сайт не ставит. Скопируй код в HTML.",
  ),
  radius: L(
    "Rəqəmdən border-radius sətri çıxarır.\n\nNümunə: 12 yazılanda border-radius: 12px; olur. Düymə və kartın küncünü yuvarlaq etmək üçün işlənir.\n\nBu səhifə CSS faylını dəyişmir. Sətri kopyalayıb qaydaya qoyursan.",
    "Makes a border-radius line from a number.\n\nExample: 12 becomes border-radius: 12px;. It rounds the corner of a button or a card.\n\nThis page does not change a CSS file. Copy the line into a rule.",
    "Rakamdan border-radius satırı çıkarır.\n\nÖrnek: 12 yazılınca border-radius: 12px; olur. Düğme ve kartın köşesini yuvarlamak için kullanılır.\n\nBu sayfa CSS dosyasını değiştirmez. Satırı kopyalayıp kurala koyarsın.",
    "يصنع سطر border-radius من رقم.\n\nمثال: 12 تصبح border-radius: 12px;. تُستخدم لتدوير زاوية زر أو بطاقة.\n\nهذه الصفحة لا تغيّر ملف CSS. انسخ السطر إلى قاعدة.",
    "Делает строку border-radius из числа.\n\nПример: 12 становится border-radius: 12px;. Скругляет угол кнопки или карточки.\n\nСтраница CSS-файл не меняет. Скопируй строку в правило.",
  ),
  trim: L(
    "Mətnin əvvəlindəki, sonundakı və sətir arasındakı artıq boşluğu silir.\n\nNümunə: iki boşluqla yazılmış Salam dünya bir boşluqla qalır.\n\nSətirlərin özü silinmir. Yalnız artıq boşluq gedir.",
    "Removes extra spaces at the start, at the end, and between words.\n\nExample: Salam dünya written with two spaces stays with one space.\n\nThe lines themselves stay. Only the extra space goes.",
    "Metnin başındaki, sonundaki ve satır arasındaki fazla boşluğu siler.\n\nÖrnek: iki boşlukla yazılmış Salam dünya bir boşlukla kalır.\n\nSatırların kendisi silinmez. Yalnız fazla boşluk gider.",
    "يحذف الفراغ الزائد في أول النص وآخره وبين الكلمات.\n\nمثال: Salam dünya المكتوبة بفراغين تبقى بفراغ واحد.\n\nالأسطر نفسها لا تُحذف. يذهب الفراغ الزائد فقط.",
    "Убирает лишние пробелы в начале, в конце и между словами.\n\nПример: Salam dünya с двумя пробелами остаётся с одним.\n\nСами строки не удаляются. Уходит только лишний пробел.",
  ),
  lines: L(
    "Hər sətirin əvvəlinə nömrə qoyur.\n\nNümunə: üç sətir 1, 2 və 3 olur. Səhvi göstərəndə sətir nömrəsini demək üçün işlənir.\n\nBu səhifə kodu işlətmir. Yalnız nömrə yazır.",
    "Puts a number at the start of each line.\n\nExample: three lines become 1, 2 and 3. It is used when you need to point at a line.\n\nThis page does not run the code. It only writes the numbers.",
    "Her satırın başına numara koyar.\n\nÖrnek: üç satır 1, 2 ve 3 olur. Hatayı gösterirken satır numarasını söylemek için kullanılır.\n\nBu sayfa kodu çalıştırmaz. Yalnız numara yazar.",
    "يضع رقمًا في أول كل سطر.\n\nمثال: ثلاثة أسطر تصبح 1 و2 و3. يُستخدم عند الإشارة إلى سطر.\n\nهذه الصفحة لا تشغّل الكود. تكتب الأرقام فقط.",
    "Ставит номер в начало каждой строки.\n\nПример: три строки становятся 1, 2 и 3. Нужно, когда указываешь на строку.\n\nСтраница код не запускает. Только пишет номера.",
  ),
  jsoncsv: L(
    "JSON siyahısından CSV cədvəli çıxarır.\n\nNümunə: ad və yaş olan bir obyekt birinci sətirdə ad,yaş, ikinci sətirdə dəyərləri olur.\n\nCSV-dən JSON ayrıca alətdir. Bu onun əksidir.",
    "Makes a CSV table from a JSON list.\n\nExample: an object with name and age puts name,age on the first line and the values on the second.\n\nCSV to JSON is a separate tool. This is the other way.",
    "JSON listesinden CSV tablosu çıkarır.\n\nÖrnek: ad ve yaş olan bir nesne ilk satırda ad,yaş, ikinci satırda değerleri olur.\n\nCSV'den JSON ayrı araçtır. Bu onun tersidir.",
    "يصنع جدول CSV من قائمة JSON.\n\nمثال: كائن فيه اسم وعمر يضع ad,yaş في السطر الأول والقيم في الثاني.\n\nمن CSV إلى JSON أداة منفصلة. هذه هي الجهة الأخرى.",
    "Делает таблицу CSV из списка JSON.\n\nПример: объект с именем и возрастом ставит ad,yaş в первую строку, значения во вторую.\n\nCSV в JSON — отдельный инструмент. Это обратная сторона.",
  ),
  palette: L(
    "Bir rəngdən açıq və tünd variant çıxarır.\n\nNümunə: #1d4ed8. Birinci sətir özüdür, ikinci açıq, üçüncü tünddür.\n\nBu səhifə şəkli dəyişmir. Yalnız üç kod göstərir.",
    "Makes a lighter and a darker variant from one color.\n\nExample: #1d4ed8. The first line is the color, the second is lighter, the third is darker.\n\nThis page does not change a picture. It only shows three codes.",
    "Bir renkten açık ve koyu varyant çıkarır.\n\nÖrnek: #1d4ed8. İlk satır kendisi, ikinci açık, üçüncü koyudur.\n\nBu sayfa resmi değiştirmez. Yalnız üç kod gösterir.",
    "يصنع درجة أفتح وأغمق من لون واحد.\n\nمثال: #1d4ed8. السطر الأول اللون نفسه والثاني أفتح والثالث أغمق.\n\nهذه الصفحة لا تغيّر صورة. تُظهر ثلاثة رموز فقط.",
    "Делает более светлый и более тёмный вариант из одного цвета.\n\nПример: #1d4ed8. Первая строка — сам цвет, вторая светлее, третья темнее.\n\nСтраница картинку не меняет. Только показывает три кода.",
  ),
  htmlfmt: L(
    "HTML kodunu sətirlərə ayırır. Hər etiket öz yerində durur.\n\nNümunə: <p><b>Salam</b></p> yazılanda p və b ayrı sətirə düşür.\n\nHTML kodu aləti işarəni gizlədir. Bu səhifə yalnız düzəldir.",
    "Breaks HTML onto lines. Each tag sits in its place.\n\nExample: <p><b>Salam</b></p> puts p and b on separate lines.\n\nThe HTML code tool hides a sign. This page only formats.",
    "HTML kodunu satırlara ayırır. Her etiket kendi yerinde durur.\n\nÖrnek: <p><b>Salam</b></p> yazılınca p ve b ayrı satıra düşer.\n\nHTML kodu aracı işareti gizler. Bu sayfa yalnız düzenler.",
    "يفصل HTML على أسطر. كل وسم يقف في مكانه.\n\nمثال: <p><b>Salam</b></p> يضع p وb في سطرين.\n\nأداة كود HTML تخفي العلامة. هذه الصفحة تنسّق فقط.",
    "Разбивает HTML на строки. Каждый тег стоит на своём месте.\n\nПример: <p><b>Salam</b></p> ставит p и b на разные строки.\n\nИнструмент кода HTML прячет знак. Эта страница только оформляет.",
  ),
  "js-min": L(
    "JavaScript-dən boşluq və şərhi çıxarır. Bir sətirdə qalır.\n\nNümunə: function salam() { return 1; } yazılanda boşluqlar gedir.\n\nBu səhifə kodu işlətmir. Yalnız sıxır.",
    "Removes spaces and comments from JavaScript. It stays on one line.\n\nExample: function salam() { return 1; } loses the spaces.\n\nThis page does not run the code. It only minifies.",
    "JavaScript'ten boşluk ve yorumu çıkarır. Tek satırda kalır.\n\nÖrnek: function salam() { return 1; } yazılınca boşluklar gider.\n\nBu sayfa kodu çalıştırmaz. Yalnız sıkıştırır.",
    "يحذف الفراغ والتعليق من JavaScript. يبقى في سطر واحد.\n\nمثال: function salam() { return 1; } تفقد الفراغات.\n\nهذه الصفحة لا تشغّل الكود. تضغط فقط.",
    "Убирает пробелы и комментарии из JavaScript. Остаётся одна строка.\n\nПример: function salam() { return 1; } теряет пробелы.\n\nСтраница код не запускает. Только сжимает.",
  ),
  python: L(
    "Python kodunun sətir sonundakı boşluğu silir və tabı dörd boşluğa çevirir.\n\nNümunə: print(\"Salam\") olduğu kimi qalır, artıq boşluq gedir.\n\nBu səhifə Python-u işlətmir. Yalnız sətiri düzəldir.",
    "Removes the space at the end of a Python line and turns a tab into four spaces.\n\nExample: print(\"Salam\") stays as it is, the extra space goes.\n\nThis page does not run Python. It only cleans the lines.",
    "Python kodunun satır sonundaki boşluğu siler ve tabı dört boşluğa çevirir.\n\nÖrnek: print(\"Salam\") olduğu gibi kalır, fazla boşluk gider.\n\nBu sayfa Python'u çalıştırmaz. Yalnız satırı düzeltir.",
    "يحذف الفراغ في آخر سطر Python ويحوّل tab إلى أربعة فراغات.\n\nمثال: print(\"Salam\") يبقى كما هو ويذهب الفراغ الزائد.\n\nهذه الصفحة لا تشغّل Python. تنظّف الأسطر فقط.",
    "Убирает пробел в конце строки Python и превращает tab в четыре пробела.\n\nПример: print(\"Salam\") остаётся как есть, лишний пробел уходит.\n\nСтраница Python не запускает. Только чистит строки.",
  ),
  php: L(
    "PHP kodunu sətirlərə ayırır. Mötərizə öz sətirində durur.\n\nNümunə: <?php echo \"Salam\"; yazılanda sətirlər ayrılır.\n\nBu səhifə PHP-ni işlətmir. Yalnız düzəldir.",
    "Breaks PHP onto lines. A brace sits on its own line.\n\nExample: <?php echo \"Salam\"; gets split onto lines.\n\nThis page does not run PHP. It only formats.",
    "PHP kodunu satırlara ayırır. Parantez kendi satırında durur.\n\nÖrnek: <?php echo \"Salam\"; yazılınca satırlar ayrılır.\n\nBu sayfa PHP'yi çalıştırmaz. Yalnız düzenler.",
    "يفصل PHP على أسطر. القوس يقف في سطره.\n\nمثال: <?php echo \"Salam\"; ينقسم على أسطر.\n\nهذه الصفحة لا تشغّل PHP. تنسّق فقط.",
    "Разбивает PHP на строки. Скобка стоит на своей строке.\n\nПример: <?php echo \"Salam\"; делится на строки.\n\nСтраница PHP не запускает. Только оформляет.",
  ),
  "sql-min": L(
    "SQL mətnindən boşluq və şərhi çıxarır. Bir sətirdə qalır.\n\nNümunə: select ad from istifadeci yazılanda boşluqlar birə enir.\n\nSQL düzəlt aləti sətirlərə ayırır. Bu səhifə sıxır.",
    "Removes spaces and comments from SQL. It stays on one line.\n\nExample: select ad from istifadeci keeps one space between words.\n\nThe SQL formatter breaks lines. This page minifies.",
    "SQL metninden boşluk ve yorumu çıkarır. Tek satırda kalır.\n\nÖrnek: select ad from istifadeci yazılınca boşluklar bire iner.\n\nSQL düzenle aracı satırlara ayırır. Bu sayfa sıkıştırır.",
    "يحذف الفراغ والتعليق من SQL. يبقى في سطر واحد.\n\nمثال: select ad from istifadeci يبقى فراغ واحد بين الكلمات.\n\nأداة تنسيق SQL تفصل الأسطر. هذه الصفحة تضغط.",
    "Убирает пробелы и комментарии из SQL. Остаётся одна строка.\n\nПример: select ad from istifadeci оставляет один пробел между словами.\n\nФормат SQL разбивает строки. Эта страница сжимает.",
  ),
  "xml-min": L(
    "XML mətnindən boşluğu və şərhi çıxarır.\n\nNümunə: <ad>Aysel</ad> bir sətirdə qalır.\n\nXML düzəlt aləti sətirlərə ayırır. Bu səhifə sıxır.",
    "Removes spaces and comments from XML.\n\nExample: <ad>Aysel</ad> stays on one line.\n\nThe XML formatter breaks lines. This page minifies.",
    "XML metninden boşluğu ve yorumu çıkarır.\n\nÖrnek: <ad>Aysel</ad> tek satırda kalır.\n\nXML düzenle aracı satırlara ayırır. Bu sayfa sıkıştırır.",
    "يحذف الفراغ والتعليق من XML.\n\nمثال: <ad>Aysel</ad> يبقى في سطر واحد.\n\nأداة تنسيق XML تفصل الأسطر. هذه الصفحة تضغط.",
    "Убирает пробелы и комментарии из XML.\n\nПример: <ad>Aysel</ad> остаётся одной строкой.\n\nФормат XML разбивает строки. Эта страница сжимает.",
  ),
  cssvar: L(
    "Rəngdən CSS dəyişən sətri çıxarır.\n\nNümunə: #1d4ed8 yazılanda --reng: #1d4ed8; olur.\n\nBu səhifə CSS faylını dəyişmir. Sətri kopyalayıb :root içinə qoyursan.",
    "Makes a CSS variable line from a color.\n\nExample: #1d4ed8 becomes --reng: #1d4ed8;.\n\nThis page does not change a CSS file. Copy the line into :root.",
    "Renkten CSS değişken satırı çıkarır.\n\nÖrnek: #1d4ed8 yazılınca --reng: #1d4ed8; olur.\n\nBu sayfa CSS dosyasını değiştirmez. Satırı kopyalayıp :root içine koyarsın.",
    "يصنع سطر متغير CSS من لون.\n\nمثال: #1d4ed8 تصبح --reng: #1d4ed8;.\n\nهذه الصفحة لا تغيّر ملف CSS. انسخ السطر إلى :root.",
    "Делает строку переменной CSS из цвета.\n\nПример: #1d4ed8 становится --reng: #1d4ed8;.\n\nСтраница CSS-файл не меняет. Скопируй строку в :root.",
  ),
  link: L(
    "Ünvanın http ilə başlayıb-başlamadığını və boşluq olub-olmadığını göstərir. Saytı açmır.\n\nNümunə: https://www.nibrascode.com yoxlamadan keçir. nibrascode.com http olmadığı üçün keçmir.\n\nBu səhifə linki heç yerə göndərmir.",
    "Shows whether an address starts with http and whether it has a space. It does not open the site.\n\nExample: https://www.nibrascode.com passes. nibrascode.com fails because it has no http.\n\nThis page does not send the link anywhere.",
    "Adresin http ile başlayıp başlamadığını ve boşluk olup olmadığını gösterir. Siteyi açmaz.\n\nÖrnek: https://www.nibrascode.com kontrolden geçer. nibrascode.com http olmadığı için geçmez.\n\nBu sayfa linki hiçbir yere göndermez.",
    "يُظهر هل يبدأ العنوان بـ http وهل فيه فراغ. لا يفتح الموقع.\n\nمثال: https://www.nibrascode.com يجتاز. nibrascode.com لا يجتاز لأنه بلا http.\n\nهذه الصفحة لا ترسل الرابط إلى أي مكان.",
    "Показывает, начинается ли адрес с http и есть ли в нём пробел. Сайт не открывает.\n\nПример: https://www.nibrascode.com проходит. nibrascode.com не проходит, потому что нет http.\n\nСтраница ссылку никуда не отправляет.",
  ),
  chars: L(
    "Mətnin simvol sayını və 160 limitini göstərir. Meta təsviri üçün işlənir.\n\nNümunə: Salam 5 simvoldur və limitin içindədir.\n\nSöz sayğacı sözü sayır. Bu səhifə simvolu sayır.",
    "Shows the character count and a limit of 160. It is used for a meta description.\n\nExample: Salam is 5 characters and inside the limit.\n\nThe word counter counts words. This page counts characters.",
    "Metnin karakter sayısını ve 160 limitini gösterir. Meta açıklaması için kullanılır.\n\nÖrnek: Salam 5 karakterdir ve limitin içindedir.\n\nSöz sayacı sözü sayar. Bu sayfa karakteri sayar.",
    "يُظهر عدد الحروف وحد 160. يُستخدم لوصف meta.\n\nمثال: Salam خمسة حروف وداخل الحد.\n\nعدّاد الكلمات يعد الكلمات. هذه الصفحة تعد الحروف.",
    "Показывает число символов и лимит 160. Нужно для meta-описания.\n\nПример: Salam — 5 символов и внутри лимита.\n\nСчётчик слов считает слова. Эта страница считает символы.",
  ),
  yaml: L(
    "YAML mətninin sətir sonundakı boşluğu silir və tabı iki boşluğa çevirir.\n\nNümunə: ad: Aysel olduğu kimi qalır, artıq boşluq gedir.\n\nBu səhifə YAML-ı işlətmir. Yalnız sətiri düzəldir.",
    "Removes the space at the end of a YAML line and turns a tab into two spaces.\n\nExample: ad: Aysel stays as it is, the extra space goes.\n\nThis page does not run YAML. It only cleans the lines.",
    "YAML satırının sonundaki boşluğu siler ve tabı iki boşluğa çevirir.\n\nÖrnek: ad: Aysel olduğu gibi kalır, fazla boşluk gider.\n\nBu sayfa YAML'ı çalıştırmaz. Yalnız satırı düzeltir.",
    "يحذف الفراغ في آخر سطر YAML ويحوّل tab إلى فراغين.\n\nمثال: ad: Aysel يبقى كما هو ويذهب الفراغ الزائد.\n\nهذه الصفحة لا تشغّل YAML. تنظّف الأسطر فقط.",
    "Убирает пробел в конце строки YAML и превращает tab в два пробела.\n\nПример: ad: Aysel остаётся как есть, лишний пробел уходит.\n\nСтраница YAML не запускает. Только чистит строки.",
  ),
  markdown: L(
    "Markdown-dan sadə HTML çıxarır. Başlıq, qalın və əlaqə tanınır.\n\nNümunə: # Salam yazılanda h1 olur. **qalın** strong olur.\n\nBu səhifə səhifəni dərc etmir. Kodu kopyalayıb HTML içinə qoyursan.",
    "Makes simple HTML from Markdown. A heading, bold text, and a link are recognized.\n\nExample: # Salam becomes h1. **bold** becomes strong.\n\nThis page does not publish a page. Copy the code into HTML.",
    "Markdown'dan basit HTML çıkarır. Başlık, kalın ve bağlantı tanınır.\n\nÖrnek: # Salam yazılınca h1 olur. **kalın** strong olur.\n\nBu sayfa sayfayı yayınlamaz. Kodu kopyalayıp HTML içine koyarsın.",
    "يصنع HTML بسيطًا من Markdown. يُعرف العنوان والخط العريض والرابط.\n\nمثال: # Salam تصبح h1. **qalın** تصبح strong.\n\nهذه الصفحة لا تنشر صفحة. انسخ الكود إلى HTML.",
    "Делает простой HTML из Markdown. Заголовок, жирный текст и ссылка узнаются.\n\nПример: # Salam становится h1. **qalın** становится strong.\n\nСтраница сайт не публикует. Скопируй код в HTML.",
  ),
  email: L(
    "E-poçtda @ və nöqtə olub-olmadığını göstərir. Məktub göndərmir.\n\nNümunə: aysel@nibrascode.com yoxlamadan keçir. aysel@sayt keçmir, çünki domendə nöqtə yoxdur.\n\nBu səhifə ünvanı heç yerə göndərmir.",
    "Shows whether an email has @ and a dot. It does not send a letter.\n\nExample: aysel@nibrascode.com passes. aysel@sayt fails because the domain has no dot.\n\nThis page does not send the address anywhere.",
    "E-postada @ ve nokta olup olmadığını gösterir. Mektup göndermez.\n\nÖrnek: aysel@nibrascode.com kontrolden geçer. aysel@sayt geçmez, çünkü alanda nokta yoktur.\n\nBu sayfa adresi hiçbir yere göndermez.",
    "يُظهر هل في البريد @ ونقطة. لا يرسل رسالة.\n\nمثال: aysel@nibrascode.com يجتاز. aysel@sayt لا يجتاز لأن النطاق بلا نقطة.\n\nهذه الصفحة لا ترسل العنوان إلى أي مكان.",
    "Показывает, есть ли в почте @ и точка. Письмо не отправляет.\n\nПример: aysel@nibrascode.com проходит. aysel@sayt не проходит, потому что в домене нет точки.\n\nСтраница адрес никуда не отправляет.",
  ),
  words: L(
    "Ədədi sözə çevirir. Səhifənin dilində yazır.\n\nNümunə: 120 Azərbaycan dilində yüz iyirmi olur.\n\nMinə qədər və bir az yuxarı işləyir. Bu səhifə pul saxlamır.",
    "Turns a number into words. It writes in the language of the page.\n\nExample: 120 is one hundred twenty in English.\n\nIt works up to a thousand and a little above. This page does not store money.",
    "Sayıyı söze çevirir. Sayfanın dilinde yazar.\n\nÖrnek: 120 Türkçede yüz yirmi olur.\n\nBine kadar ve biraz yukarı çalışır. Bu sayfa para saklamaz.",
    "يحوّل الرقم إلى كلمات. يكتب بلغة الصفحة.\n\nمثال: 120 تصبح مئة وعشرون بالعربية.\n\nيعمل حتى الألف وفوقه قليلًا. هذه الصفحة لا تحفظ مالًا.",
    "Переводит число в слова. Пишет на языке страницы.\n\nПример: 120 по-русски сто двадцать.\n\nРаботает до тысячи и немного выше. Страница деньги не хранит.",
  ),
  ip: L(
    "IP ünvanının dörd hissəsinin 0 ilə 255 arasında olduğunu göstərir.\n\nNümunə: 192.168.1.1 düzgündür. 192.168.1 keçmir, çünki dörd hissə yoxdur.\n\nBu səhifə şəbəkəyə qoşulmur.",
    "Shows whether the four parts of an IP address are between 0 and 255.\n\nExample: 192.168.1.1 is valid. 192.168.1 fails because there are not four parts.\n\nThis page does not connect to a network.",
    "IP adresinin dört parçasının 0 ile 255 arasında olduğunu gösterir.\n\nÖrnek: 192.168.1.1 doğrudur. 192.168.1 geçmez, çünkü dört parça yoktur.\n\nBu sayfa ağa bağlanmaz.",
    "يُظهر هل أجزاء عنوان IP الأربعة بين 0 و255.\n\nمثال: 192.168.1.1 صحيح. 192.168.1 لا يجتاز لأنه بلا أربعة أجزاء.\n\nهذه الصفحة لا تتصل بشبكة.",
    "Показывает, что четыре части IP-адреса между 0 и 255.\n\nПример: 192.168.1.1 верный. 192.168.1 не проходит, потому что нет четырёх частей.\n\nСтраница к сети не подключается.",
  ),
};










export const TOOL_SAMPLE: Partial<Record<ToolId, { text?: string; extra?: string; count?: string }>> = {
  json: { text: '{"ad":"Aysel","yaş":20}' },
  base64: { text: "Salam" },
  md5: { text: "Salam" },
  unix: { text: "0" },
  count: { text: "bir iki üç" },
  uuid: {},
  password: { count: "12" },
  regex: { extra: "a+", text: "baac" },
  color: { text: "#1d4ed8" },
  css: { text: "body{color:red;margin:0}" },
  cron: { text: "0 9 * * 1" },
  chmod: { text: "755" },
  robots: { text: "/admin" },
  contrast: { text: "#111111", extra: "#ffffff" },
  slug: { text: "Mənim ilk səhifəm" },
  percent: { text: "15 200" },
  mime: { text: "png" },
  meta: { text: "Nibras Code", extra: "Pulsuz kod alətləri" },
  sitemap: { text: "https://www.nibrascode.com/tools" },
  utm: { text: "https://www.nibrascode.com", extra: "google", count: "ders" },
  days: { text: "2026-01-01", extra: "2026-01-31" },
  shadow: { text: "8 16 24 #111111" },
  htaccess: { text: "/eski", extra: "/yeni" },
  gradient: { text: "#111111", extra: "#ffffff" },
  strength: { text: "123456" },
  table: { text: "ad,yaş\nAysel,20" },
  radius: { text: "12" },
  trim: { text: "  Salam   dünya  " },
  lines: { text: "bir\niki\nüç" },
  jsoncsv: { text: "[{\"ad\":\"Aysel\",\"yaş\":20}]" },
  palette: { text: "#1d4ed8" },
  htmlfmt: { text: "<p><b>Salam</b></p>" },
  "js-min": { text: "function salam() { return 1; }" },
  python: { text: "print(\"Salam\")\n" },
  php: { text: "<?php echo \"Salam\";" },
  "sql-min": { text: "select ad from istifadeci" },
  "xml-min": { text: "<ad>Aysel</ad>" },
  cssvar: { text: "#1d4ed8" },
  link: { text: "https://www.nibrascode.com" },
  chars: { text: "Salam" },
  yaml: { text: "ad: Aysel\nyaş: 20" },
  markdown: { text: "# Salam\n\n**Qalın** mətn" },
  email: { text: "aysel@nibrascode.com" },
  words: { text: "120" },
  ip: { text: "192.168.1.1" },
};

export function toolIdFromSlug(slug: string) {
  const pair = (Object.entries(TOOL_SLUG) as [ToolId, string][]).find((item) => item[1] === slug);
  return pair ? pair[0] : null;
}
