// Bəqərə surəsi: sözlərin izahı (hazır cavab məlumatı; AI-yə getmir).
// Mənbə: istifadəçinin verdiyi cədvəl (1–59-cu ayələr). Davamı gələndə yalnız bu massivin sonuna sətir əlavə edin
// (və ya yeni fayl yaradıb api/_quran.js-dəki SOURCES siyahısına qoşun).
//
// Sahələr:
//   surah  - surə nömrəsi (Bəqərə = 2)
//   ayah   - ayə nömrəsi
//   word   - ayədəki söz/ifadə (ərəbcə, hərəkələrlə)
//   ar     - ərəbcə qısa izah (mənbədəki kimi)
//   az     - Azərbaycan dilinə tərcümə
//   tr, en, ru - istəyə bağlı tərcümələr (indi yoxdur; yalnız əminsinizsə əlavə edin)
// Eyni söz müxtəlif ayələrdə keçə bilər; hər keçid ayrıca sətir olmalıdır.
const BAQARA = [
  { surah: 2, ayah: 1, word: "الٓمٓ", ar: "هذه الحروف المقطعة تشير إلى أن القرآن مركب من هذه الحروف التي تألفت منها", az: "Bu ayrı-ayrı hərflər Quranın məhz bu hərflərdən təşkil olunduğuna, yəni onlardan tərtib edildiyinə işarədir." },
  { surah: 2, ayah: 2, word: "الْكِتَابُ", ar: "القرآن", az: "Quran." },
  { surah: 2, ayah: 2, word: "لَا رَيْبَ فِيهِ", ar: "لا شك أنه من عند الله", az: "Onun Allah tərəfindən olduğunda heç bir şübhə yoxdur." },
  { surah: 2, ayah: 2, word: "لِلْمُتَّقِينَ", ar: "الذين يخافون الله، ويتبعون أحكامه", az: "Allahdan qorxanlar və Onun hökmlərinə tabe olanlar." },
  { surah: 2, ayah: 3, word: "يُؤْمِنُونَ", ar: "يُصدقون", az: "Təsdiq edirlər." },
  { surah: 2, ayah: 3, word: "بِالْغَيْبِ", ar: "بما لا يدرك بالحواس والعقول، فلا يُعرف إلا بالوحي، كالإيمان بالملائكة", az: "Hiss orqanları və əql ilə dərk olunmayan, yalnız vəhy ilə bilinən şeylərə, məsələn mələklərə iman gətirmək kimi." },
  { surah: 2, ayah: 3, word: "وَيُقِيمُونَ", ar: "يحافظون على أدائها في مواقيتها وفق ما شرع الله", az: "Onu (namazı) Allahın şəriət etdiyi kimi, öz vaxtlarında əda etməyə diqqət yetirirlər." },
  { surah: 2, ayah: 4, word: "بِمَا أُنزِلَ إِلَيْكَ", ar: "إلى محمد، من القرآن والسنة", az: "Muhəmmədə ﷺ nazil edilən Quran və Sünnəyə." },
  { surah: 2, ayah: 4, word: "وَمَا أُنزِلَ مِن قَبْلِكَ", ar: "من كتب كالتوراة والإنجيل", az: "Tövrat və İncil kimi (Peyğəmbərdən) əvvəl nazil edilmiş kitablara." },
  { surah: 2, ayah: 4, word: "وَبِالْآخِرَةِ هُمْ يُوقِنُونَ", ar: "يُصدقون بدار الحياة بعد الموت، وما فيها من الحساب", az: "Ölümdən sonrakı həyat yurduna (axirətə) və orada olan hesab-kitaba təsdiq edirlər." },
  { surah: 2, ayah: 5, word: "الْمُفْلِحُونَ", ar: "الفائزون", az: "Uğur qazananlar." },
  { surah: 2, ayah: 6, word: "كَفَرُواْ", ar: "جحدوا ما أنزل إليك من ربك", az: "Rəbbin tərəfindən sənə nazil edilənləri inkar etdilər." },
  { surah: 2, ayah: 6, word: "سَوَاءٌ", ar: "متساو", az: "Eynidir." },
  { surah: 2, ayah: 7, word: "خَتَمَ", ar: "طبع عليها، فلا تعي خيراً", az: "Onun (qəlblərin) üzərinə möhür vurdu; buna görə də heç bir xeyri dərk etmir." },
  { surah: 2, ayah: 7, word: "غِشَاوَةٌ", ar: "غطاء، فلم يوفقهم للهدى", az: "Örtük; buna görə də Allah onları haqq yola müvəffəq etmədi." },
  { surah: 2, ayah: 7, word: "عَذَابٌ", ar: "نار جهنم في الآخرة", az: "Axirətdə Cəhənnəm odu." },
  { surah: 2, ayah: 8, word: "وَمِنَ النَّاسِ", ar: "فريق المنافقين الذين يقولون بألسنتهم صدقنا، وهم كاذبون باطنياً", az: "Dilləri ilə «təsdiq etdik» deyən, daxilən isə yalançı olan münafiqlərin bir dəstəsi." },
  { surah: 2, ayah: 9, word: "يُخَادِعُونَ", ar: "يُظهرون خلاف ما يضمرون", az: "Daxillərində gizlətdiklərinin əksini göstərirlər." },
  { surah: 2, ayah: 9, word: "وَمَا يَشْعُرُونَ", ar: "وما يحسون بذلك؛ لفساد قلوبهم", az: "Bunu hiss etmirlər; çünki qəlbləri pozulmuşdur." },
  { surah: 2, ayah: 10, word: "مَرَضٌ", ar: "شك وفساد", az: "Şübhə və pozğunluq." },
  { surah: 2, ayah: 11, word: "لَا تُفْسِدُوا", ar: "بالمعاصي، وإفشاء أسرار المؤمنين وموالاة الكافرين", az: "Günahlar etməklə, möminlərin sirlərini yaymaqla və kafirlərlə dostluq etməklə (yer üzündə fəsad törətməyin)." },
  { surah: 2, ayah: 13, word: "آمِنُوا", ar: "صدقوا بقلوبكم، وألسنتكم، وجوارحكم", az: "Qəlbinizlə, dilinizlə və üzvlərinizlə təsdiq edin." },
  { surah: 2, ayah: 13, word: "السُّفَهَاءُ", ar: "ضعاف العقول والرأي، يعنون بهم الصحابة", az: "Əqli və fikri zəif olanlar; bununla səhabələri nəzərdə tuturlar." },
  { surah: 2, ayah: 13, word: "لَا يَعْلَمُونَ", ar: "ما هم فيه من الخسران", az: "Özlərinin içində olduğu ziyanı (bilmirlər)." },
  { surah: 2, ayah: 14, word: "شَيَاطِينِهِمْ", ar: "زعمائهم", az: "Başçıları, rəhbərləri." },
  { surah: 2, ayah: 14, word: "مُسْتَهْزِئُونَ", ar: "مستخفون بالمؤمنين، ساخرون منهم", az: "Möminləri kiçik sayanlar, onları lağa qoyanlar." },
  { surah: 2, ayah: 15, word: "يَمُدُّهُمْ", ar: "يمهلهم", az: "Onlara möhlət verir." },
  { surah: 2, ayah: 15, word: "طُغْيَانِهِمْ", ar: "ضلالتهم", az: "Haqq yoldan azmaları (zəlalətləri)." },
  { surah: 2, ayah: 15, word: "يَعْمَهُونَ", ar: "يترددون", az: "Tərəddüd edirlər." },
  { surah: 2, ayah: 16, word: "اشْتَرَوُا الضَّلَالَةَ بِالْهُدَىٰ", ar: "استبدلوا الكفر بالإيمان", az: "İmanın əvəzinə küfrü seçdilər." },
  { surah: 2, ayah: 17, word: "مَثَلُهُمْ", ar: "شبه المنافقين", az: "Münafiqlərin bənzəri (misalı)." },
  { surah: 2, ayah: 17, word: "اسْتَوْقَدَ", ar: "أوقد", az: "Od yandırdı." },
  { surah: 2, ayah: 17, word: "أَضَاءَتْ", ar: "سطعت وأنارت، ثم انطفأت", az: "Parladı və işıqlandırdı, sonra söndü." },
  { surah: 2, ayah: 18, word: "صُمٌّ", ar: "عن سماع الحق سماع تدبر، والصمم الانسداد", az: "Haqqı düşünərək dinləməkdən kar olanlar; karlıq (əs-səmam) qulaqların tutulması deməkdir." },
  { surah: 2, ayah: 18, word: "بُكْمٌ", ar: "عن النطق بالحق، والبكم الخرس", az: "Haqqı dilə gətirməkdən lal olanlar; lallıq (əl-bukm) dilsizlik, danışa bilməmək deməkdir." },
  { surah: 2, ayah: 18, word: "عُمْيٌ", ar: "عن إبصار نور الهداية", az: "Hidayət nurunu görməkdən kor olanlar." },
  { surah: 2, ayah: 18, word: "لَا يَرْجِعُونَ", ar: "لا يعودون إلى الإيمان", az: "İmana qayıtmırlar." },
  { surah: 2, ayah: 19, word: "أَوْ", ar: "هذا شبه فريق آخر من المنافقين الذين يظهر لهم الحق تارة، ويشكون فيه تارة", az: "Bu, münafiqlərin başqa bir dəstəsinin misalıdır: onlara haqq bir vaxt aydın görünür, bir vaxt da onda şübhə edirlər." },
  { surah: 2, ayah: 19, word: "كَصَيِّبٍ", ar: "الصيب المطر الشديد، والمعنى: كأصحاب صيب", az: "«Səyyib» şiddətli yağış deməkdir; məna belədir: şiddətli yağışa tutulanlar kimi." },
  { surah: 2, ayah: 19, word: "الصَّوَاعِقِ", ar: "جمع صاعقة، وهي العذاب المهلك المحرق", az: "«Səvaiq», «saiqə» sözünün çoxluq formasıdır; bu, məhv edən, yandıran əzabdır." },
  { surah: 2, ayah: 19, word: "مُحِيطٌ بِالْكَافِرِينَ", ar: "لا يفوتونه، ولا يعجزونه", az: "Onlar Ondan yayına bilməzlər və Onu aciz qoya bilməzlər." },
  { surah: 2, ayah: 20, word: "يَكَادُ", ar: "يقارب", az: "Yaxınlaşır (az qalır)." },
  { surah: 2, ayah: 20, word: "يَخْطَفُ", ar: "يسلب من شدة لمعانه", az: "Parıltısının şiddətindən alıb aparır." },
  { surah: 2, ayah: 20, word: "قَامُوا", ar: "وقفوا في أماكنهم متحيرين", az: "Çaşıb qalaraq öz yerlərində dayandılar." },
  { surah: 2, ayah: 21, word: "لَعَلَّكُمْ تَتَّقُونَ", ar: "لتتقوه بطاعته", az: "Ona itaət etməklə Ondan qorunmağınız (müttəqi olmağınız) üçün." },
  { surah: 2, ayah: 22, word: "جَعَلَ", ar: "صير", az: "Etdi, çevirdi." },
  { surah: 2, ayah: 22, word: "فِرَاشًا", ar: "بساطاً تسهل حياتكم عليه", az: "Həyatınızın üzərində asan olduğu döşənmiş yer." },
  { surah: 2, ayah: 22, word: "أَندَادًا", ar: "نظراء في العبادة", az: "İbadətdə (Allaha) tay tutulanlar." },
  { surah: 2, ayah: 22, word: "تَعْلَمُونَ", ar: "تعلمون تفرده بالحق والرزق، واستحقاقه العبودية", az: "Allahın haqda və ruzi verməkdə təkliyini, həmçinin ibadətə layiq olmasını bilirsiniz." },
  { surah: 2, ayah: 23, word: "رَيْبٍ", ar: "شك", az: "Şübhə." },
  { surah: 2, ayah: 23, word: "مِّن مِّثْلِهِ", ar: "تماثل سورة منه", az: "Ondan olan bir surəyə bənzəyən." },
  { surah: 2, ayah: 23, word: "شُهَدَاءَكُم", ar: "أعوانكم الذين يشهدون لكم", az: "Sizin üçün şahidlik edən köməkçiləriniz." },
  { surah: 2, ayah: 24, word: "وَلَن تَفْعَلُوا", ar: "مستقبلاً", az: "Gələcəkdə." },
  { surah: 2, ayah: 24, word: "وَقُودُهَا", ar: "حطبها", az: "Onun odunu." },
  { surah: 2, ayah: 24, word: "أُعِدَّتْ", ar: "هيئت", az: "Hazırlanmışdır." },
  { surah: 2, ayah: 25, word: "وَبَشِّرِ", ar: "أخبرهم بما يسرهم", az: "Onlara sevindirəcək şeyləri xəbər ver." },
  { surah: 2, ayah: 25, word: "مِن تَحْتِهَا", ar: "من تحت قصور الجنات العالية وأشجارها الظليلة", az: "Cənnətlərin ucaldılmış saraylarının və kölgəli ağaclarının altından." },
  { surah: 2, ayah: 25, word: "مِن قَبْلُ", ar: "في الدنيا", az: "Dünyada." },
  { surah: 2, ayah: 25, word: "مُتَشَابِهًا", ar: "وجدوا طعماً جديداً، وإن تشابه مع سابقه", az: "Əvvəlkinə bənzəsə də, təzə bir dad tapdılar." },
  { surah: 2, ayah: 25, word: "مُّطَهَّرَةٌ", ar: "من الدنس الحسي كالحيض، والمعنوي كالكذب", az: "Hissi çirkdən (məsələn, aybaşıdan) və mənəvi çirkdən (məsələn, yalandan) pak olan." },
  { surah: 2, ayah: 26, word: "لَا يَسْتَحْيِي", ar: "من الحق أن يذكر شيئاً ما، صغيراً أو كبيراً", az: "Haqqı söyləməkdən çəkinmir ki, kiçik və ya böyük, nəyi isə zikr etsin." },
  { surah: 2, ayah: 26, word: "فَمَا فَوْقَهَا", ar: "فما هو أكبر منها", az: "Ondan daha böyük olanı." },
  { surah: 2, ayah: 26, word: "الْفَاسِقِينَ", ar: "الخارجين عن طاعة الله", az: "Allaha itaətdən çıxanlar." },
  { surah: 2, ayah: 27, word: "يَنقُضُونَ", ar: "ينكثون", az: "Pozurlar." },
  { surah: 2, ayah: 27, word: "عَهْدَ اللَّهِ", ar: "العهد الذي أخذه عليهم بالتوحيد والطاعة", az: "Allahın onlardan tövhid və itaət barədə aldığı əhd." },
  { surah: 2, ayah: 27, word: "مِن بَعْدِ مِيثَاقِهِ", ar: "من بعد تأكيده باليمين", az: "Andla təsdiq edilməsindən sonra." },
  { surah: 2, ayah: 28, word: "أَمْوَاتًا", ar: "عدماً غير مخلوقين", az: "Yoxluqda idilər, xəlq edilməmişdilər." },
  { surah: 2, ayah: 28, word: "فَأَحْيَاكُمْ", ar: "فأنشأكم بشراً سوياً", az: "Sizi düzgün quruluşlu bəşər olaraq meydana gətirdi." },
  { surah: 2, ayah: 28, word: "يُحْيِيكُمْ", ar: "يوم البعث", az: "Dirilmə günündə." },
  { surah: 2, ayah: 29, word: "اسْتَوَىٰ إِلَى السَّمَاءِ", ar: "ارتفع وقصد إلى خلق السموات، وتقدير ما في كل واحد", az: "Ucaldı və göyləri xəlq etməyi, hər birində olanı təqdir etməyi qəsd etdi." },
  { surah: 2, ayah: 29, word: "فَسَوَّاهُنَّ", ar: "خلقهن مستويات ودبرهن", az: "Onları düz-bərabər olaraq xəlq etdi və idarə etdi." },
  { surah: 2, ayah: 30, word: "خَلِيفَةً", ar: "قوماً يخلف بعضهم بعضا لعمارة الأرض", az: "Bir-birinin ardınca gələn, yer üzünü abadlaşdırmaq üçün bir qövm." },
  { surah: 2, ayah: 30, word: "وَيَسْفِكُ الدِّمَاءَ", ar: "يريقها بغير حق", az: "Onu (qanı) haqsız yerə tökür." },
  { surah: 2, ayah: 30, word: "نُسَبِّحُ بِحَمْدِكَ", ar: "ننزهك التنزيه اللائق", az: "Səni layiq olduğu kimi qüsurlardan uzaq tuturuq." },
  { surah: 2, ayah: 30, word: "وَنُقَدِّسُ لَكَ", ar: "نمجدك، ونطهر ذكرك عما لا يليق بك", az: "Səni uca tuturuq və Sənin zikrini Sənə layiq olmayan şeylərdən təmizləyirik." },
  { surah: 2, ayah: 31, word: "الْأَسْمَاءَ", ar: "أسماء الأشياء التي يتعارف بها الناس", az: "İnsanların bir-birini tanıdıqları əşyaların adları." },
  { surah: 2, ayah: 31, word: "هَٰؤُلَاءِ", ar: "الموجودات التي علمها آدم", az: "Adəmə öyrədilən mövcud şeylər." },
  { surah: 2, ayah: 32, word: "سُبْحَانَكَ", ar: "تنزيها لله", az: "Allahı (hər nöqsandan) pak tutmaq." },
  { surah: 2, ayah: 32, word: "بِأَسْمَائِهِمْ", ar: "بأسماء الأشياء التي عجزوا عن معرفتها", az: "Tanımaqda aciz qaldıqları əşyaların adları ilə." },
  { surah: 2, ayah: 33, word: "تُبْدُونَ", ar: "تظهرون", az: "Aşkar edirsiniz." },
  { surah: 2, ayah: 33, word: "تَكْتُمُونَ", ar: "تخفون", az: "Gizlədirsiniz." },
  { surah: 2, ayah: 34, word: "اسْجُدُوا لِآدَمَ", ar: "إكراماً له، وإظهاراً لفضله", az: "Onu izzətləndirmək və fəzilətini aşkar etmək üçün (Adəmə səcdə edin)." },
  { surah: 2, ayah: 34, word: "أَبَىٰ", ar: "تكبراً وحسداً", az: "Təkəbbür və həsəd üzündən." },
  { surah: 2, ayah: 34, word: "اسْتَكْبَرَ", ar: "استعظم نفسه", az: "Özünü böyük gördü." },
  { surah: 2, ayah: 35, word: "رَغَدًا", ar: "هنيئاً واسعاً", az: "Xoş və geniş (bol)." },
  { surah: 2, ayah: 35, word: "الظَّالِمِينَ", ar: "المتجاوزين أمر الله", az: "Allahın əmrindən kənara çıxanlar." },
  { surah: 2, ayah: 36, word: "فَأَزَلَّهُمَا الشَّيْطَانُ عَنْهَا", ar: "فأوقعهما الشيطان في الخطيئة ليبعدهما عن الجنة", az: "Şeytan onları günaha saldı ki, Cənnətdən uzaqlaşdırsın." },
  { surah: 2, ayah: 36, word: "بَعْضُكُمْ لِبَعْضٍ", ar: "آدم وحواء، والشيطان", az: "Adəm və Həvva, bir də şeytan." },
  { surah: 2, ayah: 36, word: "مَتَاعٌ", ar: "انتفاع، واستمتاع", az: "Faydalanmaq və ləzzət almaq." },
  { surah: 2, ayah: 36, word: "إِلَىٰ حِينٍ", ar: "إلى وقت انتهاء آجالكم", az: "Əcəlləriniz bitən vaxta qədər." },
  { surah: 2, ayah: 37, word: "كَلِمَاتٍ", ar: "ما ألهمه الله من كلمات للتوبة", az: "Allahın tövbə üçün ona ilham etdiyi kəlmələr." },
  { surah: 2, ayah: 38, word: "فَلَا خَوْفٌ", ar: "آمنون من أهوال القيامة", az: "Qiyamət günündəki dəhşətlərdən əmin olanlar." },
  { surah: 2, ayah: 38, word: "وَلَا هُمْ يَحْزَنُونَ", ar: "على ما فاتهم من الدنيا", az: "Dünyada əldən verdiklərinə görə (kədərlənmirlər)." },
  { surah: 2, ayah: 40, word: "اذْكُرُوا نِعْمَتِيَ", ar: "اصطفائي للرسل منكم، وإنزال الكتب عليكم ونجاتكم من فرعون", az: "Peyğəmbərləri sizin içinizdən seçməyim, kitabları sizə nazil etməyim və sizin Fironun əlindən xilas olmanız." },
  { surah: 2, ayah: 40, word: "وَأَوْفُوا بِعَهْدِي", ar: "أتموا وصيتي لكم بالإيمان بكتبي وبرسلي جميعاً", az: "Sizə tapşırdığım — kitablarıma və bütün peyğəmbərlərimə iman gətirmək barədəki vəsiyyətimi yerinə yetirin." },
  { surah: 2, ayah: 40, word: "أُوفِ بِعَهْدِكُمْ", ar: "ما وعدتكم به من الرحمة في الدنيا والآخرة", az: "Dünyada və axirətdə rəhmət barədə sizə verdiyim vədi (yerinə yetirərəm)." },
  { surah: 2, ayah: 41, word: "أَوَّلَ كَافِرٍ بِهِ", ar: "بالقرآن", az: "«Ona» — Qurana." },
  { surah: 2, ayah: 41, word: "وَلَا تَشْتَرُوا بِآيَاتِي ثَمَنًا", ar: "ولا تبيعوا ما آتيكم به من العلم بما في كتابكم من أمر محمد ﷺ بثمن", az: "Sizə verdiyim elmi, yəni kitabınızda Muhəmməd ﷺ barədə olanı, bir qiymət müqabilində satmayın." },
  { surah: 2, ayah: 41, word: "قَلِيلًا", ar: "بخس", az: "Dəyərsiz, cüzi." },
  { surah: 2, ayah: 42, word: "وَلَا تَلْبِسُوا", ar: "ولا تخلطوا", az: "Qarışdırmayın." },
  { surah: 2, ayah: 42, word: "وَتَكْتُمُوا الْحَقَّ", ar: "وتخفوا صفة محمد ﷺ في التوراة", az: "Muhəmmədin ﷺ Tövratdakı vəsfini gizlətməyin." },
  { surah: 2, ayah: 44, word: "بِالْبِرِّ", ar: "بالطاعة، والعمل الصالح", az: "İtaət və yaxşı əməllə." },
  { surah: 2, ayah: 44, word: "الْكِتَابَ", ar: "التوراة", az: "Tövrat." },
  { surah: 2, ayah: 45, word: "لَكَبِيرَةٌ", ar: "شاقة ثقيلة", az: "Çətin və ağır." },
  { surah: 2, ayah: 45, word: "الْخَاشِعِينَ", ar: "الخاضعين لطاعته", az: "Ona itaətə boyun əyənlər." },
  { surah: 2, ayah: 46, word: "يَظُنُّونَ", ar: "يوقنون", az: "Yəqin edirlər (qəti əmin olurlar)." },
  { surah: 2, ayah: 47, word: "الْعَالَمِينَ", ar: "عالمي زمانكم؛ بكثرة الأنبياء، وإنزال الكتب", az: "Sizin dövrünüzün aləmləri, peyğəmbərlərin çox olması və kitabların nazil edilməsi baxımından." },
  { surah: 2, ayah: 48, word: "يَوْمًا", ar: "يوم القيامة", az: "Qiyamət günü." },
  { surah: 2, ayah: 48, word: "لَّا تَجْزِي", ar: "لا يغني أحد عن أحد شيئا", az: "Heç kəs başqasının yerinə heç bir şeyə yaramaz (ona fayda verməz)." },
  { surah: 2, ayah: 48, word: "عَدْلٌ", ar: "فدية", az: "Fidyə." },
  { surah: 2, ayah: 49, word: "نَجَّيْنَاكُم", ar: "نجينا آباءكم", az: "Sizin atalarınızı xilas etdik." },
  { surah: 2, ayah: 49, word: "يَسْتَحْيُونَ نِسَاءَكُمْ", ar: "يستبقونهن للخدمة والامتهان", az: "Qadınlarınızı xidmət və alçaltma üçün sağ saxlayırdılar." },
  { surah: 2, ayah: 49, word: "بَلَاءٌ", ar: "اختبار", az: "İmtahan." },
  { surah: 2, ayah: 50, word: "فَرَقْنَا بِكُمُ الْبَحْرَ", ar: "فصلنا لكم البحر، وجعلنا فيه طرقاً يابسة لعبوركم", az: "Sizin üçün dənizi ayırdıq və onda keçməyiniz üçün quru yollar qıldıq." },
  { surah: 2, ayah: 51, word: "اتَّخَذْتُمُ الْعِجْلَ", ar: "أي معبوداً لكم من دون الله", az: "Yəni Allahdan başqa özünüzə məbud (ibadət olunan) tutdunuz." },
  { surah: 2, ayah: 53, word: "الْكِتَابَ", ar: "التوراة", az: "Tövrat." },
  { surah: 2, ayah: 53, word: "الْفُرْقَانَ", ar: "الفارق بين الحق والباطل", az: "Haqqla batili ayıran." },
  { surah: 2, ayah: 54, word: "فَاقْتُلُوا أَنفُسَكُمْ", ar: "بأن يقتل بعضكم بعضا", az: "Yəni sizdən bəziniz bəzinizi öldürsün." },
  { surah: 2, ayah: 55, word: "جَهْرَةً", ar: "عياناً", az: "Gözlə görərək, açıq-aşkar." },
  { surah: 2, ayah: 55, word: "الصَّاعِقَةُ", ar: "نار من السماء", az: "Göydən gələn od." },
  { surah: 2, ayah: 57, word: "الْغَمَامَ", ar: "السحاب", az: "Bulud." },
  { surah: 2, ayah: 57, word: "الْمَنَّ", ar: "شيء يشبه الصمغ، طعمه كالعسل", az: "Saqqıza bənzər, dadı bal kimi olan bir şey." },
  { surah: 2, ayah: 57, word: "السَّلْوَىٰ", ar: "طير يشبه السماني", az: "Bildirçinə bənzər bir quş." },
  { surah: 2, ayah: 58, word: "الْقَرْيَةَ", ar: "بيت المقدس", az: "Beytül-Müqəddəs." },
  { surah: 2, ayah: 58, word: "رَغَدًا", ar: "هنيئاً", az: "Xoş və rahat." },
  { surah: 2, ayah: 58, word: "حِطَّةٌ", ar: "ربنا ضع عنا ذنوبنا", az: "Rəbbimiz, günahlarımızı üzərimizdən götür." },
  { surah: 2, ayah: 59, word: "رِجْزًا", ar: "عذاباً", az: "Əzab." },
  { surah: 2, ayah: 59, word: "يَفْسُقُونَ", ar: "يخرجون عن طاعة الله", az: "Allaha itaətdən çıxırlar." },
];

export default BAQARA;
export { BAQARA };
