// Məcmuu əl-Fətava üçün mövzu lüğəti (sabit cədvəl, AI deyil): az/tr/en/ru sözləri -> ərəbcə axtarış ifadəsi.
// Sətir: «açar1, açar2, çoxsözlü açar => ərəbcə ifadə / ehtiyat ifadə». Açar: tək söz (≥4 hərf: prefiks uyğunluğu, qısa: tam uyğunluq) və ya ardıcıl söz prefiksləri.
// Daha uzun (çoxsözlü) açarlar qısalardan üstün tutulur. İlk ərəbcə ifadə axtarılır, nəticə yoxdursa ehtiyat ifadələr. Yoxlama: scripts/fatawa.test.mjs.
export const TOPIC_SRC = `
# ===== AQİDƏ: tövhid, ad-sifət, şirk, bidət, təkfir
tovhid, tevhid, tawhid, tauhid, oneness of allah, единобожие, таухид, тавхид => التوحيد
rububiyyet, rububiyya, rububiyyah, божественность господства => توحيد الربوبية
uluhiyyet, uluhiyya, uluhiyyah => توحيد الألوهية
esma ve sifat, esma sifat, asma wa sifat, names and attributes, имена и атрибуты => الأسماء والصفات
allahin sifatlari, allahin sifetleri, sifatullah, attributes of allah, атрибуты аллаха, качества аллаха => صفات الله / الصفات
allahin adlari, allahin isimleri, names of allah, esmaul husna, имена аллаха => أسماء الله الحسنى / الأسماء الحسنى
sirk, shirk, ширк, polytheism, ortaq qosmaq, ortak kosmak, associating partners => الشرك
boyuk sirk, buyuk sirk, major shirk, shirk akbar, большой ширк => الشرك الأكبر
kicik sirk, minor shirk, shirk asghar, малый ширк => الشرك الأصغر
riya, riyakarliq, riyakarlik, showing off, ostentation, показуха => الرياء
bidet, bidat, bidah, bidaa, bid'ah, innovation, innovations, нововведен, бидъа, бидат => البدعة / البدع
bidet hasene, gozel bidet, good innovation, hasana innovation, хорошее нововведение => البدعة الحسنة
tekfir, takfir, такфир, kafir saymaq, kafir saymak, excommunication, declaring a muslim kafir => التكفير
kufr, kufur, disbelief, unbelief, куфр, неверие => الكفر
nifaq, nifak, hypocrisy, hypocrite, munafiq, лицемер, мунафик => النفاق
fasiq, fisq, fasik, фасик, фиск => الفسق
irtidad, ridda, murtad, apostasy, apostate, вероотступ, отступничество, dinden donmek, dinden cixmaq => الردة / المرتد
zindiq, zendeka, ilhad, atheism, atheist, atheists, атеизм, ateizm, ateist => الزندقة / الإلحاد
istiva, istiwa, istawa, istivasi, истива => الاستواء على العرش / الاستواء
allah haradadir, allah nerededir, where is allah, где аллах, uluvv, aboveness of allah => علو الله على خلقه / العلو
arsh, arsi, throne of allah, трон аллаха, kursi, kursu => العرش / الكرسي
nuzul, ilahi nuzul, descent of allah, allah descends, нисхождение аллаха => نزول الله إلى السماء الدنيا / النزول
ruyetullah, ruyatullah, allahi gormek, allahin gorulmesi, seeing allah, видеть аллаха, видение аллаха => رؤية الله / الرؤية
kalamullah, allahin kelami, allahin kalami, speech of allah, слово аллаха => كلام الله
quran mexluqdur, quran mahluk, quran created, коран сотворен, kuran mahluk mu => القرآن كلام الله غير مخلوق / خلق القرآن
tefviz, tafwid, tefwid, тафвид => التفويض
tevil, tawil, ta'wil, te'vil, таъвиль => التأويل
tecsim, tajsim, teshbih, tashbih, антропоморфизм, tecsim, anthropomorphism => التجسيم / التشبيه
tetil, ta'til, denial of attributes, отрицание атрибутов => التعطيل
cehmiyye, jahmiyya, jahmiyyah, cehmi, джахмия, джахмиты => الجهمية
esaire, esairi, eshari, ashari, asharite, ashariyya, ашариты, ашарит, эшари => الأشاعرة
maturidi, maturidiyye, матуридиты, матуриди => الماتريدية
mutezile, mutazila, mutazilite, mu'tazila, мутазилиты, мутазилиты => المعتزلة
murcie, murji'a, murjiah, мурджииты, murciyye => المرجئة
qederiyye, qadariyya, kaderiyye, кадариты => القدرية
cebriyye, jabriyya, джабриты => الجبرية
rafiziler, rafidi, rafida, rafidah, shia, shiite, shiites, shi'a, sie, шииты, шиит, шиа, рафидиты => الرافضة / الشيعة
haricilik, hariciler, xaricilər, kharijites, khawarij, хариджиты, хаваридж => الخوارج
nasibi, nawasib, насибиты => النواصب
alemin kidemi, qidemi alem, eternity of the world, вечность мира => قدم العالم
hulul, ittihad, vahdeti vucud, vehdeti vucud, wahdat al wujud, unity of being, единство бытия, единство существования, incarnation of god => الحلول والاتحاد / وحدة الوجود
ibn arabi, ibn al arabi, ибн араби => ابن عربي / وحدة الوجود
fena, fana, annihilation, фана => الفناء
# ===== QƏDƏR, İMAN, GÜNAH
qeder, kader, qadar, qadr, predestination, destiny, fate, предопределение, судьба, кадар => القدر / القضاء والقدر
qaza ve qeder, kaza ve kader, qada wa qadar => القضاء والقدر
ixtiyar, free will, свобода воли, cebr, irade => الجبر والاختيار / أفعال العباد
iman, imani, faith, belief in allah, иман, вера => الإيمان
imanin artmasi, imanin eksilmesi, iman artir, increase of faith, faith increases and decreases, iman zivada => زيادة الإيمان ونقصانه
imanin sertleri, imanin sutunlari, pillars of faith, arkan al iman, столпы веры => أركان الإيمان
islam ve iman, difference between islam and iman, разница между исламом и иманом => الإسلام والإيمان
istisna fil iman, istithna, mumin oldugunu soylemek, i am a believer insha allah => الاستثناء في الإيمان
mumin, mu'min, believer, believers, верующий, верующие => المؤمن / المؤمنون
kebire, kebire gunah, kaba'ir, major sin, major sins, большой грех, большие грехи => الكبائر
sagire, kicik gunah, minor sin, minor sins, малый грех, малые грехи => الصغائر
gunah, gunahlar, zenb, sin, sins, грех, грехи => الذنوب
tovbe, tobe, tevbe, tawba, tawbah, repentance, repent, покаяни, тауба => التوبة
istigfar, istighfar, seeking forgiveness, истигфар => الاستغفار
# ===== TƏVƏSSÜL, İSTİĞASƏ, ZİYARƏT, QƏBİR, BARZƏX
tevessul, tavessul, tawassul, tawassul, vasile, vesile, wasila, посредничество, тавассуль, васила => التوسل / الوسيلة
nebiye tevessul, peygambere tevessul, tawassul bil nabi, tawassul with the prophet, tawassul through the prophet, тавассуль через пророка => التوسل بالنبي / التوسل
saleh amellerle tevessul, tawassul with good deeds, тавассуль добрыми делами => التوسل بصالح الأعمال / التوسل
istigase, istighatha, istigatha, истигаса, seeking help from the dead, yardim istemek olulerden => الاستغاثة / الاستغاثة بالنبي
oluden yardim, olulerden yardim, mevtadan komek, asking the dead, calling upon the dead, обращение к умершим, просить умерших => دعاء الميت / الاستغاثة بالأموات
qebir ziyareti, kabir ziyareti, kabir ziyaret, ziyaret kubur, ziyaretul kubur, ziyarat, visiting graves, grave visitation, visit graves, посещение могил, зиярат => زيارة القبور
peygamberin kabrini ziyaret, nebinin qebrini ziyaret, visiting the prophet's grave, visit prophet's grave, посещение могилы пророка => زيارة قبر النبي صلى الله عليه وسلم / زيارة القبور
shadd al rihal, sedd er rihal, travelling to visit graves, qebir ucun sefer => شد الرحال إلى القبور / السفر لزيارة القبور
qebir, kabir, grave, graves, могила, могилы, mezar, mezarlik => القبر / القبور
qebir uzerine mescid, kabir uzerine mescit, mosque over a grave, building mosque on graves, мечеть над могилой => بناء المساجد على القبور
qebre sece, kabre secde, prostration to graves, поклон могиле => السجود للقبور / الصلاة عند القبور
qebirstanliqda namaz, mezarlikta namaz, prayer in a graveyard, prayer in a cemetery, молитва на кладбище => الصلاة في المقبرة / الصلاة عند القبور
telqin, talqin, talqeen, instructing the dead, наставление умершего => تلقين الميت
qebir suali, kabir sorusu, questioning in the grave, munkar nakir, вопросы в могиле => سؤال القبر / منكر ونكير
qebir azabi, kabir azabi, punishment of the grave, torment of the grave, мучения в могиле, azab al qabr => عذاب القبر
berzex, barzakh, барзах => البرزخ
ruh, ruhu, ruhun, soul, spirit, душа, душу, дух => الروح
oluler esidir mi, do the dead hear, dead hear, мертвые слышат, olu esitir mi => سماع الموتى
# ===== MÖVLUD, BAYRAMLAR, XÜSUSİ GÜNLƏR
mevlid, mevlud, movlud, mawlid, maulid, milad an nabi, prophet's birthday, birthday of the prophet, мавлид, день рождения пророка => المولد النبوي / المولد
mevlid kutlamak, celebrating mawlid, празднование мавлида, mevlid kandili => الاحتفال بالمولد / المولد
bayram, bayrami, eid, id al fitr, id al adha, праздник => العيدين / العيد
qurban bayrami, kurban bayrami, eid al adha, курбан байрам => عيد الأضحى / الأضحية
ramazan bayrami, fitr bayrami, eid al fitr, ураза байрам => عيد الفطر
yeni il, yilbasi, new year, noel, christmas, рождество, новый год, kafirlerin bayrami, kafirlerin bayramlari => مشابهة الكفار في أعيادهم / أعياد الكفار
nesranilere tebrik, congratulating christians, congratulate non muslims, поздравлять немусульман, kafirleri tebrik etmek => تهنئة الكفار بأعيادهم
tesebbuh, tashabbuh, imitating non muslims, imitating the kuffar, подражание неверным, kafirlere benzemek => مشابهة الكفار / التشبه بالكفار
mirac, miraj, mi'raj, isra, israel miraj, ascension, night journey, мирадж, исра => الإسراء والمعراج
regaib, ragaib, raghaib, regaib namazi, регаиб => صلاة الرغائب
berat gecesi, berat kandili, nisf shaban, mid shaban, 15 shaban, middle of shaban, ночь бараат, середина шабана => ليلة النصف من شعبان
kandil, kandil gecesi, holy nights, священные ночи => ليلة النصف من شعبان / تخصيص ليلة بعبادة
asura, ashura, aşura, 10 muharrem, muharrem orucu, ашура, achoura => عاشوراء / صوم عاشوراء
hz huseyin matemi, ashura mourning, траур по хусейну, matam tutmak, mourning husayn => المآتم / مقتل الحسين
muharrem, muharram, мухаррам, hicri yeni il => المحرم / عاشوراء
recep, rajab, раджаб, recep ayi => رجب / الاحتفال برجب
sehru remezan, shahr ramadan, ramazan, ramadan, рамадан => رمضان / فضل رمضان
# ===== DUA, ZİKR, SALAVAT
dua, duaa, du'a, supplication, мольба, дуа => الدعاء
duada el qaldirmaq, raising hands in dua, поднимать руки в дуа, el kaldirmak dua => رفع اليدين في الدعاء
dua sonra yuze sürmek, wiping face after dua, обтирать лицо после дуа => مسح الوجه باليدين بعد الدعاء
namazdan sonra toplu dua, dua after prayer, collective dua, коллективная молитва, дуа после намаза, cemaatle dua => الدعاء بعد الصلاة / الدعاء الجماعي
zikir, zikr, dhikr, зикр, zikr halqasi, dhikr circles, зикр вслух, toplu zikir => الذكر / الذكر الجماعي
zikir ile allahi anmak, remembrance of allah, поминание аллаха => ذكر الله
ya hu zikri, allah allah zikri, zikr by single name, dhikr with the name allah alone, зикр одним словом => الذكر بالاسم المفرد
tesbih, tespih, misbaha, subha, prayer beads, rosary, четки, tasbeeh beads, tasbih cekmek => السبحة / عد التسبيح
salavat, selavat, salawat, durud, durood, send blessings on the prophet, салават, ya rasulallah salavat => الصلاة على النبي صلى الله عليه وسلم
istixare, istihare, istikhara, istikhara prayer, истихара => صلاة الاستخارة / الاستخارة
quran olu icin, quran for the dead, reciting quran for the deceased, чтение корана умершим, esal sevab, isal sevab, ihdaus thawab, ruhuna yasin, yasin okumak, ruhuna fatiha => إهداء ثواب القرآن للميت / وصول ثواب القراءة إلى الميت
olu yemegi, funeral feast, feeding at funeral, поминки, 40 gun yemegi, kirk yemegi, yedisi yemegi, food for the deceased family => طعام أهل الميت / الاجتماع عند أهل الميت
taziye, ta'ziya, condolences, соболезнования, bas sagligi => التعزية
agi, nova, nuhe, wailing, lamentation, причитание, olu uzerine aglamak, crying over the dead => النياحة / البكاء على الميت
# ===== TƏHARƏT
teharet, taharet, tahara, taharah, purification, ritual purity, тахара, чистота => الطهارة
abdest, destemaz, wudu, wudhu, ablution, омовение, вуду, wuzu, abdəst, dəstəmaz => الوضوء
abdestin farzlari, abdestin sertleri, obligations of wudu, фарды омовения, arkan al wudu => فروض الوضوء
abdesti bozan, abdesti pozan, nawaqid al wudu, things that break wudu, nullifiers of wudu, что нарушает омовение, destemazi pozan => نواقض الوضوء
deve eti abdest, camel meat wudu, мясо верблюда омовение => الوضوء من لحوم الإبل
kadina dokunmak abdest, touching women wudu, touching a woman wudu, прикосновение к женщине омовение, qadina toxunmaq abdest, lems nisa => لمس المرأة هل ينقض الوضوء / لمس المرأة
ferce dokunmak, mess zekar, touching private parts wudu, touching the private part, прикосновение к половому органу, mass al dhakar => مس الذكر
gusl, qusl, ghusl, boy abdesti, buyuk abdest, cenabet, janaba, junub, major ritual impurity, полное омовение, джануб, гусль => الغسل من الجنابة / الغسل
cunub quran, junub reading quran, quran without wudu, abdestsiz kuran, касаться корана без омовения, mushaf without wudu, abdestsiz mushaf, mess mushaf => مس المصحف بغير وضوء / قراءة القرآن للجنب
teyemmum, tayammum, tayammum, dry ablution, тайаммум, tejemmum => التيمم
mesh huffeyn, meshi huf, mash alal khuffayn, wiping over socks, wiping over leather socks, wiping over khuffs, мясх по носкам, масх по хуффам, mest uzerine mesh, corap uzerine mesh, cor ab uzerine mesh => المسح على الخفين / المسح على الجوربين
cebira, jabira, wiping over bandage, mesh on cast, wiping over cast, масх по повязке => المسح على الجبيرة
necaset, najasa, najasah, najis, impurity, impure, filthy, нечистота, наджаса, нечистый, necis => النجاسة / الطهارة من النجاسة
kopek, dog, dogs, собака, собаки, kopegin salyasi, dog saliva, ulugh al kalb, keeping dogs, kopek beslemek, держать собаку => الكلاب / نجاسة الكلب / اقتناء الكلاب
istinca, istinja, istibra, toilet etiquette, tuvalet adabi, qada al hajah, kazai hacet, cleaning after toilet, этикет туалета => الاستنجاء / آداب قضاء الحاجة
misvak, miswak, siwak, мисвак, зубная палочка, toothbrush, dis fircasi => السواك
fitrat, fitra, fitrah, sunan al fitra, khitan, circumcision, sunnet olmak, sunnat, обрезание, хитан, хатна => خصال الفطرة / الختان
sac boyamaq, hair dye, dyeing hair, dyeing beard, khidab, hena, kina, kinali, покраска волос, красить бороду, хна => الخضاب / خضاب الشيب
# ===== HEYZ, NİFAS, CİMA
heyz, hayz, hayd, adet, adet gormek, menses, menstruation, haid, haiz, месячные, хайд, хайз, менструация, aybasi, aybashi => الحيض
heyzli namaz, haizin namazi, adetli kadin namaz, praying during period, praying while menstruating, хайд намаз, adet halinde namaz => الحائض والصلاة
heyzli oruc, adetli kadin oruc, fasting during period, fasting while menstruating, хайд пост => الحائض والصيام / قضاء الصوم للحائض
heyzli quran, adetli kadin kuran, menstruating woman reading quran, haid and quran, хайд коран => قراءة الحائض للقرآن
heyzli tavaf, haiz tavaf, menstruating woman tawaf, adetli tavaf, хайд таваф => طواف الحائض
heyz muddeti, adet suresi, length of menses, duration of period, aqallu al hayd, период хайда => أقل الحيض وأكثره / مدة الحيض
istihaze, istihada, mustahada, istihadah, abnormal bleeding, prolonged bleeding, истихада => الاستحاضة / المستحاضة
nifas, lohusa, lohusalik, postpartum bleeding, postnatal bleeding, нифас, послеродовое кровотечение => النفاس
cima, jima, jimaa, intercourse, sexual intercourse, sex, cinsel iliski, cinsi munasibet, cinsi elaqe, половой акт, джима => الجماع / أحكام الجماع
heyz halinda cima, adetli iken cima, intercourse during menstruation, sex during period, хайд джима => جماع الحائض / وطء الحائض
livata, liwat, lut, homosexuality, homosexual, gay, lesbian, musahaka, sihaq, гомосексуализм, гомосексуал => اللواط / السحاق
istimna, mastürbasyon, masturbation, onani, onanizm, мастурбация, istimna, el ile bosalmaq => الاستمناء / العادة السرية
# ===== NAMAZ
namaz qilmayan, namazi terk, namaz terk, namazi birakan, namaz kilmayan, tarik namaz, tarik salat, leaves prayer, abandon prayer, abandons prayer, not praying, neglect prayer, skipping prayer, не молящийся, не совершающий намаз, оставляющий молитву, тот кто не молится => تارك الصلاة
namaz, namazi, namaza, namazin, namazlar, salat, salah, salaah, prayer, prayers, praying, молитва, молитвы, молитв, намаз, namaz qilmaq, namaz kilmak => الصلاة
namaz vaxtlari, namaz vakitleri, prayer times, times of prayer, awqat al salah, mawaqit, время молитв, время намаза => أوقات الصلاة / مواقيت الصلاة
yasaq vaxtlar, yasak vakitler, times when prayer is forbidden, prohibited times for prayer, makruh times, запретные времена для молитвы, awqat al nahy => أوقات النهي عن الصلاة
subh namazi, sabah namazi, fajr, fajr prayer, фаджр, утренний намаз, утренняя молитва => صلاة الفجر
ogle namazi, zohr namazi, zuhr, dhuhr, зухр, полуденный намаз => صلاة الظهر
ikindi namazi, esr namazi, asr, asr prayer, аср, послеполуденный намаз => صلاة العصر
aksam namazi, axsam namazi, maghrib, magrib, магриб, закатный намаз => صلاة المغرب
yatsi namazi, xuften namazi, isha, isha prayer, иша, ночной намаз => صلاة العشاء
suneti rateb, sunan rawatib, rawatib, sunnah prayers, sunnet namazlar, суннат намаз, раватиб, suneti muekkede => السنن الرواتب
rekat sayi, rakat sayisi, number of rakats, number of rak'ahs, rak'ah count, количество ракатов, rekat, rakat, rakah, rak'ah, ракат => عدد ركعات الصلاة
vitr, vitir, witr, witir, витр, vitr namazi => صلاة الوتر / الوتر
qunut, kunut, qunoot, qunut dua, кунут, qunut witr, kunut vitir, kunut sabah => القنوت / قنوت الوتر
teravih, tarawih, taraweeh, qiyam ramadan, тарауих, таравих, teravih namazi, teravih kac rekat, 20 rekat teravih, 8 rekat teravih => صلاة التراويح / قيام رمضان
tehecud, teheccud, tahajjud, qiyam al layl, gece namazi, night prayer, ночной намаз, тахаджуд, qiyamul layl => قيام الليل / التهجد
duha namazi, duha, dhuha, salat ad duha, forenoon prayer, духа, духа намаз, israq namazi, ishraq prayer, ишрак => صلاة الضحى
tehiyyetul mescid, tahiyyat al masjid, greeting the mosque, prayer on entering the mosque, приветствие мечети, tahiyatul masjid => تحية المسجد
cemaatle namaz, cemaat namazi, camaatla namaz, jamaah, jama'ah, congregational prayer, prayer in congregation, praying in congregation, коллективный намаз, джамаат, cemaat vacib mi, is congregation obligatory => صلاة الجماعة / وجوب صلاة الجماعة
imama uymak, imamin arxasinda, behind the imam, praying behind the imam, following the imam, за имамом, muqtedi, muktedi, ma'mum => الائتمام بالإمام / متابعة الإمام
fasiq imam, bidetci imam, praying behind an innovator, praying behind a sinner, namaz fasik imam, за имамом нововводителем, за имамом грешником, behind ahl al bid'ah, imamet fasiq => الصلاة خلف الفاسق / الصلاة خلف المبتدع
masbuq, geç qalmaq namaza, late to prayer, joining prayer late, опоздавший на молитву, missed rak'ah, raka kacirmak => المسبوق في الصلاة
imam arxasinda fatiha, fatiha behind the imam, reciting fatiha behind imam, чтение фатихи за имамом, qiraah khalf al imam, imamin ardinda fatiha, fatiha ardinda imam => القراءة خلف الإمام
besmele cehr, besmeleyi aciq oxumaq, basmala aloud, reciting basmala aloud, джахр басмала, bismillah aloud, bismillah gizli => الجهر بالبسملة
amin, ameen, saying amin, aloud amin, амин вслух, amin cehri, amin yuxari ses => التأمين في الصلاة / الجهر بالتأمين
rafal yadayn, rafu yadayn, raising hands in prayer, raising hands in takbir, поднимать руки в намазе, elleri kaldirmak namaz, el qaldirmaq namaz, el qaldirmaq rukudan sonra => رفع اليدين في الصلاة
elleri baglamak, qol baglamaq, folding arms in prayer, placing hands, положение рук в намазе, el baglamak namaz, el baglama, hands on the chest, ellerin gogusde, hands under navel, ellerin nerede olmasi => وضع اليدين على الصدر / قبض اليمين على الشمال
secde, sujud, sajda, sajdah, prostration, поклон земной, суджуд, sedjde, secdeye => السجود
sehv secdesi, sujud sahw, sahw prostration, prostration of forgetfulness, суджуд сахв, sehv sejdesi => سجود السهو
tilavet secdesi, sajdat tilawa, recitation prostration, prostration of recitation, суджуд тилява => سجود التلاوة
sukr secdesi, sajdat shukr, prostration of gratitude, суджуд шукр => سجود الشكر
cuma, cumə, jumua, jumuah, friday prayer, джума, пятничный намаз, juma namazi, cuma namazi => صلاة الجمعة
cuma xutbesi, cuma hutbesi, friday sermon, khutba, хутба, kutbe, xutbe => خطبة الجمعة
cuma ezani, ikinci ezan, ikinci azan, second adhan on friday, второй азан, cuma ikinci ezan => الأذان الثاني يوم الجمعة
ezan, azan, adhan, call to prayer, азан, adhan, ezan oxumaq, ezan cehri => الأذان
ikamet, iqama, iqamah, икама, ikamə => الإقامة
bayram namazi, eid prayer, eid salah, ид намаз, bayram namazı, namaz id => صلاة العيدين
cenaze namazi, janaza prayer, janazah prayer, funeral prayer, джаназа, сүннәт, salat al janazah, namaz janaza, cenaze namazi nasil, ghaib janaza => صلاة الجنازة
qaib cenaze, ghaib janaza, janazah in absentia, заочная джаназа, namaz gaib, gaiben cenaze => الصلاة على الغائب
istisqa, istiska, yagmur namazi, rain prayer, prayer for rain, молитва о дожде, yagish namazi => صلاة الاستسقاء
kusuf, husuf, gunes tutulmasi namazi, eclipse prayer, solar eclipse prayer, молитва при затмении, ay tutulmasi namazi => صلاة الكسوف
yolcu namazi, seferi namazi, qasr, kasr, shortening prayer, shortening the prayer, traveller's prayer, namaz in travel, укорочение намаза, намаз в пути, sefer namazi, qesr namaz => قصر الصلاة / صلاة المسافر
cem namazi, camaa, jam' prayers, combining prayers, combining two prayers, объединение намазов, jam taqdim, jam taakhir, iki namazi birlestirmek, iki namazi cem etmek, iki namazi birlestirmek => الجمع بين الصلاتين
mesafe sefer, safe distance travel, distance of travel, masafat al qasr, qasr distance, how far to shorten prayer, qasr mesafesi, sefer mesafesi => مسافة القصر
xeste namazi, hasta namaz, prayer of the sick, praying while sick, praying sitting, oturarak namaz, ayakta duramayan, namaz in illness, молитва больного, молитва сидя => صلاة المريض
korpe, bedel, namazin qazasi, qaza namazi, kaza namazi, missed prayer, make up prayer, make up missed prayer, qada prayer, пропущенный намаз, восполнение намаза, qaza, kaza => قضاء الصلاة / قضاء الفوائت
yuxuda namaz, uyuyup namaz, sleeping and missing prayer, missing prayer due to sleep, oversleeping, проспал намаз, namaz uyku kacirmak => من نام عن صلاة أو نسيها
qibla, kible, qiblah, qiblа, direction of prayer, direction of qibla, кибла, qibleyi bulmak, finding the qibla => استقبال القبلة
namazda quran, nafile namazda quran, quran from mushaf in prayer, reading from mushaf in prayer, держа коран в намазе, mushafdan namaz, qiraat from mushaf => القراءة من المصحف في الصلاة
namazda qadin, qadinlarin namazi, women's prayer, womans prayer, how a woman prays, женский намаз, kadin namazi, kadinlar mescide, women going to the mosque, women in the mosque, женщины в мечети, qadinlarin mescide getmesi => صلاة المرأة / خروج النساء إلى المساجد
namaz esnasında, namazi bozan, namazi pozan, mufsidat, mufsidat as salah, things that invalidate prayer, invalidate prayer, break prayer, что аннулирует намаз, namazin batil olmasi, namaz batil, namaz pozulur => مبطلات الصلاة
namazda gulmek, laughing in prayer, смех в намазе, kahkaha namaz => الضحك في الصلاة
namazda konusmak, talking in prayer, говорить в намазе, speaking in prayer => الكلام في الصلاة
namazda ayet, namazda tesbih, tasbih in prayer, dhikr in prayer, зикр в намазе => الذكر في الصلاة
musalla, sutra, sutre, sutrah, prayer in front of a person, passing in front of person praying, walking in front of someone praying, проход перед молящимся, namaz kilanin onunden gecmek, namaz qilanin qarsisindan kecmek => المرور بين يدي المصلي / السترة
mescid, masjid, camii, mosque, mosques, мечеть, мечети, mescit => المساجد / المسجد
mescidde yatmak, sleeping in the mosque, sleeping in mosque, сон в мечети, mescitte uyumak => النوم في المسجد
mescide haile qadin, menstruating woman in the mosque, hayizli kadin mescit, хайд мечеть, haiz mosque => دخول الحائض المسجد
mescide girmek, entering the mosque, dua entering the mosque, вход в мечеть, mescide giris adabi, mescid adabi => آداب دخول المسجد
mescidde yuksek ses, raising voice in the mosque, loud voice in mosque, shout in mosque, mescitte yuksek ses => رفع الصوت في المسجد
mescidde sattis, selling in the mosque, buying and selling in the mosque, mescitte alisveris, mescitte satis => البيع في المسجد
mescidi zinetlemek, decorating mosques, decoration of mosques, украшение мечетей, mescit susleme, minaret => زخرفة المساجد / تزيين المساجد
# ===== ZƏKAT, SƏDƏQƏ
zekat vermeyen, zekat vermemek, mani zakat, withholding zakat, not paying zakat, refuse zakat, не выплачивающий закят => مانع الزكاة
zekat, zakat, zəkat, закят, zakah, zakat al mal => الزكاة
zekat kimlere verilir, zakat kimlere verilir, zekat kimlere, zekatin masrafi, who receives zakat, recipients of zakat, who can receive zakat, ashnaf, asnaf al zakat, кому давать закят, получатели закята, masarif al zakat, 8 sinif => مصارف الزكاة / أهل الزكاة
nisab, nisap, nisab miqdari, nisab of zakat, нисаб, nisabi, zekat nisabi => نصاب الزكاة
altin zekat, gumus zekat, altin gumus zekati, zakat on gold, zakat on silver, закят с золота, zakat on jewelry, ziynet esyasi zekat, zinet zekati, jewelry zakat, zekat on women's jewelry, украшения закят, qadin zinet zekat, qadin zinet esyalari => زكاة الحلي / زكاة الذهب والفضة
ticaret mali zekat, trade goods zakat, zakat on merchandise, закят с товаров, tacir zekat, ticaret zakati => زكاة عروض التجارة
heyvan zekati, zakat on livestock, закят со скота, davar zekati, hayvan zekati, sigir zekat, koyun zekat, deve zekat => زكاة بهيمة الأنعام / زكاة الأنعام
ziraat zekati, usr, ushr, tarim zekat, zakat on crops, закят с урожая, mehsul zekat, ekin zekati => زكاة الزروع والثمار / العشر
borc zekat, borcun zekati, zakat on debt, zakat on loans, закят с долга, alacaq zekat, dayn zakat => زكاة الدين
fitre, zakat al fitr, zakat fitr, fitr sadaqasi, закят аль-фитр, fitir sadaqa, fitre miktari, fitre ne zaman, fitr amount => زكاة الفطر
sedeqe, sadaka, sadaqa, charity, садака, sadaqa jariya, sedeqe cariye, sadaqah => الصدقة
nafile sedeqe, voluntary charity, добровольная садака, ihsan sadaqat => صدقة التطوع
sedeqe olu ucun, sadaka olu icin, charity on behalf of the dead, садака за умершего, olu adina sedeqe => الصدقة عن الميت
kafferet, kefaret, kaffarah, expiation, искупление, kaffara => الكفارة
# ===== ORUC
oruc tutmayan, oruc yemek ramazanda, ramazanda oruc yemek, breaking fast intentionally, not fasting ramadan, не держащий пост => الفطر في رمضان / ترك الصيام
oruc, orucun, siyam, saum, sawm, fasting, fast, пост, ураза, orucu, orucluq => الصيام
oruc pozan, orucu bozan, orucu pozan, mufattirat, mufattirat as siyam, things that break the fast, breaks the fast, nullifiers of fasting, что нарушает пост, orucu pozan seyler, orucu pozan sey, orucu bozan seyler => مفطرات الصيام / ما يفسد الصيام
oruc niyyeti, niyyet oruc, intention for fasting, намерение поста, niyet orucun, orucun niyeti => نية الصيام
unutarak yemek, unutup yemek, eating by forgetfulness while fasting, eating forgetfully, ate while fasting, поел по забывчивости, oruc unutmaq, oructa unutmak => من أكل أو شرب ناسيا وهو صائم
orucda qusmaq, vomiting while fasting, рвота и пост, oruc kusmak, kusmak oruc => القيء للصائم
oruc inje, injection while fasting, инъекция в пост, oruc igne, iyne oruc, igne vurdurmak oruc, infusion fasting, damla, serum oruc, tibbi muayene oruc => الإبرة للصائم / الحقنة للصائم
oruc dis fircalamaq, brushing teeth while fasting, чистка зубов в пост, oruc misvak, oruc dis, dis macunu oruc => السواك للصائم
oruc gozunu, eye drops while fasting, закапывать глаза в пост, goz damla oruc, goz damlasi oruc, burun damlasi oruc, nasal spray fasting, ear drops fasting => قطرة العين والأذن للصائم
oruc ve qan, cupping while fasting, hijama while fasting, хиджама в пост, hicama oruc, hacamat oruc, donating blood fasting, qan vermek oruc => الحجامة للصائم
oruc cimae, intercourse during ramadan, intercourse while fasting, джима в рамадан, ramazanda cima, ramazan gunduzu cima, oruc halinda cinsi, oruc cinsi, cinsi oruc => الجماع في نهار رمضان
musafir orucu, yolcu orucu, fasting while traveling, fasting in travel, пост в пути, seferde oruc, sefer oruc => صوم المسافر / الفطر في السفر
xeste oruc, hasta oruc, fasting while sick, пост больного, sick and fasting, hastalikta oruc => صوم المريض
hamile oruc, hamile ve emziren oruc, pregnant and nursing fasting, беременная пост, emziren kadin oruc, hamile qadin oruc, nursing mother fasting, fidye pregnant => صيام الحامل والمرضع
fidye, fidya, fidyah, fidye orucu, fidye miktari, оставить фидью, фидья, fidiyə, fidye ne kadar, fidye verme => الفدية في الصيام / الإطعام
oruc qaza, kaza orucu, qaza oruc, make up fasting, make up missed fasts, восполнить пост, ramazan kazasi, ramazan orucunun kazasi, orucun qazasi => قضاء رمضان / قضاء الصوم
sebe qaza, kazani gecikdirmek, delaying qada of ramadan, откладывание восполнения, ramazan kazasini geciktirmek => تأخير قضاء رمضان
nafile oruc, voluntary fasting, добровольный пост, sunnet oruc, sunnah fasting, nafl fasting, nafl oruc, pazartesi persembe orucu, monday and thursday fasting, понедельник четверг пост, ayyam al beed, beyaz gunler, ayyami biyd, 13 14 15 oruc, shawwal six days, sevval alti gun, sevval orucu, sunnah fasts => صيام التطوع / صيام الأيام البيض / صيام ست من شوال
arefe orucu, day of arafah fasting, arafa orucu, день арафа пост, arefe gunu orucu, yawm arafah fasting => صوم يوم عرفة
cum orucu, friday fasting alone, fasting on friday only, пост в пятницу, cuma gunu oruc, cumani yalniz tutmak, saturday fasting, shanba orucu, cumartesi orucu, singling out saturday => إفراد الجمعة بالصوم / صوم يوم السبت
vusal orucu, wisal fasting, continuous fasting, непрерывный пост, ard arda oruc, gece gunduz oruc => صوم الوصال
sehur, suhoor, sahur, sehri, сухур, sahoor, imsak, imsaq, imsak vaxti, fajr and suhoor, sahura kalkmak => السحور
iftar, iftari, fitr, break fast, ифтар, iftar vaxti, iftar dua, iftar duasi, iftari tez acmaq, hasten iftar, eat iftar dates => الإفطار / تعجيل الفطر
itikaf, i'tikaf, itikaf, itikaf yapmaq, retreat in mosque, итикаф, itikaf nasil, mescidde itikaf, women itikaf => الاعتكاف
qedir gecesi, kadir gecesi, laylat al qadr, night of power, night of decree, ночь могущества, ночь предопределения, laylatul qadr, lailatul qadr, kadir gecesi dua, qedir gecesi hansi => ليلة القدر
sevval, shawwal, шавваль, sevval bayrami => شوال / صوم ست من شوال
hilal, hilali gormek, moon sighting, sighting the crescent, crescent sighting, ru'yat al hilal, ay gorunmesi, астрономический расчет, ay hesabi => رؤية الهلال / إثبات الشهر
yawm ash shakk, sak gunu, day of doubt, день сомнения => صوم يوم الشك
# ===== HƏCC, ƏMRƏ, QURBAN
hec, hecc, hac, haj, hajj, hac ibadeti, хадж, паломничество => الحج
umre, umra, umrah, умра => العمرة
ihram, ihram, ихрам, ihrama girmek, ihram yasaklari => الإحرام / محظورات الإحرام
tavaf, tawaf, таваф, kabeyi tavaf => الطواف
saee, sa'y, sai al safa, саъй, safa ve merve => السعي بين الصفا والمروة
arafe, arafat, arafah, arafa, арафат, vukuf, wuquf => الوقوف بعرفة
muzdelife, muzdalifah, muzdalifa, мудзалифа => المبيت بمزدلفة
mina, rami, ramy, cemre, jamarat, stoning of jamarat, steganie, бросание камней, камни шайтану => رمي الجمار
hedy, hady, hedy kurbani, damm tamattu, жертва хаджа => الهدي
temettu, tamattu, temettu haccı, qiran, kiran, ifrad, ифрад, тамматту => التمتع والقران والإفراد
mikat, miqat, mawaqit hajj, микат, mikat yeri => المواقيت المكانية / الميقات
hacc vekalet, badal hajj, hajj on behalf of another, hajj for the dead, хадж за другого, hacc bedel, hac vekaleten => الحج عن الغير
hacc yoldasi mehrem, mahram for hajj, махрам для хаджа, kadinin mehramsiz hacci, woman without mahram, женщина без махрама, mehramsiz seyahat, qadinin mehremsiz sefer => سفر المرأة بلا محرم
zemzem, zamzam, замзам, zemzem suyu => ماء زمزم
hacerul esved, black stone, hajar aswad, черный камень, kabe, kaaba, ka'ba, kaabe, кааба => الحجر الأسود / الكعبة
mekke, meke, mecca, makkah, мекка, haram bolgesi, harem bolgesi, haram zone => مكة / حرم مكة
medine, madina, medina, madinah, медина, mescidi nebevi, masjid an nabawi => المدينة النبوية / مسجد النبي
qurban, kurban, udhiyah, udhiya, курбан, kurban kesmek, kurban kesimi => الأضحية
kurban hisse, kurbanda ortaklik, sharing udhiyah, sharing a sacrifice, доля в жертве, qurbanin hisseleri, seven shares, yedi hisse => الاشتراك في الأضحية
akika, aqiqah, aqeeqah, акика, ақика, doğum kurbanı, dogum kurbani, newborn sacrifice => العقيقة
# ===== NİKAH, ƏİLƏ
nikah, nikax, kabin, marriage, wedding, брак, никах, evlilik, evlenmek => النكاح
veli, vali, wali, guardian in marriage, опекун невесты, nikah velisi, velisiz nikah, nikah without guardian, никах без вали => الولي في النكاح / النكاح بلا ولي
mehr, mahr, mehir, dower, bridal gift, махр, mehr miqdari, mehrin miktari, meher => المهر / الصداق
sahid nikah, iki sahid, witnesses in marriage, свидетели при никахе, nikah sahitleri => الشهود في النكاح
mut'a nikahi, muta nikahi, mut'ah, muta marriage, temporary marriage, временный брак, mutaa, muta nikahi => نكاح المتعة
misyar, misyar nikahi, misyar marriage, мисьяр, urfi nikah, urfi evlilik, secret marriage, gizli nikah, gizli evlilik, nikah without registration, civil marriage, resmi nikah, mülki nikah, civil nikah => النكاح بنية الطلاق / النكاح السري / عقد النكاح
tehlil, muhallil, nikah muhallil, tahlil marriage, halala, халяла, hulle, hulla, tehlil nikahi, hulle nikahi => نكاح المحلل / التحليل
cox arvadli, birden fazla evlilik, polygamy, polygyny, многоженство, taaddud zevcat, iki arvad, 4 qadin, dörd arvad, dort kadin => تعدد الزوجات
xitbe, hitbe, hitba, khitba, engagement, помолвка, nisan, nisanlilik, nishan, fiance, namzəd => الخطبة
nisanlini gormek, seeing the fiancee, видеть невесту, nisanli kiza bakmak, looking at the fiancee => النظر إلى المخطوبة
zevcin haqqi, qadinin haqqi, kocanin haklari, husband's rights, rights of the husband, права мужа, ərin hüquqları, ərin haqqı => حقوق الزوج على زوجته
zevcenin haqqi, arvadin haqqi, karinin haklari, wife's rights, rights of the wife, права жены, arvadın hüquqları => حقوق الزوجة على زوجها
nefeqe, nafaka, nafaqa, maintenance, spousal support, алименты, нафака, spending on family => النفقة على الزوجة
nushuz, nushuz, disobedient wife, непокорность жены, qadinin itaetsizligi, kadinin serkeşligi, asi kadin => النشوز
qadinin dovulmesi, wife beating, beating one's wife, избиение жены, kocanin karisini dovmesi, arvadi dovmek => ضرب الزوجة
hicab, hijab, hijab, хиджаб, hicabi, basortusu, basörtüsü, headscarf, bashli, bashorty, kapanma, ortunmek, ortunme => الحجاب
niqab, nikab, niqab, yuz ortusu, face veil, никаб, yuzunu ortmek, veiling the face, covering the face => النقاب / تغطية الوجه
avret, awrah, awra, aurat, авра, gizli yerler, avret yeri, avret yerleri, hudud al awrah => العورة
ecnebi qadinla, ihtilat, ixtilat, mixing of men and women, смешение мужчин и женщин, qarisiqliq, kadin erkek karisikligi, birlikdelik, khalwa, halvet, khalwah, yalnizlik, khalwa with a non mahram, остаться наедине, namehremle yalniz => الاختلاط / الخلوة بالأجنبية
mehrem, mahram, махрам, namehrem, nonmahram, non mahram, ajnabi, ajnabiyyah, not mahram, немахрам, mahramlar, mehremler, kimler mahremdir => المحارم / الأجنبية
musafeha, musafaha, handshake, handshake with women, shaking hands with women, рукопожатие с женщиной, qadinla el vermek, kadinla el sikismak, kadinlarla musafeha => مصافحة النساء / مصافحة الأجنبية
# ===== TALAQ, BOŞANMA
talaq, talak, bosanma, bosanmaq, divorce, развод, талак, boşanmaq => الطلاق
uc talaq, uc talak, ucluk talaq, talaq thalatha, three talaq, three divorces, triple talaq, тройной талак, talaq bid'i, bir meclisde uc talaq, three divorces in one sitting, three talaqs at once, bir lafizla uc talak, uc talaq bir sozle, ucu bir arada => الطلاق الثلاث بلفظ واحد / طلاق الثلاث
talaq bidet, bid'i talaq, talak bidati, talaq during menstruation, divorce during menses, talak heyz halinda, развод во время хайда, adet halinde bosamak, heyz halinda talaq => الطلاق في الحيض / الطلاق البدعي
ses ile talaq, mektup ile talaq, talaq by text message, divorce by sms, divorce by text, талак по смс, telefonla talaq, talak sms ile, whatsapp talaq => الطلاق بالكتابة / الطلاق الكتابي
qezeb halinda talaq, ofke ile talaq, divorce in anger, talaq in anger, талак в гневе, gazapla bosama, ghadab talaq, ighlaq, ighlaq talaq => طلاق الغضب / الإغلاق
sakirin talaqi, serxosun talaqi, drunk divorce, divorce while drunk, talak sarhos, развод пьяным, sarhos talak => طلاق السكران
mualleq talaq, sherte baglı talak, conditional divorce, conditional talaq, талак с условием, sartli talak, talaq with condition, yemin ile talaq, talaq oath, oath of divorce, divorce oath, halefan bit talaq, talak ile yemin, talaq ile and icmek => الطلاق المعلق / الحلف بالطلاق
xul', hul, khula, khul', hul', хуль, yanindan ayrilmak, wife asks for divorce, kadinin bosanmasi, kadinin talak istemesi => الخلع
ila, zihar, zıhar, zihar kefareti, zihar, эль-иля, зихар, zihar yapmaq => الإيلاء والظهار / الظهار
liyan, li'an, lian, лиан, mulaana, mula'ana => اللعان
iddet, idda, iddah, идда, iddət, iddet bekleme, wait period, waiting period after divorce, iddet muddeti, qadinin iddəsi => العدة
iddet olum, iddet vefat, mourning period of widow, ihdad, iddah of widow, траур вдовы, dul kadinin iddeti, dul qadinin yası, qadin ihdad, hdad, ihdad kadin => إحداد المرأة / عدة الوفاة
ruci talaq, raj'i, revocable divorce, возвращение жены, ruju, rucu, rujuu, ruj'a, take back wife, taking back wife, geri almaq, geri dönmek, kocasına dönmek => الرجعة / الطلاق الرجعي
rada, radaa, rada', emzirmek, suyu emzirme, milk kinship, foster milk, молочное родство, suddaşı, sut qardasliq, sut anne, süd emme, ses emmek, sut emme, 10 emme, rada' bes emme => الرضاع
hadane, hadana, hadanah, hizane, hidane, custody of children, child custody, опека над детьми, usagin saxlanmasi, cocuk velayeti, cocuk haklari bosanma, bosanmadan sonra cocuk, child after divorce => الحضانة
kocanin hakki bosama, talaq selahiyyeti, who has the right to divorce, kim bosayabilir, the husband's right to divorce, право на развод => الطلاق بيد من / من يملك الطلاق
# ===== ALIŞ-VERİŞ, RİBA
riba, faiz, faizi, usury, interest, ростовщичество, проценты, процент, ribа, ribaa => الربا
bank faizi, banka faizi, bank interest, interest from bank, банковский процент, banka ile muamele, banking, bank krediti, kredi, credit, bank loan, loan with interest, кредит, loans => الربا في المصارف / القروض بفائدة
ribanin novleri, riba al fadl, riba an nasia, types of riba, виды риба, ribal fadl, nesie ribasi, fazl ribasi => ربا الفضل وربا النسيئة
alis veris, alish veris, bey', bay', bay, buyu, buyu', selling, buying, купля продажа, торговля, ticaret, trade, business, tijarat, ticarat => البيع / البيوع
qarar, gharar, garar, uncertainty in sale, неопределенность, belirsizlik satis, gharar sale => بيع الغرر
aldatmaq ticaret, ghish, gish, aldatma, cheating in trade, fraud in trade, обман в торговле, hile, hileli satis, nadjash, najash, najsh => الغش في البيع / النجش
taksit, taksitle satis, installment sales, installments, рассрочка, bay' al taqsit, nasia sale, deferred price, vadeli satis, vadeli, veresiye, nisye, nasi'a => البيع بالتقسيط / بيع النسيئة
ina, ayna, bay al ina, bay al inah, inah sale, hile ile faiz, мнимая продажа, tawarruq, teverruk, tawarruq banking, tawarruq loan => بيع العينة / التورق
selem, salam sale, salam contract, bay as salam, аванс торговля, selem satisi, salaf => السلم / بيع السلم
murabeha, murabaha, мурабаха, murabaha bank, islamic bank, islamic banks, ислам банк, katilim bankasi, islamic finance, исламское финансирование, ислам финанс, katilim bank => المرابحة / المصارف الإسلامية
sirket, şirkət, partnership, ortaqliq, ortaklik, партнерство, shirkah, sharika, partnership in business => الشركة
mudarebe, mudaraba, mudharaba, мудараба, qirad => المضاربة / القراض
musaqat, muzara'a, muzaraa, musakat, sharecropping, мусака, мазараа, tarlada ortaklik, ortakcilik => المساقاة والمزارعة
icare, ijara, ijarah, rent, rental, renting, leasing, аренда, kiralama, kira, icare => الإجارة
vekalet, wakala, wakalah, agency, power of attorney, доверенность, vəkalət => الوكالة
kefalet, kafala, kafalah, guarantee, guarantor, поручительство, kefil, qefil => الكفالة / الضمان
rehn, rahn, pledge, collateral, залог, ipotek, mortgage, ipoteka, ипотека, ev kredisi, housing loan, mortgage loan => الرهن
havale, hawala, hawalah, transfer of debt, перевод долга, hevale => الحوالة
borc, dayn, qard, qarz, debt, loan, долг, ödünc, borc vermek, borc almaq, borc yemek => القرض / الدين
borcu odemek, qeder borc, paying debts, repaying debt, возврат долга, borclu, borcunu ode, insolvent, olsuz, mufli, iflas, bankruptcy, банкротство => الدين / الإفلاس
hibe, hiba, hibah, gift, дарение, hediye, bagis, gifts, bagislamak => الهبة
vaqf, vakif, waqf, вакф, vakf, endowment => الوقف
vesiyyet, wasiyya, wasiyyah, will, bequest, завещание, vesiyet, vasiyat => الوصية
miras, mirass, irs, mirath, inheritance, наследство, наследование, faraiz, fara'id, ferai, miras bolusu, miras taksimi, inheritance division, inheritance of women, qadin miras, kiz miras => المواريث / الفرائض
luqta, lukata, luqata, lost property, found property, находка, bulunmus mal, tapilmis mal, tapilan seyler, kayip esya, lost and found => اللقطة
gasb, ghasb, ghasb, usurpation, usurping, угон, zorla almaq, tecavuz mal, haksiz mal, haram mal, haram money, haram kazanc, haram earnings, haram kazanc, haram mal, haram malin zekati, unlawful wealth, незаконный доход, haram gelir, haram qazanc => الغصب / المال الحرام / أكل أموال الناس بالباطل
rusvet, rüşvət, rushwa, bribe, bribery, взятка, ruşvət, hadiyye qebul, hediye qebul, accepting gifts, ocho, riswa, ruswa, ruswet => الرشوة / هدايا العمال
inhisar, ihtikar, ihtikar, ihtikâr, hoarding, monopoly, hoarding food, монополия, накопление, spekulyasiya, speculation, спекуляция, bahalandirma, price gouging => الاحتكار / التسعير
tesir, tes'ir, price fixing, price control, регулирование цен, qiymet tenzimi, fiyat belirleme, fiyat kontrolu, tas'ir, tasir => التسعير
alisverisde yemin, selling with oath, swearing in trade, клятва при торговле, satista yemin, ticarette yalan yemin => الحلف في البيع
sarraf, sarf, sarf, exchange of currency, currency exchange, обмен валют, valyuta, valyuta deyisme, currency trading, forex, форекс, dollar, dollar exchange, change money, para bozdurmak, arbitrage => الصرف / بيع العملات
kağız pul, kagit para, paper money, бумажные деньги, banknote, banknotes, fiat, fiat money, ағыз pul, nəqd pul faizi, riba in paper money, ribawi in paper currency, fulus, fulûs => النقود الورقية / الفلوس / الأوراق النقدية
# ===== HÜDUD, CİNAYƏT
zina, zinaa, zina etmek, adultery, fornication, прелюбодеяние, зина => الزنا / حد الزنا
qazf, kazf, qadhf, iftira zina, false accusation of zina, клевета на целомудренных => القذف
oqurluq, hirsizlik, sariqa, sirqa, theft, stealing, кража, воровство => السرقة / حد السرقة
yol kesme, hirabe, hirabah, highway robbery, разбой => الحرابة / قطاع الطريق
xemr, hamr, khamr, alcohol, wine, спиртное, алкоголь, вино, icki, alkol, serxosluq, sarhosluk, drinking alcohol => الخمر / شرب الخمر
narkotik, uyusturucu, esrar, hashish, drugs, наркотики, mukhaddirat, marijuana, cannabis, kenevir, afyon, heroin, kokain, cocaine => المخدرات / الحشيشة
siqaret, sigara, cigarette, cigarettes, tobacco, smoking, курение, сигареты, табак, tutun, nargile, hookah, кальян, vaping, elektron siqaret => الدخان / التدخين
qisas, kisas, retribution, возмездие, kisas ve diyet => القصاص
adam oldurmek, qetl, murder, убийство, cinayet, killing a person => القتل / قتل النفس
diyet, diya, diyah, blood money, дийа, qan pulu, kan parasi => الدية
intihar, suicide, самоубийство, ozunu oldurmek, killing oneself => الانتحار / قتل النفس
teazir, ta'zir, taazir, discretionary punishment => التعزير
murtedin qatli, killing the apostate, казнь вероотступника, riddet cezasi => قتل المرتد / حد الردة
peygambere hakaret, nebiye heqaret, insulting the prophet, cursing the prophet, оскорбление пророка, sabb ar rasul, blasphemy => سب الرسول
allaha kufur, allaha sovmek, cursing allah, ругать аллаха, sabb allah => سب الله
dinle alay, din ile alay, mocking religion, ridiculing religion, насмешка над религией, istihza => الاستهزاء بالدين
sahabeyi sebb, sahabeye kufur, cursing the companions, insulting the companions, ругать сподвижников, sabb as sahaba => سب الصحابة
sahaba, sahabe, companions of the prophet, сподвижники, асхабы, ashab => الصحابة
ehli beyt, ehlibeyt, ahl al bayt, ahlul bayt, family of the prophet, семья пророка, ахль аль-бейт => أهل البيت
hz ali, ali ibn abi talib, imam ali, али ибн аби талиб => علي بن أبي طالب
muaviye, muawiya, mu'awiyah, муавия => معاوية
yezid, yazid, езид, yezid ibn muaviye => يزيد بن معاوية
hz aise, aisha, aysha, aise, аиша => عائشة
ebu bekr, abu bakr, абу бакр => أبو بكر الصديق
omer ibn xettab, umar ibn al khattab, омар ибн хаттаб, hz omer => عمر بن الخطاب
osman ibn affan, uthman ibn affan, усман ибн аффан => عثمان بن عفان
# ===== CİHAD, SİYASƏT
cihad, jihad, джихад, gaza, ghazwa, qital => الجهاد / القتال
cizye, jizya, джизья, jizya tax, poll tax => الجزية
ehli zimme, ahl al dhimma, dhimmi, zimmi, зимми => أهل الذمة
ehli kitab, ahl al kitab, people of the book, люди писания => أهل الكتاب
yahudiler, yahudi, yehudi, jews, jewish, евреи, иудеи, judaism, иудаизм => اليهود
hristiyan, nesrani, nasara, christians, christian, христиане, христианин, christianity, христианство, trinity, teslis, троица => النصارى / التثليث
mecusi, majus, zoroastrian, огнепоклонники, atesperest, fire worshipers => المجوس
sabiiler, sabians, сабии => الصابئة
tatarlar, tatar, tatars, mongols, монголы, татары, moğol => التتار
xilafet, hilafet, khilafah, caliphate, caliph, халифат, халиф, halife => الخلافة
imamet, imamate, имамат, imamiyye, twelve imams, 12 imam, onikinci imam => الإمامة / الإمامية
mehdi, mahdi, махди, mehdi intizar => المهدي
veliyyul emr, vali emr, wali al amr, ulil emr, ulul amr, ruler obedience, obedience to rulers, послушание правителю, hakime itaat => طاعة ولي الأمر
zalim hakim, unjust ruler, zalim yonetici, несправедливый правитель => الإمام الجائر / الصبر على جور الولاة
huruc, khuruj, rebellion against ruler, revolt against ruler, восстание против правителя, hakime karsi cikmak, hakime isyan => الخروج على الحاكم
bagi, bughat, ahl al baghy, rebels, повстанцы, мятежники => قتال أهل البغي
secim, secimler, election, elections, voting, выборы, голосование, secimde oy vermek => الانتخابات
demokrasi, demokratiya, democracy, демократия => الديمقراطية / الشورى
sura, shura, consultation in ruling, шура => الشورى
partiya, siyasi parti, political party, политическая партия => الأحزاب
ihvan, ikhwan, muslim brotherhood, братья мусульмане => جماعة الإخوان / الجماعات
hizb ut tahrir, hizbut tahrir, хизб ут-тахрир => حزب التحرير / الجماعات
tebligh cemaati, tablighi jamaat, tabligh jamaat, таблиг => جماعة التبليغ
emr bil maruf, amr bil maruf, enjoining good, forbidding evil, nehy anil munker, повеление одобряемого, запрет порицаемого => الأمر بالمعروف والنهي عن المنكر
hisba, hisbe, muhtasib, мухтасиб => الحسبة
siyaset, siyaseti seriyye, siyasa shariyya, islamic politics => السياسة الشرعية
vela ve bera, wala wal bara, al wala wal bara, аль-вала валь-бара, loyalty and disavowal => الولاء والبراء
kafirlere yardim, helping kafirs, helping non muslims against muslims, tevalli kuffar => موالاة الكفار / الاستعانة بالكفار
hicret, hijrah, hijra, хиджра, emigration => الهجرة
kafir olkesinde yasamaq, living in kafir land, living among non muslims, living in the west, жить среди неверных, жить на западе => الإقامة بين المشركين / دار الكفر
sulh, suleh, peace treaty, мирный договор, перемирие, ahd, covenant => الصلح / العهد
aman, musta'min, mustamin, safe conduct, visa, виза => الأمان / المستأمن
esir, asir, prisoners of war, captives, военнопленные, пленные => الأسرى
ganimet, ghanima, spoils of war, booty, добыча, fey, fay => الغنيمة / الفيء
kolelik, slavery, qulluq, рабство, rabstvo, cariye, concubine, ملك اليمين => الرق / ملك اليمين
# ===== YEMƏK-İÇMƏK, GEYİM, ƏYLƏNCƏ
halal food, helal yemek, халяль еда, halal et, helal et => الأطعمة المباحة / الحلال والحرام
haram yemek, haram food, forbidden foods, prohibited foods, запрещённая еда => الأطعمة المحرمة
kesim, zebihe, zabiha, dhabiha, zebh, islamic slaughter, slaughtering, забой скота, зябиха => الذبائح / الذكاة
ehli kitabin kestigi, ehli kitabin zebihesi, meat of the people of the book, мясо людей писания, marketten et, supermarket meat => ذبائح أهل الكتاب
besmelesiz kesim, meat without bismillah, besmele unutmak kesende, забой без бисмиллы => الذبيحة بغير تسمية / ترك التسمية على الذبيحة
domuz, donuz, pork, pig, swine, свинина, свинья, domuz eti => الخنزير / لحم الخنزير
jelatin, gelatin, желатин => الجيلاتين / الأطعمة المشتبهة
deniz mehsullari, deniz urunleri, seafood, морепродукты, balik, fish, рыба, karides, shrimp, креветки, midye, crab, lobster => صيد البحر / ميتة البحر
at eti, horse meat, конина, eshek eti, donkey meat, мясо осла => لحم الخيل / لحوم الحمر الأهلية
pisik eti, kedi eti, cat meat, мясо кошки => لحم الهر
kopek eti, dog meat, собачье мясо => أكل الكلب
cekirge, locust, locusts, саранча => الجراد
kofe, coffee, кофе, qehve, kahve => القهوة
sigara icmek, enerji icecegi, energy drink, энергетик => ما يضر بالبدن / التدخين
nebiz, nabidh, fermented juice, mayalanmis icecek, kymyz, kumis, кумыс => النبيذ / الأشربة
bira, beer, пиво, alkolsuz bira, non alcoholic beer, безалкогольное пиво => البيرة / الخمر والمسكر
alkollu parfum, alcohol perfume, kolonya, cologne, одеколон, spirt parfum => الكحول في الطيب / العطور
alkollu ilac, alcohol in medicine, ilacda alkol, спирт в лекарствах => التداوي بالمحرم / الكحول في الدواء
tedavi haram, treating with haram, лечение запрещённым, haram ilac => التداوي بالمحرمات
yemek adabi, eating etiquette, adab of eating, этикет еды => آداب الطعام
sag el ile yemek, eating with right hand, есть правой рукой, eating with left hand => الأكل باليمين
ayakta yemek, ayakta su icmek, drinking standing, eating standing, пить стоя => الشرب قائما
altin gumus kap, gold and silver vessels, золотая и серебряная посуда, eating from gold plates => الأكل في آنية الذهب والفضة
kafirlerin kaplari, vessels of non muslims, посуда неверных => آنية أهل الكتاب
ipek, silk, шёлк, ipek giymek, wearing silk, men wearing silk => لبس الحرير للرجال
altin yuzuk, gold ring, золотое кольцо, erkek altin, men wearing gold => لبس الذهب للرجال / خاتم الذهب
gumus yuzuk, silver ring, серебряное кольцо, erkek yuzuk => خاتم الفضة
altin dis, gold tooth, золотой зуб => ربط الأسنان بالذهب
isbal, ishbal, topuktan asagi, pants below ankles, штаны ниже щиколоток, izar => الإسبال
sakal, saqqal, beard, борода, sakal birakmak, sakal kesmek, beard shaving, shaving the beard, бритьё бороды, saqqal qirxmaq => اللحية / إعفاء اللحية / حلق اللحية
biyik, mustache, moustache, усы, biyik kesmek => قص الشارب
tato, tattoo, tattoos, татуировка, tatuaj, vashm => الوشم
saç uzatma, hair extension, hair extensions, нарощенные волосы, wasl => وصل الشعر
kas almak, qas almaq, plucking eyebrows, eyebrow plucking, выщипывание бровей, namisa => النمص
estetik ameliyat, plastic surgery, plastik cerrahi, пластическая операция, botox, ботокс, rhinoplasty, burun ameliyati => عمليات التجميل / تغيير خلق الله
fotograf, foto, photograph, photography, фотография, фото, photos => التصوير / الصور
resim cekmek, suret, tasvir, taswir, drawing living things, рисовать животных, picture, pictures, image, images => التصوير / الصور
heykel, statue, statues, статуя, статуи, sculpture, idol, putlar, idols, идолы => التماثيل / الأصنام
oyuncak bebek, doll, dolls, куклы, кукла, toy, toys, oyuncaq => اللعب بالبنات / لعب الصور
televizyon, televizor, television, телевизор, телевидение, tv, televiziya => التلفزيون / التصوير
sinema, kino, cinema, кино, film, films, фильм, movies, dizi, serial, сериал, teatr, theatre, театр, temsil, acting, aktyor => التمثيل / السينما / التصوير
musiqi, muzik, music, музыка, mahni, sarki, song, songs, песни, песня => الغناء / المعازف
nasheed, nasheeds, nashid, nashid hokmu, нашид, нашиды, ilahi, ilahiler => الأناشيد
def, daf, duf, дуфф, tambourine, davul, drum, drums, барабан => الدف
calgi aletleri, musical instruments, музыкальные инструменты, maazif, ma'azif, gitar, guitar, гитара, piano, пианино, keman, violin, скрипка, ud, oud, ney => المعازف / آلات اللهو
singer, singers, ganan, mugenni, певец, певцы, singing, пение => الغناء / المغنون
dans, raks, rəqs, dance, dancing, танец, танцы => الرقص
sema, sama, dervish dance, whirling dervishes, mevlevi, танцующие дервиши, hadra, хадра, zikir dansi, hal, wajd, vecd, tawajud => السماع / الرقص والوجد
satranc, chess, шахматы, nard, tavla, backgammon, нарды, ludo, kart, cards, playing cards, игральные карты, pul oyunlari, kumar, gambling, qumar, азартные игры, kazino, casino, казино, lotereya, lottery, лотерея, loto, piyango, mısır loto, bahis, betting, ставки => الشطرنج / النرد / الميسر / القمار
oyun, video oyun, video games, видеоигры, game, games, игры, computer games, kompyuter oyunlari, pubg, play station => اللعب / اللهو المباح
idman, futbol, football, футбол, sport, sports, спорт, boks, boxing, бокс, gures, wrestling, борьба, kickboks, mma, yarisma, competition, соревнования, musabaqa, sabaq, race, yaris, atlı yaris, horse racing, скачки, okculuk, archery, стрельба из лука, yuzme, swimming, плавание => المسابقات / الرياضة / السبق والرمي
# ===== SİHR, CİN, GÖZ DƏYMƏSİ, FAL
sihir, sehir, sihr, magic, witchcraft, sorcery, колдовство, магия, сихр, cadu, cadugar, sorcerer, колдун => السحر / الساحر
sihri bozmak, nushra, nushrah, undoing magic, removing magic, разрушить колдовство, sihir bozma, sihir cozme => النشرة / حل السحر
kahin, kehanet, kahanah, fortune teller, fortune telling, fal, falci, falcı, fala baxmaq, falabakmak, гадание, гадалка, гадать, kahve fali, coffee reading, tarot, tarotu, horoscope, burc, burclar, гороскоп, astrology, astroloji, nucum, najm, звездочет, yildizname => الكهانة / العرافة / التنجيم
tetayyur, tatayyur, uğursuzluk, ugursuzluk, bad omen, bad omens, дурная примета, ugursuz, omen, shum, sum, tiyara, tiyara, fal acmak, fal tutmak => الطيرة / التشاؤم
goz deymesi, nazar, nazar degmesi, nazar boncugu, evil eye, злой глаз, ayn, al ayn, goz dəymə, nazar muskasi, amulet, amulets, tilsim, talisman, талисман, tamima, tama'im, tamaim, tamimah, tilism, muska, muska takmak, taweez, taveez, ta'wiz, ta'viz, tawiz, amulet hokmu, hirz, hirz, wearing amulets, wearing talisman, носить амулет, носить талисман => العين / التمائم / تعليق التمائم
ruqya, rukye, rukya, ruqyah, ruqiya, рукъя, рукия, quran ile tedavi, healing with quran, treating with quran, лечение кораном, ruqya shariyya, quran ile okumak, okuyup ufurmek, nafth, nefs, blowing in ruqya => الرقية / الرقى
cin, jinn, jin, jinns, джинны, джинн, cinler, jinlerle iliski, cin carpmasi, jinn possession, possession, одержимость, cin tutmasi, cin cikarmak, exorcism, экзорцизм, jinleri cikarmak, drive out jinn, ifrit, marid, shaytan, seytan, devil, devils, satan, шайтан, иблис, iblis, iblis, vesvese, waswasa, whispers of satan, наущения шайтана, вас-вас => الجن / الشياطين / الوسوسة / صرع الجن
melek, melekler, angel, angels, ангелы, ангел, malak, mala'ika, malaikah, melaike, cebrail, jibril, джибриль, mikail, mikail, israfil, israfil, azrail, malak al mawt, ölüm meleği, harut marut, harut ve marut, харут и марут, kiramen katibin, kiraman katibin => الملائكة
ruya, ruyalar, yuxu, dream, dreams, сон, сны, dream interpretation, ruya tabiri, ruya yorumu, yuxu yozumu, толкование снов, ruya gormek, seeing the prophet in a dream, seeing prophet in dream, peygamberi ruyada gormek, nebini yuxuda gormek, видеть пророка во сне, ruyada peygamber, seeing allah in dream, dream of allah, ruyada allahi gormek, ruya hokmu, ru'ya, ru'ya salihe => الرؤيا / رؤية النبي في المنام / تعبير الرؤيا
# ===== TƏSƏVVÜF
tesavvuf, tasavvuf, tasawwuf, sufism, sufi, sufis, суфизм, суфий, суфии, тасаввуф, sufiler, sufilik, taref, tariqa, tarikat, tarikatlar, tarekat, tariqah, tariqat, тарикат, мурид, murid, murids, мюрид, seyh, sheikh murid, pir, piri, pirlik, shaykh, tariqa shaykh, mursit, murshid, murshid, мурshид, murshid kamil, shaykh al tariqa => التصوف / الصوفية / الطرق الصوفية
tarikat bagi, bai'at, bay'ah, bay'at, baiat, biat, biat etmek, bay'ah to shaykh, giving bay'ah to a sheikh, клятва шейху, ahd with sheikh, ahd murid, мюрид ахд, sheikhs bay'ah, murshid bay'ah, tariqa bay'ah => بيعة الشيخ / البيعة الصوفية
nakşibendi, naksibendi, naqshbandi, naqshbandiyya, накшбанди, nakshbandi, qadiri, kadiri, qadiriyya, kadiriyye, кадири, shazili, sazili, shadhili, shadhiliyya, шазили, rifai, rifa'i, rifaiyye, рифаи, mevlevi, mevleviyye, мавляви, bektasi, bektashi, bektaşi, бекташи, tijani, tijaniyya, тиджани, chishti, chishtiyya, чишти, suhrawardi, suhrawardiyya, сухраварди, ahmadiyya, ahmadi, ахмадия => الطريقة النقشبندية / الطريقة القادرية / الطريقة الشاذلية / الطرق الصوفية
veli, evliya, awliya, velilik, wali allah, wilayah, vilayet, velayet, friends of allah, awliya allah, святые, святой, святость, святых, вали, авлия, ewliya, ulyi, ewliyanin keramati, keramet, kerametler, karamat, karamah, karama, карамат, чудеса святых, чудо святых, miracles of saints, saint miracles, marvels of the saints, karamat al awliya => الأولياء / كرامات الأولياء / ولاية الله
kutb, qutb, kutub, qutub, gavs, ghawth, gawth, gaus, gavs, qutb al ghawth, abdal, abdal, awtad, evtad, nuqaba, nukaba, nujaba, najaba, budala, budalâ, hierarchy of saints, saints hierarchy, иерархия святых, кутб, гаус => القطب / الغوث / الأبدال / الأوتاد
fena fillah, baqa, beka, baqa billah, baka billah, fana and baqa, фана и бака, ihsan, ihsan maqami, ihsan nedir, what is ihsan, ихсан, ihsan nedir => الفناء والبقاء / الإحسان
zuhd, zuhud, zohd, zahid, asceticism, ascetic, аскетизм, аскеза, zahidlik, dunyadan el cekmek, abandoning the world, dunya sevgisi, love of the world, любовь к миру, dünyaya bağlılık, dunya muhabbeti, dünya sevgisi, hubb al dunya => الزهد / حب الدنيا
tevekkul, tovakkul, tavakkul, tawakkul, reliance on allah, trust in allah, упование на аллаха, тауаккуль, тавакуль => التوكل
sabir, sabr, patience, терпение, сабр, sabirli, patient, sabr etmek => الصبر
sukr, shukr, sukur, thankfulness, gratitude, благодарность, шукр, shukr allah, sukretmek, şükür, serendipity => الشكر
mehebbet, muhabbet, mahabba, mahabbah, love of allah, loving allah, любовь к аллаху, allahi sevmek, hubb allah, ishq, ashk, ask, aşk, isq, иштиак, shawq, shevk, sevk, ashiq, asik, aşık, ashiq allah, divine love, ilahi ask, ilahi mehebbet => محبة الله / العشق / الشوق
xof, havf, khawf, fear of allah, страх перед аллахом, hayiflanmaq, haya, hayā, heya, modesty, стыдливость, haya iman, haya imandandir, rica, raja, hope, надежда, umid, ümid, hope in allah, umid allah, allahdan umid, ruh al raja, ruh al khawf, balance between hope and fear, xof ve rica, korku ve umut, hope and fear => الخوف والرجاء / الحياء
huzu, khushu, khushu', hushu, hushu', khushu in prayer, humility in prayer, смирение в намазе, хушу, hudu, huzur, huzur namazda, concentration in prayer, focus in prayer, namazda dikkat, namazda konsantrasyon, namazda xushu => الخشوع في الصلاة
ixlas, ihlas, ikhlas, sincerity, искренность, ихлас, sincere intention, niyyet, nijyat, niyyah, niyyat, niyet, intention, намерение, ният, niyyetin hokmu, ruling of intention, niyyetin yeri, place of intention, uttering the intention, niyyeti dil ile soylemek, saying the intention aloud, pronouncing the intention, talaffuz bin niyyah, talaffuz niyyet, niyyeti dil ile, arapca niyyet, niyyet nuqtayi nezer => الإخلاص / النية / التلفظ بالنية
muhasebe, muhasaba, self accounting, self examination, самоанализ, нафс муhasaba, nefsi muhasebe, muhasebe, nefis, nafs, ego, soul inclination, nefsin terbiyesi, nafs tazkiyah, tazkiye, tazkiyat an nafs, tazkiyah, tazkiya, purification of the soul, очищение души, nafsı tezkiye, nefis terbiyesi, nefsin heva, hawa, hevâ, havas, havâ, hevanin ardinca, following desires, desires, passion, страсть, следование желаниям, hevaya uymak, heva ve heves => محاسبة النفس / تزكية النفس / اتباع الهوى
kibir, kibr, kibir, takabbur, takabur, pride, arrogance, гордыня, высокомерие, kibir nedir, kibrin hokmu, ujub, ucb, ujb, conceit, self admiration, самолюбование, ucub, bogh, bughz, hasad, haset, envy, зависть, jealousy, ревность, qibta, gipta, ghibta => الكبر / العجب / الحسد / الغبطة
qeybet, gıybet, giybet, ghiba, ghiybah, backbiting, сплетни, сплетня, ghayba, ghibah, nemime, namimah, tale bearing, tale telling, tale carrying, tattling, наушничество, söz gezdirme, soz gezdirmek, soz tasimak, bohtan, buhtan, buhtan, calumny, slander, клевета, iftira, iftira atmak, yalan, lie, lying, ложь, kizb, kidhb, kazib, yalanci, liar, лжец, yalan soylemek, lying, yalanin hokmu, ruling of lying, joke lying, sakada yalan, lying in jest, sakaya yalan, lying to children, lying between spouses, lying for reconciliation => الغيبة / النميمة / البهتان / الكذب
`;
