// Oyun HTML fayllarını (content/games/<slug>.html) Vercel-in izləyə bildiyi JS modullarına çevirir: api/_games/<slug>.js
//   export default "<HTML mətni>";   (JSON.stringify ilə, itkisiz — oyun kodu bayt-bayt eyni qalır)
// İstifadə:  node scripts/build-games.mjs [mənbə-qovluq] [çıxış-qovluq]
// Hər .html üçün .js yazılır, artıq .html-i olmayan köhnə .js silinir (yalnız bu skriptin yazdıqları: «// generated by build-games»).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const HEADER = "// generated by build-games: content/games/<slug>.html -> bu fayl. Əl ilə dəyişmə; node scripts/build-games.mjs işlət.\n";

export function toModule(html) {
  // U+2028/2029 JSON-da düz qala bilər (ES2019+), amma mənbə oxunaqlı qalsın deyə escape edirik; dəyər dəyişmir.
  return HEADER + "export default " + JSON.stringify(html).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029") + ";\n";
}

export function buildGames(srcDir = path.join(ROOT, "content/games"), outDir = path.join(ROOT, "api/_games")) {
  fs.mkdirSync(outDir, { recursive: true });
  const written = [];
  for (const f of fs.readdirSync(srcDir).filter((x) => x.endsWith(".html")).sort()) {
    const slug = f.slice(0, -5);
    if (!/^[a-z0-9][a-z0-9-]*$/.test(slug)) throw new Error("slug yalnız a-z, 0-9 və - ola bilər: " + f);
    const bytes = fs.readFileSync(path.join(srcDir, f));
    const html = bytes.toString("utf8");
    if (!Buffer.from(html, "utf8").equals(bytes)) throw new Error("UTF-8 olmayan baytlar var (itkisiz çevirmək olmur): " + f);
    fs.writeFileSync(path.join(outDir, slug + ".js"), toModule(html));
    written.push(slug);
  }
  for (const f of fs.readdirSync(outDir).filter((x) => x.endsWith(".js") && x !== "index.js")) {
    const slug = f.slice(0, -3);
    if (written.includes(slug)) continue;
    if (fs.readFileSync(path.join(outDir, f), "utf8").startsWith(HEADER)) fs.unlinkSync(path.join(outDir, f));
  }
  return written;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [src, out] = process.argv.slice(2);
  const done = buildGames(src ? path.resolve(src) : undefined, out ? path.resolve(out) : undefined);
  console.log(`${done.length} oyun: ${done.join(", ") || "(yoxdur)"}`);
}
