/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NxStudioRouteImport } from './routes/nx-studio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as UnutmaRouteImport } from './routes/unutma'
import { Route as WhyRouteImport } from './routes/why'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsSlugRouteImport } from './routes/apps/$slug'
import { Route as ArAboutRouteImport } from './routes/ar.about'
import { Route as ArAppsRouteImport } from './routes/ar.apps'
import { Route as ArContactRouteImport } from './routes/ar.contact'
import { Route as ArFaqRouteImport } from './routes/ar.faq'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnAppsRouteImport } from './routes/en.apps'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnFaqRouteImport } from './routes/en.faq'
import { Route as FaqSlugRouteImport } from './routes/faq.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesTopicRouteImport } from './routes/guides/$topic'
import { Route as PrivacySlugRouteImport } from './routes/privacy/$slug'
import { Route as PrivacyNibrasPdfRouteImport } from './routes/privacy.nibras-pdf'
import { Route as ProgrammingIndexRouteImport } from './routes/programming/index'
import { Route as ProgrammingTopicRouteImport } from './routes/programming/$topic'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesTopicRouteRouteImport } from './routes/resources/$topic/route'
import { Route as ResurslarSlugRouteImport } from './routes/resurslar/$slug'
import { Route as RuAboutRouteImport } from './routes/ru.about'
import { Route as RuAppsRouteImport } from './routes/ru.apps'
import { Route as RuContactRouteImport } from './routes/ru.contact'
import { Route as RuFaqRouteImport } from './routes/ru.faq'
import { Route as TrAboutRouteImport } from './routes/tr.about'
import { Route as TrAppsRouteImport } from './routes/tr.apps'
import { Route as TrContactRouteImport } from './routes/tr.contact'
import { Route as TrFaqRouteImport } from './routes/tr.faq'
import { Route as ArAppsSlugRouteImport } from './routes/ar.apps.$slug'
import { Route as ArFaqSlugRouteImport } from './routes/ar.faq.$slug'
import { Route as ArProgrammingSlugRouteImport } from './routes/ar.programming.$slug'
import { Route as EnAppsSlugRouteImport } from './routes/en.apps.$slug'
import { Route as EnFaqSlugRouteImport } from './routes/en.faq.$slug'
import { Route as EnProgrammingSlugRouteImport } from './routes/en.programming.$slug'
import { Route as ResourcesTopicIndexRouteImport } from './routes/resources/$topic/index'
import { Route as ResourcesTopicArticleRouteImport } from './routes/resources/$topic/$article'
import { Route as RuAppsSlugRouteImport } from './routes/ru.apps.$slug'
import { Route as RuFaqSlugRouteImport } from './routes/ru.faq.$slug'
import { Route as RuProgrammingSlugRouteImport } from './routes/ru.programming.$slug'
import { Route as RuResourcesSlugRouteImport } from './routes/ru.resources.$slug'
import { Route as TrAppsSlugRouteImport } from './routes/tr.apps.$slug'
import { Route as TrFaqSlugRouteImport } from './routes/tr.faq.$slug'
import { Route as TrProgrammingSlugRouteImport } from './routes/tr.programming.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NxStudioRoute = NxStudioRouteImport.update({
  id: '/nx-studio',
  path: '/nx-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const UnutmaRoute = UnutmaRouteImport.update({
  id: '/unutma',
  path: '/unutma',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAboutRoute = ArAboutRouteImport.update({
  id: '/ar/about',
  path: '/ar/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAppsRoute = ArAppsRouteImport.update({
  id: '/ar/apps',
  path: '/ar/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ArContactRoute = ArContactRouteImport.update({
  id: '/ar/contact',
  path: '/ar/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArFaqRoute = ArFaqRouteImport.update({
  id: '/ar/faq',
  path: '/ar/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAppsRoute = EnAppsRouteImport.update({
  id: '/en/apps',
  path: '/en/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/en/faq',
  path: '/en/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FaqRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTopicRoute = GuidesTopicRouteImport.update({
  id: '/guides/$topic',
  path: '/guides/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacySlugRoute = PrivacySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrivacyRoute,
} as any)
const PrivacyNibrasPdfRoute = PrivacyNibrasPdfRouteImport.update({
  id: '/nibras-pdf',
  path: '/nibras-pdf',
  getParentRoute: () => PrivacyRoute,
} as any)
const ProgrammingIndexRoute = ProgrammingIndexRouteImport.update({
  id: '/programming/',
  path: '/programming/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammingTopicRoute = ProgrammingTopicRouteImport.update({
  id: '/programming/$topic',
  path: '/programming/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTopicRouteRoute = ResourcesTopicRouteRouteImport.update({
  id: '/resources/$topic',
  path: '/resources/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurslarSlugRoute = ResurslarSlugRouteImport.update({
  id: '/resurslar/$slug',
  path: '/resurslar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAboutRoute = RuAboutRouteImport.update({
  id: '/ru/about',
  path: '/ru/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAppsRoute = RuAppsRouteImport.update({
  id: '/ru/apps',
  path: '/ru/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const RuContactRoute = RuContactRouteImport.update({
  id: '/ru/contact',
  path: '/ru/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RuFaqRoute = RuFaqRouteImport.update({
  id: '/ru/faq',
  path: '/ru/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const TrAboutRoute = TrAboutRouteImport.update({
  id: '/tr/about',
  path: '/tr/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TrAppsRoute = TrAppsRouteImport.update({
  id: '/tr/apps',
  path: '/tr/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const TrContactRoute = TrContactRouteImport.update({
  id: '/tr/contact',
  path: '/tr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TrFaqRoute = TrFaqRouteImport.update({
  id: '/tr/faq',
  path: '/tr/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAppsSlugRoute = ArAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArAppsRoute,
} as any)
const ArFaqSlugRoute = ArFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArFaqRoute,
} as any)
const ArProgrammingSlugRoute = ArProgrammingSlugRouteImport.update({
  id: '/ar/programming/$slug',
  path: '/ar/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAppsSlugRoute = EnAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnAppsRoute,
} as any)
const EnFaqSlugRoute = EnFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnFaqRoute,
} as any)
const EnProgrammingSlugRoute = EnProgrammingSlugRouteImport.update({
  id: '/en/programming/$slug',
  path: '/en/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTopicIndexRoute = ResourcesTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesTopicRouteRoute,
} as any)
const ResourcesTopicArticleRoute = ResourcesTopicArticleRouteImport.update({
  id: '/$article',
  path: '/$article',
  getParentRoute: () => ResourcesTopicRouteRoute,
} as any)
const RuAppsSlugRoute = RuAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuAppsRoute,
} as any)
const RuFaqSlugRoute = RuFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuFaqRoute,
} as any)
const RuProgrammingSlugRoute = RuProgrammingSlugRouteImport.update({
  id: '/ru/programming/$slug',
  path: '/ru/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuResourcesSlugRoute = RuResourcesSlugRouteImport.update({
  id: '/ru/resources/$slug',
  path: '/ru/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrAppsSlugRoute = TrAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrAppsRoute,
} as any)
const TrFaqSlugRoute = TrFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrFaqRoute,
} as any)
const TrProgrammingSlugRoute = TrProgrammingSlugRouteImport.update({
  id: '/tr/programming/$slug',
  path: '/tr/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/nx-studio': typeof NxStudioRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/unutma': typeof UnutmaRoute
  '/why': typeof WhyRoute
  '/resources/$topic': typeof ResourcesTopicRouteRouteWithChildren
  '/apps/$slug': typeof AppsSlugRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/apps': typeof ArAppsRouteWithChildren
  '/ar/contact': typeof ArContactRoute
  '/ar/faq': typeof ArFaqRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apps': typeof EnAppsRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRouteWithChildren
  '/faq/$slug': typeof FaqSlugRoute
  '/guides/$topic': typeof GuidesTopicRoute
  '/privacy/$slug': typeof PrivacySlugRoute
  '/privacy/nibras-pdf': typeof PrivacyNibrasPdfRoute
  '/programming/$topic': typeof ProgrammingTopicRoute
  '/resurslar/$slug': typeof ResurslarSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/apps': typeof RuAppsRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/faq': typeof RuFaqRouteWithChildren
  '/tr/about': typeof TrAboutRoute
  '/tr/apps': typeof TrAppsRouteWithChildren
  '/tr/contact': typeof TrContactRoute
  '/tr/faq': typeof TrFaqRouteWithChildren
  '/apps/': typeof AppsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/programming/': typeof ProgrammingIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/ar/apps/$slug': typeof ArAppsSlugRoute
  '/ar/faq/$slug': typeof ArFaqSlugRoute
  '/ar/programming/$slug': typeof ArProgrammingSlugRoute
  '/en/apps/$slug': typeof EnAppsSlugRoute
  '/en/faq/$slug': typeof EnFaqSlugRoute
  '/en/programming/$slug': typeof EnProgrammingSlugRoute
  '/resources/$topic/$article': typeof ResourcesTopicArticleRoute
  '/ru/apps/$slug': typeof RuAppsSlugRoute
  '/ru/faq/$slug': typeof RuFaqSlugRoute
  '/ru/programming/$slug': typeof RuProgrammingSlugRoute
  '/ru/resources/$slug': typeof RuResourcesSlugRoute
  '/tr/apps/$slug': typeof TrAppsSlugRoute
  '/tr/faq/$slug': typeof TrFaqSlugRoute
  '/tr/programming/$slug': typeof TrProgrammingSlugRoute
  '/resources/$topic/': typeof ResourcesTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/nx-studio': typeof NxStudioRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/unutma': typeof UnutmaRoute
  '/why': typeof WhyRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/apps': typeof ArAppsRouteWithChildren
  '/ar/contact': typeof ArContactRoute
  '/ar/faq': typeof ArFaqRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apps': typeof EnAppsRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRouteWithChildren
  '/faq/$slug': typeof FaqSlugRoute
  '/guides/$topic': typeof GuidesTopicRoute
  '/privacy/$slug': typeof PrivacySlugRoute
  '/privacy/nibras-pdf': typeof PrivacyNibrasPdfRoute
  '/programming/$topic': typeof ProgrammingTopicRoute
  '/resurslar/$slug': typeof ResurslarSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/apps': typeof RuAppsRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/faq': typeof RuFaqRouteWithChildren
  '/tr/about': typeof TrAboutRoute
  '/tr/apps': typeof TrAppsRouteWithChildren
  '/tr/contact': typeof TrContactRoute
  '/tr/faq': typeof TrFaqRouteWithChildren
  '/apps': typeof AppsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/programming': typeof ProgrammingIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/ar/apps/$slug': typeof ArAppsSlugRoute
  '/ar/faq/$slug': typeof ArFaqSlugRoute
  '/ar/programming/$slug': typeof ArProgrammingSlugRoute
  '/en/apps/$slug': typeof EnAppsSlugRoute
  '/en/faq/$slug': typeof EnFaqSlugRoute
  '/en/programming/$slug': typeof EnProgrammingSlugRoute
  '/resources/$topic/$article': typeof ResourcesTopicArticleRoute
  '/ru/apps/$slug': typeof RuAppsSlugRoute
  '/ru/faq/$slug': typeof RuFaqSlugRoute
  '/ru/programming/$slug': typeof RuProgrammingSlugRoute
  '/ru/resources/$slug': typeof RuResourcesSlugRoute
  '/tr/apps/$slug': typeof TrAppsSlugRoute
  '/tr/faq/$slug': typeof TrFaqSlugRoute
  '/tr/programming/$slug': typeof TrProgrammingSlugRoute
  '/resources/$topic': typeof ResourcesTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/nx-studio': typeof NxStudioRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/unutma': typeof UnutmaRoute
  '/why': typeof WhyRoute
  '/resources/$topic': typeof ResourcesTopicRouteRouteWithChildren
  '/apps/$slug': typeof AppsSlugRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/apps': typeof ArAppsRouteWithChildren
  '/ar/contact': typeof ArContactRoute
  '/ar/faq': typeof ArFaqRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apps': typeof EnAppsRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRouteWithChildren
  '/faq/$slug': typeof FaqSlugRoute
  '/guides/$topic': typeof GuidesTopicRoute
  '/privacy/$slug': typeof PrivacySlugRoute
  '/privacy/nibras-pdf': typeof PrivacyNibrasPdfRoute
  '/programming/$topic': typeof ProgrammingTopicRoute
  '/resurslar/$slug': typeof ResurslarSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/apps': typeof RuAppsRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/faq': typeof RuFaqRouteWithChildren
  '/tr/about': typeof TrAboutRoute
  '/tr/apps': typeof TrAppsRouteWithChildren
  '/tr/contact': typeof TrContactRoute
  '/tr/faq': typeof TrFaqRouteWithChildren
  '/apps/': typeof AppsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/programming/': typeof ProgrammingIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/ar/apps/$slug': typeof ArAppsSlugRoute
  '/ar/faq/$slug': typeof ArFaqSlugRoute
  '/ar/programming/$slug': typeof ArProgrammingSlugRoute
  '/en/apps/$slug': typeof EnAppsSlugRoute
  '/en/faq/$slug': typeof EnFaqSlugRoute
  '/en/programming/$slug': typeof EnProgrammingSlugRoute
  '/resources/$topic/$article': typeof ResourcesTopicArticleRoute
  '/ru/apps/$slug': typeof RuAppsSlugRoute
  '/ru/faq/$slug': typeof RuFaqSlugRoute
  '/ru/programming/$slug': typeof RuProgrammingSlugRoute
  '/ru/resources/$slug': typeof RuResourcesSlugRoute
  '/tr/apps/$slug': typeof TrAppsSlugRoute
  '/tr/faq/$slug': typeof TrFaqSlugRoute
  '/tr/programming/$slug': typeof TrProgrammingSlugRoute
  '/resources/$topic/': typeof ResourcesTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/nx-studio'
    | '/privacy'
    | '/unutma'
    | '/why'
    | '/resources/$topic'
    | '/apps/$slug'
    | '/ar/about'
    | '/ar/apps'
    | '/ar/contact'
    | '/ar/faq'
    | '/en/about'
    | '/en/apps'
    | '/en/contact'
    | '/en/faq'
    | '/faq/$slug'
    | '/guides/$topic'
    | '/privacy/$slug'
    | '/privacy/nibras-pdf'
    | '/programming/$topic'
    | '/resurslar/$slug'
    | '/ru/about'
    | '/ru/apps'
    | '/ru/contact'
    | '/ru/faq'
    | '/tr/about'
    | '/tr/apps'
    | '/tr/contact'
    | '/tr/faq'
    | '/apps/'
    | '/guides/'
    | '/programming/'
    | '/resources/'
    | '/ar/apps/$slug'
    | '/ar/faq/$slug'
    | '/ar/programming/$slug'
    | '/en/apps/$slug'
    | '/en/faq/$slug'
    | '/en/programming/$slug'
    | '/resources/$topic/$article'
    | '/ru/apps/$slug'
    | '/ru/faq/$slug'
    | '/ru/programming/$slug'
    | '/ru/resources/$slug'
    | '/tr/apps/$slug'
    | '/tr/faq/$slug'
    | '/tr/programming/$slug'
    | '/resources/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/nx-studio'
    | '/privacy'
    | '/unutma'
    | '/why'
    | '/apps/$slug'
    | '/ar/about'
    | '/ar/apps'
    | '/ar/contact'
    | '/ar/faq'
    | '/en/about'
    | '/en/apps'
    | '/en/contact'
    | '/en/faq'
    | '/faq/$slug'
    | '/guides/$topic'
    | '/privacy/$slug'
    | '/privacy/nibras-pdf'
    | '/programming/$topic'
    | '/resurslar/$slug'
    | '/ru/about'
    | '/ru/apps'
    | '/ru/contact'
    | '/ru/faq'
    | '/tr/about'
    | '/tr/apps'
    | '/tr/contact'
    | '/tr/faq'
    | '/apps'
    | '/guides'
    | '/programming'
    | '/resources'
    | '/ar/apps/$slug'
    | '/ar/faq/$slug'
    | '/ar/programming/$slug'
    | '/en/apps/$slug'
    | '/en/faq/$slug'
    | '/en/programming/$slug'
    | '/resources/$topic/$article'
    | '/ru/apps/$slug'
    | '/ru/faq/$slug'
    | '/ru/programming/$slug'
    | '/ru/resources/$slug'
    | '/tr/apps/$slug'
    | '/tr/faq/$slug'
    | '/tr/programming/$slug'
    | '/resources/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/nx-studio'
    | '/privacy'
    | '/unutma'
    | '/why'
    | '/resources/$topic'
    | '/apps/$slug'
    | '/ar/about'
    | '/ar/apps'
    | '/ar/contact'
    | '/ar/faq'
    | '/en/about'
    | '/en/apps'
    | '/en/contact'
    | '/en/faq'
    | '/faq/$slug'
    | '/guides/$topic'
    | '/privacy/$slug'
    | '/privacy/nibras-pdf'
    | '/programming/$topic'
    | '/resurslar/$slug'
    | '/ru/about'
    | '/ru/apps'
    | '/ru/contact'
    | '/ru/faq'
    | '/tr/about'
    | '/tr/apps'
    | '/tr/contact'
    | '/tr/faq'
    | '/apps/'
    | '/guides/'
    | '/programming/'
    | '/resources/'
    | '/ar/apps/$slug'
    | '/ar/faq/$slug'
    | '/ar/programming/$slug'
    | '/en/apps/$slug'
    | '/en/faq/$slug'
    | '/en/programming/$slug'
    | '/resources/$topic/$article'
    | '/ru/apps/$slug'
    | '/ru/faq/$slug'
    | '/ru/programming/$slug'
    | '/ru/resources/$slug'
    | '/tr/apps/$slug'
    | '/tr/faq/$slug'
    | '/tr/programming/$slug'
    | '/resources/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRouteWithChildren
  NxStudioRoute: typeof NxStudioRoute
  PrivacyRoute: typeof PrivacyRouteWithChildren
  UnutmaRoute: typeof UnutmaRoute
  WhyRoute: typeof WhyRoute
  ResourcesTopicRouteRoute: typeof ResourcesTopicRouteRouteWithChildren
  AppsSlugRoute: typeof AppsSlugRoute
  ArAboutRoute: typeof ArAboutRoute
  ArAppsRoute: typeof ArAppsRouteWithChildren
  ArContactRoute: typeof ArContactRoute
  ArFaqRoute: typeof ArFaqRouteWithChildren
  EnAboutRoute: typeof EnAboutRoute
  EnAppsRoute: typeof EnAppsRouteWithChildren
  EnContactRoute: typeof EnContactRoute
  EnFaqRoute: typeof EnFaqRouteWithChildren
  GuidesTopicRoute: typeof GuidesTopicRoute
  ProgrammingTopicRoute: typeof ProgrammingTopicRoute
  ResurslarSlugRoute: typeof ResurslarSlugRoute
  RuAboutRoute: typeof RuAboutRoute
  RuAppsRoute: typeof RuAppsRouteWithChildren
  RuContactRoute: typeof RuContactRoute
  RuFaqRoute: typeof RuFaqRouteWithChildren
  TrAboutRoute: typeof TrAboutRoute
  TrAppsRoute: typeof TrAppsRouteWithChildren
  TrContactRoute: typeof TrContactRoute
  TrFaqRoute: typeof TrFaqRouteWithChildren
  AppsIndexRoute: typeof AppsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ProgrammingIndexRoute: typeof ProgrammingIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ArProgrammingSlugRoute: typeof ArProgrammingSlugRoute
  EnProgrammingSlugRoute: typeof EnProgrammingSlugRoute
  RuProgrammingSlugRoute: typeof RuProgrammingSlugRoute
  RuResourcesSlugRoute: typeof RuResourcesSlugRoute
  TrProgrammingSlugRoute: typeof TrProgrammingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nx-studio': {
      id: '/nx-studio'
      path: '/nx-studio'
      fullPath: '/nx-studio'
      preLoaderRoute: typeof NxStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unutma': {
      id: '/unutma'
      path: '/unutma'
      fullPath: '/unutma'
      preLoaderRoute: typeof UnutmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/about': {
      id: '/ar/about'
      path: '/ar/about'
      fullPath: '/ar/about'
      preLoaderRoute: typeof ArAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/apps': {
      id: '/ar/apps'
      path: '/ar/apps'
      fullPath: '/ar/apps'
      preLoaderRoute: typeof ArAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/contact': {
      id: '/ar/contact'
      path: '/ar/contact'
      fullPath: '/ar/contact'
      preLoaderRoute: typeof ArContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/faq': {
      id: '/ar/faq'
      path: '/ar/faq'
      fullPath: '/ar/faq'
      preLoaderRoute: typeof ArFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/apps': {
      id: '/en/apps'
      path: '/en/apps'
      fullPath: '/en/apps'
      preLoaderRoute: typeof EnAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/en/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof FaqRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$topic': {
      id: '/guides/$topic'
      path: '/guides/$topic'
      fullPath: '/guides/$topic'
      preLoaderRoute: typeof GuidesTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/$slug': {
      id: '/privacy/$slug'
      path: '/$slug'
      fullPath: '/privacy/$slug'
      preLoaderRoute: typeof PrivacySlugRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/privacy/nibras-pdf': {
      id: '/privacy/nibras-pdf'
      path: '/nibras-pdf'
      fullPath: '/privacy/nibras-pdf'
      preLoaderRoute: typeof PrivacyNibrasPdfRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/programming/': {
      id: '/programming/'
      path: '/programming'
      fullPath: '/programming/'
      preLoaderRoute: typeof ProgrammingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programming/$topic': {
      id: '/programming/$topic'
      path: '/programming/$topic'
      fullPath: '/programming/$topic'
      preLoaderRoute: typeof ProgrammingTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$topic': {
      id: '/resources/$topic'
      path: '/resources/$topic'
      fullPath: '/resources/$topic'
      preLoaderRoute: typeof ResourcesTopicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurslar/$slug': {
      id: '/resurslar/$slug'
      path: '/resurslar/$slug'
      fullPath: '/resurslar/$slug'
      preLoaderRoute: typeof ResurslarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/about': {
      id: '/ru/about'
      path: '/ru/about'
      fullPath: '/ru/about'
      preLoaderRoute: typeof RuAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/apps': {
      id: '/ru/apps'
      path: '/ru/apps'
      fullPath: '/ru/apps'
      preLoaderRoute: typeof RuAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/contact': {
      id: '/ru/contact'
      path: '/ru/contact'
      fullPath: '/ru/contact'
      preLoaderRoute: typeof RuContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/faq': {
      id: '/ru/faq'
      path: '/ru/faq'
      fullPath: '/ru/faq'
      preLoaderRoute: typeof RuFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/about': {
      id: '/tr/about'
      path: '/tr/about'
      fullPath: '/tr/about'
      preLoaderRoute: typeof TrAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/apps': {
      id: '/tr/apps'
      path: '/tr/apps'
      fullPath: '/tr/apps'
      preLoaderRoute: typeof TrAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/contact': {
      id: '/tr/contact'
      path: '/tr/contact'
      fullPath: '/tr/contact'
      preLoaderRoute: typeof TrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/faq': {
      id: '/tr/faq'
      path: '/tr/faq'
      fullPath: '/tr/faq'
      preLoaderRoute: typeof TrFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/apps/$slug': {
      id: '/ar/apps/$slug'
      path: '/$slug'
      fullPath: '/ar/apps/$slug'
      preLoaderRoute: typeof ArAppsSlugRouteImport
      parentRoute: typeof ArAppsRoute
    }
    '/ar/faq/$slug': {
      id: '/ar/faq/$slug'
      path: '/$slug'
      fullPath: '/ar/faq/$slug'
      preLoaderRoute: typeof ArFaqSlugRouteImport
      parentRoute: typeof ArFaqRoute
    }
    '/ar/programming/$slug': {
      id: '/ar/programming/$slug'
      path: '/ar/programming/$slug'
      fullPath: '/ar/programming/$slug'
      preLoaderRoute: typeof ArProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/apps/$slug': {
      id: '/en/apps/$slug'
      path: '/$slug'
      fullPath: '/en/apps/$slug'
      preLoaderRoute: typeof EnAppsSlugRouteImport
      parentRoute: typeof EnAppsRoute
    }
    '/en/faq/$slug': {
      id: '/en/faq/$slug'
      path: '/$slug'
      fullPath: '/en/faq/$slug'
      preLoaderRoute: typeof EnFaqSlugRouteImport
      parentRoute: typeof EnFaqRoute
    }
    '/en/programming/$slug': {
      id: '/en/programming/$slug'
      path: '/en/programming/$slug'
      fullPath: '/en/programming/$slug'
      preLoaderRoute: typeof EnProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$topic/': {
      id: '/resources/$topic/'
      path: '/'
      fullPath: '/resources/$topic/'
      preLoaderRoute: typeof ResourcesTopicIndexRouteImport
      parentRoute: typeof ResourcesTopicRouteRoute
    }
    '/resources/$topic/$article': {
      id: '/resources/$topic/$article'
      path: '/$article'
      fullPath: '/resources/$topic/$article'
      preLoaderRoute: typeof ResourcesTopicArticleRouteImport
      parentRoute: typeof ResourcesTopicRouteRoute
    }
    '/ru/apps/$slug': {
      id: '/ru/apps/$slug'
      path: '/$slug'
      fullPath: '/ru/apps/$slug'
      preLoaderRoute: typeof RuAppsSlugRouteImport
      parentRoute: typeof RuAppsRoute
    }
    '/ru/faq/$slug': {
      id: '/ru/faq/$slug'
      path: '/$slug'
      fullPath: '/ru/faq/$slug'
      preLoaderRoute: typeof RuFaqSlugRouteImport
      parentRoute: typeof RuFaqRoute
    }
    '/ru/programming/$slug': {
      id: '/ru/programming/$slug'
      path: '/ru/programming/$slug'
      fullPath: '/ru/programming/$slug'
      preLoaderRoute: typeof RuProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/resources/$slug': {
      id: '/ru/resources/$slug'
      path: '/ru/resources/$slug'
      fullPath: '/ru/resources/$slug'
      preLoaderRoute: typeof RuResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/apps/$slug': {
      id: '/tr/apps/$slug'
      path: '/$slug'
      fullPath: '/tr/apps/$slug'
      preLoaderRoute: typeof TrAppsSlugRouteImport
      parentRoute: typeof TrAppsRoute
    }
    '/tr/faq/$slug': {
      id: '/tr/faq/$slug'
      path: '/$slug'
      fullPath: '/tr/faq/$slug'
      preLoaderRoute: typeof TrFaqSlugRouteImport
      parentRoute: typeof TrFaqRoute
    }
    '/tr/programming/$slug': {
      id: '/tr/programming/$slug'
      path: '/tr/programming/$slug'
      fullPath: '/tr/programming/$slug'
      preLoaderRoute: typeof TrProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FaqRouteChildren {
  FaqSlugRoute: typeof FaqSlugRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqSlugRoute: FaqSlugRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

interface PrivacyRouteChildren {
  PrivacySlugRoute: typeof PrivacySlugRoute
  PrivacyNibrasPdfRoute: typeof PrivacyNibrasPdfRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacySlugRoute: PrivacySlugRoute,
  PrivacyNibrasPdfRoute: PrivacyNibrasPdfRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

interface ResourcesTopicRouteRouteChildren {
  ResourcesTopicArticleRoute: typeof ResourcesTopicArticleRoute
  ResourcesTopicIndexRoute: typeof ResourcesTopicIndexRoute
}

const ResourcesTopicRouteRouteChildren: ResourcesTopicRouteRouteChildren = {
  ResourcesTopicArticleRoute: ResourcesTopicArticleRoute,
  ResourcesTopicIndexRoute: ResourcesTopicIndexRoute,
}

const ResourcesTopicRouteRouteWithChildren =
  ResourcesTopicRouteRoute._addFileChildren(ResourcesTopicRouteRouteChildren)

interface ArAppsRouteChildren {
  ArAppsSlugRoute: typeof ArAppsSlugRoute
}

const ArAppsRouteChildren: ArAppsRouteChildren = {
  ArAppsSlugRoute: ArAppsSlugRoute,
}

const ArAppsRouteWithChildren =
  ArAppsRoute._addFileChildren(ArAppsRouteChildren)

interface ArFaqRouteChildren {
  ArFaqSlugRoute: typeof ArFaqSlugRoute
}

const ArFaqRouteChildren: ArFaqRouteChildren = {
  ArFaqSlugRoute: ArFaqSlugRoute,
}

const ArFaqRouteWithChildren = ArFaqRoute._addFileChildren(ArFaqRouteChildren)

interface EnAppsRouteChildren {
  EnAppsSlugRoute: typeof EnAppsSlugRoute
}

const EnAppsRouteChildren: EnAppsRouteChildren = {
  EnAppsSlugRoute: EnAppsSlugRoute,
}

const EnAppsRouteWithChildren =
  EnAppsRoute._addFileChildren(EnAppsRouteChildren)

interface EnFaqRouteChildren {
  EnFaqSlugRoute: typeof EnFaqSlugRoute
}

const EnFaqRouteChildren: EnFaqRouteChildren = {
  EnFaqSlugRoute: EnFaqSlugRoute,
}

const EnFaqRouteWithChildren = EnFaqRoute._addFileChildren(EnFaqRouteChildren)

interface RuAppsRouteChildren {
  RuAppsSlugRoute: typeof RuAppsSlugRoute
}

const RuAppsRouteChildren: RuAppsRouteChildren = {
  RuAppsSlugRoute: RuAppsSlugRoute,
}

const RuAppsRouteWithChildren =
  RuAppsRoute._addFileChildren(RuAppsRouteChildren)

interface RuFaqRouteChildren {
  RuFaqSlugRoute: typeof RuFaqSlugRoute
}

const RuFaqRouteChildren: RuFaqRouteChildren = {
  RuFaqSlugRoute: RuFaqSlugRoute,
}

const RuFaqRouteWithChildren = RuFaqRoute._addFileChildren(RuFaqRouteChildren)

interface TrAppsRouteChildren {
  TrAppsSlugRoute: typeof TrAppsSlugRoute
}

const TrAppsRouteChildren: TrAppsRouteChildren = {
  TrAppsSlugRoute: TrAppsSlugRoute,
}

const TrAppsRouteWithChildren =
  TrAppsRoute._addFileChildren(TrAppsRouteChildren)

interface TrFaqRouteChildren {
  TrFaqSlugRoute: typeof TrFaqSlugRoute
}

const TrFaqRouteChildren: TrFaqRouteChildren = {
  TrFaqSlugRoute: TrFaqSlugRoute,
}

const TrFaqRouteWithChildren = TrFaqRoute._addFileChildren(TrFaqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRouteWithChildren,
  NxStudioRoute: NxStudioRoute,
  PrivacyRoute: PrivacyRouteWithChildren,
  UnutmaRoute: UnutmaRoute,
  WhyRoute: WhyRoute,
  ResourcesTopicRouteRoute: ResourcesTopicRouteRouteWithChildren,
  AppsSlugRoute: AppsSlugRoute,
  ArAboutRoute: ArAboutRoute,
  ArAppsRoute: ArAppsRouteWithChildren,
  ArContactRoute: ArContactRoute,
  ArFaqRoute: ArFaqRouteWithChildren,
  EnAboutRoute: EnAboutRoute,
  EnAppsRoute: EnAppsRouteWithChildren,
  EnContactRoute: EnContactRoute,
  EnFaqRoute: EnFaqRouteWithChildren,
  GuidesTopicRoute: GuidesTopicRoute,
  ProgrammingTopicRoute: ProgrammingTopicRoute,
  ResurslarSlugRoute: ResurslarSlugRoute,
  RuAboutRoute: RuAboutRoute,
  RuAppsRoute: RuAppsRouteWithChildren,
  RuContactRoute: RuContactRoute,
  RuFaqRoute: RuFaqRouteWithChildren,
  TrAboutRoute: TrAboutRoute,
  TrAppsRoute: TrAppsRouteWithChildren,
  TrContactRoute: TrContactRoute,
  TrFaqRoute: TrFaqRouteWithChildren,
  AppsIndexRoute: AppsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ProgrammingIndexRoute: ProgrammingIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ArProgrammingSlugRoute: ArProgrammingSlugRoute,
  EnProgrammingSlugRoute: EnProgrammingSlugRoute,
  RuProgrammingSlugRoute: RuProgrammingSlugRoute,
  RuResourcesSlugRoute: RuResourcesSlugRoute,
  TrProgrammingSlugRoute: TrProgrammingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
