/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MovzuRouteImport } from './routes/movzu'
import { Route as MuqayiseRouteImport } from './routes/muqayise'
import { Route as NeceRouteImport } from './routes/nece'
import { Route as NxStudioRouteImport } from './routes/nx-studio'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SozRouteImport } from './routes/soz'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UnutmaRouteImport } from './routes/unutma'
import { Route as WhyRouteImport } from './routes/why'
import { Route as XetaRouteImport } from './routes/xeta'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsSlugRouteImport } from './routes/apps/$slug'
import { Route as ArAboutRouteImport } from './routes/ar.about'
import { Route as ArAppsRouteImport } from './routes/ar.apps'
import { Route as ArContactRouteImport } from './routes/ar.contact'
import { Route as ArFaqRouteImport } from './routes/ar.faq'
import { Route as ArMovzuRouteImport } from './routes/ar.movzu'
import { Route as ArMuqayiseRouteImport } from './routes/ar.muqayise'
import { Route as ArNeceRouteImport } from './routes/ar.nece'
import { Route as ArPaketRouteImport } from './routes/ar.paket'
import { Route as ArSozRouteImport } from './routes/ar.soz'
import { Route as ArToolsRouteImport } from './routes/ar.tools'
import { Route as ArXetaRouteImport } from './routes/ar.xeta'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnAppsRouteImport } from './routes/en.apps'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnFaqRouteImport } from './routes/en.faq'
import { Route as EnMovzuRouteImport } from './routes/en.movzu'
import { Route as EnMuqayiseRouteImport } from './routes/en.muqayise'
import { Route as EnNeceRouteImport } from './routes/en.nece'
import { Route as EnPaketRouteImport } from './routes/en.paket'
import { Route as EnSozRouteImport } from './routes/en.soz'
import { Route as EnToolsRouteImport } from './routes/en.tools'
import { Route as EnXetaRouteImport } from './routes/en.xeta'
import { Route as FaqSlugRouteImport } from './routes/faq.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesTopicRouteImport } from './routes/guides/$topic'
import { Route as MovzuSlugRouteImport } from './routes/movzu.$slug'
import { Route as MuqayiseSlugRouteImport } from './routes/muqayise.$slug'
import { Route as NeceSlugRouteImport } from './routes/nece.$slug'
import { Route as PrivacySlugRouteImport } from './routes/privacy/$slug'
import { Route as PrivacyNibrasPdfRouteImport } from './routes/privacy.nibras-pdf'
import { Route as ProgrammingIndexRouteImport } from './routes/programming/index'
import { Route as ProgrammingTopicRouteImport } from './routes/programming/$topic'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesTopicRouteRouteImport } from './routes/resources/$topic/route'
import { Route as ResurslarSlugRouteImport } from './routes/resurslar/$slug'
import { Route as RuAboutRouteImport } from './routes/ru.about'
import { Route as RuAppsRouteImport } from './routes/ru.apps'
import { Route as RuContactRouteImport } from './routes/ru.contact'
import { Route as RuFaqRouteImport } from './routes/ru.faq'
import { Route as RuMovzuRouteImport } from './routes/ru.movzu'
import { Route as RuMuqayiseRouteImport } from './routes/ru.muqayise'
import { Route as RuNeceRouteImport } from './routes/ru.nece'
import { Route as RuPaketRouteImport } from './routes/ru.paket'
import { Route as RuSozRouteImport } from './routes/ru.soz'
import { Route as RuToolsRouteImport } from './routes/ru.tools'
import { Route as RuXetaRouteImport } from './routes/ru.xeta'
import { Route as SozSlugRouteImport } from './routes/soz.$slug'
import { Route as TrAboutRouteImport } from './routes/tr.about'
import { Route as TrAppsRouteImport } from './routes/tr.apps'
import { Route as TrContactRouteImport } from './routes/tr.contact'
import { Route as TrFaqRouteImport } from './routes/tr.faq'
import { Route as TrMovzuRouteImport } from './routes/tr.movzu'
import { Route as TrMuqayiseRouteImport } from './routes/tr.muqayise'
import { Route as TrNeceRouteImport } from './routes/tr.nece'
import { Route as TrPaketRouteImport } from './routes/tr.paket'
import { Route as TrSozRouteImport } from './routes/tr.soz'
import { Route as TrToolsRouteImport } from './routes/tr.tools'
import { Route as TrXetaRouteImport } from './routes/tr.xeta'
import { Route as XetaSlugRouteImport } from './routes/xeta.$slug'
import { Route as ArAppsSlugRouteImport } from './routes/ar.apps.$slug'
import { Route as ArFaqSlugRouteImport } from './routes/ar.faq.$slug'
import { Route as ArMovzuSlugRouteImport } from './routes/ar.movzu.$slug'
import { Route as ArMuqayiseSlugRouteImport } from './routes/ar.muqayise.$slug'
import { Route as ArNeceSlugRouteImport } from './routes/ar.nece.$slug'
import { Route as ArProgrammingSlugRouteImport } from './routes/ar.programming.$slug'
import { Route as ArSozSlugRouteImport } from './routes/ar.soz.$slug'
import { Route as ArXetaSlugRouteImport } from './routes/ar.xeta.$slug'
import { Route as EnAppsSlugRouteImport } from './routes/en.apps.$slug'
import { Route as EnFaqSlugRouteImport } from './routes/en.faq.$slug'
import { Route as EnMovzuSlugRouteImport } from './routes/en.movzu.$slug'
import { Route as EnMuqayiseSlugRouteImport } from './routes/en.muqayise.$slug'
import { Route as EnNeceSlugRouteImport } from './routes/en.nece.$slug'
import { Route as EnProgrammingSlugRouteImport } from './routes/en.programming.$slug'
import { Route as EnSozSlugRouteImport } from './routes/en.soz.$slug'
import { Route as EnXetaSlugRouteImport } from './routes/en.xeta.$slug'
import { Route as ResourcesTopicIndexRouteImport } from './routes/resources/$topic/index'
import { Route as ResourcesTopicArticleRouteImport } from './routes/resources/$topic/$article'
import { Route as RuAppsSlugRouteImport } from './routes/ru.apps.$slug'
import { Route as RuFaqSlugRouteImport } from './routes/ru.faq.$slug'
import { Route as RuMovzuSlugRouteImport } from './routes/ru.movzu.$slug'
import { Route as RuMuqayiseSlugRouteImport } from './routes/ru.muqayise.$slug'
import { Route as RuNeceSlugRouteImport } from './routes/ru.nece.$slug'
import { Route as RuProgrammingSlugRouteImport } from './routes/ru.programming.$slug'
import { Route as RuResourcesSlugRouteImport } from './routes/ru.resources.$slug'
import { Route as RuSozSlugRouteImport } from './routes/ru.soz.$slug'
import { Route as RuXetaSlugRouteImport } from './routes/ru.xeta.$slug'
import { Route as TrAppsSlugRouteImport } from './routes/tr.apps.$slug'
import { Route as TrFaqSlugRouteImport } from './routes/tr.faq.$slug'
import { Route as TrMovzuSlugRouteImport } from './routes/tr.movzu.$slug'
import { Route as TrMuqayiseSlugRouteImport } from './routes/tr.muqayise.$slug'
import { Route as TrNeceSlugRouteImport } from './routes/tr.nece.$slug'
import { Route as TrProgrammingSlugRouteImport } from './routes/tr.programming.$slug'
import { Route as TrSozSlugRouteImport } from './routes/tr.soz.$slug'
import { Route as TrXetaSlugRouteImport } from './routes/tr.xeta.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MovzuRoute = MovzuRouteImport.update({
  id: '/movzu',
  path: '/movzu',
  getParentRoute: () => rootRouteImport,
} as any)
const MuqayiseRoute = MuqayiseRouteImport.update({
  id: '/muqayise',
  path: '/muqayise',
  getParentRoute: () => rootRouteImport,
} as any)
const NeceRoute = NeceRouteImport.update({
  id: '/nece',
  path: '/nece',
  getParentRoute: () => rootRouteImport,
} as any)
const NxStudioRoute = NxStudioRouteImport.update({
  id: '/nx-studio',
  path: '/nx-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SozRoute = SozRouteImport.update({
  id: '/soz',
  path: '/soz',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UnutmaRoute = UnutmaRouteImport.update({
  id: '/unutma',
  path: '/unutma',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const XetaRoute = XetaRouteImport.update({
  id: '/xeta',
  path: '/xeta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAboutRoute = ArAboutRouteImport.update({
  id: '/ar/about',
  path: '/ar/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAppsRoute = ArAppsRouteImport.update({
  id: '/ar/apps',
  path: '/ar/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ArContactRoute = ArContactRouteImport.update({
  id: '/ar/contact',
  path: '/ar/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArFaqRoute = ArFaqRouteImport.update({
  id: '/ar/faq',
  path: '/ar/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ArMovzuRoute = ArMovzuRouteImport.update({
  id: '/ar/movzu',
  path: '/ar/movzu',
  getParentRoute: () => rootRouteImport,
} as any)
const ArMuqayiseRoute = ArMuqayiseRouteImport.update({
  id: '/ar/muqayise',
  path: '/ar/muqayise',
  getParentRoute: () => rootRouteImport,
} as any)
const ArNeceRoute = ArNeceRouteImport.update({
  id: '/ar/nece',
  path: '/ar/nece',
  getParentRoute: () => rootRouteImport,
} as any)
const ArPaketRoute = ArPaketRouteImport.update({
  id: '/ar/paket',
  path: '/ar/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const ArSozRoute = ArSozRouteImport.update({
  id: '/ar/soz',
  path: '/ar/soz',
  getParentRoute: () => rootRouteImport,
} as any)
const ArToolsRoute = ArToolsRouteImport.update({
  id: '/ar/tools',
  path: '/ar/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ArXetaRoute = ArXetaRouteImport.update({
  id: '/ar/xeta',
  path: '/ar/xeta',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAppsRoute = EnAppsRouteImport.update({
  id: '/en/apps',
  path: '/en/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/en/faq',
  path: '/en/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMovzuRoute = EnMovzuRouteImport.update({
  id: '/en/movzu',
  path: '/en/movzu',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMuqayiseRoute = EnMuqayiseRouteImport.update({
  id: '/en/muqayise',
  path: '/en/muqayise',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNeceRoute = EnNeceRouteImport.update({
  id: '/en/nece',
  path: '/en/nece',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPaketRoute = EnPaketRouteImport.update({
  id: '/en/paket',
  path: '/en/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSozRoute = EnSozRouteImport.update({
  id: '/en/soz',
  path: '/en/soz',
  getParentRoute: () => rootRouteImport,
} as any)
const EnToolsRoute = EnToolsRouteImport.update({
  id: '/en/tools',
  path: '/en/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const EnXetaRoute = EnXetaRouteImport.update({
  id: '/en/xeta',
  path: '/en/xeta',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FaqRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTopicRoute = GuidesTopicRouteImport.update({
  id: '/guides/$topic',
  path: '/guides/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const MovzuSlugRoute = MovzuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MovzuRoute,
} as any)
const MuqayiseSlugRoute = MuqayiseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MuqayiseRoute,
} as any)
const NeceSlugRoute = NeceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeceRoute,
} as any)
const PrivacySlugRoute = PrivacySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrivacyRoute,
} as any)
const PrivacyNibrasPdfRoute = PrivacyNibrasPdfRouteImport.update({
  id: '/nibras-pdf',
  path: '/nibras-pdf',
  getParentRoute: () => PrivacyRoute,
} as any)
const ProgrammingIndexRoute = ProgrammingIndexRouteImport.update({
  id: '/programming/',
  path: '/programming/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammingTopicRoute = ProgrammingTopicRouteImport.update({
  id: '/programming/$topic',
  path: '/programming/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTopicRouteRoute = ResourcesTopicRouteRouteImport.update({
  id: '/resources/$topic',
  path: '/resources/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurslarSlugRoute = ResurslarSlugRouteImport.update({
  id: '/resurslar/$slug',
  path: '/resurslar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAboutRoute = RuAboutRouteImport.update({
  id: '/ru/about',
  path: '/ru/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAppsRoute = RuAppsRouteImport.update({
  id: '/ru/apps',
  path: '/ru/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const RuContactRoute = RuContactRouteImport.update({
  id: '/ru/contact',
  path: '/ru/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RuFaqRoute = RuFaqRouteImport.update({
  id: '/ru/faq',
  path: '/ru/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const RuMovzuRoute = RuMovzuRouteImport.update({
  id: '/ru/movzu',
  path: '/ru/movzu',
  getParentRoute: () => rootRouteImport,
} as any)
const RuMuqayiseRoute = RuMuqayiseRouteImport.update({
  id: '/ru/muqayise',
  path: '/ru/muqayise',
  getParentRoute: () => rootRouteImport,
} as any)
const RuNeceRoute = RuNeceRouteImport.update({
  id: '/ru/nece',
  path: '/ru/nece',
  getParentRoute: () => rootRouteImport,
} as any)
const RuPaketRoute = RuPaketRouteImport.update({
  id: '/ru/paket',
  path: '/ru/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const RuSozRoute = RuSozRouteImport.update({
  id: '/ru/soz',
  path: '/ru/soz',
  getParentRoute: () => rootRouteImport,
} as any)
const RuToolsRoute = RuToolsRouteImport.update({
  id: '/ru/tools',
  path: '/ru/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RuXetaRoute = RuXetaRouteImport.update({
  id: '/ru/xeta',
  path: '/ru/xeta',
  getParentRoute: () => rootRouteImport,
} as any)
const SozSlugRoute = SozSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SozRoute,
} as any)
const TrAboutRoute = TrAboutRouteImport.update({
  id: '/tr/about',
  path: '/tr/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TrAppsRoute = TrAppsRouteImport.update({
  id: '/tr/apps',
  path: '/tr/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const TrContactRoute = TrContactRouteImport.update({
  id: '/tr/contact',
  path: '/tr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TrFaqRoute = TrFaqRouteImport.update({
  id: '/tr/faq',
  path: '/tr/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const TrMovzuRoute = TrMovzuRouteImport.update({
  id: '/tr/movzu',
  path: '/tr/movzu',
  getParentRoute: () => rootRouteImport,
} as any)
const TrMuqayiseRoute = TrMuqayiseRouteImport.update({
  id: '/tr/muqayise',
  path: '/tr/muqayise',
  getParentRoute: () => rootRouteImport,
} as any)
const TrNeceRoute = TrNeceRouteImport.update({
  id: '/tr/nece',
  path: '/tr/nece',
  getParentRoute: () => rootRouteImport,
} as any)
const TrPaketRoute = TrPaketRouteImport.update({
  id: '/tr/paket',
  path: '/tr/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const TrSozRoute = TrSozRouteImport.update({
  id: '/tr/soz',
  path: '/tr/soz',
  getParentRoute: () => rootRouteImport,
} as any)
const TrToolsRoute = TrToolsRouteImport.update({
  id: '/tr/tools',
  path: '/tr/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrXetaRoute = TrXetaRouteImport.update({
  id: '/tr/xeta',
  path: '/tr/xeta',
  getParentRoute: () => rootRouteImport,
} as any)
const XetaSlugRoute = XetaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => XetaRoute,
} as any)
const ArAppsSlugRoute = ArAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArAppsRoute,
} as any)
const ArFaqSlugRoute = ArFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArFaqRoute,
} as any)
const ArMovzuSlugRoute = ArMovzuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArMovzuRoute,
} as any)
const ArMuqayiseSlugRoute = ArMuqayiseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArMuqayiseRoute,
} as any)
const ArNeceSlugRoute = ArNeceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArNeceRoute,
} as any)
const ArProgrammingSlugRoute = ArProgrammingSlugRouteImport.update({
  id: '/ar/programming/$slug',
  path: '/ar/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArSozSlugRoute = ArSozSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArSozRoute,
} as any)
const ArXetaSlugRoute = ArXetaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArXetaRoute,
} as any)
const EnAppsSlugRoute = EnAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnAppsRoute,
} as any)
const EnFaqSlugRoute = EnFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnFaqRoute,
} as any)
const EnMovzuSlugRoute = EnMovzuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnMovzuRoute,
} as any)
const EnMuqayiseSlugRoute = EnMuqayiseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnMuqayiseRoute,
} as any)
const EnNeceSlugRoute = EnNeceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnNeceRoute,
} as any)
const EnProgrammingSlugRoute = EnProgrammingSlugRouteImport.update({
  id: '/en/programming/$slug',
  path: '/en/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSozSlugRoute = EnSozSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnSozRoute,
} as any)
const EnXetaSlugRoute = EnXetaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnXetaRoute,
} as any)
const ResourcesTopicIndexRoute = ResourcesTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesTopicRouteRoute,
} as any)
const ResourcesTopicArticleRoute = ResourcesTopicArticleRouteImport.update({
  id: '/$article',
  path: '/$article',
  getParentRoute: () => ResourcesTopicRouteRoute,
} as any)
const RuAppsSlugRoute = RuAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuAppsRoute,
} as any)
const RuFaqSlugRoute = RuFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuFaqRoute,
} as any)
const RuMovzuSlugRoute = RuMovzuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuMovzuRoute,
} as any)
const RuMuqayiseSlugRoute = RuMuqayiseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuMuqayiseRoute,
} as any)
const RuNeceSlugRoute = RuNeceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuNeceRoute,
} as any)
const RuProgrammingSlugRoute = RuProgrammingSlugRouteImport.update({
  id: '/ru/programming/$slug',
  path: '/ru/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuResourcesSlugRoute = RuResourcesSlugRouteImport.update({
  id: '/ru/resources/$slug',
  path: '/ru/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuSozSlugRoute = RuSozSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuSozRoute,
} as any)
const RuXetaSlugRoute = RuXetaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuXetaRoute,
} as any)
const TrAppsSlugRoute = TrAppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrAppsRoute,
} as any)
const TrFaqSlugRoute = TrFaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrFaqRoute,
} as any)
const TrMovzuSlugRoute = TrMovzuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrMovzuRoute,
} as any)
const TrMuqayiseSlugRoute = TrMuqayiseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrMuqayiseRoute,
} as any)
const TrNeceSlugRoute = TrNeceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrNeceRoute,
} as any)
const TrProgrammingSlugRoute = TrProgrammingSlugRouteImport.update({
  id: '/tr/programming/$slug',
  path: '/tr/programming/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrSozSlugRoute = TrSozSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrSozRoute,
} as any)
const TrXetaSlugRoute = TrXetaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrXetaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/movzu': typeof MovzuRouteWithChildren
  '/muqayise': typeof MuqayiseRouteWithChildren
  '/nece': typeof NeceRouteWithChildren
  '/nx-studio': typeof NxStudioRoute
  '/paket': typeof PaketRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/soz': typeof SozRouteWithChildren
  '/tools': typeof ToolsRoute
  '/unutma': typeof UnutmaRoute
  '/why': typeof WhyRoute
  '/xeta': typeof XetaRouteWithChildren
  '/resources/$topic': typeof ResourcesTopicRouteRouteWithChildren
  '/apps/$slug': typeof AppsSlugRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/apps': typeof ArAppsRouteWithChildren
  '/ar/contact': typeof ArContactRoute
  '/ar/faq': typeof ArFaqRouteWithChildren
  '/ar/movzu': typeof ArMovzuRouteWithChildren
  '/ar/muqayise': typeof ArMuqayiseRouteWithChildren
  '/ar/nece': typeof ArNeceRouteWithChildren
  '/ar/paket': typeof ArPaketRoute
  '/ar/soz': typeof ArSozRouteWithChildren
  '/ar/tools': typeof ArToolsRoute
  '/ar/xeta': typeof ArXetaRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apps': typeof EnAppsRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRouteWithChildren
  '/en/movzu': typeof EnMovzuRouteWithChildren
  '/en/muqayise': typeof EnMuqayiseRouteWithChildren
  '/en/nece': typeof EnNeceRouteWithChildren
  '/en/paket': typeof EnPaketRoute
  '/en/soz': typeof EnSozRouteWithChildren
  '/en/tools': typeof EnToolsRoute
  '/en/xeta': typeof EnXetaRouteWithChildren
  '/faq/$slug': typeof FaqSlugRoute
  '/guides/$topic': typeof GuidesTopicRoute
  '/movzu/$slug': typeof MovzuSlugRoute
  '/muqayise/$slug': typeof MuqayiseSlugRoute
  '/nece/$slug': typeof NeceSlugRoute
  '/privacy/$slug': typeof PrivacySlugRoute
  '/privacy/nibras-pdf': typeof PrivacyNibrasPdfRoute
  '/programming/$topic': typeof ProgrammingTopicRoute
  '/resurslar/$slug': typeof ResurslarSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/apps': typeof RuAppsRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/faq': typeof RuFaqRouteWithChildren
  '/ru/movzu': typeof RuMovzuRouteWithChildren
  '/ru/muqayise': typeof RuMuqayiseRouteWithChildren
  '/ru/nece': typeof RuNeceRouteWithChildren
  '/ru/paket': typeof RuPaketRoute
  '/ru/soz': typeof RuSozRouteWithChildren
  '/ru/tools': typeof RuToolsRoute
  '/ru/xeta': typeof RuXetaRouteWithChildren
  '/soz/$slug': typeof SozSlugRoute
  '/tr/about': typeof TrAboutRoute
  '/tr/apps': typeof TrAppsRouteWithChildren
  '/tr/contact': typeof TrContactRoute
  '/tr/faq': typeof TrFaqRouteWithChildren
  '/tr/movzu': typeof TrMovzuRouteWithChildren
  '/tr/muqayise': typeof TrMuqayiseRouteWithChildren
  '/tr/nece': typeof TrNeceRouteWithChildren
  '/tr/paket': typeof TrPaketRoute
  '/tr/soz': typeof TrSozRouteWithChildren
  '/tr/tools': typeof TrToolsRoute
  '/tr/xeta': typeof TrXetaRouteWithChildren
  '/xeta/$slug': typeof XetaSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/programming/': typeof ProgrammingIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/ar/apps/$slug': typeof ArAppsSlugRoute
  '/ar/faq/$slug': typeof ArFaqSlugRoute
  '/ar/movzu/$slug': typeof ArMovzuSlugRoute
  '/ar/muqayise/$slug': typeof ArMuqayiseSlugRoute
  '/ar/nece/$slug': typeof ArNeceSlugRoute
  '/ar/programming/$slug': typeof ArProgrammingSlugRoute
  '/ar/soz/$slug': typeof ArSozSlugRoute
  '/ar/xeta/$slug': typeof ArXetaSlugRoute
  '/en/apps/$slug': typeof EnAppsSlugRoute
  '/en/faq/$slug': typeof EnFaqSlugRoute
  '/en/movzu/$slug': typeof EnMovzuSlugRoute
  '/en/muqayise/$slug': typeof EnMuqayiseSlugRoute
  '/en/nece/$slug': typeof EnNeceSlugRoute
  '/en/programming/$slug': typeof EnProgrammingSlugRoute
  '/en/soz/$slug': typeof EnSozSlugRoute
  '/en/xeta/$slug': typeof EnXetaSlugRoute
  '/resources/$topic/$article': typeof ResourcesTopicArticleRoute
  '/ru/apps/$slug': typeof RuAppsSlugRoute
  '/ru/faq/$slug': typeof RuFaqSlugRoute
  '/ru/movzu/$slug': typeof RuMovzuSlugRoute
  '/ru/muqayise/$slug': typeof RuMuqayiseSlugRoute
  '/ru/nece/$slug': typeof RuNeceSlugRoute
  '/ru/programming/$slug': typeof RuProgrammingSlugRoute
  '/ru/resources/$slug': typeof RuResourcesSlugRoute
  '/ru/soz/$slug': typeof RuSozSlugRoute
  '/ru/xeta/$slug': typeof RuXetaSlugRoute
  '/tr/apps/$slug': typeof TrAppsSlugRoute
  '/tr/faq/$slug': typeof TrFaqSlugRoute
  '/tr/movzu/$slug': typeof TrMovzuSlugRoute
  '/tr/muqayise/$slug': typeof TrMuqayiseSlugRoute
  '/tr/nece/$slug': typeof TrNeceSlugRoute
  '/tr/programming/$slug': typeof TrProgrammingSlugRoute
  '/tr/soz/$slug': typeof TrSozSlugRoute
  '/tr/xeta/$slug': typeof TrXetaSlugRoute
  '/resources/$topic/': typeof ResourcesTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/movzu': typeof MovzuRouteWithChildren
  '/muqayise': typeof MuqayiseRouteWithChildren
  '/nece': typeof NeceRouteWithChildren
  '/nx-studio': typeof NxStudioRoute
  '/paket': typeof PaketRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/soz': typeof SozRouteWithChildren
  '/tools': typeof ToolsRoute
  '/unutma': typeof UnutmaRoute
  '/why': typeof WhyRoute
  '/xeta': typeof XetaRouteWithChildren
  '/apps/$slug': typeof AppsSlugRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/apps': typeof ArAppsRouteWithChildren
  '/ar/contact': typeof ArContactRoute
  '/ar/faq': typeof ArFaqRouteWithChildren
  '/ar/movzu': typeof ArMovzuRouteWithChildren
  '/ar/muqayise': typeof ArMuqayiseRouteWithChildren
  '/ar/nece': typeof ArNeceRouteWithChildren
  '/ar/paket': typeof ArPaketRoute
  '/ar/soz': typeof ArSozRouteWithChildren
  '/ar/tools': typeof ArToolsRoute
  '/ar/xeta': typeof ArXetaRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apps': typeof EnAppsRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRouteWithChildren
  '/en/movzu': typeof EnMovzuRouteWithChildren
  '/en/muqayise': typeof EnMuqayiseRouteWithChildren
  '/en/nece': typeof EnNeceRouteWithChildren
  '/en/paket': typeof EnPaketRoute
  '/en/soz': typeof EnSozRouteWithChildren
  '/en/tools': typeof EnToolsRoute
  '/en/xeta': typeof EnXetaRouteWithChildren
  '/faq/$slug': typeof FaqSlugRoute
  '/guides/$topic': typeof GuidesTopicRoute
  '/movzu/$slug': typeof MovzuSlugRoute
  '/muqayise/$slug': typeof MuqayiseSlugRoute
  '/nece/$slug': typeof NeceSlugRoute
  '/privacy/$slug': typeof PrivacySlugRoute
  '/privacy/nibras-pdf': typeof PrivacyNibrasPdfRoute
  '/programming/$topic': typeof ProgrammingTopicRoute
  '/resurslar/$slug': typeof ResurslarSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/apps': typeof RuAppsRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/faq': typeof RuFaqRouteWithChildren
  '/ru/movzu': typeof RuMovzuRouteWithChildren
  '/ru/muqayise': typeof RuMuqayiseRouteWithChildren
  '/ru/nece': typeof RuNeceRouteWithChildren
  '/ru/paket': typeof RuPaketRoute
  '/ru/soz': typeof RuSozRouteWithChildren
  '/ru/tools': typeof RuToolsRoute
  '/ru/xeta': typeof RuXetaRouteWithChildren
  '/soz/$slug': typeof SozSlugRoute
  '/tr/about': typeof TrAboutRoute
  '/tr/apps': typeof TrAppsRouteWithChildren
  '/tr/contact': typeof TrContactRoute
  '/tr/faq': typeof TrFaqRouteWithChildren
  '/tr/movzu': typeof TrMovzuRouteWithChildren
  '/tr/muqayise': typeof TrMuqayiseRouteWithChildren
  '/tr/nece': typeof TrNeceRouteWithChildren
  '/tr/paket': typeof TrPaketRoute
  '/tr/soz': typeof TrSozRouteWithChildren
  '/tr/tools': typeof TrToolsRoute
  '/tr/xeta': typeof TrXetaRouteWithChildren
  '/xeta/$slug': typeof XetaSlugRoute
  '/apps': typeof AppsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/programming': typeof ProgrammingIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/ar/apps/$slug': typeof ArAppsSlugRoute
  '/ar/faq/$slug': typeof ArFaqSlugRoute
  '/ar/movzu/$slug': typeof ArMovzuSlugRoute
  '/ar/muqayise/$slug': typeof ArMuqayiseSlugRoute
  '/ar/nece/$slug': typeof ArNeceSlugRoute
  '/ar/programming/$slug': typeof ArProgrammingSlugRoute
  '/ar/soz/$slug': typeof ArSozSlugRoute
  '/ar/xeta/$slug': typeof ArXetaSlugRoute
  '/en/apps/$slug': typeof EnAppsSlugRoute
  '/en/faq/$slug': typeof EnFaqSlugRoute
  '/en/movzu/$slug': typeof EnMovzuSlugRoute
  '/en/muqayise/$slug': typeof EnMuqayiseSlugRoute
  '/en/nece/$slug': typeof EnNeceSlugRoute
  '/en/programming/$slug': typeof EnProgrammingSlugRoute
  '/en/soz/$slug': typeof EnSozSlugRoute
  '/en/xeta/$slug': typeof EnXetaSlugRoute
  '/resources/$topic/$article': typeof ResourcesTopicArticleRoute
  '/ru/apps/$slug': typeof RuAppsSlugRoute
  '/ru/faq/$slug': typeof RuFaqSlugRoute
  '/ru/movzu/$slug': typeof RuMovzuSlugRoute
  '/ru/muqayise/$slug': typeof RuMuqayiseSlugRoute
  '/ru/nece/$slug': typeof RuNeceSlugRoute
  '/ru/programming/$slug': typeof RuProgrammingSlugRoute
  '/ru/resources/$slug': typeof RuResourcesSlugRoute
  '/ru/soz/$slug': typeof RuSozSlugRoute
  '/ru/xeta/$slug': typeof RuXetaSlugRoute
  '/tr/apps/$slug': typeof TrAppsSlugRoute
  '/tr/faq/$slug': typeof TrFaqSlugRoute
  '/tr/movzu/$slug': typeof TrMovzuSlugRoute
  '/tr/muqayise/$slug': typeof TrMuqayiseSlugRoute
  '/tr/nece/$slug': typeof TrNeceSlugRoute
  '/tr/programming/$slug': typeof TrProgrammingSlugRoute
  '/tr/soz/$slug': typeof TrSozSlugRoute
  '/tr/xeta/$slug': typeof TrXetaSlugRoute
  '/resources/$topic': typeof ResourcesTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/movzu': typeof MovzuRouteWithChildren
  '/muqayise': typeof MuqayiseRouteWithChildren
  '/nece': typeof NeceRouteWithChildren
  '/nx-studio': typeof NxStudioRoute
  '/paket': typeof PaketRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/soz': typeof SozRouteWithChildren
  '/tools': typeof ToolsRoute
  '/unutma': typeof UnutmaRoute
  '/why': typeof WhyRoute
  '/xeta': typeof XetaRouteWithChildren
  '/resources/$topic': typeof ResourcesTopicRouteRouteWithChildren
  '/apps/$slug': typeof AppsSlugRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/apps': typeof ArAppsRouteWithChildren
  '/ar/contact': typeof ArContactRoute
  '/ar/faq': typeof ArFaqRouteWithChildren
  '/ar/movzu': typeof ArMovzuRouteWithChildren
  '/ar/muqayise': typeof ArMuqayiseRouteWithChildren
  '/ar/nece': typeof ArNeceRouteWithChildren
  '/ar/paket': typeof ArPaketRoute
  '/ar/soz': typeof ArSozRouteWithChildren
  '/ar/tools': typeof ArToolsRoute
  '/ar/xeta': typeof ArXetaRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apps': typeof EnAppsRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRouteWithChildren
  '/en/movzu': typeof EnMovzuRouteWithChildren
  '/en/muqayise': typeof EnMuqayiseRouteWithChildren
  '/en/nece': typeof EnNeceRouteWithChildren
  '/en/paket': typeof EnPaketRoute
  '/en/soz': typeof EnSozRouteWithChildren
  '/en/tools': typeof EnToolsRoute
  '/en/xeta': typeof EnXetaRouteWithChildren
  '/faq/$slug': typeof FaqSlugRoute
  '/guides/$topic': typeof GuidesTopicRoute
  '/movzu/$slug': typeof MovzuSlugRoute
  '/muqayise/$slug': typeof MuqayiseSlugRoute
  '/nece/$slug': typeof NeceSlugRoute
  '/privacy/$slug': typeof PrivacySlugRoute
  '/privacy/nibras-pdf': typeof PrivacyNibrasPdfRoute
  '/programming/$topic': typeof ProgrammingTopicRoute
  '/resurslar/$slug': typeof ResurslarSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/apps': typeof RuAppsRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/faq': typeof RuFaqRouteWithChildren
  '/ru/movzu': typeof RuMovzuRouteWithChildren
  '/ru/muqayise': typeof RuMuqayiseRouteWithChildren
  '/ru/nece': typeof RuNeceRouteWithChildren
  '/ru/paket': typeof RuPaketRoute
  '/ru/soz': typeof RuSozRouteWithChildren
  '/ru/tools': typeof RuToolsRoute
  '/ru/xeta': typeof RuXetaRouteWithChildren
  '/soz/$slug': typeof SozSlugRoute
  '/tr/about': typeof TrAboutRoute
  '/tr/apps': typeof TrAppsRouteWithChildren
  '/tr/contact': typeof TrContactRoute
  '/tr/faq': typeof TrFaqRouteWithChildren
  '/tr/movzu': typeof TrMovzuRouteWithChildren
  '/tr/muqayise': typeof TrMuqayiseRouteWithChildren
  '/tr/nece': typeof TrNeceRouteWithChildren
  '/tr/paket': typeof TrPaketRoute
  '/tr/soz': typeof TrSozRouteWithChildren
  '/tr/tools': typeof TrToolsRoute
  '/tr/xeta': typeof TrXetaRouteWithChildren
  '/xeta/$slug': typeof XetaSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/programming/': typeof ProgrammingIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/ar/apps/$slug': typeof ArAppsSlugRoute
  '/ar/faq/$slug': typeof ArFaqSlugRoute
  '/ar/movzu/$slug': typeof ArMovzuSlugRoute
  '/ar/muqayise/$slug': typeof ArMuqayiseSlugRoute
  '/ar/nece/$slug': typeof ArNeceSlugRoute
  '/ar/programming/$slug': typeof ArProgrammingSlugRoute
  '/ar/soz/$slug': typeof ArSozSlugRoute
  '/ar/xeta/$slug': typeof ArXetaSlugRoute
  '/en/apps/$slug': typeof EnAppsSlugRoute
  '/en/faq/$slug': typeof EnFaqSlugRoute
  '/en/movzu/$slug': typeof EnMovzuSlugRoute
  '/en/muqayise/$slug': typeof EnMuqayiseSlugRoute
  '/en/nece/$slug': typeof EnNeceSlugRoute
  '/en/programming/$slug': typeof EnProgrammingSlugRoute
  '/en/soz/$slug': typeof EnSozSlugRoute
  '/en/xeta/$slug': typeof EnXetaSlugRoute
  '/resources/$topic/$article': typeof ResourcesTopicArticleRoute
  '/ru/apps/$slug': typeof RuAppsSlugRoute
  '/ru/faq/$slug': typeof RuFaqSlugRoute
  '/ru/movzu/$slug': typeof RuMovzuSlugRoute
  '/ru/muqayise/$slug': typeof RuMuqayiseSlugRoute
  '/ru/nece/$slug': typeof RuNeceSlugRoute
  '/ru/programming/$slug': typeof RuProgrammingSlugRoute
  '/ru/resources/$slug': typeof RuResourcesSlugRoute
  '/ru/soz/$slug': typeof RuSozSlugRoute
  '/ru/xeta/$slug': typeof RuXetaSlugRoute
  '/tr/apps/$slug': typeof TrAppsSlugRoute
  '/tr/faq/$slug': typeof TrFaqSlugRoute
  '/tr/movzu/$slug': typeof TrMovzuSlugRoute
  '/tr/muqayise/$slug': typeof TrMuqayiseSlugRoute
  '/tr/nece/$slug': typeof TrNeceSlugRoute
  '/tr/programming/$slug': typeof TrProgrammingSlugRoute
  '/tr/soz/$slug': typeof TrSozSlugRoute
  '/tr/xeta/$slug': typeof TrXetaSlugRoute
  '/resources/$topic/': typeof ResourcesTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/movzu'
    | '/muqayise'
    | '/nece'
    | '/nx-studio'
    | '/paket'
    | '/privacy'
    | '/soz'
    | '/tools'
    | '/unutma'
    | '/why'
    | '/xeta'
    | '/resources/$topic'
    | '/apps/$slug'
    | '/ar/about'
    | '/ar/apps'
    | '/ar/contact'
    | '/ar/faq'
    | '/ar/movzu'
    | '/ar/muqayise'
    | '/ar/nece'
    | '/ar/paket'
    | '/ar/soz'
    | '/ar/tools'
    | '/ar/xeta'
    | '/en/about'
    | '/en/apps'
    | '/en/contact'
    | '/en/faq'
    | '/en/movzu'
    | '/en/muqayise'
    | '/en/nece'
    | '/en/paket'
    | '/en/soz'
    | '/en/tools'
    | '/en/xeta'
    | '/faq/$slug'
    | '/guides/$topic'
    | '/movzu/$slug'
    | '/muqayise/$slug'
    | '/nece/$slug'
    | '/privacy/$slug'
    | '/privacy/nibras-pdf'
    | '/programming/$topic'
    | '/resurslar/$slug'
    | '/ru/about'
    | '/ru/apps'
    | '/ru/contact'
    | '/ru/faq'
    | '/ru/movzu'
    | '/ru/muqayise'
    | '/ru/nece'
    | '/ru/paket'
    | '/ru/soz'
    | '/ru/tools'
    | '/ru/xeta'
    | '/soz/$slug'
    | '/tr/about'
    | '/tr/apps'
    | '/tr/contact'
    | '/tr/faq'
    | '/tr/movzu'
    | '/tr/muqayise'
    | '/tr/nece'
    | '/tr/paket'
    | '/tr/soz'
    | '/tr/tools'
    | '/tr/xeta'
    | '/xeta/$slug'
    | '/apps/'
    | '/guides/'
    | '/programming/'
    | '/resources/'
    | '/ar/apps/$slug'
    | '/ar/faq/$slug'
    | '/ar/movzu/$slug'
    | '/ar/muqayise/$slug'
    | '/ar/nece/$slug'
    | '/ar/programming/$slug'
    | '/ar/soz/$slug'
    | '/ar/xeta/$slug'
    | '/en/apps/$slug'
    | '/en/faq/$slug'
    | '/en/movzu/$slug'
    | '/en/muqayise/$slug'
    | '/en/nece/$slug'
    | '/en/programming/$slug'
    | '/en/soz/$slug'
    | '/en/xeta/$slug'
    | '/resources/$topic/$article'
    | '/ru/apps/$slug'
    | '/ru/faq/$slug'
    | '/ru/movzu/$slug'
    | '/ru/muqayise/$slug'
    | '/ru/nece/$slug'
    | '/ru/programming/$slug'
    | '/ru/resources/$slug'
    | '/ru/soz/$slug'
    | '/ru/xeta/$slug'
    | '/tr/apps/$slug'
    | '/tr/faq/$slug'
    | '/tr/movzu/$slug'
    | '/tr/muqayise/$slug'
    | '/tr/nece/$slug'
    | '/tr/programming/$slug'
    | '/tr/soz/$slug'
    | '/tr/xeta/$slug'
    | '/resources/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/movzu'
    | '/muqayise'
    | '/nece'
    | '/nx-studio'
    | '/paket'
    | '/privacy'
    | '/soz'
    | '/tools'
    | '/unutma'
    | '/why'
    | '/xeta'
    | '/apps/$slug'
    | '/ar/about'
    | '/ar/apps'
    | '/ar/contact'
    | '/ar/faq'
    | '/ar/movzu'
    | '/ar/muqayise'
    | '/ar/nece'
    | '/ar/paket'
    | '/ar/soz'
    | '/ar/tools'
    | '/ar/xeta'
    | '/en/about'
    | '/en/apps'
    | '/en/contact'
    | '/en/faq'
    | '/en/movzu'
    | '/en/muqayise'
    | '/en/nece'
    | '/en/paket'
    | '/en/soz'
    | '/en/tools'
    | '/en/xeta'
    | '/faq/$slug'
    | '/guides/$topic'
    | '/movzu/$slug'
    | '/muqayise/$slug'
    | '/nece/$slug'
    | '/privacy/$slug'
    | '/privacy/nibras-pdf'
    | '/programming/$topic'
    | '/resurslar/$slug'
    | '/ru/about'
    | '/ru/apps'
    | '/ru/contact'
    | '/ru/faq'
    | '/ru/movzu'
    | '/ru/muqayise'
    | '/ru/nece'
    | '/ru/paket'
    | '/ru/soz'
    | '/ru/tools'
    | '/ru/xeta'
    | '/soz/$slug'
    | '/tr/about'
    | '/tr/apps'
    | '/tr/contact'
    | '/tr/faq'
    | '/tr/movzu'
    | '/tr/muqayise'
    | '/tr/nece'
    | '/tr/paket'
    | '/tr/soz'
    | '/tr/tools'
    | '/tr/xeta'
    | '/xeta/$slug'
    | '/apps'
    | '/guides'
    | '/programming'
    | '/resources'
    | '/ar/apps/$slug'
    | '/ar/faq/$slug'
    | '/ar/movzu/$slug'
    | '/ar/muqayise/$slug'
    | '/ar/nece/$slug'
    | '/ar/programming/$slug'
    | '/ar/soz/$slug'
    | '/ar/xeta/$slug'
    | '/en/apps/$slug'
    | '/en/faq/$slug'
    | '/en/movzu/$slug'
    | '/en/muqayise/$slug'
    | '/en/nece/$slug'
    | '/en/programming/$slug'
    | '/en/soz/$slug'
    | '/en/xeta/$slug'
    | '/resources/$topic/$article'
    | '/ru/apps/$slug'
    | '/ru/faq/$slug'
    | '/ru/movzu/$slug'
    | '/ru/muqayise/$slug'
    | '/ru/nece/$slug'
    | '/ru/programming/$slug'
    | '/ru/resources/$slug'
    | '/ru/soz/$slug'
    | '/ru/xeta/$slug'
    | '/tr/apps/$slug'
    | '/tr/faq/$slug'
    | '/tr/movzu/$slug'
    | '/tr/muqayise/$slug'
    | '/tr/nece/$slug'
    | '/tr/programming/$slug'
    | '/tr/soz/$slug'
    | '/tr/xeta/$slug'
    | '/resources/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/movzu'
    | '/muqayise'
    | '/nece'
    | '/nx-studio'
    | '/paket'
    | '/privacy'
    | '/soz'
    | '/tools'
    | '/unutma'
    | '/why'
    | '/xeta'
    | '/resources/$topic'
    | '/apps/$slug'
    | '/ar/about'
    | '/ar/apps'
    | '/ar/contact'
    | '/ar/faq'
    | '/ar/movzu'
    | '/ar/muqayise'
    | '/ar/nece'
    | '/ar/paket'
    | '/ar/soz'
    | '/ar/tools'
    | '/ar/xeta'
    | '/en/about'
    | '/en/apps'
    | '/en/contact'
    | '/en/faq'
    | '/en/movzu'
    | '/en/muqayise'
    | '/en/nece'
    | '/en/paket'
    | '/en/soz'
    | '/en/tools'
    | '/en/xeta'
    | '/faq/$slug'
    | '/guides/$topic'
    | '/movzu/$slug'
    | '/muqayise/$slug'
    | '/nece/$slug'
    | '/privacy/$slug'
    | '/privacy/nibras-pdf'
    | '/programming/$topic'
    | '/resurslar/$slug'
    | '/ru/about'
    | '/ru/apps'
    | '/ru/contact'
    | '/ru/faq'
    | '/ru/movzu'
    | '/ru/muqayise'
    | '/ru/nece'
    | '/ru/paket'
    | '/ru/soz'
    | '/ru/tools'
    | '/ru/xeta'
    | '/soz/$slug'
    | '/tr/about'
    | '/tr/apps'
    | '/tr/contact'
    | '/tr/faq'
    | '/tr/movzu'
    | '/tr/muqayise'
    | '/tr/nece'
    | '/tr/paket'
    | '/tr/soz'
    | '/tr/tools'
    | '/tr/xeta'
    | '/xeta/$slug'
    | '/apps/'
    | '/guides/'
    | '/programming/'
    | '/resources/'
    | '/ar/apps/$slug'
    | '/ar/faq/$slug'
    | '/ar/movzu/$slug'
    | '/ar/muqayise/$slug'
    | '/ar/nece/$slug'
    | '/ar/programming/$slug'
    | '/ar/soz/$slug'
    | '/ar/xeta/$slug'
    | '/en/apps/$slug'
    | '/en/faq/$slug'
    | '/en/movzu/$slug'
    | '/en/muqayise/$slug'
    | '/en/nece/$slug'
    | '/en/programming/$slug'
    | '/en/soz/$slug'
    | '/en/xeta/$slug'
    | '/resources/$topic/$article'
    | '/ru/apps/$slug'
    | '/ru/faq/$slug'
    | '/ru/movzu/$slug'
    | '/ru/muqayise/$slug'
    | '/ru/nece/$slug'
    | '/ru/programming/$slug'
    | '/ru/resources/$slug'
    | '/ru/soz/$slug'
    | '/ru/xeta/$slug'
    | '/tr/apps/$slug'
    | '/tr/faq/$slug'
    | '/tr/movzu/$slug'
    | '/tr/muqayise/$slug'
    | '/tr/nece/$slug'
    | '/tr/programming/$slug'
    | '/tr/soz/$slug'
    | '/tr/xeta/$slug'
    | '/resources/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRouteWithChildren
  MovzuRoute: typeof MovzuRouteWithChildren
  MuqayiseRoute: typeof MuqayiseRouteWithChildren
  NeceRoute: typeof NeceRouteWithChildren
  NxStudioRoute: typeof NxStudioRoute
  PaketRoute: typeof PaketRoute
  PrivacyRoute: typeof PrivacyRouteWithChildren
  SozRoute: typeof SozRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  UnutmaRoute: typeof UnutmaRoute
  WhyRoute: typeof WhyRoute
  XetaRoute: typeof XetaRouteWithChildren
  ResourcesTopicRouteRoute: typeof ResourcesTopicRouteRouteWithChildren
  AppsSlugRoute: typeof AppsSlugRoute
  ArAboutRoute: typeof ArAboutRoute
  ArAppsRoute: typeof ArAppsRouteWithChildren
  ArContactRoute: typeof ArContactRoute
  ArFaqRoute: typeof ArFaqRouteWithChildren
  ArMovzuRoute: typeof ArMovzuRouteWithChildren
  ArMuqayiseRoute: typeof ArMuqayiseRouteWithChildren
  ArNeceRoute: typeof ArNeceRouteWithChildren
  ArPaketRoute: typeof ArPaketRoute
  ArSozRoute: typeof ArSozRouteWithChildren
  ArToolsRoute: typeof ArToolsRoute
  ArXetaRoute: typeof ArXetaRouteWithChildren
  EnAboutRoute: typeof EnAboutRoute
  EnAppsRoute: typeof EnAppsRouteWithChildren
  EnContactRoute: typeof EnContactRoute
  EnFaqRoute: typeof EnFaqRouteWithChildren
  EnMovzuRoute: typeof EnMovzuRouteWithChildren
  EnMuqayiseRoute: typeof EnMuqayiseRouteWithChildren
  EnNeceRoute: typeof EnNeceRouteWithChildren
  EnPaketRoute: typeof EnPaketRoute
  EnSozRoute: typeof EnSozRouteWithChildren
  EnToolsRoute: typeof EnToolsRoute
  EnXetaRoute: typeof EnXetaRouteWithChildren
  GuidesTopicRoute: typeof GuidesTopicRoute
  ProgrammingTopicRoute: typeof ProgrammingTopicRoute
  ResurslarSlugRoute: typeof ResurslarSlugRoute
  RuAboutRoute: typeof RuAboutRoute
  RuAppsRoute: typeof RuAppsRouteWithChildren
  RuContactRoute: typeof RuContactRoute
  RuFaqRoute: typeof RuFaqRouteWithChildren
  RuMovzuRoute: typeof RuMovzuRouteWithChildren
  RuMuqayiseRoute: typeof RuMuqayiseRouteWithChildren
  RuNeceRoute: typeof RuNeceRouteWithChildren
  RuPaketRoute: typeof RuPaketRoute
  RuSozRoute: typeof RuSozRouteWithChildren
  RuToolsRoute: typeof RuToolsRoute
  RuXetaRoute: typeof RuXetaRouteWithChildren
  TrAboutRoute: typeof TrAboutRoute
  TrAppsRoute: typeof TrAppsRouteWithChildren
  TrContactRoute: typeof TrContactRoute
  TrFaqRoute: typeof TrFaqRouteWithChildren
  TrMovzuRoute: typeof TrMovzuRouteWithChildren
  TrMuqayiseRoute: typeof TrMuqayiseRouteWithChildren
  TrNeceRoute: typeof TrNeceRouteWithChildren
  TrPaketRoute: typeof TrPaketRoute
  TrSozRoute: typeof TrSozRouteWithChildren
  TrToolsRoute: typeof TrToolsRoute
  TrXetaRoute: typeof TrXetaRouteWithChildren
  AppsIndexRoute: typeof AppsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ProgrammingIndexRoute: typeof ProgrammingIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ArProgrammingSlugRoute: typeof ArProgrammingSlugRoute
  EnProgrammingSlugRoute: typeof EnProgrammingSlugRoute
  RuProgrammingSlugRoute: typeof RuProgrammingSlugRoute
  RuResourcesSlugRoute: typeof RuResourcesSlugRoute
  TrProgrammingSlugRoute: typeof TrProgrammingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movzu': {
      id: '/movzu'
      path: '/movzu'
      fullPath: '/movzu'
      preLoaderRoute: typeof MovzuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muqayise': {
      id: '/muqayise'
      path: '/muqayise'
      fullPath: '/muqayise'
      preLoaderRoute: typeof MuqayiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nece': {
      id: '/nece'
      path: '/nece'
      fullPath: '/nece'
      preLoaderRoute: typeof NeceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nx-studio': {
      id: '/nx-studio'
      path: '/nx-studio'
      fullPath: '/nx-studio'
      preLoaderRoute: typeof NxStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soz': {
      id: '/soz'
      path: '/soz'
      fullPath: '/soz'
      preLoaderRoute: typeof SozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unutma': {
      id: '/unutma'
      path: '/unutma'
      fullPath: '/unutma'
      preLoaderRoute: typeof UnutmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xeta': {
      id: '/xeta'
      path: '/xeta'
      fullPath: '/xeta'
      preLoaderRoute: typeof XetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/about': {
      id: '/ar/about'
      path: '/ar/about'
      fullPath: '/ar/about'
      preLoaderRoute: typeof ArAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/apps': {
      id: '/ar/apps'
      path: '/ar/apps'
      fullPath: '/ar/apps'
      preLoaderRoute: typeof ArAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/contact': {
      id: '/ar/contact'
      path: '/ar/contact'
      fullPath: '/ar/contact'
      preLoaderRoute: typeof ArContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/faq': {
      id: '/ar/faq'
      path: '/ar/faq'
      fullPath: '/ar/faq'
      preLoaderRoute: typeof ArFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/movzu': {
      id: '/ar/movzu'
      path: '/ar/movzu'
      fullPath: '/ar/movzu'
      preLoaderRoute: typeof ArMovzuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/muqayise': {
      id: '/ar/muqayise'
      path: '/ar/muqayise'
      fullPath: '/ar/muqayise'
      preLoaderRoute: typeof ArMuqayiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/nece': {
      id: '/ar/nece'
      path: '/ar/nece'
      fullPath: '/ar/nece'
      preLoaderRoute: typeof ArNeceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/paket': {
      id: '/ar/paket'
      path: '/ar/paket'
      fullPath: '/ar/paket'
      preLoaderRoute: typeof ArPaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/soz': {
      id: '/ar/soz'
      path: '/ar/soz'
      fullPath: '/ar/soz'
      preLoaderRoute: typeof ArSozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/tools': {
      id: '/ar/tools'
      path: '/ar/tools'
      fullPath: '/ar/tools'
      preLoaderRoute: typeof ArToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/xeta': {
      id: '/ar/xeta'
      path: '/ar/xeta'
      fullPath: '/ar/xeta'
      preLoaderRoute: typeof ArXetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/apps': {
      id: '/en/apps'
      path: '/en/apps'
      fullPath: '/en/apps'
      preLoaderRoute: typeof EnAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/en/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/movzu': {
      id: '/en/movzu'
      path: '/en/movzu'
      fullPath: '/en/movzu'
      preLoaderRoute: typeof EnMovzuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/muqayise': {
      id: '/en/muqayise'
      path: '/en/muqayise'
      fullPath: '/en/muqayise'
      preLoaderRoute: typeof EnMuqayiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/nece': {
      id: '/en/nece'
      path: '/en/nece'
      fullPath: '/en/nece'
      preLoaderRoute: typeof EnNeceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/paket': {
      id: '/en/paket'
      path: '/en/paket'
      fullPath: '/en/paket'
      preLoaderRoute: typeof EnPaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/soz': {
      id: '/en/soz'
      path: '/en/soz'
      fullPath: '/en/soz'
      preLoaderRoute: typeof EnSozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/tools': {
      id: '/en/tools'
      path: '/en/tools'
      fullPath: '/en/tools'
      preLoaderRoute: typeof EnToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/xeta': {
      id: '/en/xeta'
      path: '/en/xeta'
      fullPath: '/en/xeta'
      preLoaderRoute: typeof EnXetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof FaqRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$topic': {
      id: '/guides/$topic'
      path: '/guides/$topic'
      fullPath: '/guides/$topic'
      preLoaderRoute: typeof GuidesTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movzu/$slug': {
      id: '/movzu/$slug'
      path: '/$slug'
      fullPath: '/movzu/$slug'
      preLoaderRoute: typeof MovzuSlugRouteImport
      parentRoute: typeof MovzuRoute
    }
    '/muqayise/$slug': {
      id: '/muqayise/$slug'
      path: '/$slug'
      fullPath: '/muqayise/$slug'
      preLoaderRoute: typeof MuqayiseSlugRouteImport
      parentRoute: typeof MuqayiseRoute
    }
    '/nece/$slug': {
      id: '/nece/$slug'
      path: '/$slug'
      fullPath: '/nece/$slug'
      preLoaderRoute: typeof NeceSlugRouteImport
      parentRoute: typeof NeceRoute
    }
    '/privacy/$slug': {
      id: '/privacy/$slug'
      path: '/$slug'
      fullPath: '/privacy/$slug'
      preLoaderRoute: typeof PrivacySlugRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/privacy/nibras-pdf': {
      id: '/privacy/nibras-pdf'
      path: '/nibras-pdf'
      fullPath: '/privacy/nibras-pdf'
      preLoaderRoute: typeof PrivacyNibrasPdfRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/programming/': {
      id: '/programming/'
      path: '/programming'
      fullPath: '/programming/'
      preLoaderRoute: typeof ProgrammingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programming/$topic': {
      id: '/programming/$topic'
      path: '/programming/$topic'
      fullPath: '/programming/$topic'
      preLoaderRoute: typeof ProgrammingTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$topic': {
      id: '/resources/$topic'
      path: '/resources/$topic'
      fullPath: '/resources/$topic'
      preLoaderRoute: typeof ResourcesTopicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurslar/$slug': {
      id: '/resurslar/$slug'
      path: '/resurslar/$slug'
      fullPath: '/resurslar/$slug'
      preLoaderRoute: typeof ResurslarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/about': {
      id: '/ru/about'
      path: '/ru/about'
      fullPath: '/ru/about'
      preLoaderRoute: typeof RuAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/apps': {
      id: '/ru/apps'
      path: '/ru/apps'
      fullPath: '/ru/apps'
      preLoaderRoute: typeof RuAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/contact': {
      id: '/ru/contact'
      path: '/ru/contact'
      fullPath: '/ru/contact'
      preLoaderRoute: typeof RuContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/faq': {
      id: '/ru/faq'
      path: '/ru/faq'
      fullPath: '/ru/faq'
      preLoaderRoute: typeof RuFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/movzu': {
      id: '/ru/movzu'
      path: '/ru/movzu'
      fullPath: '/ru/movzu'
      preLoaderRoute: typeof RuMovzuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/muqayise': {
      id: '/ru/muqayise'
      path: '/ru/muqayise'
      fullPath: '/ru/muqayise'
      preLoaderRoute: typeof RuMuqayiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/nece': {
      id: '/ru/nece'
      path: '/ru/nece'
      fullPath: '/ru/nece'
      preLoaderRoute: typeof RuNeceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/paket': {
      id: '/ru/paket'
      path: '/ru/paket'
      fullPath: '/ru/paket'
      preLoaderRoute: typeof RuPaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/soz': {
      id: '/ru/soz'
      path: '/ru/soz'
      fullPath: '/ru/soz'
      preLoaderRoute: typeof RuSozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/tools': {
      id: '/ru/tools'
      path: '/ru/tools'
      fullPath: '/ru/tools'
      preLoaderRoute: typeof RuToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/xeta': {
      id: '/ru/xeta'
      path: '/ru/xeta'
      fullPath: '/ru/xeta'
      preLoaderRoute: typeof RuXetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soz/$slug': {
      id: '/soz/$slug'
      path: '/$slug'
      fullPath: '/soz/$slug'
      preLoaderRoute: typeof SozSlugRouteImport
      parentRoute: typeof SozRoute
    }
    '/tr/about': {
      id: '/tr/about'
      path: '/tr/about'
      fullPath: '/tr/about'
      preLoaderRoute: typeof TrAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/apps': {
      id: '/tr/apps'
      path: '/tr/apps'
      fullPath: '/tr/apps'
      preLoaderRoute: typeof TrAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/contact': {
      id: '/tr/contact'
      path: '/tr/contact'
      fullPath: '/tr/contact'
      preLoaderRoute: typeof TrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/faq': {
      id: '/tr/faq'
      path: '/tr/faq'
      fullPath: '/tr/faq'
      preLoaderRoute: typeof TrFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/movzu': {
      id: '/tr/movzu'
      path: '/tr/movzu'
      fullPath: '/tr/movzu'
      preLoaderRoute: typeof TrMovzuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/muqayise': {
      id: '/tr/muqayise'
      path: '/tr/muqayise'
      fullPath: '/tr/muqayise'
      preLoaderRoute: typeof TrMuqayiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/nece': {
      id: '/tr/nece'
      path: '/tr/nece'
      fullPath: '/tr/nece'
      preLoaderRoute: typeof TrNeceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/paket': {
      id: '/tr/paket'
      path: '/tr/paket'
      fullPath: '/tr/paket'
      preLoaderRoute: typeof TrPaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/soz': {
      id: '/tr/soz'
      path: '/tr/soz'
      fullPath: '/tr/soz'
      preLoaderRoute: typeof TrSozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/tools': {
      id: '/tr/tools'
      path: '/tr/tools'
      fullPath: '/tr/tools'
      preLoaderRoute: typeof TrToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/xeta': {
      id: '/tr/xeta'
      path: '/tr/xeta'
      fullPath: '/tr/xeta'
      preLoaderRoute: typeof TrXetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xeta/$slug': {
      id: '/xeta/$slug'
      path: '/$slug'
      fullPath: '/xeta/$slug'
      preLoaderRoute: typeof XetaSlugRouteImport
      parentRoute: typeof XetaRoute
    }
    '/ar/apps/$slug': {
      id: '/ar/apps/$slug'
      path: '/$slug'
      fullPath: '/ar/apps/$slug'
      preLoaderRoute: typeof ArAppsSlugRouteImport
      parentRoute: typeof ArAppsRoute
    }
    '/ar/faq/$slug': {
      id: '/ar/faq/$slug'
      path: '/$slug'
      fullPath: '/ar/faq/$slug'
      preLoaderRoute: typeof ArFaqSlugRouteImport
      parentRoute: typeof ArFaqRoute
    }
    '/ar/movzu/$slug': {
      id: '/ar/movzu/$slug'
      path: '/$slug'
      fullPath: '/ar/movzu/$slug'
      preLoaderRoute: typeof ArMovzuSlugRouteImport
      parentRoute: typeof ArMovzuRoute
    }
    '/ar/muqayise/$slug': {
      id: '/ar/muqayise/$slug'
      path: '/$slug'
      fullPath: '/ar/muqayise/$slug'
      preLoaderRoute: typeof ArMuqayiseSlugRouteImport
      parentRoute: typeof ArMuqayiseRoute
    }
    '/ar/nece/$slug': {
      id: '/ar/nece/$slug'
      path: '/$slug'
      fullPath: '/ar/nece/$slug'
      preLoaderRoute: typeof ArNeceSlugRouteImport
      parentRoute: typeof ArNeceRoute
    }
    '/ar/programming/$slug': {
      id: '/ar/programming/$slug'
      path: '/ar/programming/$slug'
      fullPath: '/ar/programming/$slug'
      preLoaderRoute: typeof ArProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/soz/$slug': {
      id: '/ar/soz/$slug'
      path: '/$slug'
      fullPath: '/ar/soz/$slug'
      preLoaderRoute: typeof ArSozSlugRouteImport
      parentRoute: typeof ArSozRoute
    }
    '/ar/xeta/$slug': {
      id: '/ar/xeta/$slug'
      path: '/$slug'
      fullPath: '/ar/xeta/$slug'
      preLoaderRoute: typeof ArXetaSlugRouteImport
      parentRoute: typeof ArXetaRoute
    }
    '/en/apps/$slug': {
      id: '/en/apps/$slug'
      path: '/$slug'
      fullPath: '/en/apps/$slug'
      preLoaderRoute: typeof EnAppsSlugRouteImport
      parentRoute: typeof EnAppsRoute
    }
    '/en/faq/$slug': {
      id: '/en/faq/$slug'
      path: '/$slug'
      fullPath: '/en/faq/$slug'
      preLoaderRoute: typeof EnFaqSlugRouteImport
      parentRoute: typeof EnFaqRoute
    }
    '/en/movzu/$slug': {
      id: '/en/movzu/$slug'
      path: '/$slug'
      fullPath: '/en/movzu/$slug'
      preLoaderRoute: typeof EnMovzuSlugRouteImport
      parentRoute: typeof EnMovzuRoute
    }
    '/en/muqayise/$slug': {
      id: '/en/muqayise/$slug'
      path: '/$slug'
      fullPath: '/en/muqayise/$slug'
      preLoaderRoute: typeof EnMuqayiseSlugRouteImport
      parentRoute: typeof EnMuqayiseRoute
    }
    '/en/nece/$slug': {
      id: '/en/nece/$slug'
      path: '/$slug'
      fullPath: '/en/nece/$slug'
      preLoaderRoute: typeof EnNeceSlugRouteImport
      parentRoute: typeof EnNeceRoute
    }
    '/en/programming/$slug': {
      id: '/en/programming/$slug'
      path: '/en/programming/$slug'
      fullPath: '/en/programming/$slug'
      preLoaderRoute: typeof EnProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/soz/$slug': {
      id: '/en/soz/$slug'
      path: '/$slug'
      fullPath: '/en/soz/$slug'
      preLoaderRoute: typeof EnSozSlugRouteImport
      parentRoute: typeof EnSozRoute
    }
    '/en/xeta/$slug': {
      id: '/en/xeta/$slug'
      path: '/$slug'
      fullPath: '/en/xeta/$slug'
      preLoaderRoute: typeof EnXetaSlugRouteImport
      parentRoute: typeof EnXetaRoute
    }
    '/resources/$topic/': {
      id: '/resources/$topic/'
      path: '/'
      fullPath: '/resources/$topic/'
      preLoaderRoute: typeof ResourcesTopicIndexRouteImport
      parentRoute: typeof ResourcesTopicRouteRoute
    }
    '/resources/$topic/$article': {
      id: '/resources/$topic/$article'
      path: '/$article'
      fullPath: '/resources/$topic/$article'
      preLoaderRoute: typeof ResourcesTopicArticleRouteImport
      parentRoute: typeof ResourcesTopicRouteRoute
    }
    '/ru/apps/$slug': {
      id: '/ru/apps/$slug'
      path: '/$slug'
      fullPath: '/ru/apps/$slug'
      preLoaderRoute: typeof RuAppsSlugRouteImport
      parentRoute: typeof RuAppsRoute
    }
    '/ru/faq/$slug': {
      id: '/ru/faq/$slug'
      path: '/$slug'
      fullPath: '/ru/faq/$slug'
      preLoaderRoute: typeof RuFaqSlugRouteImport
      parentRoute: typeof RuFaqRoute
    }
    '/ru/movzu/$slug': {
      id: '/ru/movzu/$slug'
      path: '/$slug'
      fullPath: '/ru/movzu/$slug'
      preLoaderRoute: typeof RuMovzuSlugRouteImport
      parentRoute: typeof RuMovzuRoute
    }
    '/ru/muqayise/$slug': {
      id: '/ru/muqayise/$slug'
      path: '/$slug'
      fullPath: '/ru/muqayise/$slug'
      preLoaderRoute: typeof RuMuqayiseSlugRouteImport
      parentRoute: typeof RuMuqayiseRoute
    }
    '/ru/nece/$slug': {
      id: '/ru/nece/$slug'
      path: '/$slug'
      fullPath: '/ru/nece/$slug'
      preLoaderRoute: typeof RuNeceSlugRouteImport
      parentRoute: typeof RuNeceRoute
    }
    '/ru/programming/$slug': {
      id: '/ru/programming/$slug'
      path: '/ru/programming/$slug'
      fullPath: '/ru/programming/$slug'
      preLoaderRoute: typeof RuProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/resources/$slug': {
      id: '/ru/resources/$slug'
      path: '/ru/resources/$slug'
      fullPath: '/ru/resources/$slug'
      preLoaderRoute: typeof RuResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/soz/$slug': {
      id: '/ru/soz/$slug'
      path: '/$slug'
      fullPath: '/ru/soz/$slug'
      preLoaderRoute: typeof RuSozSlugRouteImport
      parentRoute: typeof RuSozRoute
    }
    '/ru/xeta/$slug': {
      id: '/ru/xeta/$slug'
      path: '/$slug'
      fullPath: '/ru/xeta/$slug'
      preLoaderRoute: typeof RuXetaSlugRouteImport
      parentRoute: typeof RuXetaRoute
    }
    '/tr/apps/$slug': {
      id: '/tr/apps/$slug'
      path: '/$slug'
      fullPath: '/tr/apps/$slug'
      preLoaderRoute: typeof TrAppsSlugRouteImport
      parentRoute: typeof TrAppsRoute
    }
    '/tr/faq/$slug': {
      id: '/tr/faq/$slug'
      path: '/$slug'
      fullPath: '/tr/faq/$slug'
      preLoaderRoute: typeof TrFaqSlugRouteImport
      parentRoute: typeof TrFaqRoute
    }
    '/tr/movzu/$slug': {
      id: '/tr/movzu/$slug'
      path: '/$slug'
      fullPath: '/tr/movzu/$slug'
      preLoaderRoute: typeof TrMovzuSlugRouteImport
      parentRoute: typeof TrMovzuRoute
    }
    '/tr/muqayise/$slug': {
      id: '/tr/muqayise/$slug'
      path: '/$slug'
      fullPath: '/tr/muqayise/$slug'
      preLoaderRoute: typeof TrMuqayiseSlugRouteImport
      parentRoute: typeof TrMuqayiseRoute
    }
    '/tr/nece/$slug': {
      id: '/tr/nece/$slug'
      path: '/$slug'
      fullPath: '/tr/nece/$slug'
      preLoaderRoute: typeof TrNeceSlugRouteImport
      parentRoute: typeof TrNeceRoute
    }
    '/tr/programming/$slug': {
      id: '/tr/programming/$slug'
      path: '/tr/programming/$slug'
      fullPath: '/tr/programming/$slug'
      preLoaderRoute: typeof TrProgrammingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/soz/$slug': {
      id: '/tr/soz/$slug'
      path: '/$slug'
      fullPath: '/tr/soz/$slug'
      preLoaderRoute: typeof TrSozSlugRouteImport
      parentRoute: typeof TrSozRoute
    }
    '/tr/xeta/$slug': {
      id: '/tr/xeta/$slug'
      path: '/$slug'
      fullPath: '/tr/xeta/$slug'
      preLoaderRoute: typeof TrXetaSlugRouteImport
      parentRoute: typeof TrXetaRoute
    }
  }
}

interface FaqRouteChildren {
  FaqSlugRoute: typeof FaqSlugRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqSlugRoute: FaqSlugRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

interface MovzuRouteChildren {
  MovzuSlugRoute: typeof MovzuSlugRoute
}

const MovzuRouteChildren: MovzuRouteChildren = {
  MovzuSlugRoute: MovzuSlugRoute,
}

const MovzuRouteWithChildren = MovzuRoute._addFileChildren(MovzuRouteChildren)

interface MuqayiseRouteChildren {
  MuqayiseSlugRoute: typeof MuqayiseSlugRoute
}

const MuqayiseRouteChildren: MuqayiseRouteChildren = {
  MuqayiseSlugRoute: MuqayiseSlugRoute,
}

const MuqayiseRouteWithChildren = MuqayiseRoute._addFileChildren(
  MuqayiseRouteChildren,
)

interface NeceRouteChildren {
  NeceSlugRoute: typeof NeceSlugRoute
}

const NeceRouteChildren: NeceRouteChildren = {
  NeceSlugRoute: NeceSlugRoute,
}

const NeceRouteWithChildren = NeceRoute._addFileChildren(NeceRouteChildren)

interface PrivacyRouteChildren {
  PrivacySlugRoute: typeof PrivacySlugRoute
  PrivacyNibrasPdfRoute: typeof PrivacyNibrasPdfRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacySlugRoute: PrivacySlugRoute,
  PrivacyNibrasPdfRoute: PrivacyNibrasPdfRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

interface SozRouteChildren {
  SozSlugRoute: typeof SozSlugRoute
}

const SozRouteChildren: SozRouteChildren = {
  SozSlugRoute: SozSlugRoute,
}

const SozRouteWithChildren = SozRoute._addFileChildren(SozRouteChildren)

interface XetaRouteChildren {
  XetaSlugRoute: typeof XetaSlugRoute
}

const XetaRouteChildren: XetaRouteChildren = {
  XetaSlugRoute: XetaSlugRoute,
}

const XetaRouteWithChildren = XetaRoute._addFileChildren(XetaRouteChildren)

interface ResourcesTopicRouteRouteChildren {
  ResourcesTopicArticleRoute: typeof ResourcesTopicArticleRoute
  ResourcesTopicIndexRoute: typeof ResourcesTopicIndexRoute
}

const ResourcesTopicRouteRouteChildren: ResourcesTopicRouteRouteChildren = {
  ResourcesTopicArticleRoute: ResourcesTopicArticleRoute,
  ResourcesTopicIndexRoute: ResourcesTopicIndexRoute,
}

const ResourcesTopicRouteRouteWithChildren =
  ResourcesTopicRouteRoute._addFileChildren(ResourcesTopicRouteRouteChildren)

interface ArAppsRouteChildren {
  ArAppsSlugRoute: typeof ArAppsSlugRoute
}

const ArAppsRouteChildren: ArAppsRouteChildren = {
  ArAppsSlugRoute: ArAppsSlugRoute,
}

const ArAppsRouteWithChildren =
  ArAppsRoute._addFileChildren(ArAppsRouteChildren)

interface ArFaqRouteChildren {
  ArFaqSlugRoute: typeof ArFaqSlugRoute
}

const ArFaqRouteChildren: ArFaqRouteChildren = {
  ArFaqSlugRoute: ArFaqSlugRoute,
}

const ArFaqRouteWithChildren = ArFaqRoute._addFileChildren(ArFaqRouteChildren)

interface ArMovzuRouteChildren {
  ArMovzuSlugRoute: typeof ArMovzuSlugRoute
}

const ArMovzuRouteChildren: ArMovzuRouteChildren = {
  ArMovzuSlugRoute: ArMovzuSlugRoute,
}

const ArMovzuRouteWithChildren =
  ArMovzuRoute._addFileChildren(ArMovzuRouteChildren)

interface ArMuqayiseRouteChildren {
  ArMuqayiseSlugRoute: typeof ArMuqayiseSlugRoute
}

const ArMuqayiseRouteChildren: ArMuqayiseRouteChildren = {
  ArMuqayiseSlugRoute: ArMuqayiseSlugRoute,
}

const ArMuqayiseRouteWithChildren = ArMuqayiseRoute._addFileChildren(
  ArMuqayiseRouteChildren,
)

interface ArNeceRouteChildren {
  ArNeceSlugRoute: typeof ArNeceSlugRoute
}

const ArNeceRouteChildren: ArNeceRouteChildren = {
  ArNeceSlugRoute: ArNeceSlugRoute,
}

const ArNeceRouteWithChildren =
  ArNeceRoute._addFileChildren(ArNeceRouteChildren)

interface ArSozRouteChildren {
  ArSozSlugRoute: typeof ArSozSlugRoute
}

const ArSozRouteChildren: ArSozRouteChildren = {
  ArSozSlugRoute: ArSozSlugRoute,
}

const ArSozRouteWithChildren = ArSozRoute._addFileChildren(ArSozRouteChildren)

interface ArXetaRouteChildren {
  ArXetaSlugRoute: typeof ArXetaSlugRoute
}

const ArXetaRouteChildren: ArXetaRouteChildren = {
  ArXetaSlugRoute: ArXetaSlugRoute,
}

const ArXetaRouteWithChildren =
  ArXetaRoute._addFileChildren(ArXetaRouteChildren)

interface EnAppsRouteChildren {
  EnAppsSlugRoute: typeof EnAppsSlugRoute
}

const EnAppsRouteChildren: EnAppsRouteChildren = {
  EnAppsSlugRoute: EnAppsSlugRoute,
}

const EnAppsRouteWithChildren =
  EnAppsRoute._addFileChildren(EnAppsRouteChildren)

interface EnFaqRouteChildren {
  EnFaqSlugRoute: typeof EnFaqSlugRoute
}

const EnFaqRouteChildren: EnFaqRouteChildren = {
  EnFaqSlugRoute: EnFaqSlugRoute,
}

const EnFaqRouteWithChildren = EnFaqRoute._addFileChildren(EnFaqRouteChildren)

interface EnMovzuRouteChildren {
  EnMovzuSlugRoute: typeof EnMovzuSlugRoute
}

const EnMovzuRouteChildren: EnMovzuRouteChildren = {
  EnMovzuSlugRoute: EnMovzuSlugRoute,
}

const EnMovzuRouteWithChildren =
  EnMovzuRoute._addFileChildren(EnMovzuRouteChildren)

interface EnMuqayiseRouteChildren {
  EnMuqayiseSlugRoute: typeof EnMuqayiseSlugRoute
}

const EnMuqayiseRouteChildren: EnMuqayiseRouteChildren = {
  EnMuqayiseSlugRoute: EnMuqayiseSlugRoute,
}

const EnMuqayiseRouteWithChildren = EnMuqayiseRoute._addFileChildren(
  EnMuqayiseRouteChildren,
)

interface EnNeceRouteChildren {
  EnNeceSlugRoute: typeof EnNeceSlugRoute
}

const EnNeceRouteChildren: EnNeceRouteChildren = {
  EnNeceSlugRoute: EnNeceSlugRoute,
}

const EnNeceRouteWithChildren =
  EnNeceRoute._addFileChildren(EnNeceRouteChildren)

interface EnSozRouteChildren {
  EnSozSlugRoute: typeof EnSozSlugRoute
}

const EnSozRouteChildren: EnSozRouteChildren = {
  EnSozSlugRoute: EnSozSlugRoute,
}

const EnSozRouteWithChildren = EnSozRoute._addFileChildren(EnSozRouteChildren)

interface EnXetaRouteChildren {
  EnXetaSlugRoute: typeof EnXetaSlugRoute
}

const EnXetaRouteChildren: EnXetaRouteChildren = {
  EnXetaSlugRoute: EnXetaSlugRoute,
}

const EnXetaRouteWithChildren =
  EnXetaRoute._addFileChildren(EnXetaRouteChildren)

interface RuAppsRouteChildren {
  RuAppsSlugRoute: typeof RuAppsSlugRoute
}

const RuAppsRouteChildren: RuAppsRouteChildren = {
  RuAppsSlugRoute: RuAppsSlugRoute,
}

const RuAppsRouteWithChildren =
  RuAppsRoute._addFileChildren(RuAppsRouteChildren)

interface RuFaqRouteChildren {
  RuFaqSlugRoute: typeof RuFaqSlugRoute
}

const RuFaqRouteChildren: RuFaqRouteChildren = {
  RuFaqSlugRoute: RuFaqSlugRoute,
}

const RuFaqRouteWithChildren = RuFaqRoute._addFileChildren(RuFaqRouteChildren)

interface RuMovzuRouteChildren {
  RuMovzuSlugRoute: typeof RuMovzuSlugRoute
}

const RuMovzuRouteChildren: RuMovzuRouteChildren = {
  RuMovzuSlugRoute: RuMovzuSlugRoute,
}

const RuMovzuRouteWithChildren =
  RuMovzuRoute._addFileChildren(RuMovzuRouteChildren)

interface RuMuqayiseRouteChildren {
  RuMuqayiseSlugRoute: typeof RuMuqayiseSlugRoute
}

const RuMuqayiseRouteChildren: RuMuqayiseRouteChildren = {
  RuMuqayiseSlugRoute: RuMuqayiseSlugRoute,
}

const RuMuqayiseRouteWithChildren = RuMuqayiseRoute._addFileChildren(
  RuMuqayiseRouteChildren,
)

interface RuNeceRouteChildren {
  RuNeceSlugRoute: typeof RuNeceSlugRoute
}

const RuNeceRouteChildren: RuNeceRouteChildren = {
  RuNeceSlugRoute: RuNeceSlugRoute,
}

const RuNeceRouteWithChildren =
  RuNeceRoute._addFileChildren(RuNeceRouteChildren)

interface RuSozRouteChildren {
  RuSozSlugRoute: typeof RuSozSlugRoute
}

const RuSozRouteChildren: RuSozRouteChildren = {
  RuSozSlugRoute: RuSozSlugRoute,
}

const RuSozRouteWithChildren = RuSozRoute._addFileChildren(RuSozRouteChildren)

interface RuXetaRouteChildren {
  RuXetaSlugRoute: typeof RuXetaSlugRoute
}

const RuXetaRouteChildren: RuXetaRouteChildren = {
  RuXetaSlugRoute: RuXetaSlugRoute,
}

const RuXetaRouteWithChildren =
  RuXetaRoute._addFileChildren(RuXetaRouteChildren)

interface TrAppsRouteChildren {
  TrAppsSlugRoute: typeof TrAppsSlugRoute
}

const TrAppsRouteChildren: TrAppsRouteChildren = {
  TrAppsSlugRoute: TrAppsSlugRoute,
}

const TrAppsRouteWithChildren =
  TrAppsRoute._addFileChildren(TrAppsRouteChildren)

interface TrFaqRouteChildren {
  TrFaqSlugRoute: typeof TrFaqSlugRoute
}

const TrFaqRouteChildren: TrFaqRouteChildren = {
  TrFaqSlugRoute: TrFaqSlugRoute,
}

const TrFaqRouteWithChildren = TrFaqRoute._addFileChildren(TrFaqRouteChildren)

interface TrMovzuRouteChildren {
  TrMovzuSlugRoute: typeof TrMovzuSlugRoute
}

const TrMovzuRouteChildren: TrMovzuRouteChildren = {
  TrMovzuSlugRoute: TrMovzuSlugRoute,
}

const TrMovzuRouteWithChildren =
  TrMovzuRoute._addFileChildren(TrMovzuRouteChildren)

interface TrMuqayiseRouteChildren {
  TrMuqayiseSlugRoute: typeof TrMuqayiseSlugRoute
}

const TrMuqayiseRouteChildren: TrMuqayiseRouteChildren = {
  TrMuqayiseSlugRoute: TrMuqayiseSlugRoute,
}

const TrMuqayiseRouteWithChildren = TrMuqayiseRoute._addFileChildren(
  TrMuqayiseRouteChildren,
)

interface TrNeceRouteChildren {
  TrNeceSlugRoute: typeof TrNeceSlugRoute
}

const TrNeceRouteChildren: TrNeceRouteChildren = {
  TrNeceSlugRoute: TrNeceSlugRoute,
}

const TrNeceRouteWithChildren =
  TrNeceRoute._addFileChildren(TrNeceRouteChildren)

interface TrSozRouteChildren {
  TrSozSlugRoute: typeof TrSozSlugRoute
}

const TrSozRouteChildren: TrSozRouteChildren = {
  TrSozSlugRoute: TrSozSlugRoute,
}

const TrSozRouteWithChildren = TrSozRoute._addFileChildren(TrSozRouteChildren)

interface TrXetaRouteChildren {
  TrXetaSlugRoute: typeof TrXetaSlugRoute
}

const TrXetaRouteChildren: TrXetaRouteChildren = {
  TrXetaSlugRoute: TrXetaSlugRoute,
}

const TrXetaRouteWithChildren =
  TrXetaRoute._addFileChildren(TrXetaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRouteWithChildren,
  MovzuRoute: MovzuRouteWithChildren,
  MuqayiseRoute: MuqayiseRouteWithChildren,
  NeceRoute: NeceRouteWithChildren,
  NxStudioRoute: NxStudioRoute,
  PaketRoute: PaketRoute,
  PrivacyRoute: PrivacyRouteWithChildren,
  SozRoute: SozRouteWithChildren,
  ToolsRoute: ToolsRoute,
  UnutmaRoute: UnutmaRoute,
  WhyRoute: WhyRoute,
  XetaRoute: XetaRouteWithChildren,
  ResourcesTopicRouteRoute: ResourcesTopicRouteRouteWithChildren,
  AppsSlugRoute: AppsSlugRoute,
  ArAboutRoute: ArAboutRoute,
  ArAppsRoute: ArAppsRouteWithChildren,
  ArContactRoute: ArContactRoute,
  ArFaqRoute: ArFaqRouteWithChildren,
  ArMovzuRoute: ArMovzuRouteWithChildren,
  ArMuqayiseRoute: ArMuqayiseRouteWithChildren,
  ArNeceRoute: ArNeceRouteWithChildren,
  ArPaketRoute: ArPaketRoute,
  ArSozRoute: ArSozRouteWithChildren,
  ArToolsRoute: ArToolsRoute,
  ArXetaRoute: ArXetaRouteWithChildren,
  EnAboutRoute: EnAboutRoute,
  EnAppsRoute: EnAppsRouteWithChildren,
  EnContactRoute: EnContactRoute,
  EnFaqRoute: EnFaqRouteWithChildren,
  EnMovzuRoute: EnMovzuRouteWithChildren,
  EnMuqayiseRoute: EnMuqayiseRouteWithChildren,
  EnNeceRoute: EnNeceRouteWithChildren,
  EnPaketRoute: EnPaketRoute,
  EnSozRoute: EnSozRouteWithChildren,
  EnToolsRoute: EnToolsRoute,
  EnXetaRoute: EnXetaRouteWithChildren,
  GuidesTopicRoute: GuidesTopicRoute,
  ProgrammingTopicRoute: ProgrammingTopicRoute,
  ResurslarSlugRoute: ResurslarSlugRoute,
  RuAboutRoute: RuAboutRoute,
  RuAppsRoute: RuAppsRouteWithChildren,
  RuContactRoute: RuContactRoute,
  RuFaqRoute: RuFaqRouteWithChildren,
  RuMovzuRoute: RuMovzuRouteWithChildren,
  RuMuqayiseRoute: RuMuqayiseRouteWithChildren,
  RuNeceRoute: RuNeceRouteWithChildren,
  RuPaketRoute: RuPaketRoute,
  RuSozRoute: RuSozRouteWithChildren,
  RuToolsRoute: RuToolsRoute,
  RuXetaRoute: RuXetaRouteWithChildren,
  TrAboutRoute: TrAboutRoute,
  TrAppsRoute: TrAppsRouteWithChildren,
  TrContactRoute: TrContactRoute,
  TrFaqRoute: TrFaqRouteWithChildren,
  TrMovzuRoute: TrMovzuRouteWithChildren,
  TrMuqayiseRoute: TrMuqayiseRouteWithChildren,
  TrNeceRoute: TrNeceRouteWithChildren,
  TrPaketRoute: TrPaketRoute,
  TrSozRoute: TrSozRouteWithChildren,
  TrToolsRoute: TrToolsRoute,
  TrXetaRoute: TrXetaRouteWithChildren,
  AppsIndexRoute: AppsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ProgrammingIndexRoute: ProgrammingIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ArProgrammingSlugRoute: ArProgrammingSlugRoute,
  EnProgrammingSlugRoute: EnProgrammingSlugRoute,
  RuProgrammingSlugRoute: RuProgrammingSlugRoute,
  RuResourcesSlugRoute: RuResourcesSlugRoute,
  TrProgrammingSlugRoute: TrProgrammingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
