// Tövhid 1 (Əqidə 3001): hazır cavab kitabxanasının mənbə təsviri.
//
// Bu fayl ar.txt / az.txt-dən hansı bloku götürməyi və hansı suallara uyğunlaşdırmağı bildirir.
// Dəyişiklikdən sonra:  node scripts/build-tawhid.mjs   (api/_tawhid/entries.js yenidən yaranır)
//
// ar / az sahəsi:
//   {q:N}                      -> mövzu daxilində N-ci sualın bütün cavabı (sual sətri daxil deyil)
//   {q:N, from:"..", to:".."}  -> həmin sualın cavabından alt bölmə: «from» ilə başlayan sətirdən (daxil),
//                                 «to» ilə başlayan sətrə qədər (daxil deyil). «to» yoxdursa sualın sonuna qədər.
//   az: null                   -> tərcümə hələ yoxdur (cavab ərəbcə verilir)
//   partial: true              -> az tərcümə var, amma tam deyil (tam olduqda bu sahəni silin)
// core: hamısı mütləq olmalı olan söz qrupları ("|" ilə alternativlər, ən azı bir hissə uyğun gəlməlidir)
// opt: əlavə bal verən qruplar; not: bu qruplardan biri varsa bu giriş seçilmir
// amb: eyni amb nişanlı iki giriş bərabər bal alsa, hər ikisi göstərilir
// ask: true -> mesajda sual işarəsi / sual sözü olmalıdır
// trig: [az[], tr[], ar[]] təbii sual ifadələri (uyğunlaşdırmada bal artırır)

export const G = {
  ALLAH: "allah|الله|لله",
  RUB: "rübubiyy|rububiy|rububi|ربوب",
  TOV: "tövhid|tevhid|tavhid|tauhid|توحيد",
  SIRK: "şirk|شرك",
  QISM: "qism|bölün|ayrıl|ayril|növ$|növü|növləri|kısım|çeşit|أقسام|قسم|أنواع|نوع|تنقسم|تقسيم",
  DEF: "tərif|terif|nədir|nedir|demək|demek|mənası|menasi|mənasını|mənası|anlam|izah|مفهوم|تعريف|عرف|معنى|ما$|هو$|هي$",
  DELIL: "dəlil|delil|ədillə|أدلة|دليل|برهان|kanıt",
  HOKM: "hökm|hüküm$|hükmü|hukm|əhkam|ehkam|أحكام|حكم",
  BOYUK: "böyük|büyük|ekber|əkbər|أكبر",
  KICIK: "kiçik|küçük|esğer|əsğər|أصغر",
  SERI: "şəri|şeri|شرعي|شرعية|شرعيه",
  FITRI: "fitri|fıtri|fitrət|fitret|fıtrat|فطري|فطرية|فطرة",
  AQLI: "əqli|akli|aklî|عقلي|عقلية",
  NEQLI: "nəqli|nakli|naklî|نقلي|نقلية|səm'i|semi|سمعي|سمعية",
  YARAD: "yarad|yarat|xaliq|xalik|haliq|xaliq|xalq$|خالق|خلق|احداث|أحدث|محدث|ihdas|ehdas",
  VAR: "varlığ|varlıq|varlig|mövcud|movcud|vücud|وجود",
  KAINAT: "kainat|kâinat|evren|كون|aləm$|alem$",
  INSAN: "insan|bəşər|beşer|إنسان|انسان|بشر",
  ESMA: "əsma|esma|asma|isim|ad$|adı$|adları|adlar$|adlarını|اسماء|أسماء|اسم",
  SIF: "sifət|sifet|sifat|صفة|صفات",
  QAYDA: "qayda|kaide|kaid|قاعدة|قواعد",
  TEVQIF: "təvqif|tevkif|tevqif|tavkif|tawqif|توقيف",
  GOZEL: "gözəl|gozel|güzel|hüsn|husn|hesen|حسنى|حسن",
  IMAN: "iman|inan|إيمان|ايمان|يؤمن",
  MEREFE: "mərifət|marifet|merifet|marifat|معرفة",
  ISBAT: "isbat|ispat|isbat|إثبات|اثبات",
  TETIL: "tətil$|tetil$|tətili|tatil$|ta'til|taetil|تعطيل",
  TEMSIL: "təmsil|temsil|tamsil|tamthil|تمثيل",
  ZATI: "zati$|ذاتية|ذاتي",
  FEILI: "feili$|fe'li$|fiili$|فعلية|فعلي",
  ELMI: "elmi$|ilmi|علمي",
  XEBERI: "xəbəri|haberi|xeberi|خبري",
  SEBEB: "səbəb|sebeb|niyə|niye|neden|nicin|nə üçün|why|adlan|anıl|لماذا|سبب|تسمية",
  IHSA: "ihsa|ehsa|إحصاء|احصاء",
  DUA: "dua$|duanın|duanin|duaları|دعاء",
  MENFI: "mənfi|menfi|منفية|منفي|inkar",
  SUBUTI: "sübuti|subuti|ثبوتية|ثبوتي",
  TESDIQ: "təsdiq|tesdiq|inkar|isbat|ثبوت|نفي|إثبات",
  FEL: "fel$|fellər|feller|fəl$|fiiller|fiilleri|fiil$|fi'l$|أفعال|فعل",
  KECIS: "keçişli|keçişsiz|geçişli|geçişsiz|kecisli|kecissiz|لازم|متعد|متعدي",
  TESIR: "təsir|tesir|əsər|eser|etki|آثار|ثمرة|fayda",
  USUL: "əsas|prinsip|usul$|usullar|اصول|أصول|أسس",
  LEYSE: "leyse|leysə|kəmislihi|kemislihi|ليس كمثله|كمثله",
  MUCMEL: "mücməl|mucmel|müfəssəl|mufessel|ümumi|təfsilatlı|tefsilatli|مجمل|مفصل|المجمل|المفصل|إجمالي",
  AYE: "ayə|aye|ayet|ayede|ayədə|آية|اية|آيه",
  QB: "qism|bölün|ayrıl|ayril|növ$|növü|növləri|kısım|çeşit|أقسام|قسم|أنواع|نوع|تنقسم|تقسيم|böyük|büyük|kiçik|küçük|أكبر|أصغر",
};

const T = (az = [], tr = [], ar = []) => ({ az, tr, ar });

export const TOPIC_TITLES_FALLBACK = {
  // az.txt-də başlığı olmayan mövzular üçün naviqasiya başlığı (tərcümə deyil, qısa ad)
  3: "Mərifət və isbat tövhidinin mənası və növləri",
  4: "Rübubiyyət tövhidinin tərifi, dəlilləri və Quranın onu bəyan etmə metodu",
  9: "Əhli-sünnə vəl-cəmaatın Allahın sifətləri ilə bağlı qaydaları",
  10: "Quran və sünnədə gələn bəzi Allah adları və onları ihsa etmənin mənası",
};
export const TOPIC_AR_FALLBACK = { 1: "توحيد الربوبية وأدلته" };

export const META = [
  // ---------------- 1-ci mövzu ----------------
  { id: "t1-iman-umur", t: 1, label: "Rübubiyyət tövhidini gerçəkləşdirmək üçün iman edilməli məsələlər", ar: { q: 1 }, az: { q: 1 }, partial: true,
    core: [G.RUB, "gerçəkləşd|gerceklesd|gerçəkləş|tətbiq|tehqiq|tahqiq|muhakkak|محقق|تحقيق|يحقق|يلزم|lazım|vacib|şərt|məsələ|mesele|امور|أمور|edilməli|edilmeli"], opt: [G.IMAN, G.TOV],
    trig: T(["Rübubiyyət tövhidini gerçəkləşdirmək üçün nələrə iman etmək lazımdır", "Möminin rübubiyyət tövhidini gerçəkləşdirməsi üçün hansı məsələlərə inanması vacibdir", "Rübubiyyət tövhidi üçün iman edilməli məsələlər"], ["Rububiyet tevhidini gerçekleştirmek için nelere iman etmek gerekir"], ["ما الأمور التي يلزم المؤمن لتحقيق توحيد الربوبية", "عدد أمور توحيد الربوبية"]) },
  { id: "t1-delil-novleri", t: 1, label: "Allahın varlığına dəlillər və onların növləri", ar: { q: 2 }, az: null,
    core: [G.ALLAH, G.VAR, G.DELIL], opt: [G.QISM], not: [G.FITRI, G.AQLI, G.SERI],
    trig: T(["Allahın varlığına dəlillər", "Allahın varlığının dəlilləri neçə növdür", "Allahın mövcudluğuna dəlillər nələrdir"], ["Allah'ın varlığının delilleri nelerdir", "Allah'ın varlığına deliller kaç çeşit"], ["أدلة وجود الله", "ما هي أدلة وجود الله"]) },
  { id: "t1-sheri-delil", t: 1, label: "Allahın varlığına şəri dəlillər", ar: { q: 2, from: "(1) الأدلة الشرعية", to: "(٢) الأدلة الفطرية" }, az: null,
    core: [G.DELIL, G.SERI], opt: [G.ALLAH, G.VAR],
    trig: T(["Şəri dəlillər nədir", "Allahın varlığına şəri dəlil"], ["Allah'ın varlığına şer'i deliller"], ["الأدلة الشرعية على وجود الله"]) },
  { id: "t1-fitri-delil", t: 1, label: "Allahın varlığına fitri dəlillər", amb: "fitri", ar: { q: 2, from: "(٢) الأدلة الفطرية", to: "(٣) الأدلة العقلية" }, az: null,
    core: [G.FITRI, G.DELIL], opt: [G.ALLAH, G.VAR, "imtahan|bəla|sıxıntı|müsibət|şiddət"],
    trig: T(["Fitri dəlil nədir", "Allahın varlığına fitri dəlil", "Fitrət dəlili nədir"], ["Fıtrî delil nedir", "Allah'ın varlığına fıtrat delili"], ["الأدلة الفطرية على وجود الله", "الدليل الفطري"]) },
  { id: "t1-aqli-delil", t: 1, label: "Allahın varlığına əqli dəlillər", amb: "aqli", ar: { q: 2, from: "(٣) الأدلة العقلية" }, az: null,
    core: [G.AQLI, G.DELIL], opt: [G.ALLAH, G.VAR], not: [G.YARAD],
    trig: T(["Əqli dəlil nədir", "Allahın varlığına əqli dəlillər"], ["Aklî deliller nedir", "Allah'ın varlığına akli deliller"], ["الأدلة العقلية على وجود الله", "الدليل العقلي"]) },
  { id: "t1-xalq-icad", t: 1, label: "Xəlq və icad (yaradılış) dəlili", ar: { q: 2, from: "دليل الخلق والإيجاد", to: "دليل الإحكام والإتقان" }, az: null,
    core: [G.DELIL, "icad|xəlq|xelk|إيجاد|ايجاد|yaradılış|yaradilis|خلق"], opt: [G.ALLAH],
    trig: T(["Xəlq və icad dəlili nədir", "Yaradılış dəlili nədir"], ["Yaratılış ve icad delili nedir"], ["دليل الخلق والإيجاد"]) },
  { id: "t1-ihkam-itqan", t: 1, label: "İhkam və itqan (mükəmməl nizam) dəlili", ar: { q: 2, from: "دليل الإحكام والإتقان" }, az: null,
    core: [G.DELIL, "ihkam|itqan|ithkam|mükəmməl|nizam|إحكام|احكام|إتقان|اتقان"], opt: [G.ALLAH],
    trig: T(["İhkam və itqan dəlili nədir", "Kainatdakı mükəmməl nizam dəlili"], ["İhkam ve itkan delili nedir"], ["دليل الإحكام والإتقان"]) },

  // ---------------- 2-ci mövzu ----------------
  { id: "t2-kainat-kim", t: 2, label: "Kainat sonradan yaranıbsa, onu kim yaradıb?", ar: { q: 1 }, az: { q: 1 }, partial: true, ask: true,
    core: [G.KAINAT, G.YARAD], opt: ["öz-özünü|özünü|ozunu|nefsini|ehtimal|ihtimal|sonradan|hadis|حادث"],
    trig: T(["Kainat sonradan yaranıbsa onu kim yaradıb", "Kainatı kim yaradıb", "Kainat özünü özü yarada bilərmi"], ["Kâinat sonradan olduysa onu kim yarattı", "Evreni kim yarattı"], ["إذا كان الكون حادثا فمن أحدثه", "من خلق الكون"]) },
  { id: "t2-insan-yaradici", t: 2, label: "Quranda insanın yaradıcısı olduğuna əqli dəlil", ar: { q: 2 }, az: null,
    core: [G.INSAN, G.YARAD, G.DELIL], opt: [G.AQLI, "tur|الطور|quran"],
    trig: T(["İnsanın yaradıcısı olduğuna Qurandakı əqli dəlil", "İnsan yaradıcısız yarana bilərmi dəlil"], ["İnsanın yaratıcısı olduğuna Kur'an'daki akli delil"], ["الدليل العقلي في القرآن على أن للإنسان خالقا"]) },
  { id: "t2-aqli-yaradici", t: 2, label: "Allahın yaradıcı olduğuna əqli dəlillər", ar: { q: 3 }, az: null,
    core: [G.YARAD, G.AQLI, G.DELIL], opt: [G.ALLAH, G.VAR, "qəsr|saray|bədəvi|bedevi"],
    trig: T(["Allahın kainatın yaradıcısı olduğuna əqli dəlillər", "Allahın yaradıcı olduğuna əqli dəlil gətir"], ["Allah'ın yaratıcı olduğuna akli deliller"], ["أدلة عقلية على وجود الله وأنه الخالق"]) },

  // ---------------- 3-cü mövzu ----------------
  { id: "t3-tovhid-qismleri", t: 3, label: "Tövhidin qisimləri (üç növ)", ar: { q: 1 }, az: null,
    core: [G.TOV, G.QISM], not: [G.SIRK, G.MEREFE, G.ISBAT, "peyğəmbər|peygamber|rəsul|resul|رسل", G.RUB, G.SIF, G.ESMA, G.DELIL, G.QAYDA, G.ELMI, G.AYE],
    trig: T(["Tövhidin növləri", "Tövhid neçə qismə bölünür", "Tövhidin üç növü nədir"], ["Tevhidin çeşitleri nelerdir", "Tevhid kaça ayrılır"], ["أقسام التوحيد", "عدد أقسام التوحيد"]) },
  { id: "t3-uc-tovhid-bir-ayede", t: 3, label: "Üç tövhidi bir ayədə cəm edən dəlil", ar: { q: 2 }, az: null,
    core: [G.TOV, G.AYE, "üç|uc$|ucunu|ucu|cəm|cem|toplayan|ثلاث|ثلاثة|يجمع|جامعة|qism"],
    trig: T(["Üç tövhidi bir ayədə cəm edən ayə hansıdır", "Tövhidin üç qismini bir ayədə göstər"], ["Üç tevhidi bir ayette toplayan ayet"], ["دليل من الكتاب يجمع أقسام التوحيد الثلاثة في آية"]) },
  { id: "t3-peyqemberler-baximdan", t: 3, label: "Peyğəmbərlərin dəvət etdiyi baxımdan tövhidin qisimləri", ar: { q: 3 }, az: null,
    core: [G.TOV, "peyğəmbər|peyğəmbərlər|peygamber|rəsul|resul|رسل|الرسل"], opt: [G.QISM, "dəvət|davet|دعت"],
    trig: T(["Peyğəmbərlərin dəvət etdiyi tövhid növləri", "Peyğəmbərlərin çağırdığı baxımdan tövhidin qisimləri"], ["Peygamberlerin davet ettiği tevhid çeşitleri"], ["أقسام التوحيد من حيث ما دعت إليه الرسل"]) },
  { id: "t3-merife-isbat-terif", t: 3, label: "Mərifət və isbat tövhidinin tərifi", ar: { q: 4 }, az: null,
    core: [G.MEREFE, G.ISBAT], opt: [G.TOV, G.DEF], not: [G.SEBEB, G.RUB, G.SIF, G.QISM, G.ELMI],
    trig: T(["Mərifət və isbat tövhidi nədir", "Mərifət və isbat tövhidinin tərifi"], ["Marifet ve isbat tevhidi nedir"], ["عرف توحيد المعرفة والإثبات", "ما هو توحيد المعرفة والإثبات"]) },
  { id: "t3-niye-bir-ad", t: 3, label: "Rübubiyyət və ad-sifət tövhidinə niyə eyni ad verilib", ar: { q: 5 }, az: null,
    core: [G.RUB, G.SIF, "eyni|bir ad|mərifət|marifet|معرفة|واحدا|واحد"], opt: [G.SEBEB, G.ISBAT, G.MEREFE],
    trig: T(["Rübubiyyət və ad-sifət tövhidinə niyə mərifət və isbat tövhidi deyilir", "Rübubiyyət tövhidi və ad sifət tövhidi niyə eyni adla adlanır"], [], ["لماذا يسمى توحيدا الربوبية والأسماء والصفات اسما واحدا"]) },
  { id: "t3-adlanma-sebebi", t: 3, label: "Mərifət və isbat tövhidinin bu adla adlanma səbəbi", ar: { q: 6 }, az: null,
    core: [G.MEREFE, G.ISBAT, G.SEBEB], not: [G.RUB, G.SIF, G.ELMI],
    trig: T(["Mərifət və isbat tövhidi niyə bu adla adlanır", "Mərifət və isbat tövhidinin adlanma səbəbi"], ["Marifet ve isbat tevhidi neden bu adla anılır"], ["ما سبب تسمية توحيد المعرفة والإثبات بهذا الاسم"]) },
  { id: "t3-merife-bolgusu", t: 3, label: "Mərifət və isbat bölgüsünə görə tövhidin qisimləri", ar: { q: 7 }, az: null,
    core: [G.MEREFE, "bölgü|bolgu|təqsim|taksim|تقسيم|elmi|əməli|ameli|talebi|tələbi|طلبي|عملي"], opt: [G.QISM, G.ISBAT, G.TOV], not: [G.RUB],
    trig: T(["Mərifət və isbat bölgüsünə görə tövhidin qisimləri", "Mərifət və isbat təqsiminə görə tövhid neçə qismdir"], ["Marifet ve isbat taksimine göre tevhid çeşitleri"], ["أقسام التوحيد وفق تقسيم المعرفة والإثبات"]) },
  { id: "t3-elmi-xeberi", t: 3, label: "Elmi-xəbəri tövhid niyə mərifət və isbat tövhididir", ar: { q: 8 }, az: null,
    core: [G.ELMI, G.XEBERI], opt: [G.MEREFE, G.ISBAT, G.TOV],
    trig: T(["Elmi-xəbəri tövhid nədir", "Elmi xəbəri tövhid niyə mərifət və isbat tövhididir"], ["İlmî haberî tevhid nedir"], ["علل التوحيد العلمي الخبري هو توحيد المعرفة والإثبات"]) },
  { id: "t3-merife-novleri", t: 3, label: "Mərifət və isbat tövhidinin növləri", ar: { q: 9 }, az: null,
    core: [G.MEREFE, G.ISBAT, G.QISM], not: ["bölgü|bolgu|təqsim|taksim|تقسيم|elmi|əməli|ameli|talebi|tələbi|طلبي|عملي"],
    trig: T(["Mərifət və isbat tövhidinin növləri", "Mərifət və isbat tövhidi neçə qismə bölünür"], ["Marifet ve isbat tevhidinin çeşitleri"], ["عدد أنواع توحيد المعرفة والإثبات"]) },

  // ---------------- 4-cü mövzu ----------------
  { id: "t4-rububiyyet-terif", t: 4, label: "Rübubiyyət tövhidinin tərifi", ar: { q: 1 }, az: null,
    core: [G.RUB, G.DEF], not: [G.SIRK, G.QISM, "xüsusiyyət|xususiyyet|xassə|خصائص|خصائصه", G.DELIL, "gerçəkləşd|gerceklesd|gerçəkləş|lazım|vacib|يلزم|محقق|şərt", "metod|menhec|mənhəc|üsul|uslub|üslub|منهج|مناهج|بيان|bəyan|beyan", G.MEREFE],
    trig: T(["Rübubiyyət tövhidi nədir", "Rübubiyyət tövhidinin tərifi", "Rübubiyyət nə deməkdir"], ["Rububiyet tevhidi nedir", "Rububiyet ne demek"], ["ما هو توحيد الربوبية", "عرف توحيد الربوبية"]) },
  { id: "t4-rububiyyet-delil", t: 4, label: "Rübubiyyətə Quran və sünnədən dəlil", ar: { q: 2 }, az: null,
    core: [G.RUB, G.DELIL], not: [G.SIRK, G.QISM],
    trig: T(["Rübubiyyət tövhidinə Quran və sünnədən dəlil", "Allahın rübubiyyətinə dəlil nədir"], ["Rububiyet tevhidine Kur'an ve sünnetten delil"], ["دليل من الكتاب والسنة على ربوبية الله"]) },
  { id: "t4-quran-metodlari", t: 4, label: "Quranın rübubiyyət tövhidini bəyan etmə metodları", ar: { q: 3 }, az: null,
    core: [G.RUB, "metod|menhec|mənhəc|üsul|uslub|üslub|منهج|مناهج|اساليب|أساليب|bəyan|beyan|بيان|açıkla|acikla"], not: [G.SIRK],
    trig: T(["Quran rübubiyyət tövhidini necə bəyan edir", "Quranın rübubiyyət tövhidini bəyan etmə metodları"], ["Kur'an rububiyet tevhidini nasıl açıklar"], ["مناهج القرآن الكريم في بيان توحيد الربوبية"]) },

  // ---------------- 5-ci mövzu ----------------
  { id: "t5-sirk-terif", t: 5, label: "Şirkin lüğəvi və şəri tərifi", ar: { q: 1 }, az: { q: 1 },
    core: [G.SIRK, "lüğəvi|lugevi|şəri|şeri|dil|tərif|terif|tanım|tanim|nədir|nedir|demək|demek|mənası|menasi|anlam|تعريف|عرف|معنى|ما$|هو$|الشرع|اللغة"],
    not: [G.RUB, G.BOYUK, G.KICIK, G.QISM, G.HOKM, G.TETIL, G.TEMSIL, "haqq$|haqqı|haqqi|حق"],
    trig: T(["Şirk nədir", "Şirkin lüğəvi və şəri mənası nədir", "Şirkin tərifi"], ["Şirk nedir", "Şirkin tanımı"], ["ما هو الشرك", "عرف الشرك في اللغة والشرع"]) },
  { id: "t5-allah-haqqi", t: 5, label: "Allahın haqqı nədir?", ar: { q: 2 }, az: { q: 2 },
    core: [G.ALLAH, "haqqı|haqqi|haqq$|hakkı|حق"], opt: [G.DEF], not: [G.SIRK, G.DELIL, "ad$|adı|adları|sifət|sifet"],
    trig: T(["Allahın haqqı nədir", "Allahın haqqı nə deməkdir"], ["Allah'ın hakkı nedir"], ["ما هو حق الله"]) },
  { id: "t5-sirk-qismleri-tovhid", t: 5, label: "Tövhidin növlərinə nisbətdə şirkin qisimləri", amb: "sirk-qism", ar: { q: 3 }, az: { q: 3 },
    core: [G.SIRK, G.QISM], opt: [G.TOV, "nisbət|nisbet|نسبة"], not: [G.HOKM, G.RUB, G.BOYUK, G.TETIL, G.TEMSIL],
    trig: T(["Şirk neçə qismə bölünür", "Tövhidin növlərinə nisbətdə şirk neçə qismə bölünür", "Şirkin növləri"], ["Şirk kaça ayrılır", "Şirkin çeşitleri"], ["عدد أقسام الشرك بالنسبة إلى أنواع التوحيد", "أقسام الشرك"]) },
  { id: "t5-sirk-qismleri-hokm", t: 5, label: "Hökmünə görə şirkin qisimləri", amb: "sirk-qism", ar: { q: 4 }, az: { q: 4 },
    core: [G.SIRK, G.QB], opt: [G.HOKM, G.BOYUK, G.KICIK], not: [G.RUB, G.TOV, G.TETIL, G.TEMSIL],
    trig: T(["Hökmünə görə şirk neçə qismə bölünür", "Böyük və kiçik şirk", "Şirk hökmünə görə neçə yerə bölünür"], ["Hükmüne göre şirk kaça ayrılır", "Büyük ve küçük şirk"], ["عدد أقسام الشرك بالنسبة إلى حكمه", "الشرك الأكبر والأصغر"]) },
  { id: "t5-boyuk-sirk-terif", t: 5, label: "Böyük şirkin tərifi", ar: { q: 5 }, az: { q: 5 },
    core: [G.BOYUK, G.SIRK, G.DEF], not: [G.HOKM, G.QISM, G.RUB],
    trig: T(["Böyük şirk nədir", "Böyük şirkin tərifi", "Böyük şirk nə deməkdir"], ["Büyük şirk nedir", "Şirki ekber nedir"], ["عرف الشرك الأكبر", "ما هو الشرك الأكبر"]) },
  { id: "t5-boyuk-sirk-hokm", t: 5, label: "Böyük şirkin hökmləri", ar: { q: 6 }, az: { q: 6 },
    core: [G.SIRK, G.HOKM], opt: [G.BOYUK, "nəticə|netice|cəza|ceza|sonuc"], not: [G.QISM],
    trig: T(["Böyük şirkin hökmləri", "Böyük şirkin hökmləri nələrdir", "Böyük şirk edənin hökmü"], ["Büyük şirkin hükümleri", "Büyük şirkin hükmü nedir"], ["عدد أحكام الشرك الأكبر", "حكم الشرك الأكبر"]) },
  { id: "t5-rububiyyetde-sirk", t: 5, label: "Rübubiyyətdə şirkin tərifi", ar: { q: 7 }, az: { q: 7 },
    core: [G.SIRK, G.RUB], not: [G.QISM, "xüsusiyyət|xususiyyet|xassə|خصائص", G.TETIL, G.TEMSIL, G.HOKM],
    trig: T(["Rübubiyyətdə şirk nədir", "Rübubiyyət tövhidində şirk", "Rübubiyyətdə şirkin tərifi"], ["Rububiyette şirk nedir"], ["عرف الشرك في الربوبية", "ما هو الشرك في الربوبية"]) },
  { id: "t5-rububiyyet-xususiyyetleri", t: 5, label: "Rübubiyyətin xüsusiyyətləri", ar: { q: 8 }, az: { q: 8 },
    core: [G.RUB, "xüsusiyyət|xususiyyet|xassə|xasse|خصائص|خصائصه|özəllik|ozellik"],
    trig: T(["Rübubiyyətin xüsusiyyətləri", "Rübubiyyətin xüsusiyyətlərini sadala", "Rübubiyyət tövhidinin xassələri"], ["Rububiyetin özellikleri"], ["عدد خصائص الربوبية"]) },
  { id: "t5-rububiyyet-sirk-novleri", t: 5, label: "Rübubiyyətdə şirkin növləri", ar: { q: 9 }, az: { q: 9 },
    core: [G.SIRK, G.RUB, G.QISM],
    trig: T(["Rübubiyyət şirkinin növləri", "Rübubiyyətdə şirkin növləri nələrdir", "Rübubiyyət şirki neçə qismə bölünür"], ["Rububiyette şirkin çeşitleri"], ["عدد أنواع الشرك في الربوبية"]) },
  { id: "t5-tetil-sirki", t: 5, label: "Tətil şirki", ar: { q: 9, from: "النوع الأول: شرك التعطيل", to: "النوع الثاني: شرك التمثيل" }, az: { q: 9, from: "Birinci növ: Tətil şirki", to: "İkinci növ: Təmsil şirki" },
    core: [G.TETIL, G.SIRK],
    trig: T(["Tətil şirki nədir", "Tətil şirkinin tərifi və nümunələri", "Tətil şirki nə deməkdir"], ["Tatil şirki nedir", "Ta'til şirki nedir"], ["ما هو شرك التعطيل", "شرك التعطيل"]) },
  { id: "t5-temsil-sirki", t: 5, label: "Təmsil şirki", ar: { q: 9, from: "النوع الثاني: شرك التمثيل" }, az: { q: 9, from: "İkinci növ: Təmsil şirki" },
    core: [G.TEMSIL, G.SIRK],
    trig: T(["Təmsil şirki nədir", "Təmsil şirkinin tərifi və nümunələri", "Təmsil şirki nə deməkdir"], ["Temsil şirki nedir"], ["ما هو شرك التمثيل", "شرك التمثيل"]) },

  // ---------------- 6-cı mövzu ----------------
  { id: "t6-ad-sifet-tovhidi", t: 6, label: "Allahın ad və sifətləri tövhidinin tərifi", ar: { q: 1 }, az: { q: 1 },
    core: [G.TOV, G.SIF], opt: [G.ESMA, G.DEF], not: [G.DELIL, G.QAYDA, G.USUL, G.FITRI, G.AQLI, G.NEQLI, G.SIRK],
    trig: T(["Allahın ad və sifətləri tövhidi nədir", "Əsma və sifat tövhidi nədir", "Ad və sifətlər tövhidinin tərifi"], ["Esma ve sıfat tevhidi nedir", "Allah'ın isim ve sıfatları tevhidi nedir"], ["عرف توحيد الأسماء والصفات", "ما هو توحيد الأسماء والصفات"]) },
  { id: "t6-usullar", t: 6, label: "Ad və sifətlər tövhidinin əsasları (əhli-sünnəyə görə)", ar: { q: 2 }, az: { q: 2 },
    core: [G.SIF, G.USUL], opt: [G.TOV, G.ESMA, "sünnə|sunne|əhli|ehli|السنة|أهل"],
    trig: T(["Əhli-sünnənin ad və sifətlər tövhidində əsaslandığı prinsiplər", "Ad və sifətlər tövhidi hansı əsaslar üzərində qurulub"], ["Ehl-i sünnetin isim ve sıfat tevhidindeki esasları"], ["ينبني توحيد الأسماء والصفات عند أهل السنة والجماعة على أصول"]) },

  // ---------------- 7-ci mövzu ----------------
  { id: "t7-delil-novleri", t: 7, label: "Ad və sifətlər tövhidinə dair dəlil növləri", ar: { q: 1 }, az: { q: 1 },
    core: [G.SIF, G.DELIL], opt: [G.TOV, G.ESMA, G.QISM], not: [G.FITRI, G.AQLI, G.NEQLI, G.SERI, G.QAYDA],
    trig: T(["Ad və sifətlər tövhidinə dair dəlillərin növləri", "Allahın ad və sifətlərinə dəlillər neçə növdür", "Ad və sifətlər tövhidinin dəlilləri"], ["İsim ve sıfat tevhidinin delilleri"], ["أنواع الأدلة على توحيد الأسماء والصفات"]) },
  { id: "t7-fitri-delil", t: 7, label: "Ad və sifətlər tövhidinə fitri dəlil", amb: "fitri", ar: { q: 1, from: "النوع الأول: الدليل الفطري", to: "النوع الثاني: الدليل العقلي" }, az: { q: 1, from: "Birinci növ: Fitri dəlil", to: "İkinci növ: Əqli dəlil" },
    core: [G.FITRI, G.DELIL], opt: [G.SIF, G.ESMA, G.TOV, "hər uşaq|yəhudi|nəsrani|məcusi"],
    trig: T(["Fitri dəlil nədir", "Ad və sifətlər tövhidinə fitri dəlil", "Fitri dəlil"], ["Fıtrî delil nedir"], ["الدليل الفطري على توحيد الأسماء والصفات", "الدليل الفطري"]) },
  { id: "t7-aqli-delil", t: 7, label: "Ad və sifətlər tövhidinə əqli dəlil", amb: "aqli", ar: { q: 1, from: "النوع الثاني: الدليل العقلي", to: "النوع الثالث: الدليل النقلي" }, az: { q: 1, from: "İkinci növ: Əqli dəlil", to: "Üçüncü növ: Nəqli dəlil" },
    core: [G.AQLI, G.DELIL], opt: [G.SIF, G.ESMA, G.TOV],
    trig: T(["Əqli dəlil nədir", "Ad və sifətlər tövhidinə əqli dəlil"], ["Aklî delil nedir"], ["الدليل العقلي على توحيد الأسماء والصفات", "الدليل العقلي"]) },
  { id: "t7-naqli-delil", t: 7, label: "Ad və sifətlər tövhidinə nəqli dəlil", ar: { q: 1, from: "النوع الثالث: الدليل النقلي" }, az: { q: 1, from: "Üçüncü növ: Nəqli dəlil" },
    core: [G.NEQLI, G.DELIL], opt: [G.SIF, G.ESMA, G.TOV, "quran|sünnə"], not: [G.AQLI],
    trig: T(["Nəqli dəlil nədir", "Allahın sifətlərinə nəqli dəlil", "Allahın sifətlərinə dair nəqli dəlil Quran və sünnə"], ["Naklî delil nedir"], ["الدليل النقلي على توحيد الأسماء والصفات", "الدليل النقلي"]) },

  // ---------------- 8-ci mövzu ----------------
  { id: "t8-adlar-qaydalar", t: 8, label: "Əhli-sünnənin Allahın adları ilə bağlı qaydaları", ar: { q: 1 }, az: { q: 1 }, partial: true,
    core: [G.ESMA, G.QAYDA], opt: ["sünnə|sunne|əhli|ehli|السنة|أهل"], not: [G.SIF, G.GOZEL, G.TEVQIF, "məhdud|mehdud|محصور|حصر", "mütəəddi|muteaddi|متعد", "dəlalət|delalet|دلالة"],
    trig: T(["Əhli-sünnənin Allahın adları ilə bağlı qaydaları", "Allahın adları ilə bağlı qaydalar", "Allahın adlarının qaydaları nələrdir"], ["Ehl-i sünnetin Allah'ın isimleriyle ilgili kaideleri"], ["قواعد أهل السنة والجماعة في أسماء الله", "عدد قواعد أهل السنة في أسماء الله"]) },
  { id: "t8-q1-hamisi-gozel", t: 8, label: "Birinci qayda: Allahın bütün adları gözəldir", ar: { q: 1, from: "القاعدة الأولى", to: "القاعدة الثانية" }, az: { q: 1, from: "Birinci qayda", to: "İkinci qayda" },
    core: [G.ESMA, G.GOZEL, "bütün|butun|hamısı|hamisi|hepsi|kullar|كلها|كل|qayda"], not: [G.SEBEB],
    trig: T(["Allahın bütün adları gözəldir", "Allahın adlarının hamısı gözəldir dəlil", "Əsmaül-hüsna qaydası"], ["Allah'ın bütün isimleri güzeldir"], ["أسماء الله كلها حسنى", "ما الدليل على أن أسماء الله كلها حسنى"]) },
  { id: "t8-q1-niye-gozel", t: 8, label: "Allahın adları nə üçün gözəldir?", ar: { q: 1, from: "لماذا كانت أسماء الله" , to: "القاعدة الثانية" }, az: { q: 1, from: "Allahın bütün adları nə üçün gözəldir?", to: "İkinci qayda" },
    core: [G.ESMA, G.GOZEL, G.SEBEB], 
    trig: T(["Allahın adları nə üçün gözəldir", "Allahın adları niyə gözəldir", "Allahın adlarının gözəl olmasının səbəbi"], ["Allah'ın isimleri neden güzeldir"], ["لماذا كانت أسماء الله كلها حسنى"]) },
  { id: "t8-q2-mehdud-deyil", t: 8, label: "İkinci qayda: Allahın adları müəyyən sayla məhdudlaşdırılmayıb", ar: { q: 1, from: "القاعدة الثانية", to: "القاعدة الثالثة" }, az: { q: 1, from: "İkinci qayda", to: "Üçüncü qayda" },
    core: [G.ESMA, "məhdud|mehdud|məhsur|mehsur|محصور|محصورة|حصر|sayla|sınırlı|sinirli"], opt: [G.QAYDA, "deyil|degil|olmaz|bitmir"],
    trig: T(["Allahın adları 99 ilə məhduddurmu", "Allahın adları müəyyən sayla məhdud deyil", "Allahın adları 99 adla məhdudlaşmır dəlil"], ["Allah'ın isimleri 99 ile sınırlı mı"], ["أسماء الله غير محصورة بعدد معين", "هل أسماء الله محصورة في تسعة وتسعين"]) },
  { id: "t8-q3-tevqifi", t: 8, label: "Üçüncü qayda: Allahın adları təvqifidir", ar: { q: 1, from: "القاعدة الثالثة", to: "القاعدة الرابعة" }, az: { q: 1, from: "Üçüncü qayda", to: null },
    core: [G.ESMA, G.TEVQIF], 
    trig: T(["Allahın adları təvqifidir nə deməkdir", "Allahın adlarının təvqifi olması nə deməkdir", "Allahın adları təvqifidir dəlili"], ["Allah'ın isimleri tevkifidir ne demek"], ["أسماء الله توقيفية", "ما معنى أن أسماء الله توقيفية"]) },
  { id: "t8-q4-muteaddi", t: 8, label: "Dördüncü qayda: Allahın adları keçişli və keçişsiz sifətə dəlalət edir", ar: { q: 1, from: "القاعدة الرابعة", to: "القاعدة الخامسة" }, az: null,
    core: [G.ESMA, "mütəəddi|muteaddi|متعد|متعدي|keçişli|keçişsiz|kecisli|kecissiz|geçişli|geçişsiz"],
    trig: T(["Allahın adları keçişli və keçişsiz sifətə dəlalət edir", "Allahın adları mütəəddi sifətə dəlalət edir"], ["Allah'ın isimleri geçişli ve geçişsiz sıfata delalet eder"], ["أسماء الله تدل على وصف متعد وغير متعد"]) },
  { id: "t8-q5-delalet", t: 8, label: "Beşinci qayda: adların zata və sifətlərə mütabiqət, təzəmmün və iltizam dəlaləti", ar: { q: 1, from: "القاعدة الخامسة" }, az: null,
    core: [G.ESMA, "dəlalət|delalet|dəlalət|دلالة|mütabiqət|mutabiqet|مطابقة|təzəmmün|tezemmun|تضمن|iltizam|التزام"],
    trig: T(["Allahın adlarının mütabiqət təzəmmün və iltizam dəlaləti", "Allahın adlarının mütabiqət dəlaləti nədir"], ["Allah'ın isimlerinin mutabakat tazammun ve iltizam delaleti"], ["دلالة أسماء الله على ذاته وصفاته بالمطابقة والتضمن والالتزام"]) },

  // ---------------- 9-cu mövzu ----------------
  { id: "t9-sifetler-qaydalar", t: 9, label: "Əhli-sünnənin Allahın sifətləri ilə bağlı qaydaları", ar: { q: 1 }, az: null,
    core: [G.SIF, G.QAYDA], opt: ["sünnə|sunne|əhli|ehli|السنة|أهل", G.ALLAH], not: [G.ESMA, G.TEVQIF, G.LEYSE, G.MUCMEL, "ittifaq|اتفاق", "söz|soz|قول"],
    trig: T(["Əhli-sünnənin Allahın sifətləri ilə bağlı qaydaları", "Allahın sifətləri ilə bağlı qaydalar", "Sifətlər barədə qaydalar nələrdir"], ["Ehl-i sünnetin Allah'ın sıfatlarıyla ilgili kaideleri"], ["قواعد أهل السنة والجماعة في صفات الله", "عدد قواعد أهل السنة في صفات الله"]) },
  { id: "t9-q1-tevqifi", t: 9, label: "Birinci qayda: Allahın sifətləri təvqifidir", ar: { q: 1, from: "القاعدة الأولى", to: "القاعدة الثانية" }, az: null,
    core: [G.SIF, G.TEVQIF], not: [G.ESMA],
    trig: T(["Allahın sifətləri təvqifidir nə deməkdir", "Sifətlərin təvqifi olması nə deməkdir"], ["Allah'ın sıfatları tevkifidir ne demek"], ["صفات الله توقيفية"]) },
  { id: "t9-q2-leyse", t: 9, label: "İkinci qayda: Allaha bənzər heç nə yoxdur", ar: { q: 1, from: "القاعدة الثانية", to: "القاعدة الثالثة" }, az: null,
    core: [G.LEYSE + "|bənzəri yoxdur|benzeri yok|benzeri yoktur|misli yoxdur|misli yoktur"], opt: [G.ALLAH, "qayda|sifət|sifet|tənzih|tenzih|nədir|nedir|demək|demek|mənası|menasi|ayə|aye|تنزيه|معنى|ما$"],
    trig: T(["Leysə kəmislihi şey nə deməkdir", "Allahın bənzəri yoxdur", "Allahın misli yoxdur nə deməkdir"], ["Leyse kemislihi şey ne demek"], ["ليس كمثله شيء", "الله ليس كمثله شيء"]) },
  { id: "t9-q3-nefy-isbat", t: 9, label: "Üçüncü qayda: ümumi inkar, təfsilatlı isbat", ar: { q: 1, from: "القاعدة الثالثة", to: "القاعدة الرابعة" }, az: null,
    core: [G.MUCMEL, "nəfy|nefy|inkar|isbat|إثبات|نفي|ispat"],
    trig: T(["Mücməl nəfy müfəssəl isbat qaydası", "Allahın sifətlərində ümumi inkar və təfsilatlı isbat nədir"], ["Mücmel nefy mufassal isbat kaidesi"], ["النفي المجمل والإثبات المفصل"]) },
  { id: "t9-q4-ittifaq", t: 9, label: "Dördüncü qayda: adların uyğunluğu bənzətmə deyil", ar: { q: 1, from: "القاعدة الرابعة", to: "القاعدة الخامسة" }, az: null,
    core: ["ittifaq|اتفاق|ittifaqı", "müsəmmə|musemma|müsəmməyeyn|musemmeyn|مسميين|المسميين|مسميات|المسميات"],
    trig: T(["Müsəmmaların ittifaqı bənzətmə deyil qaydası", "Müsəmmaların ittifaqı bənzətmə demək deyil"], ["Müsemmaların ittifakı teşbih değildir"], ["اتفاق المسميين ليس هو التمثيل المنفي"]) },
  { id: "t9-q5-zat-kimi", t: 9, label: "Beşinci qayda: sifətlərdə söz zatda sözə bənzəyir", ar: { q: 1, from: "القاعدة الخامسة", to: "القاعدة السادسة" }, az: null,
    core: [G.SIF, "zat$|zata|zatda|zatı|ذات", "söz|soz|qövl|قول|kimidir|كالقول"], not: [G.ZATI],
    trig: T(["Sifətlər haqqında söz zat haqqında söz kimidir", "Sifətlərdə söz zatda söz kimidir qaydası"], [], ["القول في الصفات كالقول في الذات"]) },
  { id: "t9-q6-bezi-sifet", t: 9, label: "Altıncı qayda: bəzi sifətlər haqqında söz digərləri kimidir", ar: { q: 1, from: "القاعدة السادسة" }, az: null,
    core: [G.SIF, "bəzi|bezi|بعض|digər|diger|الآخر", "söz|soz|qövl|قول|kimidir|كالقول"],
    trig: T(["Bəzi sifətlər haqqında söz digər sifətlər kimidir", "Sifətlərin bir qismi haqqında söz digərləri kimidir"], [], ["القول في بعض الصفات كالقول في بعضها الآخر"]) },

  // ---------------- 10-cu mövzu ----------------
  { id: "t10-ihsa-niye", t: 10, label: "Müsəlmanlar niyə Allahın gözəl adlarını ihsa etməyə əhəmiyyət verir?", ar: { q: 1 }, az: null,
    core: [G.IHSA, "niyə|niye|nə üçün|why|əhəmiyyət|ehemmiyet|لماذا|عني|علل"], opt: [G.ESMA],
    trig: T(["Müsəlmanlar niyə Allahın adlarını ihsa etməyə əhəmiyyət verir", "Allahın adlarını ihsa etmək niyə vacibdir"], [], ["علل عني المسلمون بإحصاء أسماء الله الحسنى"]) },
  { id: "t10-ihsa-mertebeleri", t: 10, label: "Allahın gözəl adlarını ihsa etmənin mərtəbələri", ar: { q: 2 }, az: null,
    core: [G.IHSA, "mərtəbə|merteb|mertebe|mərhələ|مراتب|مرتبة|səviyyə"],
    trig: T(["Allahın adlarını ihsa etmənin mərtəbələri", "Allahın gözəl adlarını ihsa etmə mərtəbələri nələrdir"], [], ["عدد مراتب إحصاء أسماء الله الحسنى"]) },
  { id: "t10-ihsa-hedis", t: 10, label: "«Kim onları ihsa edərsə cənnətə girər» hədisində ihsanın mənası", ar: { q: 3 }, az: null,
    core: [G.IHSA, "hədis|hadis|cənnət|cennet|جنة|الجنة|أحصاها|احصاها|mənası|menasi|demək|demek|معنى"],
    trig: T(["Kim onları ihsa edərsə cənnətə girər hədisində ihsa nə deməkdir", "Allahın 99 adını ihsa edən cənnətə girər mənası"], [], ["ما معنى الإحصاء في قول النبي من أحصاها دخل الجنة"]) },
  { id: "t10-ihsa-seadet", t: 10, label: "İhsa niyə səadətin və nicatın mərkəzidir?", ar: { q: 4 }, az: null,
    core: [G.IHSA, "səadət|seadet|nicat|necat|nəcat|fəlah|felah|سعادة|فلاح|نجاة"],
    trig: T(["İhsa niyə səadətin və nicatın mədarıdır", "Allahın adlarını ihsa etmək niyə səadətin əsasıdır"], [], ["علل الإحصاء الذي أراده النبي هو قطب السعادة"]) },
  { id: "t10-dua-mertebeleri", t: 10, label: "Duanın növləri (mərtəbələri)", ar: { q: 5 }, az: null,
    core: [G.DUA, G.QISM + "|mərtəbə|merteb|mertebe|مراتب"], not: [G.IHSA],
    trig: T(["Duanın növləri nələrdir", "Duanın mərtəbələri", "Dua neçə qismə bölünür"], ["Duanın çeşitleri nelerdir"], ["عدد مراتب الدعاء", "أنواع الدعاء"]) },

  // ---------------- 11-ci mövzu ----------------
  { id: "t11-sifet-lugevi", t: 11, label: "«Sifət» sözünün lüğəvi mənası", ar: { q: 1 }, az: { q: 1 },
    core: [G.SIF, "lüğəvi|lugevi|lüğət|lugat|sözlük|sozluk|dil$|dilcə|لغة|لغه|etimoloji|vəsf|vesf"],
    trig: T(["Sifət sözünün lüğəvi mənası nədir", "Sifət sözü lüğətdə nə deməkdir"], ["Sıfat kelimesinin sözlük anlamı nedir"], ["عرف الصفة لغة", "ما معنى الصفة في اللغة"]) },
  { id: "t11-sifet-terif", t: 11, label: "Əhli-sünnəyə görə sifətin terminoloji tərifi", ar: { q: 2 }, az: { q: 2 },
    core: [G.SIF, "istilah|termin|terminoloji|اصطلاح|اصطلاحا|əhli|ehli|sünnə|sunne|السنة|أهل|tərif|terif|تعريف|عرف"], not: ["lüğəvi|lugevi|لغة|لغه", G.QISM, G.QAYDA, G.FITRI, G.TOV, G.DELIL, G.TESIR, "bölgü|bolgu"],
    trig: T(["Əhli-sünnəyə görə sifətin terminoloji tərifi nədir", "Sifətin əhli-sünnə yanında tərifi", "Allahın sifətlərinin tərifi nədir əhli sünnə"], ["Ehl-i sünnete göre sıfatın terimsel tanımı"], ["عرف الصفة عند أهل السنة والجماعة"]) },
  { id: "t11-sifet-tesnif", t: 11, label: "Allahın sifətlərinin təsnifi (bütün bölgülər)", ar: { q: 3 }, az: { q: 3, to: "Allahın sifətlərinə iman etməyin təsirləri" },
    core: [G.SIF, G.QISM + "|təsnif|tesnif|bölgü|bolgu|sınıf|sinif|sınıflandır|تصنيف"], opt: [G.ALLAH], not: ["təsdiq|tesdiq|inkar|nəfy|nefy|إثبات|اثبات|نفي|olumlu|olumsuz", "zat$|zata|zatına|irade|iradə|مشيئة|ذات", G.TEVQIF, G.ZATI, G.FEILI, G.QAYDA, G.ESMA, G.TOV, G.SIRK, G.DELIL, G.SUBUTI, G.MENFI, G.TESIR, "sübut|subut|ثبوت"],
    trig: T(["Allahın sifətləri hansı cür təsnif edilir", "Allahın sifətləri neçə qismə bölünür", "Sifətlərin bölgüsü"], ["Allah'ın sıfatları nasıl sınıflandırılır", "Allah'ın sıfatları kaça ayrılır"], ["عدد أقسام الصفات التي صنفها أهل السنة والجماعة", "أقسام صفات الله"]) },
  { id: "t11-bolgu1-tesdiq-inkar", t: 11, label: "Birinci bölgü: təsdiq və inkar baxımından sifətlər", ar: { q: 3, from: "(1) أقسام صفات الله تعالى باعتبار ورودها", to: "(٢) أقسام صفات الله تعالى باعتبار أدلة" }, az: { q: 3, from: "Birinci bölgü", to: "İkinci bölgü" },
    core: [G.SIF, "təsdiq|tesdiq|inkar|nəfy|nefy|olumlu|olumsuz|إثبات|اثبات|نفي|ثبوتية|منفية"], not: [G.MUCMEL],
    trig: T(["Sifətlərin təsdiq və inkar baxımından bölgüsü", "Allahın təsdiq edilən və inkar edilən sifətləri"], ["Sıfatların olumlu ve olumsuz olarak ayrımı"], ["أقسام صفات الله باعتبار ورودها نفيا وإثباتا"]) },
  { id: "t11-sifet-subuti", t: 11, label: "Təsdiq edilən (sübuti) sifətlər", ar: { q: 3, from: "١. صفات ثبوتية", to: "٢. صفات منفية" }, az: { q: 3, from: "1. Təsdiq edilən sifətlər", to: "2. İnkar edilən sifətlər" },
    core: [G.SIF, "sübuti|subuti|təsdiq edilən|tesdiq edilen|ثبوتية|ثبوتي|isbati|müsbət|musbet"],
    trig: T(["Sübuti sifətlər nədir", "Allahın təsdiq edilən sifətləri hansılardır", "Allahın sübuti sifətləri"], ["Subuti sıfatlar nedir"], ["الصفات الثبوتية", "ما هي الصفات الثبوتية لله"]) },
  { id: "t11-sifet-menfi", t: 11, label: "İnkar edilən (mənfi) sifətlər", ar: { q: 3, from: "٢. صفات منفية", to: "(٢) أقسام صفات الله تعالى باعتبار أدلة" }, az: { q: 3, from: "2. İnkar edilən sifətlər", to: "İkinci bölgü" },
    core: [G.SIF, "mənfi|menfi|inkar edilən|inkar edilen|منفية|منفي|salbi|səlbi|nəfy|nefy"], not: [G.MUCMEL],
    trig: T(["Mənfi sifətlər nədir", "Allahdan inkar edilən sifətlər hansılardır", "Allahdan nəfy olunan sifətlər"], ["Menfi sıfatlar nedir", "Allah'tan nefyedilen sıfatlar"], ["الصفات المنفية", "ما هي الصفات المنفية عن الله"]) },
  { id: "t11-bolgu2-subut", t: 11, label: "İkinci bölgü: sifətin sübut olunması baxımından (əqli-nəqli / yalnız nəqli)", ar: { q: 3, from: "(٢) أقسام صفات الله تعالى باعتبار أدلة", to: "(۳) أقسام صفات الله تعالى باعتبار تعلقها" }, az: { q: 3, from: "İkinci bölgü", to: "Üçüncü bölgü" },
    core: [G.SIF, "sübut|subut|ثبوت|əqli|akli|nəqli|nakli|عقلية|نقلية|خبرية|səm'i|semi|سمعية"], opt: [G.DELIL, "sabit|bilinən|bilinen|ayrım|ayrim"], not: [G.FITRI],
    trig: T(["Sifətlərin sübut olunması baxımından bölgüsü", "Əqli və nəqli dəlillə sabit olan sifətlər", "Yalnız nəqli dəlillə bilinən sifətlər"], ["Sıfatların sübut yönünden ayrımı"], ["أقسام صفات الله باعتبار أدلة ثبوتها", "صفات سمعية عقلية وسمعية خبرية"]) },
  { id: "t11-bolgu3-zat-irade", t: 11, label: "Üçüncü bölgü: Allahın zatına və iradəsinə münasibəti baxımından sifətlər", ar: { q: 3, from: "(۳) أقسام صفات الله تعالى باعتبار تعلقها" }, az: { q: 3, from: "Üçüncü bölgü", to: "Allahın sifətlərinə iman etməyin təsirləri" },
    core: [G.SIF, "zat$|zata|zatına|zatinə|irade|iradə|iradəsi|مشيئة|ذات|ذاته"], not: [G.ZATI, G.FEILI],
    trig: T(["Sifətlərin Allahın zatına və iradəsinə münasibəti baxımından bölgüsü", "Allahın sifətləri zatına və iradəsinə görə neçə yerə bölünür"], ["Sıfatların zata ve iradeye göre ayrımı"], ["أقسام صفات الله باعتبار تعلقها بذات الله ومشيئته"]) },
  { id: "t11-zati-sifetler", t: 11, label: "Zati sifətlər", ar: { q: 3, from: "١. صفات ذاتية: هي", to: "٢. صفات فعلية" }, az: { q: 3, from: "1. Zati sifətlər", to: "2. Feili sifətlər" },
    core: [G.ZATI, G.SIF], not: [G.FEILI],
    trig: T(["Zati sifətlər nədir", "Allahın zati sifətləri hansılardır"], ["Zâtî sıfatlar nedir"], ["الصفات الذاتية", "ما هي الصفات الذاتية"]) },
  { id: "t11-feili-sifetler", t: 11, label: "Feili sifətlər", ar: { q: 3, from: "٢. صفات فعلية", to: "٣. صفات ذاتية فعلية" }, az: { q: 3, from: "2. Feili sifətlər", to: "3. Zati-feili sifətlər" },
    core: [G.FEILI, G.SIF], not: [G.ZATI],
    trig: T(["Feili sifətlər nədir", "Allahın feili sifətləri hansılardır"], ["Fiilî sıfatlar nedir"], ["الصفات الفعلية", "ما هي الصفات الفعلية"]) },
  { id: "t11-zati-feili-sifetler", t: 11, label: "Zati-feili sifətlər (kəlam sifəti)", ar: { q: 3, from: "٣. صفات ذاتية فعلية", to: "أفعال الله تعالى نوعان" }, az: { q: 3, from: "3. Zati-feili sifətlər", to: "Allahın felləri iki növdür" },
    core: [G.ZATI, G.FEILI, G.SIF],
    trig: T(["Zati-feili sifətlər nədir", "Allahın kəlam sifəti zati yoxsa feili", "Kəlam sifəti zati-feili sifətdir"], ["Zâtî-fiilî sıfatlar nedir"], ["الصفات الذاتية الفعلية", "صفة الكلام ذاتية فعلية"]) },
  { id: "t11-felleri-novleri", t: 11, label: "Allahın felləri: keçişsiz və keçişli", ar: { q: 3, from: "أفعال الله تعالى نوعان" }, az: { q: 3, from: "Allahın felləri iki növdür", to: "Allahın sifətlərinə iman etməyin təsirləri" },
    core: [G.FEL, G.KECIS + "|" + G.QISM], opt: [G.ALLAH], not: [G.ESMA],
    trig: T(["Allahın felləri neçə növdür", "Keçişsiz və keçişli fellər", "Allahın keçişli və keçişsiz felləri"], ["Allah'ın fiilleri kaç çeşittir"], ["أفعال الله تعالى نوعان لازمة ومتعدية", "الأفعال اللازمة والمتعدية"]) },
  { id: "t11-sifet-tesirleri", t: 11, label: "Allahın sifətlərinə iman etməyin təsirləri", ar: { q: 4 }, az: { q: 3, from: "Allahın sifətlərinə iman etməyin təsirləri", skipFrom: true, qText: "Allahın sifətlərinə iman etməyin təsirləri" },
    core: [G.SIF, G.TESIR], opt: [G.IMAN, G.ESMA, G.ALLAH],
    trig: T(["Allahın sifətlərinə iman etməyin təsirləri", "Allahın ad və sifətlərini bilməyin faydaları", "Allahın sifətlərini bilməyin təsiri"], ["Allah'ın sıfatlarına iman etmenin etkileri", "Allah'ın sıfatlarını bilmenin faydaları"], ["آثار الإيمان بصفات الله تعالى على العبد", "عدد آثار الإيمان بصفات الله"]) },
];
